hiero-ledger/hiero-consensus-node

- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenHandlersTest.java
This PR adds new tests for TokenHandlers.
* 100% line coverage.
* Note that this class contains entirely getter methods for the private fields. (In my mind we should look into a way for trivial methods like this to be excluded or counted as covered. Testing of these methods only improves reported coverage.)
Fixes #13160 
**Checklist**
> chore: TokenHandlers test coverage (#13160)

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
Cherry Pick of https://github.com/hashgraph/hedera-services/pull/12839 from 0.49 into 0.50
> fix: (cherry pick) Enhance purechecks for CryptoGetAccountBalanceHandler (#12839) into release 50

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/TokenServiceImplTest.java
> chore: Improve unit test coverage on TokenServiceImpl

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Cherry Pick of #12797 from 0.49 into 0.50
> fix: (cherry pick) feat: Enhance purechecks for CryptoCreateHandler (#12797) into release/0.50

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseCryptoHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/BaseCryptoHandlerTest.java
This PR adds new tests for BaseCryptoHandler. 
* 100% line coverage. 
* Note the protected method getStakedId is not currently used and was removed.
Fixes #13146 
**Checklist**
> chore: BaseCryptoHandler test coverage (#13146)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
closes #13198 
PR for develop: https://github.com/hashgraph/hedera-services/pull/13199
> fix: revert ces name

- hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/UtilHandlersTest.java
Add unit tests for UtilHandlers class
Fixes #13221
> chore: Implement unit tests for UtilHandlers class

- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlersTest.java
Add unit tests for ConsensusHandlers class
Fixes #13217
> chore: Implement unit tests for ConsensusHandlers class

- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ConsensusServiceImplTest.java
new test coverage for ConsensusServiceImpl
Fixes #13251
> chore: new test coverage for ConsensusServiceImpl

- hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/UtilPrngHandlerTest.java
increase UtilPrngHandler unit test coverage 
Fixes #13253
> chore: add unit test for UtilPrngHandler

- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageTest.java
increase consensus submit message handler code coverage
Fixes #13209
> chore: increase consensus submit message handler code coverage

- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/NetworkServiceImplTest.java
add NetworkServiceImpl test code coverage to 100%
Fixes #13290
> chore: add NetworkServiceImpl test code coverage to 100%

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/OpProvider.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenUnfreeze.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/SubmitModificationsOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/positive/SysDelSysUndelSpec.java
- Update `release/0.50` to use `submitModifiedWithFixedPayer()` with some privileged operations that will not have the expected statuses using a "civilian" payer account.
> fix: stabilize `SysDelSysUndelSpec`

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- add codecov token to GitHub workflows so that codecov can upload unit test data
Fixes #13282 
**Checklist**
> fix: add codecov token so that codecov can upload unit test data

- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteTest.java
Adds unit tests for FIleSystemUndeleteHandler. Brings coverage to 92%.
#13193 
**Checklist**
> chore: Added unit tests for FileSystemUndeleteHandler

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/platform/event/EventMigrationTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/report/EventStreamReport.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/report/EventStreamScanner.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/DetailedConsensusEvent.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/DetailedConsensusEventTest.java
> feat: remove `BaseEventHashedData` from `DetailedConsensusEvent`

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
- grantTokenKyc
- revokeTokenKyc
Suite | Tests | Signatures
-- | -- | --
GrantRevokeKycV1SecurityModelSuite | grantRevokeKycSpec | - transaction payer- contract Id- KYC key
https://github.com/hashgraph/hedera-services/issues/12725
Fixes #
https://github.com/hashgraph/hedera-services/issues/12725
> feat: Write tests for kyc operations

- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/DefaultPlatformContext.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/FileSystemManagerConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/FileSystemManagerFactory.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerFactoryImpl.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerImpl.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/NoOpRecycleBin.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerImplTest.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/platform/TestPlatformContextBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/CompareStatesCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateAddressBookStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiEventStorage.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditor.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileManagerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java
Description:
Tries to Cherry-pick, from develop:https://github.com/hashgraph/hedera-services/commit/aa96fc9091714fb2f2a0054fbc8ccbfd7e432bb3
> fix: revert recycle-bin store location (#13339)

- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenPauseHandlerTest.java
Adds unit tests for pureChecks and calculateFees. Increases coverage to 100%.
#13355 
**Checklist**
> chore: TokenPauseHandler increase unit test coverage

- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/schemas/InitialModServiceNetworkSchemaTest.java
add coverage to InitialModServiceNetworkSchema
Fixes #13294
> chore: add coverage to InitialModServiceNetworkSchema

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/StateSignatureTransaction.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/SwirldTransaction.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/Transaction.java
> feat: remove byte array from transaction

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/DefaultSavedStateController.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/nexus/DefaultLatestCompleteStateNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/DefaultStateSignatureCollector.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StateFileManagerTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSignatureCollectorTester.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AbstractStateSignatureCollectorTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AddIncompleteStateTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EarlySignaturesTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/OldCompleteStateEventuallyReleasedTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/PostconsensusSignaturesTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/RegisterStatesWithoutSignaturesTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesRestartTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/StateSignatureCollectorBuilder.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/nexus/SignedStateNexusTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssHandlerTests.java
> feat: misc platform cleanup

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/AbstractInOrderLinker.java
> fix: improved linker error log

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
Cherry-pick : https://github.com/hashgraph/hedera-services/pull/13416
Fixes https://github.com/hashgraph/hedera-services/issues/13379
Adds a missing check for record finalizer
> fix: (cherry-pick) Fix record for treasury update

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java
> fix: compiling in develop (bad merge)

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
Validating fungible token relations is expensive during transaction handling (lots of disk I/O).
Fixes #13452
**Checklist**
> perf: Warm up fungible token relations

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleNetworkContext.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerklePayerRecords.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleSpecialFiles.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/utils/ThingsToStrings.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriter.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/util/PrngLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerklePayerRecordsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleSpecialFilesTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/PrngSystemPrecompiledContractTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/util/UtilPrngTransitionLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/MiscUtilsTest.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
> feat: remove `hash.getValue()` usage from mono services code

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedMapUtils.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
closes #13491 
I have no idea what this code does. But I hit it with a hammer enough times and eventually the test started passing.
Example passing test: https://swirldslabs.slack.com/archives/C03EPH4CGG3/p1716495472994789
> chore: fix PTT

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHelperTest.java
Fixes #13202 
Improve code coverage for `StakingRewardHelper`
> chore: Improve code coverage

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSignatureWaiversImpl.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSignatureWaiversImplTest.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/FileSignatureWaivers.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2319Spec.java
Waive privileged signing requirements for file append
Fixes #13475
> fix: waive privileged signing requirements for file append

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/legacy/LegacyConfigPropertiesLoader.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- Improve logging for failure case when reading config file
- Closes #13506
> feat: Improve logging for failure case when reading config file

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSignatureWaiversImpl.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSignatureWaiversImplTest.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/FileSignatureWaivers.java
> chore: 13519 cherry pick wave file append sign

- hedera-node/configuration/preprod/application.properties
> fix: add chainId=298 to preprod/application.properties

- hapi/build.gradle.kts
> chore: Update build to use main branch of hedera-protobufs.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
> fix: increase capacity for the event creation manager's queue

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
> fix: consensus partition test flake

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
Cherry-pick of #13487 to release/0.50
> fix: cherry-pick: Skip transactions older than the software version (#13527)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/IterableStorageManager.java
- Cherry-pick relevant parts of #13533
> fix: remove pointless `WARN` logs, fix first contract key management

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/DefaultPlatformContext.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/context/internal/DefaultPlatformContextTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java
> feat: remove context from platform builder

- .github/workflows/config/node-release.yaml
> chore: Schedule release 0.51 branch creation.

- hapi/build.gradle.kts
- settings.gradle.kts
> chore: Bump hapi version to 0.51.0

- hedera-node/docs/design/services/file-service/file-service.md
- hedera-node/docs/design/services/services.md
Adds markdown file for the File Service design.
Please suggest changes and additional sections as needed.
#13593 
Fixes #
**Checklist**
> docs: File Service design doc

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractHandlers.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
Remove pure check that checks for maximum gas.  
**Checklist**
> feat: remove max gas pure check

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractHandlers.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
> chore: Cherry pick 13648 into release 0.51 branch

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractHandlers.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
> chore: Cherry pick 13648 into release 0.50 branch

- platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBaseBench.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
Fix summary: see #13531 comments for details.
Fixes: https://github.com/hashgraph/hedera-services/issues/13531
> fix: 13531: Rehash for 172129258 round has failed

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiEventStorage.java
> fix: gui setting consensus data twice

- .github/workflows/flow-pull-request-formatting.yaml
Pulls in 3 commits from `develop` for milestone and assignee check
> fix(ci): cherry pick milestone assignee checks rel 50

- .github/workflows/flow-pull-request-formatting.yaml
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/StakingInfoManagementSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchemaTest.java
Fixes https://github.com/hashgraph/hedera-services/issues/13677
Cherry-pick https://github.com/hashgraph/hedera-services/pull/13673
> fix: (cherry-pick) Use restart method to all token schemas 

- hedera-node/configuration/mainnet/application.properties
- hedera-node/configuration/testnet/application.properties
This PR updates the application.properties files for testnet and mainnet to enable balances in queries.
Fixes #13715
> fix: Enable tokens.balancesInQueries.enabled

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
> fix: Make post hash collector sequential

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/StakingInfoManagementSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0490TokenSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/schemas/V0490TokenSchemaTest.java
> fix: (cherry-pick) Add `restart` method to all token schemas (#13673)

- hedera-node/docs/design/services/schedule-service/schedule-service.md
- hedera-node/docs/design/services/services.md
Added design doc for Schedule Service.
#13706 
Fixes #
Please review and comment on any suggested changes or additional sections you would like me to add.
Thanks!
**Checklist**
> docs: Added design doc for Schedule Service

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
> fix: Make PostHashCollector SEQUENTIAL

- hedera-node/configuration/mainnet/application.properties
- hedera-node/configuration/testnet/application.properties
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
This PR moves the configuration change for balances in queries to the code.
Fixes #13768
> chore: Enable tokens.balancesInQueries in code

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Added additional test case for contract update with `maxAutoAssociations`
Fixes #13376 
**Checklist**
> test: HIP-904 Try contract update with zero max auto associations value

- hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/forensics/RecordDumperDiagnostic.java
Diagnostic utility that dumps a directory of record stream files.  User recodes the filter functions, or adds his own.
Masquerading as a unit test to make it easy to customize and run.
Fixes #13846 
**Checklist**
> feat: Diagnostic utility which lets you dump a directory of record stream files

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java
> fix: invalid signature state leak

- hedera-node/docs/design/services/network-admin-service/network-admin-service.md
- hedera-node/docs/design/services/services.md
Added design doc for Network and Freeze services.
#13815 
Fixes #
Please add any comments/requested changes and any additional section you would like to see. Thanks!
**Checklist**
> docs: Added Network and Freeze service design doc

- hedera-node/configuration/preprod/application.properties
- hedera-node/configuration/previewnet/application.properties
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersCallTest.java
Enable HIP-206 and HIP-906 by default in all environments.
> chore: enable HIP-206 and HIP-906

- gradle/plugins/src/main/kotlin/com.hedera.hashgraph.nexus-publish.gradle.kts
To fix error:
> Failed to find staging profile for package group:
**Checklist**
> build: Set 'packageGroup' in 'nexusPublishing'

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/generate-platform-diagram.sh
> fix: generate-diagram-script

- hapi/build.gradle.kts
> chore: Changed protobufs back to main branch.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/concurrent/internal/DefaultExecutorFactory.java
Create platform ForkJoinPool with `asyncMode=true` (FIFO).
Fixes #13967
**Checklist**
> perf: Create platform ForkJoinPool with asyncMode=true

- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
Stop release 0.50 nightly regression
Fixes #
N/A
**Checklist**
N/A
> ci: stop release 0.50 nightly regression

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountInfoHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoCreateUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
Cherry pick pr #13849 into release/0.50 branch
> chore: Cherry pick 13849 into v 0.50

- .github/workflows/node-zxc-build-release-artifact.yaml
- block-node/blocknode-core-spi/build.gradle.kts
- block-node/blocknode-core/build.gradle.kts
- block-node/blocknode-filesystem-api/build.gradle.kts
- block-node/blocknode-filesystem-local/build.gradle.kts
- block-node/blocknode-filesystem-s3/build.gradle.kts
- block-node/blocknode-grpc-api/build.gradle.kts
- block-node/blocknode-state/build.gradle.kts
- gradle/plugins/src/main/kotlin/com.hedera.hashgraph.nexus-publish.gradle.kts
> build: split publish of 'platform' and 'services' / do not publish blocknode

- hedera-node/docs/design/services/services.md
- hedera-node/docs/design/services/util-service/util-service.md
Added design doc for Util Service.
#13950 
Please add any suggested changes or suggested sections. Thanks.
**Checklist**
> docs: Added design doc for Util Service

- hapi/build.gradle.kts
Change proto version
Fixes #13980
> chore: change proto version

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java
Cherry-pick of PR #13900 to release/0.51 branch
Fixes #13795
> feat: invalid query error handling (#13900)

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AccountsConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java
> feat: Change config defaults

- .github/CODEOWNERS
> chore: Updated codeowners for devops-ci

- platform-sdk/swirlds-platform-core/src/jmh/java/com/swirlds/platform/core/jmh/EventSerialization.java
> chore: Add JMH test for event hashing

- hapi/build.gradle.kts
> chore: changed protobufs branch back to main

- .github/workflows/config/node-release.yaml
> chore: Schedule release 0.52 branch creation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java
This reverts commit e9f0ecf8c4e83aaa602627587a62f847c8637b5a.
Fixes #14084
**Checklist**
> chore: Revert "feat: invalid query error handling (#13900) (#14023)"

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateFilesBeforeReconnect.java
Cherry pick fixes from develop branch
N/A
**Checklist**
N/A
> ci: cherry pick fix to lower tps for reconnect tests

- hapi/build.gradle.kts
> chore: Bump hapi version to 0.52.0

- hapi/build.gradle.kts
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
Remove unneeded code, since we probably won't have a use-case for transfers to override PAUSED status.
Fixes #
**Checklist**
> chore: remove unneeded code

- hedera-node/docs/design/services/smart-contract-service/hedera-account-service-isAuthorized-design.md
Design doc for HIP-632's `isAuthorizedRaw`.
One task of #13560 
Currently needs one further update to `isAuthorizedRaw` on my side, then I'll push that section.
**Checklist**
> docs: Design doc for HIP-632 `isAuthorizedRaw`

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecContract.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecToken.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/operations/transactions/TransferTokenOperation.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/TransferTokenTest.java
> test: add tests that shows the difference of transferToken and transferFrom from contracts

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRejectHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenRejectSuite.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/14282
> chore: cherry-pick Dont modify allowances on token reject

- hedera-node/test-clients/SpecCookbook.md
- Adds a cookbook item on minimizing the effects of feature flag rollouts on `@HapiTest` classes.
> feat: Add feature flag cookbook item

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
Description:
One line fix of incorrect condition in deserialize method. Introduced with https://github.com/hashgraph/hedera-services/pull/14231
Relates to https://github.com/hashgraph/hedera-services/issues/14230
**Checklist**
> fix: 14230 platform state deserialization fix

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/Triple.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/transaction/pool/VirtualMerkleTransactionPool.java
- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/NonStandardLog.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/constructable/GenerateClassId.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/ImmutableHash.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/SerializablePublicKey.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBin.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/notification/DispatchException.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/notification/NoListenersAvailableException.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/notification/internal/AsyncNotificationEngine.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/VirtualHashRecordSerializer.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/VirtualLeafRecordSerializer.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/io/OutputStreamFactory.java
- platform-sdk/swirlds-merkle/src/main/java/com/swirlds/merkle/map/MerkleMap.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/EventDescriptor.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/UnsignedEvent.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableQueueStateBase.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTreeViewBase.java
Fixes warnings emitted by the `javadoc` tool. 
In preparation for #13645
**Checklist**
> chore: fix Javadoc warnings in 'platform' modules

- hedera-node/hedera-addressbook-service-impl/build.gradle.kts
- hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
- hedera-node/hedera-addressbook-service/build.gradle.kts
Saw that these are mostly unnecessary while testing something else. Might as well clean this up right aways as these are rather new modules. They should have a clean setup.
#11569
**Checklist**
> chore: remove compiler lint exceptions and fix (addressbook)

- hapi/build.gradle.kts
This should be merged after the last proto changes are in main: https://github.com/hashgraph/hedera-protobufs/pull/399
> feat: Point the protos to main

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java
> fix: revert node remove consensus change

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkAdminServiceInjectionModule.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkAdminHandlers.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/package-info.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/V0490FreezeSchema.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/V0490NetworkSchema.java
- hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/FreezeService.java
- hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/FreezeServiceDefinition.java
- hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/NetworkServiceDefinition.java
Add missing javadoc to networkadmin service
Made a few minor changes to field accessibility
Fixes #13144
> feat: Add javadoc for networkadmin service

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0530TokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/V0530TokenSchemaTest.java
Fixes #14408 
Update minStake to 0 on all nodes
Testing:
```
=== 32 staking info ===
0 : BBMStakingInfo[number=0, minStake=0, maxStake=156250000000000000, stakeToReward=113505645400000000, stakeToNotReward=108010000000000, stakeRewardStart=113460067200000000, unclaimedStakeRewardStart=3704900000000, stake=113568077200000000, rewardSumHistory=[J@3303e89e, weight=26]
1 : BBMStakingInfo[number=1, minStake=0, maxStake=156250000000000000, stakeToReward=166821263400000000, stakeToNotReward=600000000, stakeRewardStart=166991963100000000, unclaimedStakeRewardStart=100973100000000, stake=156250000000000000, rewardSumHistory=[J@cec590c, weight=36]
2 : BBMStakingInfo[number=2, minStake=0, maxStake=156250000000000000, stakeToReward=12016726000000000, stakeToNotReward=47515837200000000, …
```
> fix: Update minStake to 0 on all nodes

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenFeeScheduleUpdateSpecs.java
Fixes #14382 
Adds additional validations for `TokenFeeScheduleUpdate` custom fees handler
> chore: Add missing validations for CustomFees

- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts
- hapi/build.gradle.kts
- platform-sdk/swirlds-logging/build.gradle.kts
- platform-sdk/swirlds-logging/src/jmh/java/com/swirlds/logging/benchmark/log4j2/Log4JRunner.java
- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/utils/ConfigUtils.java
`com.swirlds.logging.utils.ConfigUtils` has been marked as deprecated but is still in use. need to suppress warnings on this module.
Fixes #14406
> fix(bug): Suppress warning in ConfigUtils

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AccountsConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/WiringConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/EventCreationConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/EventCreationManagerTests.java
> feat: Enable health monitor

- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
Make sure clean tasks are removed from the map timely.
Fixes #14464
**Checklist**
> perf: VirtualHasher.hash() keeps too many tasks in memory

- hapi/build.gradle.kts
Changes cloneHederaProtobufs branch to main
Fixes #14436 
**Checklist**
> chore: cloneHederaProtobufs back to main

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java
Fixes #14389 
Adds config to disable frontend throttles for testing
> chore: Add config to disable frontend throttles

- hapi/build.gradle.kts
> chore: Use main as protobuf branch

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesReplayer.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesReplayerTests.java
- cherry pick of https://github.com/hashgraph/hedera-services/pull/14465
> feat: limit PCES replay frequency

- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
Cherry pick docker rate limit fix
Fixes #14491
> fix: Cherry pick docker rate fix into release-0.53

- hedera-node/configuration/dev/settings.txt
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V053AddressBookSchemaTest.java
cherry picked #14473 and #14493
Fixes #14450
**Checklist**
> feat: cherry-pick: update node grpc information during address book service migration

- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/test/java/com/swirlds/demo/consistency/ConsistencyTestingToolRoundTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/TransactionSupplier.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/SystemTransactionExtractionUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/resubmitter/DefaultTransactionResubmitter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/resubmitter/TransactionResubmitter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/pool/DefaultTransactionPool.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/pool/TransactionPoolNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/UnsignedEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/Transaction.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/TransactionWrapper.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/TransactionUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/stale/TransactionResubmitterTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/pool/TransactionPoolTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/TransactionUtilsTest.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/RandomEventUtils.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/TestingEventBuilder.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssDetectorTests.java
> refactor: Provide EventTransaction to the app

- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
Cherry pick docker rate limit fix into release/0.52
Fixes #14489
> fix: 14489 cherry pick docker rate limit fix in release052

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/FakeEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/PlatformEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/CesEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/Event.java
> chore: Add EventCore and Signature to Event

- .github/workflows/node-zxc-compile-application-code.yaml
- hedera-node/test-clients/build.gradle.kts
- hedera-node/test-clients/repeatable-node0-log4j2.xml
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/EmbeddedHapiTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/GenesisHapiTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/RepeatableHapiTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/RepeatableReason.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TestTags.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/extensions/ExtensionUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/EmbeddedNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/EmbeddedNode.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/UnifiedConsTimeTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsRestartTest.java
> chore: include misc `@EmbeddedHapiTest` and `@RepeatableHapiTest` tests in PR checks

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/ConcurrentEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/PbjBytesHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/PbjStreamHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/TransactionWrapper.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/transaction/TransactionWrapperUtils.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/TransactionUtils.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java
> chore: Add hash to TransactionWrapper

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/TokenReconciliationValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
> fix: update `TokenReconciliationValidator` for non-fungible types

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
> fix: cherry pick 14549

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/TokenReconciliationValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
- Cherry-pick #14587 
- Cherry-pick #14608
> fix: cherry pick misc fixes

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/HgcaaLogValidator.java
> fix: only skip event from missing creator

- hapi/build.gradle.kts
Revert protobufs branch to `main`
> chore: Revert protobufs branch to `main`

- hedera-node/hedera-addressbook-service-impl/build.gradle.kts
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeCreateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidator.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/CertificatePemTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/AddressBookTestBase.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeDeleteTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/UpdateAccountEnabledTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
cherry-pick (#14611)
Fixes #
**Checklist**
> feat: cherry-pick: added X509Certificate validation for NodeCreate and NodeUpdate

- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/WritableQueueStateBaseTest.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/State.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/StateChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/KVChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/QueueChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/SingletonChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableKVStateBase.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableQueueStateBase.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java
- platform-sdk/swirlds-state-api/src/test/java/com/swirlds/state/spi/StateTest.java
- platform-sdk/swirlds-state-api/src/test/java/com/swirlds/state/spi/WritableKVStateBaseTest.java
- platform-sdk/swirlds-state-api/src/test/java/com/swirlds/state/spi/WritableSingletonStateBaseTest.java
- Closes #14580 
- Closes #14583 
- Migrates the listener API from the preview block streams working branch
> chore: migrate `StateChangeListener` to States API

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/ReconnectListener.java
> fix: get notification listeners up-to-date before `RECONNECT_COMPLETE`

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/TokenReconciliationValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
> fix: cherry-pick misc fixes

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManager.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
> fix: still set record `ethereum_hash` on `CONSENSUS_GAS_EXHAUSTED`

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAirdropHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
* Add validation to check if we airdrop to a contract without an admin key
* **Bonus refactor:** Move the airdrop max value to the config
Fixes #14663
**Checklist**
> feat: TokenAirdrop disable contract airdrops

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
Airdrop-15 from hip 904 test plan
Fixes #14445
**Checklist**
> test: AIRDROP-15 for hip-904 test plan

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
(AIRDROP - 28) Given a token with a custom fee that should be paid by the sender when the token treasury account signs and pays the tokenAirdropTransaction then no custom fees should be paid.
Fixes #14643
**Checklist**
> test: add airdrops test 28

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneDispatchFactory.java
Adds missing method parameter so that compilation succeeds.
Fixes #
**Checklist**
> chore: fix compile error

- .github/CODEOWNERS
- hapi/hedera-protobufs/services/state/recordcache/recordcache.proto
Puts changes from https://github.com/hashgraph/hedera-services/pull/14655 into inert protobufs.
Fixes #14800 
**Checklist**
> chore: Update inert protobufs with tx receipt queue changes

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
> feat: include token memo on balance validation error

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/PbjHasher.java
> feat: add hashing improvement

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/SemanticVersionConverter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetEventCreator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/CombinedEventHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/DefaultEventHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/HashingMigrationUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/PbjHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/StatefulEventHasher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/Shadowgraph.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
> feat: better event hashing migration option

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/impl/internal/AbstractMerkleNode.java
This PR improves diagnostics to help with root cause analysis of the exception.
#14851 
**Checklist**
> chore: Add route info to exception message in AbstractMerkleNode

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesTranslator.java
> fix: Call correct translator for `gasRequired` in `UpdateTokenCustomFeesTranslator`

- hedera-node/hedera-schedule-service-impl/build.gradle.kts
- hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
- hedera-node/hedera-schedule-service/build.gradle.kts
Fix compiler warnings in schedule service
Fixes #14689 
**Checklist**
> chore: Fix compiler warnings in schedule service

- hedera-node/configuration/mainnet/upgrade/feeSchedules.json
- hedera-node/configuration/testnet/upgrade/feeSchedules.json
cherry-pick https://github.com/hashgraph/hedera-services/pull/14881
> fix: fix invalid feeSchedules.json

- hedera-node/test-clients/src/main/java/module-info.java
> fix: Fix compile error

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
Added missing initialization code related to the constructible registry 
Fixes #14886
**Checklist**
> fix: 14886 Fixed ReconnectTest

- hapi/hedera-protobufs/block/stream/output/state_changes.proto
- hapi/hedera-protobufs/services/response_code.proto
- hapi/hedera-protobufs/services/state/roster/roster.proto
- hapi/hedera-protobufs/services/state/roster/roster_state.proto
> fix: update in-repo protobufs for roster, HIP-904 codes, new state changes

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAirdropHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
Add allowance strategy enum for handling allowances during airdrop
Fixes #
This PR resolves - https://github.com/hashgraph/hedera-services/pull/14844#discussion_r1719986139
**Checklist**
> chore: add AllowanceStrategy enum

- hedera-node/configuration/dev/settings.txt
Related regression issue
https://github.com/swirlds/swirlds-platform-regression/issues/4003
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1723821726548819
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1723823766432529
> fix: remove unused property

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BlockStreamTransactionTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/ContractCallTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/ContractCreateTranslator.java
- hedera-node/test-clients/src/test/java/com/hedera/services/bdd/utils/test/translators/ContractCallTranslatorTest.java
Translator for contract create transaction to convert block items to record stream entries
Fixes #14845 
**Checklist**
> feat: create translator for contract call transaction

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/UnsignedEvent.java
> fix: change order of descriptor variables

- hedera-node/hedera-token-service-impl/build.gradle.kts
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/module-info.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
This PR adds a metric that measures the number of queried account balances per second.
Fixes #14962
> chore: Added metric that measures the number of queried account balances

- hedera-node/docs/design/services/smart-contract-service/update_token_custom_fees_sc.md
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/UpdateTokenFeeScheduleTest.java
- Adjust the test plan in the design doc
- Provide tests described in the adjustment
[910](https://github.com/hashgraph/hedera-smart-contracts/issues/910)
Fixes #
**Checklist**
> docs:  Adjust test plan in design doc for `UpdateTokenCustomFees` and add related tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
(CLAIM_59) TokenClaimAirdrop transaction with a receiver - a hollow account that signs it with no HBAR fails
Fixes #14959
**Checklist**
> test: added Token Claim Airdrop Test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
- Updating test meta data
Fixes #15063
> ci: update test meta data used in report generation

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
**Description**
Increase test coverage for `ContractUpdate`
> test: add test to ensure immutable contracts cannot be changed

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/AccessoryUtils.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/CreateCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/NodesCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/UpdateCommand.java
- hedera-node/test-clients/yahcli/README.md
- hedera-node/test-clients/yahcli/assets/screened-launch.sh
- hedera-node/test-clients/yahcli/run/build.sh
- hedera-node/test-clients/yahcli/run/publish.sh
- Closes #8831
- Closes #15065
> feat: support certs from .pfx files in yahcli `nodes`

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Cherry pick of #15092 
**Checklist**
> chore: #15092 cherry pick

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropBase.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
Add contract as receiver tests
Fixes #15085
Fixes #15086
Fixes #15087
**Checklist**
> test: Add contract as receiver tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
Add claim airdrop test cases from the test plan:
CLAIM_47
CLAIM_48
CLAIM_49
CLAIM_50
CLAIM_51
Fixes #14912
Fixes #14913
Fixes #14914
Fixes #14915
Fixes #14916
**Checklist**
> test: Additional airdrop negative tests

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Improve test coverage for requirements needed for updating contract attributes.
> chore: write additional tests for contract update requirements

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
> chore: 15111 cherry pick

- .github/workflows/flow-artifact-determinism.yaml
- .github/workflows/flow-node-performance-tests.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-adhoc-artifact.yaml
- .github/workflows/node-flow-deploy-preview.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-flow-fsts-custom-regression.yaml
- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxc-deploy-preview.yaml
- .github/workflows/node-zxcron-develop-fsts-regression.yaml
- .github/workflows/node-zxcron-release-branching.yaml
- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/platform-flow-jrs-custom-regression.yaml
- .github/workflows/platform-pull-request-extended-checks.yaml
- .github/workflows/platform-zxc-launch-jrs-workflow.yaml
- .github/workflows/platform-zxcron-develop-jrs-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
- .github/workflows/zxc-jrs-regression.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts
- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
- Updates the `run-ons` stanza in the CI workflows to use the new self-hosted cluster
- Disables cgroup creation logic
- Updates Java and NodeJS versions
- Closes #15109
> ci: update workflows to use latitude.sh based runners

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
- Two PRs simultaneously changed `MerkleStateLifecycles` and added a test implementation.
> fix: compile error from simultaneous merges

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/PlatformStateValueAccumulator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateValidator.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/consensus/RoundCalculationUtilsTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/TransactionHandlerTester.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventRecoveryWorkflowTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SignedStateTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateRegistryTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SwirldStateManagerTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/hashlogger/HashLoggerTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/PbjConverterTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/PlatformStateUtils.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/SignedStateUtils.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/PlatformStateTests.java
Reduced usage of `PlatformState` to the bare minimum. 
Fixes #14098 
**Checklist**
> feat: 14098 Remove usages of `PlatformState` where possible.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/ConcurrentStreamingTreeHasher.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerConcurrent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterServiceImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/V0540RosterSchema.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaRecordCache.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/WriteStateToDiskListener.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchHandleContext.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/dispatch/RecordFinalizer.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordStreamBuilder.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/ConcurrentStreamingTreeHasherTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchHandleContextTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
This PR includes a lot of miscellaneous adjustments in preparation for merging the block stream feature branch (`stream-manager-spike`). It includes the following changes (from the commit messages):
* Minor deletions and comment modifications
* Create fee schedule before exchange rate
* Record cache adjustments
* Don't commit full stack on user transaction
* Roster state key change
* Error handling for writing state to disk
> feat: Miscellaneous minor updates

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/HapiSpecWaitUntil.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
> fix: add background traffic to `DabEnabledUpgradeTest`

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
closes #14943
regression run: https://swirldslabs.slack.com/archives/C03E8UAA2PR/p1724840716058869
> chore: use new MTT state

- hedera-node/configuration/dev/application.properties
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeCreateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeDeleteHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeDeleteHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
- hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java
- hedera-node/hedera-addressbook-service/src/main/java/module-info.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/ReconnectListener.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/WriteStateToDiskListener.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeUpgradeActionsTest.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/ReadableFreezeUpgradeActionsTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeDeleteTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
Set the flag to false for release/0.53
Added HapiTests to check the flag.
Fixes #15231
**Checklist**
> feat: add enableDAB flag to enable and disable DAB features

- hedera-node/configuration/dev/application.properties
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeCreateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeDeleteHandler.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeDeleteHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
- hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java
- hedera-node/hedera-addressbook-service/src/main/java/module-info.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/ReconnectListener.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/WriteStateToDiskListener.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeUpgradeActionsTest.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/ReadableFreezeUpgradeActionsTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeDeleteTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
Set nodes.enableDAB to true to enable DAB.
Fixes #15231
**Checklist**
> feat: cherry-pick: add enableDAB flag to enable and disable DAB features (#15232)

- hedera-cryptography/hedera-cryptography-tss/build.gradle.kts
- settings.gradle.kts
This was accidentally remove in #14245 as it was introduced in parallel to that change.
#14245
**Checklist**
> build: add back 'hedera-cryptography' as Gradle projects

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
additional test for reqSignature when testing the token airdrop claim
Fixes #15141
> test: add a sigRequired true additional test

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/UnzipUtility.java
> fix: if the directory exist, don't create it in UnzipUtility

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/UnzipUtility.java
Cherry-pick PR #15319
Fixes #15305
**Checklist**
> fix: cherry-pick: if the directory exist, don't create it in UnzipUtility (#15319)

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/CallOutcome.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HasTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HtsTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/common/AbstractCallAttempt.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/common/AbstractCallTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/common/Call.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/common/CallFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/HasCallAttempt.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/HasCallFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/records/ContractCallStreamBuilder.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/CallAttemptHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/HasCallAttemptTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/HtsCallAttemptTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersTranslatorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/records/ContractOperationStreamBuilderTest.java
> fix: stop using raw types in `Call{Attempt,Translator}` 

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/SelfNodeInfoImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/ServicesSoftwareVersionTest.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/HapiUtils.java
- platform-sdk/swirlds-state-api/src/test/java/com/swirlds/state/spi/HapiUtilsTest.java
- Add unit tests for coverage missing from https://github.com/hashgraph/hedera-services/pull/15294
> chore: add unit tests for `ServicesSoftwareVersion` utilities

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/CustomFeesValidatorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
> fix: Prevent designating deleted accounts as custom fee collectors

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakePeriodManagerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeRewardCalculatorImplTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHandlerImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/RepeatableStakingTests.java
> fix: ensure `StakePeriodManager` current stake period is always up-to-date

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceComponent.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
> chore: use correct Nullable annotation in 'smart-contract-service-impl'

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/AppNotifier.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/DefaultAppNotifier.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/state/notifications/StateHashedListener.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/state/notifications/StateHashedNotification.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/system/state/notifications/StateHashedNotificationTest.java
> chore: add `StateHashedNotification`

- platform-sdk/swirlds-merkledb/build.gradle.kts
- platform-sdk/swirlds-merkledb/src/hammer/java/com/swirlds/merkledb/files/DataFileCollectionCompactionHammerTest.java
- platform-sdk/swirlds-merkledb/src/hammer/java/com/swirlds/merkledb/files/DataFileReaderHammerTest.java
- platform-sdk/swirlds-merkledb/src/hammer/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStoreCompactionHammerTest.java
The tests were not executed for months and thus the issues were not discovered.
With #15363 these tests will run again regularly.
#14407
#15078
**Checklist**
> chore: fix/disable hammer tests that are not working

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/UnzipUtility.java
> fix: permit 100:1 deflation for upgrade ZIP files

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/UnzipUtility.java
> fix: permit 100:1 deflation for upgrade ZIP files (#15422)

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/record/StreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/PairedStreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordStreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/SavepointStackImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/ExecutorComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/records/ContractOperationStreamBuilderTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BaseTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/NaturalDispatchOrderingTest.java
> fix: (0.54) set exchange rates in triggered txn receipts

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
> chore: disable dab in release 0.54

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCornerCasesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenMetadataSpecs.java
**Description**
Enable hapiTest framework implementation in AutoAccountCreationSuite.java and AutoAccountUpdateSuite.java files
**Modified File**
java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
**Test Result:**
All unit test cases have been passed successfully
> feat: HIP796 - HapiTest implementation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/LifecycleTest.java
> fix: freeze time reset check

- hapi/hedera-protobufs/services/state/roster/roster.proto
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterRetrieverTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterValidatorTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java
Fixes #15463 
This should be merged soon after: https://github.com/hashgraph/hedera-protobufs/pull/416
> chore: correct the variable name in roster.proto

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemSetupTest.java
…grade when DAB is disabled
Fixes #15466 
**Checklist**
> chore: do not update file 102 during the first transaction after a freeze upgrade when DAB is disabled

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
> chore: add `TracerBinding` interface for `TransactionExecutors`.

- hedera-dependency-versions/build.gradle.kts
> chore: use 4.28.2 for `com.google.protobuf` artifacts

- hedera-dependency-versions/build.gradle.kts
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/CertificatePemTest.java
- hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java
- hedera-node/hedera-addressbook-service/src/main/java/module-info.java
Cherry-pick #15473 
Updated com.google.protobuf version to 3.25.5 because Synk Scan failed.
Fixes #15558
**Checklist**
> fix: cherry-pick: remove dependencies to 'org.testcontainers' in production code

- hedera-node/configuration/mainnet/upgrade/throttles.json
- hedera-node/configuration/testnet/upgrade/throttles.json
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-file-service-impl/src/main/resources/genesis/throttles-dev.json
- hedera-node/hedera-file-service-impl/src/main/resources/genesis/throttles.json
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeDeleteTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/jrs/NodeOpsForUpgrade.java
cherry-pick https://github.com/hashgraph/hedera-services/pull/15549
> test: (cherry-pick) Added a test to submit DAB transactions for JRS test (#15549)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/InlinePcesWriter.java
> feat: created iterface for inline PCES writer

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
Activates HAS but updating the effective smart contract module to 0.51, which includes `isAuthorizedRaw` and other HAS methods.
Fixes #15769
**Checklist**
> feat: Activate smart contract module 0.51

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/SignatureWriterV6.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/stream/AccountBalanceExport.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Signature.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/LinkedObjectStreamUtilities.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/internal/LinkedObjectStreamValidateUtils.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/internal/TimestampStreamFileWriter.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/SignatureTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/RandotronTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/PlatformEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/signing/DefaultSelfEventSigner.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/proof/algorithms/StateProofSerialization.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigSet.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signer/StateSignerTests.java
> chore: Cleanup `Signature`

- hedera-node/hedera-addressbook-service-impl/build.gradle.kts
Address review comments on https://github.com/hashgraph/hedera-services/pull/15781
> chore: Address review comments

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
> chore: add node details/address book export validation in `DabEnabledUpgradeTest`

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerTest.java
> fix: Handle non-existent token IDs in token fee schedule updates

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerTest.java
PR to `develop`: https://github.com/hashgraph/hedera-services/pull/15831
> fix: Cherry-Pick: Handle non-existent token IDs in token fee schedule updates

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/PlatformConfigurationExtension.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/NoOpInlinePcesWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/ComponentWiringConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/generate-platform-diagram-with-inline-pces.sh
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java
closes https://github.com/hashgraph/hedera-services/issues/15606
> feat: create inline pces wiring

- .github/CODEOWNERS
Make hedera-services also code owner of hedera-app
> chore: Make hedera-services also code owner of hedera-app

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java
PR to `develop` [here](https://github.com/hashgraph/hedera-services/pull/15933)
PR to `release/0.55` [here](https://github.com/hashgraph/hedera-services/pull/15936)
> fix: Cherry-Pick (0.54): Airdrop transfer list size validation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/OpWorkflowMetrics.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/metrics/OpWorkflowMetricsTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
PR to `develop` [here](https://github.com/hashgraph/hedera-services/pull/15900)
> fix: Cherry-Pick: Add query handling metrics upload

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
> chore: disable dab in 0.55

- .github/workflows/zxf-prepare-extended-test-suite.yaml
> ci: ensure prepare xts branch launches when node deploy production build finishes

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java
- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
Fixes: https://github.com/hashgraph/hedera-services/issues/15959
Signed-off-by: Artem Ananev <artem.ananev@swridslabs.com>
> fix: 15959: Add more logging for 12311

- hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
- hedera-node/hedera-token-service-impl/build.gradle.kts
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/module-info.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeRewardCalculatorImplTest.java
- hedera-node/hedera-token-service/build.gradle.kts
- hedera-node/hedera-token-service/src/main/java/module-info.java
Fixes compiler warnings (exports ,lossy-conversions, static) in token service.
**Related issue(s)**: 
Fixes #14693
**Checklist**
> chore: Fix compiler warnings in token service

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/TssBaseService.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/TssBaseServiceImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/handlers/TssMessageHandler.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/handlers/TssVoteHandler.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/NodeStakeUpdates.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/FakeTssBaseService.java
- Adds links to GitHub issues for TSS.
> chore: add links to TSS issues

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/ConcurrentEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java
> chore: use `0s` as `@RepeatableHapiTest` valid start offset

- .github/CODEOWNERS
Remove hedera-base as code owner
Fixes #16042
> chore: Remove hedera-base as code owner

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
> chore: use `fireAndForget()` for freeze period background traffic

- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/node-zxf-deploy-integration.yaml
- .github/workflows/platform-zxc-launch-jrs-workflow.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
Updating github workflow permissions per step-security-recommendations.
Fixes #16032 
**Checklist**
> ci: Updating workflow permissions as per step-security recommendations.

- hedera-node/docs/design/services/smart-contract-service/system-contract-gas-calc.md
Add a document to add additional details about gas calculations with special focus on system contracts.
Fixes #15983
**Checklist**
> docs: add doc to describe system contract gas calculations

- hedera-node/configuration/mainnet/upgrade/throttles.json
- hedera-node/configuration/previewnet/upgrade/throttles.json
- hedera-node/configuration/testnet/upgrade/throttles.json
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/StatsConfig.java
- hedera-node/hedera-file-service-impl/src/main/resources/genesis/throttles.json
PR to [develop](https://github.com/hashgraph/hedera-services/pull/15930)
PR to [0.56](https://github.com/hashgraph/hedera-services/pull/16338)
> feat: Cherry-Pick (0.55): Define throttle for GetBalance queries

- .github/workflows/node-zxc-compile-application-code.yaml
This PR aims to update the workflow action to the step-security maintained version.
Fixes #16333
**Checklist**
> ci: Updating workflow action to step-security version.

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
This pull request includes a configuration change to the `TokensConfig` class in the `hedera-node` project. The change modifies the default value of the `countingGetBalanceThrottleEnabled` property.
Configuration updates:
* [`hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java`](diffhunk://#diff-53a4b68e520ac34ddd7c2a767c53d4554af0c4607d97bb95d9d4cc90bb5f2c6aL70-R70): Changed the default value of `countingGetBalanceThrottleEnabled` from `false` to `true`.
Fixes #16361 
**Checklist**
> chore: Update TokensConfig countingGetBalanceThrottleEnabled default to true

- hedera-node/docs/design/services/smart-contract-service/frictionless-airdrops-system-contracts.md
This PR aims to update the design documentation for the work done for HIP-904 in HSCS by updating function signatures and test cases.
Fixes #16190 
**Checklist**
> docs: Update HIP-904 HSCS design doc

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
The field names of two JSON fields were incorrect. They have been fixed (`message` changed to `msg`, `headSha` changed to `sha`).
Fixes #16375
> ci: fix JSON field names

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/PlatformStateService.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/PlatformStateServiceTest.java
This PR removes deprecated code that was there for migration purposes
Fixes #16380 
**Checklist**
> chore: 16380 `MerkleStateRoot` clean up

- hapi/hedera-protobufs/services/node_create.proto
- hapi/hedera-protobufs/services/node_update.proto
- hapi/hedera-protobufs/services/state/addressbook/node.proto
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/ReadableNodeStoreImpl.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/AddressBookTestBase.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/ReadableFreezeUpgradeActionsTest.java
> fix: Cherry-pick: Remove tss encryption key from node-related protos

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusMetricsImpl.java
minor fix
Fixes #16539
**Checklist**
> chore: update ConsensusMetricsImpl.java

- .github/workflows/zxf-dry-run-extended-test-suite.yaml
Adds a new workflow to enable test-runs of the XTS suite
Fixes #16538
**Checklist**
> ci: Add XTS Dry Run Workflow

- hedera-node/configuration/dev/application.properties
- hedera-node/configuration/previewnet/application.properties
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
This PR enables to configuration flags for Airdrops via system contract and removes the current overrides
Fixes #16535
**Checklist**
> chore: Enable HIP-904 System Contracts configuration

- .github/workflows/zxcron-extended-test-suite.yaml
Add workflow run id, url and commit author to slack report.
Fixes #16507 
On line 336 the last part of the URL was changed to reference the xts-tag-commit sha.
**Checklist**
> ci: Add workflow run id, url and commit author to slack report

- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/AddressBookServiceImpl.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V056AddressBookSchema.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/AddressBookServiceImplTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V056AddressBookSchemaTest.java
- hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookService.java
> feat: Added 056 AddressBook schema

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/module-info.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
Compare AddressBooks as Rosters.
Fixes #16536
Tests passed: https://github.com/hashgraph/hedera-services/actions/runs/11804147456
**Checklist**
> fix: Update AddressBookTestingToolState to use Roster

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java
> feat: increase roundsExpired and maxAggregateRels

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/types/EntityType.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SharedNetworkLauncherSessionListener.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/HederaNode.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNode.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BaseTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BlockTransactionalUnitTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/ContractCreateTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/NodeCreateTranslator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/TransactionRecordParityValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/ops/ShutdownWithinOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/LifecycleTest.java
> chore: stabilize `NodeCreate` translation, `ShutdownWithinOp`, etc.

- gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts
Pull in fix for pom name field issue
Fixes #16585
> fix: Cherry-pick pom name field fix

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/NodeMetadataHelper.java
- Use `StakingNodeInfo` weight for 0.56 upgrade boundary update.
> fix: weight update typo

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HederaNativeOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QueryHederaNativeOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HssSystemContract.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/HssCallAttempt.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/HssCallFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/signschedule/SignScheduleCall.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/signschedule/SignScheduleTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameUtils.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/AbstractProxyEvmAccount.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/HederaEvmAccount.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/TokenEvmAccount.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/CallAttemptHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/HssSystemContractTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/HtsSystemContractTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/HasCallAttemptTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hss/HssCallAttemptTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hss/HssCallFactoryTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameUtilsTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ProxyEvmAccountTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ProxyEvmContractTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/TokenEvmAccountTest.java
Add classes to define the Hedera Schedule Service system contract.
Fixes #16520 
**Checklist**
> feat: add infrastructure classes for hss system contract

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java
This reverts commit b6b6018422d1dc999f9f2a5849bd0e0df98319ba.
Fixes #16630
> fix: revert remove AddressBookUtils.createRoster (#16604)

- .github/workflows/zxcron-promote-build-candidate.yaml
Update increment action to step-security maintained version
Fixes #16616 
**Checklist**
> ci: Update increment action to step-security maintained version

- .github/workflows/node-flow-deploy-release-artifact.yaml
Updates the workflow in a way that when a new tag is pushed in the hedera-services repo, it will checkout the hedera-protobufs repo, update the files there, push directly to main in the protobufs repo and create the same tag as the one in the hedera-services.
Fixes #15453 
Test workflow run: https://github.com/hashgraph/hedera-services/actions/runs/11738548571/job/32701293490
**Checklist**
> ci: Add hedera-services -> hedera-protobufs auto-update functionality

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HssTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/ProcessorModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/HssCallFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/ProcessorModuleTest.java
Make the changes needed for providing the Hedera Schedule Service system contract via dagger
Fixes #16625
> feat: implement dagger changes for hss

- gradle/plugins/build.gradle.kts
- gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts
Adds the validate-poms plugin. Updates developers section to add a developer id field to the pom.xml file
Fixes #16649
**Checklist**
> feat: Add validate-poms plugin and update developers section in pom gen

- .github/workflows/config/node-release.yaml
> chore: Schedule release 0.57 branch creation

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java
This PR removes a unit test that is broken from a prior PR.  The unit test is no longer needed.  
Fixes #16745
> chore: remove unit test to fix develop branch

- hedera-node/configuration/compose/node.properties
- hedera-node/configuration/dev/application.properties
- hedera-node/configuration/dev/node.properties
- hedera-node/data/config/node.properties
- hedera-node/docker/.dockerignore
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BlockStreamConfig.java
- hedera-node/infrastructure/docker/containers/local-node/network-node-base/Dockerfile
- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
- hedera-node/infrastructure/docker/containers/production/network-node-base/Dockerfile
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/ProcessUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/TransactionRecordParityValidator.java
> chore: Cherry Pick: Modify and mount default block streams output directory

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
Dispatch only schedules that are not deleted or expired.
Fixes #16019
**Checklist**
> fix: Dispatch only executable schedules

- hapi/hedera-protobufs/services/response_code.proto
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/16776
> fix: Add validation for grpc certificate hash (#16776)

- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxf-dry-run-extended-test-suite.yaml
- hedera-dependency-versions/build.gradle.kts
- hedera-node/hedera-app/src/main/java/module-info.java
Updates the panel-config for `zxf-dry-run-extended-test-suite.yaml` and `zxcron-extended-test-suite.yaml`
Fixes #16800
**Checklist**
> ci: Update panel-config for node-jrs-panel in XTS suite

- .github/workflows/zxc-verify-docker-build-determinism.yaml
- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
> chore: add VERSION file in deterministic container image

- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/16826 into `release/0.57`
Fixes #16750
> fix: 16750 Fixed serialization for `ISSTestingToolState`  (#16826)

- .github/workflows/zxc-jrs-regression.yaml
This PR aims to update the workflow action to the step-security maintained version.
Fixes #16830 
**Checklist**
> chore: Updating action to step security maintained version.

- .github/workflows/node-zxc-compile-application-code.yaml
Downgrade codecov-action to a stable version
Fixes #16873 
**Checklist**
> ci: Downgrade codecov-action to a stable version

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformMerkleStateRoot.java
- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/16859
Fixes #16858 
**Checklist**
> fix: 16858 Corrected class ids for PlatformMerkleStateRoot and MerkleStateRoot (cherry-pick)

- hapi/hedera-protobufs/block/block_service.proto
* Adding a few response codes.
> chore: Mirroring the changes from protobuf PR 453

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/schemas/V0570TssBaseSchema.java
> fix: ensure `TssStatus` singleton is non-null

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermSignTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
Add missing long term schedule sign tests
https://github.com/hashgraph/hedera-services/issues/16737
Fixes #
**Checklist**
> test: Long term schedule sign tests

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
To support the deprecation of the AddressBook instances from the PlatformState, and specifically the previousAddressBook, we need a new method in the RosterRetriever class. This fix introduces it.
Fixes #16907
No existing code is affected. The new method is trivial. The RosterRetriever will probably be eventually deprecated in favor of using the RosterService stores directly. It's currently needed to support the migration from AddressBook to Roster in Platform code.
**Checklist**
> feat: introduce RosterRetriever.retrievePreviousRoster()

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/SchedulingConfig.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignTest.java
- Enable long-term schedules
- Add the new transactions to the whitelist
Fixes #16894
> feat: enable long term schedules

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
Certain exceptions like invalid evm contract id were not handled in pure checks and when computing parties.
Handle these exceptions correctly.
Fixes #16949 
**Checklist**
> fix: handle invalid contract evm address

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
Add pure checks for invalid contract id and handle non `HandleException` exceptions when computing parties for contract calls
**Checklist**
> chore: cherry pick #16952 - add pure checks for invalid evm contract id

- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
Removes erroneous commas in pager duty workflow alert
Fixes #16943 
**Checklist**
> ci: Remove erroneous commas in pager duty workflow alert

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemSetupTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
> chore: export synthetic admin key updates for all undeleted nodes

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
The current ScheduleSign throttle is mostly nonsense that takes into account the scheduled transaction, and if a schedule is not present in the state returns BUSY all the time. We are changing so we throttle ScheduleSign like all other transactions basically letting it go to the default case -  `default -> !manager.allReqsMetAt(now);` in `shouldThrottleTxn()`.
The tests from mono that we ported haven't caught this because we pay for scheduleSing with the DEFAULT_PAYER witch is exempt from throttles. Added a test to cover this scenario.
PR to develop - https://github.com/hashgraph/hedera-services/pull/16959
Fixes #
https://github.com/hashgraph/hedera-services/issues/16958
> fix: schedule sign throttles

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
The current ScheduleSign throttle is mostly nonsense that takes into account the scheduled transaction, and if a schedule is not present in the state returns BUSY all the time. We are changing so we throttle ScheduleSign like all other transactions basically letting it go to the default case -  `default -> !manager.allReqsMetAt(now);` in `shouldThrottleTxn()`.
The tests from mono that we ported haven't caught this because we pay for scheduleSing with the DEFAULT_PAYER witch is exempt from throttles. Added a test to cover this scenario.
PR for 57 - https://github.com/hashgraph/hedera-services/pull/16965
Fixes #
https://github.com/hashgraph/hedera-services/issues/16958
> fix: Fix ScheduleSign throttles

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonPbjConverters.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/dispatch/RecordFinalizer.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/SavepointStackImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/dispatch/RecordFinalizerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/stack/SavepointStackImplTest.java
- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeState.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceImpl.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/ConcurrentEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/EmbeddedVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/LongTermScheduleUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermExecutionTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/RepeatableStakingTests.java
> chore: misc HIP-423 fixes

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFilePath.java
Proposed cherry-pick of fix 16083 to release/0.57
**Related issue(s)**: 16083
Fixes #16083
**Checklist**
> fix: fixed file leak in listing directory ServicesMain (cherry-pick) (#16825)

- hedera-dependency-versions/build.gradle.kts
Update com.goterl:lazysodium-java
Fixes #16957 
**Checklist**
> chore: Update com.goterl:lazysodium-java

- platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/files/DataFileCollectionTest.java
Fixed failing Extended tests
Fixes #17050
**Checklist**
> test: fixed 17050 swirlds-merkledb:timingSensitive

- .github/workflows/node-flow-deploy-release-artifact.yaml
Change secrets for protobufs access
Fixes #17066 
**Checklist**
> ci: Change secrets for protobufs access

- .github/workflows/config/node-release.yaml
> chore: schedule release cutting 0.58

- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
This PR moves and changes the value assigned to `CONTAINER_TSR_ENABLED` in a Dockerfile.
Fixes #16238 
**Checklist**
> fix: move and change value of Dockerfile environment variable

- gradle/development-branch.txt
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersDecoderTest.java
Cherry pick #17165 
Fixes #17163 
**Checklist**
> chore: 17165 cherry pick

- hedera-node/configuration/dev/application.properties
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/RosterTransplantSchema.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/MerkleStateLifecyclesImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/MerkleStateLifecyclesImplTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BootstrapConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NetworkAdminConfig.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersDecoderTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateLifecycles.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchema.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchemaTest.java
- settings.gradle.kts
> chore: only override weights for new node ids (#17175)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/BlockContentsValidator.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/17249
> fix: Set `BlockHeader.first_transaction_consensus_time`

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
> feat: Generated Files 101 & 102 Sequentially Ordered by Node ID

- .github/CODEOWNERS
Change owner of smart contract design docs
> chore: Change owner of smart contract design docs

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
- hedera-node/hedera-file-service-impl/src/main/java/module-info.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/GroupingVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
FileService address book and node details should be updated with all available node metadata at genesis
Fixes #17247 
**Checklist**
> fix: FileService address book and node details should be updated at genesis

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/KeysAndCerts.java
- platform-sdk/swirlds-platform-core/src/main/java/module-info.java
Remove Usages of tss inexact weight libraries in CryptoStatic 
Fixes #17356
**Checklist**
> chore: Remove TssKeys from CryptoStatic

- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/zxc-jrs-regression.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- hiero-dependency-versions/build.gradle.kts
- settings.gradle.kts
- Extends Yaml formatting by spotlessApply (https://github.com/hiero-ledger/hiero-gradle-conventions/issues/30)
- Automatically publishes build scans on CI so that we can remove `--scan` parameters (https://github.com/hiero-ledger/hiero-gradle-conventions/issues/32)
> build: update hiero-gradle-conventions to 0.3.0

- hedera-node/docs/design/services/smart-contract-service/system-contract-abi-guidelines.md
A "guideline" document on our practices for creating/modifying system contract ABIs.
Fixes #14649
**Checklist**
- N/A - Tested (unit, integration, etc.)
> docs: System contract ABI guidelines document

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/services_template.yml
create a new template in git for services team
Fixes #17400
> feat: add a new service template

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
> chore: Add `ROUND/BLOCK_HEADER` items to output block item tree

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/util/FileUtilities.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/FacilityInitModule.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/ConfigProviderImplTest.java
> fix: retain override values on `ConfigProviderImpl.update()`

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleTestingToolState.java
Fixes [#17479](https://github.com/hashgraph/hedera-services/issues/17479)
> fix: turtle state initializing for V54

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/StateLifecyclesImpl.java
- platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoStateLifecycles.java
- platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoStateLifecycles.java
- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestToolStateLifecycles.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/StressTestingTool/src/main/java/com/swirlds/demo/stress/StressTestingToolStateLifecycles.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/NoOpStateLifecycles.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/StateLifecycles.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleStateLifecycles.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/state/FakeStateLifecycles.java
> feat: Updated handleConsensusRound to return a boolean

- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
Code coverage increased from 72.56% to 85.14%
Fixes #17502 
**Checklist**
> test: Increase code coverage in `TransferContextImpl`

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolStateLifecycles.java
This PR fixes [AddressBook-genesis-force-use-config-addressbook-1k-1m/](http://35.247.76.217:8095/swirlds-automation/main/4N/AddressBook/20250123-065854-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)
Fixes #17501 
**Checklist**
> fix: 17501 Fixed AddressBook test.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
- hedera-node/hedera-file-service-impl/src/main/java/module-info.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/GroupingVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
> fix: Revert "cherry-pick: FileService address book and node details"

- .github/workflows/config/node-release.yaml
Reschedule release branch creation for 0.59
Fixes #17541 
**Checklist**
> chore: Update node-release for 0.59 branch

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
- hedera-node/hedera-file-service-impl/src/main/java/module-info.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/GroupingVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java
Reapplies the reverted commit from PR #17539 for latest mainnet release
> chore: Reapply "FileService address book and node details"

- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/module-info.java
This PR fixes failures of 
```
ISS-catastrophic-1k-5m 
ISS-recoverable-1k-5m
```
of JRS panel
Fixes #17503 
**Checklist**
> fix: 17503 Fixed ISS tests of JRS panel.

- hedera-node/infrastructure/docker/containers/production/network-node-base/Dockerfile
- Updates the production image base OS layer to use Ubuntu noble
- Removes unused utilities from the multi-layer build
- Update the default Java JDK version
- Fixes #17546
> chore: update the production image base OS layer

- hapi/build.gradle.kts
- hapi/hedera-protobufs/services/transaction.proto
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v7/BlockRecordFormatV7.java
- hiero-dependency-versions/build.gradle.kts
Fix circular dependency for atomic batch in pbj
Fixes #17556
**Checklist**
> feat: Bump pbj to v0.9.16

- hapi/hedera-protobufs/services/auxiliary/hints/hints_key_publication.proto
- hapi/hedera-protobufs/services/auxiliary/hints/hints_partial_signature.proto
- hapi/hedera-protobufs/services/auxiliary/hints/hints_preprocessing_vote.proto
- hapi/hedera-protobufs/services/basic_types.proto
- hapi/hedera-protobufs/services/transaction.proto
- hapi/src/main/java/com/hedera/hapi/util/HapiUtils.java
- hapi/src/main/java/module-info.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NetworkAdminConfig.java
> chore: add prereqs to `HintsHandlers`

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/PlatformTestingToolStateTest.java
> fix: PTT state test concurrency issue

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabAddresses.java
> fix: roster exception in GUI

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/HintsService.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/WritableHintsStore.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsControllerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsControllers.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsServiceComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsServiceImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/WritableHintsStoreImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterService.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterTransitionWeights.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/V0540RosterSchema.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/WritableStoreFactory.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/TssBlockHashSigner.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionHandlers.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsControllerImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsControllersTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsServiceImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/WritableHintsStoreImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/DiskStartupNetworksTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/RosterServiceTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/FakeHintsService.java
> chore: `HintsController`

- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/AddressBookServiceImpl.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V058StakingInfoReconciliationSchema.java
- hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/AddressBookServiceImplTest.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/DiskStartupNetworksTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V058PendingRewardsSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/module-info.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/TokenServiceImplTest.java
- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
> chore: 0.58-specific state migrations

- hapi/hedera-protobufs/block/stream/output/crypto_service.proto
- hapi/hedera-protobufs/block/stream/output/transaction_output.proto
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/BlockStreamBuilderTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/CryptoCreateTranslator.java
Cherry-pick for https://github.com/hashgraph/hedera-services/pull/17663 and https://github.com/hashgraph/hedera-services/pull/17687.
Fixes https://github.com/hashgraph/hedera-services/issues/17664
**Checklist**
> chore: cherry pick fill created account ID in TransactionOutput

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
This PR cherry picks commit 031d0c8 for merging into release/0.59
Fixes #
**Checklist**
> chore: cherry-pick: 16707 solder missing wire for state signature collecting

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
This PR reverts commit 5109ab8bd3f5f508c83055edfc400dd9a77a450b
Fixes #
**Checklist**
> chore: revert add-missing-wire-for-signature-collection

- platform-sdk/swirlds-platform-core/src/timingSensitive/java/com/swirlds/platform/components/appcomm/LatestCompleteStateNotifierTests.java
This PR stabilizes `LatestCompleteStateNotifierTests` that was randomly failing. Also, it makes sure that if an exception happens during the notification handling, it's not lost
Fixes #17778 
**Checklist**
> fix: 17778 Stabilized `LatestCompleteStateNotifierTests` test.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/StakingConfig.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUtils.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUtilsTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeInfoHelperTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/TokenService.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/tss/RekeyScenarioOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableTssTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/PlatformStateService.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchema.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchemaTest.java
- Addresses #17776 for `release/0.58`
> chore: Use weights from reclamped stakes in current address book

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/RecordTestData.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/PlatformTestingToolStateTest.java
- platform-sdk/platform-apps/tests/StressTestingTool/src/test/java/com/swirlds/demo/stress/StressTestingToolStateTest.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/platform/NodeId.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoader.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/KeyCertPurpose.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/KeyLoadingException.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/KeysAndCerts.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/PublicStores.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/exceptions/ExceptionTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/NetworkPeerIdentifierTest.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RandomAddressBookBuilder.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RandomRosterBuilder.java
Fixes [#15824](https://github.com/hashgraph/hedera-services/issues/15824)
**Checklist**
> chore: Enforce node<id+1> names in EnhancedKeyStoreLoader

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleContext.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustFungibleTokenChangesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustHbarChangesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AutoAccountCreatorTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/EnsureAliasesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/NFTOwnersChangeStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/ReplaceAliasesWithIDsInOpTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecContract.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/TransferTokenTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java
> chore: Use immutable dispatch metadata

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleContext.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustFungibleTokenChangesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustHbarChangesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AutoAccountCreatorTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/EnsureAliasesStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/NFTOwnersChangeStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/ReplaceAliasesWithIDsInOpTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecContract.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/FakeNmt.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/ops/TryToStartNodesOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/TransferTokenTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/TokenServiceFeesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/LifecycleTest.java
> chore: Support env overrides on @HapiTest upgrade boundaries

- hiero-dependency-versions/build.gradle.kts
Updates version of io.netty:netty-bom to fix issue with io.netty:netty-handler.
Fixes #17837
> fix: Update io.netty:netty-bom to io.netty:netty-bom:4.1.118.Final

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/StakingConfig.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUtils.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUtilsTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeInfoHelperTest.java
> chore: (0.59) Support `stake.{min,max}Stake` config

- .github/workflows/flow-node-performance-tests.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-preview.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxc-deploy-preview.yaml
- .github/workflows/node-zxcron-main-fsts-regression.yaml
- .github/workflows/node-zxcron-release-branching.yaml
- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/node-zxf-deploy-integration.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/platform-zxc-launch-jrs-workflow.yaml
- .github/workflows/platform-zxcron-main-jrs-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
- .github/workflows/zxc-jrs-regression.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-collect-workflow-logs.yaml
- .github/workflows/zxf-prepare-extended-test-suite.yaml
Updates the github runner label from network-node-linux-* to hiero-network-node-linux-*
Fixes #17895
> chore: Update github runner labels for hiero-consensus-node

- .github/CODEOWNERS
- .github/workflows/flow-node-performance-tests.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-preview.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxc-deploy-preview.yaml
- .github/workflows/node-zxcron-main-fsts-regression.yaml
- .github/workflows/node-zxcron-release-branching.yaml
- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/node-zxf-deploy-integration.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/platform-zxc-launch-jrs-workflow.yaml
- .github/workflows/platform-zxcron-main-jrs-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
- .github/workflows/zxc-jrs-regression.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-collect-workflow-logs.yaml
- .github/workflows/zxf-prepare-extended-test-suite.yaml
Brings in changes from:
https://github.com/hiero-ledger/hiero-consensus-node/commit/9d2ac099ecd7b68f17d74ceb22ef1f892aaec050
https://github.com/hiero-ledger/hiero-consensus-node/commit/86921c732a7aa8e9cd931ff59d7fe667182392c9
Fixes #17900
> chore: Cherry pick fixes for codeowners and ci runners

- .github/CODEOWNERS
- .github/workflows/flow-node-performance-tests.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-preview.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxc-deploy-preview.yaml
- .github/workflows/node-zxcron-main-fsts-regression.yaml
- .github/workflows/node-zxcron-release-branching.yaml
- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/node-zxf-deploy-integration.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/platform-zxc-launch-jrs-workflow.yaml
- .github/workflows/platform-zxcron-main-jrs-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
- .github/workflows/zxc-jrs-regression.yaml
- .github/workflows/zxc-publish-production-image.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-collect-workflow-logs.yaml
- .github/workflows/zxf-prepare-extended-test-suite.yaml
Brings in changes from:
9d2ac099ecd7b68f17d74ceb22ef1f892aaec050
86921c732a7aa8e9cd931ff59d7fe667182392c9
Fixes #17898
> chore: cherry pick codeowners and ci runner fixes for hiero-ledger

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/Shadowgraph.java
> chore: Reduce log level preventing spamming logs

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/props/NodeConnectInfo.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseContractCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
Fixing the following folders issues regarding non-zero realm/shard. Also fixed some logs.
```
meta
misc
perf
queries
reconnect
records
```
> chore: realm and shard fixes

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
Restores logic for `shouldVerifyProof` in `StateChangesValidator`
> chore: Update state changes validator `shouldVerifyProof`

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/FeeCharging.java
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleException.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/PairedStreamBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/AppFeeCharging.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/Dispatch.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchHandleContext.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordStreamBuilder.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/AppFeeChargingTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/api/TokenServiceApiImplTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java
- hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/AtomicBatchHandler.java
- hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/records/ReplayableFeeStreamBuilder.java
- hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/AtomicBatchHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountRecords.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java
- Will close #17729 when merged to `main`
> chore: Charge fees after rollback

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java
> chore: stabilize CI

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/Hts0x167TranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/Hts0x16cTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HtsTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/UpdateCommonDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/UpdateDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/UpdateKeysCommonTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/address_0x167/UpdateDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/address_0x167/UpdateKeysTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/address_0x16c/UpdateDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/address_0x16c/UpdateKeysTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/update/UpdateExpiryTranslatorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/update/address_0x167/UpdateKeysTranslatorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/update/address_0x16c/UpdateKeysTranslatorTest.java
Fixes #17817 
**Checklist**
- [] Tested (unit, integration, etc.)
> feat: HIP-1028: Apply version strategy to Key Update System Contract

- .github/workflows/flow-artifact-determinism.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-adhoc-artifact.yaml
- .github/workflows/node-flow-fsts-custom-regression.yaml
- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxcron-release-branching.yaml
- .github/workflows/platform-pull-request-extended-checks.yaml
- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
- gradle/toolchain-versions.properties
- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
@hiero-ledger/github-maintainers are there any places outside this repository that also would require the update?
> build: bump JDK to 21.0.6

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/V0500TokenSchemaTest.java
I found 3 more places where the shard/realm was set as 0/0 instead of getting it from config/entity.
> fix: Missed hard-coded shard/realm code

- hiero-dependency-versions/build.gradle.kts
(cherry picked from commit 423da5ab55fb491379c02b83ec50b362456e478c)
Fixes #17892
> fix(cherrypick): Update io.netty:netty-bom to io.netty:netty-bom:4.1.118.Final

- .github/workflows/config/node-release.yaml
Schedules the release branch creation for version 0.60
> chore: Schedule release 0.60 branch creation

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolStateLifecycles.java
- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolMain.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
This PR fixes incorrect version factories for the test apps. Incorrectly produced versions ultimately cause tests failures. 
Fixes #18003 
**Checklist**
> fix: 18003 Fix version factory  in the test apps

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18048
> fix: (cherry-pick) Update expiry when adminKey is not set and autoRenew is set 

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
This PR adds all remaining tests for the update in logic for Consensus Topic - Auto-renewal account, following the requirements of HIP-1021
**Resolves**: https://github.com/hiero-ledger/hiero-consensus-node/issues/18056
> test: HIP-1021 all tests added

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermExecutionTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
> chore: Move `scheduledSystemDeleteUnauthorizedPayerFails()` to repeatable tests

- .github/workflows/zxc-verify-docker-build-determinism.yaml
- .github/workflows/zxc-verify-gradle-build-determinism.yaml
Update the ubuntu version to 24.04 and 22.04.
Fixes #18177
**Checklist**
> ci: update ubuntu version to 24.04 and 22.04

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ReconnectStateLoader.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
Updating javadocs and doing a minor cleanup based on https://github.com/hiero-ledger/hiero-consensus-node/pull/18153#discussion_r1978437846 .
Fixes #18179
Tests should keep passing.
**Checklist**
> chore: update RosterRetriever javadocs

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
> chore: Bumping up the version in MTT

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoader.java
A simple change to stop the migration code is unnecessary. This will no longer log that the clean-up is happening, nor will it create folders inside the archive that are unnecessary.
Fixes #18249
**Checklist**
> chore: Stop PFX migration if unnecessary

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18268
> fix: 18268: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
Fixes compilation after the outdated https://github.com/hiero-ledger/hiero-consensus-node/pull/18055 got merged.
**Checklist**
> chore: fix compilation

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0490TokenSchema.java
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18353
> fix: 18353: Decrease maxKeysHint for token rels back to 1B

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
Cherry-picked fix from [this](https://github.com/hiero-ledger/hiero-consensus-node/pull/18261) PR
* PR to `main` [here](https://github.com/hiero-ledger/hiero-consensus-node/pull/18307)
> chore: (cherry-pick: 0.60) Prohibit all airdrop royalty fees 

- hedera-node/configuration/dev/application.properties
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
Cherry-pick for PR #18334 
#18333 
Fixes #
**Checklist**
> chore: cherry-pick 0.60 enable HIP-1084 feature flag

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
> fix: Remove double init from browserr

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/WritableRosterStore.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/WritableRosterStoreTest.java
> fix: Fix candidate roster adoption logic (v59)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsServiceImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/schemas/V059HintsSchema.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/schemas/V060HintsSchema.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/schemas/V059HintsSchemaTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/schemas/V060HintsSchemaTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/ScheduleServiceFeesSuite.java
> chore: Always ensure non-null hinTS singletons in 0.61

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/WritableRosterStore.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/WritableRosterStoreTest.java
Part of #18356
Must be cherry picked into v61
**Checklist**
> fix: Fix candidate roster adoption logic (v60)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/WritableRosterStore.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/WritableRosterStoreTest.java
Part of #18356
Previous version of this PR can be found [here](https://github.com/hiero-ledger/hiero-consensus-node/pull/18357). I closed that one and opened this one with a cherry pick of the original changes to ensure everything was ported over.
**Checklist**
> fix: Fix candidate roster adoption logic (v61)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
Many important performance metrics disappeared in main, after [#18324]
Fixes #18393
Run both local and JTR shows that the metrics are being reported correctly:
e.g:
**Checklist**
> fix(18393): metrics not updated in PlatformWiring

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/BlockContentsValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/EmbeddedVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/MiscellaneousFeesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/ScheduleServiceFeesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/queries/AsNodeOperatorQueriesTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/queries/RepeatableOperatorQueryTests.java
> chore: Move some timing sensitive tests into repeatable mode

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/KnownLengthStream.java
Make `KnownLengthStream` `Drainable` to avoid allocation and copy overhead in gRPC.
Fixes #18436
**Checklist**
> perf: reduce gRPC allocation and copy overhead when processing KnownLengthStream

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
Related to: https://github.com/hiero-ledger/hiero-consensus-node/issues/18169
> fix: Update MTT Version

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
The unhex utility method has moved.  Remove references in `CreatePrecompileSuite`
> fix: update reference to `unhex` method

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/AugmentedDataInputStream.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/AugmentedDataOutputStream.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/SerializableDataInputStreamImpl.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/SerializableDataOutputStreamImpl.java
Added `@inheritDoc` documentation to new methods from #18460
> chore: Added @inheritDoc in new methods

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
fix a compile issue in main
Fixes #
**Checklist**
> fix: compile fix

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
This fixes the compilation error in current `main`. A constant was moved, so all that needs change is the import statement.
> fix: Import sentinel key from hapi utils

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
> chore: Update MTT version

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeInfoHelperTest.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18500
> chore: Remove the entityCounts migration code in 0.61 (#18500)

- .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
Add birth round migration tests in daily runs. 
Should merge after https://github.com/hiero-ledger/hiero-consensus-node/pull/18390
> chore: Add brith round migration tests to jrs daily runs

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/IssHandlingTest.java
> fix: Ensure `BlockStreamManager#endRound()` is called after dispatching system txns

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeRewardCalculatorImplTest.java
* Add unit tests to cover 100% of StakeRewardCalculatorImpl
Fixes #13340
> test: StakeRewardCalculatorImpl

- hedera-node/hedera-app/build.gradle.kts
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemTransactionsTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/SchedulingConfig.java
- hedera-node/hedera-token-service-impl/build.gradle.kts
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/UpdateTokenFeeScheduleTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/GasCalculationIntegrityTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/build.gradle.kts
- platform-sdk/swirlds-benchmarks/build.gradle.kts
cherry picks fixes for https://github.com/hiero-ledger/hiero-consensus-node/issues/18488
`main` PR: https://github.com/hiero-ledger/hiero-consensus-node/pull/18493
Fixes #
**Checklist**
> fix: State changes out of order in HAPI Tests (Restart)

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
This is a cherry-pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/18411 for release/0.61 branch. 
Fixes #18410 
**Checklist**
> fix: 18410: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved - rel/0.61

- .github/workflows/flow-trigger-release.yaml
Update `git-semver` tool to v1.0.4
**Related Issue(s)**
Fixes #
> chore: update new git-semver version

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/SchedulingConfig.java
- hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleTestBase.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/DisabledLongTermExecutionScheduleTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermExecutionTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermSignTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java
- Enable the support for DAB transactions for long-term scheduling
Fixes #18440
**Checklist**
> feat: Long Term Schedule Transaction Support For DAB transactions

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAirdropHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
Fixes TCK issues for `TokenAirdrop`
https://github.com/hiero-ledger/hiero-consensus-node/issues/18538
Fixes #
https://github.com/hiero-ledger/hiero-consensus-node/issues/18588
**Checklist**
> fix: airdrop TCK issues fixes

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/handlers/HintsPartialSignatureHandler.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064Tests.java
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18622
Cherry-picks https://github.com/hiero-ledger/hiero-consensus-node/pull/18620
> fix: Call `BlockRecordManager.endRound` after system dispatch

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
> fix: Only "go back" in cons time for post-restart system work

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/BlockStreamModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BoundaryStateChangeListener.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/StateNetworkInfo.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/MigrationStateChanges.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BoundaryStateChangeListenerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/DiskStartupNetworksTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/StateNetworkInfoTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/NodeRewardManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeState.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/WritableQueueStateBaseTest.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/StateChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/DeferringListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/QueueChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/SingletonChangeListener.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableQueueStateBase.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java
- platform-sdk/swirlds-state-api/src/test/java/com/swirlds/state/spi/StateTest.java
- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
> chore: 18534 Defer singleton/queue commits to end of block

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowgraphSynchronizer.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/SyncUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
> fix: Add back sorting of sync events

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BoundaryStateChangeListener.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18664
> chore: cherry-pick fix NPE when using records

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/metrics/NodeMetrics.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/metrics/NodeMetricsTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/NodeRewardManagerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064Tests.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18655/files
> chore: Cherry-pick Add metrics for active node percentage

- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
Creates a clean-commit-list for github output and for slack reporting
Fixes #18688
> chore: Fix commit list output for XTS and REPORT BUILD PROMOTION

- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
Remove commit-list from slack reporting.
Add commit-list to github step-summary.
Modify commit list to be markdown URLs
Fixes #18690
> ci: Fix XTS and build promotion slack reporting

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/history/impl/HistoryLibraryImpl.java
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18700
Lazy initialize snark keys when methods are called
> chore: Delay initializing snark keys

- platform-sdk/consensus-event-creator-impl/src/main/java/module-info.java
- platform-sdk/swirlds-benchmarks/build.gradle.kts
- platform-sdk/swirlds-state-api/src/main/java/module-info.java
- platform-sdk/swirlds-state-impl/src/main/java/module-info.java
This PR adds missing dependencies that the dependency check randomly complaints about.
Part of #18591
> chore: Add missing dependencies

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/history/impl/HistoryLibraryImpl.java
Lazy initialize `SNARK_KEYS`
Addressed review comments on https://github.com/hiero-ledger/hiero-consensus-node/pull/18699
> chore: Lazy initialize `SNARK_KEYS`

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
- platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
Fix summary: direct backport of https://github.com/hiero-ledger/hiero-consensus-node/pull/18592 to the `release/0.61` branch.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18720
> fix: 18720: Backport the fix for 18571 to release 0.61

- .github/workflows/flow-pull-request-formatting.yaml
Cherry-picks 7fb871c Update flow-pull-request-formatting.yaml for release/0.61
Fixes #
**Checklist**
> chore: (cherry-pick) Update flow-pull-request-formatting.yaml

- .github/workflows/node-flow-deploy-release-artifact.yaml
Cherry-picks b4c06ec for release/0.61 to fix path in Update Hedera Protobufs step.
Fixes #
**Checklist**
> chore: (cherry-pick) adjust path to protobufs in 'Update Hedera Protobufs' step

- .github/CODEOWNERS
Cherry-picks df28487 for Updates to CODEOWNERS for tools-and-libs rename for release/0.61
Fixes #
**Checklist**
> chore: (cherry-pick) Update CODEOWNERS for tools-and-libs rename

- .github/CODEOWNERS
Cherry-picks 7e0f9e7 for release/0.61
Fixes #
**Checklist**
> chore: (cherry-pick) update codeowners with new team names

- platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
- platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java
- platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18813
> fix: 18813: VirtualMapLargeReconnectTest.multipleAbortedReconnectsCanSucceed is unstable

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064Tests.java
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18791
- Adds check to validate records that are only after the consensusTimestamp of the test to fix flakiness in the test assertions
> fix: Fix flakiness in HIP-1064 tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
Enhancing the test suite to validate that with bigger payload the gas cost increases.
Fixes #18275
```
Following our (https://docs.hedera.com/hedera/core-concepts/smart-contracts/gas-and-fees#intrinsic-gas), gas will be calculated based on the amount of intrinsic gas used for each kb of data.
Total gas = base gas + execution gas + callData gas per byte*
*callData gas  = 4 * (number of zeros bytes) + 16 * (number of non-zeros bytes)
For example, for a 100 kb callData (with 10K zero bytes and 90K non-zero), gas would be equal to 1480K gas.
```
This is how it's currently implemented(`CustomGasCalculator.transactionIntrinsicGasCost`); no need for change there. This PR adds enhancement to the HAPI test, verifying that the gas cost …
> test: assert the gas fees are more with bigger payload

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/EnsureAliasesStep.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustHbarChangesStepTest.java
* more coverage for `EnsureAliasesStep` and remove impossible to reach code.
* more coverage for `TransferExecutor` including `preHandle()`.
* slightly more coverage for `AdjustHbarChangesStep`
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/12987 partially
**Checklist**
> chore: 12987 more code coverage

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/QueryModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/TinybarValues.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/TinybarValuesTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/GasCalculationIntegrityTest.java
After #15098 was implemented there were configuration injections. that were not need anymore.
This PR clears those and aims to also fix the flaky tests in `GasCalculationIntegrityTest`
#15098 #10828 
Fixes #15337
**Checklist**
> fix: Remove unused injections and fix tests

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18835
> fix: Cherry-pick `transactionFee` fix for atomic batch transactions

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDb.java
- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18844
> fix: 18844: HDHM repair mechanism should not be enabled for snapshots

- hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidator.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
- hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
> fix: 0.61 cherry-pick: Correctly populate sysfiles with node info

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
Here is the link to the presentation for price calculation for HIP-1086: https://docs.google.com/presentation/d/1Ez-cWcG_Xl25vfsDuTrgg2n1iLSkFtrEfy4Te2VOepk/edit#slide=id.g349cce6607e_0_513 
According to the current gas calculator implementation we don't need to implement new fees logic for gas, so in the PR I've added checks that in case of positive cases we charge gas as expected, and in negative cases we don't charge gas for the transaction. 
_Just a note here_: 
How will gas be calculated for larger transactions?
Following our [current model](https://docs.hedera.com/hedera/core-concepts/smart-contracts/gas-and-fees#intrinsic-gas), gas will be calculated based on the amount of intrinsic gas used for each kb of data.
Total gas = base gas + execution gas + callData gas per byte* …
> test: Added gas check for jumbo transactions

- platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
- platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMapTest.java
Fix summary: `HDHM.repair()` is updated as proposed in #18903. A new unit test is provided.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18903
> fix: 18903: Tighten HDHM repair checks

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundMigrationTest.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/module-info.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/NodeConfiguration.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleApp.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNodeConfiguration.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleTestEnvironment.java
- platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/deterministic/DeterministicHeartbeatScheduler.java
This PR fixes the functionality that allows testing a migration with Turtle.
Fixes #18649
> chore: Implemented migration with Turtle framework

- hedera-node/docs/design/services/addressbook-service/addressbook-service.md
Adding the details from HIP-1046 to the existing documentation
Fixes #18748
> docs: HIP-1046 Update the technical design

- hedera-node/configuration/dev/log4j2.xml
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
- hedera-node/test-clients/build.gradle.kts
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SharedNetworkLauncherSessionListener.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/extensions/NetworkTargetingExtension.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/BlockNodeNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/simulator/BlockNodeSimulatorController.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/BlockNodeSimulatorOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSimulatorSuite.java
> chore: Decouple Block Node Simulators from SubProcessNetwork

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/BirthRoundStateMigration.java
> fix: migrate judge hashes on birth rounds

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/recordstreaming/RecordStreamingUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/impl/producers/formats/v6/BlockRecordWriterV6Test.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/BlockStreamAccess.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/StreamFileAlterationListener.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/EventualRecordStreamAssertion.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064Tests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064TestsDisabled.java
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18916
> chore: (cherry-pick) Write marker files for sidecars (#18916)

- hedera-node/test-clients/build.gradle.kts
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SharedNetworkLauncherSessionListener.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/EmbeddedNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/remote/RemoteNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/AddressBookUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecAccount.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/file/HapiGetFileContents.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetReceipt.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/network/HapiUncheckedSubmit.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/node/HapiNodeCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/util/HapiAtomicBatch.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CommonUpgradeResources.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableIntegrationTests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
Change HAPI tests part of hapiRestart to run with realm in shard taken from the `targetNetwork`
Fixes #
https://github.com/hiero-ledger/hiero-consensus-node/issues/18956
**Checklist**
> test: Realm and shard fixes for hapiRestart

- platform-sdk/consensus-otter-tests/src/testFixtures/java/module-info.java
Missing import was breaking CI for several PRs
Fixes #
**Checklist**
> fix: add required module to Otter tests test fixtures module info

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/BlockStreamModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockStreamStateManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/metrics/BlockStreamMetrics.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockStreamStateManagerTest.java
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18976
**Checklist**
> feat: additional block node communication metrics

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionCheckerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/JumboTransactionsConfig.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
Cherry-pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/18969
> feat: enable the jumbo transaction feature flag (cherry-pick)

- hapi/hedera-protobuf-java-api/src/main/proto/services/basic_types.proto
- hedera-node/configuration/mainnet/upgrade/feeSchedules.json
- hedera-node/configuration/previewnet/upgrade/feeSchedules.json
- hedera-node/configuration/testnet/upgrade/feeSchedules.json
- hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/BaseOperationUsage.java
- hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/consensus/ConsensusOpsUsage.java
- hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/consensus/SubmitMessageMeta.java
- hedera-node/hapi-fees/src/main/resources/canonical-prices.json
- hedera-node/hapi-fees/src/test/java/com/hedera/node/app/hapi/fees/usage/consensus/ConsensusOpsUsageTest.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonPbjConverters.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerTest.java
- hedera-node/hedera-file-service-impl/src/main/resources/genesis/feeSchedules.json
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiMessageSubmit.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18991
> feat: Implement fee changes for  HIP-991 (#18991)

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiClients.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/files/SysFileUploadCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/ConfigManager.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/SendSuite.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/StakeSetupSuite.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/SysFileUploadSuite.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/Utils.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/HapiSpecUtils.java
- hedera-node/test-clients/yahcli/run/build.sh
- hedera-node/test-clients/yahcli/run/publish.sh
Adds support for nonzero shard/realm to yahcli crypto transfer and sys file update functionalities. 
Closes #18983
> feat: Yahcli nonzero shard/realm implementations for crypto transfers and sys file updates

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsLibraryImplTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TssConfig.java
- Use acceptable CRS size for new library.
> fix: Update to respect 0.2.3-SNAPSHOT max CRS parties

- platform-sdk/consensus-utility/src/main/java/org/hiero/consensus/config/TransactionConfig.java
Part of #19102
Release 62 PR: https://github.com/hiero-ledger/hiero-consensus-node/pull/19104
> chore: increase transactionMaxBytes

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/util/HapiAtomicBatch.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
Fix nodeId setting for inner transactions in `test-clients`
Fixes #
**Checklist**
> fix: Inner transaction node setting in test-clients

- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/SendSuite.java
- hedera-node/test-clients/yahcli/run/build.sh
- hedera-node/test-clients/yahcli/run/publish.sh
> chore: Add `--inside-batch` option to `accounts send` 

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/SavepointStackImpl.java
- hedera-node/test-clients/build.gradle.kts
- hedera-node/test-clients/src/main/java/module-info.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/PlatformStateFacade.java
- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/NewStateRoot.java
> chore: 14803 state changes for virtual mega map blockstreams fix

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchHandleContext.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
> fix: Only use inner results for `BATCH_INNER` dispatches

- hedera-node/configuration/mainnet/upgrade/throttles.json
- hedera-node/configuration/previewnet/upgrade/throttles.json
- hedera-node/configuration/testnet/upgrade/throttles.json
> chore: Disable `AtomicBatch` prod throttles

- hedera-node/configuration/mainnet/upgrade/throttles.json
- hedera-node/configuration/previewnet/upgrade/throttles.json
- hedera-node/configuration/testnet/upgrade/throttles.json
> chore: Remove `AtomicBatch` from prod throttles

- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/logging/internal/InMemoryAppender.java
> fix: ConcurrentModificationException in InMemoryAppender

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
When parsing the staked account ID for any `HapiCryptoCreate` operation, a recent assumption was made that only numeric or fully-qualified account IDs were passed. This assumption is incorrect–accounts stored in the spec registry are also called and need to be supported. This PR fixes the errant assumption.
> fix: Correct HapiCryptoCreate staked account ID parsing

- platform-sdk/docs/base/configuration/configuration.md
- platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConverterService.java
- platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/ConfigApiTests.java
- platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/internal/ConverterServiceTest.java
If a converter of one of the by default supported types is added the config will use that one instead of the default converter.
> feat: overwrite default config converters

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolConsensusStateEventHandler.java
Fix race condition that did when setting the freeze round value
Fixes #19259
**Checklist**
> fix(19259): Fix race condition when setting freeze round value

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeCommunicationTestBase.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockStreamStateManagerTest.java
> fix: fix unit tests for `BlockStreamStateManager`

- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/keys/NewPemCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/FreezeAbortCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/FreezeOnlyCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/FreezeUpgradeCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/PrepareUpgradeCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/TelemetryUpgradeCommand.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/CostOfEveryThingSuite.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/FreezeHelperSuite.java
- hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/UpgradeHelperSuite.java
- hedera-node/test-clients/yahcli/run/build.sh
- hedera-node/test-clients/yahcli/run/publish.sh
Part of ongoing work to support nonzero shard/realm in yahcli, this PR modifies the remaining system commands. There's also a tiny codacy nit fix.
> feat: Support nonzero shard/realm in yahcli sys commands

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottle.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/AppThrottleFactory.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/DeterministicThrottleUsage.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/GasThrottleUsage.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/NetworkUtilizationManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleReqsManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleUsage.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/AppThrottleFactoryTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulatorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/impl/NetworkUtilizationManagerImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiMessageSubmit.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/EmbeddedVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/HRCTokenClaimTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java
- hedera-node/test-clients/src/main/resources/testSystemFiles/artificial-limits.json
Related to https://github.com/hiero-ledger/hiero-consensus-node/issues/19505
If the IngestWorkflowImpl fails after using throttle capacity (without submitting to consensus), reclaim the used capacity.
> chore: (cherry-pick for 0.61.8) Reclaim throttle capacity after ingest failure

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- Adds reporting to the `node-flow-deploy-release-artifact.yaml` file
- Fixes reporting issue in node-flow-build-application.yaml
- Rearranges `node-flow-deploy-release-artifact.yaml` to colocate tag and branch jobs.
Fixes #19533
> chore: Add error reporting to flow-deploy-release-artifact and fixes

- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
stop release 61 60 regression
N/A
> chore: stop release 61 60 regression

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiEventStorage.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/HashgraphPictureOptions.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/internal/HashgraphGuiControls.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/internal/HashgraphPicture.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/internal/PictureMetadata.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/internal/StandardGuiSource.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
> chore: switch hashgraph GUI to NGen

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
Testing ingest TPS and gas throttles extensivly
Fixes #
**Checklist**
> test: Extend throttle tests for HIP-551

- .github/workflows/node-flow-deploy-release-artifact.yaml
Fix a typo in the status reporting.
Fixes #19644
> ci: fix typo in status reporting

- hedera-node/configuration/mainnet/application.properties
- hedera-node/configuration/previewnet/application.properties
- hedera-node/configuration/testnet/application.properties
> chore: Remove overrides for 0.61.10

- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
This PR introduces a dedicated fork-join pool for `VirtualHasher`
Fixes #19648
> fix: 19648 Introduced dedicated ForkJoin pool for hashing.

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/AtomicTopicCustomFeeCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/AtomicTopicCustomFeeGetTopicInfoTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/AtomicTopicCustomFeeSubmitMessageTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/AtomicTopicCustomFeeUpdateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeBase.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AtomicBatchFuzzing.java
* Add test cases for validating the topic custom fees wrapped inside an atomic batch
Fixes #19532
> test: Consensus topic custom fees are charged as expected for batch transactions

- .github/workflows/node-flow-deploy-adhoc-artifact.yaml
Added new inputs ref/ref-name to AdHoc workflow that are required for the artifacts build workflow.
> chore: Added new inputs ref/ref-name to AdHoc workflow

- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/zxc-publish-production-image.yaml
This pull request updates several GitHub Actions workflows to improve artifact handling and clarify job names. The key changes include replacing artifact caching with artifact upload/download actions, removing unused code, and updating job names for clarity.
* Replaced `actions/cache` with `actions/upload-artifact` for uploading build artifacts in `node-zxc-build-release-artifact.yaml`. Updated the `path` and replaced `key` with `name` for artifact identification.
* Replaced `actions/cache` with `actions/download-artifact` for restoring build artifacts in both `node-zxc-build-release-artifact.yaml` and `zxc-publish-production-image.yaml`. Removed the `fail-on-cache-miss` option and updated artifact identification to use `name` instead of `key`. …
> chore: Update artifact caching to the upload/download-artifact actions

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/BlockStreamManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/ParentTxn.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/ParentTxnFactory.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/ParentTxnTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemTransactionsTest.java
- hedera-node/test-clients/src/main/resources/scheduled-contract-fees.json
> fix: Use independent dispatches for post-upgrade system work

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/FacilityInitModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/ExecutorComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
> fix: (0.63) Log active config *after* initializing props and permissions facilities

- hiero-dependency-versions/build.gradle.kts
- platform-sdk/base-crypto/src/main/java/module-info.java
- platform-sdk/consensus-otter-tests/build.gradle.kts
- platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/module-info.java
- platform-sdk/swirlds-common/build.gradle.kts
- settings.gradle.kts
Reverts hiero-ledger/hiero-consensus-node#19782
> chore: Revert build: bump org.hiero.gradle.build to 0.4.3

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenCreateCustomFeesTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenFeeScheduleUpdateSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenManagementSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenManagementSpecsStateful.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenMetadataSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenPauseSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/batch/AtomicTokenTransactSpecs.java
* Part 2 of 3 to add token edge cases wrapped in an atomic batch
Fixes #19757
> test: Edge cases - Token Service Tests Part 2

- .github/workflows/node-flow-deploy-adhoc-artifact.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
- gradle/aggregation/build.gradle.kts
(cherry picked from commit 9561cf53d9cfc24554bc7010fade4058e469ae44)
> chore: Cherry pick changes that update publishing mech to use central publishing portal (#19567)

- platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/ConsensusRoundListener.java
- platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/DockerApp.java
- platform-sdk/consensus-otter-docker-app/src/testFixtures/resources/log4j2.xml
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/HappyPathTest.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/KeysAndCertsConverter.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodeConsensusResultsAssert.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerNode.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeLogResultsImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/NodeResultsCollector.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/SingleNodeConsensusResultImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/SingleNodeLogResultImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/SingleNodePcesResultImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/junit/OtterTestExtension.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/logging/internal/InMemoryAppender.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleLogging.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/gossip/SimulatedGossip.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/gossip/SimulatedNetwork.java
> refactor: OtterTest container node clean-up

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/customfees/CustomFractionalFeeAssessorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/BalanceSnapshot.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
> chore: (0.63) Assess fractional fees relative to non-exempt credits and debits

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenCreateValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/token/NumericValidationTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
- Cherry-pick #https://github.com/hiero-ledger/hiero-consensus-node/pull/19878
> chore: (0.63) Restore 0.62 token auto-renew period validations

- hedera-node/configuration/mainnet/application-override.properties
- hedera-node/configuration/previewnet/application-override.properties
- hedera-node/configuration/testnet/application-override.properties
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19887
chore: Adds application-override.properties that are replica of file 121
> chore: (0.63) Adds `application-override.properties`

- .github/workflows/node-zxc-build-release-artifact.yaml
Fix a typo in the secret name
Fixes #19892
> ci: fix typo in secret

- settings.gradle.kts
Update hiero-gradle-conventions to v0.4.5
Fixes #19939
> fix(bug): update hiero-gradle-convention to v0.4.6

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
**Description**
This PR populates the new field in platform state that stores the latest freeze round. This value is used by the node to determine if an event was created with the current software version or an earlier one. Without this value, the platform thinks all events were created with the current version and it tries to checks the signatures in PCES events on the loaded state hash. Because the loaded state is modified on upgrade, the hash is changed, and the signatures no longer match. 
The Hedera app already sets this new latest freeze round value, but the Browser was not setting it for the testing apps. This PR adds the missing code.
Fixes #19906
Passing Run: https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/15978557090
> fix: Set latest freeze round in platform state from Browser

- .github/workflows/zxf-single-day-performance-test-controller.yaml
Shorten the description for skipping tag and notification checkbox on SDPT workflow.
Fixes #19918
> ci: shorten description for skip tag and notification on SDPT

- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
Updated SDPT with latest release of NLG 0.4.1 (Prometheus metrics in NLG)
Fixes #19938 
**Checklist**
20-hour SDPT
https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/15986205018/job/45153669820
n
(and other tests)
> test: NLG release 0.4.1 (with metrics support). Implements task #19938

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
Try to refactor the tests that were observed to hang the smart-contracts CI jobs
Fixes #19831 
**Checklist**
> fix: Mark some Jumbo Txn HAPI tests as repeatable

- platform-sdk/consensus-otter-tests/README.md
- platform-sdk/consensus-otter-tests/docs/getting-started.md
- platform-sdk/consensus-otter-tests/docs/turtle-environment.md
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/DocExamplesTest.java
This PR adds `turtle-environment.md`, which describes the Turtle environment in greater detail. It also fixes code references in the other documents. I just realized that the chosen approach does not work in markup documents, unfortunately.
Part of #19715
> docs: Added turtle-environment.md plus some minor improvements

- hedera-node/yahcli/build.gradle.kts
Yahcli's new build (inside its own module) doesn't include all the necessary files to run as a standalone process. This PR restores the appropriate source set. 
Closes #20030
> fix: Restore missing deps, META-INF files

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java
> fix: Fix SteadyStateThrottlingTest

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/JrsTestReaderReportCommand.java
> chore: update test URL for JTR

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java
> fix: (0.64) Query new account balance in throttling tests

- hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
> fix: Use `NFT_TRANSFERS_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE` as appropriate

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/module-info.java
Fixes a compile break from a bad merge
> fix: fix compile break

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/module-info.java
> chore: Disable node rewards before running `BalanceReconciliationValidator`

- .github/workflows/node-zxc-deploy-preview.yaml
Add a checkout step to deploy previewnet workflow to fix a bug.
Fixes #20172
> chore: add checkout to deploy preview workflow

- .github/workflows/zxcron-extended-test-suite.yaml
Updates the XTS report to use the new naming convention specified by SDCT.
Adds the short-commit ID to the XTS Report title
Closes #20187
> chore: Update XTS report name and add TCK regression status

- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
- Updates mantic to noble for Ubuntu
closes #20214
> chore: Update UBUNTU_TAG to noble-20250714

- .github/workflows/zxc-single-day-performance-test.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
Adds a new workflow
`zxf-single-day-performance-test-controller-adhoc.yaml` which allows users to manually run the SDPT flows
Updates zxc-single-day-performance-test to use the adhoc or single-day-perf-test latitude allocated resources
Updates promote-build-candidate to trigger SDPT with the ref input and use default parameters for 20 hour run.
closes #20192
> chore: Add single day performance test adhoc workflow

- platform-sdk/swirlds-benchmarks/grafana/run-docker.cmd
- platform-sdk/swirlds-benchmarks/grafana/run-docker.sh
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20231
> chore: 20231: Swirlds benchmarks grafana scripts are broken

- hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
Reverts hiero-ledger/hiero-consensus-node#20217
> revert: Update UBUNTU_TAG to noble-20250714

- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
Increased waiting timeout, added logging
Fixes #20264
**Checklist**
-Passed: https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/16376648289/job/46281378298
> test: fix of #20264 to increase timeout and to save logs in case of framework error

- .github/workflows/support/citr/Taskfile.examples.yml
- .github/workflows/support/citr/Taskfile.yml
- .github/workflows/support/citr/application.properties.txt
- .github/workflows/support/citr/init-containers-values7.yaml
- .github/workflows/support/citr/init-containers-values8.yaml
- .github/workflows/support/citr/init-containers-values9.yaml
- .github/workflows/support/citr/merkledb-values.yaml
- .github/workflows/support/citr/nlg-values.yaml
- .github/workflows/support/citr/settings.txt
- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
- .github/workflows/zxf-single-day-performance-test-controller.yaml
Cherry pick changes from `main` to `release/0.64` to support the Kubernetes labeling updates.
Fixes #20223 
**Testing**:
Successful test with latest on `main` here (1 hour test run):
https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/16375107286
This indicates the various pieces have been merged correctly.
> chore: (0.64) update CITR SDPT workflow for Kubernetes

- .github/workflows/zxc-execute-performance-test.yaml
(cherry picked from commit f90a8fe8bb8f4f591cfa7323700d7060e779102c)
closes: #20289
> chore: cherry pick final change for release/0.64 infra changes

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/batch/AtomicFileCreateSuite.java
This reverts commit a70b20a48a99b1f3afbd81d2c9f30d930df6437b.
Fixes #
https://github.com/hiero-ledger/hiero-consensus-node/issues/20300
**Checklist**
> fix: Revert Autorenew error code translation

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundFreezeTest.java
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/CheckingRecoveryTest.java
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/DocExamplesTest.java
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/HappyPathTest.java
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java
- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/SandboxTest.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Network.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Node.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/OtterAssertions.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodePlatformStatusResultsAssert.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/SingleNodePlatformStatusResultAssert.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/SingleNodePlatformStatusResultContinuousAssert.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerNode.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/AbstractNetwork.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodePlatformStatusResultsImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/NodeResultsCollector.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/SingleNodePlatformStatusResultImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/SingleNodeReconnectResultImpl.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodePlatformStatusResults.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/SingleNodePlatformStatusResult.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java
> chore: Rename results methods

- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
Fix summary: the unit test is rewritten. See #20324 comments for details.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20324
> test: 20324: VirtualMapTests.mapWithExistingHashedDataHasNonNullRootHash is flaky

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/AtomicTopicUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
This reverts commit f9c1e63eb10332f1d56dc21e88f57f2c3a398360.
Fixes #18973 
**Checklist**
> chore: revert `ConsensusUpdateTopicHandler` submitKey changes

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opsduration/OpsDurationThrottleTest.java
Fix ops duration related HAPI test that is failing in MATS
> test: fix flaky ops duration hapi test

- platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/VirtualMapState.java
- platform-sdk/swirlds-state-impl/src/test/java/com/swirlds/state/merkle/VirtualMapStateTest.java
This PR shortens state json by:
- converting singleton hashes to mnemonics
- removing singleton values;
Fixes #20402
> refactor: revisit state json

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
This pull request includes a minor update to variable names in the `CryptoTransferSuite` class within the `hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java` file. The changes replace `accountId1Key` and `accountId2Key` with `accountId1Val` and `accountId2Val`.
Fixes #20491 
**Checklist**
> chore: Update variable values to fix snyk

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/ProtocolConfig.java
Disable RPC sync due to suspicion of performance impact.
Fixes #20508
**Checklist**
> chore: Disable rpc sync before the release

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Network.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/AbstractNetwork.java
> chore: Implement network wide configuration in Otter

- .gitignore
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Revert the code that was updated and use new snyk config
Fixes #20497
> chore: Fix the snyk issues with consistent ignores

- hedera-state-validator/README.md
- hedera-state-validator/src/main/java/com/hedera/statevalidation/ExportCommand.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/JsonExporter.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/SortedJsonExporter.java
Added `sorted` mode required for the differential testing 
Added parameter to specify the output dir
Added parameter for pretty print (disabled by default)
Fixes #20383 
**Checklist**
> feat: 20383 `export` command improvement

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/NodeInfoImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/StateNetworkInfo.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneDispatchFactory.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneNetworkInfo.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriterTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/handlers/CrsPublicationHandlerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/StateNetworkInfoTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
- hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/file/HapiGetFileContents.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/AddressBookPojo.java
- platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/info/NodeInfo.java
> fix: (0.64) Include gRPC cert hash in synth `Node*` tx

- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-longevity-nlg-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
Update to teleport version 18.1.4.
Fixes #20620
> chore: upgrade to teleport version 18.1.4

- platform-sdk/consensus-otter-docker-app/src/testFixtures/docker/Dockerfile
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerImage.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerNode.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerNodeConfiguration.java
> refactor: Refactor Otter container file system structure

- hedera-node/configuration/mainnet/upgrade/throttles.json
- hedera-node/configuration/previewnet/upgrade/throttles.json
- hedera-node/configuration/testnet/upgrade/throttles.json
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AtomicBatchConfig.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/MiscellaneousFeesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
- hedera-node/test-clients/src/main/resources/testSystemFiles/mainnet-throttles-sans-reservations.json
- hedera-node/test-clients/src/main/resources/testSystemFiles/mainnet-throttles.json
- hedera-node/test-clients/src/main/resources/testSystemFiles/node-operator-throttles.json
- hedera-node/test-clients/src/main/resources/testSystemFiles/throttles-sans-mint.json
> feat: Re-enable batch transaction processing (HIP-551)

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/DocExamplesTest.java
This PR fixes the failing test `DocExamplesTest.testDeterministicBehavior`
Fixes #20760
> fix: Fix DocExamplesTest.testDeterministicBehavior

- hapi/hedera-protobuf-java-api/src/main/proto/platform/state/virtual_map_state.proto
- hedera-state-validator/README.md
- hedera-state-validator/src/main/java/com/hedera/statevalidation/ExportCommand.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/StateOperatorCommand.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/JsonExporter.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/SortedJsonExporter.java
- platform-sdk/swirlds-virtualmap/src/main/java/module-info.java
This PR backports following PRs: 
- https://github.com/hiero-ledger/hiero-consensus-node/pull/20528
- https://github.com/hiero-ledger/hiero-consensus-node/pull/20573
- https://github.com/hiero-ledger/hiero-consensus-node/pull/20622 
- https://github.com/hiero-ledger/hiero-consensus-node/pull/20700
Fixes #20750 
**Checklist**
> chore: 20750 `export` command backport

- .github/workflows/zxcron-extended-test-suite.yaml
Adds the github action `rootly-incident-action` to generate a rootly incident with an alert during CITR pipeline failures
Closes #20771
> ci: Integrate rootly incident action with XTS workflows

- hedera-state-validator/src/main/java/com/hedera/statevalidation/validators/merkledb/StateAnalyzer.java
Implements short (2-bit) counts in duplicate counting code.
This change is required to validate large states created during longevity testing and will be used from the branch if not merged. Real life states are not large enough to depend on this fix.
Fixes #20788
See also #20792 (port to 0.65)
**Checklist**
> fix: validator runs out of memory on large states

- hedera-state-validator/src/main/java/com/hedera/statevalidation/ExportCommand.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/JsonExporter.java
- hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/SortedJsonExporter.java
This PR adds some console output that helps with tracking progress of the export.
Fixes #20823
**Checklist**
> feat: 20823 Added progres input to `export` command

- .github/workflows/zxc-json-rpc-relay-regression.yaml
This PR refines the zxc-json-rpc-relay-regression workflow to properly support XTS (Cross-Technology Suite) tests and removes unnecessary dependencies to streamline the CI process.
Fixes #
**Checklist**
> ci: refine JSON-RPC relay regression workflow for XTS tests

- .github/workflows/zxc-single-day-longevity-nlg-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
- .github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
- .github/workflows/zxf-single-day-longevity-test-controller.yaml
This pull request updates several GitHub workflow files to enhance reporting and notification for longevity test jobs, improve integration with Rootly for incident management, and clarify test asset handling. The changes introduce new Rootly alerting and incident creation steps, improve output and summary reporting, and update job and variable names for consistency.
**Longevity Test Workflow Improvements**
* Added Rootly alerting and incident creation to the longevity test workflow (`zxc-single-day-longevity-nlg-test.yaml`), including detailed summaries and conditional alerting based on job results. This improves visibility and incident tracking for failed longevity test runs. [[1]](diffhunk://#diff-befdc1fa53221eeedd361cfdf3addfb464624172fdcee35a0b5dece213e372f1L555-R656) …
> ci: Add rootly integration to SDLT

- .github/workflows/zxcron-extended-test-suite.yaml
Require the TCK test pass for XTS pass tag to be applied.
Fixes #20769
> ci: require TCK test pass for XTS pass tag

- .github/workflows/zxc-block-node-regression.yaml
- Added custom MN image
- Commented out sections that will fail for now, so we can test the rest of the flow
- added version to Block Node helm chart to use latest
Fixes #
**Checklist**
> ci: Filling the gaps for Solo to able to run an e2e test using BN

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/containers/BlockNodeContainer.java
- Fixed health check in BlockNodeContainer constructor.
- Fixed gRPC port.
- Separated gRPC and health check ports.
> fix: BN container health check and ports

- .github/workflows/zxc-json-rpc-relay-regression.yaml
This PR reverted the kind versions used previously
Fixes #
**Checklist**
> fix: use stable kind versions

- .github/workflows/zxc-block-node-regression.yaml
- Fixes MN override value to produce expected yaml file, so MN can be launched in BN mode
- Fixes grpcurl command by defining correctly the working dir of the step
> ci: Fixed MN override values and grpcurl

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/containers/BlockNodeContainer.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/simulator/BlockNodeController.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/BlockNodeOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/BlockNodeVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSuite.java
Fixed testBlockBufferBackPressure, added BN container pause/unpause ops.
> fix: fixed testBlockBufferBackPressure, added bn container pause/unpause

- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxf-dry-run-extended-test-suite.yaml
> fix: restored mirror node regression panel

- platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java
> fix: Attempted fix of flaky Otter reconnect test

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
Adds a test that verifies a question from our HIP-551 final code review
> test: Verify batch inner txn time range

- .github/workflows/flow-generate-release-notes.yaml
- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/support/scripts/process_json_release_notes.py
- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-longevity-nlg-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
- .github/workflows/zxcron-extended-test-suite.yaml
- .github/workflows/zxcron-promote-build-candidate.yaml
- .github/workflows/zxf-prepare-extended-test-suite.yaml
- .github/workflows/zxf-single-day-canonical-test.yaml
- .github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
- .github/workflows/zxf-single-day-longevity-test-controller.yaml
- .github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
- .github/workflows/zxf-single-day-performance-test-controller.yaml
Cherry picks the following into release/0.65
- #18149
- #20765
- #20805
- #20815
- #20822 
- #20827 
- #20837
- #20844
- #20849 
- #20869 
- #20899 
- #20905 
- #20912
- #20939 
- #20955 
- #20964 
This adds rootly integration and updates the NLG version.
Fixes #20956
> chore: cherry pick required citr changes

- .github/workflows/zxf-dry-run-extended-test-suite.yaml
Add missing secrets to XTS dry run workflow
Fixes #20974
> ci(fix): Add missing secrets to XTS Dry Run workflow

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/app/OtterExecutionLayer.java
- platform-sdk/consensus-utility/src/main/java/module-info.java
- platform-sdk/consensus-utility/src/main/java/org/hiero/consensus/transaction/TransactionPoolNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/ExecutionLayer.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/NoOpExecutionLayer.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/DefaultSwirldMain.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
> chore: add back health check to transaction pool

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/EthereumSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/batch/AtomicEthereumSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/AtomicSmartContractServiceFeesTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/SmartContractServiceFeesTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
Revert feature flags for turning on HIP-1249.  Also revert feature to refund at max 80 of gas limit.
> fix: revert hip 1249

- .github/workflows/zxc-execute-performance-test.yaml
- .github/workflows/zxc-single-day-longevity-nlg-test.yaml
- .github/workflows/zxc-single-day-performance-test.yaml
Fixed HeliSwap benchmark
**Related issue(s)**:20990
Fixes #
**Checklist**
> test: NLG 0.6.3

- hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/YahcliCommandParamsTest.java
- hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/fees/FeesCommandTest.java
Add yancli unit tests for FeesCommand 
https://github.com/hiero-ledger/hiero-consensus-node/issues/20996
Fixes #20996 
**Checklist**
> test: Command Params: FeesCommand #20996

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/SchedulingConfig.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/DisabledLongTermExecutionScheduleTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchRepeatableTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/RepeatableStakingTests.java
> fix: Add `scheduling.maxExpirySecsToCheckPerUserTxn`

- hedera-state-validator/src/main/java/com/hedera/statevalidation/blockstream/BlockStreamRecoveryWorkflow.java
Fixes a compilation issue
Fixes #20809 
**Checklist**
> fix: 20809 Fixing a compilation issue

- .github/workflows/zxc-single-day-performance-test.yaml
To use abs diff instead of percentage that may show wrong status when rounded to 0%
Fixes #21164
**Checklist**
> test: fix of 21164 (to use abs diff value instead of rounded percentage)

- hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/nodes/NodesCommandTest.java
Adds unit tests for `NodesCommand`
Fixes [#20999](https://github.com/hiero-ledger/hiero-consensus-node/issues/20999)
**Checklist**
> test: Add nodes command params tests

- hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/schedule/ScheduleCommandTest.java
Adds unit tests for `SignCommand` 
Fixes #21000 
**Checklist**
> test: Add Yahcli schedule param unit tests

- platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/DockerManager.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerNode.java
- platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/utils/ContainerConstants.java
Fix #21267 
see https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/18158051523/artifacts/4152865619
> chore: Make CSV metric files available after container run

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSuite.java
This PR fixes a suite test in regards to BN communication
Fixes #
**Checklist**
> fix: Fix suite test on main

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSuite.java
- Fixed failing unit tests and increased coverage in BlockNodeConnectionManagerTest
- Added assertions to node0SupportsDynamicBlockNodeConnectionInfo()
> chore: improved tests related to dynamic updates of block-nodes.json
