hiero-ledger/hiero-consensus-node

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmContext.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmTransactionFactoryTest.java
hedera-node/test-clients/src/itest/java/ConcurrentSuites.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallHapiOnlySuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java

Ethereum contract calls have an amount - the amount of the native currency to transfer. In Ethereum this amount is unsigned. But as a recent regression we are interpreting this amount as signed (2's complement), leading to failure when the amount's high-order bit is 1.
Bug was introduced in https://github.com/hashgraph/hedera-services/pull/12834.
Fix is to (manually) revert the particular change that treats these amounts as signed.
As a freebie code cleanup also renamed constants `WEIBARS_TO_TINYBAR` to `WEIBARS_IN_A_TINYBAR` to reflect their actual semantic meaning.
Fixes #13816
**Checklist**

fix: Ethereum contract calls where high-bit of amount is set, fail

---

.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/node-zxc-compile-application-code.yaml

Removes integration tests step from node-flow-pull-request-checks
Per [Freshdesk ticket 3065](https://swirldslabs.freshdesk.com/a/tickets/3065) we've removed e2e tests and integration tests from the Node: PR Checks flow.
Fixes #13838

ci: Removes e2e tests & Integration tests step from node-flow-pull-request-checks

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmContext.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmTransactionFactoryTest.java
hedera-node/test-clients/src/itest/java/ConcurrentSuites.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallHapiOnlySuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java

Cherry pick of 9bfc581:
Ethereum contract calls have an amount - the amount of the native currency to transfer. In Ethereum this amount is unsigned. But as a recent regression we are interpreting this amount as signed (2's complement), leading to failure when the amount's high-order bit is 1.
Bug was introduced in https://github.com/hashgraph/hedera-services/pull/12834.
Fix is to (manually) revert the particular change that treats these amounts as signed.
As a freebie code cleanup also renamed constants `WEIBARS_TO_TINYBAR` to `WEIBARS_IN_A_TINYBAR` to reflect their actual semantic meaning.
Fixes #13816
**Checklist**

fix: (cherry pick to 0.51) Ethereum contract calls where high-bit of amount is set, fail

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AccountsConfig.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java

Fixes #13855
Increases accounts and NFTs to 40 million each, and increases the number of rounds kept in memory from 500 to 1500.
**Checklist**

chore: Increase default to 40 million each

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/utils/SynthTxnUtilsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoCreateUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java

Due to mono service fidelity, the parent contracts attributes were copied for externalizing the record in the hollow creation flow for contracts.  If the contract frame does not have a contract parent then handle with default values.
**Checklist**

fix: address null pointer exception in hollow contract flow

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingUtilities.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

fix: work around missing `clearOneOfType()` method on PBJ builder

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.reports.gradle.kts

Fixes this publishing error:
>Could not determine the dependencies of task ':closeSonatypeStagingRepository'.
> Task with path ':reports:releaseMavenCentral' not found in root project 'hedera-services'.
**Checklist**

build: Make sure also 'reports' has all expected lifecycle tasks

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.reports.gradle.kts

Cherry-pick fix for gradle task :reports:releaseMavenCentral into release/0.51
Fixes error: `Could not determine the dependencies of task ':closeSonatypeStagingRepository'.`

fix: Cherry pick 11381 for 0.51

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QueryHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ProxyWorldUpdater.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ProxyWorldUpdaterTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/utils/SynthTxnUtilsTest.java

When finalizing a contract create onto a hollow account, for externalization purposes, only set the adminKey to be the contract key.

feat: remove attributes when externalizing finalized hollow contract

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

fix bug issue that happened in testnet when negative less than -1 stakednodeid happened it fires incorrect exception
Fixes #13961

fix: negative Id for StakedNodeId in token service. less than -1

---

settings.gradle.kts

- Fix failing Prepare Release [Tag] CI Job : We still require the tag version to match the hapiProtoVersion specified 
- Run TAG_MAJOR="$(semver get major "v0.52.0-alpha.0")"
Fixes #13935 
**Checklist**

chore: Upgrade settings to 0.52

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

Verify `maxAutomaticAssociations` is set to -1 in `CryptoTransferSuite`. 
Fixes #
**Checklist**

test: HIP-904 Verify max automatic associations with -1

---

.github/workflows/node-zxc-build-release-artifact.yaml
block-node/blocknode-core-spi/build.gradle.kts
block-node/blocknode-core/build.gradle.kts
block-node/blocknode-filesystem-api/build.gradle.kts
block-node/blocknode-filesystem-local/build.gradle.kts
block-node/blocknode-filesystem-s3/build.gradle.kts
block-node/blocknode-grpc-api/build.gradle.kts
block-node/blocknode-state/build.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.nexus-publish.gradle.kts

Pulls changes from `release/0.51` into `develop` to update the publishing steps to maven central such that they use the new credentials for both `SVCS_OSSRH` and `PLATFORM_OSSRH`.

build: split publish of 'platform' and 'services' / do not publish blocknode 

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java

There's been confusion over the `EthTxData` fields `recId` and `v`.  Add comments to the code to guide future readers.  (This came up in looking at issues w.r.t. EIP-155.)
Fixes #13390
**Checklist**
- [N/A] Tested (unit, integration, etc.)

docs: Add comment to explain `recId` and `v` fields of `EthTxData`

---

hedera-node/configuration/dev/bootstrap.properties
hedera-node/configuration/preprod/bootstrap.properties

for:
* #14042
- **fix throttle path for dev bootstrap.properties**
- **fix throttle path for preprod bootstrap.properties**
Do we also need to update the compose boostrap.properties too?
https://github.com/hashgraph/hedera-services/blob/c958c4de5a29715e5732863b190bb96915138bb2/hedera-node/configuration/compose/bootstrap.properties#L1

fix: update bootstrap.throttleDefsJson.resource path for bootstrap.properties for dev and preprod

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/GrpcUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCancelAirdrop.java

Added `HapiTokenCancelAirdrop` operation and exposed it to `TxnVerbs`
Fixes #13949 
**Checklist**

feat: HIP-904: Add `TokenCancelAirdrop` transaction verb for `test-clients`

---

.github/CODEOWNERS

Update smart contract directory owners to allow for focused reviewers  
- Set `hedera-smart-contracts-core` as codeowners in `CODEOWNERS`
Fixes #14153 
**Checklist**

chore: Update codeowners for smart contracts contributors

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/CustomGasCalculator.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawTranslator.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawTranslatorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/IsAuthorizedSuite.java

Chooses gas requirement for `isAuthorizedRaw` based on whether you're verifying an EC key (3000) or an ED key (1.5M).
Fixes #14156 
**Checklist**

fix: HAS.isAuthorizedRaw: Choose proper gas amount for EC vs ED signature verification

---

.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/zxc-jrs-regression.yaml
hedera-node/test-clients/build.gradle.kts
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/StakingSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/StartStaking.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/SetupStakeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/StakeSetupSuite.java
hedera-node/test-clients/yahcli/run/build.sh

- Closes #14184 
- Only builds `yahcli` and `SuiteRunner` JARs during PR checks as needed, not every `assemble`.

fix: yahcli reward rate; build `SuiteRunner` and `yahcli` JARs only as needed

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/IsAuthorizedSuite.java

**Description:**:
`isAuthorizedRaw`, a system contract method, should take all offered gas when it fails due to bad input.
(Note that give a valid account, message (hash), and signature it is _not_ a failure for the signature to not be valid for that message + account.  But if the account doesn't _exist_ that's bad input and that is a failure.)
Fixes: #14209
**Checklist**

fix: `isAuthorizedRaw` to take all gas on bad input

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/IsAuthorizedSuite.java

Fix should be in 0.52 as well:
isAuthorizedRaw, a system contract method, should take all offered gas when it fails due to bad input.
(Note that give a valid account, message (hash), and signature it is not a failure for the signature to not be valid for that message + account. But if the account doesn't exist that's bad input and that is a failure.)
**Related issue(s):**
Fixes #14217 
Relates to: #14209, #14210 
**Checklist**

fix: cherry-pick, to 0.52, #14210 isAuthorizedRaw to charge all gas on failure

---

hedera-node/hedera-file-service-impl/build.gradle.kts
hedera-node/hedera-file-service-impl/src/main/java/module-info.java
hedera-node/hedera-file-service/build.gradle.kts
hedera-node/hedera-token-service-impl/build.gradle.kts

Removed `-Xlint:-*` compilerArgs from hedera-file-service and hedera-file-service-impl which would disable warnings for those names.
Only issue was requiring transitive for java.compiler in the file service impl `module-info.java`
Fixes #14213 
**Checklist**

chore: File Service compiler warning fixes

---

.github/workflows/node-zxc-build-release-artifact.yaml
gradle/plugins/src/main/kotlin/com.hedera.gradle.lifecycle.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.nexus-publish.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.platform-publish.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.services-publish.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.versions.gradle.kts

...rather than changing task dependencies.
With this change, we can still call ALL tasks of a certain publishing profile. E.g, we can do 'releaseMavenCentral' or 'releaseDevelopCommit' (without leading ':'). This is less risky of breaking if Gradle is called wrongly. And, more importantly, it allows us to again call all tasks that publish to CGP repositories (not Nexus) and only exist in the _platform_ projects.
Same as #14160 but for **develop**
**Checklist**

build: filter publishing by deactivating tasks (develop)

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java

Require admin key for maxAutoAssociations during contractUpdate
Fixes #14111 
**Checklist**

feat: require admin key for maxAutoAssociations during contractUpdate

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/stats/ReconnectMapMetrics.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/stats/ReconnectMapStats.java

Log the stats collected in `ReconnectMapStats`.
While an implementation of the `ReconnectMapStats` interface, such as the `ReconnectMapMetrics`, emits actual metrics already, it is still useful to also log the accumulated stat values once the reconnect is finished. This simplifies analyzing the metric values in a situation when the metrics are not published to Grafana directly, for example, when running a test on a developer branch locally or in a custom test network.
Fixes #13749
Trivial changes simply adding extra logging.
**Checklist**

feat(reconnect): log ReconnectMapStats

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRejectHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenRejectSuite.java

Fixes #14271 
Removed allowances modification on `TokenReject`

chore: Removed allowances modification on `TokenReject`

---

hapi/build.gradle.kts
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonPbjConverters.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateNftsHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateNftsSuite.java

This PR implements the functionality required for [HIP-850](https://hips.hedera.com/hip/hip-850) 
Enhancing Supply Key Functionality for NFT Updates in Treasury Account. Specifically enabling the Supply Key to update an NFT metadata field while the NFT is held in the treasury account
See https://github.com/hashgraph/hedera-protobufs/pull/394
for protobuf changes (new `ResponseCodeEnum` value).
Fixes #14109 
**Checklist**

feat: HIP-850: HTS mutable metadata in treasury

---

hapi/build.gradle.kts

This PR changes the branch for cloneHederaProtobufs back to "main" after the merge for HIP-850.
#14109 
Fixes #
**Checklist**

chore: HAPI cloneHederaProtobufs back to main

---

hedera-dependency-versions/build.gradle.kts
platform-sdk/swirlds-logging/build.gradle.kts

Follow up to #11656.
The removed statement added 'commons.compress' to the runtime **and compile** classpath of ALL modules. That's not needed and conceptually wrong. To update the version, the other changes of #11656 are sufficient.
#11656
**Checklist**

fix: remove hard dependency on 'commons.compress'

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java

Description:
One line fix of incorrect condition in deserialize method. Introduced with https://github.com/hashgraph/hedera-services/pull/14231
Relates to https://github.com/hashgraph/hedera-services/issues/14230

fix: 14230 Fixed incorrect deserialization of `PlatformState`

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/communication/ProtocolNegotiatorThread.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/NetworkUtilsTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/communication/multithreaded/TestNegotiator.java

Add a RateLimiter and log the stack trace of socket exceptions once a minute.
Fixes #14304
Trivial changes to improve logging and diagnostics.
**Checklist**

feat: log socket exception stack trace periodically

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureVerificationFutureImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ServiceApiFactory.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HederaOperations.java

Fixes warnings given by the `javadoc` tool. 
In preparation for #13645
**Checklist**

chore: fix Javadoc warnings in 'services' modules

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/WorkingDirUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecContract.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/upgrade/BuildUpgradeZipOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip583/CreateWithAliasDisabledTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/LifecycleTest.java

Fixes warnings given by the `javadoc` tool. 
In preparation for #13645
**Checklist**

chore: fix Javadoc warnings in 'test-clients'

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/permits/SyncPermitProvider.java

Fixing a bug discovered by @lpetrovic05 in `SyncPermitProvider` by moving a `sleep()` call outside of a `synchronized {}` block to allow other threads to acquire the lock and eventually satisfy the waiting condition.
Fixes #14094
This is a timing issue that is difficult to reproduce consistently, therefore there's no any new tests. Existing unit tests in `swirlds-platform-core` pass though.
**Checklist**

fix(gossip): wait outside of lock

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetEventCreator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/DefaultEventHasher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/PbjHasher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/StatefulEventHasher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/UnsignedEventHasher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventConfig.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/RandomEventUtils.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java

feat: add new event hashing algorithm

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.jpms-modules.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.protobuf.gradle.kts

- Activates Javadoc lint checks (except _missing_) and fail on problems as part of `qualityGate`
Related:
- #14337 
- #14338
- #14339
#11569
**Checklist**

build: activate more Javadoc lint checks and fail on problems

---

hedera-node/infrastructure/grafana/dashboards/production/platform/reconnect.json

Adding new ReconnectMap metrics to the Reconnects dashboard in Grafana.
A few minor, unrelated changes in the diff are due to the fact that the dashboard was modified by other engineers in Grafana manually prior to me starting working on this issue, so its definition in Grafana slightly differed from what is currently present in the repository. Per a suggestion from @poulok , I used the current Grafana dashboard as the source of truth to start my fix.
Please note that I'm unsure why the charts don't show node ids. I used the exact same template as used for the "Reconnect Teachers" chart above the new charts, and it shows the node labels. If you know how to make the node ids visible in the legend and on the charts, please suggest proper changes in my diff (I'm not a …

feat(reconnect): add Grafana dashboard for new ReconnectMap metrics

---

.github/CODEOWNERS

Fixes #14403 
Proposal this work is based on:[ platform-sdk/docs/proposals/TSS-Library/TSS-Library.md](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/TSS-Library/TSS-Library.md)
```
No new projects should be published under the `com.swirlds` namespace prefix or Maven Group ID. This should be a `com.hedera.cryptography` namespace prefix and `com.hedera.cryptography` Maven Group ID.
```
_Originally posted by @nathanklick in https://github.com/hashgraph/hedera-services/pull/14307#pullrequestreview-2191679889_

chore: include hedera-cryptography in code owners

---

hedera-node/docs/design/services/smart-contract-service/evm-transaction-response-codes.md

This PR adds a doc with possible response codes for failed smart-contract EVM transactions that could be propagated to the top-level status.
Fixes #14207 
**Checklist**

docs: add evm-transaction-response-codes.md

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

updates crazy-max/gh-action-setup-docekr to include registry mirrors
Fixes #14466

ci: Add registry mirrors to daemon-config on crazy-max/ghaction-setup-docker

---

docs/glossary.md

Update definitions of alias - there are several different kinds - and triplets.
**Checklist**
- [N/A] Tested (unit, integration, etc.)

docs: Update glossary defns of aliases, triplets

---

hedera-node/configuration/dev/settings.txt

- Until changes in event hashing are enabled, an upgrade with `event.migrateEventHashing=true` will expect the PCES events to be in a `v0.52` format and fail otherwise.
- This PR updates dev configuration _settings.txt_ to set `event.migrateEventHashing=false`.

fix: add `event.migrateEventHashing=false` override to upgrade `@HapiTest`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java

Fixes https://github.com/hashgraph/hedera-services/issues/14389
Cherry-pick #14498 
Adds config to disable frontend throttles for testing

chore: (cherry-pick) Add config to disable frontend throttles (#14498)

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.evm-publish.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.jpms-module-dependencies.gradle.kts

The `hedera-evm` and `hedera-evm-impl` modules were attempting to publish under both com.hedera and com.swirlds. This PR corrects that issue.
Fixes #14474
**Additional information**: 
This change will also need to be pulled into release/0.53 and develop

ci: fix gradle publish failures in release-0.52 for hedera.com.evm

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.root.gradle.kts

Fixes issue in versionAsSpecified task where the exception is always thrown in the property definition.
Fixes #14537

fix: Fixes issue with newVersion not being specified in versionAsSpecified Task

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.evm-publish.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.jpms-module-dependencies.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.root.gradle.kts

From release/0.52 branch: Enables publishing of `com.hedera.evm` exclusively under `com.hedera` instead of under both `com.hedera` and `com.swirlds`
From release/0.53 branch: Enables the versionAsSpecified Check to run successfully
Fixes #14543

ci: Cherry pick release fixes into develop

---

hedera-node/data/config/application.properties
hedera-node/data/config/bootstrap.properties
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/cache/CacheWarmer.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/CacheConfig.java

Rename of property `cache.cryptoTransfer.warmThreads` since the number of threads used to warm the memory is global and is not dependent on an any individual transaction type.
Fixes #12770 
**Checklist**

chore: Renaming Warm Threads Cache Property

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/SimpleFreezeOnly.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java

- Closes #14520 
- Instead of calling `VirtualMap#registerMetrics()` only at the moment of creating an _absent_ node in `MerkleStateRoot#putServiceStateIfAbsent()`, does this work in an initialization callback that receives the node for the state being defined, no matter if present or absent at beginning of the call.

fix: move `VirtualMap#registerMetrics()` call to a node initializer

---

.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

Removes the daemon config lines for setting up registry mirrors 
Fixes #14598
** Notes for Reviewer**:
Devops-CI and Release Engineering are still looking at alternatives to build in stability for the docker-determinism checks =

fix(bug): Removed daemon config changes

---

.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

Cherry picks reversion of docker mirror registry changes into release/0.52
Fixes #14601

fix(bug): Removed daemon config changes (#14599)

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateNftsHandlerTest.java

This PR fixes `TokenUpdateNftsHandler` to not throw a `HandleException` when the Token or Nft cannot be retrieved. Instead a `PreCheckException` will be thrown.
#14204 
Fixes #14595 
**Checklist**

fix: TokenUpdateNftsHandler throwing HandleException in preHandle

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateNftsHandlerTest.java

Cherry pick of fix from release 53 branch.
This PR fixes TokenUpdateNftsHandler to not throw a HandleException when the Token or Nft cannot be retrieved. Instead a PreCheckException will be thrown.
Fixes #14595 
**Checklist**

fix: cherry-pick: TokenUpdateNftsHandler throwing HandleException in preHandle

---

hedera-node/hedera-addressbook-service-impl/build.gradle.kts
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeCreateHandler.java
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidator.java
hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/CertificatePemTest.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/AddressBookTestBase.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeDeleteTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/UpdateAccountEnabledTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java

Add X509Certificate check for gossipCaCertificate field in nodeCreate and nodeUpdate.
Fixes #14603 
**Checklist**

feat: added X509Certificate validation for NodeCreate and NodeUpdate

---

platform-sdk/swirlds-jasperdb/src/hammer/java/com/swirlds/merkledb/MerkleDbDataSourceHammerTest.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbCompactionCoordinator.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListOffHeap.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java

Fix summary:
* `MerkleDbDataSource.saveRecords()` now handles dirty and deleted leaves in a separate thread / executor
* On close, MerkleDb data source shuts down this executor and waits for it to complete. This is required to make sure no read / write operations are running, when data files and indices are closed
* Compaction coordinator is also improved to wait till all compaction tasks are fully stopped on shutdown
* Minor improvements like closing data files before the corresponding indices
Testing:
* A new hammer test is introduced
Fixes: https://github.com/hashgraph/hedera-services/issues/14567

fix: 14567: Interrupt reading from data files gracefully when the data source is closed

---

.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

This PR migrates the `ghaction-setup-docker` to the step-security maintained version
Fixes #14296 
**Checklist**

chore: migrate ghaction-setup-docker to step-security maintained

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/listeners/ReconnectListener.java

- Closes #14615 
- When constructing the app Dagger component, _if_ it is already non-null, then:
* First, unregister the old component's listeners with the platform `NotificationEngine`; then,
* Immediately register the new component's listeners.
- This ensures that the listener that receives [this](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ReconnectStateLoader.java#L165) `ReconnectCompleteNotification` is for the latest Dagger component.
- Also switches `ReconnectListener` to simply use the state from the notification instead of `WorkingStateAccessor`.

fix: get notification listeners up-to-date before `RECONNECT_COMPLETE`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/AppSignatureVerifierTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DispatchProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java

- Closes #14610 
* In `DispatchProcessor`, if an `EthereumTransaction` is throttled, ensures the record still has the `ethereum_hash` by calling a new `handleThrottled()` method on the `EthereumTransactionHandler`.

fix: still set record `ethereum_hash` on `CONSENSUS_GAS_EXHAUSTED`

---

hapi/hedera-protobufs/block/stream/output/state_changes.proto
hapi/hedera-protobufs/services/state/blockstream/block_stream_info.proto

* Fixed _protobuf_ package for blockstream file
* Added missing specification text
* Fixed bad copyright header in the recently added file
* Made some minor ordering changes to an _advisory_ enum.

fix: Small adjustments to recently added inert protobufs

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

* Updates Docker Daemon configuration to use the registry mirror
* Updates BuildKit configuration to use the registry mirror
* Closes #14774 
* `release/0.52`
* `release/0.53`

chore: updates the buildkit and docker daemon configuration to use the registry mirror

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

* Cherry picks #14774 into the `release/0.53` branch
* Closes #14774 
* `release/0.52`

chore(0.53): updates the buildkit and docker daemon configuration to use the registry mirror

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

* Cherry picks #14774 into the `release/0.52` branch
* Closes #14774

chore(0.52): updates the buildkit and docker daemon configuration to use the registry mirror

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/dispatch/ChildDispatchFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/TriggeredFinalizeContext.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/TriggeredFinalizeContextTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransferListAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java

- Without the complete HIP-993 implementation, we need a special case to finalize the transfer list in a scheduled `CryptoTransfer` that triggers an auto-creation.
- Note this special case was eliminated by the completion of HIP-993 changes in `release/0.53`.

fix: immediately finalize transfer lists for scheduled crypto transfer

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java

On token airdrop reject only tokens with royalty with fallback fees, for tokens with custom fees.
https://github.com/hashgraph/hedera-services/issues/14794
Fixes #
**Checklist**

fix: reject tokens only with royalty with fallback fee

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java

(AIRDROP - 59) Given sender is a deleted account when it attempts to sign a tokenAirdropTransaction then the transaction should fail.
Fixes #14578
**Checklist**

fix: Add test with deleted sender account

---

hapi/hedera-protobufs/block/stream/output/state_changes.proto

* Removed old "entity number" style messages from state changes
* Replaced with recommended alternatives.
* Removed state change cause
Mirror of [hedera-protobuf PR 408](https://github.com/hashgraph/hedera-protobufs/pull/408)

chore: Mirror state change updates from protobuf repo

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java

Implement two tests:
-Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for 1 FT A, that he got dissociated from.
-Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for 1 NFT A, that he got dissociated from.
Fixes #14820 
Fixes #14821

test: 14820 14821 token dissociate hapi tests for token claim

---

.github/CODEOWNERS

Add codeowners for the /hapi directory. Previously this was not specified and defaulted to devops-ci and release-engineering-managers
Fixes #14724

chore: Add codeowners for the /hapi directory

---

hedera-node/configuration/mainnet/upgrade/feeSchedules.json
hedera-node/configuration/testnet/upgrade/feeSchedules.json

Fixed invalid feeSchedules.json in both testnet and mainnet directories

fix: invalid `feeSchedules.json`

---

hedera-node/hedera-util-service-impl/build.gradle.kts
hedera-node/hedera-util-service-impl/src/main/java/module-info.java
hedera-node/hedera-util-service/build.gradle.kts

Removed `tasks.withType<>...` line from `build.gradle.kts` files in `hedera-util-service` and `hedera-util-service-impl` which disables warnings for those packages.
- In service-impl `module-info.java` file java.compiler is changed from `static` to `transitive` 
Fixes #14866 
**Checklist**

chore: Fix compiler warnings in util-service and util-service-impl

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomContractCreationProcessor.java
hedera-node/test-clients/SpecCookbook.md
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/SpecEntity.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java

SELFDESTRUCT opcode wasn't deleting contracts when it should.  An unnoticed BESU update needed to be made in our override classes.
Also:  For the HAPI test suite adds an easy way to create multiple entities (accounts, contracts, ...) at a deterministic time and in order.  Useful for some test cases where you need to predict entity numbers for entities created by smart contracts (e.g., via contract create, or HTS).
Fixes #14835
**Checklist**

fix: SELFDESTRUCT now deletes contracts properly

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java

Currently the memo of "Synthetic system creation" for genesis crypto accounts are only externalized in the record stream via a TransactionRecord, the TransactionBody itself does not contain the memo. This change would put the memo in the body and then it would be available in the block stream and applicable translates converting BlockItem's to a TransactionRecord would have the memo available.
Fixes #14871 
**Checklist**

chore: Update SystemSetup to set memo in TransactionBody

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/impl/internal/AbstractMerkleNode.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/State.java

The failed check in `AbstractMerkleNode.setRoute()` and the exception were bogus due to incorrect route of the Merkle tree root migrated from 0.52.
Fixes #14851
Cherry-picked from release/0.53 (#14858, #14880)
**Checklist**

fix: node exits after repeating unsuccessful reconnects

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomContractCreationProcessor.java
hedera-node/test-clients/SpecCookbook.md
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/SpecEntity.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java

Cherry pick of #14863 - SELFDESTRUCT now deletes contracts properly - in case it is needed in some 0.53 point release.
Fixes #14835
**Checklist**

fix(0.53): cherrypick selfdestruct fix

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAirdropHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/AirdropSigReqsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java

Changing the status of the error from INVALID_TRANSACTION_BODY to NOT_SUPPORTED

fix: When airdrop to contract return NOT_SUPPORTED

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java

Airdrop multiple times to 1 receiver, and claim with one transaction the aggregated amount.
CLAIM-19
https://github.com/hashgraph/hedera-services/issues/14918
Fixes #
**Checklist**

test: claim multiple tokens send to 1 receiver

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/ConsensusSubmitMessageTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/UtilPrngTranslator.java

For tests resulting in `HandleException` we'll end up rolling back the save point stack and which invokes `BlockStreamBuilder.nullOutSideEffectFields()`.
Removed the reset for `status` and `parentConsensusTimestamp` from there in order to have the similar behavior as in `RecordStreamBuilder.nullOutSideEffectFields()`.
Fixes https://github.com/hashgraph/hedera-services/issues/14852
**Checklist**

fix: ConsensusSubmitMessage StreamValidation diffs from SubmitMessageSuite

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BlockStreamTransactionTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/ConsensusTopicCreateTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/CryptoCreateTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/FileCreateTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/ScheduleCreateTranslator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/TokenCreateTranslator.java

`NodeCreate` isn't included since it doesn't have a state changes protobuf method yet. 
Closes #14926

feat: Add transaction-specific translators for create transactions

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java

Fix summary: changed `VirtualPipeline.applyFamilySizeBackpressure()` to be a set of small sleeps rather a single long sleep. After each small sleep, it checks the current backpressure (which may have changed, if a virtual map copy is flushed in a parallel thread) and compares it with total time slept so far.
Fixes: https://github.com/hashgraph/hedera-services/issues/13901

fix: 13901: VirtualPipeline back-pressure is too harsh

---

docs/gradle-quickstart.md

These – `:test-clients:eet` – no longer exist.
#11564 / #15009 (this will cleanup related Gradle configuration)
**Checklist**

chore: remove outdated docs about End-to-End Tests

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/V0540RosterSchema.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java

RosterSchema only provides default for Genesis state. That's a bug, as it must also provide default for existing state created in previous versions. This PR fixes that bug.

fix: RosterSchema should provide default roster for existing states from previous versions AND genesis.

---

.github/CODEOWNERS

So that all `@hashgraph/devops-ci-committers` can:
- Approve Dependabot PRs
- Can approve changes from each other on Gradle and GH action workflow files
**Checklist**

chore: grant code ownership for Gradle and GH workflow files to @hashgraph/devops-ci-committers

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java

Fixes https://github.com/hashgraph/hedera-services/issues/15118
When hollow payer pays for CryptoTransfer that does an autoAssociation to itself with unlimitedAssociationsEnabled = true the changes to state are not committed correctly. This PR fixes that case that was causing a FAIL_INVALID record.
Added a HapiTest validating the behavior

fix: fix hollow payer paying for transaction with unlimitedAssociationsEnabled

---

platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/State.java

This PR officially adds `copy` method to State API. The implementation is already there, so only the interface update was required. 
Fixes #14828 
**Checklist**

feat: 14828 Added `copy` method to the State API

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/MerkleStateLifecyclesImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/MerkleStateLifecyclesImplTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/DefaultTransactionHandler.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateLifecycles.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SwirldState.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/DefaultTransactionHandlerTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/TransactionHandlerTester.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SwirldStateManagerTests.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/state/FakeMerkleStateLifecycles.java

- Closes #15139 
- Fixes a flake in `TokenAirdropTest`.

feat: add `SwirldState#sealConsensusRound()` lifecycle

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml

- Removes several CI workflow steps which are no longer needed and preventing the docker images from being published
- Closes #15156 
- `release/0.52`
- `release/0.53`

ci: resolves release issue preventing the publication of the docker images

---

.github/workflows/node-flow-build-application.yaml

- Fixes the `Node: Build Application` workflow definition by removing the `enable-integration-tests` and `enabled-e2e-tests` which no longer exist in the reusable workflow being called.
- Closes #15168 
- https://github.com/hashgraph/hedera-services/actions/runs/10587478941

ci: fix build application workflow

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/record/DeleteCapableTransactionStreamBuilder.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameUtils.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/records/ContractDeleteStreamBuilder.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/records/ContractOperationStreamBuilder.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/records/ContractUpdateStreamBuilder.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaNativeOperationsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameUtilsTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsDistributor.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHandlerImplTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/CryptoDeleteStreamBuilder.java

Part of the ongoing effort to merge `stream-manager-spike` into develop. This PR does a single rename of `DeleteCapableTransactionRecordBuilder` to `DeleteCapableTransactionStreamBuilder`

refactor: Rename DeleteCapableTransactionRecordBuilder

---

hapi/hedera-protobufs/block/stream/output/state_changes.proto

* Same changes made in the hedera-protobufs repo to add roster and roster_state to the block stream state_changes proto.
This replaces PR #15177, which unintentionally included an "undo" of other recent changes.

chore: Mirroring state changes update to block stream for roster values

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java

This PR fixes migration code for the `PlatformState` in `MerkleStateRoot`. Previously, there was an assumption that there is a guarantee for the `PlatformState` to be a zeroth child. It turned out to be not true. This PR addresses that. 
Fixes #15221 
**Checklist**

fix: 15221 Fixed migration code for the PlatformState

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/BlockStreamServiceTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/schemas/V0540BlockStreamSchemaTest.java

The `BlockStreamInfo` definition, generated from `block_stream_info.proto`, has changed. This PR removes the extra param from any test instantiations of `BlockStreamInfo`

chore: Update tests to use latest valid block stream info protobuf

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/record/DeleteCapableTransactionStreamBuilder.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordInfoUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterServiceImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/V0540RosterSchema.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaRecordCache.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/NodeStakeUpdates.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockImplUtilsTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/schemas/V0540BlockStreamSchemaTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/RosterServiceImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/NodeStakeUpdatesTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemSetupTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java

More preparation to merge `stream-manager-spike` into `develop`. The following changes are contained:
* Add overload of hash by block number
* Add exchange rate and memo to staking period updater
* Minor update to roster service name
* System setup to use exchange rate; initialize treasury clones earlier
* Roster state key update
* Incorporate exchange rate into node stake updates
* Use exchange rate and user txn commit only in handle workflow
* Minor docs, test default

feat: Various block stream modifications

---

settings.gradle.kts

This was accidentally remove in #14245
#14245
**Checklist**

build: add back 'platform-sdk/swirlds' as Gradle project

---

hedera-node/hedera-config/build.gradle.kts
hedera-node/hedera-config/src/testFixtures/java/module-info.java

Removed `tasks.withType<>...` line from `build.gradle.kts` files in `hedera-config` which disables warnings for those packages.
- Inside test `module-info.java` file `com.hedera.node.config` is changed to `transitive` because of `ConfigProvider`
Fixes #15239 
**Checklist**

chore: Fix compiler warnings in `hedera-config`

---

hedera-node/hedera-app-spi/build.gradle.kts
hedera-node/hedera-app-spi/src/testFixtures/java/module-info.java

Removed `tasks.withType<>...` line from `build.gradle.kts` files in `hedera-app-spi` which disables warnings for those packages.
- Inside test `module-info.java` file `com.hedera.node.app.service.token` is changed to `transitive` because of `FakePreHandleContext`
Fixes #15241 
**Checklist**

chore: Fix compiler warnings in `hedera-app-spi`

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/InvalidAddressBookException.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterRetrieverTests.java

* Extending the `RosterRetriever` to be able to retrieve a Roster instance for a specific round number.
* Minor refactoring of the supporting unit test to help test the new utility.
* Addressing a minor typo identified at https://github.com/hashgraph/hedera-services/pull/15096#discussion_r1735343278
Fixes #14969
Unit tests.
**Checklist**

feat: utility to retrieve a Roster for a round

---

settings.gradle.kts

Required proto version update in order to issue 0.54 tags

chore: Use protos v0.54.0 for release 0.54

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NetworkAdminConfig.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/ReadableFreezeUpgradeActionsTest.java

Add networkAdmin.keysPath property. The default value is data/upgrade/current/data/keys. Write s-public-alias.pem file for each node during freeze prepare upgrade to this directory, networkAdmin.keysPath.
Fixes #15255 
**Checklist**

fix: write s-public-alias.pem file for each node to a configurable location

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/PbjConverterTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/WritablePlatformStateStoreTest.java

This PR adds more unit tests for `WritablePlatformStateStore`. 
Relates to #11771

chore: 11771 Added more unit tests for `WritablePlatformStateStore`

---

hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakePlatform.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/FakePlatformContext.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/DefaultPlatformContext.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/context/internal/DefaultPlatformContextTest.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/platform/TestPlatformContextBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateRoot.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MerkleStateRootTest.java
platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/State.java

This PR adds hash-related methods to `State` interface and provides an implementation of these methods in `MerkleStateRoot`. In fact, only `calculateHash` implementation is required, as the other methods are already implemented  by a parent class (`AbstractMerkleNode`). 
Fixes #15146 
**Checklist**

feat: 15146 Added `calculateHash`, `setHash` and `getHash` methods to `State` interface

---

hapi/build.gradle.kts

Setting the release branch to use the specific protobufs 0.54 tag, so as not to depend on the head of main.

chore: Use 0.54 protobufs on 0.54 release branch

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/cache/CacheWarmer.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/cache/CacheWarmerTest.java

- Restored CacheWarmer() constructor with provided Executor erroneously removed in https://github.com/hashgraph/hedera-services/pull/12753.
- Added a unit test to keep it used.
Fixes #12815

chore: Allow injection of CacheWarmer's Executor

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.feature.test-time-consuming.gradle.kts
platform-sdk/swirlds-logging/build.gradle.kts

Adds the `timeConsuming` test set as something projects may use if necessary.
- Will run regularly once #15363 is in
- Can then be filled by moving long running tests from `test` to `timeConsuming` where
For reference, here is a recent scan, that show which tests are above the `100ms` threshold and should be moved once the setup is complete: https://scans.gradle.com/s/fasvtpqbn54tq/tests/slowest-tests
#14407
**Checklist**

build: add 'timeConsuming' test set

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUtils.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakePeriodManagerTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/StakingRewardsApi.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/RepeatableStakingTests.java

- Add assertion that exactly `staking.rewardHistory.numStoredPeriods=365` periods of rewards are collected by a staker who did not collect rewards for over a year.
- Replace e.g. `List.get(0)` with `List.getFirst()`.

chore: improve `noStakingInteractionsForExtendedPeriodIsFine()` spec

---

hedera-node/hedera-app/build.gradle.kts
hedera-node/hedera-network-admin-service-impl/build.gradle.kts
settings.gradle.kts

Remove 'hapiProtoVersion' as this is now the same as the version of hedera services itself.
Related to #15324
**Checklist**

chore: remove hapiProtoVersion

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Utilities.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/PeerInfo.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/NetworkPeerIdentifierTest.java

As a part of replacing usages of AddressBook with Roster, I'm removing a usage of the Address.selfName which is not present in Roster.
Fixes #15440
`test` and `timingSensitive` pass.
**Checklist**

chore: Remove PeerInfo.nodeName

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIterator.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/LearnerPullVirtualTreeView.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/LearnerPushVirtualTreeView.java
platform-sdk/swirlds-virtualmap/src/timingSensitive/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIteratorTest.java

Fix summary:
* All timeouts are removed from `ConcurrentBlockingIterator`
* Rationale: when an iterator is used during reconnects, if elements (dirty leaves from the teacher) aren't provided for too long, the whole reconnect process is terminated. There is no need to have timeouts at the iterator level
Testing:
* All existing unit tests pass
* A couple new tests are provided, in particular to make sure `hasNext()` results in a runtime exception, if the thread is interrupted
Fixes: https://github.com/hashgraph/hedera-services/issues/15167

fix: 15167: Remove timeout from reconnect/rehash Iterators

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java

- Updates `StateChangesValidator` to follow the new order of service schema initializations in https://github.com/hashgraph/hedera-services/pull/15442

fix: match genesis schema changes in `StateChangesValidator`

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesDecoder.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesDecoderTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesTranslatorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/UpdateTokenFeeScheduleTest.java

This PR addresses a fail-fast way of handling invalid amount of fees provided in contract call.
Fixes [#945](https://github.com/hashgraph/hedera-smart-contracts/issues/945)
**Checklist**

fix: Validate `CustomFees` input arrays in `UpdateTokenCustomFeesDecoder`

---

platform-sdk/swirlds-common/src/timingSensitive/java/com/swirlds/common/crypto/CryptographyTests.java

In negative unit tests, truncate Java byte arrays from the beginning rather than from the end to avoid possible padding with 0 when converted to native arrays in JNI code (or native library itself).
Fixes #15533
Related to #15529
**Checklist**

test: unit test verifySyncInvalidEd25519() is not stable

---

hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/CertificatePemTest.java
hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java
hedera-node/hedera-addressbook-service/src/main/java/module-info.java

We only have 'org.testcontainers' in our dependency catalog for testing. It should never be used in production, as it pulls in the complete test containers library, with a bunch of transitive dependencies, into the Hedera Services release.
Here it was mistakenly introduced instead of using the original 'org.bouncycastle' dependencies.
@iwsimon *I recommend picking this also to the `0.54` branch.*
Follow up to #14568
**Checklist**

fix: remove dependencies to 'org.testcontainers' in production code

---

hapi/hedera-protobufs/services/consensus_update_topic.proto

Update the protobuf docs for consensus_update_topic.proto to clarify the following:
-Only the admin key has to sign if the custom fee key is updated.
Fixes #15566

docs: hip-991 protobuf documentation fix

---

.github/workflows/node-flow-pull-request-checks.yaml

Use upgrade test that uses DAB transactions for deleting and updating node instead of the old way for upgrade

test: Use DAB upgrade test in CI runs 

---

.github/workflows/node-flow-deploy-release-artifact.yaml

*Description*:
Removes the `checkout code` and `verify HAPI version` steps from the Prepare Release [Tag] job
*Related Issue(s)*:
Fixes: #15767

ci: Remove unnecessary check in node-flow-deploy-release-artifact

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/ExchangeRateSystemContract.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/PrngSystemContract.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/ExchangeRateSystemContractTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/PrngSystemContractTest.java

There are checks in some of the system contracts which ensure that value is not passed to the contract.  These checks have been made superfluous by this pr #14843 and thus need to be removed.
Fixes #13286

chore: remove unnecessary checks for value xfer to system contracts

---

hedera-node/configuration/dev/application.properties
hedera-node/configuration/previewnet/application.properties
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java

This PR adds the needed configurations to enable the functionalities for the HIP-904 System Contract calls.
Design doc for the feature: https://github.com/hashgraph/hedera-services/pull/15435
Fixes #
As the feature is still in development, the feature flags are disabled by default and enabled only for dev and previewnet envs.
**Checklist**

chore: Add configuration properties for HIP-904 System Contracts

---

hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
hedera-node/infrastructure/docker/containers/production-next/consensus-node/entrypoint.sh

- Updates the `entrypoint.sh` script for the `production-next` deterministic image
- Adds retry logic to properly handle DNS being unavailable during the first few seconds of the container startup sequence
- Adds waitFor logic to properly handle persistent/projected volumes not being immediately available during the container startup sequence
- Adds a configurable `sleep infinity` to keep the container running after the Java process has died
- Closes #15913

fix(container): adds resiliency to the deterministic image entrypoint script

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/singleton/BlockInfoDumpUtils.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/HashTests.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/lifecycle/SaveExpectedMapHandler.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/DefaultIssDetector.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/PbjConverter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/ReadablePlatformStateStore.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/EventDescriptorWrapper.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/DefaultSignedStateValidatorTests.java

Fix [#15542](https://github.com/hashgraph/hedera-services/issues/15542)

chore: Add constructor for `Bytes` in `Hash` to avoid copying

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/OpWorkflowMetrics.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/metrics/OpWorkflowMetricsTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/throttle/DispatchUsageManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java

This PR extends the implementation of `HandleWorkflowMetrics` to encompass both transactions _and_ queries. I considered making a separate `QueryWorkflowMetrics`, which may have had a smaller surface area, but saw no other real advantage. 
Closes #15896

fix: Add query handling metrics upload

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java

Replaces the current transfer list size validation with one that complies with the CryptoTransfer behaviour.
Fixes #15906
PR, that replaces the current transfer list size validation with one that complies with the CryptoTransfer behavior :
1. Allowing no more than 10 fungible token **balance adjustments**.
- In case of one fungible token airdrop, it is possible up to 9 receivers (1 adjustment for the sender and 9 for receivers)
- In case of multiple fungible tokens, it is possible to make up to 5 token transfers (5 x 2 adjustments of the sender and the receiver balances)
2. Allowing no more than 10 NFT transfers
**Checklist**

fix: Airdrop transfer list size validation

---

.github/workflows/zxf-prepare-extended-test-suite.yaml

The status of the triggering job is set to `skipped` need to include that status as a valid conclusion to trigger the XTS job.
Relates to: #15955

ci: Add skipped status as possible triggering conclusion

---

.github/workflows/zxf-prepare-extended-test-suite.yaml

**Details**:
Add checks at the job level to prove we are on the develop branch of the hashgraph/hedera-services repository and not on a fork
Fixes: #15973
**Note(s)**:
- Only testable on merge

ci: Fix issue with zxf prepare extended test suite

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/FullLeafRehashHashListener.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListener.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java

Fix summary:
* Two log statements are added to `AbstractHashListener`: to log flush time and to log leaves/hashes counters
* Flush duration is also reported as a virtual map metric
Fixes: https://github.com/hashgraph/hedera-services/issues/15994

fix: 15994: Need more logging in AbstractHashListener

---

.github/workflows/node-zxc-compile-application-code.yaml
gradle/aggregation/build.gradle.kts
gradle/modules.properties
gradle/plugins/build.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.jpms-modules.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.reports.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.settings.settings.gradle.kts
gradle/reports/build.gradle.kts
hedera-dependency-versions/build.gradle.kts
hedera-node/test-clients/src/main/java/module-info.java

- Update extra-java-module-info to 1.9
- Configure a consistent classpath (new feature in 1.9) to no longer do multiple transformations of the same Jar
- For the consistent/global classpath, use the 'gradle/aggregation' project to configure it (renamed from 'gradle/reports')
- Update Guava and related libraries and remove no longer needed patch rules
This fixes the problem that many Jars are transformed several times, which leads to long IntelliJ import times and the Jars showing up many times in IntelliJ (which looks like this BEFORE this change):
#14255
**Checklist**

build: update Java Module patching

---

.github/CODEOWNERS

Fix the ownership of services protobufs because we modify them in the `hedera-services` repository.
Fixes #16014

chore: Fix ownership of services protobufs

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/defaultkycstatus/DefaultKycStatusCall.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/defaultkycstatus/DefaultKycStatusCallTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DefaultTokenStatusSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java

This PR aims to fix the way we return the value for DefaultKycStatusCall system contract..
Now returning the value based on kycKey present. If the related token is missing the kycKey the status is `KycNotApplicable` which is represented as a boolean true. We return false when the token has kycKey where the status is `Revoked`.
Adjusted existing tests and added a new one.
Fixes #5775 
**Checklist**

fix: DefaultKycStatusCall correct returned values from System Contract

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemSetupTest.java

This fix was in release/0.54 and not cherry-picked into develop branch because the DAB was going to be enabled in releases after 0.54. DAB is disabled again in release/0.55, this needs to be cherry-picked in.
Fixes #15466
**Checklist**

chore: cherry-pick, do not update file 102 during the first transaction after a freeze upgrade when DAB is disabled 

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemSetupTest.java

This fix was in release/0.54 and not cherry-picked into develop branch because the DAB was going to be enabled in releases after 0.54. DAB might be disable after 0.55, this needs to be cherry-picked in deveop.
Fixes #15466 
**Checklist**

chore: cherry-pick, Do not update file 102 during the first transaction after a freeze upgrade when DAB is disabled

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/legacy/LegacyConfigPropertiesLoader.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java

In PR https://github.com/hashgraph/hedera-services/pull/15791, `nextNodeId` was completely removed from config.txt.  DevOps indicated that a hard removal of the field would make things more complicated as they switch back and forth between software version in test environments.  The decision was made to allow the field to be present until all test environments and CI/CD pipelines were on a version of the software that did not require the field to be present, then it could be removed from the format. 
Fixes #15934 
A new issue was created to undo the effects of this PR when we can completely remove the field.  https://github.com/hashgraph/hedera-services/issues/16049

chore: tolerate nextNodeId field in config.txt

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterService.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/WritableStoreFactory.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/RosterServiceTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/ReadableRosterStore.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/ReadableRosterStoreImpl.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/WritableRosterStore.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/schemas/V0540RosterSchema.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/WritableRosterStoreTest.java

`ReadableRosterStore` and `WritableRosterStore` have been introduced as Roster stores and this PR includes changes to register Services/Schema/State/Migration registrations.
* [`hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/RosterService.java`](diffhunk://#diff-b57d421270a96d2d6595715a37c98dbb725e503c6947dca9209c9f2adb16b81fL21-R22): Renamed from `RosterServiceImpl.java` and updated to use `RosterStateId`. [[1]](diffhunk://#diff-b57d421270a96d2d6595715a37c98dbb725e503c6947dca9209c9f2adb16b81fL21-R22) [[2]](diffhunk://#diff-b57d421270a96d2d6595715a37c98dbb725e503c6947dca9209c9f2adb16b81fL31-R37)
* [`hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/RosterServiceTest.java`](diffhunk://#diff-9e740aed933ba8752261fee71c5ee11303c92520b4ab41192e16e …

feat: Readable and Writable Roster state stores

---

.github/workflows/zxcron-promote-build-candidate.yaml

Use the proper reference to the previous jobs `outputs` variable
Fixes: #16153

ci: Fix ZXCron Promote Build Candidate Checkout Tagged Code step

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

xts-candidate tag was failing to be deleted if it did not exist
Fixes: #16156
**Checklist**
- Prepare XTS: https://github.com/hashgraph/hedera-services/actions/runs/11506585644
- Execute XTS: https://github.com/hashgraph/hedera-services/actions/runs/11506615363

ci: Fix bug with deleting xts-candidate tag prior to creation or use 

---

.github/workflows/node-flow-pull-request-checks.yaml

This PR fixes the Gradle Determinism / Verify Artifacts (windows-2019) check. It seems that when specifying only "21" as a java version, at some point the action automatically switched to java 21.0.5, which seems to be the problem.
Example with only "java-version: 21" specified - https://github.com/hashgraph/hedera-services/actions/runs/11507482709/job/32043010427?pr=16095#step:7:26
N/A
**Checklist**

ci: Specify java major minor and patch versions

---

.github/workflows/config/node-release.yaml

Schedule 0.56 release branch creation for 2:00pm Pacific / 4:00pm Central / 21:00 GMT
Fixes #16183

chore: schedule 0.56 release branch creation

---

.github/workflows/node-zxcron-release-fsts-regression.yaml
.github/workflows/platform-zxcron-release-jrs-regression.yaml

0.54 is on mainnet , no longer need to run regression for release 0.54

ci: disable release 0.53 regression

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/legacy/LegacyConfigPropertiesLoader.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java

Fixes #16132 
Fixes https://github.com/hashgraph/solo-operator/issues/233
During boot time, platform shouldn't try to resolve the FQDN addresses (internal or external) in the config.txt as other nodes may not be up by the time a node starts parsing config.txt. So this PR removes FQDN resolution at config parsing time.
Also it throws exception if `config.txt` parsing fails for other reasons at the boot time.
**Checklist**

fix: LegacyConfigPropertiesLoader should not suppress ParseException

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

Need `actions:write` in order to enable the cancel action by the GH token
Fixes #16212

ci: Update github token permissions

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ReconnectStateLoader.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/DefaultEventSignatureValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/EventSignatureValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/RosterUpdate.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/EventSignatureValidatorTests.java

As a part of the TSS initiative, and specifically the TSS-Roster project, we're refactoring the Platform code to replace usages of `AddressBook` with `Roster`.
This fix refactors the `event.validation`-related classes.
Fixes #16201
Tests should pass.
**Checklist**

chore: replace usages of AddressBook with Roster in event.validation

---

hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
hedera-node/infrastructure/docker/containers/production-next/consensus-node/entrypoint.sh
platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/NetworkUtils.java
platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Retry.java
platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/ThrowableFunction.java
platform-sdk/swirlds-base/src/test/java/com/swirlds/base/utility/NetworkUtilsTest.java
platform-sdk/swirlds-base/src/test/java/com/swirlds/base/utility/RetryTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookNetworkUtils.java

- Improves the `AddressBookNetworkUtils.isLocal()` method to reduce brittleness when DNS resolution is slow or fails on the first attempt. 
- Updates the `production-next` container image to resolve a bug in the `entrypoint.sh` script when retrying for address book loading issues.
- Updates the `production-next` container image to adjust the Java JVM DNS caching timeouts to behave within reasonable limits. 
- Closes #16210
- Related to #16133

fix: resolve issues with isLocal flakiness due to DNS resolution

---

hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
hedera-node/infrastructure/docker/containers/production-next/consensus-node/etc/s6-overlay/s6-rc.d/hedera/finish
hedera-node/infrastructure/docker/containers/production-next/consensus-node/etc/s6-overlay/s6-rc.d/hedera/run
hedera-node/infrastructure/docker/containers/production-next/consensus-node/etc/s6-overlay/s6-rc.d/hedera/type

Run entrypoint.sh as s6 supervised service to provide a structured path to perform setup/teardown through s6 supervision.
Fixes #15942 
**Checklist**

feat: run entrypoint as s6 supervised service

---

.github/workflows/node-zxc-compile-application-code.yaml

This a recreation of PR #16078
Codecy reporter needs additional parameters to be skipped on forked PRs so that steps/actions which require the use of secrets are only ran on PRs from the original repo.
Fixes #14293
**Checklist**

ci: Updating workflow to skip codacy checks on forked PRs.

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/branching/DefaultBranchDetector.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/branching/DefaultBranchReporter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/branching/BranchDetectorTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/branching/BranchReporterTests.java

As a part of the TSS initiative, and specifically the TSS-Roster project, we're refactoring the Platform code to replace usages of `AddressBook` with `Roster`.
This fix refactors the `event.branching`-related classes.
Fixes #16235
Tests should pass.
**Checklist**

chore: replace usages of AddressBook with Roster in event.branching

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/CommonPcesWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/DefaultInlinePcesWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/DefaultPcesWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/InlinePcesWriter.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/preconsensus/CommonPcesWriterTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/preconsensus/DefaultInlinePcesWriterTest.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/PcesWriterTestUtils.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java

feat: Add InlinePcesWriter

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/EmbeddedVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/embedded/MutateScheduleExpiries.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java

- Updates the state "corruption" used in [this embedded test](https://github.com/hashgraph/hedera-services/blob/2c30a3ac0ddb31a4f2289b33ddc8ac0c20f5bb70/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java#L169) to target the updated `ScheduleService` schemas.

fix: change `failInvalidOutsideDispatchDoesNotAttemptToChargeFees()` for refactored ScheduleService schema

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

Updates the following workflows to prevent duplicate tagging on a given commit:
- `zxcron-extended-test-suite.yaml`
- `zxcron-promote-build-candidate.yaml`
- `zxf-prepare-extended-test-suite.yaml`
Fixes #16329
**Testing**:
Manual Triggers: 
- [Skipped xts-candidate tag](https://github.com/hashgraph/hedera-services/actions/runs/11607212373)
- [Passed xts-candidate tag](https://github.com/hashgraph/hedera-services/actions/runs/11607189764)
- [Skipped xts-pass tag](https://github.com/hashgraph/hedera-services/actions/runs/11607302685)
- [Passed xts-pass tag](https://github.com/hashgraph/hedera-services/actions/runs/11607302685/attempts/1)
- [Skipped build promotion tag](https://github.com/hashgraph/hedera-services/actions/runs/11607252702/job/32320514864 …

ci: Update the XTS workflows to prevent double tagging on commits

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoader.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/CryptoArgsProvider.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoaderTest.java

This PR stops reading the agreement key from disk and always generates it on startup.  The migration code will delete the agreement key if found and force generation anyway.   This is a code cleanup operation so that when the migration code is removed, there are no potential bugs.  
Potential Bug This Avoids:  
* PFX file contains an agreement key
* Migration code is deleted and PFX files remain on disk because someone put them there again. 
* DAB has rotated the signing key and is using a new signing key in a PEM file. 
* Agreement key for old signing key is loaded from PFX file. 
* The mismatch between the old agreement key and new signing key will cause the node to fail to create mTLS connections with peers. 
Fixes #16161 
The only testing …

feat: always generate agreement key on startup

---

.github/CODEOWNERS
.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxf-deploy-integration.yaml

We need to re-enable the jenkins integration flow. To do this, we will pass a limited set of JSON fields from the github event through to the Jenkinsfile.
Fixes #16319

ci: Re-enable jenkins integration flow

---

.github/workflows/node-flow-build-application.yaml

In the previous effort of escaping and cleaning the commit message, we removed all tabs, returns, newlines, and spaces to squash all the text together. To make the output more readable, we'd like to replace all tabs, returns, and newlines with spaces.
Fixes #16387

ci: add spaces to JSON message cleanup

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java
hedera-node/test-clients/src/main/resources/testSystemFiles/artificial-limits.json

Based on this comment: https://github.com/hashgraph/hedera-services/pull/15930#pullrequestreview-2407720434
Adding `artificial-limits.json` for GetBalance queries in order to test it in `SteadyStateThrottlingTest`
Fixes #16374

test: GetBalance queries

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/NodeMetadata.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/AddressBookUtils.java

Description:
The gRPC node operator port for node0 in a SubProcessNetwork was conflicting with the external gossip port assigned to node1.

fix: Eliminate node operator port conflict 

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isvalidalias/IsValidAliasCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCallTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip632/IsAuthorizedTest.java

Fixes `isAuthorizedRaw`:
> Fix bug where isAuthorizedRaw fails when given an auto-created account with EC… key
Fixes #16404 
Cherry picked from commits at PR #16218 (not yet merged to develop at this time)
**Checklist**

fix: Cherry pick (0.56): `isAuthorizedRaw` bug fix

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterHistory.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterHistoryTest.java

Introducing a `RosterHistory` class to encapsulate the information about active/previous (and in the future, any historical) rosters necessary for the consensus node to function. Specifically, this object is going to be a `PlatformBuilder` input instead of the currently used `withAddressBook`/`withRoster` and friends. The refactoring of the PlatformBuilder, as well as the code in ServicesMain that instantiates it, will be performed in a separate PR in the future.
Fixes #16353
Unit tests.
**Checklist**

feat: introduce RosterHistory

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java

This PR loads the cryptography in the address book given the to the `GuiEventStorage` constructor.   Without the crypto, the translate of the address book to a Roster throws an exception. 
This problem was missed because the Browser is not production code and not tested in the CI/CD pipeline.  It can only be used by starting platform applications locally and in nightly platform JRS tests. 
Fixes #16452 
Verified local startup of Browser.

fix: load crypto into address book in `Browser` call to `GuiEventStorage`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/pairings/FakeFieldElement.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/tss/pairings/FakeGroupElement.java
hedera-node/hedera-app/src/main/java/module-info.java

Do not use 'org.jetbrains.annotations'.
See this for getting IntelliJ to be more helpful there:
https://github.com/hashgraph/hedera-services/blob/1fe6a2de8b797eec943a45420c48a0d59f9f3271/docs/intellij-quickstart.md#spotbugs-annotations 
This should not have been added: https://github.com/hashgraph/hedera-services/pull/15908/files#diff-b387a7cf1f02bb7e5aeb741f42e0f851f454dd6f5f48beab877b433b3cb46e6cR55
Please give some thought to `module-info` additions. In particular when it is about 3d party modules that have not been used before.
Follow up to #15908
**Checklist**

chore: consistently use findbugs annotation

---

hedera-node/docs/design/services/service-configuration.md

Adds a markdown file explaining the purpose of the various *Config classes.
Fixes #16020 
**Checklist**

docs: Add services configuration design doc

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoader.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/CryptoArgsProvider.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoaderTest.java

There is an edge case if the migration of the cryptography is removed and a PFX file is placed in the cryptography directory that contains an old agreement key, the old agreement key will be loaded and prevent mTLS gossip connections from being formed with peers.  
This contains two cherry picked commits.  
1. Always generating agreement keys and not loading them
2. A fix for migrating the public.pfx file to the wrong sub-directory.  
Fixes #16453
Fixes #16451 
The PRs for develop: 
1. https://github.com/hashgraph/hedera-services/pull/16315
1. https://github.com/hashgraph/hedera-services/pull/16444

fix: cryptography always generates agreement keys on startup

---

hapi/hedera-protobufs/services/address_book_service.proto
hapi/hedera-protobufs/services/node_update.proto
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/UpdateAccountEnabledTest.java

feat: NodeUpdate needs only admin key to sign

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuildingBlocks.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterHistory.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterRetriever.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterHistoryTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java

Refactor `PlatformBuilder` to accept a RosterHistory object as the medium of receiving rosters.
With this change, the PlatformBuilder `.withAddressBook()` and `.withRoster()` are gone and replaced with a `RosterHistory` argument to the PlatformBuilder constructor. Further, the RosterHistory is propagated to the `PlatformBuildingBlocks` and then used in the `PlatformComponentBuilder` to access the current and "previous" rosters.
This is a step towards removing the AddressBook object from the PlatformState.
Please note that the `SignedState.getAddressBook()` still exists and is used in a few places, notably in reconnect and recovery-related code, as well as some state-signing-related code. We'll be looking into these other usages separately in the future.
**One extra …

feat: use RosterHistory in PlatformBuilder

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/NodeInfoImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/StateNetworkInfo.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/StateNetworkInfoTest.java

Fixes https://github.com/hashgraph/hedera-services/issues/16499
Use disk address book to construct StateNetworkInfo instead of using roster entries until Roster proposal and DAB are enabled

fix: Use disk address book to construct network Info

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java

Contracts deployed via `EthereumTransaction` are setting the externalized record to the mirror node as null.  Update to externalize a self managing contract key
Fixes #16508

fix: set admin key to self managed key for EthereumTransaction contract deployments

---

hapi/hedera-protobufs/services/node_create.proto
hapi/hedera-protobufs/services/node_update.proto
hapi/hedera-protobufs/services/state/addressbook/node.proto
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/ReadableNodeStoreImpl.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/AddressBookTestBase.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/ReadableFreezeUpgradeActionsTest.java

We're not ready to specify requirements for a node's TSS key yet. We'll remove it for now to make syncing with the protobufs repo easier, and re-enable when we actually need it.

fix: Remove tss encryption key from node-related protos

---

.github/workflows/node-flow-deploy-preview.yaml

Fix dry-run-enabled parameter passing
Fixes #11046 
Test workflow run: https://github.com/hashgraph/hedera-services/actions/runs/11739466577/job/32704033446
The error at the end seems to be desired as the pipeline should not be trigger with the `dry-run-enabled` parameter being `true`
**Checklist**

ci: Fix dry-run-enabled parameter passing

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/config/AddressBookConfigTest.java

This pull request introduces a new configuration option to the `AddressBookConfig` class and adds corresponding unit tests to ensure its default value is correctly set. The key changes include:
* Added a new configuration parameter `useRosterLifecycle` to the `AddressBookConfig` class, which determines whether the platform will use the roster lifecycle.
* Added a new test `testUseRosterLifecycleDefaultValue` in `AddressBookConfigTest` to verify that the default value of `useRosterLifecycle` is set to `false`.
Fixes #16351 
**Checklist**

chore: Add useRosterLifecycle to platform AddressBookConfig

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AccountsConfig.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java

Increases the account and NFT maximums to 100M each.
Addresses #16516 in release 57
**Checklist**

feat: increase maximums to 100M each by default

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java

feat: increase roundsExpired and maxAggregateRels

---

.github/workflows/zxcron-extended-test-suite.yaml

Add log artifact on XTS failure.
Fixes #16537 
Unfortunately the more intuitive way of gathering job logs (`gh run view --job "$job_id" --log`) returns an error when executed in a running workflow, despite the fact that the job is already finished:
"run 11799265961 is still in progress; logs will be available when it is complete"
That's why the approach with `gh api` is chosen.
Test workflow run: https://github.com/hashgraph/hedera-services/actions/runs/11815991373
**Checklist**

ci: Add log artifact on XTS failure

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java

This PR removes the redundant `createRoster` from `AddressBookUtils` and replaces its usage with `buildRoster` from the `RosterRetriever`. 
Fixes #15573 
The behavior of `buildRoster` is the correct behavior and the unit tests in `AddressBookNetworkUtilsTest` have been updated to reflect this.

chore: remove `AddressBookUtils.createRoster()`

---

hapi/hedera-protobufs/block/stream/output/block_header.proto
hapi/hedera-protobufs/block/stream/output/smart_contract_service.proto
hapi/hedera-protobufs/block/stream/record_file_item.proto

* Adjusted record file item to latest expectation
* Removed address book version from block header
* Added a missing service name in `block/stream/output/smart_contract_service.proto` documentation
During work to migrate record file data into block stream format, Jasper found some issues with the current proto files, and requested some modest changes.
The `address_book_version` field in `BlockHeader` is not needed with TSS.
The `number` and `hash_algorithm` in `RecordFileItem` are duplicative of `BlockHeader`.
A decision was made to add a `BlockHeader` to record file blocks.
A (to be designed) `AddressBookProof` item will also be added to record file blocks in a later PR.
The `address_book_version` field was not used anywhere, so removal does not require code changes.
The `RecordFileItem` …

chore: Modified block stream handling for record file data

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts

The `<description></description>` field was not present in the pom.xml file generated for maven central. Needed to update two parts of the field setter:
- `.orElse(provider { project.description })` became `.orElse(provider(project::getDescription))` to actually populate with the project description
- `.orNull()` becomes `.orElse("")` to prevent a null entry on description if it is not present in the other ways
Fixes #16624
**Checklist**

build(bug): description field in pom.xml was not populated

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/SubmitMessageSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/classiccalls/FailureCharacterizationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallHapiOnlySuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetBytecodeSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractStateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/DelegateCallOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileV2SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSV2SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSV2SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java

This PR does not change any test conditions; instead, it merely wraps each set of spec operations with the new `hapiTest(...)` method wrapper instead of `defaultHapiSpec(...)`. 
Part of #16494

chore: Refactor hapi tests to use `hapiTest(...)` instead of `defaultHapiSpec(...)` (Part 1)

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts

The `<description></description>` field was not present in the pom.xml file generated for maven central. Needed to update two parts of the field setter:
- `.orElse(provider { project.description })` became `.orElse(provider(project::getDescription))` to actually populate with the project description
- `.orNull()` becomes `.orElse("")` to prevent a null entry on description if it is not present in the other ways
Fixes #16624
**Checklist**

build(bug): cherry pick #16626 into release 0.56

---

hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V056AddressBookSchema.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V053AddressBookSchemaTest.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V056AddressBookSchemaTest.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java

* When migrating from an `AddressBook` to the `Node`s, convert from hex string to hash bits
* When generating an `AddressBook` from the `Node`s, convert from hash bits to hex string
* Fix the two unit tests that assumed both were arbitrary bytes.
* Fix the one HAPI test that interacts with the `101`/`102` file generation.

fix: correct a missing conversion between `AddressBook` cert hash hex-string-as-bytes and actual SHA2-384 hash bytes for `Node` entries.

---

hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V053AddressBookSchemaTest.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/NodeMetadataHelper.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java

* When migrating from an `AddressBook` to the `Node`s, convert from hex string to hash bits
* When generating an `AddressBook` from the `Node`s, convert from hash bits to hex string
* Fix the one unit test that assumed both were arbitrary bytes.
* Fix the one HAPI test that interacts with the `101`/`102` file generation.

fix: correct a missing conversion between AddressBook cert hash hex-string-as-bytes and actual SHA2-384 hash bytes for Node entries.

---

hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidator.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/CertificatePemTest.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidatorTest.java
hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java

- Closes #16645 
- Instead of relying on the permissive `CertificateFactory.getInstance("X.509")` accepting the client's gossip X509 cert bytes, change `AddressBookValidator` to serialize the given bytes as a PEM X509 certificate; and validate an X509 cert can be parsed from the resulting PEM.

chore: Do stricter validation of X.509 gossip cert in DAB transactions

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/node-zxf-snyk-monitor.yaml
.github/workflows/zxc-jrs-regression.yaml
.github/workflows/zxc-verify-docker-build-determinism.yaml
.github/workflows/zxc-verify-gradle-build-determinism.yaml

Revert gradle/actions upgrade. This reverts commit 08011d87371c9f9a5d9066dc227b883c715f0b93.
Revert the dependabot upgrade in #16655 
Fixes #16655

build(deps): Revert bump gradle/actions from 3.4.2 to 4.2.1 (#16655)

---

.github/workflows/node-zxc-compile-application-code.yaml
gradle/plugins/build.gradle.kts
gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts
hedera-node/hedera-app-spi/build.gradle.kts

Run `validatePomFiles` as part of qualityGate and PR checks. It is not expensive to run this check and this will hopefully reduce the amount of issues we only find very late in the publishing process right now.
Resolves #16649
Builds on #16651
**Checklist**

build: run validatePomFiles as part of qualityGate and PR checks

---

platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoMain.java
platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoMain.java
platform-sdk/platform-apps/demos/StatsDemo/src/main/java/com/swirlds/demo/stats/StatsDemoMain.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolMain.java
platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
platform-sdk/platform-apps/tests/StressTestingTool/src/main/java/com/swirlds/demo/stress/StressTestingToolMain.java

This is a follow-up for https://github.com/hashgraph/hedera-services/pull/16477. Some nightly tests are failing due to missing initialization blocks that register class IDs of the Merkle state root. This PR fixes the issue.
Relates to #[15638](https://github.com/hashgraph/hedera-services/issues/15638)
**Checklist**

fix: 15638 Added missing contructor registry initialization to test and demo apps

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ReconnectMetrics.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookMetrics.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/RosterMetrics.java

A small PR to replace the use of `AddressBook` with `Roster` in `ReconnectMetrics` and `AddressBookMetrics`. 
Fixes #16718

chore: replace use of `AddressBook` with `Roster` in `ReconnectMetrics and `AddressBookMetrics`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/platform/PlatformModule.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakePlatform.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/AbstractFakePlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/SwirldsGui.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabAddresses.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookNetworkUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/Platform.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SwirldStateManagerTests.java

As part of the platform refactor to replace usage of `AddressBook` with `Roster`, this PR replaces the use of `Platform.getAddressBook()` with `Platform.getRoster()`.   The impacted code is updated with equivalent usage for rosters.
Fixes #16717

chore: replace `Platform.getAddressBook()` with `Platform.getRoster()`

---

gradle/wrapper/gradle-wrapper.properties

This is required by the latest version of the `io.freefair.gradle:maven-plugin` plugin introduced in #16679 to properly report errors.
**Checklist**

build: bump Gradle from 8.10 to 8.11.1

---

hapi/hedera-protobufs/services/node_delete.proto
hapi/hedera-protobufs/services/node_update.proto
hapi/hedera-protobufs/services/transaction_receipt.proto

Very small update to fix some documentation-only errors in the protocol buffer specification for Node update/delete and transaction receipt.
Fixes #16595

docs: Removed incorrect specification for node id in receipt

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/node-zxcron-release-branching.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

Reverts hashgraph/hedera-services#16611
Need a ticket to upgrade to the new major version: https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0

fix: Revert build(deps) bump slackapi/slack-github-action from 1.25.0 to 2.0.0

---

hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/CreateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/UpdateCommand.java
hedera-node/test-clients/yahcli/run/build.sh
hedera-node/test-clients/yahcli/run/publish.sh

chore: (yahcli) Use hash of gRPC cert PEM instead of its X.509 DER encoding

---

hedera-node/configuration/compose/node.properties
hedera-node/configuration/dev/application.properties
hedera-node/configuration/dev/node.properties
hedera-node/data/config/node.properties
hedera-node/docker/.dockerignore
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BlockStreamConfig.java
hedera-node/infrastructure/docker/containers/local-node/network-node-base/Dockerfile
hedera-node/infrastructure/docker/containers/production-next/consensus-node/Dockerfile
hedera-node/infrastructure/docker/containers/production/network-node-base/Dockerfile
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/ProcessUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/TransactionRecordParityValidator.java

This PR modifies the default block streams output directory to `/opt/hgcapp/blockStreams` in order to match the corresponding record streams directory. This directory is also added as a mount in the relevant docker compose files.
Closes #16713

chore: Modify and mount default block streams output directory

---

platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectNodeRemover.java
platform-sdk/swirlds-virtualmap/src/timingSensitive/java/com/swirlds/virtualmap/internal/hash/VirtualHasherTest.java

Fix summary:
1. `ReconnectNodeRemover`: changed `allNodesReceived()` to work correctly, if the new leaf path range from the teacher is empty (-1, -1)
2. `VirtualHasher`: hash listener is now notified about hashing started/finished even if the leaf path range is empty
3. `AbstractHashListener`: changed `onHashingCompleted()` to run the final flush even if the list of collected dirty leaves and the list of dirty hashes are empty. This is needed to delete stale leaves from the data source. This method is now called by `VirtualHasher` even if the virtual map is empty on the teacher
Testing:
1. Manual testing
2. Existing reconnect unit tests are improved to run deeper virtual key checks. It made some existing tests (with empty learner maps) fail without this fix and pass with it, as expected. …

fix: 16657: State validation fails for round 191161423 on LSE

---

hapi/hedera-protobufs/services/response_code.proto
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java

Fixes #16751 
Adds validation that grpcCertificate hash is not empty

fix: Add validation for grpc certificate hash

---

platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileReader.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleTreeSnapshotReader.java

This fix addresses `AddressBook`-related JTR failures. It should fix the following tests:
```
AddressBook-restart-force-use-config-addressbook-1k-4m 
AddressBook-restart-saved-state-same-version-1k-4m 
AddressBook-restart-upgrade-force-use-config-addressbook-1k-4m
AddressBook-restart-upgrade-weight-behavior2-1k-4m
```
Fixes #16748 
**Checklist**
```

fix: 16748 Fixed serialization for AddressBookTestingToolState

---

platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java

This PR fixes the following tests:
```
ISS-catastrophic-1k-5
ISS-recoverable-1k-5m
```
There were two causes of the failure:
1. Absent state serialization 
2. NPE in `ISSTestingToolState#findLargestPartition`. 
Both issues are resolved. 
Fixes #16750 
**Checklist**

fix: 16750 Fixed serialization for `ISSTestingToolState`

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java

Code coverage increased from 71.25 % to 95.00 %
Fixes #16833 
**Checklist**

test: Increase code coverage in `CryptoDeleteAllowanceHandlerTest`

---

platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectNodeRemover.java
platform-sdk/swirlds-virtualmap/src/timingSensitive/java/com/swirlds/virtualmap/internal/hash/VirtualHasherTest.java

chore: Cherry Pick: State validation fails for round 191161423 on LSE

---

hedera-node/configuration/mainnet/upgrade/throttles.json
hedera-node/configuration/previewnet/upgrade/throttles.json
hedera-node/configuration/testnet/upgrade/throttles.json

Increase CryptoGetAccountBalance throttle to the number of nodes times 1,000,000 plus a buffer
Fixes #16850
Related PR in 0.57: PR #16853 
Related PR in develop: PR #16857

chore: Cherry-Pick (0.56): Increase CryptoGetAccountBalance throttle

---

platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/MerkleTestUtils.java
platform-sdk/swirlds-common/src/testFixtures/java/module-info.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java

This PR adds deep VirtualMap key validation for reconnect tests.
Fixes #16754

chore: add deep VirtualMap key validation for reconnect tests

---

hedera-node/configuration/mainnet/upgrade/throttles.json
hedera-node/configuration/previewnet/upgrade/throttles.json
hedera-node/configuration/testnet/upgrade/throttles.json

Description:
Increase CryptoGetAccountBalance throttle to the number of nodes times 1,000,000 plus a buffer
Fixes https://github.com/hashgraph/hedera-services/issues/16850
PR in develop: #16857 
PR in 0.56: #16852

chore: Cherry-Pick (0.57): Increase CryptoGetAccountBalance throttle

---

hedera-node/configuration/mainnet/upgrade/throttles.json
hedera-node/configuration/previewnet/upgrade/throttles.json
hedera-node/configuration/testnet/upgrade/throttles.json

Update CryptoGetAccountBalance throttle in previewnet, testnet, mainnet to the number of network nodes times 1,000,000 plus a buffer
Fixes #16850

chore: Increase CryptoGetAccountBalance throttle

---

hapi/hedera-protobufs/services/response_code.proto
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermSignTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/queries/AsNodeOperatorQueriesTest.java
hedera-node/test-clients/src/main/resources/testSystemFiles/mainnet-throttles-sans-reservations.json

chore: Cover changing throttle definitions

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformMerkleStateRoot.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java

This PR swaps `classId`-s for `PlatformMerkleStateRoot` and `MerkleStateRoot`. This will resolve an issue with loading of saved state created with `release/0.56`
Fixes #16858 
**Checklist**

fix: 16858 Corrected class ids for PlatformMerkleStateRoot and MerkleStateRoot

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/AppContext.java
hedera-node/hedera-app-spi/src/main/java/module-info.java
hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/blocks/BlockStreamManagerBenchmark.java
hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/blocks/StandaloneRoundManagement.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/AppContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceComponent.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/metrics/ContractMetrics.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/AbstractContractTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/metrics/ContractMetricsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java

SCSC metrics for #TXs that fail pureCheck:
- counts for CONTRACT_CREATE / CONTRACT_CALL / ETHEREUM_TRANSACTION that fail pureCheck for any reason
- and for those that fail pureCheck because they don't even have the intrinsic gas amount
- and for Type 3 format (BLOB) Ethereum transactions (that we don't support)
Fixes #16076 
- Key class is `ContractMetrics` to encapsulate all SCSC metrics; and currently it is used in `ContractCreateHandler`, `ContractCallHandler`, and `EthereumTransactionHandler`
- Added a `Supplier<Metrics>` to the `AppContext` so smart contract service (and others) can get the metrics instance from the app.
- There are quite a few unit tests that needed to be modified for this change as they create an …

feat: SCSC metrics for #TXs that fail pureCheck

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/AppContext.java
hedera-node/hedera-app-spi/src/main/java/module-info.java
hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/blocks/BlockStreamManagerBenchmark.java
hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/blocks/StandaloneRoundManagement.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/AppContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceComponent.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/metrics/ContractMetrics.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/AbstractContractTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/metrics/ContractMetricsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java

Cherry pick of #16077 (from the PR, which has not yet merged to develop)
Fixes #16076
**Checklist**

feat: cherry pick smart contract service P1 metrics to release 0.57

---

.github/workflows/node-zxc-compile-application-code.yaml

Snyk has an issue where it has not been successful on the mainline when running actions. It fails with a failure to authenticate. Adding the `--org=hedera-services` should resolve this issue.
Fixes #16878

ci: add org to snyk action

---

.github/workflows/flow-pull-request-formatting.yaml

In commit 778d279 there was a merge for preventing forked repos running on our runners when PRs are created. In this, we removed one env token. This caused an authentication issue in the Check PR Title step. Adding the env token back to the workflow file will resolve the problem.
Fixes #16919

ci: Add env token for Check PR Title step to pull-request-formatting

---

hapi/hedera-protobufs/services/response_code.proto
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java

- Deleting `SCHEDULE_EXPIRY_MUST_BE_FUTURE` and `SCHEDULE_EXPIRY_TOO_LONG` and replacing them with `SCHEDULE_EXPIRATION_TIME_MUST_BE_HIGHER_THAN_CONSENSUS_TIME` and `SCHEDULE_EXPIRATION_TIME_TOO_FAR_IN_FUTURE`

refactor: remove duplicated response codes

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java

This fix removes the last meaningful use of the `PlatformStateAccessor.getPreviousAddressBook()` by making the `RosterUtils.buildRosterHistory` use the RosterRetriever calls instead of fetching the current/previous AddressBooks directly from the PlatformState.
The RosterRetriever would automatically fetch the data from the RosterState/RosterMap once we start populating these states. Until then, the code will automatically fall back to reading the current/previous ABs from the PlatformState and converting them to rosters.
A few remaining usages of the `PlatformStateAccessor.getPreviousAddressBook()` are listed in the #16922 and cannot be removed immediately.
Fixes #16922 
Tests should pass.
**Checklist**

chore: use RosterRetriever in RosterUtils.buildRosterHistory

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AssociateTokenRecipientsStepTest.java

Code coverage increased from 73.97 % to 93.62 %
Fixes #16926 
**Checklist**

test: Increase code coverage in `AssociateTokenRecipientsStep`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/metrics/ContractMetrics.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/metrics/ContractMetricsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteAllowanceSuite.java

Move initialization call of P1 smart contract metrics.
The new place for it has the potential to be called multiple times but metrics must only be created once. So there is a gate too.
Fixes #16902 
**Checklist**
- [x[ Tested (unit, integration, etc.)

fix: move initialization of P1 smart contract metrics

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/metrics/ContractMetrics.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/metrics/ContractMetricsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteAllowanceSuite.java

Cherry pick of #16903
- reliable initialization of smart contract metrics
- correct new metrics names to meet constraints
Fixes #16942 
**Checklist**

fix: cherry pick to 0.57 of #16903 - a fix for smart contracts P1 metrics

---

platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java

This PR fixes `AddressBookTestingToolState`. After introduction of `ROSTERS` and `ROSTER_STATE` in this PR https://github.com/hashgraph/hedera-services/pull/16656, all the other states have to be shifted
Fixes #16954 
**Checklist**

fix: 16954 Shifted child indexes in `AddressBookTestingToolState` by two

---

platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolStateRoot.java

This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/16905 to `release/0.57`
Fixes #16744 
**Checklist**

fix: 16744 Added reincarnation of State (MigrationTestingToolStateRoot) - cherry-pick

---

platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoMain.java
platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoMain.java
platform-sdk/platform-apps/demos/StatsDemo/src/main/java/com/swirlds/demo/stats/StatsDemoMain.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolMain.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
platform-sdk/platform-apps/tests/StressTestingTool/src/main/java/com/swirlds/demo/stress/StressTestingToolMain.java

`ConstructableRegistry` constructors are used for deserialization. When deserializing a state object, the code that loads the state from disk already performs the initialization of service states if/when it's necessary to use the state and call the services. If the service states, such as the ROSTERS map of the RosterService, is also initialized in the `ConstructableRegistry` constructor, then this double initialization may cause problems in the VirtualMap implementation code that leads to thread pools being terminated and VirtualMap-related task runnables being rejected.
We've already fixed this problem for `ConsistencyTestingToolState` previously. This fix replicates the fix to all other demo states implementations.
Fixes #17000
**Notes for …

fix: don't initStates() in ConstructableRegistry

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/DefaultSignedStateValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateValidationData.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateValidator.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/DefaultSignedStateValidatorTests.java

This PR refactors `SignedStateValidator` to use Roster instead of AddressBook. It also adds some duplicate methods in `SignedState` to support rosters; address book usages here will be cleaned up in #16906.
Fixes #16913 
**Checklist**

chore: #16913 - replace AddressBook with Roster in SignedStateValidator

---

hapi/hedera-protobufs/services/token_get_info.proto

Reverts `token_get_info.proto` fields from develop
Fixes #17024 
**Checklist**

fix: Revert HIP-796 Protobuf changes (develop)

---

hapi/hedera-protobufs/services/token_get_info.proto

Cherry picks https://github.com/hashgraph/hedera-services/pull/17026 (revert `token_get_info.proto` fields)
Fixes https://github.com/hashgraph/hedera-services/issues/17024
**Checklist**

fix: Revert HIP-796 Protobuf changes (cherry-pick 0.57)

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StateFileManagerTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java

Fixed know leaking call Files.list()
Fixes #16947
**Checklist**

test: fixed 16947 leaking file descriptors in swirlds-platform-core tests

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java

This fixes a bug where the output in an error message that calculated the weight as a percentage was using integers instead of floating point numbers. This caused the percent to always be 0%.
Fixes #16879 
**Checklist**

fix: use floating point numbers for calculating percentage in #checkSignatures(SignedState)

---

platform-sdk/swirlds-common/src/test/java/com/swirlds/common/io/utility/FileUtilsTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileTests.java

Fixed #16948 using try-with-resources, similarly to fix #16947
Fixes #16948
**Checklist**

test: fixed 16948 leaking file descriptors

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeInfoHelperTest.java

Fixes #17063 
Currently the deleted nodes are also exported in `NodeStakeUpdate` synthetic transaction every day. Fixed it to export only active nodes.

fix: Export only active nodes in `NodeStakeUpdates`

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenClaimAirdropHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenClaimAirdropHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java

When submitting a tokenClaimAirdrop transaction, if one of the PendingAirdropIds in the list has an empty `senderId` or `receiverId` then the transaction fails catastrophically. This PR fixes the problem and adds unit tests and hapi tests to verify the fix.
Fixes #17095
Sister PR to develop: #17097

fix: tokenClaimAirdrop throws NPE on null sender or receiver

---

hiero-dependency-versions/build.gradle.kts

Some versions for _dependency groups_ – such as all `io.grpc:*` dependencies – were defined multiple times. This let to multiple Dependabot PRs for the same versions, leading to inconsistencies between merging of the several PRs.
Each repeated version is now only defined once in a `val` in the `hiero-dependency-versions/build.gradle.kts` file. This notation is supported by Dependabot.

build: remove duplicated dependency versions

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenClaimAirdropHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenClaimAirdropHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java

Description:
When submitting a tokenClaimAirdrop transaction, if one of the PendingAirdropIds in the list has an empty senderId or receiverId then the transaction fails catastrophically. This PR fixes the problem and add unit tests and hapi tests to verify the fix.
Fixes https://github.com/hashgraph/hedera-services/issues/17095
This PR is a cherry-pick of PR #17096

fix: tokenClaimAirdrop throws NPE on null sender or receiver (cherry-pick)

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/IssMetrics.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/DefaultIssDetector.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssDetectorTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssMetricsTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/RoundHashValidatorTests.java

Replaces usage of AddressBook with Roster in DefaultIssDetector.
Fixes #16741 
None
**Checklist**

chore: refactor DefaultIssDetector to use rosters

---

.github/workflows/node-flow-deploy-release-artifact.yaml

Add GH_TOKEN env variable in Check Prep XTS Job & Check Integration Job State
Fixes #17159

ci: Update Check Integration/XTS Job State to include GH_TOKEN

---

.github/workflows/node-flow-deploy-release-artifact.yaml

Adds id_token: write permission to `node-flow-deploy-release-artifact.yaml`
**Related Issue(s)**
Relates to #17159

ci: add id_token write permission to node-flow-deploy-release-artifact.yaml

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersDecoderTest.java

As described in the below issue, consolidate the hbar transfer list when decoding verses after dispatch to token service.
Fixes #17163 
**Checklist**

feat: consolidate hbar transfer list when decoding cryptoTransfer function

---

settings.gradle.kts

Cherry-pick the version roll of gradle build conventions to version 0.1.4.
Fixes #17148 
**Checklist**

build: Roll hiero gradle conventions to version 0.1.4 (#17149)

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/ExecutorComponent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutor.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneModule.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java

chore: support `maxSignedTxnSize` override in standalone `TransactionExecutor`

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BootstrapConfig.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java

- Adds a new `bootstrap.throttleDefsJson.file` configuration option
- This config specifies the optional file on disk containing throttles to be loaded during genesis  
- Changes the `bootstrap.throttleDefsJson.resource` configuration option
- This config now only specifies the optional classpath resource containing throttles to be loaded during genesis  
- Adds a universal fallback to the loading mechanism which defaults to loading mainnet values from the `genesis/throttles.json` classpath resource, if the `bootstrap.throttleDefsJson.file` and the `bootstrap.throttleDefsJson.resource` files are not present
- Closes #17177 
- `release/0.58`

feat: support universal fallback for throttles.json genesis loading

---

hedera-node/configuration/dev/application.properties
hedera-node/hedera-app/src/main/java/com/hedera/node/app/roster/schemas/RosterTransplantSchema.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/MerkleStateLifecyclesImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/roster/schemas/V0540RosterSchemaTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/MerkleStateLifecyclesImplTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NetworkAdminConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MerkleStateLifecycles.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchema.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/service/schemas/V058RosterLifecycleTransitionSchemaTest.java

- Closes #17171 
- Makes `MerkleStateLifecyclesImpl#onUpdateWeight()` an explicit no-op since it no longer affects startup phase state changes.

chore: only override weights for new node ids

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/ExecutorComponent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutor.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneModule.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java

chore: (0.58) support maxSignedTxnSize override in standalone TransactionExecutor

---

gradle/wrapper/gradle-wrapper.properties
gradlew
hedera-node/hedera-app/build.gradle.kts
hiero-dependency-versions/build.gradle.kts
settings.gradle.kts

- Gradle 8.12
- com.google.jimfs:jimfs:1.3.0 - now has an Automatic-Module-Name
- commons-codec:commons-codec:1.17.1 - now has a `module-info`
- org.jetbrains:annotations:26.0.1 - now has a `module-info`

build: bump Gradle and module versions 

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ByteStringUtils.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/fee/FeeBuilder.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/accounts/BBMHederaAccount.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/utils/ThingsToStrings.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/WritableFreezeStore.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/CreateSyntheticTxnFactory.java

This PR updates all object comparisons to use equals instead of == except for a few instances where reference comparisons are per design.
Fixes #16639
A zero-length PBJ Bytes is not necessarily Bytes.EMPTY so nothing should depend on object equality with Bytes.EMPTY. Using == for comparing objects is an anti-pattern in Java.

fix: change == to .equals for Bytes.EMPTY and other non-primitive types

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/timingSensitive/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java

Fix summary: fixed a thread race in `VirtualNodeCache.filterMutations()`.
Fixes: https://github.com/hashgraph/hedera-services/issues/17218

fix: 17218: Learner: ERROR "NullPointerException: Cannot invoke "com.swirlds.virtualmap.internal.cache.VirtualNodeCache$Mutation.isDeleted()"

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/BlockContentsValidator.java

Fixes https://github.com/hashgraph/hedera-services/issues/17202
Adds `BlockHeader. first_transaction_consensus_time` by iterating through `ConsensusTransaction` in the round and set the first non-null consensus time.

fix: Set `BlockHeader.first_transaction_consensus_time`

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabAddresses.java

Instead of synchronizing on the getter value, capture the value in a local variable and synchronize around that and also use it to generate the output string instead of making the getter call again.
Fixes #16726 
This change should be non-impactful and as such all tests that worked before should continue to work.
**Checklist**

chore: Synchronize around local reference to collection instead of synchronizing on the getter result directly

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java

Signed-off-by: Iris Simon <iris.simon@swirldslabs.com>
(cherry picked from commit 66ebd29a5c0ef78b7a264234e9788c82c2cff8a9)
Cherry-pick PR #17253
Fixes #17067
**Checklist**

feat: cherry-pick: Generated Files 101 & 102 Sequentially Ordered by Node ID

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java

Enable the `scheduleNative` feature flag as the development is now done
[#16964](https://github.com/hashgraph/hedera-services/issues/16964)
Fixes #
**Checklist**

chore: enable scheduleNative feature flag

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileWriter.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java

This PR swaps writing the current address book with the state snapshot to writing the current roster.  The code was already changing the roster to an address book.  This removes the translation and adjusts variable names appropriately. 
Fixes #17089

refactor: write current roster with state snapshot

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileIterator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesMultiFileIterator.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/PcesWriterTestUtils.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesReadWriteTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java

fix: PcesReadWriteTests.corruptedEventTest

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
platform-sdk/swirlds-virtualmap/src/timingSensitive/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/17237 to release 0.58
Fixes: https://github.com/hashgraph/hedera-services/issues/17283

fix: 17283: Backport the fix for #17218 to release 0.58

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/internal/StaticPlatformBuilder.java

This PR unifies the process of starting logging between Browser and ServicesMain, and starts logging at the beginning of the process for either entry point.  The `Node is Starting` banner has been added to the `initLogging` method to show up as the first log message.  
If all goes correctly, the `Node is Starting` banner is the first log entry in the swirlds.log on the JRS runs.  
Fixes #16623

refactor: move init logging to start of process

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/BlockItemNonceValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/BlockNumberSequenceValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java

This pull request introduces two new block validators and updates the `StreamValidationOp` class to incorporate these new validators. 
New validators added:
* [`BlockItemNonceValidator`](diffhunk://#diff-a16779dd197d97a0f5f4c9863b3f5ed21e6640bbbc025938cfcc6c6c93af6bfaR1-R102): Ensures nonces are properly incremented for related transactions.
* [`BlockNumberSequenceValidator`](diffhunk://#diff-84537cd202323508e7d7aa697bf74213cdc12ff66351da1a7d0fd6839a302f34R1-R75): Ensures block numbers are sequential and not repeated in the block stream.
Updates to `StreamValidationOp`:
* Added license header to `StreamValidationOp.java`.
* Imported the new block validators.
* Updated `BLOCK_STREAM_VALIDATOR_FACTORIES` to include the new validators.
Fixes #15409 …

chore: Additional Block Stream Validators for number and nonce

---

.github/CODEOWNERS
docs/maintainers-guide.md

Rename devops-ci to platform-ci
Fixes #17380

chore: Update codeowners/docs to include platform-ci name change

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxf-deploy-integration.yaml

Clean up Node: Build Application workflow calls
Fixes #17233
This is PR containing just a suggestion for changes and can be closed at any time.
**Checklist**

ci: Clean up Node: Build Application workflow calls

---

hapi/hedera-protobufs/block/stream/block_item.proto
hapi/hedera-protobufs/block/stream/record_file_item.proto
hapi/hedera-protobufs/services/node_create.proto

There were some small recent changes to the proto definitions in `hedera-protobufs` that need to be reflected in the services code before we sync back to there from `services` the latest up to date protobufs 
Fixes #17397

chore: sync changes from hedera-protobufs

---

hedera-node/test-clients/build.gradle.kts
settings.gradle.kts

Use `id("org.hiero.gradle.feature.shadow")` to simplify setup in 'test-client' project.
Release Notes: https://github.com/hiero-ledger/hiero-gradle-conventions/releases/tag/v0.3.1

build: update hiero-gradle-conventions to 0.3.1

---

hedera-node/hedera-app/build.gradle.kts

The gradle run task is broken , because there are no CLI arguments to run a local node.
Fixed it by adding a nodeId for the `localNodesToRun`

fix: fix gradle run task to include a nodeId from cli arguments

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/DiskStartupNetworks.java

In the case where we don't have a `genesis-network.json` file present at startup, `DiskStartupNetworks.genesisOrThrow(...)` correctly falls back to loading `config.txt` etc. to produce the `Network` object. We need to do the same for migration cases, so this PR adds that same fallback to `DiskStartupNetworks.migrationOrThrow()`. 
Closes #17257

chore: Fall back to legacy config loading in migration startup

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/util/FileUtilities.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/FacilityInitModule.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/ConfigProviderImplTest.java

fix: retain override values on `ConfigProviderImpl.update()` (#17424)

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecContract.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/operations/transactions/AuthorizeContractOperation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java

Adding some test cases for HIP-904 where sender is a contract
Fixes #16262
Fixes #16263 
Fixes #16264 
Fixes #16265 
Fixes #16266 
Fixes #16267 
Fixes #16268 
This PR is owned and authored by @bubo 
**Checklist**

test: HIP-904 Additional e2e test cases where sender is a contract

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/system/HapiStateSignature.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/StateSignatureCallbackSuite.java

This PR adds an implementation of `SwirldMain.encodeSystemTransaction()` in `Hedera`.
Fixes #17073 
**Checklist**

chore: Add factory method for StateSignatureTransaction

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java

Fixes: https://github.com/hashgraph/hedera-services/issues/17219

fix: 17219: WARN EXCEPTION "virtual-map: cache-cleaner StandardFuture: Future has already been cancelled"

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemSetup.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java
hedera-node/hedera-file-service-impl/src/main/java/module-info.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/GroupingVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip993/SystemFileExportsTest.java

Cherry pick #17278
Fixes #17247
**Checklist**

fix: cherry-pick: FileService address book and node details should be updated at genesis

---

.github/workflows/config/node-release.yaml

This pull request updates the release schedule in the `node-release.yaml` configuration file. The most important change is the rescheduling of the release date and the corresponding version update.
Release schedule update:
* [`.github/workflows/config/node-release.yaml`](diffhunk://#diff-0eafb62babc7f1fe6968a22d9623ac6b5dfb99d2100f819a024f89f953d749e4L6-R10): Changed the release date from "2024-12-20" to "2025-01-24" and updated the release name from "release/0.58" to "release/0.59" along with the initial tag name from "v0.58.0-alpha.0" to "v0.59.0-alpha.0".

chore: Schedule release 0.59 branch creation

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileIterator.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesReadWriteTests.java

quick fix for #17500
In [this PR](https://github.com/hashgraph/hedera-services/pull/17312) I unsuppressed these exceptions and now they are breaking JRS tests. This is a quick fix to get the tests running while the issue is investigated more.

chore: fix JRS tests failing because of PCES

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/GrpcConfig.java

This pull request includes a change to the `GrpcConfig` class in the `hedera-node` project. The change modifies the default value of the `nodeOperatorPortEnabled` property to true.
* [`hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/GrpcConfig.java`](diffhunk://#diff-5a8d1c9a9cc0ddc0d484472309c26bc955ccaabf42f043f6a5a42e198def483fL49-R49): Changed the default value of `nodeOperatorPortEnabled` from false to true.
Fixes #17468 
**Checklist**

chore: GrpcConfig nodeOperatorPortEnabled default to true

---

.github/workflows/zxc-verify-docker-build-determinism.yaml

Scopes the usability of `Write Artifact Version Descriptor` to only enable when a baseline exists.
Fixes #17510

fix(ci): Add conditionals on Write Artifact Version Descriptor

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
hedera-node/hedera-app/src/main/java/module-info.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/concurrent/AbstractTask.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/crypto/MerkleCryptographyFactory.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/crypto/internal/MerkleCryptoEngine.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/hash/FutureMerkleHash.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/hash/MerkleHashBuilder.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/internal/ConcurrentTask.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/internal/SequentialTask.java
platform-sdk/swirlds-component-framework/src/main/java/module-info.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
platform-sdk/swirlds-merkledb/src/main/java/module-info.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
platform-sdk/swirlds-virtualmap/src/main/java/module-info.java

* reimplemented MerkleHashBuilder using the task framework; eliminated thread contention
* moved AbstractTask from the wiring framework to swirlds-common (removed unjustified dependencies)
* merged two thread pools used by `MerkleHashBuilder` and `VirtualHasher`
Fixes #7582
**Checklist**

perf: `MerkleHashBuilder` does not scale

---

docs/gradle-quickstart.md
docs/intellij-quickstart.md
hedera-node/docs/design/modules.md
hedera-node/docs/design/services/service-modules.md
platform-sdk/README.md

This updates all documentation referring to Gradle and module setup to the current state. The documentation on "Defining modules and dependencies" was moved to https://github.com/hiero-ledger/hiero-gradle-conventions#modules and updated/extended. This PR adds several links to the documentation in that repository that is now the same for other Hiero and Hedera projects.
#14255
I updated the following files so that they are not outdated anymore. Although I think they could use some general revision on the non-Gradle part (for example, _integration tests_ do not exist in this repository at the moment).
- [docs/design/modules.md](https://github.com/hashgraph/hedera-services/blob/14255-doc-update/hedera-node/docs/design/modules.md) …

chore: update Gradle build documentation

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java

Headlong's `RLPItem.asBigInt` preferred over `asByte/asInt/asLong`.
Fixes #17523 
**Checklist**

refactor: use preferred headlong API when decoding RLP

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/AppClient.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolStateLifecycles.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PttTransactionPool.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/PlatformTestingToolStateTest.java

This PR fixes  `PlatformTestingTool` tests
Fixes #17501 
**Checklist**

fix: 17501 Fixed PlatformTestingTool initialization.

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomMessageCallProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameUtilsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DisabledPrecompileTest.java

Add a feature flag for disabling calls to precompile contracts 
**Checklist**

feat: add feature flag for disabling precompile contracts

---

platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/merkle/test/MerkleRehashTests.java

The test hangs after #17437 due to inducing an exception in a situation impossible in actual code.
Moved throwing exception from root (internal node) to the first child (leaf node).
**Checklist**

test: fix `MerkleRehashTests.failedRehash()` unit test

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/PlatformTestingToolStateTest.java

Fixes compiler error for the `compileTestJava` task

fix: Reference correct `main` obj in test

---

.github/workflows/node-flow-deploy-release-artifact.yaml

The gh workflow list call was not properly scoped to a sufficiently large number of workflows. Adding the `--limit 200` command line argument satisfies the needs of the gh workflow tool.
Fixes #17582
**Checklist**

ci: Fix Check Integration Job State step to detect properly

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountRecordsHandlerTest.java

Code coverage increased from 72.09% to 95.35%
Fixes #17410 
**Checklist**

test: Increase code coverage in `CryptoGetAccountRecordsHandler`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImplTest.java

Use `.thenAcceptAsync()` to ensure `finishProofWithSignature()` is executed off the transaction handling thread.
Fixes #17597
**Checklist**

perf: performance regression in `BlockStreamManagerImpl.endRound()`

---

platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/TaskScheduler.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/transformers/WireFilter.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/transformers/WireListSplitter.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/transformers/WireRouter.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/transformers/WireTransformer.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/wires/output/OutputWire.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/benchmark/WiringBenchmark.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/component/WiringComponentPerformanceTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/model/DeterministicHeartbeatSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/model/DeterministicModelTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/model/ModelTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/schedulers/ConcurrentTaskSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/schedulers/DirectTaskSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/schedulers/HeartbeatSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/schedulers/NoOpTaskSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/schedulers/SequentialTaskSchedulerTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/transformers/TaskSchedulerTransformersTests.java
platform-sdk/swirlds-component-framework/src/test/java/com/swirlds/component/framework/wires/OutputWireTests.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/GossipWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PassThroughWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PcesReplayerWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/RunningEventHashOverrideWiring.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/EventWindowManagerTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/stream/ConsensusEventStreamTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/gossip/SimulatedGossipTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/SignedStateReserverTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java

Removes the unsafe `cast()` method from TaskScheduler and replaces its uses with the correct generics invocation.
Fixes #17592

chore(17592): Remove unsafe cast in TaskScheduler

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomMessageCallProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameUtilsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DisabledPrecompileTest.java

Cherry pick https://github.com/hashgraph/hedera-services/pull/17548 into release 0.59

chore: 17548 cherry pick into 0.59

---

hiero-dependency-versions/build.gradle.kts

`hamcrest` is a test assertion library that is not part of the production code. We do not use it (anymore). We use `assertj`, which is an alternative library for test assertions.
This PR removes the version so that we do not track it anymore and have to deal with Dependabot updates.

build: remove hamcrest version from dependency version list

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/HintsLibrary.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/HintsService.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsLibraryCodec.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/hints/impl/HintsLibraryImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/TransactionExecutors.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsLibraryCodecTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/hints/impl/HintsLibraryImplTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/fakes/FakeHintsService.java

chore: Update `HintsLibrary` for CRS mgmt functions

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/UserTxnFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneDispatchFactory.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/BlockOpeningTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/UserTxnTest.java

chore: always use current `PreHandleResult` when checking for `STATE_SIGNATURE_TRANSACTION`

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/RandomVirtualMapReconnectTests.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fix summary:
* "vm_size" metric is updated explicitly in `VirtualRootNode.postInit()`. This method is called both when a new map is created, and when a map is initialized after reconnect
* A new unit test is provided
Fixes: https://github.com/hashgraph/hedera-services/issues/17062

fix: 17062: VirtualMap metrics are wrong after reconnect

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/UserTxnFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/standalone/impl/StandaloneDispatchFactory.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/BlockOpeningTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/UserTxnTest.java

Cherry picks commit `10f1bcf` always use current PreHandleResult when checking for STATE_SIGNATURE_TRANSACTION for release 0.59.
Fixes #17682
**Checklist**

chore: cherry-pick: 17682 always use current `PreHandleResult` when checking for `STATE_SIGNATURE_TRANSACTION`

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java

This PR adds missing wire soldering that collects state signatures after state hashing.
**Related issue(s)**: #16707 
Fixes #
**Checklist**

fix: solder missing wire for state signature collecting

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorized/IsAuthorizedCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SignatureMapUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/utils/SignatureMapUtilsTest.java

Need to support chain ids such that encoding them in the `v` part of the signature according to EIP-155 works for "large" chain ids, such as Hedera's own.
Fixes #17273
**Checklist**

fix: EIP-155 support in isAuthorized/isAuthorizedRaw

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java

This PR removes changes from a previous commit that adds unnecessary output wire.
**Related issue(s)**: #16707 
Fixes #
**Checklist**

fix: revert unnecessary output wire

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListHeap.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListOffHeap.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java

Fix summary:
* `AbstractLongList.readDataIntoBuffer()` is changed, so it doesn't set buffer position/limit
* In case of `LongListHeap` and `LongListDisk` the returned buffer isn't used directly, and they set the position/limit anyway
* In case of `LongListOffHeap` the buffer is used directly as a chunk. It's now consistent with all other chunks, they never have position/limit set
* When a `LongListOffHeap` is written to a file, the first and the last chunks are handled appropriately, no need to change that code
* A new unit test is provided
Fixes: https://github.com/hashgraph/hedera-services/issues/17803

fix: 17803: LongListOffHeap snapshots + updates are broken

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Utilities.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/modular/PeerCommunication.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/modular/SyncGossipModular.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ReconnectMetrics.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/ConnectionManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/InboundConnectionManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/OutboundConnectionManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/PeerInfo.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/OutboundConnectionCreator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/protocol/ReconnectProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/protocol/SyncProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/topology/StaticConnectionManagers.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/NetworkPeerIdentifierTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/OutboundConnectionCreatorTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/StaticConnectionManagersTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/communication/multithreaded/ReturnOnceConnectionManager.java

This change reduces dependency of gossip network code on Roster class, moving to List/Collection<PeerInfo> instead. This is needed as a preparation for dynamic connections for DynamicAddressBook
* Add port to PeerInfo
* Change Roster to List<PeerInfo> in multiple places
* Reduce dependency on Topology in StaticConnectionManager
Fixes #17812
**Checklist**

chore: Changed Roster to List<PeerInfo> wherever possible, in preparation for dynamic connections

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxcron-release-branching.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxf-collect-workflow-logs.yaml

Change yaml instances calling out to hashgraph/hedera-services to point to hiero-ledger/hiero-consensus-node
Fixes #17902

chore: Update github workflow references to hiero-consensus-node

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/WritableQueueStateBaseTest.java
platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableQueueStateBase.java

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/17904
- Fixes the missed variable `currentAddedElementIndex` that should be reset on `WritableSingletonSttaeBase.commit()`
- Resets all stateful variables on `WritableSingletonSttaeBase.commit()` call.

fix: Reset stateful variables in WritableQueueStateBase on `commit()`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockImplUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/AbstractNode.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/AddressBookUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/entities/SpecAccount.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CommonUpgradeResources.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/UpgradeSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/BalanceValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsNodeDeathReconnectTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/FutureSchedulableOpsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/PrivilegedOpsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java

Fixed failing Hapi tests for non-zero shard/realm values in the following packages:
Fixes https://github.com/hashgraph/hedera-services/issues/17681
- `utils` package doesn't contain Hapi tests, so nothing to fix there
- There are some tests failing because they use ContractCreate transactions, those should be fixed as part of work done by HSCS team:
- AddressAliasIdFuzzing
- CompletedHollowAccountOperationsFuzzing
- HollowAccountCompletionFuzzing
- UmbrellaRedux
- stakingMetadataUpdateIsRewardOpportunity
- txOverGasLimitThrottled
- precompileNftMintsAreLimitedByConsThrottle
- contractInfoQueriesAsExpected
- associatedContractsMustHaveAdminKeys
- dissociateHasExpectedSemanticsForDissociatedContracts
- …

feat: add fixes for Hapi test suites with non-zero shard or realm values

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/DiskStartupNetworks.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoader.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/CryptoArgsProvider.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/EnhancedKeyStoreLoaderTest.java

- Cherry picks changes to `EnhancedKeyLoader` private key detection and loading logic to avoid using `AddressBookNetworkUtils.isLocal()`
- Resolves startup issues when using internal addresses with an overlapping internal IP range
- Fixes #17951

fix(release/0.58): backport changes from release 0.59 related to enhanced key loader private key detection

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java

Covering the negative test cases for fee charging for HIP-551.

test: HIP-551 fee charging negative test cases

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/util/ProtobufUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowInjectionModule.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionCheckerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/AtomicBatchHandler.java
hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/AtomicBatchHandlerTest.java

This PR ensures we use the raw bytes of `TransactionBody` sent by the user. This is critical because the deserializing and serializing a Protobuf object may lead to different results which would break any signatures.

feat: Extract raw bytes from user input

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/SubmitMessageSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/ScheduleLongTermSignTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

- Closes #17952 by replacing use of `executionEnd` with `boundaryStateChangeListener.lastConsensusTimeOrThrow()`.
- Removes legacy uses of the `"ADHOC"` test tag to simplify using it to run a targeted `@HapiTest` with stream validation via `./gradlew hapiTestAdhoc`.

fix: Give `StateChanges` purging unexecuted schedules the latest consensus time

---

platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/ReadableKVStateBase.java
platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/WritableKVStateBase.java

This PR modifies `ReadableKVStateBase` and `WritableKVStateBase` classes in order to make the read and write cache more customizable as a structure. This change is needed for the mirror node team in order to substitute our own scoped value based cache for concurrency reasons with historical state.
This PR is opened as a substitute for https://github.com/hiero-ledger/hiero-consensus-node/pull/17819
Fixes: #17818

feat: Make base read and write state classes more customizable by constructor overload

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListHeap.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListOffHeap.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/17804 to `release/0.59`.
Fixes: https://github.com/hashgraph/hedera-services/issues/17841

fix: 17841: Backport the fix for 17803 to release 0.59

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriter.java

This pull request includes changes to the logging level in the `FileBlockItemWriter` class.
Logging level adjustments:
* [`hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriter.java`](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL130-R132): Changed the logging level from `info` to `debug` for the messages indicating the start and close of a block, and added checks to ensure these messages are only logged if debug logging is enabled. [[1]](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL130-R132) [[2]](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL161-R165)
Fixes #18069  …

chore: Change some log info statements to debug level in `FileBlockItemWriter`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriter.java

This pull request cherry-picks the changes to the logging level in the `FileBlockItemWriter` class.
Logging level adjustments:
* [`hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriter.java`](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL130-R132): Changed the logging level from `info` to `debug` for the messages indicating the start and close of a block, and added checks to ensure these messages are only logged if debug logging is enabled. [[1]](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL130-R132) [[2]](diffhunk://#diff-c7ba90e615b00d8264c70c4eab891ed4e504538d4a19e157d2d2f6ae562026afL161-R165)
Fixes #18069  …

chore: cherry-pick: Change some log info statements to debug level in `FileBlockItemWriter`

---

hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18045
Allow setting expiry when adminKey is not set and autoRenewAccount is set

fix: Update expiry when adminKey is not set and autoRenew is set

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/AtomicBatchHandler.java
hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/AtomicBatchHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java

Rename response code BATCH_TRANSACTION_NOT_IN_WHITELIST to BATCH_TRANSACTION_IN_BLACKLIST
Fixes #18065

fix: rename atomic batch enum code

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BlockStreamConfig.java

Cherry pick's cc03859208c0719b6f488c966e590bc278a5209e regarding the issue as described below.
Currently there is an issue with `DefaultIssDetector` only looking at `StateSignatureTransaction`'s from boundary rounds, therefore ISS's will most likely be missed.
Let's fall back to `roundsPerBlock` of 1 until this issue is fixed.
Fixes #
**Checklist**

chore: cherry-pick Set `blockPeriod` to 0 in `BlockStreamConfig`

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BlockStreamConfig.java

Currently there is an issue with `DefaultIssDetector` only looking at `StateSignatureTransaction`'s from boundary rounds, therefore ISS's will most likely be missed.
Let's fall back to `roundsPerBlock` of 1 until this issue is fixed.
Fixes #18106 
**Checklist**

chore: Set `blockPeriod` to 0 in `BlockStreamConfig`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/CompareStatesCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateAddressBookStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/protocol/ReconnectProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectPeerProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditor.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/StartupStateUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileReader.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StateFileManagerTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectPeerProtocolTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleNode.java

This PR is a follow-up to [[this pull request](https://github.com/hiero-ledger/hiero-consensus-node/pull/18050)](https://github.com/hiero-ledger/hiero-consensus-node/pull/18050) and addresses [[this comment](https://github.com/hiero-ledger/hiero-consensus-node/pull/18050#discussion_r1973206024)](https://github.com/hiero-ledger/hiero-consensus-node/pull/18050#discussion_r1973206024). It removes redundant parameters of the `Configuration` type when they can be taken from a `PlatformContext` instance.
Fixes #18083 
**Checklist**

refactor: 18083 Remove redundant `Configuration` parameter

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/utils/Signing.java

- Validates arguments given to secp256k1 native lib.
- Unifies `AccountAmount` deduplication logic to ignore `is_approval` in settings in pure checks as well.

chore: (0.59) Cherry-pick misc fixes

---

.github/workflows/zxc-verify-docker-build-determinism.yaml
.github/workflows/zxc-verify-gradle-build-determinism.yaml

Cherry picks fix from main to update ubuntu runners in gradle determinism to use 22.04/24.04 instead of 20.04/22.04
(cherry picked from commit 0a994c1c91ac9cb8779e85c19abe8ca2f0e428d3)
Fixes #18180

ci: update ubuntu version to 24.04 and 22.04

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/HelloWorldEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/utils/Signing.java

- Validates arguments given to secp256k1 native lib.
- Unifies `AccountAmount` deduplication logic to ignore `is_approval` in settings in pure checks as well.

chore: (0.60) Cherry-pick misc fixes

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/stale/StaleEventDetectorTests.java

StaleEventDetectorTests.eventIsStaleBeforeAddedTest was failing sometimes (in 1/100 of the cases), because it used random(100) to offset stale even from the ancient threshold. Unfortunately, sometimes that random was 0, which meant birthRound==ancientThreshold, which is NOT considered ancient/stale.
Fixes #18192 
**Checklist**

fix: Stale event test was failing in 1/100 of cases due to randomness 

---

build.gradle

The Synk UI is detecting our projects multiple times because it thinks each "build.gradle.kts" marks a separate project. This is caused by this issue: https://github.com/snyk/snyk-gradle-plugin/issues/298
This is a workaround until it is fixed upstream by Snyk.
#17897

ci: add empty 'build.gradle' to root for Snyk integration

---

.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/node-zxf-snyk-monitor.yaml
.snyk
gradle/aggregation/build.gradle.kts

- No extra step to disable configuration cache needed anymore. [Snyk now does this automatically.](https://github.com/snyk/snyk-gradle-plugin/blob/9589d184dcf5baba8e198074b4f2746e5ec3a8ad/lib/index.ts#L748)
- `build.gradle` in root (already merged #18199) to work around https://github.com/snyk/snyk-gradle-plugin/issues/298
- Focus the analysis on the `aggregation` project that contains all dependencies we use in all scopes in the `mainRuntimeClasspath` _configuration_. This is used in the Gradle plugins already for consistent versioning and Jar patching. Hence, this contains all dependencies used in **all** modules.
- This is done by running with `--subProject=aggregation` and `--configuration-matching=mainRuntimeClasspath` 
Fixes #17897

ci: fix and cleanup snyk/gradle integration

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-pull-request-checks.yaml
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/IssHandlingTestSuite.java

Enables hapi-iss-tests to run as part of Standard PR Checks Adds hapi-iss-tests to build-application workflow-dispatch triggers Enables the IssHandlingTestSuite
Fixes #18198

ci: Enable IssHandlingTestSuite in CI PR Checks

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AncientAgeBirthRoundTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/PlatformEvent.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/branching/DefaultBranchDetector.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesBirthRoundMigration.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileIterator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/BirthRoundStateMigration.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/DefaultBirthRoundMigrationShim.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/EventMetadata.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/UnsignedEvent.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/system/events/EventMetadataTest.java

This PR creates a HAPI test for birth round migrations.
With that in mind, there are also a couple of code changes included that move us closer to having birth rounds functional. These changes include:
- Re-reading the PCES files after the files have been converted from generation-based to birth round-based. This needs to be done because the PCES files are loaded on startup and the migration replaces those old PCES files with the new migrated ones.
- Remove re-calculating the hashes as the final state in the `BirthRoundStateMigration` because later in startup we expect the state to not be hashed.
- When a birth round migration has happened, set the lower bound to 0 when reading the PCES events such that they are all read and not prematurely filtered out.
- Override the …

feat: Create a HAPI test to validate birth round migration

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip423/DisabledLongTermExecutionScheduleTest.java

Validating that if the long-term schedules is disabled the `expiration_time` field is not populated
Fixes #7211
**Checklist**

feat: add SCHEDULE_EXPIRY_NOT_CONFIGURABLE validation

---

.github/workflows/zxc-verify-docker-build-determinism.yaml
.github/workflows/zxc-verify-gradle-build-determinism.yaml
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java

- Fail airdrops that use royalties with _or without_ fallback fees.

chore: Prohibit all airdrop royalty fees

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/utils/Signing.java

- Validates arguments given to secp256k1 native lib.
- Unifies `AccountAmount` deduplication logic to ignore `is_approval` in settings in pure checks as well.

chore: (0.58) Cherry-pick misc fixes

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java

- Prohibit both fallback _and_ non-fallback royalty fees in token airdrops.

chore: Prohibit airdrop royalty fees 

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java

Fix summary: direct backport of https://github.com/hiero-ledger/hiero-consensus-node/pull/18250 to the release/0.59 branch.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18267

fix: 18267: Backport the fix for 18235 to 0.59

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java

Fix summary: direct backport of https://github.com/hiero-ledger/hiero-consensus-node/pull/18250 to the `release/0.60` branch.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18266

fix: 18266: Backport the fix for 18235 to 0.60

---

platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/map/MapTest.java

Fix summary: make sure all virtual map copies created in `MapTest.insertRemoveAndModifyOneMillion()` are released and fully processed before the test is complete.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18363

fix: 18363: Random test failures because MapTest destroys virtual map copies asynchronously

---

hedera-node/hedera-app/build.gradle.kts
platform-sdk/swirlds-platform-core/build.gradle.kts

This addresses these warnings currently emitted on `main`:
```
[WARN] [Java Module Dependencies] com.hedera.cryptography.altbn128=group:artifact missing
[WARN] [Java Module Dependencies] com.swirlds.platform.test=group:artifact missing
```
The modules in questions no longer exist. This was an oversight in the corresponding PRs that removed the use of these modules.

chore: remove incorrect/unused 'requires' entries

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java

This is a cherry-pick from #18272 with resolved merge conflicts
Fixes #18405

fix: 18405: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved - cherry-pick.

---

platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/map/MapTest.java

This Pr addresses a test flake from this commit: https://github.com/hiero-ledger/hiero-consensus-node/pull/18364/files
by temporarily increasing the duration of the check.
Fixes #18363
**Checklist**

fix: Extended suite failure during insertRemoveAndModifyOneMillion

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/getevmaddressalias/EvmAddressAliasCall.java

This PR fixed a behaviour that was checking whether the alias is 20 bytes long.
Now it uses a helper method from `AliasUtils` to verify and extract the given alias
Fixes #17570 
**Checklist**

fix: HIP-632 fix alias length check

---

.github/workflows/flow-increment-next-main-release.yaml

Fix a typo in workflow file, change `input` to `inputs`
Fixes #18472

ci: fix typo in workflow input file 

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java

This is a cherry-pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/18406
Fixes #18410

fix: 18410: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved 

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/sysfiles/domain/throttling/HapiThrottleUtils.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/sysfiles/domain/throttling/ThrottleBucket.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ThrottleDefValidationSuite.java
hedera-node/test-clients/src/main/resources/testSystemFiles/lcm-overflow-throttles.json

- Add validation to check if the throttle group's milliOpsPerSec least common multiple is overflowing on FILE_UPDATE to 0.0.123
Fixes #13295
**Checklist**

fix: Should reject a FILE_UPDATE to 0.0.123 with an invalid throttle definition

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakeInfoHelperTest.java

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/18499
- We have added migration code to migrate all the entityCounts using `KVState.size()` to `EntityIdService.ENTITY_COUNTS` in 0.59
- Since, this migration code would have run in 0.60, this code must be deleted before we enable MegaMap.

chore: Remove the entityCounts migration code in 0.61

---

platform-sdk/consensus-utility/build.gradle.kts
platform-sdk/consensus-utility/src/main/java/org/hiero/consensus/utility/ByteUtils.java

This PR makes an implicit cast in `ByteUtils` explicit and enables failing on compiler warnings
Fixes #18566 
**Checklist**

chore: fix compiler warning in ByteUtils

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/IssHandlingTest.java

- Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/18554

fix: Ensure `BlockStreamManager#endRound()` is called after dispatching

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/KeyUtils.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Secp256k1Utils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/SigControl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/AccessoryUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromEcdsaFile.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromFile.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromLiteral.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromMnemonic.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromPem.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/TypedKey.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/CreateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/RekeyCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/keys/ExtractDetailsCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/RekeySuite.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java
hedera-node/test-clients/yahcli/README.md
hedera-node/test-clients/yahcli/run/build.sh
hedera-node/test-clients/yahcli/run/publish.sh

This PR adds support for ecdsa keys to the accounts `rekey` command. Accounts with an admin ecdsa key can now use `rekey` to 'import' a new key (via `-k`) without running into an error trying to incorrectly unmarshall the key. 
Other noteworthy modifications:
* Adds ecdsa support to the framework's default payer key
* Fixes a stub exception encountered when the default shard/realm is applied
* When rekeying with a pre-existing key, relax the assumption of super-admin privileges to an account's normal administrative key instead
Closes #18327

feat: Enhance yahcli rekey with ECDSA support

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/modular/PeerConnectionServer.java

Due to one of the previous changes, amount of threads handling SSL certification resolution for new connections was only one, which could have starved the processing. This change reintroduces the possibility of using more threads concurrently (30 at the moment, based on configuration), while still having max number of them, with overflow being handled in the caller thread (which will block the acceptance rate of new connections, but won't crash the server with runaway threads). Behavior from before the original change (infinite number of threads) can be achieved by changing configuration (maxSocketAcceptThreads) to a very large number.
Fixes #18498 
**Checklist**

fix: Utilize more than one thread for SSL accept handling

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java

Fix summary:
* When a MerkleDb data source instance is created from existing data files, and path to hash / path to KV indices are restored, leaf path range is taken into consideration. Old data files may contain entries outside the current path range, now these entries are ignored
* Testing: there is an existing test to check that MerkleDb indices can be restored from data files. This test is improved, so it checks multiple different path ranges, not just one
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18571

fix: 18571: Current path range should be respected when path to hash and path to KV indices are restored

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java

`currentSubmitTask` keeps a reference to `SubmitTask`, iterator and `oneTransactionsData` between flushes.
Fixes #18626
**Checklist**

fix: memory leak in HalfDiskHashMap.endWriting()

---

.github/CODEOWNERS

Update the CODEOWNERS file team names to match hiero-ledger/governance repo names.
Fixes #18668

chore: update codeowners with new team names

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BoundaryStateChangeListener.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java

Since `boundaryStateChangeListener.lastConsensusTime()` will be set only when streamMode is Blocks or Both or once user transactions are handled, in Solo environments using `streamMode=RECORDS` will fail with NPE.
Delay dispatching node rewards until atleast one user transaction is handled

chore: fix NPE when using records

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml

Updates the data reported to slack for both extended test suite and promote build candidate to include the list of commits between build-XXXXX tags and also between xts-pass-* commits.
Closes #18681

chore: Update reporting to include commits in releases

---

.github/workflows/zxcron-extended-test-suite.yaml

Add a guard around commit list in zxcron extended test suite to provide an empty commit list if this is the first commit after a build is promoted
Fixes #18688

fix: Add guard around LATEST_XTS_PASS_TAG

---

.github/workflows/zxcron-promote-build-candidate.yaml

Adds workflow run URL to promoted build report success/failure steps
Closes #18692

ci: Add Workflow Run URL to slack output in promote build candidate

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTestBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAirdropHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenAirdropTest.java

Improve error handling for TokenAirdrops with multiple senders.
Currently when there is a FT with multiple senders we throw `INVALID_TRANSACTION_BODY`
and if there is NFT airdrops with multiple senders we throw `SENDER_DOES_NOT_OWN_NFT_SERIAL_NO`.
https://github.com/hiero-ledger/hiero-consensus-node/issues/18610
Fixes #
**Checklist**

fix: Improved error handling for airdrops with multiple senders

---

platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/module-info.java
platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/module-info.java
platform-sdk/platform-apps/demos/StatsDemo/src/main/java/module-info.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/module-info.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/module-info.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/module-info.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/turtle/runner/TurtleTests.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/runner/Turtle.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/runner/TurtleBuilder.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/runner/TurtleConsensusStateEventHandler.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/runner/TurtleNode.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/runner/TurtleTestingToolState.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/module-info.java

Moved remaining classes of turtle framework to test fixtures to make them available in other modules
Part of #18630

chore: move turtle framework to test.fixtures module

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/BlockStreamValidationOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java

❗ This PR is created and maintained by @gkozyryatskyy. It was initially approved by the `hiero-consensus-node-smart-contracts-codeowners` here #18608
When comparing record files to blocks, a failed Contract Create Result should NOT contain an Contract ID, the error message is CONTRACT_REVERT_EXECUTED.
Fixes [1280](https://github.com/hashgraph/hedera-smart-contracts/issues/1280)
- the actual fix is in `HederaEvmTransactionResult`
**Checklist**

fix: 1280 hip 1056 block item with failed contract create result contains a contract

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImplTest.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

- When we update a token's expiry with less than the current expiry time, we should get `EXPIRATION_REDUCTION_NOT_ALLOWED` error response code.  However, due to the differential testing with mono, we've mirrored the logic from there. Now that we are past the differential testing, we can return the correct error code.
- Additionally, I saw that we are doing the same for `AUTORENEW_DURATION_NOT_IN_RANGE`. I cleaned that.
- Making these changes made the `isForTokenUpdate` param in `resolveUpdateAttempt` not needed. I deleted that.
Fixes #18697
**Checklist**

fix: Remove mono logic returning the wrong response code

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java

The PR implements the handling of `ResendBlock`'s responses from Block Nodes. In those cases, the consensus node should restart the stream and try resending the specified block in the message or it might choose to end the stream if the specified block in `ResendBlock` message has already been acknowledged by any other connection.
Fixes #18254 
**Checklist**

feat: handle `ResendBlock` block node responses

---

platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundMigrationTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/HappyPathTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/SandboxTest.java

This PR disables all examples for the Otter Test Framework. The framework is not ready yet and the tests are not meant to be executed right now.
Part of #18630

chore: Disable all examples for Otter Test Framework

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowgraphSynchronizer.java

Moves the sorting of events prior to sending in a sync to the original location.
Fixes #18721

fix: Move sort before `filterLikelyDuplicates`

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java

We found a bug that only allows creation of accounts with shard/realm 0.0. This PR fixes that bug by relaxing the restriction to instead check that the account's shard/realm matches the node's configured shard/realm.

fix: Only allow creation of accounts that match the configured shard/realm

---

.github/CODEOWNERS

Cherry-picks dc044fd for release/0.61
Fixes #
**Checklist**

chore: (cherry-pick) remove github-committers team from codeowners

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java

Fix summary:
* `HDHM.repair()` is improved to check bucket ID integrity. That is, when a bucket is loaded for a bucket ID, this bucket's ID is checked against the ID from the index. If they don't match, the bucket is removed altogether from the index
* I couldn't think of a unit test to cover this case. With current code bucket index entries are never corrupted (but they used to in the past, this is why this mechanism is needed)
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18795

fix: 18795: HDHM repair mechanism can be improved to clean stale buckets

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml

Use the SLACK_CITR_OPERATIONS_WEBHOOK for the slack channel for XTS failures
Closes #18824

ci: Update slack channel for XTS failures

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenUpdate.java

- Fixing a flaky test
Fixes #18800
[Here](https://github.com/hiero-ledger/hiero-consensus-node/pull/18698/files#diff-f3dd7dace03e4f3e95b382d56d49c1f46781902d5d8e8f1639ca6396c38263e7L131) an old logic from mono was deleted. Because of that, when we have an `autorenew_duration` lower than **now**, we are now throwing `AUTORENEW_DURATION_NOT_IN_RANGE` instead of `INVALID_RENEWAL_PERIOD`.
The `completedHollowAccountOperationsFuzzing` test is doing a lot of **random** operations with **random** populated fields in them.
One of them is `RandomTokenUpdate`. In `RandomTokenUpdate.get` there is this line:
`randomUpdates.forEach(o -> o.accept(op));` 
It populates the operation with random keys, name, etc. One of the random populations, …

fix: flaky `completedHollowAccountOperationsFuzzing` test

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/Shadowgraph.java

closes #18565
this log statement no longer makes sense when using birth rounds since there can be birth rounds with no events

chore: remove obsolete log

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/consensus/ConsensusTestDefinitions.java

This test fixes the `Consensustests.CliqueTests()`. Checked by looking at the generated parent matrix.
Fixes #18826

chore: Fix for ConsensusTests.cliqueTests()

---

hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/validators/AddressBookValidator.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeUpdateHandlerTest.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java

We discovered that there is a genesis case where sys files 101 and 102 were empty. This PR fixes the problem by only creating sys files after the node metadata has been synthetically populated.
This PR also removes the deprecated requirement to include 'internal IP address' in gossip endpoints.
Fixes #18551

fix: Correctly populate sysfiles with node info

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18856

fix: 18856: ReconnectHashLeafFlusher uses a wrong config

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/LeakyBucketDeterministicThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/LeakyBucketThrottle.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/LeakyBucketDeterministicThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/LeakyBucketThrottleTest.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/impl/NetworkUtilizationManagerImplTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java

Add a separate config for backend max gas throttle.  Also add support for optional burst capability across multiple seconds.
Fixes #18614

feat: decouple backend throttle config from front end and add support for burst

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDb.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/ParsedBucket.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMapTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/MerkleDbTest.java

Fix summary:
* Backport of https://github.com/hiero-ledger/hiero-consensus-node/pull/18625 to the `release/0.61` branch
* Also contains changes from https://github.com/hiero-ledger/hiero-consensus-node/issues/18795, since this is a follow-up for #18625 above, it makes sense to backport them together
* Also contains changes from https://github.com/hiero-ledger/hiero-consensus-node/pull/18859
* Also contains changed from https://github.com/hiero-ledger/hiero-consensus-node/pull/18906
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/18771

fix: 18771: Backport fixes for 18593, 18795, 18844, and 18903 to release 0.61

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/standalone/TransactionExecutorsTest.java
platform-sdk/base-crypto/src/main/java/org/hiero/base/crypto/CryptoUtils.java
platform-sdk/base-crypto/src/main/java/org/hiero/base/crypto/internal/DetRandomProvider.java
platform-sdk/base-crypto/src/test/java/org/hiero/base/crypto/SerializablePublicKeyTests.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/stream/StreamFileSigner.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Utilities.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/KeysAndCerts.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossipModular.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/Address.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/crypto/SerializableX509CertificateTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/NetworkPeerIdentifierTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterRetrieverTests.java

This PR introduces `CryptoUtils`, a class with commonly used cryptographic functionality that is independent of the underlying domain model (unlike some of the functionality in `CryptoStatic`). This is preparatory work for moving `Address` and `AddressBook` to the `consensus-model` in the next step. Also, renamed `DetRandomProvider` to avoid confusion.
Part of #18927

chore: Introduced CryptoUtils

---

platform-sdk/swirlds-base/build.gradle.kts
platform-sdk/swirlds-base/src/main/java/module-info.java
platform-sdk/swirlds-base/src/testFixtures/java/module-info.java
platform-sdk/swirlds-config-extensions/build.gradle.kts
platform-sdk/swirlds-config-impl/build.gradle.kts
platform-sdk/swirlds-logging/build.gradle.kts
platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/api/internal/format/StackTracePrinter.java
platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/api/internal/format/StackTracePrinterTest.java
platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/test/internal/FilteredLoggingMirrorTest.java
platform-sdk/swirlds-logging/src/testFixtures/java/com/swirlds/logging/test/fixtures/util/Throwables.java
platform-sdk/swirlds-logging/src/testFixtures/java/module-info.java
platform-sdk/swirlds-merkle/build.gradle.kts
platform-sdk/swirlds-merkle/src/testFixtures/java/module-info.java
platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/merkle/test/MerkleSerializationTests.java
platform-sdk/swirlds-merkledb/build.gradle.kts
platform-sdk/swirlds-merkledb/src/testFixtures/java/module-info.java
platform-sdk/swirlds-state-impl/src/main/java/module-info.java
platform-sdk/swirlds-virtualmap/src/main/java/module-info.java
platform-sdk/swirlds-virtualmap/src/testFixtures/java/module-info.java

The goal of this PR (together with #18924 and #18922) is to enable running tests on the Java Module Path (as opposed to the Classpath which is used now). This is the first step towards resolving #11573 to eventually fully use the Java Module System at runtime.
To allow the tests to use the Module Path, we will use the so-called [_Whitebox Testing_ approach for Java Modules](https://github.com/gradlex-org/java-module-testing#whitebox-test-suites). It uses Java's module patching mechanisms so that tests of a certain module are still allowed to access internals of that module at test time, but for all other Modules, the module restrictions are still enforced. Therefore, we need to allow some more cross-module visibility which this PR is adding. This makes relationships …

build: add exports/opens to run tests on Module Path (foundation)

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java

* Adding debug logging to cover all failures thrown from `pureChecks`, `preHandle`, `handle`, and `calculateFees`.
* To enable the debug level see https://limechain.notion.site/Debug-HAPI-tests-1d810baa8dcd807a91ebf806eecbd708
Fixes #3428

feat: add debug logs on key places

---

.github/workflows/docs/forked_prs.md
.github/workflows/docs/required_checks.md

Adds documentation to `.github/workflows/docs` about PR checks that can be run on forked PRs.
closes #18966

chore: Generate list of PR checks that can and cannot be run by forked PRs

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/utils/KeyMetadata.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyRole.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenBurn.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDelete.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenFeeScheduleUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenFreeze.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycGrant.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycRevoke.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenMint.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenPause.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnfreeze.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnpause.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdateNfts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java

- Refactored HapiSpecRegistry role key management by introducing a KeyRole enum.
-  Removed the proliferation of specialized saveXKey() and getXKey() methods by using role-based key storage with standardized naming. 
- Simplified KeyMetadata to support role-aware registration without changing existing public signatures.
Fixes #
https://github.com/hiero-ledger/hiero-consensus-node/issues/13640
**Checklist**

refactor: introduce KeyRole enum and refactor role key management in HapiSpecRegistry

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiEventStorage.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/gui/TestGuiSource.java

Since introduction of non-deterministic generation, GUI consensus testing tool was not working, as it was not generating nGens for local events and it was creating local copies of events without copying over nGen.
Fixes #18939 
**Checklist**

fix: Assign nGen for GUI generated events

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionCheckerTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextTransactionProcessor.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java

Cherry pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/18647

feat: Limit the callData field instead of ethereumData (cherry-pick)

---

hedera-node/test-clients/build.gradle.kts
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SharedNetworkLauncherSessionListener.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/AddressBookUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/RecordStreamValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/BalanceReconciliationValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/props/NodeConnectInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoGetInfoRegression.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/BalanceValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/StartStaking.java

In order to effectively support intuitive configuration of nonzero shard/realm in hapi test networks, an extension of the hapi test framework that doesn't rely on a test scenario's specific use case is required. Therefore, this PR is the beginning of work needed to scope a configurable shard/realm to a hapi test network (specifically, the `HederaNetwork` interface). 
Two underlying ideas govern the majority of this change set: first, that the `HederaNetwork`–if not set to the default values of (0,0)–is the primary source of truth for determining what a test network's shard/realm should be, as well as the target for any test clients instantiated as part of any related process; second, that the `hapi.spec.default.shard` and `hapi.spec.default.shard` system properties serve as the secondary …

test: Scope shard/realm first to target network, system properties

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/dispatch/DispatchValidator.java

* Separate the account check into more granular checks
Fixes #18448

fix: Improve exception handling when payer account is not meeting the specifications

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java

The `prepareFakeUpgrade` was left when the jumbo transaction was disabled, but we do not need it anymore. The fake upgrade operation sometimes fails (flaky) since it cannot find the `0.0.150` file, thus we need to remove it to fix the pipeline.

fix: Flaky Jumbo transactions tests

---

platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundMigrationTest.java

This PR disables the log validation as it fails currently
Fixes #19033

chore: Fix Otter test

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSV2SecurityModelSuite.java

The `ContractMintHTSV2SecurityModelSuite` has become flaky.  One explanation is that because each `ContractCall` takes 4M gas and the gas needed for `ContractCreate` has recently been increased, we are running into the gas throttle.  This pr is an attempt to reduce the flakiness of this test by reducing the gas sent with each `ContractCall`

test: reduce gas sent in ContractMintHTSV2SecurityModelSuite

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/remote/RemoteNetworkFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/remote/RemoteNodeSpec.java
hedera-node/test-clients/src/main/java/module-info.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/SetupStakeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/StakeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/ConfigManager.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/domain/NetConfig.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/domain/NodeConfig.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/output/CommonMessages.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/StakeSetupSuite.java

This PR reworks some of the yahcli config code to integrate a nonzero shard and realm. Since the config is already passed into each of yahcli's `Suite` classes, it then only becomes a matter of using it to construct a target network and invoking the spec with said network. The new code makes use of each configured node's 'info' string–already quite similar to the info string produced by `NodeConnectInfo`–as inputs to new `NodeConnectInfo` objects, which are then used to construct a `RemoteNetwork`. Done this way, yahcli need not worry about juggling specific local vs. remote scenarios (except for a small number of isolated locations in the code, which should be appropriately encapsulated). 
The hapi framework essentially does the rest. Each `HapiSpec` now has a `shard()` and `realm()` …

feat: Implement staking activation with nonzero shard/realm

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java

Adds additional unit tests for CryptoUpdateHandler, specifically the cases where account is null, account.memo is null, and when unlimitedAutoAssociations are disabled and the max auto associations are different than before.
Partially fixes #12987
**Checklist**

chore: 12987 more code coverage for CryptoUpdateHandler

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java

Adds a check to make sure that CryptoTransferHandler. calculateFees actually handles exceptions thrown by the CustomFeeAssessor
Fixes partially fixes #12987
**Checklist**

chore: 12987 more code coverage for CryptoTransferHandler

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeCreateHandler.java
hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/handlers/NodeUpdateHandler.java
hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/handlers/NodeCreateHandlerTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/node/HapiNodeCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java

This PR adds a feature flag–`nodes.webProxyEndpointsEnabled`–to toggle support for the gRPC web proxy endpoint added in HIP 1046's implementation. The flag's default mainnet value should be `false`; any submissions for NodeCreate or NodeUpdate transactions that populate this field, without enabling the flag, should receive a new response code–`GRPC_WEB_PROXY_NOT_SUPPORTED`. Otherwise these fields should behave as expected and tested for HIP 1046.
Closes #19046

feat: Implement feature flag for gRPC web proxy endpoint

---

platform-sdk/base-utility/src/main/java/org/hiero/base/constructable/ConstructableRegistry.java
platform-sdk/base-utility/src/main/java/org/hiero/base/constructable/NoArgsConstructor.java
platform-sdk/base-utility/src/main/java/org/hiero/base/constructable/internal/DefaultConstructableRegistry.java

In `GenericConstructorRegistry.getMethod(Class<?> constructorType)` [we drop duplicated constructors](https://github.com/hiero-ledger/hiero-consensus-node/blob/b4509ff0045de9f86c770bcda9ff1d714c98ff18/platform-sdk/base-utility/src/main/java/org/hiero/base/constructable/internal/GenericConstructorRegistry.java#L204). However, [we ignore the return type in the comparison](https://github.com/hiero-ledger/hiero-consensus-node/blob/b4509ff0045de9f86c770bcda9ff1d714c98ff18/platform-sdk/base-utility/src/main/java/org/hiero/base/constructable/internal/MethodWrapper.java#L20-L26). I think the return type is also the reasons why there are duplicates in the first place. It is somehow related to how Java is compiling generic types. In the case of `NoArgsConstructor` the method …

fix: NoArgsConstructor has duplicated get() method

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/DiskStartupNetworks.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/info/DiskStartupNetworksTest.java

Fixes #19075 
Change default `decline_reward` to true for nodes created during genesis

fix: Change default `decline_reward` to true for nodes created during genesis

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
platform-sdk/consensus-model/src/main/java/org/hiero/consensus/model/node/NodeId.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleInstrumentedNode.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNetwork.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNodeConfiguration.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/app/TurtleAppState.java
platform-sdk/consensus-utility/src/main/java/org/hiero/consensus/roster/RosterUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/StartupStateUtils.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/turtle/gossip/SimulatedNetwork.java

This PR replaces the address book with the roster in the Otter framework. Also, moved `loadInitialState()` from `ServicesMain` to `StartupStateUtils` to make it generally available.
Fixes #18934

chore: Replace usage of address book with roster

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BootstrapConfig.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/V0490FileSchema.java

Follow up to #18922.
There are more cases in `V0490FileSchema` that I missed in #18922. I only discovered those by running HAPI tests on module path. This is a more consistent and complete solution.

chore: unify resource-from-module/class-path-loading in V0490FileSchema

---

hedera-node/test-clients/build.gradle.kts
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/ProcessUtils.java
hiero-dependency-versions/build.gradle.kts
platform-sdk/consensus-event-creator-impl/build.gradle.kts
platform-sdk/swirlds-common/src/main/java/module-info.java
settings.gradle.kts

- Activates running unit tests on module path (by updating plugins to `0.4.0`)
- Activates running hapi tests on module path by doing the corresponding updates in the `test-client` project
Follow up to #18922
Fixes #5275

build: run tests on module path

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/reconnect/BenchmarkMerkleInternal.java

This PR fixes `classId` conflict between `BenchmarkMerkleInternal` and `DummyMerkleInternal`
Fixes #19107
**Checklist**

fix: 19107 Corrected classId of `BenchmarkMerkleInternal` to prevent `classId` conflict.

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleTestEnvironment.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/app/TurtleApp.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/RuntimeObjectRegistry.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/RuntimeObjectRegistryTest.java

`RuntimeObjectRegistry` uses real-time to determine an object's age. This leads to unexpected behavior in tests when we use `FakeTime`. This PR adds the possibility of setting a time provider in `RuntimeObjectRegistry`.
Fixes #19111

chore: Allow the provision of a FakeTime in RuntimeObjectRegistry

---

platform-sdk/junit-extensions/README.md
platform-sdk/swirlds-platform-core/build.gradle.kts

After enabling JMS at runtime, we need to update the module information for client modules of junit-extensions to open their content to it, allowing access and execution of code on the target module.
Fixes #19162

fix(19162): Open clause for JMS runtime for junit-extensions

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java

This PR fixes compilation errors and adds and fixes unit tests for BlockNodeConnection and BlockNodeConnectionManager
#18947 
This is a draft PR that needs to be merged to feature branch: [feature_bn_comm_eos_backoff_squashed](https://github.com/hiero-ledger/hiero-consensus-node/tree/feature_bn_comm_eos_backoff_squashed)
This is the first such PR that focuses on fixing the compilation errors of the tests and adding unit tests mostly for the BlockNodeConnection. There will be additional PRs in order to fully cover the CN to BN functionality.

test: Rewrite feature branch unit tests for Block Node communication #18947

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleTestEnvironment.java

The `SATE_HASH` marker was still in the console output

fix: Use `CompositeFilter` for console logging

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockStreamStateManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockStreamStateManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java

Added `blockStream.writerMode` feature flag checks in `BlockStreamStateManager` and `HandleWorkflow`.
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19136
**Checklist**

fix: ensure all Block Node Communication is behind feature flag

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/network/HapiUncheckedSubmit.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/util/HapiAtomicBatch.java

Refactor `HapiSpecOperation` :
* Remove `protected Optional<String> nodeNum = Optional.empty();`
* Update `protected Optional<String> node = Optional.empty();` so any operation can set node as string. This way we can pass ID literals, account number literal or spec registry key.
Fixes #
**Checklist**

chore: Node account id shard realm

---

.github/workflows/node-zxc-compile-application-code.yaml

Current CI failures result in persistence of the network logs, but do not include the logged output of the test client itself. This PR adds that file for each of the hapi test tasks. We also add the `*.log` filepath to the hapi test tasks that didn't have it.

build: Upload hapi test client logs with network logs in CI

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19197
Removes extra charging of the synthetic `CryptoTransfer` to assess custom fee when a `ConsensusSubmitMessage` for a topic with custom fees is submitted. 
Also, fixes the `transactionFee` in the record to be same as the credits to fee collection accounts.

fix: Fix the `transactionFee` in the record for `ConsensusSubmitMessage` with custom fees

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip991/TopicCustomFeeSubmitMessageTest.java

Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/19195
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19197
Removes extra charging of the synthetic `CryptoTransfer` to assess custom fee when a `ConsensusSubmitMessage` for a topic with custom fees is submitted. 
Also, fixes the `transactionFee` in the record to be same as the credits to fee collection accounts.

fix: Fix the transactionFee in the record for ConsensusSubmitMessage with custom fees

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java

Since we call `transactionChecker.parseAndCheck()` in PreHandle with `maxTxnSize = HederaConfig.nodeTransactionMaxBytes`, there’s a discrepancy in the `maxTxnSize` value when `checkJumboTransactionBody()` is called in preHandle(). Therefore, we should move this check exclusively to the ingest phase.
Fixes #
**Checklist**

fix: Move jumbo transaction size check only at ingest

---

hedera-node/configuration/dev/api-permission.properties
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AtomicBatchConfig.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/EmbeddedNode.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/MiscellaneousFeesSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/ConcurrentIntegrationTests.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip423Tests.java

Fixes #19146 
Cherry-pick 
https://github.com/hiero-ledger/hiero-consensus-node/pull/19115
https://github.com/hiero-ledger/hiero-consensus-node/pull/19130
- Disables AtomicBatch feature by default and enables only in dev environment.

chore: (cherry-pick) Disable `AtomicBatch` feature

---

platform-sdk/consensus-utility/src/main/java/org/hiero/consensus/config/EventConfig.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/preconsensus/DefaultInlinePcesWriterTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/ShadowGraphTest.java

Enables birth rounds as the definition of the ancient threshold.
Fixes #10023

feat: Enable Birth Rounds as Ancient Threshold

---

hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/CreateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/UpdateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/domain/NetConfig.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/CreateNodeSuite.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/UpdateNodeSuite.java
hedera-node/test-clients/yahcli/README.md
hedera-node/test-clients/yahcli/run/build.sh
hedera-node/test-clients/yahcli/run/publish.sh

This version of yahcli adds support for defining node rewards behavior in the dynamic address book. For yahcli node create commands, the new `--declineRewards` flag indicates such to the consensus node, while a value of `--declineRewards false` indicates the intent to accept rewards. The node update command, keeping with the format of the staking command, now has two additional parameters: `--startDecliningRewards` and `stopDecliningRewards`, where of course 'stop declining rewards' means 'start accepting rewards.' 
Closes #19247

feat: Support accepting/declining rewards in yahcli DAB transactions

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/node-zxc-compile-application-code.yaml
settings.gradle.kts

With this PR we use `com.hedera.hashgraph` as **Maven Group** for all modules published from this repository. This allow us to keep Modules that already exist in that group as they are. All other Modules – `com.swirlds` and new `org.hiero` – are moved from the `com.swirlds` group to the `com.hedera.hashgraph` group with this PR.
Publishing in then simplified and can be performed in one step (see pipeline adjustment in this PR).
**This will then allow us, as a next step, to switch to the new Maven Central Portal publishing mechanism in one go.**
This will also make it simpler to eventually move everything to the new `org.hiero` group.

chore: publish all HCN Modules in the same Maven group

---

.github/dependabot.yml

With this change, Dependabot will observe our own `org.hiero.gradle.build` (hiero-gradle-conventions) plugin and suggest updates when available.
For reference, see the similar configuration here:
https://github.com/hiero-ledger/hiero-sdk-java/blob/main/.github/dependabot.yml#L4-L12

ci: let Dependabot find updates for org.hiero.gradle.build

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbCompactionCoordinator.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/CASableLongIndex.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/DataFileCompactor.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/CompactionInterruptTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/MerkleDbDataSourceSnapshotMergeTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/files/DataFileCollectionCompactionTest.java
platform-sdk/swirlds-merkledb/src/timingSensitive/java/com/swirlds/merkledb/files/DataFileCollectionTest.java

Fix summary:
* `DataFileCompactor.snapshotCompactionLock` is changed from `Semaphore` to `ReentrantLock`
* `MerkleDbCompactionCoordinator` synchronization is reworked, now it has most methods synchronized
* Busy loop in `MerkleDbCompactionCoordinator.stopAndDisableBackgroundCompaction()` is reworked with `wait()`
* `CASableLongIndex.forEach()` is changed to return boolean (if all entries are processed) and it now accepts a boolean supplier to check whether iteration over all list entries should be stopped (gracefully)
* To interrupt data compaction tasks, `Thread.interrupt()` is no longer used. Instead, a new method is introduced to `DataFileCompactor` to interrupt the task explicitly. This method sets a flag, which is checked periodically in `compactFiles()`, so this method can return …

fix: 19319: Improve MerkleDb reconnect / compaction synchronization

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemTransactionsTest.java

Remove the migration code for setting declineReward=true for all nodes on upgrade
Cherry-pick https://github.com/hiero-ledger/hiero-consensus-node/pull/19338

chore: Remove the migration code for setting declineReward=true for all nodes on upgrade

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/utils/ConversionUtilsTest.java

when converting a possible long zero token address into a token Id, remove the check for negative values as this used to not throw an exception when the address is a non-long zero EVM address
**Checklist**

feat: remove shard/realm negative check in asTokenId

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/SigMapGenerator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/TrieSigMapGenerator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/node/HapiNodeUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/TokenServiceFeesSuite.java

Fixes the flaky tests related to `INSUFFICIENT_TX_FEE`. 
Currently when any of the keys signing are having same short prefixes, we will be verifying extra signatures and are charging extra fee. This can easily happen with the Update tests and Schedule sign tests. 
To stabilize the tests, full prefix signatures are used in those tests.

chore: Fix flaky tests

---

platform-sdk/swirlds-platform-core/src/jmh/java/com/swirlds/platform/core/jmh/PcesWriterBenchmark.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileChannelWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileWriterStats.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesOutputStreamFileWriter.java

Report pcs writer metrics in nanoseconds to have a finer grain measurement of the impact of the pces operations
Fixes #19408

chore(19408): report pces metrics in nanoseconds

---

hedera-node/configuration/mainnet/application.properties
hedera-node/configuration/previewnet/application.properties
hedera-node/configuration/testnet/application.properties

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19456
- Disable node rewards by adding an override to `application.properties` , `nodes.nodeRewardsEnabled=false`
- When needed this will be enabled with dynamic property update

chore: Add overrides for `nodes.nodeRewardsEnabled=false`

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxcron-release-branching.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

- Adds error reporting to `node-flow-build-application`
- Updates steps throughout yaml files to change "Hedera Services" to "Hiero Consensus Node".
closes #19496

chore: Add error reporting to node-flow-build-application cleanup Hedera Services text in workflows

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StateFileManagerTests.java

Fix unit test `StateFileManagerTests.sequenceOfStatesTest`, so it passes locally.
Fixes #19528

test: fix StateFileManagerTests.sequenceOfStatesTest

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/zxcron-extended-test-suite.yaml

Adds failure reporting `node-flow-build-application.yaml` and `zxcron-extended-test-suite.yaml` to force them to get through the slack reporting steps.
closes #19550

fix: Add continue-on-error logic to failure reporting in workflows

---

platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundFreezeTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundMigrationAndFreezeTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundMigrationTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/SandboxTest.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Network.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Node.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNetwork.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java

This PR splits the method `Network.prepareUpgrade()` into `freeze()` and `shutdown()` and updates the Turtle implementation accordingly.
Fixes #19468

test: Split the method Network.prepareUpgrade() in freeze() and shutdown()

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AtomicCryptoServiceFeesSuite.java

* Add test cases for validating the base fees for the crypto service wrapped inside an atomic batch
Fixes #19379

test: Validate base fees inside of atomic batch for crypto service

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AtomicSmartContractServiceFeesTest.java

* Add test cases for validating the base fees for the smart contract service wrapped inside an atomic batch
Fixes #19382

test: Validate base fees inside of atomic batch for smart contract service

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/hbarallowance/HbarAllowanceCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/hbarallowance/HbarAllowanceTranslator.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/has/hbarAllowance/HbarAllowanceCallTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip906/HbarAllowanceApprovalTest.java
hedera-node/test-clients/src/main/resources/spec-default.properties

❗ This PR is created and maintained by @gkozyryatskyy. It was initially approved by the hiero-consensus-node-smart-contracts-codeowners here #19388
Fix `HbarAllowanceCall` reversion gas
Fixes [19169](https://github.com/hiero-ledger/hiero-consensus-node/issues/19169) [19013](https://github.com/hiero-ledger/hiero-consensus-node/issues/19013)
- actual fix is in `HbarAllowanceCall`
- `ContractFnResultAsserts.approxGasUsed` uses suppliers because values should be returned at the step execution but not at the test start
- `HbarAllowanceCall` success result `isViewCall` changed to `true`. Because of this new child record is produced on success result (there was no child record before).
- `CreatePrecompileSuite` changes, fixes …

fix: HbarAllowanceCall reversion gas (#19388)

---

platform-sdk/consensus-event-creator-impl/build.gradle.kts
platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/Tipset.java
platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetTracker.java
platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetWeightCalculator.java
platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/tipset/TipsetTests.java
platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/tipset/TipsetTrackerTests.java
platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/tipset/TipsetWeightCalculatorTests.java

Update the Tipset.merge() method to support an empty list 
Fixes #18832 
**Checklist**

refactor: Tipset.merge() method to support an empty list 

---

platform-sdk/consensus-gossip/src/main/java/org/hiero/consensus/gossip/FallenBehindManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowgraphSynchronizer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncManagerImpl.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/FallenBehindManagerTest.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/sync/TestingSyncManager.java

When some node has reported us as falling behind, this marker was never cleared, until we have finished full reconnect ourselves. In rare situations, if we managed to get back on our own, then other node was stuck and we again have fallen behind, we might have been chosing broken node for reconnect target, just because it reported issues to us once.
This fix clears the markers not only after each reconnect, but each time we are catching up with the node (or it has falled behind compared to us), so they won't get used in far future when real reconnect happens.
Fixes #19271 
**Checklist**

fix: don't use nodes which haven't reported us as fallen behind for reconnect

---

.github/workflows/zxf-update-gs-state-variable.yaml

Write a new workflow to update the GS_STATE variable based on input.
**Testing**:
Successful testing with `TEST_VARIABLE` [here](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/15536803867/job/43737719906).
Reworked from `TEST_VARIABLE` to `GS_STATE`.
Fixes #19637

ci: write workflow to update GS_STATE variable

---

.github/workflows/node-flow-deploy-release-artifact.yaml

This pull request includes a small change to the `.github/workflows/node-flow-deploy-release-artifact.yaml` file. The change adds a `type: boolean` property to the `dry-run-enabled` input to specify its data type.
**Related Issue(s)**
Fixes #19585

fix: Issue with dry-run-enabled in node-flow-deploy-release-artifact

---

platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionCompactionTest.java

`DataFileCollectionCompactionTest` was failing non-deterministically in a couple of scenarios: 
```
com.swirlds.merkledb.files.DataFileCollectionCompactionTest > Snapshot + update in parallel with compaction ✘ [1] 0
org.opentest4j.AssertionFailedError: Unexpected files after compaction: [11] ==> expected: <true> but was: <false>
at app/com.swirlds.merkledb@0.64.0-SNAPSHOT/com.swirlds.merkledb.files.DataFileCollectionCompactionTest.lambda$testMergeUpdateSnapshotRestore$4(DataFileCollectionCompactionTest.java:513)
com.swirlds.merkledb.files.DataFileCollectionCompactionTest > Snapshot + update in parallel with compaction ✘ [2] 1
org.opentest4j.AssertionFailedError: Unexpected files after compaction: [11] ==> expected: <true> but was: <false>
at …
```

fix: 19623 Fixed `DataFileCollectionCompactionTest` intermittent failure.

---

.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/zxc-publish-production-image.yaml

This pull request introduces changes to workflow files to enhance flexibility and consistency in handling Git references (`ref`) for build and release processes. The updates ensure that Git references are passed explicitly as inputs and used uniformly across jobs.
* [`.github/workflows/node-zxc-build-release-artifact.yaml`](diffhunk://#diff-c4507eafecb6e04bf4d768bd725d1f4ac3707e6c7524678afeadbd40f421bd0bR539): Added `ref` input to both GCP and JFrog production image publishing jobs, ensuring the commit ID from validation outputs is used consistently. [[1]](diffhunk://#diff-c4507eafecb6e04bf4d768bd725d1f4ac3707e6c7524678afeadbd40f421bd0bR539) [[2]](diffhunk://#diff-c4507eafecb6e04bf4d768bd725d1f4ac3707e6c7524678afeadbd40f421bd0bR558)
* …

fix: Pass ref to publish-production-image to fix cache keys mismatch

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java

Fixes #19646 
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19668
Similar to https://github.com/hiero-ledger/hiero-consensus-node/pull/19356.
Fixes a flaky test by using full prefix signatures. When there is more than one signature in the transaction and it is suing short signature prefixes, if signature prefixes match, we verify more signatures and charge more transaction fee.

chore: Fixes flaky test `TopicCreateSuite.signingRequirementsEnforced`

---

platform-sdk/swirlds-common/src/timingSensitive/java/com/swirlds/common/notification/IntegerNotificationTests.java

Increase the timeout to reduce the probability of flaky results
Fixes #19684

chore(19684): Increase timeout on IntegerNotificationTests

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/CommonPcesWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesFileWriterType.java

Performance of FILE_CHANNEL is 150x slower on MacOS, but marginally better on Linux; it is so bad on Mac that basic tests cannot pass in some cases, so we need to make it system dependent, at the same time allowing override if needed
Extra setting just for mac is added, so values can be overwritten depending on the platform, without affecting each other.
Fixes #19761 
**Checklist**

feat: Separate configuration for Mac PcesWriter, due to difference in performance between platforms

---

platform-sdk/swirlds-merkle/build.gradle.kts
platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java
platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java

This PR makes sure that instances `BreakableDataSource` instances get released. If not done properly, it may cause OOM errors. 
Fixes #19748 
**Checklist**

fix: 19748 Fixed `BreakableDataSource` lifecycle management for reconnect tests

---

.github/workflows/zxc-tck-regression.yaml

This pull request updates the version of the `@hashgraph/solo` pack  the `.github/workflows/zxc-tck-regression.yaml` file to ensure compatibility with the latest features and fixes.
Dependency update:
* Updated the `@hashgraph/solo` package from version `0.36.0` to `0.37.1` in the `Install Solo` step of the workflow file `.github/workflows/zxc-tck-regression.yaml`.
Fixes #19745
**Testing**:
[eXtended Test Suite - Dry Run](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/15735890648)

chore: Update solo to use v0.37.1

---

hedera-node/test-clients/build.gradle.kts

1. Fixed log outputs for Hapi tests to ensure logs are displayed in the correct console output
(see [#19786](https://github.com/hiero-ledger/hiero-consensus-node/issues/19786) for more details).
2. Set `modularity.inferModulePath` to `false` for:
•	`testEmbedded`
•	`testRepeatable`
•	`testSubprocess`
https://github.com/hiero-ledger/hiero-consensus-node/issues/19786
Fixes #
**Checklist**

test: Fix HapiTest logs

---

hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/BalanceCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/InfoCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/RekeyCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/StakeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/accounts/UpdateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/files/SysFileDownloadCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/files/SysFileUploadCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/CreateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/DeleteCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/nodes/UpdateCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/schedules/SignCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/FreezeUpgradeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/PrepareUpgradeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/commands/system/TelemetryUpgradeCommand.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/config/ConfigManager.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/suites/Utils.java
hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java
hedera-node/test-clients/yahcli/run/build.sh
hedera-node/test-clients/yahcli/run/publish.sh

Yahcli configuration now supports configuring nonzero shard/realm via its config file, but it's still possible to cause unexpected behavior by specifying a fully-qualified entity ID as an input param (for many different commands). This PR accounts for possible ID literals by stripping said literals of their shard/realm, warning the end user with a console message, and falling back to the shard/realm in the configuration.
Also fixes:
* a bug that outputs the wrong shard/realm for a rekey operation
* a bug that outputs `NA` as the system file type for uploading/downloading system files 
Closes #19720

fix: Ignore ID literals for individual input parameters

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/NodesConfig.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeUpdateTest.java

Now that the feature is better tested, we want the gRPC web proxy feature flag to be enabled by default. This PR enables it as the default in `NodesConfig`.

feat: Enable web proxy endpoints by default

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java

Update `fileCreate() `error handling to return proper error when giving invalid expiration time.
The current impementation of returning `AUTORENEW_DURATION_NOT_IN_RANGE` was created for mono parity testing.
Fixes #
https://github.com/hiero-ledger/hiero-consensus-node/issues/19791
**Checklist**

fix: Update expiration time handling in file create

---

platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/Configuration.java
platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigDataFactory.java
platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationImpl.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/ConfigApiSetTests.java

To ensure deterministic behavior we're making the Config API return sets with a stable iteration order. See the linked issue for more details.
Fixes #19724
All tests should pass.
**Checklist**

feat: Config API to make sets deterministic

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/FrameRunner.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/FrameRunnerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java

Addresses https://github.com/hiero-ledger/hiero-consensus-node/issues/19732 (a subtask of https://github.com/hiero-ledger/hiero-consensus-node/issues/19176).
Summary of changes:
- Post [EIP-3529](https://eips.ethereum.org/EIPS/eip-3529) selfdestruct refund has been removed - I do so in this PR (its value was always `0` anyway, so no functional difference in that regard)
- [EIP-3529](https://eips.ethereum.org/EIPS/eip-3529) specifies a limit on the total gas refund amount (1/5th of gas used). We used to apply it wrongly - only to the selfdestruct component, while SSTORE refund was unlimited. I fix it in this PR.
- I've updated the tests. The "temporary hold" scenario falls under this path: " .... If original value is 0, add SSTORE_SET_GAS - SLOAD_GAS to refund counter." in …

feat: Apply EIP-3529 refund limits

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/AsyncNodeActions.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Node.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/solo/SoloNode.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java

chore: Remove gracefulShutdown from Otter interface

---

.github/workflows/zxc-tck-regression.yaml

This pull request adds a new job to the `.github/workflows/zxc-tck-regression.yaml` file to report the status of TCK regression tests to a Slack channel. The job builds a Slack payload message with detailed information about the test results and workflow metadata, and sends it using the Slack GitHub Action.
* **New job `report-tck-regression-status`**: Introduced a job to send a Slack notification summarizing the results of the TCK regression tests. The notification includes the test result, source commit, workflow run ID, and workflow run URL.
* **Slack payload construction**: Added a step to dynamically build a Slack payload message with color coding based on test success or failure, and structured blocks for clear presentation.
* **Slack API integration**: Integrated …

chore: Add report to TCK Regression Panel to show status in slack

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java

- Add a small `@HapiTest` to verify the in-batch cost of minting with a newly updated keylist scales as expected.

chore: Add in-batch signature fees scaling `@HapiTest`

---

.github/workflows/zxc-tck-regression.yaml

This pull request includes a single change to the `.github/workflows/zxc-tck-regression.yaml` file. The change ensures that the job always runs by adding an `if: ${{ always() }}` condition to the `jobs:` configuration.
Fixes #19844

chore: Add always condition to reporting job

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/customfees/CustomFractionalFeeAssessorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/BalanceSnapshot.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

- Instead of computing the amount to reclaim for a non-`netOfTransfer` fractional fee from the size of each debit, and then reclaiming from only non-exempt credits (source of exploit); we now,
1. Compute the fraction of the non-exempt debits that each debit makes up; then,
2. Reclaim that fraction of the non-exempt credits.
- Instead of repeatedly reclaiming from the non-exempt credits in the original transaction and applying the deltas, always reclaims from the _remaining credits_ net of all previously assessed fractional fees.
- Clamps the amount to reclaim to the amount of remaining credits.

chore: Assess fractional fees relative to non-exempt credits and debits

---

hedera-node/configuration/mainnet/application-override.properties
hedera-node/configuration/previewnet/application-override.properties
hedera-node/configuration/testnet/application-override.properties
hedera-node/configuration/testnet/application.properties

Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/19887
chore: Adds `application-override.properties` that are replica of file 121

chore: Adds `application-override.properties`

---

.github/workflows/node-zxc-build-release-artifact.yaml

Fix a typo in the secret name in `main` branch.
Fixes #19892

ci: fix typo in secret

---

.github/workflows/zxcron-promote-build-candidate.yaml

This pull request includes a minor change to the `.github/workflows/zxcron-promote-build-candidate.yaml` file. The `dry-run-enabled` parameter was replaced with `disable-notifications`.

chore: Fix trigger to zxf-single-day-performance-test-controller

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PttTransactionPool.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/stream/DefaultConsensusEventStream.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/DefaultTransactionHandler.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/stream/ConsensusEventStreamTest.java

A new instance of a failure for JRS test FCM-VM-RestartEventStream-1k-10m occurred.
The symptom is that the node entered CHECKING instead of the expected FREEZING
We are adding debug information to the  default transaction handler to be able to have more details
Related #19352

chore(19352): Add debug Information to DefaultTransactionHandler

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/EthereumTransactionTranslator.java

- Closes #19946 
- Once the issue with failed `EthereumTransaction` nonce updates not "sticking" inside `AtomicBatch` is resolved, this special case can be removed.

chore: Add temporary special case for nonce translation

---

.github/workflows/zxc-single-day-performance-test.yaml

Remove the `pbj` repo checkout from the Single Day Performance Test workflow.
Fixes #19924

ci: remove pbj repo checkout from SDPT

---

.github/workflows/zxc-execute-performance-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxf-single-day-performance-test-controller.yaml

Remove the Network Load Generator repo checkout step from CITR workflow.
Fixes #19925

ci: remove NLG repo checkout from CITR workflow

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleMetrics.java

Make it so that both the GAS throttle and OPS_DURATION throttle are excluded from having an inert metric.
Not quite sure what's the purpose of those inert metrics (perhaps to detect misconfiguration?) - at some point we might want to revisit if they're still needed.
https://github.com/hiero-ledger/hiero-consensus-node/issues/19264
**Checklist**

fix: Exclude OPS_DURATION throttle from inert metrics

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java

The `keyRotationDoesNotChangeEvmAddress()` test uses multiple stream listeners to verify the creation and key rotation of various EVM-addressable accounts—one listener for the key rotations, and one listener for the account creations. Instructing both listeners to verify the same creation purportedly introduces a condition by which each listener does not always receive the complete change set from the records, thereby causing the test to fail intermittently. This PR remedies the issue by requiring both listeners to verify a mutually-exclusive set of transaction IDs. 
Closes #19632

test: Restrict evm rotation acct names to strict subsets

---

.github/workflows/zxc-tck-regression.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxf-dry-run-extended-test-suite.yaml

This pull request updates Slack webhook configurations across multiple GitHub Actions workflows to improve clarity and functionality. The changes include renaming an existing webhook variable for consistency, adding a new webhook for detailed reporting, and incorporating a new Slack notification step in one of the workflows.
* [`.github/workflows/zxc-tck-regression.yaml`](diffhunk://#diff-276b3c78510bfe1ba0edc6d1c72256cf2d3c424c7b3733a999efb0f5c7b886cdL18-R21): Renamed `slack-report-webhook` to `slack-tck-report-webhook` and added a new `slack-detailed-report-webhook` input for detailed reporting.
* [`.github/workflows/zxcron-extended-test-suite.yaml`](diffhunk://#diff-0200fc6fe4d2e0194aa278446c5ef3a562d270505fee1d169229d3d977705687L197-R198): Updated secrets to reflect the renamed …

chore: Report TCK regression test to CITR Detailed Test Reports Channel

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/Capability.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/OtterTest.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerTestEnvironment.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/junit/OtterTestExtension.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleTestEnvironment.java

This PR adds a basic Capabilities API to the Otter framework. Required capabilities can be defined like so:
```
@OtterTest(requires = Capability.RECONNECT)
void testFoo(@NonNull final TestEnvironment env) {...}
```
Fixes #19803

chore: Basic Capabilities API for Otter

---

settings.gradle.kts

Includes: https://github.com/hiero-ledger/hiero-gradle-conventions/pull/239
To fix:
```
> Failed to apply plugin 'org.hiero.gradle.feature.publish-artifactregistry'.
> Repository with name 'sonatype' not found.
```

build: update org.hiero.gradle.build to 0.4.8

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesConfig.java

Description:
In https://github.com/hiero-ledger/hiero-consensus-node/issues/18458, we changed how we write events into the pces files (we now sync on every event and write using the strongest available guarantee). It produced an increased i/o activity on the disks.
This configuration rolls back the change.
Reverts https://github.com/hiero-ledger/hiero-consensus-node/pull/19067

fix(18458): Pces file writer rollback

---

.github/CODEOWNERS
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/AtomicSmartContractServiceFeesTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/SmartContractServiceFeesTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hip906/HbarAllowanceApprovalTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/ContractRecordsSanityCheckSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/staking/StakingSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/SteadyStateThrottlingTest.java

Occasionally services code owners are requested to review PR for which are non applicable to their ownership which slows down development time for SC contributors.
Fixes [#17322](https://github.com/hiero-ledger/hiero-consensus-node/issues/17322)
- `##### HAPI protobuf #####` remove because of duplication
- `# Protobuf` fixed (changed to real folder) and moved to `#####   HAPI  ######` block
- doc ownership was already changed by https://github.com/hiero-ledger/hiero-consensus-node/commit/02ba8dfd2a5b208598ad5605f1fe417c40a01eda
- SC tests movement is not a great change as I think, because any change in "test utils" or "test core" will still cause execution team to review. But I grouped what is possible
**Checklist**

chore: Update CODEOWNERS for SC contributions

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java

Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20146

fix: 20146: Bucket.keyEquals() may throw an underflow exception

---

gradle/aggregation/build.gradle.kts

Restores the publishing of `hedera-protobuf-java-api` which has been accidentally removed when moving to the new Maven Central mechanism. Hence, follow up to #19567.
#19567
**Note**
I testes that this fixes the problem by:
- Locally removing the `SNAPSHOT` from the version in `version.txt`
- Running `./gradlew nmcpZipAggregation` and inspecting `gradle/aggregation/build/nmcp/zip/aggregation.zip` which contains everything that would get published.

build: add 'hedera-protobuf-java-api' to published artifacts

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/steps/StakePeriodChanges.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/NodeStakeUpdatesTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/StakePeriodChangesTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/steps/SystemTransactionsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/BlockStreamAccess.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1064Tests.java

- Closes #20083 
- Now the relevant calls to `blockStreamManager.setLastHandleTime()` are both done through the `StakePeriodChanges.advanceTimeTo()` method, which triggers side effects of crossing stake period boundary if appropriate.
* There is one special case at genesis, when we do _not_ want to consider any side effects since the involved entities will not exist yet.

chore: Isolate responsibility for stake period boundary side effects

---

platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/MerkleTestUtils.java
platform-sdk/swirlds-merkledb/src/test/resources/log4j2-test.xml
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
platform-sdk/swirlds-virtualmap/src/test/resources/log4j2-test.xml

This PR suppresses expected exceptions in unit tests, so they don't overload the test output.
Fixes #19942
- Besides Virtual Map Reconnects, some expected exceptions in compaction tests were suppressed;
- Need to keep in mind that exceptions are suppressed in case of debugging something;

test: suppress expected exceptions in unit tests

---

.github/workflows/zxcron-extended-test-suite.yaml

This pull request includes updates to the `.github/workflows/zxcron-extended-test-suite.yaml` file to fix a typo in the workflow outputs and enhance the GitHub step summary with additional information.
* Corrected a typo in the `xts-info` output reference, changing `steps.check-tags-exist.output.xts-info` to `steps.check-tags-exist.outputs.xts-info` to align with the correct syntax for accessing outputs.
* Added a new section to the GitHub step summary to include "XTS Information," which displays the `xts-info` value in the format `${XTS_COMMIT_BRANCH} - ${XTS_SHORT_COMMIT}` for better visibility of extended test suite details.
Fixes #20284

fix: Fix typo in xts-info output definition

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/batch/AtomicRecordsSuite.java

* Wrapping the ethCalls into a single atomicBatch so the timestamp is the same
Fixes #20255

test: AtomicRecordsSuite.blck003ReturnsTimestampOfTheBlock flaky test

---

platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/BirthRoundFreezeTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/HappyPathTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/SandboxTest.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodeConsensusResultsAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodeConsensusResultsContinuousAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodePlatformStatusResultsContinuousAssert.java

This PR removes `MultipleNodeConsensusResultsAssert.haveMaxDifferenceInLastRoundNum()` and it includes some minor cleanups in multi node continuous assert classes.
Fixes #20342

chore: Remove haveMaxDifferenceInLastRoundNum(), some minor cleanups

---

.github/workflows/node-flow-deploy-release-artifact.yaml

This pull request updates the conditions for triggering certain jobs in the `node-flow-deploy-release-artifact.yaml` workflow file. The changes ensure that the jobs only run when the workflow is triggered by a `workflow_dispatch` event and the `dry-run-enabled` input is set to `false`.
* **Trigger XTS CI Flow (`deploy-xts-ci-trigger`)**: Added a condition to check that the workflow is triggered by a `workflow_dispatch` event in addition to verifying that `dry-run-enabled` is `false`.
* **Trigger Deploy Integration Flow (`deploy-integration-ci-trigger`)**: Updated the condition to include a check for the `workflow_dispatch` event.
* **Deploy Integration CI Job**: Refined the conditional logic to include the `workflow_dispatch` event check while maintaining the existing conditions for …

fix: Fix erroneous failure report in deploy prod release tag push

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/NodeRewardManagerTest.java

This pull request modifies the `NodeRewardManager` class to fix a condition regarding the tracking of missed judges during staking periods. It also adds a new test to verify the updated behavior. Currently if the candidate roster is adopted somewhere in the staking period, the new node gets "credit" for being considered active as if it had produced judges for all the previous rounds in a staking period.
* Updated the `updateJudgesOnEndRound` method to ensure missed judge counts are updated correctly. If a node is already tracked, its count is incremented; otherwise, its missed judge count is initialized to the current total rounds in the staking period.  I.e. (`hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java`)
* Added …

fix: NodeRewardManager missingJudgeCounts map initialization

---

hedera-state-validator/src/main/java/com/hedera/statevalidation/validators/merkledb/ValidateLeafIndexHalfDiskHashMap.java
hedera-state-validator/src/main/java/module-info.java

Fix summary:
* `ValidateLeafIndexHalfDiskHashMap`: changed bucket index check, so only lower bucket index bits are taken into consideration
* `ValidateLeafIndexHalfDiskHashMap`: added a new check that bucket entry hash code should match bucket index
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20399

fix: 20399: HalfDiskHashMap resize support in the state validator

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java

- Fixes [this](https://scans.gradle.com/s/36emgaf7oyo4w) flake.
```
deletionValidatesWrongAdminKey()
[1]:test-clients:testSubprocesscom.hedera.services.bdd.suites.token.TokenDeleteSpecs
com.hedera.services.bdd.spec.exceptions.HapiTxnCheckStateException: Wrong status!
Expected INVALID_SIGNATURE, was INSUFFICIENT_TX_FEE
```

chore: Stabilize `TokenDeleteSpecs`

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/VirtualHasherTestBase.java

Fix summary:
* When virtual tree contains only two elements, root and one leaf, root hash doesn't use any hash for path 2. Previously, NULL_HASH was used
* Existing unit tests are updated
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20454

fix: 20454: Virtual hasher should not include any hash for path 2 if virtual tree has only one leaf

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBaseBench.java
platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/VirtualMapState.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapMigration.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualInternalNode.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualInternalNodeTest.java

This PR fixes an issue of not creating a copy of `VirtualMapMetadata` in `detach` method. 
Misc: Renamed `VirtualMapState` to `VirtualMapMetadata`
Fixes #20468 
**Checklist**

fix: 20468 VM snapshot should use a copy of virtual state metadata

---

hapi/hedera-protobuf-java-api/src/main/proto/block/block_stream_publish_service.proto
hedera-node/docs/design/app/blocks/BlockNodeConnection.md
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeCommunicationTestBase.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/simulator/SimulatedBlockNodeServer.java

This PR updates the `block_stream_publish_service.proto` file to `v0.15.0` of what's in the block node repository.
In the future, the consensus node will utilize the protobuf sources for the block stream publish service published by the block node repository.
Key changes in this PR include removing the `block_already_exists` field, introducing new response codes, updating tests to reflect these changes, and modifying related methods. Below is a breakdown of the most important changes:
- Removed the `block_already_exists` field from the `PublishStreamResponse` message definition, simplifying the acknowledgment structure.
- Introduced new response codes `INVALID_REQUEST` and `ERROR` while renumbering existing codes to maintain consistency.
- Updated the table in …

chore: Update block_stream_publish_service to v0.15.0 spec

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkValue.java
platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBench.java
platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/FCHashMapBench.java
platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBench.java

Fix summary:
* No changes to any module other than swirlds-benchmarks
* `BenchmarkValue` is now immutable
* To update benchmark value's value, a builder is introduced to `BenchmarkValue`. It creates a new instance of `BenchmarkValue` every time
* `CryptoBench` is updated to use the builder
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20515

fix: 20515: CryptoBench hashing is unstable

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeConsensusResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeLogResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeMarkerFileResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodePcesResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodePlatformStatusResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeReconnectResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodeConsensusResults.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodeLogResults.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodeMarkerFileResults.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodePcesResults.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodePlatformStatusResults.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/result/MultipleNodeReconnectResults.java

chore: Add methods to suppress multiple node results in Otter

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/HealthCheckCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/health/OSHealthCheckMain.java

Adds `health-check` command to pcli, which allows running:
- clock speed report
- random entropy speed report
- file access speed report
Fixes #5363 
Please note it is reporting the output in the format that was previously used by the random utility run with the main method. I'm not sure what a real use case for that command is; if the outputs are supposed to be parsed in an automated way, maybe we can put the numbers in a more obvious place.
I have also added the possibility to specify limits under which the tool will fail (return non-zero). If used as an automated check, it should allow for using it without scraping the output.
**Checklist**

feat: Added health-check command for pcli

---

hapi/hedera-protobuf-java-api/src/main/proto/services/response_code.proto
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/DeduplicationCache.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/DeduplicationCacheTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/SubmissionManagerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/EmbeddedReason.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/AbstractEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/ConcurrentEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/EmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/StaleEventTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SwirldMain.java

This pull request introduces support for a callback in execution layer for events which are stale. The main changes add a new `STALE` status code, update the deduplication cache to track and manage stale transactions, and ensure the system can report and allow resubmission of such transactions. Additional changes update related logic and tests to accommodate this new status.
**Stale Transaction Handling:**
* Added a new `STALE` response code to `ResponseCodeEnum`
* Implemented a `staleEventCallback` in `Hedera.java` to mark all transactions in a stale event as stale in the deduplication cache, enabling correct downstream handling and resubmission.
* Updated `ServicesMain.java` to register the new `staleEventCallback` with the platform.
**Deduplication Cache …

feat: `STALE` Status Code in Transaction Receipts

---

hapi/hedera-protobuf-java-api/src/main/proto/platform/state/virtual_map_state.proto
hedera-state-validator/README.md
hedera-state-validator/src/main/java/com/hedera/statevalidation/ExportCommand.java
hedera-state-validator/src/main/java/com/hedera/statevalidation/exporters/SortedJsonExporter.java

PR highlights: 
-  adds support of exporting all the states in `sorted` mode. 
- fixes inconsistent naming 
- updates documentation 
- adds normalization of state key names
- replaces parallel sorting with `ConcurrentSkipListSet` which is a sorted data structure 
- adds clean up of empty files
Fixes #20609

feat: 20609 Implemented export for all the states

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockBufferService.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockState.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/GrpcBlockItemWriter.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockBufferServiceTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/HapiBlockNode.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/extensions/NetworkTargetingExtension.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/BlockNodeNetwork.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/subprocess/SubProcessNetwork.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeBackpressureSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSimulatorSuite.java

This PR cherry-picks the commit 54c499c to the release/0.65 branch.
Until Block Streams become the authoritative source of truth, backpressure via the block buffer service should not be enabled unless the StreamMode is BLOCKS and the BLockStreamWriterMode is FILE_AND_GRPC or GRPC specifically.
Fixes #20502 
**Checklist**

chore: cherry-pick: Change BlockBufferService backpressure logic

---

.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-longevity-test-controller.yaml
.github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-performance-test-controller.yaml

Add a new set of tags indicating when builds fail the single day test workflows.
Fixes #20541

ci: add fail tags to single day test workflows

---

.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-longevity-test-controller.yaml
.github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-performance-test-controller.yaml

This pull request updates the workflow job dependencies and output references in several GitHub Actions YAML files to use the new result job names (`tag-sdlt-result` and `tag-sdpt-result`) instead of the previous passing job names (`tag-sdlt-passing` and `tag-sdpt-passing`). This change ensures consistency in job naming and correct referencing throughout the workflows for both single-day longevity and performance test controllers, in both regular and adhoc variants.
**Workflow job dependency and output reference updates:**
* Longevity test controller workflows:
- Updated all job dependencies and output references from `tag-sdlt-passing` to `tag-sdlt-result` in `.github/workflows/zxf-single-day-longevity-test-controller.yaml` and …

chore: Replace tag-sdlt-passing tag-sdlpt-passing with appropriate tag-*-result

---

.github/workflows/flow-pull-request-formatting.yaml

This pull request simplifies the workflow configuration by removing the milestone check job from the `.github/workflows/flow-pull-request-formatting.yaml` file. This means that pull requests will no longer be required to have a milestone set for this workflow to pass.
Workflow configuration simplification:
* Removed the entire `milestone-check` job, including runner hardening and milestone validation steps, from `.github/workflows/flow-pull-request-formatting.yaml`.
Resolves #20715

ci: Remove milestone check from PR Formatting workflow

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/OpsDurationConfig.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/hevm/OpsDurationScheduleTest.java

Update multipliers used for ops duration when the value is not currently measure to reflect the worst case - 1575.

feat: update multipliers to reflect worst case

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/config/ConfigUtils.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/MerkleStateRoot.java
platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/VirtualMapState.java

Fix summary: backport of https://github.com/hiero-ledger/hiero-consensus-node/pull/20630 and https://github.com/hiero-ledger/hiero-consensus-node/pull/20692 to the `release/0.65` branch.
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20681
Fixes: https://github.com/hiero-ledger/hiero-consensus-node/issues/20691

chore: 20681: Backport the fix for 20629 to release 0.65

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml

This pull request enhances the failure reporting process in the `.github/workflows/zxcron-promote-build-candidate.yaml` workflow by improving the conditional logic and adding automated notifications and summaries. These changes help ensure that failures in any of the critical jobs are more visible and actionable.
**Workflow logic improvements:**
* Updated the `if` condition to check for failures in additional jobs (`deploy-ci-trigger` and `report-promotion`) alongside the existing ones, ensuring that failures in any step trigger the failure reporting process.
* Added `deploy-ci-trigger` and `report-promotion` to the `needs` list, so their results are included in the conditional checks and reporting.
**Automated failure notification and summary:**
* Added a `Build Rootly Summary` step to …

ci: Add rootly integration to zxcron-promote-build-candidate

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/zxcron-extended-test-suite.yaml

This pull request adds an automated integration with Rootly to the `node-flow-build-application.yaml` GitHub Actions workflow. The new steps generate a summary of job statuses, determine incident creation parameters, and trigger Rootly alerts and incidents based on workflow outcomes. This improves visibility and incident response for CI failures.
**Rootly Integration:**
* Added a step to set Rootly parameters (`CREATE_INCIDENT`, `ROOTLY_SERVICE_NAME`) based on the result of the `deploy-ci-trigger` job, allowing dynamic incident management.
* Implemented a step to build a Rootly summary, including job statuses and commit information, and output it for use in subsequent steps.
* Added a step to log the Rootly summary to the GitHub Actions job summary for easy review.
**Rootly Alerting and …

ci: Integrate Rootly with MATS tests

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java

This pull request updates the `EndOfStream` handling logic to acknowledge blocks in the buffer <= the block_number specified in the message. This block is the latest persisted and verified block.
**Block acknowledgement and state update logic:**
* Extracted and centralized the block acknowledgement logic into a new `acknowledgeBlocks` method, which updates the last verified block and conditionally triggers a jump to a new block if needed. (`BlockNodeConnection.java`)
* Modified end-of-stream handling to always update the latest acknowledged block by calling `acknowledgeBlocks` with `maybeJumpToBlock=false`, ensuring state consistency.
**Test updates and simplification:**
* Updated tests to verify that `updateLastVerifiedBlock` is always called on end-of-stream scenarios, …

feat: Update `EndOfStream` handling for acknowledgements

---

.github/workflows/zxc-block-node-regression.yaml

- Using latest CN Tag for the solo block node add command
- assigning correctly latest BN Tag to deploy

ci: Using latest CN tag for solo block node add command

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableHip1127Test.java

- Closes #20856 
* Reproduces the scenario and verifies fix (including no `WARN` or `ERROR` logs) in a new `@RepeatableHapiTest` that temporarily switches to submitting with 0.64 message encoding.
- 👉 This is a _0.65-only fix_, there is no corresponding PR to `main`.

fix: Fall back to `parseAndCheck()` if `parseSignedAndCheck()` is `INVALID_TX`

---

.github/workflows/zxc-single-day-longevity-nlg-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml

This pull request makes a small syntax adjustment to how the `title` variable is assigned in two GitHub Actions workflow files. The change improves consistency and correctness in shell scripting by switching from colon (`:`) to equals (`=`) for variable assignment.
- Changed variable assignment in the `Build Rootly Summary` step from `title: "..."` to `title="..."` in both `.github/workflows/zxc-single-day-longevity-nlg-test.yaml` [[1]](diffhunk://#diff-befdc1fa53221eeedd361cfdf3addfb464624172fdcee35a0b5dece213e372f1L595-R595) and `.github/workflows/zxc-single-day-performance-test.yaml` [[2]](diffhunk://#diff-3a51911168fea8fa3e128c5aa8376603deb99452e40137ebb41798b5780744a6L1191-R1191).
Fixes #20868

fix(ci): Invalid syntax wheen assigning rootly title to bash variable

---

.github/workflows/zxc-json-rpc-relay-regression.yaml

Fixes the JSON-RPC relay regression workflow to work properly with XTS tests.
- Removed temporary branch checkout logic that was causing issues
- Updated Kubernetes versions (node v1.32.5, kubectl v1.32.5, kind v0.29.0) 
- Simplified solo deployment commands and removed redundant node ID parameters
- Updated mirror node configuration to use port 8081 instead of multiple port forwards
- Added Redis and async transaction processing environment variables
- Cleaned up step naming and removed commented code

ci: fix JSON-RPC relay regression workflow for XTS tests

---

.github/workflows/zxc-block-node-regression.yaml

- Removed the "v" from the PROTO_TAG, that is used to construct the filename to untar the protobuf_source, since the file has this format: `block-node-protobuf-0.17.0.tgz` without the "v"
- Fixed Log Recollection steps to use the correct GitHub env variables.

ci: Fix untar and log recollection steps

---

.github/workflows/zxc-single-day-longevity-nlg-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml

This pull request updates several GitHub workflow YAML files to add support for new test machines (`AdHocSD8` and `AdHocSD9`) across both longevity and performance test pipelines. The changes ensure these new machines are recognized in input options, descriptions, environment variable parsing, and logic for assigning network owners. This improves test coverage and flexibility for running single-day tests on additional assets.
**Support for new test machines (`AdHocSD8`, `AdHocSD9`):**
* Updated the `test-asset` input descriptions and options in `.github/workflows/zxc-single-day-longevity-nlg-test.yaml`, `.github/workflows/zxc-single-day-performance-test.yaml`, `.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml`, and …

ci: Enable AdHocSD runners for Single Day Performance and Longevity Tests

---

.github/workflows/zxc-block-node-regression.yaml

This is a small fix, for a failure to print `ls -lR ..` of log folder for CN logs dump, expected is 1 zip file found.
We know the Folder path is calculated correctly cause is used on the next step successfully and the logs are produced.
but is making the wf think it "fails" in this step. leaving the log since it might be useful for future debugging or troubleshooting.

ci: fix cn logs folder list ls command (non blocking)

---

.github/workflows/zxf-dry-run-extended-test-suite.yaml

Add a missing secret to the mirror node regression workflow call inside XTS Dry Run workflow.
Fixes #20930

ci: add missing secret to mirror node regression workflow call

---

hedera-state-validator/src/main/java/com/hedera/statevalidation/validators/servicesstate/TokenRelationsIntegrity.java
hedera-state-validator/src/main/java/module-info.java

* verify existence of accounts and tokens directly in `VirtualMap`,  avoid caching read entities in `ReadableKVStateBase`
Fixes #20865
**Checklist**

chore: state validator keeps all read entities in memory, exhausts the Java heap

---

.github/workflows/zxc-single-day-longevity-nlg-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-longevity-test-controller.yaml
.github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-performance-test-controller.yaml

This pull request updates several GitHub Actions workflow files to standardize the usage and naming of the Rootly API token secret across performance and longevity test pipelines. The main changes involve introducing a new `rootly-api-token` secret for workflows, updating references to the token in workflow steps, and ensuring the secret is passed correctly in all relevant controller jobs.
**Workflow configuration improvements:**
* Added a new `rootly-api-token` input to both `.github/workflows/zxc-single-day-longevity-nlg-test.yaml` and `.github/workflows/zxc-single-day-performance-test.yaml`, specifying it as a required secret for Rootly alert and incident reporting. [[1]](diffhunk://#diff-befdc1fa53221eeedd361cfdf3addfb464624172fdcee35a0b5dece213e372f1R53-R55) …

ci(fix): Fix bug - SDPT/SDLT fail to create rootly incidents/alerts

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/logging/internal/LogConfigHelper.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleInstrumentedNode.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNetwork.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleTestEnvironment.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/logging/TurtleLogClock.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/logging/TurtleLogConfigBuilder.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/logging/TurtleLogging.java

Implemented a custom Log4j2 clock to enable simulated time timestamps in turtle test logs while maintaining real timestamps for test environment logging.
1. TurtleLogClock.java (NEW)
- Custom Log4j2 Clock implementation with context-aware time sources that provide fake time for Turtle Node threads and real time for all other threads.
2. TurtleTestEnvironment.java
- Added static block: Sets `log4j.Clock` system property before any Log4j2 initialization
- Updated constructor: Calls `TurtleLogClock.setFakeTime()` to configure simulated time
3. LogConfigHelper.java
- Updated node filters: Changed from plain node ID strings to JSON format to match TurtleNode `ThreadContext` values
- Empty `swirlds.log` files: Fixed `ThreadContext` key/value mismatch that was causing all log events to be …

chore: Use FakeTime in TurtleNode Logs

---

hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/system/VersionInfoCommandTest.java

Add yancli unit tests for VersionInfoCommand
https://github.com/hiero-ledger/hiero-consensus-node/issues/21007
Fixes #21007
**Checklist**

test: 21007 yahcli param unit tests VersionInfoCommand

---

.github/workflows/zxc-single-day-longevity-nlg-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxf-single-day-canonical-test.yaml

This pull request updates the incident type configuration in several GitHub workflow YAML files to streamline alert categorization. The main change is the removal of the "Performance Engineering" incident type from the `incident_types` field, leaving only "Platform CI". The "Performance Engineering" team is still listed under the `teams` field, so team notifications will continue as before.
Incident type configuration updates:
* [`.github/workflows/zxc-single-day-longevity-nlg-test.yaml`](diffhunk://#diff-befdc1fa53221eeedd361cfdf3addfb464624172fdcee35a0b5dece213e372f1L666-R666): Removed "Performance Engineering" from the `incident_types` field, now only "Platform CI" is specified.
* [`.github/workflows/zxc-single-day-performance-test.yaml`](diffhunk://#diff-3a51911168fea8fa3e128c5aa837660 …

chore: Update incident_types

---

platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/ConsensusNodeManager.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java
platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ReconnectStateLoader.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuildingBlocks.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformComponents.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/ConsensusWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PassThroughWiring.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java

This PR breaks PlatformWiring into two different pieces and moves some of its responsibilities to PlatformCoordinator.
`PlatformCoordinator` repurposing. It now hosts all operations against the platform (e.g., start, stop, pause, and resume gossip, submit a status action, push a roster update, etc.) through its wires.
`PlatformWiring` becomes a static utility class with the responsibility of wiring the components.
`PlatformComponents` is a new record that holds a reference to all components in the platform.
Fixes #20698

chore(20698): Invert PlatformWiring and PlatformCoordinator relationship

---

.github/workflows/zxc-single-day-longevity-test.yaml
.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-longevity-test-controller.yaml

Rename all instances of `longevity-nlg-test` to `longevity-test` to be consistent with other test names.
Fixes #20833
**Testing**:
Successful Smoke Test run [here](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/17469376098).

chore: rename all instances of longevity-nlg-test to longevity-test

---

.github/workflows/zxcron-extended-test-suite.yaml

This pull request includes a minor update to the `.github/workflows/zxcron-extended-test-suite.yaml` workflow. The change ensures that backtick characters are removed from the commit list output before it is set as a GitHub Actions output variable.
- Fixes #21088

ci(fix): Fix bug with control characters being interpreted in json output

---

.github/workflows/zxc-single-day-longevity-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxc-tck-regression.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxf-dry-run-extended-test-suite.yaml

Recently surface bug prevents TCK and RPC Relay regression panels from running as the solo version is out of date (and hard coded). This PR binds the CITR solo installs to a single version.
Fixes #21138 
- [XTS Dry Run](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/17862933890/job/50798045252)

ci(fix): Solo version mismatch causing errors in regression panels

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/zxcron-extended-test-suite.yaml

This pull request introduces enhancements to the CI/CD workflow by improving error reporting and service classification in GitHub Actions. The main changes add a new `failure-mode` output to the `node-zxc-compile-application-code.yaml` workflow, enabling downstream jobs to distinguish between general and CI/CD-specific failures. This allows for more accurate assignment of incidents to the appropriate service and better traceability of workflow failures.
**Failure mode reporting enhancements:**
* Added a `failure-mode` output to the `node-zxc-compile-application-code.yaml` workflow, which is determined by a new `calculate-failure-mode` step that analyzes the outcomes of key workflow steps to classify failures as either `general` or `ci_cd`. …

ci(fix): Add granularity to failure-modes in zxc-compile-application

---

hapi/hedera-protobuf-java-api/src/main/proto/platform/message/gossip_sync_data.proto
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/rpc/SyncData.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/RpcPeerHandler.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/protocol/rpc/RpcPeerProtocol.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/gossip/shadowgraph/RpcShadowgraphSynchronizerTest.java

Change sync logic to always send events, even when we are struggling (i.e. too much backpressure or new idea below), but do not receive events. This is a port of #20663 to RPC sync.
Fixes #20666 
**Checklist**

chore: Do not receive events when unhealthy in RPC sync

---

hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/accounts/SetupStakeCommandTest.java

Description:
Add yancli unit tests for SetupStakeCommand
https://github.com/hiero-ledger/hiero-consensus-node/issues/21008
Fixes https://github.com/hiero-ledger/hiero-consensus-node/issues/21008
Notes for reviewer:
Checklist
Tested (unit, integration, etc.)

test: yahcli param unit tests SetupStakeCommand

---

.github/workflows/flow-increment-next-main-release.yaml
.github/workflows/flow-trigger-release.yaml

Rename release workflows to use a `[Release]` prefix instead of `[Main]` prefix.
Fixes #21148

ci: rename release workflows

---

hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/commands/keys/KeysCommandTest.java

Adds unit tests for:
* `NewPemCommand`
* `ExtractPublicCommand`
* `ExtractDetailsCommand`
Fixes [20998](https://github.com/hiero-ledger/hiero-consensus-node/issues/20998)
**Checklist**

test: Add Yahcli Keys command params unit tests

---

platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/MerkleDbCompactionCoordinator.java
platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/DataFileCompactor.java

* make sure pending compaction tasks are properly interrupted.
* honor the timeout parameter in `awaitForCurrentCompactionsToComplete(long timeoutMillis)`
Fixes #21187
**Checklist**

fix: compaction is not properly interrupted upon closing MerkleDbDataSource

---

.github/workflows/zxcron-extended-test-suite.yaml

This pull request updates the `.github/workflows/zxcron-extended-test-suite.yaml` workflow to add an option for enabling promotion tagging and to adjust the tagging logic accordingly.
Workflow input and logic changes:
* Added a new workflow input `enable-promotion` to control whether promotion tagging with an epoch timestamp is enabled.
* Updated the tagging step to only create a tag if `enable-promotion` is not set to `"true"`, ensuring that promotion tagging is conditional based on the new input.
Closes #21221

ci: Add input `enable-promotion` to XTS workflow

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/zxc-single-day-longevity-nlg-test.yaml
.github/workflows/zxc-single-day-longevity-test.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxc-tck-regression.yaml
.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxcron-promote-build-candidate.yaml
.github/workflows/zxf-dry-run-extended-test-suite.yaml
.github/workflows/zxf-prepare-extended-test-suite.yaml
.github/workflows/zxf-single-day-canonical-test.yaml
.github/workflows/zxf-single-day-longevity-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-longevity-test-controller.yaml
.github/workflows/zxf-single-day-performance-test-controller-adhoc.yaml
.github/workflows/zxf-single-day-performance-test-controller.yaml

Add CI-related changes to the release/0.66 branch.
**Approved on Sep 18 2025**:
- [ci: Update SDPT and SDLT workflow to only tag when build ID is present](https://github.com/hiero-ledger/hiero-consensus-node/pull/20984), `3ac05f882891cbbc9b86e2777d96feff0418c104`
- [chore: Update incident_types](https://github.com/hiero-ledger/hiero-consensus-node/pull/21055), `785c4b9f6b9f5f9198aedaba42794fe2c413adc2`
- [chore: replace input.ref with github.ref in single day controllers](https://github.com/hiero-ledger/hiero-consensus-node/pull/20988), `5675961e64066aadb04cef05b01bcc10b1e5bf7f`
- [ci: Automatically generate the GH release](https://github.com/hiero-ledger/hiero-consensus-node/pull/20970), `2711159980a05df5b1c97027bf36c42aa36caa2b`
- [ci(fix): remove inputs from calls to …

chore(cherry pick): add CI-related PRs to release 0.66 branch

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/zxc-single-day-performance-test.yaml
.github/workflows/zxcron-promote-build-candidate.yaml

**CI-Related Scripts Approved on Sep 25 2025**:
- [ci: Update ref to use the correct tag instead of latest on main](https://github.com/hiero-ledger/hiero-consensus-node/pull/21165), `e199f7bede0e8236478304e6fe41de59f3fa1dfb`
- [ci: update MATS to parallel runs](https://github.com/hiero-ledger/hiero-consensus-node/pull/21159), `1a5b9474e13e802d9b4b86a9dba857e8f6ff4513`
**Performance-Related Scripts Approved on Sep 25 2025**:
- [test: fix of 21164 (to use abs diff value instead of rounded percentage)](https://github.com/hiero-ledger/hiero-consensus-node/pull/21166), `d28b84a2038679e1d1c356d309654f7245adbf98`
Fixes #21243

chore(cherry-pick): additional CI changes for 0.66 release

---

.github/workflows/zxcron-extended-test-suite.yaml
.github/workflows/zxf-dry-run-extended-test-suite.yaml

This pull request restructures the extended test suite workflows in `.github/workflows/zxcron-extended-test-suite.yaml` and `.github/workflows/zxf-dry-run-extended-test-suite.yaml` by splitting the monolithic "extended test suite" job into five distinct jobs, each targeting a specific type of XTS test. It also updates downstream jobs and status reporting to reflect these changes, and introduces logic to better determine and report failure modes.
**Test suite job restructuring:**
* The previous `extended-test-suite` job is replaced by five specialized jobs: `xts-timing-sensitive-tests`, `xts-time-consuming-tests`, `xts-hammer-tests`, `xts-hapi-time-consuming-tests`, and `xts-hapi-block-node-comms-tests`. Each job runs its corresponding subset of tests and passes relevant secrets and …

ci(main): Split CITR eXtended Test Suite into component parts 

---

platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodeLogResultsAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/MultipleNodeLogResultsContinuousAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/SingleNodeLogResultAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/assertions/SingleNodeLogResultContinuousAssert.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeLogResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodePcesResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/internal/result/MultipleNodeReconnectResultsImpl.java
platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleNode.java

This PR adds new log assertions that were introduced in the PoC and should be generally available. There are also some bug fixes included that popped up recently.
Fixes #21225

chore: Additional log assertions

---

hapi/hapi/src/main/java/com/hedera/hapi/util/HapiUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/FileBlockItemWriter.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/impl/producers/formats/v6/BlockRecordWriterV6Test.java
platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/HapiUtils.java

This PR moves  Move `asAccountString` to `hapi` module (from `com.swirlds.state.lifecycle.HapiUtils` to `com.hedera.hapi.util.HapiUtils`)
Fixes #21269 
**Checklist**

refactor: 21269 Move `asAccountString` to `hapi` module

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnectionTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/blocknode/BlockNodeSuite.java

This PR fixes two BN communication suite tests part of the XTS tests.
Fixing the behaviour when we want to restart a connection to a particular block node. In this case, we don't want to select a new block node while the reschedule period elapses, but restart the same connection to that block node
Fixes #
**Checklist**

fix: Fix some BN communication XTS tests

---

hedera-node/configuration/dev/application.properties
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/OpsDurationConfig.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/annotations/ServicesV066.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/annotations/ServicesV067.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/OpsDurationCounter.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v066/Version066FeatureFlags.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v067/V067Module.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v067/Version067FeatureFlags.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEVM.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmVersion.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/OpsDurationSchedule.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/hevm/OpsDurationScheduleTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/EthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/JumboTransactionsEnabledTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ethereum/batch/AtomicEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/AtomicSmartContractServiceFeesTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/fees/SmartContractServiceFeesTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchNegativeTest.java

Enables the ops duration throttle feature in the 0.67 module.
- disables the existing gas throttle (and, even though disabled, bumps its limits by a factor of 100, not sure why we wanted this @lukelee-sl ?)
- enables the new ops duration throttle
- enables 100% gas refund on evm transactions
Includes some tweaks carried over from https://github.com/hiero-ledger/hiero-consensus-node/pull/21076

feat: Add v0.67 module and enable ops duration throttle; minor tweaks

---

platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java
platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkPartitionTest.java
platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/test/CheckingRecoveryTest.java
platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/test/ReconnectTest.java
platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/test/RestartTest.java

This PR increases the timeouts when waiting for a condition to be met to 120 seconds. These conditions are usually fulfilled much faster and the timeouts are just there to ensure that tests do not hang forever.
Fixes #21440

test: Increase all timeouts waiting for conditions to be met to 120 seconds.
