hiero-ledger/hiero-consensus-node

hedera-node/configuration/dev/settings.txt

Remove `eventsLogDir` from _hedera-node/configuration/dev/settings.txt_.

Remove eventsLogDir in DEV

---

.circleci/config.yml

None
Previous sleep time is too long
None.
None

sleep shorter time to avoid ci complains no output

---

hedera-node/src/main/java/com/hedera/services/state/serdes/TopicSerde.java
hedera-node/src/test/java/com/hedera/services/state/serdes/MerkleTopicSerdeTest.java

Fix inconsistent use of `SerializableDataOutputStream#writeBytes` and `SerializableDataInputStream#readByteArray` in [`TopicSerde`](hedera-node/src/main/java/com/hedera/services/state/serdes/TopicSerde.java).

Use read/writeNormalisedString for Topic memos

---

.circleci/config.yml

In this PR https://github.com/swirlds/swirlds-platform-regression/pull/410 the names of JRS regression JSONS are modified. change names of those JSONs in the cron job that runs nightly regression

Fix JRS test file names based on new naming conventions

---

.circleci/config.yml

Closes #488 
1. Temporarily disable several legacy tests to avoid possible threshold caused failure;
2. Also disable nightly regression for master branch per discussion with Nosh and Neeha;
None.

Disable CircleCi nightly regression for master as per discussed.

---

.circleci/config.yml

Closes #515 
1. Changed the start times for JRS regression tests;
2. Also restored the swirlds-platform-regression branch to the right one;
None.

Modifying the cron times for JRS regression tests.

---

hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java

Summary of the change:
- Add check if token divisibility is bigger than `Long.Max_value` (e.g. set too big divisibility upon token creation)
- Add tests

Fix(token-divisibility): check if 10 ^ divisibility > long max value

---

hedera-node/pom.xml
test-clients/pom.xml

Use another staging repo while waiting for `ethereumj-core` to publish to Maven Central.

Update staging repo while waiting for ethereumj-core 

---

hedera-node/pom.xml
test-clients/pom.xml

Remove `ethereumj-core` staging repo since the artifact is now in Maven Central.

Use ethj from Maven Central

---

.circleci/config.yml

Closes #501 
Reduce TPS to avoid overloading GRPC server

Lower TPS for circle ci network error test flow

---

.circleci/config.yml
hapi-proto/pom.xml
hedera-node/pom.xml
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
hedera-node/src/main/java/com/hedera/services/context/properties/PropertySource.java
hedera-node/src/main/java/com/hedera/services/records/FeeChargingRecordsHistorian.java
hedera-node/src/main/resources/bootstrap.properties
hedera-node/src/main/resources/semantic-version.properties
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/records/FeeChargingRecordsHistorianTest.java
hedera-node/src/test/resources/bootstrap/standard.properties
pom.xml
test-clients/devops-utils/validation-scenarios/config.yml
test-clients/pom.xml
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
test-clients/src/main/java/com/hedera/services/bdd/suites/records/ThresholdRecordCreationSuite.java

- Roll _pom.xml_ versions to `0.8.0`.
- Use the `SwirldState#initialize` method to ensure the tokens `FCMap` is created when restoring from an `0.7.0` state.
- Add a global/dynamic property `ledger.createThresholdRecords` (default `false`) to disable threshold records in a more principled way than the targeted code deletion.

Fix rc1 issues

---

test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/OpProvider.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java

Closes #497 
This is a follow-up of previous commit, which has caused insufficient_tx_fee error for smart contract test.
None.

Adjust the transaction fee for fixing the insufficient tx fee error

---

hedera-node/src/main/java/com/hedera/services/fees/charging/FieldSourcedFeeScreening.java
hedera-node/src/test/java/com/hedera/services/fees/charging/FieldSourcedFeeScreeningTest.java

Closes #551 
Related to [261](https://github.com/swirlds/hedera-fpcomplete-audit/pull/261)
Validates that `THRESHOLD_RECORD` is present in `feeAmounts` to avoid a NullPointerException.

00551-D-FieldSourcedFeeScreeningNPE

---

test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java

Enhance `HapiQueryOp` to allow the user to set the query payment explicitly.
This allows tests such as [`queryPaymentsAreSanityChecked` here](https://github.com/hashgraph/hedera-services/blob/support-querypayment-testing/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java#L95):
```
private HapiApiSpec queryPaymentsAreSanityChecked() {
return defaultHapiSpec("QueryPaymentsAreSanityChecked")
.given(
cryptoCreate("a"),
cryptoCreate("b")
).when().then(
getAccountInfo(GENESIS)
.withPayment(
cryptoTransfer(spec ->
invalidMultiAccountPaymentToNode003(
spec, "a", "b", 1_000L))
).hasAnswerOnlyPrecheck(INVALID_QUERY_PAYMENT_ACCOUNT_AMOUNTS)
);
}
```

Support querypayment testing

---

hapi-proto/src/main/java/com/hedera/services/legacy/proto/utils/KeyExpansion.java
hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JKey.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JKeyTest.java

Signed-off-by: Anirudh Ghanta <anirudh.ghanta@hedera.com>
Closes #602 
Updated the key depth limit `KEY_EXPANSION_DEPTH` and we throw a `DecoderException` error when this limit is reached.
None.

update the key depth limit

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleOptionalBlob.java

- Add a comment to clarify why `MerkleOptionalBlob#serializeAbbreviated` is a no-op.

Add comments clarifying abbreviated serde in MerkleOptionalBlob

---

hapi-proto/HAPI.html
hapi-proto/src/main/proto/ResponseCode.proto
hedera-node/src/main/java/com/hedera/services/txns/token/TokenTransferTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
hedera-node/src/main/java/com/hedera/services/txns/validation/OptionValidator.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenTransferTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/validation/ContextOptionValidatorTest.java
hedera-node/src/test/java/com/hedera/test/mocks/TestContextValidator.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenTransact.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

Closes #None
* Add two ResponseCodes - `EMPTY_TOKEN_TRANSFER_BODY` and `EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS`.
* Update `isAcceptableTokenTransfersLength`.
* Add/update unit tests.
* Update `HapiTokenTransact` to allow token transfers with empty account amounts.
* Add BDD Tests.

Fix(token): Restrict empty token transfers

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetTxnRecordResourceUsage.java
hedera-node/src/main/java/com/hedera/services/records/RecordCache.java
hedera-node/src/main/java/com/hedera/services/state/EntityCreator.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiringCreations.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
hedera-node/src/main/java/com/hedera/services/state/expiry/NoopExpiringCreations.java
hedera-node/src/main/resources/bootstrap.properties
hedera-node/src/test/java/com/hedera/services/context/ServicesContextTest.java
hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/legacy/unit/FreezeServiceImplTest.java
hedera-node/src/test/java/com/hedera/services/legacy/unit/PreCheckValidationTest.java
hedera-node/src/test/java/com/hedera/services/legacy/unit/QueryValidationTest.java
hedera-node/src/test/java/com/hedera/services/legacy/unit/handler/TransactionHandlerTest.java
hedera-node/src/test/java/com/hedera/services/legacy/unit/service/SmartContractServiceImplTest.java
hedera-node/src/test/java/com/hedera/services/records/RecordCacheFactoryTest.java
hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiringCreationsTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
hedera-node/src/test/java/com/hedera/test/mocks/TestFeesFactory.java
hedera-node/src/test/resources/bootstrap/standard.properties
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/PerpetualTransfers.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/ReviewMainnetEntities.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/TogglePayerRecordUse.java

**Summary of change**
Introduce the `ledger.createPayerRecords` (default is `false`) flag to control if 3-min payer records should be added to the `payerRecords` FCQ of the effective payer for each consensus txn handled.

Make state payer records optional

---

hedera-node/src/test/java/com/hedera/services/txns/file/FileUpdateTransitionLogicTest.java

Signed-off-by: Anirudh Ghanta <anirudh.ghanta@hedera.com>
Closes #617 
Mock the class 'UpdateResult' to remove the NPE logs.
None.

add a mock UpdateResult so that setAttr method of Hederafs doesnt return null

---

test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/consensus/RandomMessageSubmit.java

Closes #578 
Passed test https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1602113932103000 
Expected 7200 with 6 SuiteRunner processes and 4 clients and 300 maxOpsSec , achieved 7000

Fix the TPS reduced by half for HCSSubmitMessage performance test 

---

test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiApiClients.java
test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java

Fix netty channels closing issue

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

Permit recovery from `<= 0.9.0` states.

Use MerkleInternal#initialize to create DiskFs if missing 

---

pom.xml

Change config for `maven-surefire-plugin` to avoid random crashes of forked VMs during `mvn test`.

Try hard-coding argLine

---

test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/QueryFailuresSpec.java

Closes #654
Simple change to fix previous misunderstanding of query response status of deleted file.
None.

Change the test case to correct check method.

---

pom.xml

Restore `@{argLine}` interpolation in Surefire config to get Jacoco reports  discoverable by CodeCov.

Revert Surefire argLine config

---

.circleci/config.yml

Closes #678
1. Enable 6-node JRS daily regression in hedera-regression channel;
2. Add the weekly performance regression tests for hedera services CryptoTransfer and HCS;
3. Currently starting from fresh instead of start from saved state as planned. Have hedera services issue #691 tracking this;
None.

Add weekly performance regression tests.

---

.circleci/config.yml

Closes #678 
Right now the planned 4 hour performance regression starting from saved state is impossible due to validation memory limitation and issues from saved state file loading. Now the intermediate solution is:
1. run for one hour for started;
2. Start from scratch instead of from saved state;
We will have follow up issues to fix these issues and reach the designed goal.
None.

00678 d weekend perf regression

---

test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/SimpleFreezeOnly.java

Added a simple freeze test will be used at the end of state recover test,
so the event stream file can be flushed with running hash and closed properly.

Add simple freeze test to close stream file properly

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/FreezeSuite.java

Closes #715 
1. Changes to fix the feature update CircleCi regression test. Here we force the FreezeSuite's transactions to be paid by treasury account as recent check only allow treasury account to do update. 
2. Also disable 4-node perf JRS regression test;
None.

00715 d nightly update regression failure

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/BackingStore.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/BackingTokenRels.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/FCMapBackingAccounts.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/ServicesContextTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/BackingTokenRelsTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/FCMapBackingAccountsTest.java

If the context's `backingAccounts` or `backingTokenRels` are non-`null` in `ServicesState#init`, then rebuild their "existing entities"  lookups because this implies a reconnect just finished.

Add + use ServicesContext#rebuildBackingStoresIfPresent

---

.circleci/config.yml

While running nightly JRS regression `swirlds-platform` build is failing. This PR fixes the build

Fix building swirlds-platform in cicleci JRS regression

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/records/RecordCache.java
hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
hedera-node/src/main/java/com/hedera/services/state/expiry/KeyedExpirations.java
hedera-node/src/main/java/com/hedera/services/state/expiry/MonotonicFullQueueExpiries.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/MonotonicFullQueueExpiriesTest.java

Ensure that not only the `txnHistories` map, but also the expiry queues in both `ExpiryManager` and `RecordCache` are cleared when starting from a saved state.

Clear all record-based views in ExpiryManager#restartTrackingFrom

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
hedera-node/src/main/java/com/hedera/services/state/initialization/SystemFilesManager.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
test-clients/devops-utils/validation-scenarios/config.yml

- Closes #786 
- Skip `SystemFilesManager` load calls in `ServicesState#init` if `BinaryObjectStore.isInitializing()` is `true`.
- Initialize system files in `ServicesMain#init` if `SystemFilesManager.areFilesLoaded()` is `false`.

Defer sysfile loads until ServicesMain#init if BinaryObjectStore#isInitializing

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java

Closes #779 
As throttles are limited to 8k on public testnet , Restart performance testsresulted only 8k. Modified throttles on `CryptoTransferLoadTest` and `SubmitMessageLoadTest` to 10K.
Passed `9
Crypto-Restart-Performance-10k-46m` with 10k: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1605816581075700

Modify throttles on LoadTest after loading public testnet state

---

hedera-node/src/test/java/com/hedera/services/context/ServicesContextTest.java

Catch more mock calls to resolve test coupling.
- Ran build many times locally, all tests passed.
- CI build passed twice with links provided below
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/7030/workflows/a3be7674-8db4-4abc-931b-994d5b5cfa15/jobs/42667
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/7030/workflows/4d59d3e6-0905-46c3-9cba-05a450789420
None.
None.

Fix test coupling

---

.circleci/config.yml

The basic test was changed by mistake to zero stake tests. Reverted the change

fix test added by mistake

---

hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/AwareFcfsUsagePricesTest.java

N/A
Create standalone PR since other changes may take a while to finish test.
Closes #793

Avoid false alarm when using default price usage

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransfersLoadProvider.java

- Supports resolution of #802 
- Reschedule the `run-performance-regression` nightly at 5:30.
- Allow [the `TokenTransfersLoadProvider`](https://github.com/hashgraph/hedera-services/blob/772b7eac041ecefaee92b2c836e4bec63c21343c/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransfersLoadProvider.java) to be run against a network starting from a public testnet state; that is, when there is no guarantee that each client has a unique client, nor that the HTS operations are initialized by default.
1. Add the `.retryPrecheckFrom(BUSY, DUPLICATE_TRANSACTION, PLATFORM_TRANSACTION_NOT_CREATED)` qualifier to all initializing operations in the test.
2. Begin initialization by setting all HTS ops permission ranges to `0-*` in …

Update TokenTransfersLoadProvider for use in restart testing from public testnet state

---

.circleci/config.yml

Add Reconnect tests to run once a night in addition to other daily tests.
Should be closed after https://github.com/swirlds/swirlds-platform-regression/pull/683
Sanity check test passed: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1606236412106000

add reconnect tests to nightly

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/legacy/stream/RecordStream.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java

Closes #806 
Ensure that any context objects using `ctx.properties()` initialize _after_ `ctx.systemFilesManager().loadAllSystemFiles()` is called.

Rationalize init order in ServicesMain for restart case

---

docs/privileged-transactions.md
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileUpdate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/CustomSpecAssert.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransfersLoadProvider.java

- Add appropriate retries for various `CryptoCreate`/`GetTxnRecord`/`FileUpdate` operations that may run into `DUPLICATE_TRANSACTION` or---much more rarely---`INVALID_FILE_ID` prechecks during a JRS test with multiple clients. 
- The main thing is to catch `Throwable`s instead of `Exception`s since many operations use `Assert.fail` to die, which raises an `AssertionError` and will slip through a `catch (Exception...` clause.
- Accidentally added working draft of _docs/privileged-transactions.md_, doesn't need review here. 😁

Stabilize jrs clients

---

test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

In HTS correctness specs, don't give non-trivial balances to scratch crypto accounts unless really necessary.

Use minimal initial balances for accounts created in HTS functional tests

---

test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/NodeLivenessTimeout.java

Use non-free query in `NodeLivenessTimeout` to ensure platform must be `ACTIVE` for liveness to be accepted.

Switch getAccountBalance to getAccountInfo

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateApiPermissionsDuringReconnect.java

Closes #814 
Add initial delay to make sure the last server node is disconnected before moving forward with rest of the test. This should help with random failure of this test case. 
None.

00814 d reconnect api permission update failure

---

.circleci/config.yml

As the folder structure has changed, S3 link in slack message doesn't work. Fixed the folder structure that syncs to S3.
Closes #769 
Running a test to validate this change works

Fix S3 folder link to see the results of nightly regression

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java

Related to #815
Reduces the wait time for the node to reconnect, because the transaction is only alive for 180 seconds. It waits after the first check and checks again due to the transition DISCONNECTED -> ACTIVE -> BEHIND, documented in #833 
This change will not be required or could be removed once #833 is completed

00815: Waits for reconnect to happen

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/CannotDeleteSystemEntitiesSuite.java

Closes #823 
1. Added the test suite to make sure nobody can delete current system entities (entity with id < 1000);
2. Added the test suite to Continuous Integration workflow;
None.

Add new system entities deletion test cases.

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2144Spec.java

Closes #836 
1. Disabled the daily basic JRS regression test. Didn't delete it because we may bring it back after some thinking;
2. Created a CircleCi regression test workflow to cover the JRS regression test disabled;
3. Modified the superuser throttling test case to not run into INSUFFICIENT_ACCOUNT_BALANCE error;
The successful test run: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/7546/workflows/74da5c55-0a3f-4a64-b13a-e366e660b998
None.

00836 d move basic tests out of jrs

---

hapi-proto/src/main/proto/TransactionReceipt.proto
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/AwareTransactionContext.java
hedera-node/src/main/java/com/hedera/services/context/TransactionContext.java
hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/TxnReceipt.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenBurnTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenMintTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenWipeTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/context/AwareTransactionContextTest.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/TxnReceiptTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenBurnTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTotalSupplyAfterMintBurnWipeSuite.java

Closes #645 
1. Added newTotalSupply in TransactionReceipt for Token mint/burn/wipe transactions if these these transactions are successful;
None.

Added newTotalSuppy in TransactionReceipt for token mint/burn/wipe transactions

---

hedera-node/src/main/java/com/hedera/services/state/initialization/BackedSystemAccountsCreator.java
hedera-node/src/test/java/com/hedera/services/state/initialization/BackedSystemAccountsCreatorTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

Closes #784
Special accounts from 900 to 1000 will be created with zero balance and genesis key if they don't exist.
Note that no records will be created for the creation of these special accounts.

00784 Special accounts creation

---

.circleci/config.yml

Closes #862 
GCP side still doesn't work, as before.
1. Split the 4-node and 6-node perf JRS regression into separate workflows to avoid the issue of killing by CircleCi due to timeout (5-hour limit);
None.

Split 6-node and 4-node perf JRS regression tests.

---

test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/SysFilesUpdate.java

**Summary of change**
- In `CryptoCreateForSuiteRunner`, use a new `.ensuringResolvedStatusIsntFromDuplicate()` to have the `cryptoCreate` put a unique memo in the submitted transaction; and then assert the resolved record actually _has_ that memo.
- (This prevents two JRS clients from believing they both created the same payer account.)
- Also cherry-picks a fix to the `SysFilesUpdate` dev-ops utility.

Add HapiTxnOp option to ensure resolved status isn't from duplicate txn

---

.env
.gitignore
compose-build.sh
run/gcr-login.sh
run/gcr-push.sh
run/gcr-tag.sh

- Addresses #532 (will close pending secondary confirmation of new Docker image)
Update `TAG=0.10.0` in _.env_ so default `docker-compose up` will use the `gcr.io/hedera-registry/services-node:0.10.0` image.

Add some run/gcr* helper scripts; roll TAG in .env to 0.10.0 

---

.circleci/config.yml

Using the  `--include` and `--exclude` flags are still taking time to upload though they are not uploading data/saved folder to s3.
So we are deleting the folder before uploading to s3.

Fix S3 Upload

---

.circleci/config.yml

Closes #888 
Disable all AWS nightly tests running on `master` and only run on GCP.

Disable AWS nightly tests

---

.circleci/config.yml

All regression tests on master runs on GCP. Move all tests that run on v0.10.0 release tag to run on GCP instead of AWS.

Move tests on 0.10.0 to run on GCP

---

test-clients/scripts/updateNodeTransfer.sh

Related with regression issue https://github.com/swirlds/swirlds-platform-regression/pull/755
Replacing hard coded user name and key file with command line parameter

Add use name and key file location to fix updated node test

---

test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java

set the property ledger.keepRecordsInState before the tests as it is being set to true at startUp on every regression run.
Signed-off-by: Anirudh Ghanta <anirudh.ghanta@hedera.com>
Closes #898 
Set ledger.keepRecordsInState=false before the test `accountsGetPayerRecordsIfSoConfigured`.
None.

Property ledger.keepRecordsInState is set to true by default.

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java

Closes #936 
Related regression PR : https://github.com/swirlds/swirlds-platform-regression/pull/765
Instead of setting `ledger.keepRecordsInState` as true for all the tests in regression, set the value to true for `ValidateDuplicateTransactionAfterReconnect` as it is needed for the test `TransactionHistory-Reconnect-1-12m.json`
Passed Reconnect test : 
`TransactionHistory-Reconnect-1-12m` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609954937441200
Passed other reconnect tests : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609953504440500

Fix ValidateDuplicateTransactionAfterReconnect to set ledger.keepRecordsInState as true 

---

hapi-fees/pom.xml
hedera-node/pom.xml
pom.xml

Use JUnit5 BOM @ `<version>5.7.0</version>` to fix warnings like,
```
Jan 07, 2021 5:06:17 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 4.13.1
```

Move to junit-bom dependency management for junit5 artifacts

---

Dockerfile
docker-compose.yml

- @mark-hedera surfaced a problem when building the Docker image on a Raspberry PI 4 (`libsodium` was missing); he also provided this fix. 
- Install `postgresql-client` so that database recovery from a _PostgresBackup.tar.gz_ will work with the Docker Compose network.

Improve build portability; add psql to image

---

hedera-node/src/main/java/com/hedera/services/context/AwareTransactionContext.java
hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JFileInfo.java
hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JKey.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/file/FileCreateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/file/FileUpdateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
hedera-node/src/main/java/com/hedera/services/txns/validation/PureValidation.java
hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JFileInfoTest.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JKeyTest.java
hedera-node/src/test/java/com/hedera/services/txns/file/FileUpdateTransitionLogicTest.java

- Closes #914 
- Throw only `DecoderException`s from `JKey.mapKey`; refine `catch` clauses in client code.
None.

Refine exception-handling for JKey.mapKey

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccountTokens.java

- Closes #916
- Use `MerkleAccountTokens.set` instead of `System.arraycopy` to set token id parts into `long[]` fields.
- Fix typo using non-standard midpoint calculation in `MerkleAccountTokens.logicalIndexOf` binary search.
None.

Use MerkleAccountTokens.set instead of System.arraycopy

---

hedera-node/src/main/java/com/hedera/services/fees/calculation/consensus/queries/GetTopicInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetContractInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountRecordsResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetTxnRecordResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/file/queries/GetFileContentsResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/file/queries/GetFileInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/token/queries/GetTokenInfoResourceUsage.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/consensus/queries/GetMerkleTopicInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/contract/queries/GetContractInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountRecordsResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetTxnRecordResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/file/queries/GetFileContentsResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/file/queries/GetFileInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/token/queries/GetTokenInfoResourceUsageTest.java

- Closes #915
Dispense with the redundant `catch` clauses in all `QueryResourceUsageEstimator.usageGivenType` implementations except for `ContractCallLocalResourceUsage`, which may benefit by translating exceptions thrown by its legacy delegate.
The top-level handler in `QueryAnswerHelper` can do just as well for any unforeseen condition that causes usage estimation to fail with a runtime exception.
None.

Let runtime exceptions in query usage estimators propagate

---

hedera-node/src/main/java/com/hedera/services/context/domain/trackers/IssEventInfo.java
hedera-node/src/main/java/com/hedera/services/state/forensics/IssListener.java
hedera-node/src/test/java/com/hedera/services/context/domain/trackers/IssEventInfoTest.java
hedera-node/src/test/java/com/hedera/services/state/forensics/IssListenerTest.java

- Closes #917
Convert `IssEventInfo.shouldDumpThisRound()` into a pure method and use `IssEventInfo.decrementRoundsToDump()` to accomplish the current side-effect of `remainingRoundsToDump--`.
None.

Separate side-effects from IssEventInfo.shouldDumpThisRound

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/BackingTokenRels.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleEntityAssociation.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/ledger/BaseHederaLedgerTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/BackingTokenRelsTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/HashMapBackingTokenRels.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java

- Closes #918 
- Closes #919
- Use `org.apache.commons.lang3.tuple.Pair` instead of `Map.Entry` to represent account-token relationships.
- Iterate over the cache entry set in `BackingTokenRels.flushMutableRefs` instead of key set.
None.

Use commons Pair instead of Map.Entry; simplify iteration in flushMutableRefs

---

hapi-fees/src/main/java/com/hedera/services/usage/SingletonEstimatorUtils.java
hapi-fees/src/main/java/com/hedera/services/usage/UsageEstimate.java
hapi-fees/src/test/java/com/hedera/services/usage/SingletonEstimatorUtilsTest.java
hapi-proto/src/main/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilder.java
hapi-proto/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java
hapi-proto/src/main/java/com/hederahashgraph/fee/FeeBuilder.java
hapi-proto/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java
hapi-proto/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageEstimatorUtils.java
hedera-node/src/main/java/com/hedera/services/store/CreationResult.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/UsageEstimatorUtilsTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java

- Closes #920
- Closes #921
- Fix typo in `FeeBuilder.RECIEPT_STORAGE_TIME_SEC`.
- Add Javadoc to `CreationResult<T>` (replacement of `TokenCreationResult`).
None.

Fix misc typos

---

hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
hedera-node/src/main/java/com/hedera/services/context/properties/PropUtils.java
hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java

- Closes #923
Use try-with-resources when loading properties files in `BootstrapProps.load`, `PropUtils.loadOverride`, and `HfsSystemFilesManager.asSerializedConfig`.
None.

Use try-with-resources when opening property files

---

hedera-node/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java
hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java

**NOTE:** I accidentally pushed commits from branch [`0913-M-StandardizeIaeUsage`](https://github.com/hashgraph/hedera-services/tree/0913-M-StandardizeIaeUsage) here, my bad. 🤕 
- Closes #922
Replace a "bespoke" `finally` construct in `HederaTokenStore` and `HederaScheduleStore` with the language construct.
None.

Remove bespoke finally constructs in store implementations

---

.circleci/config.yml

As the folder that is storing results for Migration test is changed to `5N_1C` on `swirlds-platform-regression`, but the sync command is not changed in services side, Migration test results are not synced. Modified the folder name to be synced.
Related to https://github.com/swirlds/swirlds-platform-regression/issues/810

Fix failing migration test sync

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java

Closes #985
Increase the throttle for crypto
None.
None.
Runs of `Crypto-Restart-Performance-Testnet-10k-46m` that passed both in `release/0.11` and `master`
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611087172069100
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611092019070800

Bump up crypto throttle to match with dev app properties

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleDiskFsTest.java

Closes #955
Changed the log level from Error to warn and only print out the stack trace when debug is enabled. I checked all the current callers of this method. As of now, this change shouldn't cause any issue.
This method is at low level. When anything happens, it's difficult for this method to decide whether the situation should be treated as error or not.  Its callers shall have better context to decide what it should be.  So an alternative solution is to re-throw this exception and let its called to handle it.
None.

Change the log level from Error to warn.

---

hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleCreateUsage.java
hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsage.java
hapi-fees/src/main/java/com/hedera/services/usage/schedule/entities/ScheduleEntitySizes.java
hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleCreateUsageTest.java
hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsageTest.java
hapi-fees/src/test/java/com/hedera/services/usage/schedule/entities/ScheduleEntitySizesTest.java
hapi-proto/src/main/proto/ScheduleCreate.proto
hapi-proto/src/main/proto/ScheduleGetInfo.proto
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
hedera-node/src/main/java/com/hedera/services/store/schedule/ExceptionalScheduleStore.java
hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java
hedera-node/src/main/java/com/hedera/services/store/schedule/ScheduleStore.java
hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduleTest.java
hedera-node/src/test/java/com/hedera/services/store/schedule/ExceptionalScheduleStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogicTest.java

Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Closes [#963](https://github.com/hashgraph/hedera-services/issues/963)
- Adds new memo field in the `MerkleSchedule`
- Adds `memo` to proto `ScheduleCreate` and `ScheduleGetInfo`
None.

Feature: Scheduled TX - Add memo field

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleDiskFsTest.java

**Related issue(s):**
Closes #955 
The original changes was already merged to `master` branch. Neeha suggests to also merge the fix to `0.11.0` release branch as well.
1. Short-term solution to change the log message level from `error` to `warn` to avoid migration test failure;
None.

00955 d file 150 for migration test (merge to 0.11.0 release branch)

---

hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java

Closes #988
*Performance results*
Crypto-Basic-Performance-10k-46m:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611160463074600
Crypto-Restart-1.5k-10m:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611179508083700
Misc-UpdateNode-1-6m   against 0.8.2
Misc-Update-1-5m  against 0.8.2
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611334794022600
Crypto-Restart-1.5k-10m against 0.8.2
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611339739025000

00988: Removes extra QueueThread from RecordStreamManager

---

.circleci/config.yml

Closes #977 
1. Removed all AWS workflows
2. Removed `test-name` and used `workflow-name`+`.json`
3. Disabled Hotspot and Random tests as the PR in regression is yet to be merged
4. The configuration to disable `continuous-integration-gcp` is already done in previous PR
Ran one test to check if the changes are valid : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1611788506013500

Simplify CircleCI config

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java

Closes #1008 
Allow to use single payer which is the sender while testing with public testnet state
Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611699444050000

Fix HCS-Restart-Performance-Testnet-10k-46m

---

hapi-proto/HAPI.html
hapi-proto/src/main/proto/ResponseCode.proto
hapi-proto/src/main/proto/TokenUpdate.proto

Reflect that name/symbol limits are now in terms of UTF-8 bytes; reference `tokens.maxPerAccount` in `TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED` doc.

Small HTS doc corrections

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java

Closes #1051 
Fixed the JSON names to match the names merged in `swirlds-platform-regression` for Hotspot and Random tests.
Most of the tests started failing as initialBalance is increased and is being used for most of the tests, that gave `INSUFFICIENT_PAYER_BALANCE`

Fix JSON names for Hotspot and Random tests 

---

hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleCreateUsage.java
hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleSignUsage.java
hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleTxnUsage.java
hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleSignUsageTest.java
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleSignResourceUsage.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleSignResourceUsageTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java

Closes #None
* Fix schedule sig `rbs` - instead of using `scheduedTxExpirationTimeSecs` from global props, multiply it by `expiry - txValidStart`.
None.

Scheduled Transactions: Fix Sign op usage

---

pom.xml

Temporary fix for schedule protos in `com.hedera.hashgraph:hedera-protobuf-java-api:0.12.0-SNAPSHOT` getting out-of-sync with `master`.

Use temporary snapshot repo awaiting schedule-develop merge

---

test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java

Closes #1057
- Use GENESIS or default payer because system accounts have zero initial balance. #1020
- Turn off some log errors that were added in #893, until HAPIClientValidator needs them and knows how to deal with them.
Passing all reconnect tests
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612582160219000

Fix reconnect tests

---

.env
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/main/java/com/hedera/services/keys/InHandleActivationHelper.java
hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountBalanceAnswer.java
hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/RawTokenRelationship.java
hedera-node/src/main/resources/semantic-version.properties
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountBalanceAnswerTest.java
hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountInfoAnswerTest.java
hedera-node/src/test/java/com/hedera/services/sigs/factories/ScheduleBodySigningSigFactoryTest.java
hedera-node/src/test/java/com/hedera/services/sigs/factories/SigFactoryCreatorTest.java
hedera-node/src/test/java/com/hedera/services/sigs/sourcing/ScheduledPubKeyToSigBytesTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/RawTokenRelationshipTest.java
hedera-node/src/test/java/com/hedera/services/throttling/BucketThrottlingTest.java
hedera-node/src/test/java/com/hedera/test/utils/IdUtils.java
pom.xml
test-clients/devops-utils/validation-scenarios/config.yml
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/ExpectedTokenRel.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CreateAndUpdateOps.java
test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
test-clients/src/main/resource/spec-default.properties

Closes #1075
- Set the `decimals` field in `TokenBalance` and `TokenRelationship` messages returned from queries.
-  **NOTE:** this PR also includes some unrelated EET changes helpful for recording cost snapshots in crypto/file mutations. 
Nothing breaking; this information will simply be available in queries now.

Include token decimals in query responses

---

.circleci/config.yml

Until we understand the explosion of spot nodes in `us-east1`, ignore the `continuous-integration` workflow on all branches.

Ignore the AWS continuous-integration workflow 

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/state/exports/BalancesExporter.java
hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/sigs/factories/SigFactoryCreatorTest.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenMiscOps.java

- Closes #1092
- Revert to using `TokenBalances` proto type in exporting Base64-encoded token balances in CSV format.
- Eliminate duplication in `SignedStateBalancesExporter`.
- Add unit test to ensure `version:2` CSV token balances remain backward-compatible in future.
Fixes failure of `0.12.0-rc.1` balances CSV to be backward-compatible with `0.11.0` code.

Make SignedStateBalancesExporter CSV output backward-compatible

---

hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

- Closes #1096
- In `HederaTokenStore.exists` and `HederaScheduleStore.exists`, only test id against pending id if `isPendingCreation() == true`.
- Add various EET specs using id `0.0.0`.
- Uncomment suppressed `throw` statements in `HapiTxnOp`.

Only check existence against pending id if appropriate

---

test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

Use an actually invalid signature in `CryptoUpdateSuite.updateFailsIfMissingSigs`

Fix misconfiured test in CryptoUpdateSuite

---

test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java

When `ValidationScenarios` was first written, there was no `DEFAULT_PAYER`/`GENESIS` distinction.
This resulted in several incorrect uses of `GENESIS` that just surfaced in a DevOps migration test.

Fix incorrect legacy use of GENESIS in ValidationScenarios

---

test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/RunLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoCreatePerfSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/FileContractMemoPerfSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/FileUpdateLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/MixedOpsMemoPerfSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenCreatePerfSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

Closes #1071 
Added a new performance test that does cryptoCreate, cryptoUpdate, TokenCreate, TokenUpdate, FileCreate, FileUpdate transactions with entityMemo set. 
Use memoLength from CI properties map in the load test to vary the length of the memo set to the entities. 
None.

Add perf suite for testing entity memos

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
hedera-node/src/main/java/com/hedera/services/store/Store.java
hedera-node/src/main/java/com/hedera/services/store/schedule/ContentAddressableSchedule.java
hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/ServicesContextTest.java
hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java

- Closes #1105
- Closes #1107
- Add a `Store.rebuildViews()` method.
- Add a `ServicesContext.rebuildStoreViewsIfPresent()` method to be called from `ServicesState.initializeContext()`; dispatch `tokenStore.rebuildViews()` and `scheduleStore.rebuildViews()` from there.
- In `HederaTokenStore`, rebuild the `Map<AccountID, Set<TokenID>>` view of known treasuries.
- In `HederaScheduleStore`, rebuild the `Map<ContentAddressableSchedule, ScheduleID>` view of existing scheduled txns.

Rebuild *Store views upon reconnect

---

test-clients/src/main/java/com/hedera/services/bdd/suites/regression/RegressionProviderFactory.java
test-clients/src/main/java/com/hedera/services/bdd/suites/regression/UmbrellaRedux.java

Closes #1128 
Slack link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614651796208500
1. Modified the RegressionProviderFactory class to take care of the missing bias number cases;
2. Also added the client re-try waiting time to avoid server occasionally down or start up later than test client cases;
None.

Fix daily perf failure of UmbrellaRedux for File and Contract.

---

hedera-node/src/main/java/com/hedera/services/fees/charging/ItemizableFeeCharging.java
hedera-node/src/main/java/com/hedera/services/fees/charging/TxnFeeChargingPolicy.java
hedera-node/src/main/java/com/hedera/services/legacy/services/state/AwareProcessLogic.java
hedera-node/src/test/java/com/hedera/services/fees/charging/ItemizableFeeChargingTest.java
hedera-node/src/test/java/com/hedera/services/fees/charging/TxnFeeChargingPolicyTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransferListAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java

- Closes #1136
- Respect only the `submittingNode` account in `ItemizableFeeCharging` (allow leaving `TransactionBody.nodeAccountID` empty).
- Charge the payer of a triggered txn only the service fee via a new `TxnFeeChargingPolicy.applyForTriggered()` policy.
Node and network fees will not be charged to scheduled txns.

Only charge service fees to payer for a triggered txn

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransfersLoadProvider.java

Closes #1149
1. Mainly to let the freeze request to start later.
None.

Make freeze start time longer to give all client nodes chances

---

test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java

Closes #1151 and platform regression #914
1. Added a message to indicate SuiteRunner has finished running all test suites;
None.

Add the test client finish message.

---

test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileUpdate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/BigRecordSpec.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CostOfEverythingSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CreateAndUpdateOps.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/ReadyToRunScheduledXfersLoad.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenRelStatusChanges.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransferBasicLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

Closes #1161
Made the test more robust to handle price fluctuation, by:
- Remove hardcoded fee to be expected https://github.com/hashgraph/hedera-services/blob/e050405b3698faeccd9d845ed9cf3138d399a101/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java#L80
- During reconnect, update exchange rates to have significantly high new fees in hbars
- Provide high, but not high enough fee (100 hbars) for requests with expected `INSUFFICIENT_TX_FEE` for new fees and provide high enough fee (1 mil hbars) for expected passing requests
- Some other minor clean-ups
**Passing tests**:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1615398086324300 …

Fix reconnect test

---

test-clients/src/main/java/com/hedera/services/bdd/suites/misc/ReviewMainnetEntities.java
test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AddWellKnownEntities.java
test-clients/src/main/java/com/hedera/services/yahcli/suites/CostOfEveryThingSuite.java

PR #1134, which used the old variable `A_HUNDRED_HBARS`, was merged before PR #1162. Change to using the new `ONE_HUNDRED_HBARS` variable.

Fix build after renaming a variable

---

.circleci/config.yml

Closes #1169
Modified 6N_6C performance tests to run on Wednesday and Sunday
15N_15C performance tests to run on Saturday
20N_20C MixedOps performance test to run on Wednesday in fixed in PR https://github.com/hashgraph/hedera-services/pull/1139

Modify frequency of performance tests on master

---

hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java

Closes #1142 
1. changed the account balances export timeline;
2. Also wiped out the timestamp field for client account balances .pb file.
None.

Change the account balances export timeline.

---

test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/ChunkingSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/SubmitMessageSuite.java

Address #1198 
Couldn't reproduce the StatsValidator error in local runs. 
Check-in the changes to reduce the failure rate.
Test run reports links: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1616710312046800, https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1616708815046300.
1. Added retry pre-check to minimize the failures caused by server occasional BUSY response code.
None.

Addressing Misc-Basic-1-20m test failures

---

docs/hip-16.md

**Summary of changes**
- Consistently differentiate between _deletion_ and _removal_ of an entity. (That is, entities marked deleted are not removed until they expire.)
- Other minor wording and style suggestions.

Differentiate entity deletion and removal

---

.circleci/config.yml

Closes #1207 
Currently logs of Continuous Integration are not uploaded to google storage. This doesn't allow developers to see the logs if there is any error.
Modified to store logs of `continuous-integration-gcp`  to GS.
One of the CI run with results folder link : https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1617074380015200
**NOTE:** The branch checked out in regression will be reverted before merge, once the [PR](https://github.com/swirlds/swirlds-platform-regression/pull/951/files) in regression is merged. 
Space changes are necessary as the path for results folder breaks if there is any space in the path.

Store logs of CI to GS

---

hedera-node/src/main/java/com/hedera/services/state/forensics/IssListener.java

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>
Ensure a missing blob doesn't prevent dumping the storage FCM.

Abbreviate the storage FCM when dumped after ISS

---

.circleci/config.yml
hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java

Closes #1198
Test links for account balance validation: 
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1617144468089900
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1617642058166000
Test link for 15N NetDelay test: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1617298643138200
Opened an issue: https://github.com/hashgraph/hedera-services/issues/1229 to track the possible failure of the account balances file is scheduled to export off of the epoch export period boundary. 
1. Added account balances validation JRS  as a separate workflow; 
2. Some minor changes to fix occasional failure for client account balances validation;
3. Added 15-node NetDelay JRS workflow;
None.

01198 d misc basic jrs failure

---

.circleci/config.yml
hedera-node/src/main/java/com/hedera/services/grpc/controllers/ConsensusController.java
hedera-node/src/test/java/com/hedera/services/grpc/controllers/ConsensusControllerTest.java

Closes #1243
1. Fixed the typo of ConsensusController;
2. Also renamed the NetDelay JRS to weekly appropriately;
None.

Fix the typo for getTopicInfo

---

hedera-node/pom.xml

- Exclude unneeded transitive dependencies from the `org.ethereum` group.
- Remove the `https://dl.bintray.com/ethereum/maven/` repository, which will be shortly unavailable in any case.

Exclude unneeded org.ethereum dependencies, remove Ethereum bintray repository

---

hedera-node/src/main/resources/throttles-dev.json
test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ThrottleDefValidationSuite.java
test-clients/src/main/resource/testSystemFiles/throttles-dev.json

MixedOps Reconnect test failed because throttle values for dev are smaller and the accounts, topics and files expected to be created doesn't exist during `MixedValidationsAfterReconnect`
Closes #1247 
Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618264231330000

Fix MixedOps Reconnect test

---

hedera-node/configuration/preprod/api-permission.properties

Remove whitespace from the end of the `schedule*` ops in _configuration/preprod-api-permission.properties_
Allow DevOps to use this config for deployment with schedule ops enabled.

Strip whitespace from preprod/api-permission.properties

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java

Closes #1269
1. Added defensives to prevent test failure due to server node's failure to create accounts. 
None.

Add checks to handle situations when server not able to create accounts.

---

.circleci/config.yml

Since JRS doesn't have a default _api-permissions.properties_, we need to use `-PdevSetup` when building for CI/regression jobs.

Add -PdevSetup in CircleCI config

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java

Address issue #1295
slack link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619105926454600
summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619107593456300
1. Changed to match the registry names;
None.

Fix the mistake registry accounts not matching.

---

hedera-node/src/main/resources/throttles.json

- Increase burst periods to ensure node-level capacity for all ops w/ network sizes up to 30 nodes
- Limit `ScheduleSign` to 100 tps via a dedicated throttle group in the `ThroughputLimits` bucket.

Correct default throttles packaged in JAR

---

.circleci/config.yml

Closes #1268 and #1265.
1. Add the 6-node perf regression for HTS which seems to be missing;
The changes that 'fix' these issues are on platform regression side.
Also opened issue https://github.com/hashgraph/hedera-services/issues/1290 to track why TPSs for 6-node random perf regression tests (Crypto, HCS, and HTS) can't stay on 10K. 
https://github.com/hashgraph/hedera-services/issues/1290
None.

01268 d 6 n perf platform not active error

---

hapi-fees/pom.xml
hapi-utils/pom.xml
hedera-node/pom.xml
hedera-node/src/main/resources/throttles.json
pom.xml
test-clients/pom.xml

Update default _throttles.json_ to have burst periods appropriate for 20+ node networks and a `ScheduleSign` 100tps limit

Release 0132 branch

---

hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java

Closes #1337
Test slack link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619738364053600
Summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619738408054000
1. Change the logic to allow `balances.exportPeriodSecs`  to be retrieved every time.
NOTE: This allows the user to change the `balances.exportPeriodSecs` in the middle of test, which may cause issues for account balances export.
None.

Need to get the export period every time to pick latest value

---

hedera-node/pom.xml
hedera-node/src/main/java/com/hedera/services/context/properties/SemanticVersions.java
hedera-node/src/main/resources/semantic-version.properties
hedera-node/src/test/java/com/hedera/services/context/properties/SemanticVersionsTest.java
hedera-node/src/test/resources/frozen-semantic-version.properties
hedera-node/src/test/resources/frozenVersion.properties
pom.xml
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetVersionInfo.java
test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java

- Closes #1188
- Replace the hard-coded HAPI and Services semvers in [_hedera-node/src/main/resources/_](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/resources/semantic-version.properties) with the appropriate Maven properties (`hapi-proto.version` and `project.version`, respectively).
- Update the _hedera-node/pom.xml_ to filter resources.
- Refactor the `SemanticVersions` resource loader utility to understand the (optional) pre-release version and build metadata fields from the [semver spec](https://semver.org/#spec-item-9).
* We need the full spec to capture our tag name conventions.
The semantic versions returned by `getVersionInfo` will automatically be set to the versions that …

Automate setting Services and HAPI semvers in Maven build 

---

hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleExecutor.java
hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleExecutorTest.java

Signed-off-by: abhishek-hedera <abhishek.pandey@hedera.com>
Closes #<[1374](https://github.com/hashgraph/hedera-services/issues/1374)>
Modified `ScheduleExecutor` and `ScheduleExecutorTest` for `IllegalArgumentException` check instead of `NullPointerException` check with the use of @NotNull annotation.
None.

fix for ScheduleExecutorTest

---

.circleci/config.yml

Closes #1381
1. Disable daily-aws-summary job.
None.

Disable daily AWS summary job.

---

test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/RunLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/PerfTestLoadSettings.java

1. Replaced the hard-coded export period value with one that can be controlled by JRS test configuration;
2. Added one parameter to control the export of the client side exporting of account balances;
Passed slack links: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620742129179700,
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620745586180200
Latest run link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620754060183800 
None.

Add parameters to avoid hard-coded value

---

.circleci/config.yml

Closes #1386
1. Changed the 6-node transaction perf tests to run on daily basis.
None.

Run 6-node perf tests on a daily basis.

---

.dockerignore
pom.xml

Closes #1378 
Updates the version of Jacoco in use. Does not have any impact on runtime.
None.
- [N/A] Javadoc
- [N/A] HAPI protobuf comments
- [N/A] README

01378-master-UpgradeJacoco

---

.circleci/config.yml

Remove obsolete steps from `build-artifact` job that used S3.

Remove unneeded s3 upload from CI

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoRenewal.java
hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/src/test/java/com/hedera/services/state/expiry/EntityAutoRenewalTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java

- Closes #1389
Summarize auto-renew activity per consensus second in two counts: `entitiesScannedThisSecond` and `entitiesTouchedThisSecond`.

Include autorenew per-second summary counts in network ctx

---

.circleci/config.yml

Closes #1396 
Reconnect tests using reconnect window are added in PR https://github.com/swirlds/swirlds-platform-regression/pull/1096 .
**This will be merged only after merging official `0.9.4-alpha.2` sdk from platform.**
A bug related to schedules expiry is fixed in [commit](https://github.com/hashgraph/hedera-services/pull/1398/commits/c88d68166e86165f8d28db5ee022355e61e47b71)
Passed tests:
- [AllProtectedFilesUpdate-NDReconnect-1-12m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1621010795272200) FAILED 
- [MixedOps-NIReconnectFail-1.5k-10m.json ](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1621026899305200) PASSED, …

Add Correctness tests to nightly regression

---

docs/dev/testnet-rekey.md
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/FreezeRekeyedState.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/RekeySavedStateTreasury.java

Add warnings to the re-key README and avoid a EET helper failure mode by splitting into two suites.

Clarify re-key readme and split EET helper into two suites

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java

Closes #1404
Ensure the `ExpiryManager` has access to the latest mutable `schedules` FCM when rebuilding its expiration queue after a reconnect.

Inject schedules FCM supplier to ExpiryManager

---

hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java

Signed-off-by: abhishek-hedera <abhishek.pandey@hedera.com>
Closes #1429 
Modified `SignedStateBalancesExporter` and `SignedStateBalancesExporterTest` to use string concatenation instead of `String.format` for basic string concatenations.

1429 modified SignedStateBalancesExporter for write performance improvement

---

hedera-node/src/main/java/com/hedera/services/fees/TxnRateFeeMultiplierSource.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/src/test/java/com/hedera/services/fees/TxnRateFeeMultiplierSourceTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java

- Make `MerkleNetworkContext.deserialize` null-safe.
- Return a `clone` from`TxnRateFeeMultiplierSource.congestionLevelStarts()` so that fast-copies of `MerkleNetworkContext` won't share the same array.
* If the array _is_ shared, and the congestion level changes on one node but not another while Platform is serializing a fast-copy of `MerkleNetworkContext`, we will get a transient ISS.

Add MerkleNetworkContext.deserialize() null-safety and avoid transient ISS

---

hedera-node/src/main/java/com/hedera/services/records/TxnIdRecentHistory.java

Fix accessibility of `TxnIdRecentHistory.observe()` for new `ExpiryManagerTest` unit test.

Make TxnIdRecentHistory#observe public for ExpiryManagerTest

---

hapi-fees/src/main/java/com/hedera/services/usage/token/entities/TokenEntitySizes.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleUniqueToken.java
hedera-node/src/main/java/com/hedera/services/store/tokens/BaseTokenStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/common/CommonStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/common/CommonTokenStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/unique/OwnerIdentifier.java
hedera-node/src/main/java/com/hedera/services/store/tokens/unique/UniqueStore.java
hedera-node/src/main/java/com/hedera/services/store/tokens/unique/UniqueTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenMintTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/utils/invertible_fchashmap/FCInvertibleHashMap.java
hedera-node/src/main/java/com/hedera/services/utils/invertible_fchashmap/FCInvertibleHashMapIterator.java
hedera-node/src/main/java/com/hedera/services/utils/invertible_fchashmap/Identifiable.java
hedera-node/src/main/java/com/hedera/services/utils/invertible_fchashmap/InverseKey.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/ServicesContextTest.java
hedera-node/src/test/java/com/hedera/services/ledger/BaseHederaLedgerTest.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerLiveTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleUniqueTokenIdTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/BaseTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/unique/OwnerIdentifierTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/unique/UniqueTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java

Added ```UniqueTokenStore```  for working with unique tokens.
Added ```CommonTokenStore``` which has functionallity specific for common tokens.
Refactored ```BaseTokenStore``` to an abstract class, holding common functionality for both types of tokens.
Provided basic ```mint``` operation for unique tokens.
Added ```OwnerIdentifier``` in order to work with the invertible map
Added alpha implementation of``` FCInvertibleHashMap```, used in the unique store.
None.
**Notes**:
This will be done in a future PR(s):
- Ledger transfer for unique tokens.
- State transition for N unique tokens.
- Precheck validation.
- Update Invertible map when ready.

Feat/token seggregation internal (#231)

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SchedulesExpiryDuringReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensStateAfterReconnect.java

Closes #1506 
Related regression PR : https://github.com/swirlds/swirlds-platform-regression/pull/1152
Reconnect correctness tests failed as the nodes are killed before saving state, and reconnect is not supported when node starts from genesis. To solve this issue added some transactions before attempting the correctness tests. 
Other validator failures will be resolved with `0.15.0-alpha.2` sdk
Passed tests:
1. `AllProtectedFilesUpdate-NDReconnect-1-12m` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622750250246300
2. `TransactionHistory-NDReconnect-1-12m` :https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622779608259700
3. `ScheduleExpiry-NDReconnect-1-12m` : …

Fix Reconnect correctness tests

---

hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccountTokens.java
hedera-node/src/test/java/com/hedera/services/ledger/properties/MerkleAccountPropertyTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountTokensTest.java

- Closes #1542
▶️  &nbsp; [Passing `TokenValidate-NIReconnect-1-16m`](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1623078907385800)
▶️  &nbsp; [Passing `TokenValidate-NDReconnect-1-16m`](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1623080057386200)
- Temporary fix of `AccountProperty.TOKENS` getter/setter to match the new `FCMap.getForModify()` paradigm used by `BackingAccounts`, in which the `getForModify()` call to each mutated account is delayed until `TransactionalLedger.commit()` is called.
- The `MerkleAccountTokens.tmpNonMerkleCopy()` will no longer be necessary when then `TokenAssociate`/`TokenDissociate` refactor are complete and ported from `master`.

Fix AccountProperty.TOKENS getter/setter impls for new G4M paradigm

---

hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccount.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccountState.java
hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
hedera-node/src/test/java/com/hedera/services/state/exports/ToStringAccountsExporterTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountStateTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountTest.java
hedera-node/src/test/java/com/hedera/test/factories/accounts/MerkleAccountFactory.java

Closes #NONE
Added `nftsOwned` property in `MerkleAccountState` in order to extend the information in `CryptoGetInfo` query to show basic information for the number of nfts that a certain account owns. Updated unit tests.
None.

Crypto Get Info Modification (#260)

---

hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleUniqueToken.java
hedera-node/src/main/java/com/hedera/services/store/tokens/unique/UniqueTokenStore.java
hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleUniqueTokenTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/unique/UniqueTokenStoreTest.java

Closes #NONE
In recent discussions a refactoring of unique merkle token's memo string to metadata byte array was agreed on. I made the change and updated the correlating unit tests.
None.

NFT: Memo to Metadata

---

.circleci/config.yml

Slack channel was changed to `hedera-regression-test` by mistake when the master-plus-sdk-0.15.0 branch is merged. Changed back to `hedera-regression` for nightly results

Update channel for Nightly regression results

---

hedera-node/src/test/java/com/hedera/test/utils/AccountIDConverter.java
hedera-node/src/test/java/com/hedera/test/utils/ByteArrayConverter.java
hedera-node/src/test/java/com/hedera/test/utils/ConverterUtils.java
hedera-node/src/test/java/com/hedera/test/utils/DurationConverter.java
hedera-node/src/test/java/com/hedera/test/utils/Ed25519KeyConverter.java
hedera-node/src/test/java/com/hedera/test/utils/EntityIdConverter.java
hedera-node/src/test/java/com/hedera/test/utils/InstantConverter.java
hedera-node/src/test/java/com/hedera/test/utils/JEd25519KeyConverter.java
hedera-node/src/test/java/com/hedera/test/utils/RichInstantConverter.java
hedera-node/src/test/java/com/hedera/test/utils/TopicIDConverter.java
hedera-node/src/test/java/com/hedera/test/utils/TxnUtils.java

Signed-off-by: abhishek-hedera <abhishek.pandey@hedera.com>
Closes #1488 
Created a `ConverterUtils` class to reuse checks and string split operation being used by the converters.
None.

Refactoring converter utils to reuse checks

---

hedera-node/src/test/java/com/hedera/services/txns/ExpandHandleSpanTest.java

DevOps reported the `ExpandHandleSpanTest` tests calling `Thread.sleep()` are unstable in their Jenkins build environment. 
These tests have very limited value-add, so all things considered we should delete them.

Remove sleep-dependent unit tests that are unstable in DevOps builds

---

hapi-fees/src/main/java/com/hedera/services/calc/OverflowCheckingCalc.java
hapi-fees/src/test/java/com/hedera/services/calc/OverflowCheckingCalcTest.java

- Closes #1607
Use the min/max values from the fee schedule to constrain the network, node, and service fees computed by `OverflowCheckingCalc`.

Constrain component prices by the min/max in fee schedule

---

pom.xml

Use SDK 0.15.1 in preparation for tagging `v0.15.1`.

Roll to SDK 0.15.1 for v0.15.1 tag

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/CustomFee.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/CustomFeeTest.java
pom.xml

- Closes #1591 
**Changes:**
- Update the `MerkleToken` type with (2) a `List<CustomFee>` for the custom fee schedule, if any; and a `customFeeKey` to permit updates to the custom fee schedule.
- Add a static from-gRPC factory to `CustomFee`.

Add a List<CustomFee> to MerkleToken

---

test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

1654 EET for TokenUpdate with CustomFees

---

hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfers.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshal.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMeta.java
hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/CustomFee.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/EntityId.java
hedera-node/src/main/java/com/hedera/services/store/models/Id.java
hedera-node/src/test/java/com/hedera/services/ledger/BalanceChangeTest.java
hedera-node/src/test/java/com/hedera/services/ledger/ImpliedTransfersMarshalTest.java
hedera-node/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/span/SpanMapManagerTest.java
hedera-node/src/test/java/com/hedera/test/utils/IdUtils.java

`BalanceChange` class is modified to use `EntityId` instead of `Id` as it was previously planned to be used in `ExpirableTransactionRecord`. Since we have created a new class with `AssessedCustomFee` , reverting `Id` to beused in `BalanceChange`

Update BalanceChange to use Id instead of EntityId

---

hedera-node/src/main/java/com/hedera/services/context/AwareTransactionContext.java
hedera-node/src/main/java/com/hedera/services/context/TransactionContext.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/context/AwareTransactionContextTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogicTest.java

- Expected to close #1669
Reset `assessedCustomFees` in `AwareTransactionContext.resetFor()`.

Always reset assessedCustomFees to null in AwareTransactionContext

---

hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml
hedera-node/log4j2.xml

Closes #1680 
- Refactor filters by moving out of the global space and into a Logger space
- Define a new com.swirlds logger to contain the filters
- Remove filters from Root logger
- Change Root logger level to FATAL as a last resort catch-all

01680: Fix log4j2 issue that resulted in empty hgcaa.log file

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/MixedFileOpsLoadTest.java

Closes #1632
Slack report link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1624900151228000
1. In the quasi perf test setup, it's possible to observe some requests that not be answered as SUCCESS. 
None.

Add UNKNOWN in acceptable status.

---

hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryEvent.java
hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
hedera-node/src/main/java/com/hedera/services/state/expiry/MonotonicFullQueueExpiries.java
hedera-node/src/main/java/com/hedera/services/state/expiry/PriorityQueueExpiries.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryEventTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/PriorityQueueExpiriesTest.java

- Closes #1709
- Use a `Comparator` for the `PriorityQueue` in `PriorityQueueExpiries` to guarantee a unique total order on the `ExpiryEvent`s in the queue.

Use ExpiryEvent id in PriorityQueue ordering 

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/state/exports/BalancesExporter.java
hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java

**Note to reviewer:** I don't immediately see why Codecov is showing missing coverage, but if anyone sees why, lmk and I'll add some tests. 
- Closes #1686
- In an NI reconnect scenario, the Platform may call `ServicesMain.newSignedState()` with a signed state that never received a `ServicesState.init()` call.
* For such a signed state, the `ServicesState#nodeId` field will be `null`.
- Instead of relying on this field, just use `ctx.id()` in `ServicesMain.newSignedState()` to get the node id.

Don't rely on the nodeId being set in a signed state

---

hedera-node/src/main/java/com/hedera/services/legacy/crypto/SignatureStatus.java
hedera-node/src/main/java/com/hedera/services/legacy/crypto/SignatureStatusCode.java
hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigStatusOrderResultFactory.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigningOrderResultFactory.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/HederaSigningOrderTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SigStatusOrderResultFactoryTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenCreateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/txns/TokenCreateFactory.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

- Addresses first three bullets in #1699
- Require any fixed fee collector with `receiverSigRequired=true` to sign a `TokenCreate`.
- Require any fractional fee collector to sign a `TokenCreate`.
- Automatically associate fractional fee collectors to the newly created token (exactly as is done for the treasury).

Enforce TokenCreate signing reqs; auto-associate fractional fee collectors

---

pom.xml

01715: Fail CI step/workflow on javadoc warnings

---

hedera-node/src/main/resources/throttles.json

Replace incorrect `TokenNftGetInfo` with `TokenGetNftInfo`.

Fix throttles.json resource function names

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

`ReconnectValidator` passed on MixedOps-NIReconnect-6k-28m [here](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625257704275700).
- The Platform `SyncCaller` always calls `copy()` on a signed state it receives from a neighbor during reconnect. 
- This signed state will _NOT_ have received a `ServicesState.init()` call, so its `FCOneToManyRelation`s will be `null`.
- `copy()` needs to handle this case.

Allow copy to be called on a signedState received during reconnect

---

hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/AwareFcfsUsagePricesTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java

**Changes**:
- Migrate prices from deprecated `TransactionFeeSchedule.feeData` into a `SubType -> FeeData` map at startup.
- On EET side, translate a downloaded 0.15.x fee schedule into a form usable by 0.16.0 EET clients.

01730 m infer default fee data from old json

---

test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java

**Issues**
- Expected to close #1745 and close #1746
**Summary of change**
- Don't `printStackTrace()` in `HapiSpecOperation` by default.

Stack trace shouldn't be printed by default'

---

test-clients/src/main/resource/testSystemFiles/artificial-limits-6N.json

The `ValidateCongestionPricingAfterReconnect` suite uses _test-clients/src/main/resource/artificial-limits-6N.json_ but the NFT operations weren't added.

Include nft ops in reconnect throttles JSON

---

.circleci/config.yml
hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
hedera-node/src/main/resources/bootstrap.properties
hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
hedera-node/src/test/resources/bootstrap/standard.properties

This PR changes the account balances export timing algorithm in order to minimize chances to skip exporting in low TPS environment. 
1. Changed the algorithm to anchor to export period boundary. It will now export account balances at earliest possible consensus time event even it's away from expected export boundary;
2. Changed the default export period to 15 mins;
3. Removed the export of .csv account balance files;
Fixes #1732
Slack summary for JRS results for JRS tests:  https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625723064314100
**Checklist**

Change export timing and remove .csv export.

---

test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java

This PR changes the aof(...) from generic to non-generic method. Seems like java has issue with casting in some special occasions.
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842058325100
Fixes #1782
Slack report link for passing test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842058325100
And summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842089325200
**Checklist**

Fix the type casting error of Java generics.

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/FcCustomFee.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/FcCustomFeeTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/test/factories/fees/CustomFeeBuilder.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenFeeScheduleUpdateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

Close #1810
- Used sentinel tokenId with tokenNum == 0
- Added CustomFeeBuilder to simplify test codes and remove lots of duplications
- Simplify TokenFeeScheduleUpdateTransitionLogic and its unit tests

01810: Support custom fixed fees token to be created/updated

---

docs/fees/custom-fees-characterization.md
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/CustomFeeMeta.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/CustomSchedulesManager.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfers.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshal.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMeta.java
hedera-node/src/main/java/com/hedera/services/txns/customfees/CustomFeeSchedules.java
hedera-node/src/main/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedules.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomFeeMetaTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomSchedulesManagerTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshalTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
hedera-node/src/test/java/com/hedera/services/txns/span/SpanMapManagerTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

Add two exemptions for custom fee charging:
1. A token treasury account is exempt from all custom fees for its token(s).
2. A fee collection account is exempt from the fees for which it is the collector.
- Closes #1830
- Closes #1798
- The main step is to include the token treasury in the `ImpliedTransfersMeta` via a new `CustomFeeMeta` wrapper object.
- EETs for exemptions are added in `TokenTransactSpecs`.

Custom fee exemptions

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

- Call `FCOneToManyRelation.release()` in the right`ServicesState` lifecycle callbacks.
- Fixes #1837

Call FCOTMR.release() at expected lifecycle points

---

hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
hedera-node/src/test/java/com/hedera/services/ledger/BaseHederaLedgerTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederLedgerTokenXfersTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederLedgerTokensTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerLiveTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerXfersTestHelper.java

This PR fixed the Sonarcloud code smell blocker issue.
Fixes #1864
The URL for the resulting sonar report: https://sonarcloud.io/project/issues?branch=branch-01864-D-fix-sonar-blocker-codesmells&id=com.hedera.hashgraph%3Ahedera-services&resolved=false&severities=BLOCKER
3 issues complaining no "assertion" statement in the test methods are filtered out from Sonarcloud rule, as those are not real unit tests. 
**Checklist**

Fix Sonarcloud code smell blocker issues.

---

hedera-node/src/test/java/com/hedera/services/store/tokens/views/TreasuryWildcardsUniqTokenViewTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/RandomOps.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenTransferBasicLoadTest.java

1. Add AnswerOnly retry prechecks to HapiQueryOp
2. Removed unnecessary token enablement which was supposed to be removed once we enable token operations by default.
Fixes #1885, #1880
Will share the JRS run results for test `HTS-Restart-Performance-Random-10k-61m` when run finishes. 
Test result : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1627407100408500
Summary : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1627407151408900
Also added a spec `RandomOps.getAccountInfoRetryWorks()` to validate retry on `AnswerOnlyPrecheck`s
**Checklist**

Add AnswerOnly retry precheck to HapiQueryOp

---

hedera-node/src/main/java/com/hedera/services/store/tokens/views/EmptyUniqTokenViewFactory.java
hedera-node/src/main/java/com/hedera/services/store/tokens/views/EmptyUniqueTokenView.java
hedera-node/src/main/java/com/hedera/services/store/tokens/views/UniqTokenViewFactory.java
hedera-node/src/test/java/com/hedera/services/store/tokens/views/EmptyUniqTokenViewFactoryTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/views/EmptyUniqueTokenViewTest.java
pom.xml

Close #1892
https://sonarcloud.io/dashboard?branch=license-header-code-smells&id=com.hedera.hashgraph%3Ahedera-services

01892: Ignore SonarCloud code smells in license header

---

hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java

- Wait until `MerkleNetworkContext.copy()` is called to deep-copy the `FunctionalityThrottling` usage snapshots and `FeeMultiplierSource` congestion-level starts into the `MerkleNetworkContext` about to be made immutable.
- Closes #1847

Only update NetworkContext state when FastCopyable.copy() called

---

hedera-node/src/main/resources/feeSchedules.json

Until https://github.com/hashgraph/hedera-services/issues/1910 is fixed, a `TokenMint/Burn/AccountWipe` against an invalid `TokenID` will expect `DEFAULT` prices to be available.
This PR adds `DEFAULT` prices for these operations that are the same as the `TOKEN_FUNGIBLE_COMMON` prices.

Add `DEFAULT` prices for `TokenMint/Burn/AccountWipe`

---

.github/dependabot.yml

The maven packages in hedera-services don't get updated very often and can contain bugs or vulnerabilities that might go unnoticed. We should make an effort to proactively keep them up to date. This PR enables automatic weekly [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates) version updates. Every week (usually Monday) 5 PRs dependency bump at a time will get created. You can then choose to merge them or close them.
**Checklist**

Enable weekly dependabot updates

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java

Revert the changes that were made assuming that start from saved state tests are only v0.16 and above in PR https://github.com/hashgraph/hedera-services/pull/1901
Fixes #1942 
version checks were removed form `MerkleNetworkContext#deserialize` which cause start from saved tests in JRS that use older states [ < v0.16.0] to fail.
Test Runs :
[MixedOps-NI-3NReconnect-6k-24m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628192689027600)
[HTS-Restart-Performance-Hotspot-10k-61m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628197737028300)
[HTS-Restart-Performance-Random-10k-61m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628201818028700)
**Checklist**

Revert the changes to `MerkleNetworkContext#deserialize`

---

pom.xml

Add dependency jackson-datatype-jsr310 to use java.time.Instant as jackson-databind v2.12 doesnt import it by default
Fixes #1954 
**Test Results**
[Crypto-Migration-Restart-Testnet-100-12](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628271735030600)
[Crypto-Restart-Testnet-200-18m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628273195031000)
[Crypto-Migration-Testnet-100-7m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628273990031400)
[Summary Link](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628274040031800)
**Checklist**

Add dependency jackson-datatype-jsr310

---

.circleci/config.yml
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/AdjustmentUtils.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/BalanceChangeManager.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/HbarFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/HtsFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/AdjustmentUtilsTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/BalanceChangeManagerTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HbarFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HtsFeeAssessorTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/NoFungibleTransfers.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/NoNftTransfers.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/SomeFungibleTransfers.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFees.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

- Closes #1925
- Closes #1825
- Add an [`exemptFromCustomFees` field](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java#L59) in `BalanceChange`.
- Pass the `chargingToken` id to the [`HtsFeeAssessor.assess()` method](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java#L83). 
- When the `chargingToken` matches an HTS fee `denom`, [set `exemptFromCustomFees=true`](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/grpc/marshalling/AdjustmentUtils.java#L …

Don't recurse when assessing self-denominated fixed fees 

---

hedera-node/pom.xml
pom.xml

Use the same `Jackson-databind` version as Platform by downgrading from `v2.12.4` to `v2.11.2`
Fixes #1954 
Moved the `Jackson-databind` dependency from `services` to `Hedera-node` and it is used just there.
Test Result:
[HTS-Restart-AccountBalances-2k-20m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628608618041700)
[Crypto-Migration-Testnet-100-7m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1628611721042200)
**Checklist**

Downgrade `Jackson-databind` from `v2.12.4` to `v2.11.2`

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/state/migration/Release0170Migration.java
hedera-node/src/test/java/com/hedera/services/state/migration/Release0170MigrationTest.java

We currently depend on `.addDeserializedChildren(List<MerkleNode> children, int version)` to be called to correctly trigger the [release 0.17.0 state migration](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/ServicesState.java#L154). 
This is a bug, since during a reconnect `.addDeserializedChildren()` is never called; so we should instead initialize `deserializedVersion = StateVersions.CURRENT_VERSION`.

Initialize `deserializedVersion = StateVersions.CURRENT_VERSION` instead of `-1`

---

hedera-node/src/main/java/com/hedera/services/state/submerkle/FcCustomFee.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/FcCustomFeeTest.java

- Fix `FcCustomFee.deserialize()` to only read the `netOfTransfers` flag from a release 0.17.x saved state.

Only deserialize `netOfTransfers` if reading from 0.17.x state

---

hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/HbarFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/HtsFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessor.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/FcAssessedCustomFee.java
hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HbarFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HtsFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersTest.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessorTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiringCreationsTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/FcAssessedCustomFeeTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/span/SpanMapManagerTest.java
hedera-node/src/test/java/com/hedera/test/utils/IdUtils.java
pom.xml

- In the `assessed_custom_fee`s record list, include the "effective payer(s)" for each fee; that is, the accounts whose final balances would have been higher in the absence of the fee.
- Fixes #1938

Add effective payers for assessed custom fees

---

hedera-node/src/main/java/com/hedera/services/store/models/Token.java
hedera-node/src/test/java/com/hedera/services/store/models/TokenTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java

**Summary of change**:
- Return `CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT` as expected when trying to wipe an NFT owned by its treasry.
- Closes #2012

Use`CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT` correctly

---

hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
hedera-node/src/main/java/com/hedera/services/store/tokens/views/UniqTokenViewsManager.java
hedera-node/src/main/resources/bootstrap.properties
hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerLiveTest.java
hedera-node/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/views/UniqTokenViewsManagerTest.java
hedera-node/src/test/resources/bootstrap/standard.properties

- Add static `tokens.nfts.areQueriesEnabled=true` that determines if the `UniqTokenViewsManager` actually maintains NFT views via FCOTMR; or just does no-ops for all methods.
- This property will likely be set to `false` for the `v0.17.1` tag on the release branch; but will be left `true` in `master`.
- Closes #2024

Provide FCOTMR toggle via static `tokens.nfts.areQueriesEnabled` property

---

hedera-node/src/main/resources/feeSchedules.json

Add non-default `TokenGetNftInfo` prices being used in the public fee estimator.

Add `TokenGetNftInfo` prices being used in public fee estimator

---

hedera-node/src/main/java/com/hedera/services/store/models/Account.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/ServicesAppTest.java
hedera-node/src/test/java/com/hedera/services/store/models/AccountTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogicTest.java
pom.xml
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

Added appropriate checks during `semanticCheck`[precheck] in CryptoCreateTransitionLogic and `sanityCheck` in CryptoUpdateTransitionLogic
Fixes #2093 
Ran a JRS CI regression locally 
Results : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1630517846014900
**Checklist**

Fail when max automatic associations requested is more than `token.maxPerAccount`

---

hedera-node/configuration/compose/node.properties
hedera-node/configuration/dev/application.properties
hedera-node/configuration/dev/node.properties
hedera-node/src/test/java/com/hedera/services/ServicesAppTest.java

**Problem**
This test fails when local environment already has `node.properties` with `hedera.recordStream.logDir` value set to `data/recordStreams` with `UnnecessaryStubbing` failure.
Modified such that:
Test only passes if the node.propertis file has `hedera.recordStream.logDir=data/recordStreams` or no `hedera.recordStream.logDir` at all

Fix test ServicesAppTest

---

hedera-node/src/main/java/com/hedera/services/state/submerkle/FractionalFeeSpec.java

In custom fee refactor, accidentally required fractional fee min/max to be strictly positive. 😞

Allow zero min/max for fractional fee spec

---

hedera-node/src/main/java/com/hedera/services/records/RecordCacheFactory.java
hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleDeleteTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/submission/TxnResponseHelper.java
hedera-node/src/test/java/com/hedera/services/records/RecordCacheFactoryTest.java
hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleDeleteTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/submission/TxnResponseHelperTest.java

This PR modifies `RecordCacheFactory`, `ScheduleDeleteTransitionLogic`, `TxnResponseHelper` to use their own loggers as described [here](https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false&rules=java%3AS3416&types=CODE_SMELL)
Fixes #2168 
Modified tests to add more coverage and made variables `final` as appropriate.
**Checklist**

Updating correct loggers for classes

---

hedera-node/src/main/java/com/hedera/services/txns/token/TokenBurnTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenMintTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenOpsValidator.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenWipeTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/stats/ExecutionTimeTrackerTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenOpsValidatorTest.java

Instead of passing a `List<Object> metadataList` to `TokenOpsValidator.validateTokenOpsWith()`, pass a `List<?>` and explicitly cast to `List<ByteString>` or `List<Long>` as appropriate.

Avoid unnecessary `ArrayList` creations

---

hedera-node/src/main/java/com/hedera/services/ledger/accounts/AccountCustomizer.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/HederaAccountCustomizer.java
hedera-node/src/main/java/com/hedera/services/ledger/properties/ChangeSummaryManager.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/AccountCustomizerTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/TestAccountCustomizer.java
hedera-node/src/test/java/com/hedera/services/ledger/properties/ChangeSummaryManagerTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogicTest.java

Resolves Sonar cloud [issue](https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false&rules=java%3AS1319&types=CODE_SMELL) and modifies `AccountCustomizer` and `ChangeSummaryManager` to use interface type instead of implementation type. This PR also modifies the variable types and tests to resolve other Sonar cloud smells.
Fixes #2167
**Checklist**

Replace implementation type with interface type

---

hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java
hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucketTest.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/CongestionMultipliers.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/CongestionMultipliersTest.java

This PR adds @ParameterizedTest to similar test functions that vary simply by arguments. Also modifies `ThrottleBucket` and `CongestionMultipliers` to make variables `final` and `private`.
Fixes #2169 
**Checklist**

Remove redundant tests to use @ParameterizedTest

---

hapi-fees/src/main/java/com/hedera/services/usage/contract/ContractGetInfoUsage.java
hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoGetInfoUsage.java
hapi-fees/src/test/java/com/hedera/services/usage/contract/ContractGetInfoUsageTest.java
hapi-fees/src/test/java/com/hedera/services/usage/crypto/CryptoGetInfoUsageTest.java
hapi-utils/src/main/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilder.java
hapi-utils/src/test/java/com/hedera/services/UtilsConstructorTest.java
hapi-utils/src/test/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilderTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java

This PR replaces the use of `Charset.forName()` with `StandardCharsets.UTF_8`. Also added `ConsensusServiceFeeBuilderTest` and modified variables, class and their modifiers.
Fixes #2166 
**Checklist**

Replace non-compliant charsets with StandardCharsets.UTF_8

---

run/gen-explicit-fee-schedules.py
test-clients/yahcli/run/test/local/sysfiles-down.sh
test-clients/yahcli/run/with-service-endpoints.py

Add two useful Python scripts:
1. _run/gen-explicit-fee-schedules.py_ to translate a Services _feeSchedules.json_ into the format used by the public pricing calculator.
2. _test-clients/yahcli/run/with-service-endpoints.py_ to augment a `(0.0.101, 0.0.102)` pair of deprecated-style yahcli JSON with the new `ServiceEndpoint` fields [as documented in the protobufs](https://hashgraph.github.io/hedera-protobufs/#proto.NodeAddress).

Commit two helper scripts 

---

hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java
hedera-node/src/main/java/com/hedera/services/sigs/metadata/DelegatingSigMetadataLookup.java
hedera-node/src/main/java/com/hedera/services/state/logic/AwareNodeDiligenceScreen.java
hedera-node/src/test/java/com/hedera/services/ledger/properties/MerkleAccountPropertyTest.java
hedera-node/src/test/java/com/hedera/services/sigs/metadata/DelegatingSigMetadataLookupTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/AwareNodeDiligenceScreenTest.java

This PR reorders modifiers in `AccountProperty`, `DelegatingSigMetadaLookup` and `AwareNodeDiligenceScreen`. Closes other code smells.
Fixes #2163 
**Checklist**

Reorder Modifiers

---

test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java

Fixes #2261 
Slack Results : 
[`GCP-Daily-Comp-NetError-4N-1C`](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1633017158222800)
[`GCP-Weekly-Services-Comp-NetDelay-15N-1C`](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1633020489223300)
**Checklist**

updated TopicUpdateSuite to use the right autorenew values

---

test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
test-clients/src/main/java/com/hedera/services/bdd/suites/records/DuplicateManagementTest.java

Before release 0.18.0, if a superuser account (`0.0.2` or `0.0.50`) paid for a query, the node would still submit its `CryptoTransfer` payment to the network.
Although query node payments are tiny (8-10 tinybars), all superuser operations are supposed to be free, so this behavior was not really correct.
In release 0.18.0 this was fixed, but the `DuplicateManagementTest.hasExpectedDuplicates()` EET spec was not updated with the new behavior.
This PR reworks the spec to pass.

Fix `DuplicateManagementTest.hasExpectedDuplicates()` for new node behavior

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/init/StateInitializationFlow.java
hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
hedera-node/src/main/java/com/hedera/services/state/logic/ReconnectListener.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSpecialFiles.java
hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/network/UpgradeActions.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/init/StateInitializationFlowTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/ReconnectListenerTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleSpecialFilesTest.java
hedera-node/src/test/java/com/hedera/services/txns/network/FreezeTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/network/UpgradeActionsTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/UpgradeSuite.java

1. Moves`UpgradeActions.catchUpOnMissedSideEffects()` from `ServicesState.init()` to `ReconnectCompleteListener.notify()`.
- This prevents triggering NMT side-effects based on a out-of-date saved state during `ServicesState.init()`.
- But `ServicesState.init()` is still responsible for nulling out the `DualState` freeze time when `freezeTime == lastFrozen`.
2. 🛑 Stops writing a "defensive" _freeze_aborted.mf_, even when reconnecting to a state without a prepared upgrade and a null `DualState.getFreezeTime()`.
3. Makes `FREEZE_ABORT` handling idempotent (i.e., stop resolving to `NO_FREEZE_IS_SCHEDULED ` if no freeze is scheduled or upgrade prepared; and always write the _freeze_aborted.mf_).
4. Fixes a bug in the `MerkleSpecialFiles` that didn't invalidate cached hashes. …

Move `UpgradeActions.catchUpOnMissedSideEffects()` into the `ReconnectCompleteListener`

---

test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileExpansionLoadProvider.java

- Adds the `FileExpansionLoadProvider` to serve as a client that puts maximum pressure on the hashing of blobs in state, by continually appending 5kb chunks to a rotating set of "targets".
- Closes #2374

Add blob hashing stress test

---

test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AccountAutoRenewalSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CryptoTransferThenFreezeTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenTransfersLoadProvider.java

Fixes #2398 , #2399 
Set a future time for all freeze txns as the starting time and 
make `FREEZE_ALREADY_SCHEDULED` as acceptable response in multi client scenario
Test Results:
[HTS-Restart-Performance-Hotspot-10k-61m](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1635872796042800) multiple clients will no longer fail with `FREEZE_ALREADY_SCHEDULED`
**Checklist**

FREEZE_ALREADY_SCHEDULED should be an acceptable response in multi client scenario

---

hedera-node/src/main/java/com/hedera/services/ServicesApp.java
hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/state/StateModule.java
hedera-node/src/main/java/com/hedera/services/state/logic/StateWriteToDiskListener.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/StateWriteToDiskListenerTest.java

Closes #2423 
1. Added `StateWriteToDiskListener` that listens to `StateWriteToDiskCompleteNotification`
2. Modified the `now_frozen.mf` marker to be written when the StateWriteToDiskCompleteNotification is received and state is frozen
Passed update Migration test

Write now_frozen marker based on StateWriteToDiskCompleteNotification

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/txns/prefetch/PrefetchProcessor.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/txns/prefetch/PrefetchProcessorTest.java
pom.xml

Fix use of `ExecutorService` when scheduling pre-fetch EVM bytecode task.
Fixes #2427 
In unit tests, kept one use of Thread.sleep() to add latency during task performing. This delay helps when trying to reproduce scenario when queue fills up. Without the delay, the performing of the tasks can be too quick and the queue empties before the check.
**Checklist**

Fixed issue with prefetch task submission (#2427)

---

hedera-node/src/main/java/com/hedera/services/stats/HapiOpCounters.java
hedera-node/src/main/java/com/hedera/services/stats/HapiOpSpeedometers.java
hedera-node/src/main/java/com/hedera/services/stats/ServicesStatsConfig.java
hedera-node/src/main/java/com/hedera/services/txns/submission/StructuralPrecheck.java
hedera-node/src/main/java/com/hedera/services/utils/SignedTxnAccessor.java
hedera-node/src/test/java/com/hedera/services/stats/HapiOpCountersTest.java
hedera-node/src/test/java/com/hedera/services/stats/HapiOpSpeedometersTest.java
hedera-node/src/test/java/com/hedera/services/txns/submission/StructuralPrecheckTest.java

Closes #2415 
1. Added a new counter `receivedDeprecatedTxns` to count number of transactions with deprecated fields are received
2. The counter is incremented in `StructuralPrecheck.assess`
Testing:
1. Added unit tests
2. Ran a test locally and submitted transactions with deprecated fields. Observed the change in stats in CSV files.

Track deprecated transactions received in precheck

---

hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
hedera-node/src/main/java/com/hedera/services/context/properties/ScreenedSysFileProps.java
hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java
hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
hedera-node/src/test/java/com/hedera/services/context/properties/ScreenedSysFilePropsTest.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/throttling/DeterministicThrottlingTest.java

- Add a [value screen for `contracts.maxRefundPercentOfGasLimit`](https://github.com/hashgraph/hedera-services/blob/ci-enabled-2373/hedera-node/src/main/java/com/hedera/services/context/properties/ScreenedSysFileProps.java#L103) so that values outside the range `[0, 100]` will be ignored for this property. 
- Split `GlobalDynamicPropertiesTest` methods up to get fewer assertions per method and fix Sonar code smell.
- Add unit tests to `DeterministicThrottling`, tweak log messages to improve readability.

Fix code smell, add value screen for `contracts.maxRefundPercentOfGasLimit` 

---

Dockerfile

`Unable to locate package openjdk-15-jdk` when building with ubuntu `22.04`

Revert #2442

---

hedera-node/src/main/java/com/hedera/services/ledger/LedgerCheck.java
hedera-node/src/main/java/com/hedera/services/ledger/MerkleAccountScopedCheck.java
hedera-node/src/main/java/com/hedera/services/ledger/TransactionalLedger.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/BackingStore.java
hedera-node/src/main/java/com/hedera/services/store/TopicStore.java
hedera-node/src/test/java/com/hedera/services/ledger/LedgerImplBackingStoreTest.java
hedera-node/src/test/java/com/hedera/services/ledger/MerkleAccountScopedCheckTest.java
hedera-node/src/test/java/com/hedera/services/ledger/TestAccountScopedCheck.java
hedera-node/src/test/java/com/hedera/services/ledger/TransactionalLedgerTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/HashMapTestAccounts.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/TestAccount.java
hedera-node/src/test/java/com/hedera/services/ledger/properties/TestAccountProperty.java
hedera-node/src/test/java/com/hedera/services/store/TopicStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/models/TopicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/MemoValidation.java

**Related issues**:
- Addresses #2411 
- Allows a `TransactionalLedger<K, P, A>` to be used as a `BackingStore<K, A>`. 
- This makes it easy to "wrap" one ledger in another, so that a `HederaWorldUpdater` implemented in terms of `TransactionLedger`s can execute HTS precompiles without affecting any `Updater`s below it in the call stack.
- ➡️ &nbsp;When a ledger is wrapping another ledger, it is far more efficient to get entity properties using the wrapped ledger's `get(K id, P property)` method instead of going through its `BackingStore.getRef(K id)` implementation.
* So this PR also updates the `LedgerCheck<A, P>` interface to have a `checkUsing()` variant that accepts a `Function<P, Object>` instead of an `A` instance.
* A ledger wrapping another ledger chooses this …

Extend `TransactionalLedger` to implement `BackingStore` 

---

README.md
pom.xml

Switch to non-alpha SDK in preparation for `0.20.0-rc.1` tag.

Use `0.20.0` SDK

---

hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCreateSuite.java

- Instead of checking payer balance in `EvmTxProcessor` using a model object from the `AccountStore` (which will not reflect fees _already charged to the account_), [uses an `EvmAccount` from the `WorldState.updater()`](https://github.com/hashgraph/hedera-services/blob/02490-M-FixContractPayerBalanceEdgeCase/hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java#L163).
* Since `WorldStateAccount`s are sourced from the `HederLedger`, they reflect fees already charged.
- Fixes #2490

Fix contract payer balance edge case

---

hedera-node/src/main/java/com/hedera/services/state/logic/ServicesTxnManager.java
hedera-node/src/main/java/com/hedera/services/txns/TransitionRunner.java
hedera-node/src/test/java/com/hedera/services/state/logic/ServicesTxnManagerTest.java

- Makes `ServicesTxnManager.process()` react to an internal `Exception` in a way that is logically consistent with the `TransitionRunner` reclaiming of all created ids.
- That is, on a process failure, calls `ledger.rollback()` instead of attempting `ledger.commit()` to collect fees.
- Fixes #2492

Make `ledger.rollback()` the default on a process failure

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
test-clients/src/main/java/com/hedera/services/yahcli/Yahcli.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/system/PrepareUpgradeCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
test-clients/src/main/java/com/hedera/services/yahcli/config/domain/NetConfig.java
test-clients/yahcli/README.md
test-clients/yahcli/config.yml
test-clients/yahcli/run/build.sh

**Related issues**
- Closes #2511 
- Make `defaultNodeAccount` take effect; also provide `-a/--node-account` options to override the target node account.
- Update yahcli _README_, reference tag `0.1.7`.
- Add a step to _.circleci/config.yml_ to ensure `run-continuous-integration-gcp` fails if an EET fails.

Update yahcli tag to `0.1.7`, fix `defaultNodeAccount`

---

hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JEd25519Key.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigRequirements.java
hedera-node/src/main/java/com/hedera/services/sigs/verification/PrecheckKeyReqs.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JEd25519KeyTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SigRequirementsTest.java
hedera-node/src/test/java/com/hedera/services/sigs/verification/PrecheckKeyReqsTest.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/ConsensusCreateTopicScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/ConsensusUpdateTopicScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/CryptoDeleteScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/CryptoUpdateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/ScheduleCreateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenAssociateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenCreateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenDissociateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenFeeScheduleUpdateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenUpdateScenarios.java

Skip the signature expansion of other party keys if the party matches the payer
Fixes #2287, #2291, #2292 
Currently we repeat the signature expansion of the payer if it is also involved in the transaction other than just paying for it. 
one Example : 
```
cryptoTransfer(
tinyBarsFromTo(sender, receiver , 1L))
.payingWith(sender)
``` 
we repeat for `sender` 
Added checks to avoid this.
**Checklist**

Avoid redundant signature expansions

---

test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
test-clients/src/main/java/com/hedera/services/yahcli/Yahcli.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/BalanceCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/RekeyCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/fees/FeeBasePriceCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigUtils.java
test-clients/yahcli/config.yml

Fixes #2512 
Now you can set the log level using -v --verbose option like this 
```
java -jar assets/yahcli.jar -n localhost -p 2 -v INFO fees list-base-prices all
```
levels you can set are WARN , INFO and DEBUG. You have to specify these string literals in the command line.
By default its WARN.
**Checklist**

Enhance YAHCLI to set log level

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java

Fix numHbar arg we use for assessing custom fees - in the context of a precompile it is always 0
Only add receiver/sender transfers to balance changes if they're present
Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>

HTS Precompile fixes

---

.circleci/config.yml
pom.xml

As `swirlds-platform` moved to JDK 17 , use the docker image that has `JDK 17` for the `hedera-services` CI

Use JDK 17 image for services CI

---

hedera-node/src/main/java/com/hedera/services/fees/FeesModule.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/system/txns/UncheckedSubmitResourceUsage.java
hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/system/txns/UncheckedSubmitResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordBuilderTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTestHelper.java
hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/records/DuplicateManagementTest.java

- Adds an `UncheckedSubmitResourceUsage` estimator to avoid a `FAIL_FEE` response in precheck when an unauthorized payer tries this operation.
- Updates `ExpirableTxnRecord.asGrpc()` to translate the `packedParentConsensusTime` field, and makes explicit in `AccountRecordsHistorian` the `parentConsensusTimestamp` is only set for child records that _follow_ the top-level transaction.

Final 0.21.x cleanup

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoAccountCreationValidationsAfterReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java

adjusted the account ids for post reconnect validations after we add autoAccount creations to the mix
Test fails for other reasons but EET validation suits passed [here](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1639603626140500)

Adjust reconnect validation suits to accommodate autoAccountCreations

---

hedera-node/src/main/java/com/hedera/services/context/init/StateInitializationFlow.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/BackingTokenRels.java
hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java
hedera-node/src/test/java/com/hedera/services/context/init/StateInitializationFlowTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/BackingTokenRelsTest.java
hedera-node/src/test/java/com/hedera/services/store/TypedTokenStoreTest.java

- Instead of building a separate `HashSet` to do existence checks for token relationships, accept the small overhead of `MerkleMap.containsKey()` and use that directly.

Use `MerkleMap` for existence check in `BackingTokenRels`

---

hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java

Closes #2653 
Changes `AccountInfo` query while querying with alias to return accountID in the form of `0.0.accountNum` instead of `0.0.alias`

Fix AccountInfo to return AccountID instead of Alias

---

hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java
hedera-node/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java
hedera-node/src/main/java/com/hedera/services/store/contracts/CodeCache.java
hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/queries/contract/ContractCallLocalAnswerTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/UpdateTrackingLedgerAccountTest.java

Add the CodeCache to HederaWorldState. This improves speed of
repetative calls and hashing of the code in CALL* and EXTCODE* ops.
Fixes #
**Checklist**

Add CodeCache to HederaWorldState

---

Dockerfile

Following the upgrade to [use JDK 17 for the Maven Compiler plugin](https://github.com/hashgraph/hedera-services/commit/65089b67e1fd8c6761b716d1f668e6d0a4a6c226), this PR intends to update the Dockerfile definition to do the same when generating the hedera-services Docker image.
Maven needed also to be bumped to work with JDK 17 otherwise compilation would fail with the following message:
Maven 3.8 is not part of Ubuntu's package manager so it had to be brought in.
A deployed instance of the build can be obtained [from here](https://hub.docker.com/r/buidlerlabs/hedera-services).
Fixes #
**Checklist**

Bumped Dockerfile JDK and Maven versions

---

Dockerfile

- Update Dockerfile to use Ubuntu 21.10.
- Note that an [issue with older versions of `runc`](https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build) may require updating your local Docker to use this new image.
**Related issues**:
- Closes #2669

Update Dockerfile with Ubuntu 21.10

---

hedera-node/src/main/java/com/hedera/services/ServicesApp.java
hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/StateChildren.java
hedera-node/src/main/java/com/hedera/services/context/init/StateInitializationFlow.java
hedera-node/src/main/java/com/hedera/services/fees/calculation/RenewAssessment.java
hedera-node/src/main/java/com/hedera/services/files/SimpleUpdateResult.java
hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java
hedera-node/src/main/java/com/hedera/services/sigs/metadata/TokenMetaUtils.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SignedStateSigReqs.java
hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java
hedera-node/src/main/java/com/hedera/services/state/StateModule.java
hedera-node/src/main/java/com/hedera/services/state/annotations/LatestSignedState.java
hedera-node/src/test/java/com/hedera/services/ServicesAppTest.java
hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/init/StateInitializationFlowTest.java
hedera-node/src/test/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookupTest.java
hedera-node/src/test/java/com/hedera/services/sigs/metadata/TokenMetaUtilsTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SignedStateSigReqsTest.java
hedera-node/src/test/java/com/hedera/services/state/StateAccessorTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoCreateUtils.java

- Adds to the context [a `StateAccessor`](https://github.com/hashgraph/hedera-services/blob/02019-M-ImplSignedStateSigReqsMgr/hedera-node/src/main/java/com/hedera/services/state/StateModule.java#L239) whose children are [continually updated from the latest signed state](https://github.com/hashgraph/hedera-services/blob/02019-M-ImplSignedStateSigReqsMgr/hedera-node/src/main/java/com/hedera/services/ServicesMain.java#L99) by `ServicesMain.newSignedState()`.
- Pro-actively implements the [`SignedStateSigReqs`](https://github.com/hashgraph/hedera-services/blob/02019-M-ImplSignedStateSigReqsMgr/hedera-node/src/main/java/com/hedera/services/sigs/order/SignedStateSigReqs.java#L45) that will use the `@LatestSignedState` accessor to help `ServicesState.expandSignatures()` use the …

Add the `@LatestSignedState` accessor + implement `SignedStateSigReqs`

---

hapi-fees/src/main/java/com/hedera/services/usage/token/TokenUpdateUsage.java
hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/consensus/TopicUpdateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/utils/EntityIdUtils.java
hedera-node/src/test/java/com/hedera/services/txns/consensus/MerkleTopicUpdateTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java

- In a `TopicUpdate`, if the auto-renew account is set to an alias `AccountID`, returns `INVALID_ACCOUNT_ID`.
- Fixes #2688

Distinguish `0.0.<alias>` from the removal sentinel AccountID `0.0.0`

---

hedera-node/src/main/java/com/hedera/services/records/RecordCache.java
hedera-node/src/main/java/com/hedera/services/records/TxnIdRecentHistory.java
hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
hedera-node/src/test/java/com/hedera/services/records/TxnIdRecentHistoryTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java

- Adds javadoc to `TxnIdRecentHistory`.
- Fixes `TxnIdRecentHistory.forgetFromClassifiableList()` so that it decrements `numDuplicatesFromDifferentNodes` for each expired record that was not a node duplicate.
- Comment out [this line](https://github.com/hashgraph/hedera-services/blob/fix-recent-history-dup-counting/hedera-node/src/main/java/com/hedera/services/records/TxnIdRecentHistory.java#L274) and run [this unit test](https://github.com/hashgraph/hedera-services/blob/fix-recent-history-dup-counting/hedera-node/src/test/java/com/hedera/services/records/TxnIdRecentHistoryTest.java#L173) to see the previous failure mode.
- It's nearly impossible to write a system-level test to trigger this bug, since a node must be more than 100 seconds behind in …

Add javadoc to `TxnIdRecentHistory` and counting of `numDuplicatesFromDifferentNodes`

---

.circleci/config.yml
run/set-cron-times.py

- Update _config.yml_ to run all jobs offset `-3` hours before `master`.
- Include a _run/set-cron-times.py_ script to automate changing _config.yml_ `cron` formats.

Update nightly regression on `hts-contracts`

---

hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java
hedera-node/src/main/java/com/hedera/services/context/StateChildren.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigReqsManager.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SigReqsManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/StateAccessorTest.java

- Per @nathanklick recommendation, eliminate need for `MutableStateChildren.nullOutRefs()` by just holding `WeakReference`s to the various state children.

Use weak refs for `MutableStateChildren` members

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java
hedera-node/src/main/java/com/hedera/services/context/StateChildren.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigReqsManager.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/ledger/TransactionalLedgerTest.java
hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JKeyTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SigReqsManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/StateAccessorTest.java
pom.xml

- Simplifies `SigReqsManager` by using weak references for `MutableStateChildren`.
- Checks the version of a signed state before using it to expand sigs (possible after upgrade that we have an old version).

Use weak refs in `MutableStateChildren`, check signed state version before expanding sigs

---

hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigReqsManager.java
hedera-node/src/test/java/com/hedera/services/context/MutableStateChildrenTest.java
hedera-node/src/test/java/com/hedera/services/state/StateAccessorTest.java

- Adds `MutableStateChildren.updateFromMaybeUninitializedState()` for use by `SigReqsManager` to update children from a signed state which may not have received an `init()` call (e.g., because it was received from a teacher during reconnect).

Add primitive-only `MutableStateChildren` update

---

test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
test-clients/yahcli/README.md

- Create `yahcli:0.1.10` giving an explicit `.fee()` qualifier to its `FileAppend` ops, to prevent custom fee calculation from running a `getFileInfo()` query.

Give explicit fee for `updateSpecialFile()` append ops

---

hedera-node/src/main/java/com/hedera/services/contracts/execution/CallEvmTxProcessor.java
hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessor.java
hedera-node/src/main/java/com/hedera/services/store/contracts/CodeCache.java
hedera-node/src/main/java/com/hedera/services/store/contracts/EntityAccess.java
hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
hedera-node/src/main/java/com/hedera/services/store/contracts/MutableEntityAccess.java
hedera-node/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCallTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/CodeCacheTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/MutableEntityAccessTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/UpdateTrackingLedgerAccountTest.java
hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java

- Replaces the `LoadingCache` previously used by `CodeCache` with a vanilla `Cache` that is only populated after finding non-`null` bytecode for a requested contract.

Restrict `CodeCache` read-throughs to non-empty bytecode

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
test-clients/src/main/resource/testfiles/updateFeature/updateSettings/sdk/settings.txt

Update settings since **asyncInputStreamTimeoutMilliseconds** has been renamed
Many tests failed because false alarm of 
**ERROR: reconnect.asyncInputStreamTimeoutMilliseconds is not a valid setting name.**

Hts contracts settings change

---

hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
hedera-node/src/main/java/com/hedera/services/sigs/order/PolicyBasedSigWaivers.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SigRequirements.java
hedera-node/src/main/java/com/hedera/services/sigs/order/SignatureWaivers.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
hedera-node/src/main/java/com/hedera/services/txns/validation/OptionValidator.java
hedera-node/src/test/java/com/hedera/services/ledger/BaseHederaLedgerTestHelper.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTest.java
hedera-node/src/test/java/com/hedera/services/sigs/order/SigRequirementsTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/validation/ContextOptionValidatorTest.java
hedera-node/src/test/java/com/hedera/test/factories/scenarios/CryptoUpdateScenarios.java
hedera-node/src/test/java/com/hedera/test/factories/txns/CryptoUpdateFactory.java
hedera-node/src/test/java/com/hedera/test/factories/txns/SignedTxnFactory.java
hedera-node/src/test/java/com/hedera/test/mocks/TestContextValidator.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

Related to #2691 
1. Allow existing accounts without an `alias` set to update their `alias`, when signed with the alias private key. Otherwise fails with `INVALID_SIGNATURE`
2. If `alias` key to be updated is not a primitive Key , returns `INVALID_ALIAS_KEY` response
3. When trying to update an account with an alias set on it , will return `ALIAS_IS_IMMUTABLE`response.

Allow existing accounts to update their alias

---

test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java

Add no op spec to let JRS hapiClientValidator for DynamicGasCostSuite with no acutal specs running as passed
**Checklist**

Add no op spec to let JRS hapiClientValidator for DynamicGasCostSuite Pass

---

hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountInfoAnswerTest.java
hedera-node/src/test/java/com/hedera/test/factories/accounts/MerkleAccountFactory.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

Closes #2817 
Related to #2747 
Add `CryptoAllowance`, `TokenAllowance` and `NftAllowance` values to cryptoGetInfo Query by looking into the maps in `account.state()`

Add Allowances Info to CryptoGetInfo Query

---

hedera-node/src/main/java/com/hedera/services/files/store/FcBlobsBytesStore.java
hedera-node/src/main/java/com/hedera/services/store/contracts/SizeLimitedStorage.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/files/store/FcBlobsBytesStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/SizeLimitedStorageTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogicTest.java

- Revert use of `VirtualMap.remove()` in favor of `put(, <empty value>)`.
- Mark signing requirement impact of `TokenFeeScheduleUpdate` (fallback fees require NFT receiver to sign).

Port `0.22.4` fixes

---

hedera-node/src/main/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenFeeScheduleUpdateTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

- `TokenFeeScheduleUpdate` can have an impact on signing requirements if it adds (or removes) a fallback fee.
- This PR supplies an [EET that fails reliably on `master`](https://github.com/hashgraph/hedera-services/blob/add-fee-schedule-update-sig-impact-test/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java#L692), but passes with the needed [call to `sigImpactHistorian.markEntityChanged()`](TokenFeeScheduleUpdateTransitionLogic) in `TokenFeeScheduleUpdateTransitionLogic`.

Add failing EET + fix for missing sig impact in `TokenFeeScheduleUpdate`

---

.circleci/config.yml
hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelper.java
hedera-node/src/main/java/com/hedera/services/state/logic/RecordStreaming.java
hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelperTest.java

- Uses `RecordStreaming` instead of directly adding renewal records to `RecordStreamManager`.
- Adds check in CI to fail if ISS detected in node logs.

Use `RecordStreaming` in `RenewalRecordsHelper`

---

hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java
hedera-node/src/main/java/com/hedera/services/txns/token/process/Dissociation.java
hedera-node/src/test/java/com/hedera/services/store/TypedTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/process/DissociationTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java

- Fixes the `Dissociation` logic to always update the model object for the dissociating account/token relationship, even when the treasury is already dissociated.
- Updates documentation and EETs.
- Closes #2857

Always update account/token relationship for dissociated account

---

pom.xml

- Use `0.23.1` version of protobufs to prepare for release tag.

Use non-`SNAPSHOT` proto artifact

---

.circleci/config.yml

Split some jobs to multiple smaller ones to less than 1 hour,
a work around to current circle ci issue.
Did not split all long jobs, some single test is longer than 1hours, could not split,
in addition, some are already failing due to known
pending bugs before this circle ci issue.
Changes to the JSON config files can be found here:
https://github.com/swirlds/swirlds-platform-regression/pull/2052/files

Split ci jobs

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml

This PR adds a new log marker (`THREADS`) to the log4j file in all environments, enabled by default. It is currently only logged during a reconnect. These log statements were previously logged using the `RECONNECT` marker, but the code has been moved to a utility class and is no longer specific to reconnect. It logs information about threads being stopped. Supports [this](https://github.com/swirlds/swirlds-platform/issues/4708) platform issue.
https://github.com/swirlds/swirlds-platform/issues/4708
N/A
**Checklist**

add new THREADS log marker, enabled by default

---

hedera-node/src/main/java/com/hedera/services/files/MetadataMapFactory.java
hedera-node/src/main/java/com/hedera/services/files/store/FcBlobsBytesStore.java
hedera-node/src/main/java/com/hedera/services/ledger/accounts/AliasManager.java
hedera-node/src/main/java/com/hedera/services/store/contracts/SizeLimitedStorage.java
hedera-node/src/test/java/com/hedera/services/files/MetadataMapFactoryTest.java
hedera-node/src/test/java/com/hedera/services/files/store/FcBlobsBytesStoreTest.java
hedera-node/src/test/java/com/hedera/services/ledger/accounts/AliasManagerTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/SizeLimitedStorageTest.java

- Merges fixes for `v0.23.1` tag:
* Continue to put tombstone rather than calling `remove()` pending 0.24.x upgrade.
* Return an unresolved contract alias instead of `null` to get expected `INVALID_SOLIDITY_ADDRESS` failure status.

Still defer `remove()` usage, and return unresolved aliases from `AliasManager.resolveForEvm()`

---

test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java

This PR adds an E2E that verifies the changes made from the [key-verification-logic-refactor PR.](https://github.com/hashgraph/hedera-services/pull/2900)
Fixes #
**Checklist**

Add E2E test for HTS precompile key verification logic when transfering tokens from the active contract

---

hedera-node/src/main/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdater.java
hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
hedera-node/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractStackedLedgerUpdaterTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/MockLedgerWorldUpdater.java
hedera-node/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java

Overload WorldLedgers.wrapped() to remove SideEffectsTracker as argument, so that we can initialize new ledgers without commit interceptors, when they are not needed.
Fixes #
**Checklist**

refactor: overload wrapped() method without sideEffectsTracker

---

hedera-node/src/main/java/com/hedera/services/txns/crypto/validators/AdjustAllowanceChecks.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/validators/ApproveAllowanceChecks.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/validators/AdjustAllowanceChecksTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/validators/ApproveAllowanceChecksTest.java

Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
If Token Supply Type is set to INFINITE, than the maxSupply field is always 0.
This PR fixes a check for approve allowance and adjust allowance when the tokenSupplyType is INFINITe.
Fixes #
**Checklist**

Fix approve/allowance issue with INFINITE supply type fungible tokens

---

hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java

- Sets the charged `CryptoCreate` fee on a child auto-creation record.
- Sets the expiration on an auto-created account.
- Fixes #2963

Add fee to record, expiry to new account in `AutoCreationLogic`

---

.circleci/config.yml

Use an old platform commit before removing blob feature to fix regression tests of service side,
also cherry picked  some fixes to service test from regression repo develop branch.
Once later a new sdk released to master branch, 
we need to revert this change.
Test result:
https://hedera-hashgraph.slack.com/archives/CJ1P4A2NS/p1647387065758839
The work flow started working, some test still failing need further debug

Fix service regression by bring back postgres support

---

pom.xml

- Fixes expired staging repository for `v0.24.0-alpha.2` protobufs.

Use `v0.24.0-alpha.3` staging repo

---

hedera-node/src/main/java/com/hedera/services/context/SideEffectsTracker.java
hedera-node/src/main/java/com/hedera/services/state/logic/SigsAndPayerKeyScreen.java
hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
hedera-node/src/main/java/com/hedera/services/stats/MiscSpeedometers.java
hedera-node/src/test/java/com/hedera/services/context/SideEffectsTrackerTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/SigsAndPayerKeyScreenTest.java
hedera-node/src/test/java/com/hedera/services/stats/MiscSpeedometersTest.java

- Removes the [`sigVerifyAsync/sec` stat](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/stats/MiscSpeedometers.java#L84), as I have never seen it used---and in any case, its value is exactly `transH/sec - sigVerifySync/sec`. (Plus JProfiler claims updating this speedometer is now ~1% of the time spent in handling a simple `CryptoTransfer`!)
- Removes the [vestigial `acctLookupRetries/sec` stat](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/stats/MiscSpeedometers.java#L85); no existing code path uses this speedometer.
- Stops creating a [new auto-associations `ArrayList` for **every** record](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/s …

Drop async verifications `Speedometer`; create new `ArrayList` only on new auto-associations

---

hedera-node/src/main/java/com/hedera/services/txns/network/UpgradeActions.java
hedera-node/src/test/java/com/hedera/services/txns/network/UpgradeActionsTest.java

- Before extracting an upgrade ZIP---either software or telemetry---calls [`FileUtils.cleanDirectory()`](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FileUtils.html#cleanDirectory-java.io.File-) on the `upgrade.artifacts.path` location. (I.e., _/opt/hgcapp/services-hedera/HapiApp2.0/data/upgrade/current_ in prod environments.)
- Closes #2846

Call `FileUtils.cleanDirectory()` before extracting upgrade ZIP

---

hedera-node/src/main/java/com/hedera/services/state/submerkle/EvmFnResult.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
hedera-node/src/test/java/com/hedera/services/state/serdes/DomainSerdesTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultSerdeTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java
pom.xml
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/FunctionParameters.java

This PR modifies `HTSPrecompiledContract` to include additional fields in the `ContractFunctionResult` of its transaction records in order to support precompile traceability from the mirror nodes.
* `gas`, `amount` and `functionParameters` fields have been added to `EvmFnResult` 
- `gas` specifies the amount of gas available for the call
- `amount` specifies the number of tinybars sent.  **NOTE** that currently EVM value transfers are not allowed.
- `functionParameters` specifies the called called function and the parameters passed into the contract call
* Precompile calls to `HTSPrecompiledContract` now include the three fields in their transaction records whenever their corresponding transaction body is not of type `ContractCallTransactionBody` or …

Include additional fields needed for traceability in precompile ContractFunctionResult #2933 

---

hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleAccount.java
hedera-node/src/test/java/com/hedera/services/state/exports/ToStringAccountsExporterTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountTest.java

Merkle account copy method should copy based on the no of children it has

Merkle account copy patch

---

hedera-node/src/test/java/com/hedera/services/ServicesStateE2ETest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountStateSerdeTest.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java
hedera-node/src/test/java/com/hedera/test/serde/SelfSerializableDataTest.java

Refactor SelfSerializableDataTest to register all constructables in the classpath automatically making the registerConstructables method optional. 
https://github.com/hashgraph/hedera-services/issues/3114

Refactor SelfSerializableDataTest to register all constructables in the classpath automatically making the registerConstructables method optional.

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithAutoAccounts.java

Small fix for https://github.com/swirlds/swirlds-platform-regression/issues/2173 .

---

hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
hedera-node/src/main/java/com/hedera/services/store/models/Account.java
hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
hedera-node/src/test/java/com/hedera/services/store/AccountStoreTest.java
hedera-node/src/test/java/com/hedera/services/store/models/AccountTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/misc/CannotDeleteSystemEntitiesSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java

- Ensure `numPositiveBalances` is decremented when dissociating from a deleted token w/ positive balance.
- Move `TokenAssociationSpecs.cannotAssociateMoreThanTheLimit()` out of async run section---it sets `tokens.maxPerAccount=0`.
- Update the `CannotDeleteSystemEntitiesSuite` to the new lower # of system entities (750).

Fix `treasuryBecomesDeletableAfterTokenDelete()` EET

---

test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/AddrBkJsonToGrpcBytes.java
test-clients/yahcli/README.md
test-clients/yahcli/run/build.sh

- Stops rejecting `FileUpdate`s to `0.0.101/2` that omit the [deprecated `NodeAddress` fields](https://hashgraph.github.io/hedera-protobufs/#proto.NodeAddress) (`ipAddress`, `portno`, `memo`).
- Bumps yahcli version to `0.1.12`

Update yahcli for deprecated address book fields

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java

This brief PR modifies the behavior for Transfer and ERCTransfer precompiles to **not throw errors** but to **return null** on a decoding failure.
Fixes #03133
**Checklist**

Consistent Transfer and ERC20Transfer failure behavior

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensStateAfterReconnect.java

Close regression test 2253 and 2146
https://github.com/swirlds/swirlds-platform-regression/issues/2253
https://github.com/swirlds/swirlds-platform-regression/issues/2146
TokenDeleteValidate-NIReconnect-1-16m
TransactionHistory-NIReconnect-1-16m
Test result:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1649736945502569

Adjust timing for token reconnect tests

---

test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ResetThrottleSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ResetTokenMaxPerAccount.java

Some regression tests failed because those test started
from a saved state file from the test net.
And CryptoCreate TPS limit and tokens.maxPerAccount are set too low 
in the state file.
Need to add these test suite to reset to higher limit
before the following load test or performance test.
Related PR 
https://github.com/swirlds/swirlds-platform-regression/pull/2259

Add test to reset TPS and token create account limit

---

hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java
hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java

Signed-off-by: Neeharika-Sompalli [neeharika.sompalli@hedera.com](mailto:neeharika.sompalli@hedera.com)
Closes #3185 
- `ExpirableTxnRecord` with versions 0.23.0 and 0.24.0 serialized 3 empty allowance maps sizes. 
- But those maps are removed from 0.25.0 in the TxnRecord
- So for the versions **>=23.0** and **< 0.25.0** while deserializing we need to read 3 Integers.

Fix deserialization for 0.24.x versions

---

hedera-node/src/main/java/com/hedera/services/files/store/FcBlobsBytesStore.java
hedera-node/src/test/java/com/hedera/services/files/store/FcBlobsBytesStoreTest.java

- Uses a more performant `VirtualMap` path in `FcBlobsByteStore`.

Prefer `put()` to `getForModify()` in blob store

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AdjustFeeScheduleSuite.java

Resolved regression issue  2238 
https://github.com/swirlds/swirlds-platform-regression/issues/2238
When a client 0 is asking node 0 to update fee schedule fees,
other clients may doing fee schedule download.
This change will use fixed fee schedule to skip fee schedule downloading step
to avoid the race condition.
Test result
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1649892873350709

Use fixed fee to avoid downloading fee schedule

---

test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ResetTokenMaxPerAccount.java

From latest test report
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1649922949090839
It seems upper limit 10K is not enough for those tests, increase limit to 100K
```
2022-04-14 06:02:29.688 ERROR  263  HapiTxnOp - 'RunCreateTokens' -  HapiTokenCreate{sigs=1, node=0.0.3, token=token9993} Wrong actual status TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED, not one of [UNKNOWN, SUCCESS, TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT]!
2022-04-14 06:02:29.689 ERROR  263  HapiTxnOp - 'RunCreateTokens' -  HapiTokenCreate{sigs=1, node=0.0.3, token=token10013} Wrong actual status TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED, not one of [UNKNOWN, SUCCESS, TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT]!
```

Increase tokens.maxPerAccount

---

hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaExceptionalHaltReason.java
hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
hedera-node/src/main/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdater.java
hedera-node/src/main/java/com/hedera/services/txns/contract/helpers/DeletionLogic.java
hedera-node/src/test/java/com/hedera/services/contracts/operation/HederaSelfDestructOperationTest.java
hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdaterTest.java
hedera-node/src/test/java/com/hedera/services/txns/contract/helpers/DeletionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java

In this PR I added non-zero balance checks inside ContractDeleteTransitionLogic and HederaSelfDestructOperation so that both through HAPI and through EVM we validate that when deleting a contract it has already sent all of its token balances somewhere else.
Addresses zero balance check for selfdestruct/delete operations on contracts.
Fixes #3087
**Checklist**

Zero Fungible/NFT Balances before Contract delete/selfdestruct operations

---

hedera-node/src/test/java/com/hedera/test/utils/SeededPropertySource.java

The seeded generation of objects for the large scale serdes test
depends on selecting some constants from a large range of values.
However, when protobuf upgrades occur that range can grow and hence the
values selected for those fields will change.
To address this the default range selector of the objects is fixed to
the 0.25 length. A second form of the call allowing future upgrades to
request values from a larger range is also supplied in the event future
serialization structures depend on the new value.
**Checklist**

Hardcode range of enums for Seeded SerDes tests

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt

- Removes now-unneeded `virtualMap.preferredFlushQueueSize=10000` overrides.

Remove `virtualMap.preferredFlushQueueSize` overrides

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt

Reverts hashgraph/hedera-services#3228
(SDK team recommended postponing this change until release 0.26.)

Revert "Remove `virtualMap.preferredFlushQueueSize` overrides"

---

hedera-node/src/main/java/com/hedera/services/store/contracts/CodeCache.java
hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCallTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/store/contracts/CodeCacheTest.java
hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java

Calls to `ERC20` or `ERC721` functions of HTS tokens are possible after `HIP-218` implementation through the EVM.
Direct calls with `HAPI` contract call transactions however are failing. This PR fixes that.
Fixes #3222 
- CodeCache to return redirectBytecode if the address we're querying is a token account address
- ContractCallTransitionLogic to not load target from accountStore if target is a token
- E2E tests with direct calls to Fungible and NFT tokens
**Checklist**

Support HTS / HIP-218 precompile for direct calls

---

benchmarks/src/main/java/com/hedera/hashgraph/SizeLimitedStorageBench.java
benchmarks/src/main/java/com/hedera/hashgraph/setup/InfrastructureInitializer.java
hedera-node/src/main/java/com/hedera/services/contracts/ContractsModule.java
hedera-node/src/main/java/com/hedera/services/state/expiry/TokenRelsListRemoval.java
hedera-node/src/main/java/com/hedera/services/state/expiry/removal/AccountGC.java
hedera-node/src/main/java/com/hedera/services/state/expiry/removal/ContractGC.java
hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseTwentySixMigration.java
hedera-node/src/main/java/com/hedera/services/state/virtual/ContractStorageListRemoval.java
hedera-node/src/main/java/com/hedera/services/state/virtual/IterableStorageUtils.java
hedera-node/src/main/java/com/hedera/services/utils/MapValueListRemoval.java
hedera-node/src/main/java/com/hedera/services/utils/MapValueListUtils.java
hedera-node/src/test/java/com/hedera/services/state/expiry/TokenRelsListRemovalTest.java
hedera-node/src/test/java/com/hedera/services/state/virtual/ContractStorageListRemovalTest.java
hedera-node/src/test/java/com/hedera/services/state/virtual/IterableStorageUtilsTest.java
hedera-node/src/test/java/com/hedera/services/utils/MapValueListUtilsTest.java

- Renames methods that mutate a `VirtualMap` via `getForModify()` with an `inPlace` prefix.
* E.g., `MapValueListUtils.removeFromMapValueList()` becomes `inPlaceRemoveFromMapValueList()`.
- Provides `overwriting*` variants of these methods that use a `get() -> copy() -> put()` idiom instead of `getForModify()`.

Use `put()` not `getForModify()` with `VirtualMap`s

---

hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
hedera-node/src/test/java/com/hedera/services/contracts/operation/HederaSelfDestructOperationTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java

Hedera Self Destruct Operation needed to filter mirror address usage for aliased contract deletion.

Self Destruct Operation Address Filtering

---

hedera-node/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java

* Adds logic in `EthereumTransitionLogic` that inherits the following sender account properties in a synthetic `ContractCreate` transaction body:
* `adminKey`
* `autoRenewPeriod`
* `memo` (if present)
* `proxy` (if present)
* Adds unit tests that verify proper synthetic body translation
Fixes #3223 
Fixes #3210

Inherit sender properties when performing ContractCreate with ETH txn

---

hedera-node/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java

AliasManager.lookupById never returns null, instead check for
MISSING_NUM.
Also, delete two duplicate tests and uncomment a third.
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #
**Checklist**

Check for MISSING_NUM in validation

---

hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java

When executing a create (to address is empty) ethereum transaction, add
a child record containing the synthetic transaction data.
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #
**Checklist**

Create Child Record for Child Transactions

---

hedera-node/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java

In this PR I am adding an E2E Scenario where no eth data is passed to the EthereumTxBody. This started to produce exceptions so I had to add an explicit precheck whether the EthTxData is present. I think we need to come up with a proper response code so I added a TODO and we can discuss that.
Fixes #3216 
**Checklist**

3216 ethtx calldata noethdata

---

.circleci/config.yml

Closes regression issue 2342.
Update regression result upload folder, not including "path"
Some original test , more test results will be posted.
Manually checked the results were uploaded correctly and can be accessed through URL from slack report.
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1651610804446709
More test results
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1651620664783629

02342 fix result upload folder

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java

Use test AllProtectedFilesUpdate-NIReconnect-1-16m as an example.
After analyzing some test logs, 
The last node became disconnected after about 9 minutes 50 seconds of node start.
The client is expecting node to be disconnected after the 9 minutes 30 seconds of client start.
Since there is a little delay between client start and node start,  so sometimes
client's check time is after the disconnection time,
client's check time is a few second earlier than disconnection time.
and caused the client to report disconnection not happening yet.
```
Node start -------------------------------> Node disconnect
Client Start ---------------------------> client check if disconnect happened
```
Added some delay to make sure the check time a after actual disconnection time.
```
Node start …
```

Adjust timing for a few occasionally failed NI reconnect tests

---

test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java

- For `GetsInsufficientPayerBalanceIfSendingAccountCanPayEverythingButServiceFee`, since there is no longer a fixed `service` fee, use a fire-and-forget `CryptoTransfer` to ensure the `ContractCreate` can get through precheck, but payer's balance will be just below the amount needed to pay `gas` at consensus.
- For `TransferNftAfterNestedMint` and `GasCostNotMetSetsInsufficientGasStatusInChildRecord`, add a helper method to compute the expected gas cost of a precompile based on active `gas` price and canonical price loaded from _hapi-fees/_ assets.

Address failing EETs

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensDeleteAfterReconnect.java

Client check if the node 0.0.8 is offline at time 10:07:40
```
2022-05-05 10:07:40.925 ERROR  225  HapiSpecOperation - Node 0.0.8 is NOT unavailable as expected!!!
```
The node actually became disconnected at 10:07:53
```
2022-05-05 10:07:53.691 54       ERROR SOCKET_EXCEPTIONS <<platform-core: listener 5 to 4 #0>> NetworkUtils: Connection broken: 5 <- 4
```
Test results:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1651783705388629

Adjust timing of TokenDeleteValidate-NIReconnect-1-16m

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/state/migration/KvPairIterationMigrator.java
hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseTwentySixMigration.java
hedera-node/src/test/java/com/hedera/services/ServicesStateE2ETest.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

- Since `ReleaseTwentySixMigration` replaces the contract storage `VirtualMap` at child index 11, we must re-initialize the `WeakReference`s in the `MutableStateChildren` before proceeding to `ServicesMain.init()`.

Re-initialize `MutableStateChildren` after 0.26 migrations

---

test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java

Signed-off-by: Dimitar Dinev <mitkojc@gmail.com>
Adds E2E for ETX-012 in `EthereumSuite` -> 
`Contract call to HTS precompile operations requiring authenticaion work when only the EthTX has the needed signature (not the hedera tx)`
Fixes #3279
**Checklist**

Add ETX-012 from the Ethereum test plan

---

test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java

Signed-off-by: Dimitar Dinev <mitkojc@gmail.com>
Adds `nonce` assertions to the E2Es in `HelloWorldEthereumSuite` 
Fixes #3322 
ETX-017 (`EthTx works when presented with correct nonce in transaction `) is implicitly verified by each Ethereum E2E test (nonce is supplied when creating `HapiEthereumCalls`)
**Checklist**

Add ETX-SVC-001 from the Ethereum Test Plan

---

test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java

Part of regression PR
https://github.com/swirlds/swirlds-platform-regression/pull/2375
One of balance test loads state file from test net, 
uses EXCHANGE_RATE_CONTROL for updating throttle file leads to INVALID_SIGNATURE error.
So change it to genesis account

Update AccountBalancesClientSaveLoadTest 

---

.circleci/config.yml

Updates the CCI pipelines to properly handle the removal of the Git submodules from the `swirlds/swirlds-platform` repository.
Fixes #3387

Update CircleCI Pipelines to support the submodule removal in Platform

---

test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java

Assertions for ContractCallResult on child records for the following e2e test suites:
1. Associate
2. Keys
3. ContractHTSSuite

adding assertion of ContractCallResult for Associate e2e tests

---

test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DissociatePrecompileSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/MixedHTSPrecompileTestsSuite.java

Assertions for ContractCallResult on child records for the following e2e test suites:
Dissociate
Mixed
Transfer
ERC

adding assertion of ContractCallResult for e2e tests

---

hedera-node/src/main/java/com/hedera/services/state/expiry/UniqueTokensListRemoval.java
hedera-node/src/test/java/com/hedera/services/state/expiry/UniqueTokensListRemovalTest.java

Fixes issue with UniqueTokensListRemoval that can happen if next/prev fields are stored (serialized) and then loaded (deserialized). This can lead to next/prev returning a valid pair instead of null.
Fixes #: https://github.com/hashgraph/hedera-services/issues/3421

Fixes issue with MISSING_NFT_NUM_PAIR comparison in UniqueTokenListRemoval

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

- Updates CI test failure check to include new _assets/_ path segment.
- Tries to stabilize `TokenTransactSpecs` by moving `ContractUpdateSuite.updateMaxAutoAssociationsWorks()` out of async run section.
- Tries to stabilize a couple other specs by using a non-default payer.

Fix CI results path; move stateful `updateMaxAutoAssociationsWorks()` out of async run section

---

hedera-node/src/test/java/com/hedera/services/ServicesStateE2ETest.java

Modifies ServicesStateE2ETest to add migration and genesis state generation tests to ensure no crashes occur during migration.
Fixes:  https://github.com/hashgraph/hedera-services/issues/3423

Add E2E unit tests for migration and genesis init.

---

docs/gradle-quickstart.md
hedera-node/build.gradle.kts
pom.xml

Closes #3380. Adds a task called `cleanRun` to clean up files produced as part of `./gradlew run` (or any other method used to run the app). Plumbs this into `./gradlew clean` so that a clean gets this too.

Clean files produced by Gradle application run

---

buildSrc/src/main/kotlin/com.hedera.hashgraph.benchmark-conventions.gradle.kts

- Fixes issue with `ConstructableRegistry` in JMH benchmarks.

Add `Multi-Release: true` to JMH JAR manifest

---

hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

- Removes ServicesState mocks and actually set the properties of the state.
- Update test for no migration on current version to always use current version to avoid constant need to update.
Fixes: https://github.com/hashgraph/hedera-services/issues/3426

Remove ServicesState mocks in ServicesStateTest leading to more realistic test results.

---

test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensStateAfterReconnect.java

Closes regression issue 2436 
https://github.com/swirlds/swirlds-platform-regression/issues/2436
Test result
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1653092943924259

Add delay during reconnect test to avoid sending query when reconnect node is updating its state

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
hedera-node/src/main/java/com/hedera/services/txns/token/AssociateLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/BurnLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/DissociateLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/MintLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenAssociateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenBurnTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenDissociateTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenMintTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/AssociateLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/BurnLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/MintLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenAssociateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenBurnTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java

- Inserts precheck syntax checks into `HTSPrecompiledContract` implementations to align error codes with those returned by HAPI.
- Grabs a small `allowance(address _owner, address _spender)` fix from [this PR](https://github.com/hashgraph/hedera-services/pull/3440).

Align precompile error codes with those returned by HAPI

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/init/StateInitializationFlow.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/init/StateInitializationFlowTest.java

- Refactors some of the logging logic into ServicesState.
- Log out ServicesState children sizes before and after migration.
- Update tests to reflect changes.
Fixes: https://github.com/hashgraph/hedera-services/issues/3462

Logging out ServicesState children sizes before and after migration to simplify ensuring consistency pre- and post- migration.

---

hedera-node/src/main/java/com/hedera/services/state/migration/KvPairIterationMigrator.java

Changing a log line back to debug level because it generated more logging lines than expected.
Related issue: https://github.com/swirlds/swirlds-platform/issues/5473

Remove spurious logging line back to debug level to avoid log spamming.

---

hedera-node/src/main/java/com/hedera/services/exceptions/MissingEntityException.java
hedera-node/src/main/java/com/hedera/services/ledger/TransactionalLedger.java
hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptor.java
hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java
hedera-node/src/main/java/com/hedera/services/ledger/properties/NftProperty.java
hedera-node/src/main/java/com/hedera/services/store/models/NftId.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/ApproveAllowanceLogic.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoDeleteTransitionLogic.java
hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogic.java
hedera-node/src/test/java/com/hedera/services/ledger/TransactionalLedgerTest.java
hedera-node/src/test/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
hedera-node/src/test/java/com/hedera/services/store/models/NftIdTest.java
hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoDeleteTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoUpdateTransitionLogicTest.java

- Removes `NftProperty` values `PREV`, `NEXT`; and `AccountProperty` values `HEAD_TOKEN_NUM`, `HEAD_NFT_ID`, `HEAD_NFT_SERIAL_NUM`---all these properties should be invisible outside the `CommitInterceptor`s that manage them.
- Future-proofs `ApproveAllowanceLogic` by making the order of approval persistence deterministic. (Doesn't matter with a `MerkleMap`, but could with `VirtualMap`.)
- Confirms `OWNER` is actually changing before updating links in `LinkAwareUniqueTokensCommitInterceptor`. 
- Renames `MissingAccountException` -> `MissingEntityException` for better readability.

Fix NFT link management 

---

.circleci/config.yml
test-clients/src/main/resource/logback.xml

As @JeffreyDallas recommended in a comment on #3077 , this PR will disable ethereumj library to create log files by overriding the logback.xml from the library. After we completely remove the depedency from test-clients this logback.xml file can also be deleted.
**Related issue(s)**: #3077 
Fixes #
**Checklist**

feat: disable ethereumj log

---

hedera-node/src/main/java/com/hedera/services/store/contracts/AbstractLedgerWorldUpdater.java
hedera-node/src/main/java/com/hedera/services/store/contracts/AbstractStackedLedgerUpdater.java
hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractLedgerWorldUpdaterTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractStackedLedgerUpdaterTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java

- Reverts a change in `FeeAndRatesProvider` to use genesis rather than default payer.
- Cleans up management of records between parent and child updaters during `commit()`.

Misc cleanup

---

hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalExecutor.java
hedera-node/src/main/java/com/hedera/services/utils/EntityIdUtils.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalExecutorTest.java
hedera-node/src/test/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsageTest.java
hedera-node/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java

ContractCallLocalQuery was not respecting the sender_id and was not aliasing the sender.  This patch does those two steps.
Fixes #3512
**Checklist**

Set and alias Sender in Local Contract Call Queries

---

Dockerfile
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java

- Reset the `HTSPrecompiledContract.isTokenReadOnlyTransaction` flag every computation.

Reset `isTokenReadOnlyTransaction` in `prepareComputation()`

---

hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java

ServicesStateTest can fail during test setup if the `database` folder is non-existent. This PR checks for the existence of the folder and creates it if it is missing. This PR also improves the overall logging for when the error occurs (which was non-existent).
Fixes #: https://github.com/hashgraph/hedera-services/issues/3540

Fixes flakiness in ServicesStateTest during setup caused by a directory being non-existent.

---

test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/ParallelSpecOps.java
test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java

Improve parallelism in HapiApiSpec test clients by creating a common thread pool and avoiding calls to CompletableFuture.runAsync without a thread pool argument.
Calls to CompletableFuture.runAsync without a thread pool uses ForkJoinPool.commonPool which is limited to numCores - 1 threads. This is extremely limited and can lead to I/O bounded threads to be starved. This PR addresses this issue by:
- Creating a common thread pool with a high upper bound to max threads allowed.
- Switching calls to runAsync to include the new thread pool as the thread pool argument.
On a custom test written, the test previously took 233 seconds to run before this change. After these changes it took 12 seconds to complete.
Fixes: …

Improve parallelism in HapiApiSpec test clients

---

hedera-node/build.gradle.kts
hedera-node/pom.xml
pom.xml
settings.gradle.kts

The besu-evm brings in the secp256r1 library, which hedera neither needs nor uses.
Fixes #3546 
kotlin build didn't get the 0.5.0 version upgrade in the prior PR, adding it here.
**Checklist**

remove secp256kr1 library

---

hedera-node/build.gradle.kts

Correct exclusion of the bls12-381 lib kotlin build and exclude secp256r1.
Fixes #3546
**Checklist**

Restore bls12-381 to kotlin build

---

test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/NftTransferSuite.java

Add an E2E test for simulating a high number of peer-to-peer NFT transfers on a local node. This is useful for debugging, profiling, and testing.
Related:
https://github.com/hashgraph/hedera-services/issues/2820

Add an E2E NFT transfer test suite for stressing out a local node.

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com.hedera.hashgraph.hedera-conventions.gradle.kts

Signed-off-by: Richard Bair <richard.bair@swirldslabs.com>

Add spotless support which also manages license headers automatically.

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java

With this PR we are changing the value of address field in the log of the emitted event after transfer from hts precompiled contract address(0x167) to EVM_ADDRES_OF_HTS_TOKEN.
Also changed the way of loading the addresses of the sender and receiver fields(check whether they're aliased).
**Related issue(s)**: #3530 
Fixes #
**Checklist**

HTS Tokens emit events with wrong emitter address

---

hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java
hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleProcessingTest.java

Change schedule processing error message to warn and up threshold. 
This error can be hit easily when many transactions are scheduled for a time when the system is down and with long term transactions disabled while many schedule creations come in during one second.
Fixes #
**Checklist**

fix(): change schedule processing error message to warn and up threshold

---

hedera-node/src/main/java/com/hedera/services/contracts/execution/StaticBlockMetaSource.java
hedera-node/src/main/java/com/hedera/services/state/logic/BlockManager.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/src/test/java/com/hedera/services/contracts/execution/StaticBlockMetaSourceTest.java
hedera-node/src/test/java/com/hedera/services/state/logic/BlockManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextSerdeTest.java
hedera-node/src/test/java/com/hedera/test/utils/SeededPropertySource.java

- Makes block numbers in dev environments more readable by starting from 0 after a reset (which should indeed be the correct number in a true genesis environment!)

Start genesis `blockNo` at 0 since no longer a risk of false numbering

---

.github/workflows/comp-compile-application-code.yaml
.github/workflows/flow-build-application.yaml
.github/workflows/flow-pull-request-checks.yaml

Adds FOSSA Scan support with optional FOSSA Test support (manual initiation).
Fixes #3672

Add FOSSA Support to the GH Actions Workflow

---

hedera-node/src/main/java/com/hedera/services/ServicesMain.java
hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/context/init/StoreInitializationFlow.java
hedera-node/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
hedera-node/src/main/java/com/hedera/services/state/initialization/SystemFilesManager.java
hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleStakingInfo.java
hedera-node/src/main/java/com/hedera/services/store/Store.java
hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/src/test/java/com/hedera/services/context/init/StoreInitializationFlowTest.java
hedera-node/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
hedera-node/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleStakingInfoTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/BookEntryPojo.java

Closes #3610 
- On a non-`RECONNECT` initialization, updates the `NodeAddress#stake` fields in file `0.0.102` with the stakes from the platform `AddressBook`. (Post-dynamic `AddressBook`, this needs to be done on reconnect as well.)
- Fixes the last two bugs mentioned [here](https://www.notion.so/swirldslabs/b6b6a2a1af194e6d95cd541e6ace1031?v=946b21412e9d4caea2d291581d5a5c81).
- Removes the now-unused `Store.rebuildViews()` method.
- Updates `BookEntryPojo` to support `stake` in yahcli transactions (does not yet push a `yahcli:0.2.2`).

Make `AddressBook` stakes queryable via `0.0.102`

---

hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
hedera-node/src/main/java/com/hedera/services/txns/validation/PureValidation.java
hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
hedera-node/src/test/java/com/hedera/services/txns/validation/PureValidationTest.java
pom.xml
settings.gradle.kts
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

- Two tweaks to make staking behavior more intuitive and consistent.
- The EET verifying these behaviors is [here](https://github.com/hashgraph/hedera-services/blob/minor-staking-fixes/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java#L1259); a direct comparison is impossible b/c spotless.

Allow staking to contract accounts, only return `stakePeriodStart` if staking to node

---

Dockerfile
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts
test-clients/build.gradle.kts

Ensures `SuiteRunner.jar` is built as an Uber JAR file which is expected by JRS.
Fixes #3714

SuiteRunner JAR file is expected by JRS to be an Uber JAR file

---

test-clients/src/main/java/com/hedera/services/yahcli/commands/keys/ExtractDetailsCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/keys/KeysCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/keys/NewPemCommand.java
test-clients/yahcli/README.md
test-clients/yahcli/run/build.sh

Per DevOps request,
- Adds the `print-keys` subcommand to display both the public and private keys in a Ed25519 keypair.
- Updates `new-key` to also export the DER-encoded private key as a _.privkey_ file.

yahcli 0.2.5 keys tweaks

---

hedera-node/src/main/java/com/hedera/services/ServicesState.java
hedera-node/src/main/java/com/hedera/services/config/HederaNumbers.java
hedera-node/src/main/java/com/hedera/services/context/properties/SerializableSemVers.java
hedera-node/src/main/java/com/hedera/services/state/initialization/TreasuryCloner.java
hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
hedera-node/src/test/java/com/hedera/services/context/properties/SerializableSemVersTest.java
hedera-node/src/test/java/com/hedera/services/state/initialization/TreasuryClonerTest.java
hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java

- Omits treasury clones in the range reserved for system contracts. 
- Ensures clones have the same `declineRewards` as the treasury.

Skip treasury clones in the `0.0.350-399` range

---

test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java

Add dedicated account in wipe e2e tests.
Additionally use an invalid token instead of address of an account address in GrantRevokeKycSuite for revoking and granting in cases.
**Related issue(s)**: https://github.com/hashgraph/hedera-services/issues/3766
**Checklist**

Add dedicated account in wipe e2e tests

---

hedera-node/src/main/java/com/hedera/services/context/init/StoreInitializationFlow.java
hedera-node/src/main/java/com/hedera/services/state/validation/UsageLimits.java
hedera-node/src/test/java/com/hedera/services/context/init/StoreInitializationFlowTest.java
hedera-node/src/test/java/com/hedera/services/state/validation/UsageLimitsTest.java

- Ensure contracts are not re-counted on reconnect. 🤕

Reset contracts before re-counting them inside `InitializationFlow`

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java

When a user calls the `setApprovalForAll(address token, address operator, bool approved)` function of the HTS precompiled contract, the tokenId field of the [SetApprovalForAllPrecompile](https://github.com/hashgraph/hedera-services/blob/67166f8e252e9d99608b601c9a026c283765b066/hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java#L84) is initialized with a `null` value, which causes an NPE in [SyntheticTxnFactory](https://github.com/hashgraph/hedera-services/blob/67166f8e252e9d99608b601c9a026c283765b066/hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java#L298) when constructing the `CryptoApproveAllowanceTransactionBody`. 
Fix: use the tokenId value from the …

Fix NPE when creating approve for all synth transaction

---

hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenPrecompileReadOperationsTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java

Closes regression issue 2739
https://github.com/swirlds/swirlds-platform-regression/issues/2739
Add a little delay after the client found the offline node is back online

Add delay for reconnect correctness test

---

hedera-node/build.gradle.kts

Fixes #3851
Directly makes sure "assemble" is executed before "run".

Assemble before Run

---

.circleci/config.yml

Removes the `continuous-integration-gcp` from the CircleCI configuration. 
Fixes #3865

Disable the per commit CircleCI based JRS workflow

---

.github/workflows/comp-build-release-artifact.yaml

This change updates the `deterministic-zip` software to version `1.2.0` which enables directory entry support.
Fixes #3873 
```
Enable verbose mode
Executing feature Recursive ...
read directory data
Executing feature Directories ...
Using go zip compression method 8
Adding VERSION
Adding data/
Adding data/apps/
Adding data/apps/HederaNode.jar
Adding data/lib/
Adding data/lib/animal-sniffer-annotations-1.19.jar
Adding data/lib/annotations-16.0.2.jar
Adding data/lib/annotations-4.1.1.4.jar
Adding data/lib/apiguardian-api-1.0.0.jar
Adding data/lib/bcpkix-jdk15on-1.70.jar
Adding data/lib/bcprov-jdk15on-1.70.jar
Adding data/lib/bcutil-jdk15on-1.70.jar
Adding data/lib/besu-datatypes-22.7.1.jar
Adding data/lib/bls12-381-0.5.0.jar
Adding data/lib/caffeine-3.1.1.jar
Adding …
```

Update the release artifact pipeline to use the newest version of deterministic-zip

---

.github/workflows/comp-build-release-artifact.yaml

Resolves an issue caused by a branch name with an underscore character `_` forming an invalid semantic version number.
Fixes #3854 
Passing test run: https://github.com/hashgraph/hedera-services/actions/runs/2936862246

Ensure release pipeline replaces underscores in the branch name with periods

---

hedera-node/src/main/java/com/hedera/services/fees/charging/RecordedStorageFeeCharging.java
hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
hedera-node/src/test/java/com/hedera/services/fees/charging/RecordedStorageFeeChargingTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/AutoExpiryCycleTest.java
hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java

Fixes two edge cases for expired contracts:
- When renewing a contract, make sure its new expiry is in the future by using `now + renewalPeriod` instead of `oldExpiry + renewalPeriod` (it's possible the auto-renew cycle will take a long time to visit an expired contract, and for a small value of `renewalPeriod`, we could leave the contract still expired).
- When charging storage fees for an expired contract, treat the expected lifetime of the new storage slots as the contract's auto-renew period.

Rationalize treatment of expired entity lifetimes

---

hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java

Signed-off-by: Dimitar Dinev <mitkojc@gmail.com>
* Changes traceability migration logic in `MigrationRecordsManager` to check for `null` bytecode for a contract and not export any sidecars in such cases.
Fixes #3922

Check for `null` bytecode in traceability migration

---

hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ApprovePrecompile.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetApprovedPrecompile.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/OwnerOfPrecompile.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenURIPrecompile.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERCTransferPrecompileTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetApprovedPrecompileTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/OwnerOfPrecompileTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenURIPrecompileTest.java

Signed-off-by: Georgi Georgiev <georgi.getz@outlook.com>
This PR focuses on the problem that the `longValue()` method of `BigInteger` allows overflows of the long value which can lead to some unexpected results.
It's not opened directly to the master branch because a significant part of the cases were in the decoding facade which would have caused a lot of needless conflicts.
Fixes #3920 
**Checklist**

Removed all instances of longValue being unsafely called on BigInteger types

---

hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseThirtyMigration.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
hedera-node/src/test/java/com/hedera/services/state/migration/ReleaseThirtyMigrationTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
settings.gradle.kts

- Takes into account a fungible treasury return is really a _burn_ if the token is deleted or its treasury is missing (so only one adjustment in the `TokenTransferList`).
- Ensures the NFT link list rebuild truly resets any corrupt pointers. 😓 
- Updates SDK to `v0.30.0`.

Fix migration issues 

---

hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
hedera-node/src/test/java/com/hedera/services/state/logic/StandardProcessLogicTest.java

Fixes #3869
In order to solve the issue of a balance file with consensusTimestamp X, has all the child transactions and triggered long term scheduled transactions with T <= X be included in it,  
Deducted 1000 nanos from the consensusTime allotted by platform, when allocating to the transaction in services.

Allocate a reduced `consensusTimeStamp` to accommodate triggered transactions in balance file

---

hedera-node/src/main/java/com/hedera/services/txns/span/SpanMapManager.java
hedera-node/src/main/java/com/hedera/services/utils/accessors/PlatformTxnAccessor.java
hedera-node/src/main/java/com/hedera/services/utils/accessors/SignedTxnAccessor.java
hedera-node/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
hedera-node/src/test/java/com/hedera/services/txns/span/EthereumSpanMapManagerTest.java
hedera-node/src/test/java/com/hedera/services/utils/accessors/PlatformTxnAccessorTest.java
hedera-node/src/test/java/com/hedera/services/utils/accessors/SignedTxnAccessorTest.java
hedera-node/src/test/java/com/hedera/services/utils/accessors/TokenWipeAccessorTest.java
hedera-node/src/test/java/com/hedera/test/utils/TxnUtils.java

- Simplifies management of rehydrated calldata.
- Adds and refactors some unit tests.

Move re-usable test helpers under `TestUtils`, clean up rehydrated calldata mgmt

---

hedera-node/hedera-evm-api/build.gradle.kts
hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/PlaceholderApi.java
hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/package-info.java
hedera-node/hedera-evm-api/src/main/java/module-info.java
hedera-node/hedera-evm/build.gradle.kts
hedera-node/hedera-evm/src/main/java/com/hedera/services/evm/implementation/PlaceholderImplementation.java
hedera-node/hedera-evm/src/main/java/com/hedera/services/evm/implementation/package-info.java
hedera-node/hedera-evm/src/main/java/module-info.java
settings.gradle.kts

Signed-off-by: ivanparnarev <ivan.parnarev@limechain.tech>
This PR creates two new subprojects – hedera-evm and hedera-evm-api – under the hedera-node project in preparation for implementing EVM modularisation.

Add hedera-evm / hedera-evm-api submodules

---

.github/workflows/comp-compile-application-code.yaml
compose-build.sh

Removes the FOSSA actions from our CI pipelines due to the current outage at the third-party service level. 
- Closes #3982

Remove FOSSA support from the CI pipelines

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ApprovePrecompile.java
hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractLogAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java

A continuation of #3608, fixing emitter address in the rest of the functions, for which we emit events - `approve` and `setApprovalForAll`.
Fixes #3530

Fix wrong emitter address in `approve` and `approveForAll` precompiles

---

.github/workflows/flow-deploy-release-artifact.yaml

Resolves an issue with the Maven Central deployment for the `hedera-evm-api` artifact when merging into the `master` branch. Please see the related ticket for more details.
- Closes #3998

Maven Central release workflow failed on push due to missing fields

---

hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java
hedera-node/src/main/java/com/hedera/services/store/models/Token.java
hedera-node/src/main/java/com/hedera/services/txns/token/TokenOpsValidator.java
hedera-node/src/test/java/com/hedera/services/ledger/PureTransferSemanticChecksTest.java
hedera-node/src/test/java/com/hedera/services/store/models/TokenTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/BurnLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/MintLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenBurnTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenOpsValidatorTest.java
hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java

Fixes #3961 #3962 #3960 
Related to [HIP-564](https://hips.hedera.com/hip/hip-564)
- Allowed zero unit fungible token changes in `TokenTransfers`, `BurnLogic`, `MintLogic` and `WipeLogic`
- If no fungible/non-fungible units are present in a transfer it fails in the handle transaction.
- Added unit tests for the same
- Test plan is added [here](https://www.notion.so/swirldslabs/HIP-564-Zero-Unit-Token-Operations-in-Smart-Contracts-Test-Plan-32eee41855694fa086b9addb4f7ff303)

Allow zero unit token transfers

---

hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/CustomFeeSpecs.java
test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/CustomFeeTests.java
test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

**Notes to reviewer:**
- It's easier to review the test plan specs inline starting [here](https://github.com/hashgraph/hedera-services/blob/03397-implement-HIP-573-test-plan/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java#L2223) than through the diff, as this PR also fixes all the `TokenTransactSpecs` Sonar smells.
-  ‼️ All the HIP-573 tests fail at this time, since the feature implementation isn't merged to `master` yet. (Hence the commenting of them out.)
- Implements the [HIP-573 test plan](https://www.notion.so/swirldslabs/HIP-573-Blanket-Exemptions-for-Custom-Fee-Collectors-Test-Plan-05e9ebfb588b49c58b1552d4fba00fb0) as a [series of five EETs](https://github.com/hashgraph/hedera-services/blob/03397-implement-HIP-573-test-plan/t …

Implement HIP-573 test plan

---

.github/workflows/flow-build-application.yaml
.github/workflows/flow-deploy-release-artifact.yaml

Updates the Github Action workflows to properly trigger on the new `develop` branch and to stop triggering on the `master` and `main` branches where appropriate.
- Closes #4063

Update the new develop branch to ensure all workflows are triggering appropriately

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt

Cherry-picking these config changes from https://github.com/hashgraph/hedera-services/pull/4059

Revert "Remove `virtualMap.preferredFlushQueueSize` overrides" 

---

hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java

Signed-off-by: Michael Tinker <michael.tinker@swirldslabs.com>
Porting merged fix in `develop` https://github.com/hashgraph/hedera-services/pull/4065

Switch to `iterator()`

---

.circleci/config.yml

Updates the CircleCI cron jobs to only execute against the `develop` branch instead of the `master` branch.
- Closes #4098

Ensure CircleCI cron tasks run on the develop branch

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/initialization/BackedSystemAccountsCreator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/initialization/TreasuryCloner.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/initialization/BackedSystemAccountsCreatorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/initialization/TreasuryClonerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java

Fixes #3906 
- Published synthetic creations for all system accounts
- Changed `MigrationRecordsManager` to use `BackedSystemAccountsCreator` instead of `TreasuryCloner`
**Testing:**
1. Started a node from genesis and on first handle observed these logs for accounts creation from `800, 801`, `1-100`, `200-349`, `400-750`, and `900-1000`
```
2022-10-20 09:42:14.570 INFO  209  MigrationRecordsManager - Published synthetic CryptoCreate for staking fund account 0.0.800
2022-10-20 09:42:14.571 INFO  209  MigrationRecordsManager - Published synthetic CryptoCreate for staking fund account 0.0.801
2022-10-20 09:42:14.572 INFO  209  MigrationRecordsManager - Published synthetic CryptoCreate for treasury clone account 0.0.200
. …
```

Externalize system account creations

---

hedera-node/hedera-mono-service/build.gradle.kts

Resolves the issues with the Gradle `run` task due to classpath issues related to several PRs which restructured the folder and module layouts.
- Closes #4122

Resolve classpath issues with the Gradle run task

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesApp.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/StateModule.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesAppTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesStateTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/StateModuleTest.java

- Make the `Console` creator a bound instance of `ServicesApp.Builder` so we can avoid calling `SwirldGui.createConsole()` during unit tests.

Fix `ServicesApp` unit test

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/network/UpgradeActions.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/network/UpgradeActionsTest.java

Optional, avoids changing production code in this PR. (Shouldn't matter either way tho.)

Avoid change to prod code for `@TestDir` PR

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java

Fixes #4145 
Although the staking interceptor explicitly sets any stake-able account's value in the `stakePeriodStartUpdates` array, when `0.0.800` is added to the change-list in a reward situation, it will not always have a NA set in the `stakePeriodStartUpdates` array.
To avoid this reset the array for each transaction.

Fill `stakePeriodStartUpdates` array with `NA`

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/keys/impl/HederaEd25519Key.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/keys/impl/HederaKeyList.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/spi/keys/ByteBufferBackedInputStream.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/spi/keys/ReplHederaKey.java

- Provides default `ReplHederaKey` serde for `ByteBuffer` that delegates to `Serializable*Stream` implementation.
- Uses `ByteBufferBackedInputStream` to wrap a `ByteBuffer` in an `InputStream` without requiring the buffer to have an on-heap backing `byte[]` array.

Delegate to `Serializable*Stream` serde in `ReplHederaKey` default implementation

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/BalanceChange.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/TransferLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/AccountsCommitInterceptor.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/legacy/core/jproto/JECDSASecp256k1Key.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/legacy/core/jproto/JEd25519Key.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/MiscUtils.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/TransferLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/AccountsCommitInterceptorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
settings.gradle.kts
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

- Prevents user error auto-creating accounts with invalid keys.
- Fails faster on invalid balance change attempts.
- Cherry-picks [this](https://github.com/hashgraph/hedera-services/pull/4161) PR

Cherry-pick fixes for `v0.31.2`

---

.circleci/config.yml

Stop nightly regression to save cost.

Disable recovery test until new implementation is merged

---

hapi-utils/src/main/java/com/hedera/services/ethereum/EthTxSigs.java
hapi-utils/src/test/java/com/hedera/services/ethereum/EthTxSigsTest.java

- Ensures the 64-byte `signature` used in `EthTxSigs.extractSig()` verification is a concatenation of 32-byte curve points, _including_ any leading zeros.
- Closes #4180

Left-pad `(r, s)` curve points given to native library

---

test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java

* Adds E2Es asserting that all the HIP-583 functionalities included in the `release/0.32` branch are disabled and fail as expected when the flags related to HIP-583 are turned off
Fixes #

Add E2Es verifying HIP-583 CryptoCreate txns are not accepted when flags are disabled

---

hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java
hapi-utils/src/test/java/com/hederahashgraph/fee/FeeBuilderTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsage.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimatorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java

- Provides a different way to support directly adding fees _in tinycents_ to the charged price.
- Does this by updating `TxnResourceUsageEstimator` to signal via `hasSecondaryFees()` that the fee calculator should combine both the resource-scaled prices and the explicit secondary fees in its returned `FeeObject`.

Add `TxnResourceUsageEstimator` support for secondary fees

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml

This PR moves the swirlds-hashstream log file into a subdirectory within all log4j configs.

Move swirlds-hashstream log file to subdirectory

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java

- Closes #4166 
- Suppose `A` stakes to `B`, and `B` stakes to a node. This PR adds reward situations for `B` in three cases:
1. `A`'s balance changes, but **not** its number of whole hbars.
2. `A`'s balance is less than 1 whole hbar, and stops staking to `B`.
3. Some other account `C`  with balance less than 1 whole hbar **starts** staking to `B`.
- `B`'s total stake does not change in any of these cases, so there's no harm in not treating them as reward sitautions; but users have reported being surprised by this policy.

Match user expectations on indirect staking reward situations

---

.github/workflows/comp-build-release-artifact.yaml
.github/workflows/flow-deploy-release-artifact.yaml

Enhances the release workflows to remove Github features which are deprecated. Additionally, adds a new output to allow for the filtering of prerelease builds. Improves the workflow to not attempt a MC release if the prerequisite jobs have failed. 
The actual fix for publishing prerelease tag versions was made in [this commit](https://github.com/hashgraph/hedera-internal-workflows/commit/52c9d728e6f2e49052dd2aecae971210ef62a2a6) on the internal repository.
- Closes #4189

Fix Maven publishes of the EVM modules to properly respect prerelease versions

---

.github/workflows/comp-build-release-artifact.yaml
.github/workflows/flow-deploy-release-artifact.yaml

Updates the CI release pipeline to ensure that any Jenkins handoff failures will properly cause the GH Actions workflow to report the failure by failing in turn.
- Closes #4190

Enhance the release pipeline to ensure a failure if Jenkins fails to dispatch the job

---

.github/workflows/flow-pull-request-checks.yaml

Adds a concurrency group constraint to the PR Checks CI pipeline to prevent multiple PR updates from simultaneously running many jobs which could monopolize the available CI runners. 
- Closes #4260

Add concurrency group support to the PR Checks CI workflow

---

.gitignore
gradle.properties
test-clients/build.gradle.kts
test-clients/yahcli/Dockerfile
test-clients/yahcli/run/build.sh
test-clients/yahcli/run/refresh-jar.sh
test-clients/yahcli/yahcli

Address the issues reported by @tinker-michaelj in #4187 regarding the YahCli build not working.  This PR also ensure the YahCli docker image uses our standard `Adoptium Temurin OpenJDK 17` java version. It also ensure the docker image always uses UTF-8 encoding/character sets and the docker build scripts will function properly regardless of the current working directory. 
- Closes #4187

Fixes broken YahCli builds

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordBuilderTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

Fixes https://github.com/hashgraph/hedera-services/issues/4273
Sets the balances of accounts created in on synthetic creations export records
Tested by:
1. starting node at genesis
2. Do a CryptoCreate transaction paying with account 2.
3. Look at the child records of the transaction to have synthetic creation records. Only for Genesis account shows the balance on Created account record.
Top level record transfer list
```
, receipt {
status: SUCCESS
accountID {
accountNum: 2
}
}
transactionHash: "\r\222\243\0276 \340\027\226=\205\234\241\t\366[\237ik\006\230\211\004\221\262\213\360\325\255gDu\230\244f\252\203\020|\260\222N\371\000\317\345\252\364"
consensusTimestamp {
seconds: 1668116519
nanos: 219633498
}
transactionID {
transactionValidStart {
seconds: 1668116459
nanos: 792
}
accountID …
```

Set balance on synthetic creations export records

---

test-clients/src/main/java/com/hedera/services/bdd/spec/keys/TrieSigMapGenerator.java
test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromFile.java
test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigUtils.java
test-clients/src/main/java/com/hedera/services/yahcli/suites/SendSuite.java
test-clients/yahcli/README.md

- Extends the `accounts send` subcommand with `--denomination` and `--decimals` parameters to provide basic support for sending HTS token units.
- Amounts are expressed in whole units, relative to the `decimals` of the token being sent. 
* E.g. sending `1.23` units of USDC amounts to `1_230_000` units of the underlying token.
🎉 Also fixes the EET bug that left ECDSA signatures out of the full-prefix sig map ([this line](https://github.com/hashgraph/hedera-services/blob/df1dde313da950dc5e37a77e1e94192aae98b143/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/TrieSigMapGenerator.java#L128) was missing).

Add HTS fungible token transfers to yahcli

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java

Signed-off-by: Georgi Georgiev <georgi.getz@outlook.com>
A symbol was missing from one of the function hashes in AbiConstants, all other are in check

added missing symbol to function hash

---

test-clients/build.gradle.kts

... for both BDD and yahcli command line tool.
Fixes problem where if a yahcli command initalized log4j it would fail due to not being able to find log4j's jar.
- Added `libs.log4j.core` as a dependency
- Added `"Multi-Release" to "true"` to both manifests (BDD and yahcli)
- per https://stackoverflow.com/a/54713830/751579 (found by Nathan)
Signed-off-by: David Bakin <117694041+david-bakin-sl@users.noreply.github.com>
Fixes #4283 
I tested running `yahcli` only, not the bdd suite.
**Checklist**
- [*] Tested - ran the `yahcli` command line tool `validate` command which performs logging: works

Add `libs.log4j.core` as dependency in `test-clients`

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/sigs/order/SigRequirements.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/sigs/order/SigRequirementsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java

- Waives signature of a treasury for token w/ custom royalty + fallback fee when it's receiving an NFT of its type, since no fee will actually be assessed.
- Fixes #4245

Waive treasury sig if receiving NFT w/ fallback fee

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContractTest.java

- Always sets a `UtilPrngTransactionBody` in the synthetic transaction for a `PrngSystemPrecompiledContract` call.
- Fixes #4288

Always set a PRNG synth body (without range choice)

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/span/SpanMapManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/ethereum/EthereumTransitionLogicTest.java

- "Makes up" for a missed `preHandle()` call in `EthereumTransitionLogic` by explicitly calling `rationalizeEthereumSpan()` as needed.
Fixes #4285

Ensure `EthereumTransitionLogic` works during e.g. state recovery

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogicTest.java
test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java

* Alters `CryptoCreate` semantic checks to accept a txn with `ECDSA` key and `public address` alias (**which does not classify as a hollow account (lazy) creation**), independently of the current value of the `lazyCreation.enbaled` flag.
Fixes #4265

[HIP-583] Allow `CryptoCreate` txns with `ECDSA` key and `public address` alias when lazy creation flag is off

---

settings.gradle.kts

Only one Jackson Version is used
fixes https://github.com/hashgraph/hedera-services/issues/4237

jackson version fixed

---

hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmMessageCallProcessor.java
hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmMessageCallProcessorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaMessageCallProcessorTest.java

Fix an issue regarding executing unnecessary precompile methods resulting in additional child records creation.
**Related issue(s)**: #4160 
Fixes #
**Checklist**

Fix precompile operations order execution inside `HederaEvmMessageCallProcessor`

---

test-clients/build.gradle.kts

We have observed some CI runs with,
```
...
> Task :test-clients:itest FROM-CACHE 👈 🤔
> Task :hedera-node:hedera-app-spi:jar UP-TO-DATE
> Task :hedera-node:hedera-app:compileItestJava
> Task :hedera-node:hedera-app:processItestResources NO-SOURCE
```
The result is that no `HapiSuite`'s are actually executed---see for example [here](https://github.com/hashgraph/hedera-services/actions/runs/3517095134/jobs/5894475927).
This PR tries to enlighten Gradle on what module changes could actually cause `eet` or `itest` to fail.

Mark `eet` and `itest` dependencies explicit

---

gradle.properties
settings.gradle.kts

Bump services to 0.33.0-alpha.1
Bump platform to 0.33.0-alpha.3

New tag to bump platform version

---

hedera-node/hedera-mono-service/src/main/java/module-info.java

Fix module-info.java

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
hedera-node/settings.txt
test-clients/src/eet/resources/network/config/settings.txt
test-clients/src/itest/resources/network/config/settings.txt
test-clients/src/main/resource/testfiles/updateFeature/updateSettings/sdk/settings.txt

`state.roundsExpired` setting name is changed in platform to `consensus.roundsExpired`. 
Changed the same in Services and removed when value is same as default 500 .

Change setting to `consensus.roundsExpired`

---

hedera-node/configuration/preprod/settings.txt

This PR enables the Prometheus scrape endpoint for all preproduction environments.

Enable prometheus scrape endpoint for preprod

---

test-clients/build.gradle.kts

test-clients module missed correct version for grpc dependencies.

Hotfix to execute itests in IntelliJ

---

settings.gradle.kts

-  Fixes the `io.grpc` version conflict that causes all `develop` test clients to fail
- Closes #4433 
```
java.lang.AbstractMethodError: Receiver class io.grpc.netty.NettyClientTransport does not define or inherit an implementation of the resolved method 'abstract io.grpc.internal.ClientStream newStream(io.grpc.MethodDescriptor, io.grpc.Metadata, io.grpc.CallOptions, io.grpc.ClientStreamTracer[])' of interface io.grpc.internal.ClientTransport.
```

Use `0.33.0-grpc-1.45.1-SNAPSHOT` protobuf artifact

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/AccountStore.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/CryptoPreTransactionHandlerImpl.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/AccountStoreTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/CryptoPreTransactionHandlerImplTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/PreHandleCryptoTransferParityTest.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/TxnHandlingScenario.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/CryptoTransferFactory.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AdapterUtils.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/StateKeyAdapter.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TxnUtils.java
test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
test-clients/src/main/java/com/hedera/services/yahcli/suites/SysFileUploadSuite.java

- Adds factories under _testFixtures/_ to create [an `AccountStore`](https://github.com/hashgraph/hedera-services/blob/add-crypto-xfer-prehandle-tests/hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AdapterUtils.java#L66) and [a `TokenStore`](https://github.com/hashgraph/hedera-services/blob/add-crypto-xfer-prehandle-tests/hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AdapterUtils.java#L83) that contain the "well-known" entities used in `SigRequirementsTest` scenarios.
- "Replays" all relevant `CryptoTransferScenarios` against the new `CryptoPreTransactionHandlerImpl` in [this test](https://github.com/hashgraph/hedera-services/blob/add-crypto-xfer-prehandle-tests/hedera-node/hedera-mono-service/src/test/java/com/hed …

Adapt `SigRequirementsTest`, port `CryptoTransfer` scenarios, fix issues

---

test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StartStaking.java

- Adds a `StartStaking` suite to simplify the task of setting up staked accounts on a test network.

Create a test client to setup staked accounts and export CSV on e.g. previewnet

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenPreTransactionHandlerImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenPreTransactionHandlerImplTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenServiceImplTest.java

Fixes compile errors , due to some classes not moved from `hedera-mono-service`( belongs to`hedera-token-service-impl`)

Fix compile errors on develop

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/RewardCalculator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/RewardCalculatorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManagerTest.java

Even when using `estimatePendingRewards()` in `StakeStartupHelper.doUpgradeHousekeeping()`, there is a second path to hit `txnCtx.consensusTime()` through `StakePeriodManager.currentStakePeriod()`:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.time.Instant.getEpochSecond()" because "now" is null
at com.hedera.services.ledger.accounts.staking.StakePeriodManager.currentStakePeriod(StakePeriodManager.java:73) ~[main/:?]
at com.hedera.services.ledger.accounts.staking.StakePeriodManager.firstNonRewardableStakePeriod(StakePeriodManager.java:99) ~[main/:?]
at com.hedera.services.ledger.accounts.staking.StakePeriodManager.isRewardable(StakePeriodManager.java:103) ~[main/:?]
at com.hedera.services.ledger.accounts.staking.RewardCalculator.computeRewardFromDetail …
```

Avoid `txnCtx.consensusTime()` when recomputing rewards

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/proxy/ViewExecutor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactoryTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/proxy/ViewExecutorTest.java

- Don't use the `HTSPrecompiledContract#ledgers` to construct a `ViewExecutor`---these ledgers are subject to odd race conditions---or could even be `null` if the view function is running in a `ContractCallLocal` query!
- Instead use the frame updater's `WorldLedger`.

Use static ledgers to answer view queries

---

.github/workflows/comp-compile-application-code.yaml

- The `:hedera-node:hapi:test` task runs for multiple hours in CI and always fails. Skip it for now.

Skip PBJ unit tests in CI

---

hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTest.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java

This PR  enriches the exported in the evm-module  [UpdatedHederaEvmAccount](https://github.com/hashgraph/hedera-services/blob/111b0a75fd5dd6370ace30a257f199f03761d34e/hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java).
The changes makes it a suitable mutable account that can be called for transfers, check of account balance and get stored storage values.
Implementation for [HederaEvmStackedWorldStateUpdater](https://github.com/hashgraph/hedera-services/blob/111b0a75fd5dd6370ace30a257f199f03761d34e/hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java) `get` and `getAccount` methods also added. 
`The introduced  implementations are not final and will be …

Enriching evm-module's  account/updater  impl.

---

.github/workflows/comp-build-release-artifact.yaml
.github/workflows/comp-compile-application-code.yaml
.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-pull-request-checks.yaml

Updates the workflows to use the new ARC cluster and fixes remaining deprecation warnings due to `set-output` usage in the steps.
- Closes #4544

Migrate Actions workflows to new cluster 

---

.circleci/config.yml
test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java

Fixes https://github.com/swirlds/swirlds-platform-regression/issues/3013
Tests failed because a recent PR added 50 staking accounts creations in `CryptoTransfer` suite and the entity numbers hardcoded to validate needs to be changed.
[Passing tests Summary](https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1672774794921709)

Fix failing services tests

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
hedera-node/settings.txt

Added an override for the class path using setting
```
state.mainClassNameOverride,                   com.hedera.services.ServicesMain
```
This class path is used by Devops in their scripts

Add override for class path `state.mainClassNameOverride`

---

settings.gradle.kts

Incorporate platform version 0.35.0-alpha.0 into services code

Bump platform version

---

hedera-node/configuration/mainnet/bootstrap.properties
hedera-node/configuration/testnet/bootstrap.properties
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java

- Remove `cryptoCreateWithAliasAndEvmAddress.enabled` from _mainnet/bootstrap.properties_ and _testnet/bootstrap.properties_.
- Adds `Mockito.framework().clearInlineMocks()` to `ServicesStateTest` per @OlegMazurov.

Remove `0.34` properties from develop prod config files

---

test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/Network.java

- `defaultFeeInHbars` denomination is **hbars** but was being set to `100 * ONE_HBAR`. 🤕

Fix denomination of `FEE_TO_OFFER` in `ValidationScenarios`

---

settings.gradle.kts

- Update platform SDK to `0.34.2` and use the `v0.34.0` protobufs tag.

Prepare for v0.34.0 tag

---

.github/workflows/comp-build-release-artifact.yaml
.github/workflows/comp-compile-application-code.yaml
.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-pull-request-checks.yaml

This PR modifies the workflows and pins used third party actions from mutable release tags to the corresponding immutable SHA hash. This improves security and prevents the introduction of breaking changes on update of the used actions.
* Change workflows
Fixes #
**Checklist**

Pin used Github action to SHA hashes

---

.github/workflows/comp-compile-application-code.yaml
.github/workflows/flow-pull-request-checks.yaml

Allows the PR checks workflow to run on PRs from forks
* Removes a dependency on a third party action
Fixes #
This PR removes the use of the third party `verify-pr-label-action` and relies on the built in if checks which allows the workflow to work on PRs from forks, without requiring the use of the less secure `pull_request_target` event type.
The separate Label Check step is left for better readability of the workflow and to make it clear and easy to understand for everyone how to trigger the tests.
**Checklist**

Make PR checks run on PRs from forks

---

hedera-node/hedera-app/src/main/java/module-info.java

Fix the error faced while running `ServicesMain` on current develop.
```
2023-01-24 07:49:02.680 12       ERROR EXCEPTION        <main> Browser: 
com.swirlds.common.constructable.ConstructableRegistryException: Could not create a lambda for constructor: symbolic reference class is not accessible: class com.hedera.node.app.state.merkle.MerkleHederaState, from class com.swirlds.common.constructable.internal.GenericConstructorRegistry (module com.swirlds.common)
...........
Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class com.hedera.node.app.state.merkle.MerkleHederaState, from class com.swirlds.common.constructable.internal.GenericConstructorRegistry (module …
```

Fix ServicesMain run

---

hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt

This PR enabled the prometheus scrape endpoint for both previewnet and the stable testnet.

Enable prometheus scrape endpoint in previewnet and testnet

---

hedera-node/hedera-app-spi/build.gradle.kts
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/OverrideSignatureVerifier.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/SignatureVerifier.java
hedera-node/hedera-app-spi/src/main/java/module-info.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JContractIDKey.java

- Adds SPI types for the Hedera signature verification facility.
- ⚠️  Possibly controversial: Adds SPI dependency on `com.swirlds.common` to re-use platform's `VerificationStatus` enum.
- ⚠️ Also provocative: Claims in javadoc that there are three instances where business logic will at least participate in enforcing signing requirements (within an EVM system contract, before triggering a scheduled transaction, and evaluating the top-level signature on a `FileDelete`).

Define `SignatureVerifier` API

---

hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractEvmStackedLedgerUpdater.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockAccountAccessor.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdater.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MockLedgerWorldUpdater.java

This PR enrich the current hedera-evm module Updaters and HederaEvmWorldState to work with `HederaEvmWorldStateTokenAccount` adding a support for redirect token calls.
The flow tends to be a light mimic of the mono-services one with as litle duplication possible.
The workflow in this PR is being test from mirror-node side in [PR](https://github.com/hashgraph/hedera-mirror-node/pull/5206).
Follow-up [PR](https://github.com/hashgraph/hedera-services/pull/4894/files#diff-dbed0555410c6fe08e05b985f47fd2518053a381919a0b134ff683c5d76c44ac) with refactoring and removal of duplicated fields.
Fixes #4798

Adding support for Redirect Token Calls fro evm-module 

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
settings.gradle.kts

- Update to `v0.35.0` protobufs, validate that long-zero address cannot be used as an alias.

Use `0.35` protobufs

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java

Description:
Adds the pre handle logic for token dissociate
Fixes https://github.com/hashgraph/hedera-services/issues/4631

Implement TokenDissociateFromAccountHandler preHandle

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java

Description:
Adds the pre handle logic for token associate
Fixes https://github.com/hashgraph/hedera-services/issues/4604

Implement TokenAssociateHandler prehandle

---

hedera-node/docs/scheduled-transactions/revised-spec.md

Very minor change to the Schedule spec to modify the error code that is returned when someone tries to delete a schedule which has already executed or been deleted. Spec was out of alignment with how the code actually behaves. After discussion, decision was made to update the spec to reflect current behavior.
Fixes issue #4814

Minor spec update to reflect current behavior

---

hedera-node/configuration/testnet/bootstrap.properties
hedera-node/configuration/update/during-freeze.sh
hedera-node/configuration/update/immediate.sh

- enable node software compression of recordstream and account balance files for testnet
- minor updates to update scripts during-freeze.sh and immediate.sh to update headers and remove deprecated function

enable node software compression of recordstream and account balance files for testnet

---

hedera-node/configuration/mainnet/settings.txt

This PR updates settings.txt to enable the prometheus scrape endpoint. 
As this is now enabled in all configurations, we may also want to consider a follow-up before too long that enables the prometheus scrape endpoint by default.

Update mainnet settings to enable prometheus

---

.github/CODEOWNERS

This pull request updates the code owner definitions to properly assign maintainers to all files in the repository. Teams are assigned as maintainers with a few exceptions for several of the Hedera Node modules.
@poulok @nickpoorman Please review the line items relevant to your teams carefully and make any suggestions as PR comments. 
- Closes #5469

feat: update the repository code owner definitions

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
hedera-node/hedera-app/src/test/resources/bootstrap.properties
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/traceability/HederaEvmOperationTracer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java
hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/SolidityActionTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LogCaptor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LoggingSubject.java
hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java

**_Why_**
Finalization of the contracts actions (as part of the flow of producing `CONTRACT_ACTION` sidecars) was not performed when the frame state == `COMPLETED_FAILURE`. The state diagram in `org.hyperledger.besu.evm.frame.MessageFrame` shows you can't get to `COMPLETED_FAILURE` without going through `EXCEPTIONAL_HALT` - which _was_ being handled. But there we are.
(You can see the BESU state diagram [here](https://github.com/hyperledger/besu/blob/d48403d1852e270b2c58cc867885f448b04e1518/evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java#L86). It clearly shows you only get to `COMPLETED_FAILURE` by going first to `EXCEPTIONAL_HALT`.  But it shows the same for getting to `COMPLETED_SUCCESS` only after `CODE_SUCCESS` while our _existing_ code …

Fix action sidecars missing expected fields

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
hedera-node/hedera-app/src/test/resources/bootstrap.properties
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/traceability/HederaEvmOperationTracer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java
hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/SolidityActionTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LogCaptor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LoggingSubject.java
hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java

Signed-off-by: Hedera Eng Automation <swirlds-eng-automation@swirlds.com>
Cherry pick a fix to contract actions sidecar logic that 1) handles a state machine state that was missed before and 2) makes sure all fields of a contract actions sidecar are valid. 
Cherry picks #5192
Fixes #5169

Action sidecars missing field fix cherry-pick to 0.36

---

hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java

Changes required in mono-service to compile.
All but one test succeed. (`ServicesStateTest.testLoading0305State()` fails.)

Fixes required to make mono-service compile.

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkMetrics.java
platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBenchMerkleDb.java

Closes #5665.
Uses `UnixOperatingSystemMXBean.getOpenFileDescriptorCount()` where available (a no-op on Windows).
Also fixes metric registration for `CryptoBenchMerkleDb`.

5665:  Add a metric for open file descriptors to platform benchmarks

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/ReadableScheduleStoreTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleCreateHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerParityTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleHandlerTestBase.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleSignHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/serdes/MonoSchedulingStateAdapterSerdesTest.java

* Small changes for correct serialization in the MonoSchedulingStateAdapterCodec.
* Added missing imports and fixed method name change in ScheduleServiceImpl.
* Updated test base class to make compatible with intensified non-null requirements.
* Updated several tests to set mocking up better; the intensified non-null requirements require more mocks to return values.
* Adjusted serialization/deserialization testing to work with PBJ DataIO classes.
* Suppressed some unnecessary warnings in test classes
* Removed, for now, two tests for not-in-whitelist transactions.
* Those didn't actually test what was claimed, and what was tested, missing keys, throws NPE now, rather than failing.
* Added `@todo` comments to create proper tests for non-whitelisted transactions
**Related …

Fix Schedule Service to compile and pass unit tests with PBJ

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java

Be able to create strings of AddressBooks in the format used in Config.txt.  
Be able to create AddressBooks from the format used in Config.txt for unit testing purposes. 
- adds AddressBookUtils.java with the ability to parse an AddressBook from text used in config.txt
- adds unit tests for round trip serialization/deserialization and testing parse exceptions to AddressBookTests.java"
- adds `toConfigText()` method for rendering a config.txt compatible AddressBook to AddressBook.java
Fixes #5664 
**Checklist**

5664 - serialize / deserialize AddressBook to text compatible with config.txt

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualRecord.java

Used feature of Java 17 to seal `VirtualRecord` class. Now it's inheritance limited to `VirtualInternalRecord` and `VirtualLeafRecord`.
Fixes #5190 
**Checklist**

05190 Made VirtualRecord sealed

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SwirldState.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

Updates the address book through the `SwirldState` on version upgrade.  If there is no version upgrade, the address book loaded from the saved state on disk is used.   If there is no `SignedState` loadable from disk, the address book is initialized by the genesis `SwirldState`.  This solution moves the construction of the `EmergencyRecoveryManager` and loading of the `SignedState` from disk to `Browser.java` so that the `AddressBookInitializer` can determine the address book to pass to the `SwirldsPlatform`. 
- adds `AddressBookInitializer.java`
- adds `updateStake(AddressBook, AddressBook)` method to SwirldState.java
- adds `sameExceptForStake(AddressBook, AddressBook)` method to AddressBookValidator.java
- adds `toConfigText()` method to AddressBook.java
- adds …

5475 - Initialize Address Book On Startup

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/ConcurrentArrayTest.java

Closes #5717.
Merging `ConcurrentArray` copies is now constant time.

5717: Improve VirtualNodeCache.merge

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/ConcurrentArrayTest.java

5793: ConcurrentArray.merge() may fail to correctly compute the resulting size

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ApprovePrecompile.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java

- Addresses #5608 but does not include migration records.
- Sets `msg.sender` as `ownerId` in synthetic `ApproveAllowance` txn.

Include `ownerId` in synthetic child `ApproveAllowance` txn

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/MonoSignaturePreparerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/FeeCalculatorModule.java

Use FCHashMap for aliases. Closes #5843.
The implementation makes `MerkleHederaState` the owner of the aliases map. It remembers to make fast-copies of it when needed, and makes the current version available through `StateChildrenProvider`.

Use FCHashMap for aliases so they are versioned

---

hedera-node/configuration/dev/bootstrap.properties
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/log4j2.xml
hedera-node/configuration/testnet/settings.txt
hedera-node/hedera-app/src/test/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/contracts/SizeLimitedStorageBench.java
hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/setup/Constructables.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties

Fix summary:
* Added MERKLE_DB marker to all log4j2 configs, next and similar to the existing JASPER_DB one
* Enabled MerkleDb by default in test resources (I don't think it has any effect on most tests, since tests usually use JasperDB explicitly; although some high-level tests may switch to MerkleDb)
* Enabled JasperDB to MerkleDb migration in "dev" configuration, while having it disabled in all other configs (testnet, mainnet, previewnet) - need somebody from the devops team to check this, who will be impacted and how
Fixes: https://github.com/hashgraph/hedera-services/issues/5314

5314: JasperDB to MerkleDb: logs and settings

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

- adds `cleanAddressBookDirectory()` to AddressBookInitializer.java
- adds synchronized on methods which touch the file system.
- moves `forceUseOfConfigAddressBook` to AddressBookConfig.java
- adds `addressBookDirectory` to AddressBookConfig.java
- adds `maxRecordedAddressBookFiles` to AddressBookConfig.java
- replaces some arguments to the AddressBookInitializer constructor with an instance of AddressBookConfig.
Fixes #5738 
Tested Manually
**Checklist**

05738 - deletes old saved address books

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java

Fix summary:
* `HalfDiskHashMap` is improved to make use of the latest changes in `DataFileWriter`: ability to read entries before the file is fully written
Fixes: https://github.com/hashgraph/hedera-services/issues/5869

5869: Faster bucket index updates in HalfDiskHashMap

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java

Fixes a startup crash
* changed access of `appsMain.get(0L)` to an iteration over the values for the first next() value. 
Fixes #5895

05895 - fixing startup crash due to new SwirldMain configuration

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java

- Fixes: When an EthereumTransaction creates a contract whose constructor calls selfdestruct, the record contains a "nonsense" ContractID=A.B.C corresponding to the 0xA...BC EVM address instead of the 0.0.X id
- Eliminates assumption that a newly created contract's EVM address will still be linked at the end of its creating transaction. (Not the case if the constructor calls selfdestruct.)

Cherry pick - Use mirror address of selfdestruct-ed creation in record

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacadeTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java

- Fix convertLeftPaddedAddressToAccountId() to, instead of generating a A.B.C id from an account referenced in a precompile via missing EVM address, generate a 0.0.<alias=0xA...BC> id in the synthetic transaction body.
- Update downstream code to respect this original alias when it is set.

cherry pick Fix AccountID's generated from missing EVM addresses

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java

Whenever one invokes `DataFileWriter#finishWriting` on Windows OS, it fails with the following exception:
```
<merkledb: Store Internal Records #0> ERROR MerkleDbDataSource [mergeThenInterrupt] Failed to store internal records
java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
at sun.nio.ch.FileDispatcherImpl.truncate0(Native Method) ~[?:?]
at sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:90) ~[?:?]
at sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:437) ~[?:?]
at com.swirlds.merkledb.files.DataFileWriter.finishWriting(DataFileWriter.java:310) ~[main/:?]
at com.swirlds.merkledb.files.DataFileCollection.endWriting(DataFileCollection.java:649) ~[main/:?]
at …
```

05908 Fixed DataFileWriter.finishWriting for Windows

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java

A few minor changes to HDHM `Bucket` class:
* New ByteBuffer API is used in `putValue()` as proposed in #5188
* `getKeySize()` call is skipped for the last entry in `findEntryOffset()` as proposed in #5179 
* Fixed `getValue()` and the corresponding unit test - wrong offset in the bucket buffer was used
* Changed `FindResult` to a record and added "entryValue" field to it
* A few JavaDoc updates
Fixes: https://github.com/hashgraph/hedera-services/issues/5179
Fixes: https://github.com/hashgraph/hedera-services/issues/5188

5179: Bucket.findEntryOffset() can reduce calls to getKeySize()

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileTests.java

Change the file name for preconsensus event stream files.

---

hedera-node/hedera-mono-service/build.gradle.kts
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKey.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/ContractKeyTest.java

- Reinstates original `ContractKey.hashCode()` implementation with some test vectors created using the `v0.35.3` tag.
- Adds the Dagger2-generated code to the `mono-service` source set to avoid some build annoyances.

Revert to `v0.35.3` `ContractKey.hashCode()`

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java

- Fix `MixedValidationsAfterReconnect` numbers one more time (there are 299 blocklist accounts, not 300).

Decrement entity numbers (299 not 300 blocklist accounts)

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java

Every time a state is saved, a human readable form of the state's address book is written in the directory where the state is saved to. 
- adds `STATE_ADDRESS_BOOK_FILE_NAME` to SignedStateFileUtils.java
- adds `writeStateAddressBookFile()` method to SignedStateFileWriter.java
- adds assertion to unit test to verify existence of written address book.
Fixes #5987 
**Checklist**

05987 - write human readable state address book during state save.

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml

Updates the log4j2 appender configurations to enable time and size based rollovers with automatic cleanup. Additionally, this enables automatic gzip compression of archived logs.
- Closes #4745

fix: update log rollover configuration

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

- removed use of genesis state supplier from AddressBookInitializer.java
- updated code and unit tests to always use config address book when state is not loaded.
Fixes #6077 
**Checklist**

6077 - if no state is loaded, always use config address book.

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/BootstrapUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

Fixes bug where forcing the use of the config.txt address book would bypass the check and exception throw on software version downgrade.   The version comparison is moved to the browser, immediately after loading any saved signed state. 
Fixes #5930

05930 - fix address book init on software downgrade

---

platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/module-info.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SwirldState.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookValidator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Network.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java

The following changes allow automated testing through JRS without recompiling.
* moves `isOwnHost` check from `equalsWithoutStake` to `equals` in Address.java
* adds AddressBookTestingToolConfig.java with `softwareVersion` and `stakingBehavior` settings.
* updates README.md instructions to use the new settings instead of recompiling.
* updates softwareVersion through settings in AddressBookTestingToolMain.java
* updates stakingBehavior through settings in AddressBookTestingToolState.java
* validates the different testing scenarios in AddressBookTestingToolState.java
Fixes #5584 
**Checklist**

05584 - automating address book initialization tests

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AccountCustomizer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizer.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizerTest.java

- Closes #6109 
- Instead of setting `0.0.0` for an unused auto-renew account id, leaves `ContractCreateTransactionBody`'s `auto_renew_account_id` field unset as expected.

Omit auto-renew id if unused in synth `ContractCreateTransactionBody`

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java

* Adds more tests to the `HollowAccountFinalizationSuite`:
* [ Completion of 2 hollow accounts in a single txn](https://github.com/hashgraph/hedera-services/pull/5918/files#diff-05c4149f73fcae50993b79b8a27a30e03ecf321ec940b8974a77b63676c9d53cR748) 
* [Completion of a hollow account even when the transaction fails](https://github.com/hashgraph/hedera-services/pull/5918/files#diff-05c4149f73fcae50993b79b8a27a30e03ecf321ec940b8974a77b63676c9d53cR806) (cryptoTransfer failing with `INSUFFICIENT_BALANCE`
* [A `ContractCall` calling the precompile, where the executed precompile function needs signature for the hollow account (and it is provided in the `unusedFullPrefixSigs`) does not finalize the hollow account](https://github.com/hashgraph/hedera-services/pull/5918/files#diff-05 …

Add more hollow finalization tests

---

hedera-node/cli-clients/build.gradle.kts
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/ExamplePcliPlugin.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SummarizeSignedStateFileCommand.java
hedera-node/cli-clients/src/main/java/module-info.java
hedera-node/hedera-mono-service/src/main/java/module-info.java
settings.gradle.kts

Example pcli plugin implements one command - summarize a signed state file. This is simply a command I had at hand that uses services functionality (specificially `hedera-mono-service`) on top of platform functionality.
Purpose is to
1) enable development of pcli plugins in the services repo, and 
1) provide a working example as PoC.
Fixes #5694 
To execute, change directory to `platform-sdk/swirlds-cli` and execute
```
./pcli.sh --load ../../hedera-node  example summarize -f <path-to-a-SignedState.swh>
```
(Takes about 12s to start on my laptop, just to provide help.  Then it takes ~25s on top of that to read the signed state file.)
**Checklist**

Enable writing pcli plugins in `hedera-services` and provide an example plugin

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java

- Sets msg.sender as ownerId in synthetic createApproveAllowanceForAllNFT txn.
Fixes #6135 
**Checklist**

Include ownerId in synthetic child createApproveAllowanceForAllNFT txn

---

hedera-node/configuration/previewnet/bootstrap.properties

Update for bootstrap.properties file for previewnet to turn on the Shanghai version of the EVM for previewnet

Turn on the Shanghai version of the EVM in previewnet

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoFeeAccumulator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoGetTopicInfoUsage.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoFeeCalculator.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoFeeAccumulatorTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoGetTopicInfoUsageTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactoryTest.java
hedera-node/hedera-consensus-service-impl/build.gradle.kts
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ReadableTopicStoreImpl.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/TopicStore.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ReadableTopicStoreImplTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/AdapterUtils.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerParityTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/module-info.java
hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/ReadableTopicStore.java
hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/TopicMetadata.java

This PR migrates the ConsensusService to the new design:
- Makes the `preHandle()` method generic. It has only one parameter `context` and is defined in `TransactionHandler`.
- Introduces interfaces for each store (e.g. `ReadableTokenStore`) in the corresponding api-module
- Adds the suffix 'Impl' to names of store implementations (e.g. `ReadableTokenStoreImpl`). The classes implement the new interfaces.
- `PreHandleContext` will become an interface in an upcoming PR. To prepare this change, `FakePreHandleContext` was introduced and tests were updated. This class allows to do the switch without breaking all the tests in services.
- We will stop to use `AccountAccess` soon. Instead the new interface `ReadableAccountStore` should be used instead.

Migrated ConsensusService to new design

---

hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/ReadableSpecialFileStoreImpl.java
hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/handlers/FreezeHandlerTest.java
hedera-node/hedera-admin-service-impl/src/test/java/module-info.java
hedera-node/hedera-admin-service/src/main/java/com/hedera/node/app/service/admin/ReadableSpecialFileStore.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java

This PR migrates the AdminService to the new design:
- Makes the `preHandle()` method generic. It has only one parameter `context` and is defined in `TransactionHandler`.
- Introduces interfaces for each store (e.g. `ReadableTokenStore`) in the corresponding api-module
- Adds the suffix 'Impl' to names of store implementations (e.g. `ReadableTokenStoreImpl`). The classes implement the new interfaces.
- `PreHandleContext` will become an interface in an upcoming PR. To prepare for this change, tests were updated.
- We will stop to use `AccountAccess` soon. Instead the new interface `ReadableAccountStore` should be used instead.

Migrated AdminService to new design

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiry.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryProcess.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/SystemTask.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TaskModule.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTask.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiryTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/ExpiryProcessTest.java

Signed-off-by: David Bakin <117694041+david-bakin-sl@users.noreply.github.com>
Traceability migration should run when the migration feature flag is on (and there are contracts which haven't been migrated.  But in fact it was _also_ gated on `autoRenew` entities having been enabled.  And too it _also_ needed
to be listed in `TaskModule` so dagger would include it as a system task to run.  Both done here.
And a one-time info-level log message is emitted the first time the traceability task is invoked.  After that you can look
for "n-thousand contracts exported" messages (not the exact text) to see progress.  (But the current system task
API doesn't allow for a "migration done" message.)
Fixes #6256
**Checklist**

Traceability migration now gated only on migration feature flag

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java

Scale up the consensus weights [0, 500] to [minStake, maxStake] while exporting to mirror node

Scale up weights while exporting to mirror node

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/PostOrderedDepthFirstRandomAlgorithm.java

Closes #6278 
Emergency mitigation for performance issue noticed by Oleg where calling `parent.getNumberOfChildren()` ends up being very expensive due to the way Java does inheritance and virtual methods.
This is not a full fix, but will reduce the number of times this method is called to 1/4th its previous number (for binary trees).

Call getNumberOfChildren() less in iterator.

---

platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
platform-sdk/sdk/settings.txt
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java

Don't require signing keys when doing event stream recovery.

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java

Instead of using the test config and doing a full class scan the AppTestBase class use a basic config that only knows about the metrics config.

AppTestBase use simple config

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SynthApprovalRecordsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/AssertingBiConsumer.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/BaseIdScreenedAssertion.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/IdScreenedAssertion.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/TransactionBodyAssertion.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java

- Closes #6262 
- Updates `TransferPrecompile` to produce a synthetic `CryptoTransferTransactionBody` with `is_approval = true` for each asset change that was automatically switched to use an approval/allowance.
- Includes EET to verify this behavior using a new `RecordStreamAssertion` implementation.

Distinguish auto-approvals in synthetic `CryptoTransfer` transfer lists

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/SignedStateViewFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/SignedStateViewFactoryTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
settings.gradle.kts

Use latest platform adhoc build. The latest platform build caused two sets of breaking changes in services build. Both stem from PR #6142
1) Platform.getLatestImmutableState now takes a String as an argument, the reason why the signed state is being retrieved. This is for debugging if there is ever a state reference leak. It is only logged when there is a leak. I used the name of the method making the call in most places.
2) SignedStateFileReader.readStateFile method signature changed, both the parameters and the return type. @cody-littley and @david-bakin-sl helped me figure out how to update the code to use the new signature.

6316 bump platform version 38 adhoc

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompileTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

- Closes #6268 
- Adds a `boolean mergeUnsetMemoFromExisting` flag to `TokenUpdateLogic.updateToken()` so that when client code cannot properly signal the difference between an _unset_ `memo` field and an _empty_ `memo` field, we don't unconditionally clear the token's existing memo.
- This is relevant when the client code is an `updateToken()` system contract, whose current ABI does not let it distinguish between a contract (1) leaving the `memo` field unset and (2) explicitly setting `memo = ""` to erase the memo.

Only clear memo in `TokenUpdateLogic` if client code can signal unset vs empty

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fix summary:
* Virtual node cache initialization is moved from `VirtualRootNode` constructor to its `postInit()` method. If a root node is created from scratch, deserialized from a snapshot, or initialized during reconnects, its cache will be created in `postInit()`. When a root node is a copy of another root node, the cache will be set directly in the copy constructor.
Fixes: https://github.com/hashgraph/hedera-services/issues/5199

5199: VirtualRootNode constructor creates a cache object that doesn't get reused

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiry.java
hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiryTest.java

- Eliminates `EntityAutoExpiry` overhead post-traceability migration by aborting `execute()` as soon as all pre-existing entities are scanned.

Abort `EntityAutoExpiry` cycle immediately once all entities are scanned

---

platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md

06329: Update AddressBookTestingTool README.md

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/DefaultSignedStateValidator.java

Fix string formatting bug

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookUtils.java

This PR targeting the develop branch contains the commit that is targeting the release/0.38 branch in PR #6334 
- Changed the default to `false` in AddressBookConfig.java
- Fixed bug in Demo GUI using `Address.isOwnHost()` on state loaded AddressBook in AddressBookUtils.java
Fixes #6331

06331 - `AddressBook.forceUseOfAddressBook` default setting to false

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/singleton/ConfigurationHolder.java

Fixes https://github.com/hashgraph/hedera-services/issues/6429

Only com.swirlds is scanned by ConfigurationHolder

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java

06479 - AddressBookInitializer do not validate state loaded addressbook

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java

Closes #6479
Prior Behavior: 
* During restarts that did not have a software upgrade, if the state loaded address book differed from the config.txt address book in any way other than stake values, the config.txt address book would be used with a warning.  
New Behavior
* During restarts that do not have a software upgrade, the state loaded address book is always used.

Cherry-Pick into v0.38 for 06479 - AddressBookInitializer skip validating state loaded addressbook

---

.github/workflows/node-flow-fsts-daily-interval-05.yaml

We have no longer maintain the saved state file used in this performance test,
and also the performance test will be covered by perfNet test

Remove HTS performance test from nightly regression

---

platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/config/TestConfigBuilder.java

Method name was wrong based on copy&paste error ;)

Method name in TestConfigBuilder fixed

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java

- Fixes `canAutoCreateWithFungibleTokenTransfersToAlias()` flakiness (c.f. #6486) by recognizing that varying `pubKeyPrefix` overlap lengths will change `SignatureMap` size, which will slightly change the fee charged.
- Adds logging to improve diagnosis of `canCreateViaFungibleWithFractionalFee()` failure.

Accommodate varying sig map sizes in `canAutoCreateWithFungibleTokenTransfersToAlias()`

---

hedera-node/test-clients/build.gradle.kts
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
hedera-node/test-clients/validation-scenarios/Dockerfile
hedera-node/test-clients/validation-scenarios/assets/screened-launch.sh
hedera-node/test-clients/validation-scenarios/run/build.sh
hedera-node/test-clients/yahcli/run/publish.sh

- Closes #6478 
- Updates `contract` validation scenario to send 1 tinybar in value to `0.0.800` instead of bootstrap payer (since in dev env this is may be an account in precompile range).
- Adds Docker build assets, publishes `gcr.io/hedera-registry/validation-scenarios:0.1.0`
- Follows yahcli bind mount convention, typical usage would be,
```
docker run -e BOOTSTRAP_PASSPHRASE=swirlds \
-v $(pwd):/launch gcr.io/hedera-registry/validation-scenarios:0.1.0 \
target=localhost novel=true scenarios=staking,contract,xfers
```

Add Dockerfile, publish `gcr.io/hedera-registry/validation-scenarios:0.1.0`

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/NodeToSend.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualLearnerTreeView.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTeacherTreeView.java

A minor improvement to skip sending redundant class IDs during virtual node reconnects. All leaf nodes processed by `VirtualTeacherTreeView` and `VirtualLearnerTreeView` are always instances of `VirtualLeafRecord`, so there is no need to (de)serialize them as generic serializable objects.
I tried to enhance the fix to also skip sending virtual key/value class IDs, but it appeared to be complicated. On the teacher side there is no information about keys/values other than compile-time generic types. There is no class ID to send to the learner, there is no way to have a self-serializable supplier (similar to JasperDB's `SelfSerializableSupplier`) without virtual map API changes.
Testing: existing unit tests cover these changes.
Fixes: https://github.com/hashgraph/hedera-services/issues/6524 …

6524: Skip sending class IDs for virtual leaf records during reconnects

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/BurnWrapper.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/MintWrapper.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/BurnPrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MintPrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractAbis.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractTypes.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/UpdateTokenExpiryInfoPrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/WipeFungiblePrecompile.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/BurnPrecompilesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/MintPrecompileTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SystemContractAbisTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/UpdateTokenExpiryInfoPrecompileTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/WipeFungiblePrecompileTest.java

(Essentially a cherry-pick from develop, but done on my machine before the merge to develop happened.  See #6564 for the original PR.)
Start of a new method for having one-stop-shopping for everything we
need related to system contract ABIs.  (Subsequent additions will
include _all_ system contract ABIs, and then moving to use this enum
as the source of ground truth for ABI (names, selectors, etc.)
everywhere.
**N.B.:** The initial goal of this is to simplify correct maintenance by putting everything related to our ABI in one place, instead of being scattered all over the place the way it is now.  The ultimate goal is to _generate_ this enum from the ground truth Solidity system contracts in our smart contracts repo.
Of the versioned ABIs, in this PR are: burn, mint, update token expiry …

0.38.x: Move (some) signatures and decoders of versioned ABIs to a dedicated location

---

platform-sdk/swirlds-platform-core/src/main/java/module-info.java

Export the uptime package to the config package.

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ReusableBucketPool.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/ReusableBucketPoolTest.java

Closes #6585
Use straightforward `ConcurrentLinkedDeque` in `ReusableBucketPool`.
Control the number of concurrent read tasks in `HalfDiskHashMap.endWriting()` to limit the number of outstanding `Buckets` sitting in the output queue.

6585: ReusableBucketPool synchronization redone

---

platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java

Closes #6627.
Null all internal references when `FCQueue` is destroyed.

6627: FCQueue is not properly destroyed

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/HapiUtilsTest.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/SubmissionManagerTest.java

Closes #6636 
`SubmissionManager` can ignore the `RecordCache` and have its own expiry cache. This makes it really easy to understand the behavior of the system and nullifies some potential problems with dishonest nodes. Most importantly, the question the `SubmissionManager` has to answer is "Have I seen this transaction ID submitted to me already?". It needs to answer this question because the node does not want to submit duplicate transactions (since if it does, it has to pay for it). It doesn't need to know anything about what transactions other nodes have seen or what the ultimate resolution of a transaction is. It just needs to say "within the valid transaction ID lifespan, have I seen this transaction submitted by a user before"? This allows us to keep the implementation very simple …

Implement complete SubmissionManager with expiry dedupe cache

---

platform-sdk/swirlds-cli/color-logs.py
platform-sdk/swirlds-cli/pcli.sh

Closes #6667 
In this PR, PCLI colorizes log output sent to the console. It elegantly handles situations where python is not installed, and will not add color to the output if the `--no-color` flag is present.

06667 colorize pcli logs

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java

This PR adds `fullLeafRehash` call to `VirtualMap` instances created by `VirtualMerkleStateInitializer` in `PlatformTestingTool`
Fixes #6651 
This test should fix https://github.com/swirlds/swirlds-platform-regression/issues/3411

06651 Added missing rehash for VirtualMap leaves

---

hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/ContractKeyTest.java

**Description**: We recently copied the hashCode function from Platform into Services. We need to ensure that the result of this hash code never changes or risk data ending up in a corrupted state, (under incorrect keys).
Fixes #6581

Added comment that hashCode test values must not be changed

---

.gitignore
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreCheckException.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java

Added initial methods to PreHandleContext for optional keys and optional hollow accounts, and skeleton implementations in implementing classes.
Also fixed a minor issue in PreHandleContext leftover from earlier work.
**Changes**:
* Removed unnecessary (and always ignored) response code parameter from PreHandleContext create inner context.
* Added methods to PreHandleContext to add one optional key, or a Set of optional keys
* Added a method on PreHandleContext to return the Set of optional keys
* Added a method on PreHandleContext to add one optional hollow account
* Added a method on PreHandleContext to return the Set of optional hollow accounts
* Added base implementations for the new methods
* Adjusted AbstractScheduleHandler to process the inner context correctly and …

Add optional keys and optional hollow accounts to pre-handle context

---

hedera-node/configuration/mainnet/upgrade/feeSchedules.json
hedera-node/configuration/mainnet/upgrade/throttles.json
hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json
hedera-node/hedera-mono-service/src/main/resources/throttles.json

- The _throttles.json_ and _feeSchedules.json_ resources [here](https://github.com/hashgraph/hedera-services/tree/develop/hedera-node/hedera-mono-service/src/main/resources) and [here](https://github.com/hashgraph/hedera-services/tree/develop/hedera-node/configuration/mainnet/upgrade) don't reflect the current contents of system files `0.0.111` and `0.0.123` on mainnet. 
- This PR updates these resources from mainnet system files to avoid confusion.

Reflect mainnet 0.0.111 (fees) and 0.0.123 (throttles) contents in repo

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java

Current MAX_FULL_REHASHING_BUFFER_TIMEOUT equals to 10 seconds. Performance testing demonstrated that it's not enough. Increase MAX_FULL_REHASHING_BUFFER_TIMEOUT to 60 seconds. I chose 60 seconds because we have a similar hashing mechanism for the reconnect. It has the same buffer size (10,000,000) and timeout of 60 seconds. My reasoning is that if it's enough for the hashing during reconnect, it should be enough for rehashing of 10m leaves as well.
**Update:** Oleg suggested following improvements:
- instead of having a timeout on iterator, let's fail the whole rehashing if it can't make it on time. The timeout is set to 6 hours.
- to rehash a prod-sized virtual map it may take up to 3-4 hours. It necessary to see if it's making any progress. I added progress-tracking …

06716 MAX_FULL_REHASHING_BUFFER_TIMEOUT is increased to 60 seconds.

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottleTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTask.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTaskTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/ThrottleGaugesTest.java

- Closes #6706 
- When setting a gauge metric for throttle utilization, instead of calling `percentUsed(Instant)` (which simulates leaking capacity until the given time), just sets the metric to utilization at the last decision time for the throttle.
- 😢 Note the regrettable duplication in the `Gas*` variants; will not be fixed here.
- Also switches the `freeToUsedRatio(Instant)` method to be an instantaneous measurement to fix an annoying problem that can surface in `TraceabilityExportTask`.

Use instantaneous capacity checks for gauges and `TraceabilityExportTask`

---

.github/workflows/platform-zxcron-release-jrs-regression.yaml
.github/workflows/zxc-jrs-regression.yaml

Update the daily CI tasks to use a regex which properly supports the `hedera-services` release branch names.
- Closes #6708

fix: updates daily CI tasks to properly handle the release branch names

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/meta/GetTxnRecordAnswer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/DeletionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/meta/GetTxnRecordAnswerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/DeletionLogicTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractDelete.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java

- Closes #6593 
- Fixes `getTransactionRecord` validity check, which treated a deleted account as an invalid `TransactionID#accountID` field.

Allow queried `TransactionID` to have deleted payer account

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java

Fixes #6737 
Not a cherry pick from develop, but performs the same logic as PR #6740 
original `config.txt`: 
```
swirld, 123
app,		HashgraphDemo.jar,	   1,0,0,0,0,0,0,0,0,0, all
address,  A, Alice,    1, 127.0.0.1, 15301, 127.0.0.1, 15301
address,  B, Bob,      1, 127.0.0.1, 15302, 127.0.0.1, 15302, has a memo
address,  C, Carol,    1, 127.0.0.1, 15303, 127.0.0.1, 15303
address,  D, Dave,     1, 127.0.0.1, 15304, 127.0.0.1, 15304, has a memo2
```
output of `currentAddressBook.txt`:
```
address, A, Alice, 1, 127.0.0.1, 15301, 127.0.0.1, 15301              
address, B, Bob,   1, 127.0.0.1, 15302, 127.0.0.1, 15302, has a memo  
address, C, Carol, 1, 127.0.0.1, 15303, 127.0.0.1, 15303              
address, D, Dave,  1, 127.0.0.1, 15304, 127.0.0.1, 15304, has a memo2 
```

06737 - AddressBook.toConfigText() Supports Memo Field

---

hedera-node/data/config/bootstrap.properties

- Revert _data/config/bootstrap.properties_ from [this PR](https://github.com/hashgraph/hedera-services/pull/6718/files) since these are actually used in JRS tests and will cause problems tonight.

Revert on-disk, consolidated FCQ dev overrides

---

.github/workflows/platform-zxcron-release-jrs-regression.yaml
settings.gradle.kts

Bump platform version to 0.38.3
Fixes #6771 
Note: Tests will not pass for this PR until platform 0.38.3 is uploaded to Maven Central.

Bump platform version to 0.38.3

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AddresBookUtils.java

Fixes https://github.com/hashgraph/hedera-services/issues/6778
Updates weights of newly added nodes to 0, irrespective of the weights specified in `config.txt`

Update zero weights for new nodes

---

platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java

Closes #6763.
Also fixes NPEs when a destroyed copy of `FCQueue` is accessed (from tests and `MerkleTreeVisualizer`).

6763: FCQueue.getHash() is a hashing bottleneck

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/EthereumTransferToRandomEVMAddress.java

- Closes #6774 
- Since it is possible for `addressAliasIdFuzzing()` [to create an account with `receiverSigRequired=true`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java#L87), it is possible for [`EthereumTransferToRandomEVMAddress`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/EthereumTransferToRandomEVMAddress.java#L59) to be using an `EthereumTransaction` to send value with a `to` address with `receiverSigRequired=true`.
* But then we fail [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono …

Allow `INVALID_SIGNATURE` status on `EthTx` value sent to EOA with `receiverSigRequired=true`

---

hedera-node/configuration/dev/bootstrap.properties
hedera-node/data/config/bootstrap.properties

Fixes: https://github.com/hashgraph/hedera-services/issues/6794

6794: Enable data on disk and MerkleDb for nightly services runs

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
hedera-node/hedera-config/build.gradle.kts
hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/BytesConverter.java
hedera-node/hedera-config/src/main/java/module-info.java
hedera-node/hedera-config/src/test/java/com/hedera/node/config/PropertySourceBasedConfigTest.java
hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/BytesConverterTest.java
hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java

Bytes Converter added for Config

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottleTest.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottleTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTask.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTaskTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/ThrottleGaugesTest.java

- Allows us to run `TraceabilityExportTask` without contracts being skipped if desired in 0.38.

Use instantaneous capacity checks for gauges

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Accessing hashes before they are computed causes exceptions in the database.
[Partially?] fixes #5383.

5383: IOException during warm() call

---

hedera-node/configuration/previewnet/bootstrap.properties
hedera-node/data/config/bootstrap.properties

Sunset old security model for smart contracts by changing the HAPI signature check block boundary to 0 (from 10M).
Pushing this for PREVIEWNET and node running locally in the repo only.
Tested by confirming that contract itests running locally against the repo node now _fail_ as expected.
Signed-off-by: David Bakin <117694041+david-bakin-sl@users.noreply.github.com>
Partial f*x of #6767 
**Checklist**

PREVIEWNET, LOCAL: Sunset old security model for smart contracts

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
settings.gradle.kts

- Syncs proto artifact with [latest merge to `add-pbj-types`](https://github.com/hashgraph/hedera-protobufs/commits/add-pbj-types-for-state).

Update HAPI version

---

settings.gradle.kts

**Description**: Update Release/0.39 branch hedera-protobufs tag to fix the compile errors:
Could not determine the dependencies of task ':hedera-node:test-clients:yahCliJar'.
> Could not resolve all dependencies for configuration ':hedera-node:test-clients:runtimeClasspath'.
> Could not find com.hedera.hashgraph:hedera-protobuf-java-api:0.39.0.
Fixes #6889 
**Checklist**

Update Release/0.39 branch hedera-protobufs tag

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/LedgerConfig.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoHandlerTest.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileHandlerTestBase.java

I refactor the file query details and the content not to use the network and instead to use the ledger id from the ledger config.
Also refactoring all the places depends on it.
Fixes #6751

use ledger id from config and not from the netwrok

---

buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
buildSrc/src/main/kotlin/com/hedera/hashgraph/gradlebuild/rules/IoNettyNativeEpollMetadataRule.kt
hedera-node/hedera-mono-service/src/main/java/module-info.java
hedera-node/test-clients/src/itest/resources/network/config/node.properties
settings.gradle.kts

This pull request resolves the issue introduced by PR #6715  and reported in issue #6908 by @OlegMazurov and also by @tannerjfco via integration docker network deployment failures.
Additionally, this PR updates the `itest` suite to run netty in `PROD` mode and also adds support for `itest` with netty `PROD` on Apple M1 hardware. 
- Closes #6908

fix: browser won't start in PROD mode

---

hedera-node/infrastructure/dashboards/network-details-prom.json

This PR duplicates #6900 against the 0.39 release branch.
This PR adds stats for platform_degraded and platform_healthyNetworkFraction_fraction to the network status dashboard. These stats were added to the platform in 0.39.x.
The following screenshot shows the top of the network status dashboard with degraded + healthNetworkFraction stats added.

Add stats for platform_degraded and platform_healthyNetworkFraction_fraction to Network Status dashboard

---

hedera-node/hedera-mono-service/src/main/java/module-info.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/validators/HgcaaLogValidator.java

Small commit to fix the failing integration tests
* Added two "problem patterns" to HgcaaLogValidator so that log validation is correct with current code.
* Removed unnecessary module requires from mono-service leftover from shift to helidon-grpc

Partial fixes for #6984

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManager.java
hedera-node/test-clients/src/eet/java/E2ETestBase.java
hedera-node/test-clients/src/itest/java/IntegrationTestBase.java

Add Fine Tuning transport parameters, use standard SSL implementation
* Added what few parameters for GRPC and netty transport we can access.
* The former implementation set a number of GRPC parameters, which are never set by Helidon, so those are inaccessible for now
* We didn't set much in netty (which make sense, we don't want to meddle with TCP parameters a lot in GRPC calls).
* Set transport to "native" for Helidon (which should use Netty Epoll on linux).
* Set "jdkSsl to false, as that should only be set true in very rare (usually debugging) situations

More small refinements for Helidon version of GRPC

---

hedera-node/data/config/api-permission.properties
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/ApproveAllowanceLogic.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteAllowanceSuite.java

Fixes #7018 
Currently spender validation exist in `CryptoApproveAllowance` logic. But there is no need to validate spender exists when amount == 0 which is deleting allowance. 
Instead need to delete the allowance if it exists. This is necessary because spender could be deleted by the time allowance is being removed by the owner.

Move spender validation only for approvals

---

hedera-node/configuration/dev/bootstrap.properties
hedera-node/data/config/bootstrap.properties

Change default dev env settings (e.g. used by nightly services JRS runs) to defaults: no data on disk, JasperDB as virtual map backend.
Fixes: https://github.com/hashgraph/hedera-services/issues/6885

6885: Enable / disable data on disk and MerkleDb in dev environments

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MapMigrationToDisk.java

Backport to 0.39
Fixes: https://github.com/hashgraph/hedera-services/issues/7006

7006: Old virtual map copies aren't released during to disk migration

---

hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/ScheduleSignScenarios.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/sigs/SigFactory.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/SignedTxnFactory.java

Small change to remove a few of the `throws Throwable` clauses that cause everything in the test fixtures to declare Throwable rather than specific exceptions or, at least, the much narrower Exception.
Precursor to Schedule Handler work for #5518

Removed terrible `throws Throwable` from some test scenario code, replaced with correct exceptions

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearnerThrottle.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocolResponder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectThrottle.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java

`Objects.requireNonNull` used in platform-core instead of `throwArgNull`

Objects.requireNonNull used in platform-core

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/NodeInfo.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/AllowanceValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/ApproveAllowanceValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAttributesValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenCreateValidator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandleParityTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerParityTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/AllowanceValidatorTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/ApproveAllowanceValidatorTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/DeleteAllowanceValidatorTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/TokenAttributesValidatorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java

Make all TokenService validators not depend on `ConfigProvider`

Make all TokenService validators not depend on `ConfigProvider`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryDispatcher.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryHandlers.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowInjectionModule.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryDispatcherTest.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkAdminServiceInjectionModule.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkAdminHandlers.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetFastRecordHandler.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetFastRecordHandlerTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetStakersHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetStakersHandlerTest.java

Implement handlers for TransactionGetFastRecord and CryptoGetStakers queries, which are unsupported.
Fixes #7082 
Fixes #7081 
TransactionGetFastRecord was inadvertently left off of the list of queries for which stubs were created. Consequently, this PR contains modifications to a number of classes to hook it up. These modifications are not needed for CryptoGetStakers because the infrastructure for it was already set up.

TransactionGetFastRecord and CryptoGetStakers handlers

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskAccount.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java

- Updates `SelfSerializableDataTest` to automatically assert that `FastCopyable` serializations don't change under `copy()`.
- Includes `OnDiskAccount.copy()` fix from [here](https://github.com/hashgraph/hedera-services/pull/7134) (fails without it as expected).

Automatically assert `FastCopyable` copies have stable serialization

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JContractIDKey.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKey.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKeyList.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JContractIDKeyTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java

- Restores previous behavior mapping an empty `JContractIdKey` to a `Key{contractID=0.0.0}` protobuf key.

Restores mapping of "stand-in" `JContractIdKey` in hollow account finalization

---

.github/workflows/node-flow-deploy-release-artifact.yaml

This pull request simply updates the `.github/workflows/node-flow-deploy-release-artifact.yaml` workflow to match the new contract of the repository dispatch triggered EVM release workflow contained in the internal workflow repository. 
- Closes #7200

feat: updates the release workflow to reflect the EVM release changes

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/validators/BlockNoValidator.java

- `BlockNoValidator` should use `-1` as the "block number" preceding the genesis block.

Update `BlockNoValidator` to expect genesis block `0`

---

platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/ExampleFixedSizeVirtualValue.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MigrationTest.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapMigration.java

The `platform-sdk` part for #6659. Provides a new method to iterate over all key-value pairs in a `VirtualMap` concurrently.
#6659 : Exporting balances is not parallelized well when accountsOnDisk is enabled.
The `hedera-services` part for #6659 will come in a separate PR once the repository migrates to `platform-sdk:0.40.0-SNAPSHOT`.
**Checklist**

6659: iterate over VirtualMap concurrently

---

hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomChainIdOperationTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/v030/Version030FeatureFlagsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/v034/Version034FeatureFlagsTest.java

- Updates unit tests to use `create()` instead of constructor on `HederaTestConfigBuilder`. 😞

Fix `HederaTestConfigBuilder` usage
