- .circleci/config.yml
Closes #404
This is mainly to fix the config issue for nightly regression of master branch:
None.
> Fix the config issue for master nightly-regression 

- hedera-node/pom.xml
> Include POM change!

- .circleci/config.yml
> Add zero stake regression suite to Nightly regression

- hedera-node/pom.xml
> Move to 0.7.2 SDK

- hedera-node/configuration/dev/application.properties
- hedera-node/configuration/nextRelease/application.properties
- hedera-node/pom.xml
- test-clients/pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
- Update staging repo for `etherumj-core`.
- Disable effective throttles for dev/CI.
- Small improvements to _ValidationScenarios.jar_ for increased config flexibility.
> Misc prop changes

- test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/ConsensusThrottlesSuite.java
Fix EET spec in CI for new dev throttle settings.
> Adapt for new dev throttle properties

- hapi-proto/HAPI.html
- hapi-proto/src/main/proto/ResponseCode.proto
**Related issues**
Closes #314 
Per Donald's request.
> Update PLATFORM_TRANSACTION_NOT_CREATED comment

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- test-clients/src/main/resource/log4j2-JRS.xml
Added a new log4j for JRS regression test clients
> Fix HCS failing test

- hedera-node/src/main/java/com/hedera/services/records/FeeChargingRecordsHistorian.java
- hedera-node/src/test/java/com/hedera/services/records/FeeChargingRecordsHistorianTest.java
**Summary of change**
Don't create threshold records, no matter the account settings.
> Stop creating threshold records

- test-clients/src/main/java/com/hedera/services/bdd/suites/misc/OneOfEveryTransaction.java
Fix typos in failing spec in `nightly-freeze-restart` job.
> Fix failing OneOfEveryTransaction

- .circleci/config.yml
Closes #495 
1. Disabled CircleCi custom-migration nightly regression test.
None.
> 00495 d custom migration regression fix

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ChildStorageSpec.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/records/FileRecordsSanityCheckSuite.java
#466, #472
Add tests to validate strictness of the cost returned from a cost answer query
None.
None.
> 00472 d cost answer mismatch fee

- .circleci/config.yml
Closes #507 (original issue #438 was deleted for some unknown reason). 
The issue link: https://github.com/hashgraph/hedera-services/issues/507.
1. Created a separate workflow for mainnet migration regression test;
2. Passed regression test: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1598726460065800 
None.
> 00438 d mainnet jrs migration 

- hedera-node/pom.xml
- test-clients/pom.xml
> Update POMs to 1168 staging repo for ethj

- hedera-node/log4j2.xml
- test-tools/test_state_recover.sh
None
Removed unused database recover functions
Add features to random delete and truncate event files
Change stateSavePeriod and event save period to better match hedera real use case
None.
None.
> State recover test script update

- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/TestHelper.java
- hedera-node/src/test/java/com/hedera/services/legacy/services/state/AwareProcessLogicTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/CryptoTxRecordTransferListTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/PreCheckValidationTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/QueryValidationTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/RequestValidationTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/TransferListSizeTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/handler/SmartContractRequestHandlerStorageTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/serialization/DepthCheckValidationTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/service/SmartContractServiceImplTest.java
- hedera-node/src/test/java/com/hedera/services/sigs/verification/PrecheckVerifierTest.java
- hedera-node/src/test/java/com/hedera/services/txns/submission/TxnHandlerSubmissionFlowTest.java
- hedera-node/src/test/java/com/hedera/services/utils/PlatformTxnAccessorTest.java
- hedera-node/src/test/java/com/hedera/test/utils/TxnUtils.java
Some tests are added similar to existing tests, to check if test pass with the new Transaction proto.
> Added a few tests for new proto changes

- hapi-proto/src/main/proto/ResponseCode.proto
- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/main/java/com/hedera/services/sigs/metadata/TokenSigningMetadata.java
- hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
- hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
- hedera-node/src/main/java/com/hedera/services/tokens/TokenStore.java
- hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java
- hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
- hedera-node/src/test/java/com/hedera/services/ledger/properties/MerkleAccountPropertyTest.java
- hedera-node/src/test/java/com/hedera/services/sigs/metadata/DelegatingSigMetadataLookupTest.java
- hedera-node/src/test/java/com/hedera/services/sigs/order/HederaSigningOrderTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountStateTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleAccountTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
- hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/token/TokenUpdateTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenDeleteScenarios.java
- hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenUpdateScenarios.java
- hedera-node/src/test/java/com/hedera/test/factories/scenarios/TxnHandlingScenario.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDelete.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Closes #None
Add functionality a token to be immutable.
Immutable tokens can neither be updated, nor deleted.
Updated tests.
None.
> Feature(token): Immutability

- hedera-node/pom.xml
> Use 1185 for SDK staging repo

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/RunLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/PerfTestLoadSettings.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java
Close #647 #627 
Add `messageSize` CI property to Load test , so that we can use it for HCS Performance tests
> Add messageSize property to LoadTest settings

- hapi-proto/src/main/java/com/hederahashgraph/builder/TransactionSigner.java
- hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTest.java
- pom.xml
- test-clients/pom.xml
Update Jackson Databind and Commons Collections4 versions.
> Merge dependabot recs

- hedera-node/src/main/java/com/hedera/services/legacy/services/stats/HederaNodeStats.java
- hedera-node/src/test/java/com/hedera/services/legacy/services/stats/HederaNodeStatsTest.java
Register HTS stats with platform.
> Register HTS stats with platform

- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/NodeLivenessTimeout.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/misc/UtilVerbChecks.java
Add `withLiveNode` verb, used as e.g.
```
...
withLiveNode("0.0.3")
.within(300, TimeUnit.SECONDS)
.loggingAvailabilityEvery(30)
.sleepingBetweenRetriesFor(10)
```
> Add the NodeLivenessTimeout UtilVerb

- .circleci/config.yml
- .circleci/scripts/gen-stat-insight-pdf.sh
Closes #716 
1. Changed the python package installation. Turns out  the saved state not loading is not the root cause of the failure.
None.
> 00716 d freeze restart nightly failure

- .circleci/config.yml
Closes #720 
Move all the tests except state recovery tests to run on `develop` branch of `swirlds-platform-regression`
**NOTE:** The branch `573-D-Final-Changes` will be changed to develop once the final PR is merged.
None.
On develop the following regression tests passed.
1. **PASS** - `AWS-Daily-Services-Comp-Basic-4N-1C` - https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1604074802396800
2. `AWS-Daily-Services-Comp-Basic-Performance-4N-4C.json` - 
- Crypto-Basic-Performance-8k-31m- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1604086134404400
- HCS-Basic-Performance-7k-61m - https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1604090029407400
- HCS-Chunking - …
> 720 m move tests to run on develop

- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleDiskFsTest.java
Fix missing directory issue caused by switching to `java.nio.file.Files` methods.
> Use CommonsIO helpers instead of java.nio.file.Files methods

- hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
- hedera-node/src/main/java/com/hedera/services/stats/HapiOpCounters.java
- hedera-node/src/main/java/com/hedera/services/stats/MiscRunningAvgs.java
- hedera-node/src/test/java/com/hedera/services/stats/HapiOpCountersTest.java
- hedera-node/src/test/java/com/hedera/services/stats/MiscRunningAvgsTest.java
> Fix handledSubmitMessageSize and recordStreamQueueSize stats

- .circleci/config.yml
Run nightly regression on develop
> Run nightly regression on develop

- hedera-node/src/main/java/com/hedera/services/ServicesMain.java
- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
- hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
- hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/misc/UtilVerbChecks.java
Add a `schedulesCb` to the `HfsSystemFilesManager` implementation to be consistent with other system file `load*` methods.
> Initial commit

- hedera-node/pom.xml
- pom.xml
Also remove staging repo that is no longer in use.
> Integrate Swirlds SDK 0.7.4

- .circleci/config.yml
Closes #753 
1. Move the 4-hr JRS performance regression tests to weekend;
2. Adjust other routine JRS regression tests to run on a daily basis and avoid conflicts with 0.9.0 regression;
3. Some cleanup;
None.
> 00753 d extend weekly perf to 4hrs

- .circleci/config.yml
- hedera-node/src/main/java/com/hedera/services/throttling/bucket/BucketThrottle.java
- hedera-node/src/main/java/com/hedera/services/throttling/bucket/CapacityTest.java
- hedera-node/src/test/java/com/hedera/services/throttling/bucket/BucketThrottleTest.java
- hedera-node/src/test/java/com/hedera/services/throttling/bucket/CapacityTestTest.java
- test-clients/pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/BucketThrottlingSpec.java
> Rescale node-level throttle if required capacity exceeds bucket capacity

- hedera-node/pom.xml
> Update SDK version

- .circleci/config.yml
As services state recovery has been merged to develop, modified to run state recover tests on develop.
> fix state recover test to run on develop

- .circleci/config.yml
Closes #822 
1. Renamed the CircleCi JRS regression test workflow names;
None.
> Rename the JRS regression test workflows to match slack report.

- .circleci/config.yml
> Temporarily disable 15-node perf regression.

- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java
> 00872 Enhance reconnect test

- hapi-proto/HAPI.html
- hapi-proto/src/main/proto/ConsensusTopicInfo.proto
- hapi-proto/src/main/proto/CryptoGetAccountBalance.proto
- hapi-proto/src/main/proto/NetworkGetVersionInfo.proto
- hapi-proto/src/main/proto/NetworkService.proto
- hapi-proto/src/main/proto/Query.proto
- hapi-proto/src/main/proto/ResponseCode.proto
- Closes #682
Add comments to various undocumented protobuf elements.
> Add various missing proto comments

- .circleci/config.yml
> Stop syncing data/saved folder from nightly regression results to s3

- .circleci/config.yml
Fix S3 upload in V0.10.0 branch
> fix s3 upload

- hedera-node/src/main/resources/FeeSchedule.json
> Use latest HTS resource prices per Paul Madsen

- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduleTest.java
> (+CI) Scheduled Transactions: MerkleSchedule

- pom.xml
> (+CI) Roll JUnit version

- pom.xml
CI-enabled https://github.com/hashgraph/hedera-services/pull/773
> (+CI) activate reproducible builds

- pom.xml
you need to put a first value for timestamp: updates will be done by maven-release-plugin
on the next release, I'll check rebuild and add the result to https://github.com/jvm-repo-rebuild/reproducible-central
> activate reproducible builds

- .circleci/config.yml
Enable nightly regression on RecordStream branch
> Enable nightly regression on RecordStream branch

- docs/scheduled-transactions/EET.md
- docs/scheduled-transactions/spec.md
Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Adds the specification of the Scheduled Transactions functionality and a list of EETs that must be supported. More EETs will be added in the coming days/weeks
None.
> Docs (Scheduled Transactions): Add Specification file + EET

- .circleci/config.yml
Closes #866 
Pass CircleCi username and Build URL to regression_services_circleci.sh
This PR has a dependent PR in regression : https://github.com/swirlds/swirlds-platform-regression/pull/819
None.
> 0866 te display c ijob link user name gcp

- hedera-node/src/main/java/com/hedera/services/state/initialization/BackedSystemAccountsCreator.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/BackedSystemAccountsCreatorTest.java
> 00859 Fix bootstrap initial balance

- hedera-node/src/main/java/com/hedera/services/store/schedule/CompositeKey.java
- hedera-node/src/main/java/com/hedera/services/store/schedule/ExceptionalScheduleStore.java
- hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java
- hedera-node/src/main/java/com/hedera/services/store/schedule/ScheduleStore.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogic.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/CompositeKeyTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/ExceptionalScheduleStoreTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
- Refactors the `CompositeKey` to include all properties of the ScheduleCreate op except for the `sigMap`
- Added/updated unit tests
- Added BDDs
None.
> Scheduled TX: Composite Key update

- hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
- hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/services/utils/SignedTxnAccessorTest.java
- hedera-node/src/test/java/com/hedera/services/utils/TriggeredTxnAccessorTest.java
> Schedule ref

- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
> Remove log entry that may flood client log

- .circleci/config.yml
- hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsage.java
- hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsageTest.java
- hapi-proto/src/main/proto/ScheduleGetInfo.proto
- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
- hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsageTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduleTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
> BDD additions

- hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsage.java
- hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleGetInfoUsageTest.java
- hapi-proto/src/main/proto/ScheduleGetInfo.proto
- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
- hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/queries/GetScheduleInfoResourceUsageTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduleTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
Closes #NONE
BDD Scenarios for the following operations:
ScheduleCreate
ScheduleDelete
ScheduleSign
ScheduleExecution
These scenarios were written according to the EET specification in /docs/scheduled-transactions
None.
> Feature: Scheduled Transactions - BDD Scenarios

- docs/scheduled-transactions/EET.md
- docs/scheduled-transactions/spec.md
- Updates the EET file with the latest response codes and removes invalid test cases
- Updates the Spec file to the latest changes as-well
None.
> Docs - Update EET and Spec file to latest version

- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleBlobMeta.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleEntityAssociation.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleEntityId.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleOptionalBlob.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleSchedule.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleTokenRelStatus.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleTopic.java
- hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
- hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleBlobMetaTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduleTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTopicTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
Closes #1049 
Integrates v0.9.0-alpha.1 SDK from platform. 
For sanity check passed tests:
1. Update test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612455353163200
2. Reconnect: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612460012166000 Failed with same errors as in master yesterday
3. Performance: 10 min test looked fine https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612475738184800
20min run https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612478154185800
4. NetError: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612462133168000
5. Restart: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612464005171600 Failing with same errors as in master
6. Migration : …
> Integrate v0.9.0-alpha.1

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
Closes #1054 
Passed Migration test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612482469189000
Yesterday's failed test : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1612418938306500
> Fix INSUFFICIENT_PAYER_BALANCE error in nightly tests

- docs/dev/protobuf-features.md
- Addresses #883
Update _docs/dev/protobuf-features.md_ to explain the initial manual process for developing features that change protobufs.
> Second draft of docs/dev/protobuf-features.md

- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
Related to #1067 
Passed Restart test : 
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612825328242600
Passed Migration Restart test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612827683244600
> Fix failing Restart test

- hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
- hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
Closes #852 
1. Changes to use revisited protobuf API.
None.
> 00852 d new account balance export

- hedera-node/pom.xml
Closes #1081 
Regression summary results:
1. NetError: failed a test similar to master : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613005125037600
2. Update: similar to master : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613015680038800
3. Restart : Passed: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613006406038000
4. Migration : passed: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613007125038200, https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613017434039100
5. Reconnect : similar to master : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613009541038400, https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1613019994039200
6. Recovery: random fail due to platform not active: …
> v0.9.0-alpha.3 Integration

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
Incorporate effects of `mvn release:branch`.
> [maven-release-plugin] prepare for next development iteration

- .circleci/config.yml
> Fix OOM error in 15N tests

- .circleci/config.yml
- hedera-node/src/main/java/com/hedera/services/sigs/sourcing/PubKeyToSigBytes.java
- pom.xml
Closes #1013
1. Added the job to generate javadoc;
2. Also add step in the CI workflow to trigger the job;
None.
> 1013 m javadoc to ci

- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransferBasicLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/TokenTransfersLoadProvider.java
Closes #1070
slack report: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614308585078800 
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614293992071600
Note: there changes should fix some failure scenarios. More changes may be needed. 
1. Changes to fix these test failures.
None.
> Minor changes to fix test failures.

- hedera-node/pom.xml
> Use Maven Central artifact for 0.9.0 SDK

- pom.xml
> Use HEAD for SCM base

- .circleci/config.yml
> Disable nightly tests on 0.12.0

- pom.xml
- Change email and organization for @qnswirlds
- Add info for @abhishek-hedera 
- Fix info for @QianSwirlds 
- Standardize format
> Minor pom fix - developers' section

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
Set current working version to `0.13.0-SNAPSHOT`.
> Use 0.13.0-SNAPSHOT as working version

- .circleci/config.yml
- hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/RecordStreamVerification.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/verification/NodeSignatureVerifier.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/file/FetchSystemFiles.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/AddressBookPojo.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/SysFilesUpdate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/AddrBkJsonToGrpcBytes.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/NodesJsonToGrpcBytes.java
- test-clients/src/main/java/com/hedera/services/legacy/regression/ProtectedEntityTests.java
- test-clients/src/main/java/com/hedera/services/legacy/regression/umbrella/CryptoServiceTest.java
- test-clients/src/main/java/com/hedera/services/legacy/regression/umbrella/UmbrellaTest.java
- test-clients/src/main/java/com/hedera/services/yahcli/suites/SysFileUploadSuite.java
Use new `AddressBook` name instead of `NodeAddressBook`.
> Use new AddressBook name rather than NodeAddressBook

- hedera-node/src/main/java/com/hedera/services/ServicesMain.java
- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
- hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
- hedera-node/src/main/java/com/hedera/services/state/initialization/SystemFilesManager.java
- hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
- hedera-node/src/test/java/com/hedera/services/ServicesMainTest.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
- hedera-node/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java
Fix mismatch in `MerkleNetworkContext` serdes.
> Fix reconnect issues caused by MerkleNetworkContext changes

- hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/grpc/controllers/ScheduleController.java
- hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JKey.java
- hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JKeyList.java
- hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/JThresholdKey.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleDeleteTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleReadyForExecution.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleSignTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/SigMapScheduleClassifier.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/SignatoryUtils.java
- hedera-node/src/main/java/com/hedera/services/utils/SignedTxnAccessor.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsageTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JKeyListTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JKeyTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/core/jproto/JThresholdKeyTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/TransferListSizeTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/util/ComplexKeyManager.java
- hedera-node/src/test/java/com/hedera/services/records/RecordCacheFactoryTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
- hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleSignTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/services/utils/SignedTxnAccessorTest.java
- test-clients/devops-utils/validation-scenarios/config.yml
- Closes #1227 other than doc changes not in the `hedera-services` repo.
See the checklist in issue #1227; notice especially that `Schedule*Logic` source files are just reformatted with IntelliJ style, no code changes.
> Misc code improvements around scheduled txns

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java
Closes #1251 
Closes #1248
Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618352417340700
Because of the issue #1224, overriding the property `"minimumAutoRenewDuration", "20"` did not update `ledger.autoRenewPeriod.minDuration` and from hgcaa.log the values are as 
` ledger.autoRenewPeriod.maxDuration=1000000000, ledger.autoRenewPeriod.minDuration=10`. So, the precheck did not pass `AUTORENEW_DURATION_NOT_IN_RANGE` .
Modified to override the property `"ledger.autoRenewPeriod.minDuration"` instead
> Fix AllProtectedFilesUpdate-Reconnect-1-12m

- .circleci/config.yml
- test-clients/pom.xml
> Enable nightly regression on release/0.13

- .circleci/config.yml
- pom.xml
Integrates 0.9.1 platform sdk to services
**Regression is currently running and once it succeeds this will be merged.**
Passed tests:
**Update**:https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618933252410500 (one failed on master as well)
**Migration:**https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618934762412500 (one failed because platform not active)
**Restart:**https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618935022413000
**Performance:** 
Random : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618945320424700
Hotspot: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618938066416000
**NetError:**https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p161893312640960 …
> Integrate 0.9.1 platform SDK

- hedera-node/configuration/mainnet/optional-upgrade/application.properties
- hedera-node/configuration/mainnet/upgrade/application.properties
- hedera-node/configuration/testnet/optional-upgrade/application.properties
- hedera-node/configuration/testnet/upgrade/application.properties
- Update config to reflect that `scheduling.whitelist` will be overridden in testnet and mainnet `0.0.121.`
> Remove CryptoCreate from scheduling.whitelist

- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
Address #1295 for release/0.13
slack link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619135402470400
summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619135445470800 
1. Changes to fix the account balance validator JRS test;
None.
> Get the account balance validation fixes from master

- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
> Just warn on failed legacy DiskFs migration since update zip never used

- pom.xml
Integrating platform SDK 0.9.2 
**Reconnect tests and Regression running on the branch. Will be merged tomorrow after successful runs**
> Integrate 0.9.2 platform SDK

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleReadyForExecution.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleSignTransitionLogic.java
- hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleReadyForExecutionTest.java
- hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleSignTransitionLogicTest.java
- pom.xml
- test-clients/pom.xml
> Incorporate scheduled fix for 0.13.1

- test-clients/pom.xml
> Re-enable packaging SuiteRunner.jar in release/0.13 to run JRS tests

- .circleci/config.yml
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleDiskFsTest.java
Signed-off-by: Neeharika-Sompalli neeharika.sompalli@hedera.com
Passed Migration test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619214934009200
> Mark missing MerkleDiskFs file while migration as WARN

- hedera-node/configuration/preprod/bootstrap.properties
> Switch preprod to use mainnet throttles in bootstrap.properties

- hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
Closes #1288 
Replace`javafx.util.Pair` with `org.apache.commons.lang3.tuple.Pair`
None.
> Replace usage of javafx.util.Pair with org.apache.commons.lang3.tuple.Pair

- docs/fees/automated-congestion-pricing.md
- Closes #1300
Add _docs/congestion-pricing.md_ to explain the behavior of automated congestion pricing in Services.
> Congestion pricing README

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateTokensBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SchedulesExpiryDuringReconnect.java
Fixed issues caused by logging in existing reconnect tests. 
Passed existing reconnect tests : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619732568053200, https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619733675053300
> Fix existing reconnect tests

- test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AccountAutoRenewalSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/TopicAutoRenewalSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java
1. added test case that verifies if anyone can update the expiration time on an account.
2. minor updates to reconnect test for auto renew
> 01225 m autorenew test development

- pom.xml
Passed tests :   
1. Reconnect : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620181842091100, https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620178010088900, https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620173532085300 (Few new errors in Interrupted reconnect test ReconnectValidator, but thats because of timing)
2. Recovery : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620174278086200
3. Migration : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620169695079200, https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620152922072600
4. Performance : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620177074088000
5. Update : …
> Integrate 0.9.3 platform SDK

- hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalProcess.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalProcessTest.java
> Fix the new expiration time in the memo of auto-renew record

- pom.xml
> Integrate platform SDK 0.9.4

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>
> Rebind SuiteRunner packaging

- hapi-utils/src/test/java/com/hedera/services/throttles/DeterministicThrottleTest.java
- hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java
- hedera-node/src/test/java/com/hedera/services/ledger/properties/MerkleAccountPropertyTest.java
Closes #1436
1. Changes to hopefully get rid of the 1 blocker and 4 critical bug reported by sonar;
None.
> Fix blocker and critical sonar issues.

- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
> Enhance EET to validate that precheck on a transaction don't get charged

- test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
> Fix warning supressor property name (#1528)

- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
> Integrate 0.15.0-alpha.2 sdk

- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
Closes #1551
1. Added the retry for BinaryObjectDeletedException;
2. Added more test scenarios;
None.
> Added retry to bin obj deleted scenario.

- pom.xml
> Roll to SDK 0.15.1

- hedera-node/configuration/compose/log4j2.xml
- hedera-node/configuration/dev/log4j2.xml
- hedera-node/configuration/mainnet/log4j2.xml
- hedera-node/configuration/preprod/log4j2.xml
- hedera-node/configuration/previewnet/log4j2.xml
- hedera-node/configuration/testnet/log4j2.xml
Signed-off-by: Nathan Klick <nathan@swirlds.com>
Closes #1621
> Log4j2 Configuration Missing Filter Explicit DENY

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
Update _pom.xml_ for 0.16.0 development iteration.
> Begin 0.16.0 development iteration

- pom.xml
> Integrate platform SDK 0.16.0-alpha.1

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/settings.txt
Closes #1641 
Successful test slack summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1624372943099900 
1. Cherry-picked the changes to fix the NPE errors for release/0.15 beanch.
None.
> Cherry picked the fix for issue 01641 NPE errors for JRS tests.

- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensDeleteAfterReconnect.java
Related to  #1678
Passed test :  https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1624658996216600
> Reconnect test with an account dissociation from a deleted token

- .circleci/config.yml
Closes #1289 
Removed GCP-Daily-Services-Crypto-Update-5N-1C from nightly regression
>  Remove GCP-Daily-Services-Crypto-Update-5N-1C from nightly regression

- pom.xml
> 01704: Integrate platform SDK 0.16.0

- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateAccountsBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateFilesBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateTokensBeforeReconnect.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateTopicsBeforeReconnect.java
Closes #1694, #1692, #1647
Replaces usage of getVersionInfo as a noOp with an actual noOp.
> use noOp instead of getVersionInfo

- hapi-utils/src/main/java/com/hedera/services/sysfiles/validation/ExpectedCustomThrottles.java
- hapi-utils/src/test/java/com/hedera/services/sysfiles/validation/ExpectedCustomThrottlesTest.java
- hedera-node/configuration/compose/api-permission.properties
- hedera-node/configuration/dev/api-permission.properties
- hedera-node/configuration/mainnet/api-permission.properties
- hedera-node/configuration/preprod/api-permission.properties
- hedera-node/configuration/previewnet/api-permission.properties
- hedera-node/configuration/testnet/api-permission.properties
- hedera-node/src/main/java/com/hedera/services/context/domain/security/PermissionFileUtils.java
- hedera-node/src/main/java/com/hedera/services/grpc/controllers/TokenController.java
- hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
- hedera-node/src/main/resources/api-permission.properties
- hedera-node/src/main/resources/throttles-dev.json
- hedera-node/src/main/resources/throttles-perf.json
- hedera-node/src/main/resources/throttles.json
- hedera-node/src/test/java/com/hedera/services/context/domain/security/PermissionFileUtilsTest.java
- hedera-node/src/test/java/com/hedera/services/grpc/controllers/TokenControllerTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
- hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
- test-clients/src/main/resource/testSystemFiles/artificial-limits-6N.json
- test-clients/src/main/resource/testSystemFiles/artificial-limits.json
- test-clients/src/main/resource/testSystemFiles/duplicated-operation.json
- test-clients/src/main/resource/testSystemFiles/throttles-dev.json
- test-clients/src/main/resource/testSystemFiles/throttles-for-acct-balances-tests.json
- test-clients/src/main/resource/testSystemFiles/throttles-sans-mint.json
- test-clients/src/main/resource/testSystemFiles/zero-ops-group.json
Update `ExpectedCustomThrottles`, `MiscUtils`, `TokenController`, assorted _api-permission.properties_ and throttle JSON, etc. for new `TokenFeeScheduleUpdate` operation.
> Update HAPI permissions, throttles, etc for new op

- hedera-node/configuration/mainnet/javaOptions
- hedera-node/configuration/preprod/javaOptions
- hedera-node/configuration/previewnet/javaOptions
- hedera-node/configuration/testnet/javaOptions
> 01757: Match the current java options and huge page setting in prod/pre-prod

- hedera-node/src/main/java/com/hedera/services/store/models/Token.java
- hedera-node/src/test/java/com/hedera/services/store/models/TokenTest.java
- pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java
The Nft **Transitions** and **Queries** did not have enough E2E Scenarios to verify that the features work. I added some more.
Fixes #NONE
> Nfts: E2E Scenarios

- hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
- hapi-fees/src/main/java/com/hedera/services/usage/state/UsageAccumulator.java
- hapi-fees/src/main/java/com/hedera/services/usage/token/TokenMintUsage.java
- hapi-fees/src/test/java/com/hedera/services/pricing/FeeSchedulesTest.java
- hapi-fees/src/test/java/com/hedera/services/usage/state/UsageAccumulatorTest.java
- hapi-fees/src/test/java/com/hedera/services/usage/token/TokenMintUsageTest.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/token/txns/TokenMintResourceUsage.java
- hedera-node/src/main/resources/feeSchedules.json
- hedera-node/src/test/java/com/hedera/services/fees/calculation/token/txns/TokenMintResourceUsageTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenFeeScheduleUpdate.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenMint.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java
Addresses first check of #1766.
> Fix TokenMint usage estimate + update fee schedule for desired pricing

- .circleci/config.yml
Signed-off-by: ljianghedera <leo.jiang@hedera.com>
This PR modifies config.xml of release/0.15 branch to disable the nightly JRS regression.
Fixes #1791 
**Checklist**
> Disable release/0.15 nightly JRS regression.

- .circleci/config.yml
This PR modifies config.xml of release/0.16 branch to enable the nightly JRS regression tests.
Fixes #1791 
**Checklist**
> Start release/0.16 nightly JRS regression.

- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
This PR modifies the way client querying account balances. Instead of sending all queries in one batch, which takes too long and no transaction is send to server during this period. This may cause the server side missing consensus event to trigger exporting, hence cause the test to fail.
Fixes #1801
Test results slack summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1626290755331000
**Checklist**
> Fix the issue that account balance files not exported sometimes.

- README.md
- Add link to organization level SUPPORT.md
- Add link to license
**Checklist**
> Add links to license and support guide

- .circleci/config.yml
Signed-off-by: ljianghedera <leo.jiang@hedera.com>
This PR fix the typo of slack summary report channel introduced by 1373
Fixes #1373 
**Checklist**
> Fix the slack summary channel name.

- test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CryptoTransferThenFreezeTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/FileContractMemoPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/QueryOnlyLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/ContractBigArrayLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/ContractCallLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/ContractCallLocalPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/ContractCallPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/MixedSmartContractOpsLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoCreatePerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferPerfSuiteWOpProvider.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileUpdateLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/MixedFileOpsLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/mixedops/MixedOpsLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/mixedops/MixedOpsMemoPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/mixedops/MixedTransferAndSubmitLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/mixedops/MixedTransferCallAndSubmitLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenCreatePerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenTransferBasicLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/topic/CreateTopicPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/topic/HCSChunkingRealisticPerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/topic/SubmitMessageLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/topic/SubmitMessagePerfSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/topic/createTopicLoadTest.java
This PR removed `reportStats` from `HapiApiSuite` and other EETs
Fixes #1800 
**Checklist**
> Removing stats related code from EET and HapiApiSuite

- hedera-node/src/main/java/com/hedera/services/fees/charging/NarratedLedgerCharging.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
> Fixes for v0.16.0 issues

- hapi-fees/pom.xml
- hapi-fees/src/test/java/com/hedera/services/pricing/FeeSchedulesTest.java
- hapi-utils/pom.xml
- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
- pom.xml
- test-clients/pom.xml
- Begin `0.17.0` dev iteration.
- Remove some debug print statements noticed during tagging `v0.16.0`.
> Begin 0.17.0 development iteration

- test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java
Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>
Fixes #
**Checklist**
> Resolve movingUnique argument order in Hip17UnhappyTokens

- hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/FeeCalcUtils.java
- hedera-node/src/main/java/com/hedera/services/keys/HederaKeyActivation.java
- hedera-node/src/main/java/com/hedera/services/keys/HederaKeyTraversal.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/AbstractUniqTokenView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/EmptyUniqueTokenView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/ExplicitOwnersUniqTokenView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/TreasuryWildcardsUniqTokenView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/UniqTokenView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/UniqTokenViewsManager.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/utils/GrpcUtils.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/views/utils/MultiSourceRange.java
- hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/FeeCalcUtilsTest.java
- hedera-node/src/test/java/com/hedera/services/keys/HederaKeyActivationTest.java
- hedera-node/src/test/java/com/hedera/services/keys/HederaKeyTraversalTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/views/AbstractUniqTokenViewTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/views/ExplicitOwnersUniqTokenViewTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/views/TreasuryWildcardsUniqTokenViewTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/views/utils/GrpcUtilsTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/views/utils/MultiSourceRangeTest.java
- hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
- Change from int array to Pair for ranges
- For those `UniqTokenView`, change to require non-null `AccountID` and `TokenID`
> Tests and code smells for #1873

- hedera-node/src/main/java/com/hedera/services/fees/calculation/utils/ResourceUsageSubtypeHelper.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/utils/ResourceUsageSubtypeHelperTest.java
Default the fallBack prices of token operations to `TOKEN_FUNGIBLE_COMMON` subtype instead of `DEFAULT` subtype
Fixes #1910 
**Checklist**
> Default Token Operations FallBack Prices To FungibleCommon subtype

- .dockerignore
- Dockerfile
- hedera-node/configuration/compose/log4j2.xml
- hedera-node/configuration/compose/node.properties
- hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
- Only check if the new unique token treasury already holds NFTs...if there _is_ a new treasury on a `TokenUpdateTransactionBody`.
- Fix some issues breaking Docker Compose networks.
- Closes #1930
> Only check new treasury balance if set on `TokenUpdateTransactionBody`

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
> 01983: Consolidate release version

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
- Restore `HEAD` tag in parent _pom.xml_
- Use version `0.17.1-SNAPSHOT`
> Restore HEAD tag

- hedera-node/pom.xml
Add a classifier to let netty-transport-native-epoll build libnetty_transport_native_epoll_x86_64 library
Fixes #2003 
**Checklist**
> `netty.mode=PROD` fix for netty v4.1.66

- hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
- hedera-node/src/test/java/com/hedera/services/store/models/fees/CustomFeeTest.java
- hedera-node/src/test/java/com/hedera/services/store/tokens/ExceptionalTokenStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/TransitionRunnerTest.java
- hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
Signed-off-by: Yoan Sredkov <yoansredkov@gmail.com>
Increases code coverage by adding more unit tests.
> CI enabled 1916 - Coverage

- hapi-fees/src/main/java/com/hedera/services/usage/crypto/entities/CryptoEntitySizes.java
- hapi-fees/src/main/java/com/hedera/services/usage/token/entities/TokenEntitySizes.java
- hedera-node/src/main/java/com/hedera/services/context/domain/security/PermissionedAccountsRange.java
- hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
- hedera-node/src/main/java/com/hedera/services/context/properties/ScreenedNodeFileProps.java
- hedera-node/src/main/java/com/hedera/services/context/properties/ScreenedSysFileProps.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java
- hedera-node/src/main/java/com/hedera/services/files/interceptors/PureRatesValidation.java
- hedera-node/src/main/java/com/hedera/services/grpc/controllers/NetworkController.java
- hedera-node/src/main/java/com/hedera/services/keys/HederaKeyActivation.java
- hedera-node/src/main/java/com/hedera/services/legacy/handler/FreezeHandler.java
- hedera-node/src/main/java/com/hedera/services/sigs/metadata/lookups/RetryingFCMapAccountLookup.java
- hedera-node/src/main/java/com/hedera/services/sigs/utils/ImmutableKeyUtils.java
- hedera-node/src/main/java/com/hedera/services/state/serdes/TopicSerde.java
- hedera-node/src/main/java/com/hedera/services/stats/ServicesStatsConfig.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
- hedera-node/src/main/java/com/hedera/services/txns/validation/TokenListChecks.java
- hedera-node/src/test/java/com/hedera/services/context/properties/ScreenedNodeFilePropsTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/FreezeHandlerTest.java
- hedera-node/src/test/java/com/hedera/services/txns/validation/TokenListChecksTest.java
Close #1991
- Add `final` where appropriate
- Refactor `FreezeHandler`
> 01991: static final fields

- hedera-node/configuration/compose/log4j2.xml
- hedera-node/configuration/dev/log4j2.xml
- hedera-node/configuration/mainnet/log4j2.xml
- hedera-node/configuration/preprod/log4j2.xml
- hedera-node/configuration/previewnet/log4j2.xml
- hedera-node/configuration/testnet/log4j2.xml
Also bring non-prod _log4j2.xml_ in sync with mainnet config.
> Use `INFO` level logging only

- hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/AtomicCounter.java
- hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java
- hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/ProtoCommonUtils.java
- hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureGenerator.java
- hapi-utils/src/main/java/com/hederahashgraph/builder/RequestBuilder.java
- hapi-utils/src/main/java/com/hederahashgraph/exception/InvalidTxBodyException.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilder.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/FeeObject.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/SigValueObj.java
- hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java
- hapi-utils/src/test/java/com/hederahashgraph/fee/CryptoFeeBuilderTest.java
- pom.xml
Close #2083
Close #2086
Address #1995
> Refactor crypto fee builder

- hedera-node/src/main/java/com/hedera/services/legacy/handler/SmartContractRequestHandler.java
- hedera-node/src/main/java/com/hedera/services/records/RecordCache.java
- hedera-node/src/main/java/com/hedera/services/records/TxnIdRecentHistory.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiringCreations.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/NoopExpiringCreations.java
- hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelper.java
- hedera-node/src/main/java/com/hedera/services/state/logic/RecordStreaming.java
- hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
- hedera-node/src/test/java/com/hedera/services/records/TxnIdRecentHistoryTest.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiringCreationsTest.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryManagerTest.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelperTest.java
- hedera-node/src/test/java/com/hedera/services/state/logic/RecordStreamingTest.java
- Fixed most issues reported by #1995
- Refactored all touched classes and tests
- Close #1995
> 01995: Rename record variables

- .circleci/config.yml
Use regression branch `run-services-regression` to run services regression
Until we fix our regression config, we can use this to run regression on services.
**Checklist**
> Use regression branch `run-services-regression` to run services regression

- hedera-node/configuration/mainnet/settings.txt
> Update mainnet `maxOutgoingSyncs=8`

- hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountRecordsResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/queries/GetTxnRecordResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/queries/answering/AnswerFunctions.java
- hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountRecordsAnswer.java
- hedera-node/src/main/java/com/hedera/services/queries/meta/GetTxnRecordAnswer.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetAccountRecordsResourceUsageTest.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/crypto/queries/GetTxnRecordResourceUsageTest.java
- hedera-node/src/test/java/com/hedera/services/queries/answering/AnswerFunctionsTest.java
- hedera-node/src/test/java/com/hedera/services/queries/crypto/GetAccountRecordsAnswerTest.java
- hedera-node/src/test/java/com/hedera/services/queries/meta/GetTxnRecordAnswerTest.java
- hedera-node/src/test/java/com/hedera/test/utils/QueryUtils.java
- Avoid potential misuse of AnswerFunctions. Close #2104
- More record variables renaming. #1995
- Add QueryUtils and clean up unit tests.
> 02104:  Avoid potential misuse of AnswerFunctions

- pom.xml
> 02117: Ignore SonarCloud rule for uses of deprecated code

- hapi-fees/src/main/java/com/hedera/services/pricing/ScheduleGenerator.java
- hapi-fees/src/test/java/com/hedera/services/pricing/ConsensusFeeSchedulesTest.java
- hapi-fees/src/test/java/com/hedera/services/pricing/CryptoFeeSchedulesTest.java
- hapi-fees/src/test/java/com/hedera/services/pricing/FileFeeSchedulesTest.java
- hapi-fees/src/test/java/com/hedera/services/pricing/ScheduleGeneratorTest.java
- hapi-fees/src/test/java/com/hedera/services/pricing/TokenFeeSchedulesTest.java
- hedera-node/src/test/java/com/hedera/services/context/properties/StandardizedPropertySourcesTest.java
- hedera-node/src/test/java/com/hedera/services/ledger/HederLedgerTokensTest.java
- hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerLiveTest.java
- hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerXfersTest.java
- hedera-node/src/test/java/com/hedera/services/legacy/unit/serialization/HFileMetaSerdeTest.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleDiskFsTest.java
- hedera-node/src/test/java/com/hedera/services/store/schedule/HederaScheduleStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/token/TokenDeleteTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/test/factories/scenarios/TxnHandlingScenario.java
- Fix code smells for #2103. Close #2123
- Replace try catch by assertThrows in HederaLedgerXfersTest. Close #2122
- Remove some more public modifier for JUnit5
> Bring SonarCloud quality gate back to passing

- hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java
- hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucketTest.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/CongestionMultipliers.java
- hedera-node/src/test/java/com/hedera/services/fees/calculation/CongestionMultipliersTest.java
- Combine more tests to remove duplications
- Increase readability
- Fix one more SonarCloud issue
> 02169: Remove more duplications

- hapi-utils/src/main/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilder.java
- hapi-utils/src/test/java/com/hedera/services/UtilsConstructorTest.java
- hapi-utils/src/test/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilderTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java
> Make ConsensusServiceFeeBuilder a util class. #2219

- hedera-node/src/main/java/com/hedera/services/context/domain/process/TxnValidityAndFeeReq.java
- hedera-node/src/main/java/com/hedera/services/queries/answering/StakedAnswerFlow.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/BasicSubmissionFlow.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/PresolvencyFlaws.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/StagedPrechecks.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/StructuralPrecheck.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/SubmissionModule.java
- hedera-node/src/main/java/com/hedera/services/txns/submission/TransactionPrecheck.java
- hedera-node/src/test/java/com/hedera/services/context/domain/process/TxnValidityAndFeeReqTest.java
- hedera-node/src/test/java/com/hedera/services/queries/answering/StakedAnswerFlowTest.java
- hedera-node/src/test/java/com/hedera/services/txns/submission/BasicSubmissionFlowTest.java
- hedera-node/src/test/java/com/hedera/services/txns/submission/StructuralPrecheckTest.java
- hedera-node/src/test/java/com/hedera/services/txns/submission/TransactionPrecheckTest.java
- hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
Close #2230 (part of #1996)
Close #2231
> 02230: Remove uses of Optional in pre-check

- hapi-fees/pom.xml
- hapi-fees/src/test/java/com/hedera/services/pricing/TokenFeeSchedulesTest.java
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
> Fix `TokenFeeSchedulesTest` + start `0.19.0` dev iter

- hedera-node/src/main/java/com/hedera/services/fees/calculation/consensus/ConsensusFeesModule.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/ContractFeesModule.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/crypto/CryptoFeesModule.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/file/FileFeesModule.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/ScheduleFeesModule.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/token/TokenFeesModule.java
- hedera-node/src/main/java/com/hedera/services/keys/KeysModule.java
- hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java
- hedera-node/src/main/java/com/hedera/services/stats/StatsModule.java
- hedera-node/src/main/java/com/hedera/services/throttling/ThrottlingModule.java
- hedera-node/src/main/java/com/hedera/services/txns/contract/ConsensusLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/contract/ContractLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/file/FileLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/network/NetworkLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleLogicModule.java
- hedera-node/src/main/java/com/hedera/services/txns/token/TokenLogicModule.java
- hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
> 02147-02252: Disallow Dagger2 module extension or instantiation

- hedera-node/src/main/java/com/hedera/services/state/initialization/HfsSystemFilesManager.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/HfsSystemFilesManagerTest.java
- hedera-node/src/test/java/com/hedera/test/factories/keys/KeyTree.java
> 02257: Refactor HfsSystemFilesManager

- hedera-node/pom.xml
- pom.xml
> Use `v0.19.0-alpha.2` protobufs

- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CommonUpgradeResources.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/FreezeAbort.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/FreezeUpgrade.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/PrepareUpgrade.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/UpdateFileForUpgrade.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/PerfTestLoadSettings.java
> 02282: Standalone test suites for testing network upgrade

- hapi-fees/src/main/resources/canonical-prices.json
- hedera-node/src/main/resources/feeSchedules.json
- test-clients/devops-utils/validation-scenarios/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AllBaseOpFeesSuite.java
- test-clients/src/main/resource/FeeSchedule.json
The price of an NFT mint was not updated to differentiate from the price of a fungible common mint.
> Correct NFT mint price to ¢5

- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/misc/MemoValidation.java
Added memo validations [with MultiByte chars] for entityMemos and transaction memos on various operations.
> Add memo validation specs

- hedera-node/pom.xml
- test-clients/pom.xml
Upgrade version from RC-1 to released 21.10.0.
Fixes #
**Checklist**
> Upgrade Besu Version

- .circleci/config.yml
- hedera-node/src/main/java/com/hedera/services/state/virtual/VirtualMapFactory.java
- Offset regressions 4 hours away from main branch.
- Fix code smell.
> SDK 0.20.0-test.3: Offset regression times and fix code smell

- test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/RekeyCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/files/SysFileDownloadCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/files/SysFileUploadCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/FreezeAbortCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/FreezeOnlyCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/FreezeUpgradeCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/StageUpgradeCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/TelemetryUpgradeCommand.java
Fixes #2425 
return non zero exit code on a failed yahcli commands and also log a warn with the failure message
**Checklist**
> return non zero exit code on a failed yahcli commands

- hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java
- hedera-node/src/main/java/com/hedera/services/txns/token/process/Dissociation.java
- hedera-node/src/test/java/com/hedera/services/store/TypedTokenStoreTest.java
- hedera-node/src/test/java/com/hedera/services/txns/token/process/DissociationTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
> Allow dissociating from deleted token with dissocaited treasury

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC20ContractInteractions.java
> Add contract log validations for ERC20 contract

- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCreateOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSStoreOperation.java
- test-clients/pom.xml
Upgrade Besu to 21.10.2.
**Checklist**
> Upgrade Besu 21.10.2

- .circleci/config.yml
⚠️ Pending merge of https://github.com/swirlds/swirlds-platform-regression/pull/1789
- Split reconnect correctness workflow into two, one for NI and one for ND.
> Split reconnect correctness panel into NI and ND panels

- .circleci/config.yml
Test result, all passed
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1637175297101100
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1637172943101000
> Add new update json tests

- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetVersionInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
- test-clients/src/main/java/com/hedera/services/yahcli/Yahcli.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/system/VersionInfoCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/suites/BalanceSuite.java
- test-clients/yahcli/README.md
> add version command to yahcli which perform the getVerionInfo query

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- pom.xml
- test-clients/pom.xml
> Begin 0.21 dev iteration

- .circleci/config.yml
> 02557: Other os update regression workflows

- .circleci/config.yml
To be merged together with https://github.com/swirlds/swirlds-platform-regression/pull/1882
Close #2576
> 02576: CircleCI workflows to use 7N-7C regression panels

- test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
Close #2573
Close #2575 (https://github.com/swirlds/swirlds-platform-regression/pull/1882 was already merged)
> 02573: Fix java.lang.ArithmeticException thrown in test-clients

- hedera-node/configuration/compose/log4j2.xml
- hedera-node/configuration/dev/log4j2.xml
- hedera-node/configuration/mainnet/log4j2.xml
- hedera-node/configuration/preprod/log4j2.xml
- hedera-node/configuration/previewnet/log4j2.xml
- hedera-node/configuration/testnet/log4j2.xml
- hedera-node/log4j2-prod.xml
- hedera-node/log4j2.xml
- test-clients/src/main/resource/log4j2-JRS.xml
- test-clients/src/main/resource/log4j2.xml
- test-clients/src/main/resource/regression-log4j2.xml
Update all Log4J configs to not expand lookups.
Fixes #
**Checklist**
> Update Log4J config for nolookup

- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFees.java
Token treasury accounts are exempt from paying custom fees. Introduced a tokenTreasury account and added one more cryptoTransfer between the treasury and the tokenOwner in order to test the fees logic.
Fixes #
Note: these tests are also failing in `master`
**Checklist**
> Fixes for TransferWithCusomFees - token treasuries are exempt from fees

- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/ReferenceType.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoDelete.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
Clean up duplicated methods in test-clients.
> Clean up test clients avoiding duplication

- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryUtils.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetReceipt.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Added support to retrieve the child receipts and log them.
> support retreiving the child receipts of a transaction

- test-clients/src/main/java/com/hedera/services/yahcli/Yahcli.java
- test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
- test-clients/yahcli/README.md
- test-clients/yahcli/run/build.sh
- Add a `-i/--node-ip` option to yahcli so nodes can be targeted independent of a _config.yml_ file.
> Add `-i/--node-ip` option

- .circleci/config.yml
Close #2614
Passing CI with stats graph: https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1639592090253900
> 02614: Use cci-openjdk-regression image for ci-test-executor

- hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
> Remove from the alias map before removing from the merkleAccount map

- pom.xml
> Use Java 17 for maven compiler plugin

- hedera-node/src/test/java/com/hedera/services/config/Log4JExploitTest.java
- hedera-node/src/test/resources/log4j2-WithMDC-test.xml
add a test to make logger log the MDC fish tags added to the logger and see if the jndi lookup exploit triggered by having a url in one of these tags.
> log4J exploit testing with MDC config

- hapi-fees/src/test/java/com/hedera/services/usage/SigUsageTest.java
- hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithAutoAccounts.java
Closes #2632 
Added 
1. Load test to be used for Restart and Migration tests in regression
2. Modified and Added few unit tests
> Add test coverage ECDSA and Auto account features

- .circleci/config.yml
- .circleci/scripts/clean_up_instances.sh
Passed workflow: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/27639/workflows/c87779c0-e023-46f5-98b9-93ba29c9cb9d/jobs/96800
> Fix gcp cleanup script

- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
> 02651: Remove debug print-out in HapiCryptoTransfer

- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithInvalidAccounts.java
> 02663: Add CryptoTransferLoadTestWithInvalidAccounts

- .circleci/config.yml
> 02671: Add daily panel for crypto with invalid accounts

- .circleci/config.yml
Close #2677
CI with stats graph:
https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1640728245283500
> 02677: Fix missing stats graph

- hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java
- hedera-node/src/main/java/com/hedera/services/sigs/metadata/TokenMetaUtils.java
- hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
> Changes for comments in #2681

- hapi-fees/pom.xml
- hapi-fees/src/main/java/com/hedera/services/usage/token/TokenUpdateUsage.java
- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
- hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
- hedera-node/src/main/java/com/hedera/services/txns/consensus/TopicUpdateTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/utils/EntityIdUtils.java
- hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
- hedera-node/src/test/java/com/hedera/services/txns/consensus/MerkleTopicUpdateTransitionLogicTest.java
- test-clients/pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
- Ports fixes for issues #2653, #2688, and #2674 
- Fixes some _pom.xml_ `SNAPSHOT` versions that were out of sync for some reason.
> Port selected fixes for `v0.21.2` tag.

- hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
> HederaWorldState must be a Singleton

- hapi-utils/README.md
- hedera-node/README.md
> Update ReadMe files

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCreateSuite.java
> fix ContractCreateSuite

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCreateSuite.java
> fix getsInsufficientPayerBalanceIfSendingAccountCanPayEverythingButServiceFee 

- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/previewnet/bootstrap.properties
- hedera-node/configuration/testnet/bootstrap.properties
- Add ledger ids to deployment config.
> Add `ledger.id` props to configuration

- test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
- test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Synchronize the HTS contracts with other soruces.
Just formatting and setting NFT serial numbers to int64 in this case.
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #
**Checklist**
> Synchronize HTS Contracts

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
- Add `csvOutputFolder, data/stats` in all environments.
- Update stat `reconnect.asyncInputStreamTimeoutMilliseconds` to new name `reconnect.asyncStreamTimeoutMilliseconds`.
> Update _settings.txt_ for 0.22

- hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
- hedera-node/src/main/java/com/hedera/services/contracts/execution/HederaMessageCallProcessor.java
- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
- hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaMessageCallProcessorTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/ContractCallSuite.java
Update the HTS precompile pricing to charge, in gas, 120% of the service fees a similar operation would be charged.
Fixes #2786
**Checklist**
> Update HTS Precompile pricing

- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
- hedera-node/src/main/java/com/hedera/services/txns/span/SpanMapManager.java
> Add `Precompile.addImplicitCostsIn()` hook for `TransferPrecompile` to add custom fee usage

- hedera-node/configuration/dev/log4j2.xml
- hedera-node/configuration/preprod/log4j2.xml
- hedera-node/configuration/previewnet/log4j2.xml
- hedera-node/configuration/testnet/log4j2.xml
Signed-off-by: Nathan Klick <nathan@swirlds.com>
Closes #2809
> Move Jasper DB & Virtual Map logging to a separate log file

- hedera-node/configuration/mainnet/log4j2.xml
Signed-off-by: Nathan Klick <nathan@swirlds.com>
Closes #2844
> 02844: Port issue #2809 changes to mainnet config

- hedera-node/src/main/java/com/hedera/services/config/NetworkInfo.java
- hedera-node/src/test/java/com/hedera/services/config/NetworkInfoTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/consensus/HapiGetTopicInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/file/HapiGetFileInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetAccountNftInfos.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenNftInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenNftInfos.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiTokenNftInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
> make ledeger Id a byteString of just hex bytes rather than a bytes from a stirng representation of hex

- hedera-node/src/main/java/com/hedera/services/state/virtual/VirtualMapFactory.java
- pom.xml
> Integrate 0.23.0 SDK

- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java
- hedera-node/src/main/java/com/hedera/services/state/migration/StateChildIndices.java
- hedera-node/src/main/java/com/hedera/services/state/migration/StateVersions.java
- hedera-node/src/main/resources/throttles.json
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/ledger/BalanceChangeTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
> Uncomment commented specs

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
Disables virtual map flush throttle via a settings change.
Fixes #2902
> Disable virtual map flush throttle via a settings change.

- test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/SubmitMessageSuite.java
> 02907: Fix concurrent HCS suites

- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/state/migration/StateVersions.java
- pom.xml
- test-clients/pom.xml
- Roll _pom.xml_ versions + `StateVersion.CURRENT_VERSION`.
> Begin `0.24.0` dev iteration

- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
- hedera-node/src/test/java/com/hedera/services/contracts/operation/HederaSelfDestructOperationTest.java
- Fixes `HederaSelfDestructOperation` to compare the "priority form" of the beneficiary `Address` to the `MessageFrame` recipient address.
* Priority form is EIP-1014 if applicable; see [here](https://github.com/hashgraph/hedera-services/pull/2924) for tests verifying the recipient address is always the priority address.
> Patch fix for #2925

- .circleci/config.yml
Circle ci back to normal, no more 1 hour time limit.
> Revert "Split ci jobs (#2895)"

- test-clients/src/main/resource/FeeSchedule.json
Updated feeSchedules in `test-clients` to use latest fee schedule for Approve and Adjust Allowances
All tests passed : https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1646836909655569
> Fix failing EET tests

- benchmarks/pom.xml
- hapi-fees/pom.xml
- hapi-utils/pom.xml
- hedera-node/pom.xml
- hedera-node/src/main/java/com/hedera/services/state/migration/StateVersions.java
- pom.xml
- test-clients/pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/NWayDistNoHotspots.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/SimpleXfersAvoidingHotspot.java
- Updates _pom.xml_ version and `StateVersions.CURRENT_VERSION`.
- Adds a random EET client `NWayDistNoHotspots` that is useful for evaluating the perf impact of touching _n_ more leaves in the accounts `MerkleMap`.
> Begin 0.25 development iteration

- hedera-node/src/main/java/com/hedera/services/store/AccountStore.java
- hedera-node/src/main/java/com/hedera/services/store/models/Account.java
- hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoAdjustAllowanceTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/txns/crypto/CryptoApproveAllowanceTransitionLogic.java
- hedera-node/src/test/java/com/hedera/services/store/models/AccountTest.java
- hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoAdjustAllowanceTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoApproveAllowanceTransitionLogicTest.java
Description:
Checks if protobuf has approvedForAll set before checking the value
Fixes https://github.com/hashgraph/hedera-services/issues/3134
> Check ApproveForAll value is set before checking if it is true/false

- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensStateAfterReconnect.java
> dissociate from deleted token before deleting the treasury

- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateTokensStateAfterReconnect.java
Closes regression ticket #2254 
https://github.com/swirlds/swirlds-platform-regression/issues/2254
Test result passed
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1649690493399679
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1649693181291669
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1649695489217079
> Add delay before trying reconnect node

- hedera-node/src/main/resources/feeSchedules.json
> Fix typo in feeSchedules.json

- hedera-node/src/main/resources/bootstrap.properties
- hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
- hedera-node/src/test/resources/bootstrap/standard.properties
- pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenAssociationLoadTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
- test-clients/src/main/resource/bootstrap.properties
- Configures HIP-358: _**ON**_  (`accounts.limitTokenAssociations=false`)
- Configures HIP-367: _**ON**_ (`contracts.precompile.htsEnableTokenCreate=true`)
- Uses non-`SNAPSHOT` protobufs (`v0.25.1`)
> Set `v0.25.0` feature flags

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
This PR refactors the `ContractMintHTSSuite` and enriches the validations for `contractCallResult`
> Refactors ContractMintHTSSuite with contractCallResult assertions

- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
Fixed regression issue 2261 
https://github.com/swirlds/swirlds-platform-regression/issues/2261
Test result
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1650074052833519
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1650127071129859
> Fixed failed regression test congestion pricing ni reconnect

- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
Fix regression test issue 2279
https://github.com/swirlds/swirlds-platform-regression/issues/2279
Test result
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1650298389386599
Thanks for Micael's help.
> Add  createDefaultContract

- hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalExecutor.java
- hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java
- hedera-node/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java
- hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalExecutorTest.java
- hedera-node/src/test/java/com/hedera/services/queries/contract/ContractCallLocalAnswerTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
Add support for HIP-218 calls to ContractCallLocalQueries.
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #
**Checklist**
> Add HIP-218 support to local calls

- hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthereumTransactionTransitionLogicTest.java
Adds unit tests as per #3211.
Fixes #3211
> Add unit tests for checking invalid to addresses on contract call

- hedera-node/src/main/java/com/hedera/services/txns/token/process/Creation.java
- hedera-node/src/test/java/com/hedera/services/txns/token/process/CreationTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
> Filter existing association from auto-associations list in `TokenCreate` record

- .circleci/config.yml
This part of process to change regression sub repo to independent repo.
Changes
- Add platform repo parameter to JRS and related test flows
Test result:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1650841293300799
> 02266 d add platform location

- .circleci/config.yml
> Create JRS keys directory

- hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
- hedera-node/src/main/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdater.java
- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
- hedera-node/src/main/java/com/hedera/services/txns/token/CreateLogic.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdaterTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
- hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/GracePeriodRestrictionsSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
- Stabilizes CI by porting several auto-association record fixes from `eth-tx-interop`.
> Port misc fixes from `eth-tx-interop`

- .circleci/config.yml
Updates the CI pipelines to account for files moved in the JRS repository. 
Related to swirlds/swirlds-platform-regression#2307
> CI Pipeline updates for JRS changes

- pom.xml
Adds Platform prerelease Maven repository definitions. 
Fixes #3357 
N/A
> Adds support for Platform GCP GAR prerelease channels

- test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Signed-off-by: Dimitar Dinev <mitkojc@gmail.com>
Adds the negative scenario for ETX-012/013, in which the needed signature from the precompile call is not present in either Ethereum or Hedera transaction and the execution should fail with `INVALID_SIGNATURE.`
Fixes #
**Checklist**
> Add negative scenario for ETX-012/13 from the Ethereum test plan

- .circleci/config.yml
> Update CI pipelines to use new Slack API Token Override in JRS

- pom.xml
> Use latest SDK

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DissociatePrecompileSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/MixedHTSPrecompileTestsSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
E2E additional contactResult check for child records.
[003239](https://github.com/hashgraph/hedera-services/issues/3239)
> e2e update with contactCallResults

- .circleci/config.yml
Part of regression PR
https://github.com/swirlds/swirlds-platform-regression/pull/2437
> remove unused 

- hedera-node/src/test/java/com/hedera/services/sigs/HederaToPlatformSigOpsTest.java
- Ensures the accessor passed to `performFor()` has a public-key-to-crypto-sig mapping that is consistent with the public keys returned from the test's mock `SigRequirements`.
* Previously the test would fail whenever the randomly generated `SignatureMap` in the underlying Hedera `Transaction` included a key with a prefix that overlapped with one of these keys.
> Stabilize `HederaToPlatformSigOpsTest.doesNothingToTxnIfAllSigsAreRational()` 

- hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java
- hedera-node/src/test/java/com/hedera/services/txns/token/TokenUpdateTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Signed-off-by: Tanyu Dermendzhiev <tanyu.dermendzhiev@limechain.tech>
Added functionality for auto association of new token treasury set via TokenUpdate
**Related issue(s)**: #3086
> auto association for new token treasury set via tokenUpdate

- hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleScheduledTransactions.java
- hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleScheduledTransactionsState.java
- hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
- hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java
- hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleScheduledTransactionsStateTest.java
- hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
Minor cleanup of changes from https://github.com/hashgraph/hedera-services/pull/3234
Fixes https://github.com/hashgraph/hedera-services/issues/3491
**Checklist**
> feat(#3069): long term scheduled transactions - minor cleanup

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ResetTokenMaxPerAccount.java
Modify ResetTokenMaxPerAccount.java to only allow one client to update throttle file.
Closes #3497 
Test result
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654530700345879
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654540234710989
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654555058189789
> 03497 refactor reset token max per account

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/ResetTokenMaxPerAccount.java
Part of PR to resolve
regression repo issue 2504
https://github.com/swirlds/swirlds-platform-regression/issues/2504
Test result
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654555058189789
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654548788649009
> 02504 refactor reset token max per account

- .circleci/config.yml
- test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/props/MapPropertySource.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/regression/UmbrellaRedux.java
- test-clients/src/main/resource/logback.xml
Part of regression PR
https://github.com/swirlds/swirlds-platform-regression/pull/2520
Also closes issue #3503
"status.wait.timeout.ms=60000" used in launching client is not
being picked up correctly by test suite.
Miachel helped to identify the issue and suggested fix.
---
Test result
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654755035195079
https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1654785459776629
> Fix wait response time and logback configuration file

- hapi-utils/src/main/java/com/hedera/services/keys/Ed25519Utils.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyFactory.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/NewSpecKey.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/AccountsCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/CreateCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigUtils.java
- test-clients/src/main/java/com/hedera/services/yahcli/suites/CreateSuite.java
- test-clients/src/main/java/com/hedera/services/yahcli/suites/RekeySuite.java
- test-clients/yahcli/README.md
- Provides a yahcli `accounts create` subcommand to create a new account.
> Add yahcli `accounts create` subcommand

- pom.xml
Upgrade teh besu-native dependency to 0.5.0.
Major feature is arm-linux support.
Fixes #3546
**Checklist**
> Upgrade besu-native dependency

- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
- hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
- Sets the `sender_id` in a precompile record.
> Include fix from 0.26

- pom.xml
- Need `RandomGenerate` in snapshot proto artifact for now.
> Use a protobuf with `RandomGenerate`

- hapi-utils/src/main/java/com/hedera/services/sysfiles/serdes/FeesJsonToProtoSerde.java
- hapi-utils/src/main/java/com/hedera/services/sysfiles/validation/ExpectedCustomThrottles.java
This PR applies the fixes to the sonar issues reported in the #3647 pull request.
Partial Resolution of #3642 
**Notes to Reviewer**:
This PR needs to merge before #3647
> Apply Spotless Formatting - Part 6

- hedera-node/configuration/previewnet/bootstrap.properties
> Use V6 record stream in previewnet

- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
> Remove `jasperDb.indexRebuildingEnforced` overrides

- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/ThrottlesJsonToGrpcBytes.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/keys/NewPemCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
- test-clients/yahcli/README.md
- test-clients/yahcli/run/build.sh
- Make yahcli Docker images multi-architecture
- Avoid `UnsupportedOperationException` from `STANDARD_SERDES` now being an immutable map.
- Update yahcli version to `0.2.1`
> yahcli fix + `multiarch` build

- .github/workflows/comp-compile-application-code.yaml
- .github/workflows/flow-build-application.yaml
- .github/workflows/flow-pull-request-checks.yaml
- hapi-utils/src/main/java/com/hedera/services/throttles/BucketThrottle.java
- hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java
- hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitBucketThrottle.java
- hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitDeterministicThrottle.java
- hapi-utils/src/test/java/com/hedera/services/throttles/BucketThrottleTest.java
- hapi-utils/src/test/java/com/hedera/services/throttles/DeterministicThrottleTest.java
- hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitBucketThrottleTest.java
- hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitDeterministicThrottleTest.java
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
- hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java
- hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContractTest.java
- pom.xml
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/util/PrngSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/ThrottlesJsonToGrpcBytes.java
- test-clients/src/main/java/com/hedera/services/yahcli/commands/keys/NewPemCommand.java
- test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
- test-clients/yahcli/README.md
- test-clients/yahcli/run/build.sh
> Merge master

- .circleci/config.yml
- test-clients/build.gradle.kts
Updates CircleCI to use gradle for all builds where applicable. 
Fixes #3463
This pull request must merge simultaneously with the following related pull requests: 
- swirlds/swirlds-platform-regression#2649
- swirlds/swirlds-platform#5717
> Update CircleCI automation to use Gradle

- hedera-node/src/main/java/com/hedera/services/context/BasicTransactionContext.java
- hedera-node/src/main/java/com/hedera/services/context/TransactionContext.java
- hedera-node/src/main/java/com/hedera/services/records/InProgressChildRecord.java
- hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java
- hedera-node/src/main/java/com/hedera/services/records/TransactionRecordService.java
- hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
- hedera-node/src/main/java/com/hedera/services/state/submerkle/EvmFnResult.java
- hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java
- hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java
- hedera-node/src/main/java/com/hedera/services/stream/RecordStreamObject.java
- hedera-node/src/main/java/com/hedera/services/stream/RecordStreamType.java
- hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
- hedera-node/src/main/java/com/hedera/services/utils/ResponseCodeUtil.java
- hedera-node/src/test/java/com/hedera/services/context/BasicTransactionContextTest.java
- hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
- hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultSerdeTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java
- hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
- hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
- hedera-node/src/test/java/com/hedera/services/stream/RecordStreamManagerTest.java
- hedera-node/src/test/java/com/hedera/services/stream/RecordStreamTypeTest.java
- hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
- hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java
Spotless formatting for #3625
PR # 3625
**Checklist**
> Spotless formatting for sidecar work

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermSignSpecs.java
Signed-off-by: ivanparnarev <ivan.parnarev@limechain.tech>
**Description**: Ensured that the payer has enough balance in order to fix E2E tests.
Fixes #
**Checklist**
> Fix tests that fail with INSUFFICIENT_PAYER_BALANCE

- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/main/java/com/hedera/services/config/HederaNumbers.java
- hedera-node/src/main/java/com/hedera/services/context/properties/SerializableSemVers.java
- hedera-node/src/main/java/com/hedera/services/state/initialization/TreasuryCloner.java
- hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- hedera-node/src/test/java/com/hedera/services/context/properties/SerializableSemVersTest.java
- hedera-node/src/test/java/com/hedera/services/state/initialization/TreasuryClonerTest.java
- hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
- Ports changes in https://github.com/hashgraph/hedera-services/pull/3768
- Drops NFT rationalization since this is now done in all production states.
> Fixes for `v0.28.6`

- .github/CODEOWNERS
- .github/workflows/comp-build-release-artifact.yaml
- .github/workflows/comp-compile-application-code.yaml
- .github/workflows/flow-build-application.yaml
- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/flow-pull-request-checks.yaml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/RepairDashedCommentsFormatterStep.kt
- buildSrc/src/main/kotlin/StripOldLicenseFormatterStep.kt
- buildSrc/src/main/kotlin/Utils.kt
- buildSrc/src/main/kotlin/com.hedera.hashgraph.aggregate-reports.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.benchmark-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.hedera-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
- compose-build.sh
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- hapi-fees/build.gradle.kts
- hapi-utils/build.gradle.kts
- hedera-node/build.gradle.kts
- hedera-node/configuration/update/during-freeze.sh
- hedera-node/configuration/update/immediate.sh
- settings.gradle.kts
- test-clients/build.gradle.kts
Adds support for creating a release artifact based on the requirements given in swirlds/infrastructure#2719 along with the necessary gradle changes.
Fixes #3767 
Depends On swirlds/infrastructure#2910
**NOTE: Only to merged by @nathanklick or @tannerjfco in coordination with other pull requests in the infrastructure repository!!!**
> Add CI pipelines for release artifact builds

- hedera-node/src/jmh/java/com/hedera/services/setup/InfrastructureType.java
- hedera-node/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
- Don't discard prepared upgrade metadata unless version has actually increased.
> Only discard upgrade metadata if version has increased

- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
Signed-off-by: Nana-EC <nana@swirldslabs.com>
Fixes #3802 
**Checklist**
> Localize Gas Calculation

- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
Add test cases for grant/revoke with account that has key not matching token KYC key that
should revert with invalid signature status.
Fixes # TBD
**Checklist**
> Add more GrantRevokeKycSuite test cases

- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
- settings.gradle.kts
Upgrade Besu to 22.7.1, remove old overrides.
Fixes #3824
**Checklist**
> Upgrade Besu to 22.7.1

- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
- hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
- settings.gradle.kts
> Cherry-pick 22.7.1 Besu

- .github/workflows/comp-build-release-artifact.yaml
- gradle.properties
- settings.gradle.kts
> Update services version

- .github/workflows/flow-deploy-release-artifact.yaml
- README.md
- buildSrc/src/main/kotlin/com.hedera.hashgraph.aggregate-reports.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
- hapi-fees/build.gradle.kts
- hapi-utils/build.gradle.kts
- hedera-node/build.gradle.kts
- hedera-node/hedera-app-api/build.gradle.kts
- hedera-node/hedera-app/build.gradle.kts
- hedera-node/hedera-evm-api/build.gradle.kts
- hedera-node/hedera-evm-api/src/main/java/module-info.java
- hedera-node/hedera-evm/build.gradle.kts
- test-clients/build.gradle.kts
Adds Maven Central publish support for the `hedera-evm-api` Gradle module. 
- Closes #3980
> Add Maven Central publishing support

- docs/design/alias-configuration.md
Signed-off-by: Miroslav Gatsanoga <miroslav.gatsanoga@limechain.tech>
**Related issue(s)**: **Related issue(s)**: https://github.com/hashgraph/hedera-services/issues/3827, https://github.com/hashgraph/hedera-services/issues/3828, https://github.com/hashgraph/hedera-services/issues/3829
Fixes #3827
Fixes #3828 
Fixes #3829 
**Checklist**
> Update alias design with additional notes

- hedera-node/src/main/java/com/hedera/services/utils/forensics/RecordParsers.java
- Fix last-minute merge conflict causing import mismatch.
> Fix merge conflict

- docs/design/evm-versioning.md
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_32Module.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsTestComponent.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Updates the version of number of the evm changes to match the Hedera services version number with which the changes are associated.
**Checklist**
> update version number of evm from v0.31.0 to v0.32.0

- hedera-node/src/main/java/com/hedera/services/grpc/marshalling/CustomFeeMeta.java
- hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java
- hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
- hedera-node/src/main/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedules.java
- hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomFeeMetaTest.java
- hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshalTest.java
- hedera-node/src/test/java/com/hedera/services/state/logic/StandardProcessLogicTest.java
- hedera-node/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
- settings.gradle.kts
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- Use final 0.31.x SDK, misc cleanup.
> Use non-alpha SDK

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
Reverts hashgraph/hedera-services#3228
> Revert "Remove `virtualMap.preferredFlushQueueSize` overrides"

- settings.gradle.kts
> Change Platform SDK version

- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/codec/CryptoTransferWrapper.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/codec/TransferWrapper.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERCTransferPrecompileTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/codec/TransferWrapperTest.java
The wrapper class for cryptoTransfer needs to be refactored in order to support hbar transfers.
Epic: #4084 
**Related issue(s)**: #3758 
Fixes #4085 
**Checklist**
> Refactor wrapper for atomic crypto transfer

- gradle.properties
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/grpc/marshalling/CustomFeeMeta.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedules.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/grpc/marshalling/CustomFeeMetaTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshalTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
> Start 0.32 dev iteration

- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
Cherry-picking the PR merge of  #4148
> Fill `stakePeriodStartUpdates` array with `NA`

- settings.gradle.kts
Services version bump of platform dependency
> Platform version bump

- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/HapiSpecWaitUntil.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
- Second half of https://github.com/hashgraph/hedera-services/pull/4282.
> Check for zero-rewards-from-zero-stake condition in `stakePeriodStart` mgmt

- hedera-node/configuration/mainnet/bootstrap.properties
For `v0.31.3` upgrade:
- Disable contract sidecars
- Disable contract expiration
- Disable "traceability export" system task
> Disable contract expiry, sidecars + don't do traceability export

- hedera-node/hedera-app-spi/build.gradle.kts
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreHandleContext.java
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/States.java
- hedera-node/hedera-app-spi/src/main/java/module-info.java
- hedera-node/hedera-app/build.gradle.kts
- hedera-node/hedera-app/src/itest/java/grpc/GrpcTransactionTest.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/GrpcServiceBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/KnownLengthStream.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/NoopMarshaller.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/QueryMethod.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/TransactionMethod.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
fix for #4371
Labeled as `P1` based on the code freeze till modularization is done
> null annotations in hedera app

- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCache.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/WorldStateAccount.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/MockHederaEvmTxProcessor.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCacheTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_30Module.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_32Module.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperation.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
- settings.gradle.kts
Upgrade the Besu EVM to 22.10.1
Fixes #4400
**Checklist**
> Upgrade Besu EVM to 22.10.1

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/SigWaivers.java
- hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/PreHandleContextTest.java
- hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/AbstractCodeCache.java
- hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
- hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/WorldStateAccount.java
- hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/MockHederaEvmTxProcessor.java
- hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/AbstractCodeCacheTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoSignatureWaiversImpl.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_30Module.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_32Module.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CallEvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/AbstractRecordingCreateOperation.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/AliasManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/AliasManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
- settings.gradle.kts
Bump platform version to 0.33.0-alpha.4 
Incorporated select changes from PR 4386
> Bump platform version

- test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/MixedSmartContractOpsLoadTest.java
Fix BigInteger casting issue in one of the E2E test suites.
Fixes #4383 
**Checklist**
> Fix E2E BigInteger casting issue

- .circleci/config.yml
Closes #4472
Test result
no longer has **ERROR StatusLogger Reconfiguration failed**
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/50277/workflows/af8f9309-c62d-4165-a7ae-728f1b962af6/jobs/143751
> Update log4j2 file name used in circle ci pipeline

- test-clients/build.gradle.kts
- test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/Scenarios.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/StakingScenario.java
- Add `STAKING` validation scenario that stakes the scenario payer to every node id in the `0.0.102` address book.
> Add staking validation scenario

- hedera-node/data/config/bootstrap.properties
- hedera-node/hedera-mono-service/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakePeriodManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakePeriodManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
> Port staking fix

- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakePeriodManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakingUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/TimedFunctionalityThrottling.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/TxnAwareHandleThrottling.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsageTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakingUtilsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/queries/contract/ContractCallLocalAnswerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/throttling/TxnAwareHandleThrottlingTest.java
- settings.gradle.kts
- Ports misc patches for `v0.33.1`
- Uses `0.33.0` proto artifact.
> Fixes for 0331

- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseCall.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/ContractScenario.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/Network.java
- Re-works `contractScenario()` in _ValidationScenarios.jar_ to use new EET contract operations.
- Adds `defaultFeeInHbars` property.
> Fix `VS` contract scenario

- settings.gradle.kts
Update hapi version to 0.33.1-SNAPSHOT
> Update Hapi version

- buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
- hedera-node/hedera-mono-service/build.gradle.kts
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigratorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySerializerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySupplierTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeyTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValueSupplierTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValueTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactoryTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/BurnLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/MintLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/subjects/UniqueTokenValueSubject.java
- settings.gradle.kts
> Google Truth removed

- .circleci/config.yml
> Don't delete summary test files from google storage during rsycn process

- buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
- gradle.properties
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AutoRenewCalcsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListenerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/ResponsibleVMapUser.java
- settings.gradle.kts
- test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
> Update platform and services version numbers

- buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
- gradle.properties
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AutoRenewCalcsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListenerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/ResponsibleVMapUser.java
- settings.gradle.kts
Signed-off-by: Michael Tinker <michael.tinker@swirldslabs.com>
Co-authored-by: Neeha <52669918+Neeharika-Sompalli@users.noreply.github.com>
Co-authored-by: Neeharika-Sompalli <neeharika.sompalli@swirldslabs.com>
Co-authored-by: Michael Tinker <michael.tinker@swirldslabs.com>
> Update platform and services version numbers (#4558)

- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/preprod/bootstrap.properties
- hedera-node/configuration/previewnet/bootstrap.properties
- hedera-node/configuration/testnet/bootstrap.properties
Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
Fixes #4568
**Checklist**
> Enable HIP-583 feature flags for previewnet and preprod

- .github/workflows/comp-compile-application-code.yaml
- buildSrc/src/main/kotlin/Utils.kt
- gradle.properties
Updates the workflows to use the patched test reporter step and configures it not create a check run.
- Closes #4575
> Update workflows to use patched test reporting step

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Signed-off-by: Miroslav Gatsanoga <miroslav.gatsanoga@limechain.tech>
Fixes #
**Checklist**
> Fix hollow account with CryptoCreate to set EMPTY_KEY instead on null

- settings.gradle.kts
> Bump platform version in services to v0.35.0-alpha.1

- hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessor.java
- hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
- Ports missing PR's #4381 and #4432
> Port `v0.33.3` fixes

- hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessor.java
- hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/forensics/ServicesIssListener.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/forensics/ServicesIssListenerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Closes #4639 
We need to test this. Hand tests might be the fast way of verifying this fix.
> Fix state leak during ISS.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
Cherry-picked https://github.com/hashgraph/hedera-services/pull/4640
> Fix state leak during ISS

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
Fixes #4639 
Cherry-picks #4669
> Fix state leak during ISS (#4669)

- .circleci/config.yml
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Resolve regression issue #3085
https://github.com/swirlds/swirlds-platform-regression/issues/3085
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1673991616079089
> Get record stream header info from command line parameter

- .circleci/config.yml
Adds python virtual environment support to the CircleCI pipelines.
- Closes #4683
> Add support for python virtual environment in CircleCI 

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
> Fix `contractCallResult` in txn record on hollow account creation via top-level `EthereumTransaction`

- settings.gradle.kts
> Integrate platform 0.35.0

- hedera-node/configuration/mainnet/settings.txt
Disables chatter in the mainnet environment profile.
- Closes #4697
> Update environment configuration files

- hedera-node/configuration/testnet/settings.txt
> Disable chatter in testnet config

- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Fixes #4670 
Add staking test with `isReceiverSigRequired=true`
> Add staking test with `isReceiverSigRequired=true`

- .github/workflows/config/release.yaml
- .github/workflows/support/scripts/release-branch-check.sh
- .github/workflows/xcron-release-branching.yaml
- hedera-node/configuration/preprod/log4j2.xml
Adds a new CI pipeline to automatically create release branches based on a configuration file containing a schedule. 
- Closes #4688
> Add CI pipeline support for automatic release branch creation

- .github/workflows/config/release.yaml
Change release branch creation time to 11 AM
> Change release branch creation time

- hedera-node/configuration/previewnet/settings.txt
- hedera-node/settings.txt
Disable chatter on previewnet and use maxEventQueueForCons=1K
> Disable chatter on previewnet

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacks.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/SigImpactHistorian.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/RationalizedSigMeta.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacksTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookupTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/RationalizedSigMetaTest.java
- test-clients/src/main/java/com/hedera/services/bdd/junit/validators/HgcaaLogValidator.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Signed-off-by: Miroslav Gatsanoga <miroslav.gatsanoga@limechain.tech>
Fixes #
**Checklist**
> Cherry pick tracking property changes for 0.35

- gradle.properties
> Update services version num to 0.36.0-SNAPSHOT

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ParityTestBase.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
* Adds the pre handle logic for token mint
Fixes #4593
> Implement TokenMintHandler prehandle

- settings.gradle.kts
Update platform version to `0.35.2`
> Update platform version

- .circleci/config.yml
Update hedera-services to use FSTS command line parameters instead of system properties for CircleCI overrides.
closes: https://github.com/swirlds/swirlds-platform-regression/issues/3128
**Checklist**
regression test results: https://swirldslabs.slack.com/archives/C04HRF2AN5S/p1675298015114729
> update hedera-services to use FSTS CLI instead of system properties

- test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
Fixes #4849 #4848 
Added tests for validating auto-renew behavior
> Add a test for validating auto-renew behavior

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelper.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelperTest.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
> Fix `nftsOwned` for treasury during expiry

- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractEvmStackedLedgerUpdater.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockAccountAccessor.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdater.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MockLedgerWorldUpdater.java
This is a cherry-pick for changes in the Updater components that enhance token redirect logic. We need it to support ERC token precompiles with `eth_call` on the Mirror Archive Nodes.
Fixes #
**Checklist**
> Adding support for Redirect Token Calls for hedera-evm (#4880)

- .circleci/config.yml
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Closes regression issue #3178
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1676044662818399
> Update parameter name to avoid confusion

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
- settings.gradle.kts
- removing the use of evm_address from cryptoCreate
- Add missing validation for long zero address
Fixes #
**Checklist**
> Crypto create refactoring

- hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/keys/Ed25519UtilsTest.java
> Fix unit test

- settings.gradle.kts
> Upgrade platform dependency to `0.36.0-alpha.2`

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockNumberMeta.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ReconnectListener.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/RecordStreaming.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriter.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamObject.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/BlockManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ReconnectListenerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/RecordStreamingTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamObjectTest.java
Cherry-pick #4924 
Signed-off-by: Michael Tinker <michael.tinker@swirldslabs.com>
> Clean up block number/record file relationship (#4924)

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
- hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/keys/Ed25519UtilsTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
- settings.gradle.kts
- test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java
- test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
- test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Cherry-pick #4907 #4940 
Signed-off-by: Tanyu Dermendzhiev <tanyu.dermendzhiev@limechain.tech>
Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
Signed-off-by: Nana Essilfie-Conduah <nana@swirldslabs.com>
Signed-off-by: Michael Tinker <michael.tinker@swirldslabs.com>
Co-authored-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
Co-authored-by: Nana Essilfie-Conduah <nana@swirldslabs.com>
Co-authored-by: Michael Tinker <michael.tinker@swirldslabs.com>
> Cherry pick 4907

- settings.gradle.kts
> Upgrade platform dependency to 0.36.0

- hedera-node/test-clients/src/eet/resources/log4j2.xml
- hedera-node/test-clients/src/itest/resources/log4j2.xml
> Reduce itest and e2e test logging to ERROR or above

- .github/workflows/comp-build-release-artifact.yaml
- .github/workflows/comp-compile-application-code.yaml
- .github/workflows/flow-build-application.yaml
- .github/workflows/flow-pull-request-checks.yaml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
- gradle.properties
This pull request updates the Gradle configuration to use the Palantir plugin and adds a new Spotless Check CI pipeline. Enforcement is currently disabled and the CI pipeline Spotless / Check may be safely ignored if it fails.
- Closes #4976
> feat: update code style enforcement and configuration

- hedera-node/docs/design/modules.md
A documentation that describes the general structure of all modules of the project.
> (Gradle) Module Documentation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerParityTest.java
Adds the pre handle logic for token update
Based on: https://github.com/hashgraph/hedera-services/pull/4503
Fixes #4499
> Implement TokenUpdateHandler preHandle

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerParityTest.java
Adds the pre handle logic for token delete
Based on: https://github.com/hashgraph/hedera-services/pull/4579
Fixes #4578
> Implement TokenDeleteHandler preHandle

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
Adds the pre handle logic for token freeze
Fixes #4580
> Implement TokenFreezeAccountHandler preHandle

- settings.gradle.kts
Update platform version to 0.35.3
> Update platform version to 0.35.3

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
> Port NFT logging (#4978)

- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-flow-snyk-monitor.yml
- .github/workflows/node-zxc-compile-application-code.yaml
This PR modifies PR checks to add Snyk vulnerability scanning and fail the checks on vulnerabilities that are of High or Critical severity. 
It also keeps the snapshot used for ongoing monitoring updated on the Snyk servers to the current develop branch.
* Add PR check step
* Add workflow for Snyk monitoring
Fixes #
**Checklist**
> Add Snyk scanning

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerParityTest.java
Adds the pre handle logic for token burn
Fixes #4590
> Implement TokenBurnHandler preHandle

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
Adds the pre handle logic for token wipe
Fixes #4994
> Implement TokenAccountWipeHandler preHandle 

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerParityTest.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
- hedera-node/hedera-consensus-service-impl/src/test/java/module-info.java
- hedera-node/hedera-mono-service/src/main/java/module-info.java
- hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/accounts/MockMMapFactory.java
> Implement topic deletion prehandle

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/validation/TokenPuvSuite.java
One-line code change to add missing teardown code
Fixes issue #5037
> Add missing code to TokenPUV test suite cleanup

- .circleci/config.yml
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
Fixes https://github.com/swirlds/swirlds-platform-regression/issues/3186
Test result : https://swirldslabs.slack.com/archives/C03FD752LKA/p1677110795729119
> Fix regression test

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
Resolves the CI pipeline issues preventing Snyk and Sonar analysis from running on the `push` and `workflow_dispatch` triggers.
- Closes #5049
> fix: resolve issues in the CI pipeline preventing Snyk and Sonar analysis from running on push and workflow_dispatch triggers

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
This change restores the E2E and Integration test capture of the network node logs as a CI pipeline build artifact. 
- Closes #5061
> feat: updates the e2e and itest based network log captures and adds a conditional flag

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
> Fix hash stream log.

- platform-sdk/sdk/log4j2.xml
> Fix log4j configuration for local tests.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerDouble.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerSingle.java
> Fix minGenInfo in signed state.

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/exceptions/HandleStatusException.java
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java
- hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/exceptions/HandleStatusExceptionTest.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoTransitionRunner.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoTransitionRunnerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidatorTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
- Closes #4958 
- Closes #4764
> Implement `TopicUpdate` handle logic

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
> Topic Update preHandle

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
Closes #5153 
The settings changes made in this PR should also be applied to all production environments with version 0.35 and higher.
> Disable transThrottle.

- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/testnet/bootstrap.properties
enable node software compression of recordstream and account balance files for mainnet
> enable node software compression of recordstream and account balance files for mainnet

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/CodecFactory.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/MonoMapCodecAdapter.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/AbstractVirtualCodecTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/CodecFactoryTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/DataBufferTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/MonoMapSerdesAdapterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/UtilsConstructorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualKeySerdesAdapterTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualValueSerdesAdapterTest.java
- hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
Changes required to make mono-service compile and all but one test succeed
> Mono-service fixes for PBJ-branch

- hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/UtilPrngHandler.java
- hedera-node/hedera-util-service-impl/src/main/java/module-info.java
- hedera-node/hedera-util-service-impl/src/test/java/module-info.java
**Related issue(s)**: use PBJ entities on hedera-util-service
Fixes #5436
**Checklist**
> 5436 use pbj util service

- hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
- hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemDeleteHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemUndeleteHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EtherumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/AdapterUtils.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerParityTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerParityTest.java
> Fix tests in smart contract impl module

- hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-admin-service-impl/src/main/java/module-info.java
- hedera-node/hedera-admin-service-impl/src/test/java/module-info.java
Fix issues with integrating pbj into hedera-admin-service and hedera-admin-service-impl
Fixes #5429
> Update admin modules to use pbj libraries

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileManagerTests.java
> Fix flaky test.

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountDetailsAsserts.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransferListAsserts.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/Contract.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/File.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoDeleteAllowance.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/network/HapiUncheckedSubmit.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenPause.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnpause.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CongestionPricingSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/PermissionSemanticsSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/CreateFailuresSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/positive/SysDelSysUndelSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1765Suite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/KeyExport.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithInvalidAccounts.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileExpansionLoadProvider.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/UniqueTokenStateSetup.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
Code Smoke : Lambdas containing only one statement should not nest this statement in a block java:S1602
Fixes #5688
> 5688 - Removed curly braces and returns when there is just one statement in the lambda

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetRecordsHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
> Smart Contracts PBJ Round 2

- .github/CODEOWNERS
Based on the feedback from @poulok, these changes represent the final disposition of the Platform SDK code owners. 
- Closes #5692
> chore: update Platform SDK code owners

- .github/workflows/zxc-jrs-regression.yaml
Fix the error when launching regression tests
```
Unknown options: '-w', 'configs/services/suites/daily/GCP-Daily-Services-Crypto-Migration-7N-1C.json'
```
> Remove workflow parameter

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/SyncPermit.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/SyncPermitTest.java
Add the `SyncPermit` class in preparation for #5702 
Fixes #5776
This code is not currently used except for in unit tests.
**Checklist**
> Sync Permits

- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/ids/SeqNoEntityIdSourceTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
Fix compile errors in hedera-mono-service following latest pbj updates.
Issue #5833
> Fix compile errors in mono-service

- hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/DataBufferMarshaller.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/GrpcServiceBuilder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/KnownLengthStream.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/QueryMethod.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/DataBufferMarshallerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/GrpcServiceBuilderTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/QueryMethodTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/TransactionMethodTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ReadableTopicStore.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStore.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountRecordsHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetLiveHashHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetStakersHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetAccountNftInfosHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetInfoHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfoHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfosHandler.java
- hedera-node/hedera-token-service/build.gradle.kts
Fixes #5837
Related to #5830 
Minor changes in consensus service and token service PBJ + spotless .
> Minor changes in consensus service and token service PBJ

- settings.gradle.kts
Update pbj version in use by use-pbj branch to 0.5.0
Issue #5854
> Update pbj version num

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
> Smart contract service review

- hedera-node/hedera-app/build.gradle.kts
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/AbstractVirtualCodecTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/DataBufferTest.java
- Fixes remaining failing unit tests on PBJ branch.
> Fix unit tests

- settings.gradle.kts
Update protobufs to v0.36.0 tag
> Update protobufs to v0.36.0 tag

- settings.gradle.kts
Update protobufs to v0.36.1 tag
> Update protobufs to v0.36.1 tag

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
Please check in particular, if the changes in `PbjConverter` are correct
> Fix for IngestCheckerTest

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/SyncFallenBehindStatus.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestExecutor.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTests.java
bug introduced recently
closes https://github.com/swirlds/swirlds-platform-regression/issues/3310
> fix fallen behind

- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/testnet/bootstrap.properties
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Update typo `CONTRACT_STATE_CHANGE`
> Update typo `CONTRACT_STATE_CHANGE`

- settings.gradle.kts
cherry pick update gradle kts file. 
Fixes #5951
> 5951 gradle kts update release branch

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/signingtool/FileSignTool.java
Regression issue 3316
https://github.com/swirlds/swirlds-platform-regression/issues/3316
Part of PR
https://github.com/swirlds/swirlds-platform-regression/pull/3325
> Update FileSignTool to support compressed rcd file with extension "rcd.gz"

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
> Fix flaky preconsensus event stream test

- hedera-node/configuration/mainnet/bootstrap.properties
Add property overrides to turn on balance and recordstream compression on mainnet
> balance and recordstream compression prop update mainnet

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
Explicitly disable `transThrottle` in all environments
> Explicitly disable `transThrottle`

- settings.gradle.kts
Change HAPI Jar  and use long running branch for state PBJ types in `hedera-protobufs`
> Change HAPI Jar

- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Fix NPE in `SigReqAdapterUtils`
> Fix NPE in `SigReqAdapterUtils`

- hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
Cherry picking https://github.com/hashgraph/hedera-services/pull/6069.
Fixes #
**Checklist**
> Make accounts blocklisting feature flag disabled by default (#6069)

- settings.gradle.kts
> change hapi version

- platform-sdk/gradle.properties
Update platform version to 38.
Fixes #6075
> update platform version to 38

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactoryTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenRelationStoreTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
> Implement Token Grant KYC Handle

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
> Fix angry log message when state metadata doesn't record any state signatures

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SavedStateLoader.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/BootstrapUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
> Use correct path when loading state.

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyUtils.java
> Added break statement.

- .github/workflows/platform-flow-jrs-daily-regression.yaml
- .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
> Add new test workflow

- .github/workflows/platform-flow-deploy-ea-release.yaml
- .github/workflows/platform-flow-deploy-mc-release.yaml
- .github/workflows/platform-zxc-release-internal.yaml
- .github/workflows/platform-zxc-release-maven-central.yaml
This pull request updates the Platform SDK CI release pipelines to allow the MC and EA releases to function in the merged repository layout.
- Closes #6286
> feat: update Platform SDK CI/CD release pipelines to support the integrated repository 

- settings.gradle.kts
Updates the Platform SDK version for the upcoming Hedera Node Software release.
> feat: update Platform SDK version number

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
> Increase the TPS for AddressBookTestingTool to 1k

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
Related to #6368
Needs to be cherry-picked into `develop` before closing issue
> Add feature flag for state ref count debug feature.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
Closes #6368 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/6404
> 06368 d ref count debug flag

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompile.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompileTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
- #6322 for 0.38
⚠️ **NOTE TO REVIEWER:** The Integration Tests check failure was a [well-known flaky test](https://scans.gradle.com/s/6i5d3aj2audsa/tests/:hedera-node:test-clients:itest/AllIntegrationTests/concurrentSpecs()%5B1%5D?top-execution=1).
> Cherry pick 6322

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
> Don't send signature transactions unless the node is active.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
> Continue sending signature transactions during a freeze.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
> Fix state loading.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
> Flatten buildEventIntake()

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/legacy/LegacyConfigPropertiesLoader.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/GenesisStateBuilder.java
Fix #6528
Also refactored the access to make the dependency clearer
> #6528 Add support back for genesisFreezeTime

- settings.gradle.kts
> update platform build to 0.38.0

- settings.gradle.kts
> change platform version to final 0.38

- platform-sdk/swirlds-platform-core/src/main/java/module-info.java
> Export sync config to config impl.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlow.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlowTest.java
Fixes https://github.com/hashgraph/hedera-services/issues/6605
Zero stake nodes (nodes that have zero weight in address book) will be able to submit transactions.
> Remove zero stake check in submission

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlow.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlowTest.java
Cherry-Pick #6604 
Zero stake nodes (nodes that have zero weight in address book) will be able to submit transactions.
> Remove zero stake check in submission (#6604)

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/InvariantChecks.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/InvariantChecksTest.java
- Follow-up to https://github.com/hashgraph/hedera-services/pull/6604
- Drops the same check in `handle()`.
> Remove unwanted check

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
> Set ReconnectController state to null after releasing

- hedera-node/docs/design/services/token-service/hollow-finalization.md
Adds a hollow account finalization design doc as per #5753 
Fixes #5753
> Аdd hollow account finalization doc

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
> Add token grant kyc checks

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenRevokeKycFromAccountHandlerTest.java
> Add checks for token revoke

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/adapters/VirtualMapLikeAdapterTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKeySerializer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKeySerializer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySerializer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobKeySerializer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleEqualityVirtualKeySerializer.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/temporal/SecondSinceEpocVirtualKeySerializer.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/adapters/VirtualMapLikeTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualBlobKeySerializer.java
- hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AddresBookUtils.java
- settings.gradle.kts
> integrate with platform adhoc build 0.39.0-adhoc.xa9477c7f

- platform-sdk/swirlds-cli/pcli.sh
> Cause pcli.sh to fall back to no color if the color script is missing

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccess.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccessTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
- Cherry-pick of https://github.com/hashgraph/hedera-services/pull/6679
> Cherry pick #6679

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccess.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccessTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
- Re-used `EvmSigsVerifier` in `ContractCallTransitionLogic`.
> Refactor top-level sig check

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/NodeId.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigSet.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeDataImpl.java
> 06671 NodeId implements SelfSerializable

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
This is a follow-up for #5825 . It enables leaf rehashing in the upgrade scenarios and removes comments that are no longer necessary.
Fixes #6037
> 06037 Enabled leaf rehashing for existing VirtualMap instances.

- hedera-node/hedera-app/src/test/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
- hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
- hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
- hedera-node/test-clients/src/main/resource/bootstrap.properties
Added `contracts.nonces.externalization.enabled` feature flag
Fixes #6720
> 06720: Added contracts.nonces.externalization.enabled feature flag

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
> 06737 - AddressBook.toConfigText() Supports Memo

- platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
- in service of #6739 
Adds some debug messages to provide clarity to the observed failure
> 06739 Add helpful debug messages for JRS failure

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SingleNodeSyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
> Properly clear pipelines before a reconnect.

- platform-sdk/swirlds-cli/misc/generate-new-node-config.py
> Added script for merging config.txt and currentAddressBook.txt.

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteHandlerTest.java
fix the compilation error on develop branch that was caused by the method change.
> file service fix the configuration method

- .github/workflows/config/node-release.yaml
> delay release 0.39 branch creation to next Tuesday

- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
Fix summary:
* When data source snapshot is made, both the source data source (in the current merkle tree) and the target one (in the snapshot) are left as "primary" in MerkleDb terms
* On copy (used during reconnects), still only one of the source and target data sources is marked as primary, while the other is secondary
Testing:
* A new unit test is provided
* Virtual map benchmarks
Fixes: https://github.com/hashgraph/hedera-services/issues/6806
> 6806: MerkleDb compactions are stopped after a snapshot

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
> Add extra information to state dump log.

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
> 06816 - bug fix in AddressBookTestingToolState

- .github/workflows/config/node-release.yaml
> disable initial tag for release 0.39

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
This is a cherry-pick of PR #6815
Fixes #6807 
**Checklist**
> 06790 Remove usages of `VirtualMap.fullLeafRehash` (#6815)

- settings.gradle.kts
Update to use jar with new protobufs
> Update new protobufs jar

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateToDiskAttempt.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/TestStateToDiskAttemptConsumer.java
> save state after reconnect

- settings.gradle.kts
Changed HAPI version to add block and running hash state
> Changed HAPI version to add block and running hash state

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
- platform-sdk/buildSrc/build.gradle.kts
- platform-sdk/buildSrc/src/main/kotlin/com.swirlds.platform.spotless-conventions.gradle.kts
- platform-sdk/buildSrc/src/main/kotlin/com.swirlds.platform.spotless-java-conventions.gradle.kts
- platform-sdk/buildSrc/src/main/kotlin/com.swirlds.platform.spotless-kotlin-conventions.gradle.kts
This pull request updates the spotless version for both Platform SDK and Services Node Gradle builds. Also, this PR makes a few minor tweaks to the `kotlinGradle` formatting.
- Closes #6930
> chore: update spotless version and convention plugins

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKVState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryReadableKVState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryWritableKVState.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/AdapterUtils.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoHandlerTestBase.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTokenHandlerTestBase.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
> Use AccountID instead of EntityNumVirtualKey

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableFileStoreImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/base/FileQueryBase.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableFileStoreImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableFileStoreImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileHandlerTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteHandlerTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateHandlerTest.java
> Use FileID instead of EntityNum as the key into the FILES map

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigratorTest.java
Fix summary: backport of the fix for #6887 to 0.39.
Fixes: https://github.com/hashgraph/hedera-services/issues/6939
> 6939: Backport #6887 to 0.39

- settings.gradle.kts
**Description**: Integrate platform build 0.39.0-alpha.5 to release/0.39 branch
Fixes #6976
**Checklist**
> Integrate platform build 0.39.0-alpha.5 to release/0.39 branch

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
Change CLASS_ID for HederaSoftwareVersion which is same as `SemanticVersions` CLASS_ID
> Change CLASS_ID for HederaSoftwareVersion

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporter.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
Fixes #7015 
Based on Tom's tests in perf network, when we are using old signed state to load into the network, a wrong export period is stored in services and `SignedStateBalancesExporter` export balance files multiple times than in every 900 seconds.
Fixes this scenario, by resetting nextExportTime to nextPeriod boundary if the current time is more than one exportPeriod far away from the stored `nextExportTime`
> Fix `nextExportTime` if time exceeded one exportPeriod

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporter.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
> Cherry Pick - Fix `nextExportTime` if time exceeded one exportPeriod (#7016)

- hedera-node/hedera-network-admin-service-impl/build.gradle.kts
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkGetAccountDetailsHandlerTest.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
implementation of Transaction Get Receipt and some refactoring of Get account details
Include unit tests
Fixes #6188
> Implementation of Transaction Get Receipt and some refactor of Get account details

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EvmTokenUtil.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/EvmTokenUtilTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
> Make no-min fractional fees viewable via precompiles

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/CriticalQuorumImpl.java
> Fix null pointer exception in critical quorum

- buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- settings.gradle.kts
Add JUL bridge to the class path and enable it early in the startup of the system.
> Add JUL bridge for log4j

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetRecordHandlerTest.java
implement get Record query and also remove the payment part from the receipt because it is free. In addition, removed the check of the cost in Get account details because it is coming from the abstract class
Fixes #6760
> implement get Record query

- .github/CODEOWNERS
> Update CODEOWNERS for `hedera-app`

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
Closes #7034 
Let responses have a max size of 100 KiB, and add a special log statement in case method dispatch fails (I had this happen during testing, and wondered what went wrong, the log statement was very useful).
> Allow max response size of 100KiB

- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolConfig.java
- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolState.java
> Make consistency testing tool play nicely with local testing.

- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
This PR relates to #7046 and temporarily disables the tests that are making the build hang.
> 07046 Temporarily disabled tests to unblock other team and buy some time for the investigation

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/DummyHashgraph.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
> 07061 sync test flake

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/RecycleBinConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBin.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBinImpl.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/TestRecycleBin.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFile.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/RecycleBinTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
> Use RecycleBin to handle files after discontinuity in PCES.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/GrpcServerManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManagerTest.java
* Added unit test for the Helidon GRPC Manager
> Finish small refinements for Helidon version of GRPC (#6984)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/AutoClosableLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/AutoClosableResourceLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/IndexLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/Locks.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AcquiredOnTry.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AcquiredResource.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AutoLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AutoNoOpLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/DefaultIndexLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/NotAcquiredResource.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/ResourceLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/package-info.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/locked/LockedResource.java
- Null annotations added
- Implementations defined as final classes
- package documentation
> update of Lock api

- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/preprod/bootstrap.properties
- hedera-node/configuration/previewnet/bootstrap.properties
- hedera-node/configuration/testnet/bootstrap.properties
Fixes: https://github.com/hashgraph/hedera-services/issues/7108
> 7108: Enable MerkleDb in previewnet, testnet, and mainnet in 0.39

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskCreatorTest.java
> Fix test flake in random event test.

- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/StoppableThreadTests.java
> More stable maxRateTest()

- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolRound.java
> Fix bug where round has no transactions.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/internal/SettingsCommon.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/RunningAverageMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/SpeedometerMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/config/MetricsConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetricsProvider.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultStatEntry.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/prometheus/PrometheusConfig.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/RunningAverageMetricConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/SpeedometerMetricConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultMetricsTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultStatEntryTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/LegacyCsvWriterTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/prometheus/PrometheusConfigTest.java
- platform-sdk/swirlds-common/src/test/resources/metrics-test.properties
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/MetricsDocUtilsTest.java
> #6451 Introduce MetricsConfig

- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/OSTime.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/Time.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/internal/OSTime.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/SnapshotService.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsRunningAverage.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsSpeedometer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/internal/StatsBuffer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/config/QueueThreadMetricsConfiguration.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateSentinel.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/NoOpIntakeCycleStats.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/chatter/SimulatedChatterFactories.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterCoreTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskDispatcherTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/ConsensusHashManagerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssHandlerTests.java
OSTime is internal api now and Time interface is used as facade
> Time interface is facade for OSTime

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskAccount.java
Fixes: https://github.com/hashgraph/hedera-services/issues/7087
> 7087: ISS in account store after migration to disk

- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/platform-flow-pull-request-checks.yaml
- .github/workflows/platform-pull-request-extended-checks.yaml
Removes the label based job gating to resolve the issue with pull request job run associations.
- Closes #7160
> feat: update ci workflows to remove job gating based on labels

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/account/AccountVirtualMapKeySerializerMerkleDb.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/account/AccountVirtualMapValueSerializerMerkleDb.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/state/VirtualMerkleStateInitializer.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/virtualmerkle/transaction/handler/VirtualMerkleJPDBTransactionHandlerTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
Fixes: https://github.com/hashgraph/hedera-services/issues/6834
> 6834: Platform JRS apps should run with both JasperDB and MerkleDb data sources

- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
- Fixed NPE which caused infinite wait on a future object. 
- Added cancellation of a future in case of an error.  
- Re-enabled the tests that were previously disabled
Fixes #7046 
**Checklist**
> 7046 Fixed NPE which caused infinite wait on a future object. 

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/internal/SettingsCommon.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/BasicConfigTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingsProvider.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StartUpEventFrozenManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StaticSettingsProvider.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTab2Stats.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/unidirectional/HeartbeatSender.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/TestSettings.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/TestSettings.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
> #06452 Migrate Settings to BasicConfig

- settings.gradle.kts
change back to the common protobuf branch "add-pbj-types-for-state" // hapiProtoVersion
> change the protobuf version back to common branch

- .github/workflows/node-zxc-compile-application-code.yaml
- .snyk
- build-logic/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
- build-logic/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
- build-logic/src/main/kotlin/com.hedera.hashgraph.platform.gradle.kts
- build-logic/src/main/kotlin/com/hedera/hashgraph/gradlebuild/rules/IoGrpcDependencyMetadataRule.kt
- hedera-node/hedera-consensus-service-impl/src/main/java/module-info.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
- hedera-platform/build.gradle.kts
This pull request closes the outstanding snyk reports via version updates. The snyk check should now be passing after this PR has been merged.
- Closes #6713
> chore: address snyk scan and code detections

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/PlatformConfigUtils.java
> #7079 Add logging for applied ConfigMappings

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncCaller.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
> #6455 Introduce SyncConfig

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/PlatformConfigUtils.java
> #7247 Log warnings only for actually applied mappings

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/BasicConfigTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ThreadConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoSetup.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/EventCreatorThread.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/PreConsensusEventHandlerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimulatedEventCreationNode.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
> #6456 Introduce ThreadConfig

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java
> #7296 Correct Mapping for ThreadConfig properties

- platform-sdk/swirlds-cli/color-logs.py
- platform-sdk/swirlds-cli/squelch-spam.py
> Don't log keyboard interrupts in python scripts.

- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/utils/ValidationUtils.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/utils/ValidationUtilsTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Token.java
Created variants of `ValidationUtils.validateTrue()/validateFalse()` with deferred parameter evaluation.
> 6347: Evaluating parameter for ValidationUtils.validateTrue() is expensive

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreationRulesTests.java
> Fix flaky rate limiter test.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/TokenStateTranslator.java
- settings.gradle.kts
updated protobuf branch and fixed merge issues.
Fixes #
**Checklist**
> updated protobuf branch and fixed merge issues.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/NftStateTranslator.java
- hedera-node/hedera-mono-service/src/main/java/module-info.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleUniqueTokenSerdeTest.java
bi-directional nft translator
Fixes #7304
> nft bi directional translator

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StakingNodeInfoStateTranslator.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoSerdeTest.java
Implement bi-directional staking info translator
Fixes #7305
> merkle staking info bi directional impl

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
> fix PTT ISS

- hedera-node/docs/design/services/smart-contract-service/accounts-blocklisting.md
Add accounts blocklisting design doc.
Fixes https://github.com/hashgraph/hedera-services/issues/6051
**Checklist**
> Add accounts blocklisting design doc

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/TokeRelationStateTranslator.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleTokenRelStatusSerdeTest.java
Implement bi-directional token relation translator
Fixes #7306
> add token relation translator

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
Related to #7443 
Needs to be cherry picked into develop.
> 07443 40 uptime bug

- README.md
> formatting in README.md fixed

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
> Make PTT state copy deterministic.

- settings.gradle.kts
updated hapiProtoBranchOrTag back to add-pbj-types-for-state
Fixes #
**Checklist**
> updated hapiProtoBranchOrTag back to add-pbj-types-for-state

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/GenesisStateBuilder.java
> Copy state in between hashing and init()

- settings.gradle.kts
> Integrate the 0.39.1 Platform SDK with Services

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTests.java
> fix for flaky test

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/GenesisStateBuilder.java
> 07487 d copy after hash

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
> Fix PTT issue.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/MerkleIterationOrder.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/MerkleIterator.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/BreadthFirstAlgorithm.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/MerkleIterationAlgorithm.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/PostOrderedDepthFirstAlgorithm.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/PostOrderedDepthFirstRandomAlgorithm.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/ReversePostOrderedDepthFirstAlgorithm.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleIterationTests.java
> Add a reverse BFS merkle iteratation order.

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java
> Fix bug in MTT copy.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/EventCreationConfig.java
Closes #7388 
This is not to be merged until after we run a few test panels against it.
> Enable tipset event creation.

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteTest.java
I fix the logic to support system delete and undelete for regular files and not for special files
Fixes #7526
> fix file delete and undelete to work properly

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
> Fix bug in PTT copy constructor.

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AssessmentResult.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFixedFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/CustomFeeAssessmentStepTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
Fixes #7284 
Addressed review comments from PR https://github.com/hashgraph/hedera-services/pull/7434 and added unit tests
> Address review comments from PR #7434

- hedera-node/configuration/compose/log4j2.xml
- hedera-node/configuration/dev/log4j2.xml
- hedera-node/configuration/mainnet/log4j2.xml
- hedera-node/configuration/preprod/log4j2.xml
- hedera-node/configuration/previewnet/log4j2.xml
- hedera-node/configuration/testnet/log4j2.xml
Cherry pick of fix for Log4J file rotation.
Resolves issue https://github.com/swirlds/infrastructure/issues/4393
> Infrastructure Issue #4393 excessive log retention

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
> Fix CountPerSecond unit

- platform-sdk/sdk/settings.txt
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
> Set saveReconnectStateToDisk to true by default

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/ChildlessEventTracker.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetWeightCalculator.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorImplTests.java
> 07589 tipset debug log

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/MerkleAccountScopedCheck.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/MerkleAccountScopedCheckTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
- As in the included EET, current status when a missing NFT is transferred with `is_approval = true` is `FAIL_INVALID`.
- Fixes this to be `INVALID_NFT_ID`.
> Resolve to `INVALID_NFT_ID` when missing NFT transferred with approval

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/MerkleAccountScopedCheck.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/MerkleAccountScopedCheckTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
> Cherry-Pick : Resolve to `INVALID_NFT_ID` when missing NFT transferred with approval

- platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/RandomAddressBookGenerator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabAddresses.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/OutboundConnectionCreator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/SocketFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/TcpFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/TlsFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookNetworkUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/CryptoArgsProvider.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
> 06860 dns endpoints

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SingleNodeSyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
> Fix sync metric bug

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/EventConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/EventStreamManager.java
> Increase capacity of consensus event stream queues.
