hiero-ledger/hiero-consensus-node

platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowWrapper.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/SwirldStateFlowTests.java

Remove the `TIME_CONSUMING` tag prevents important event flow tests from running and get them passing again.
Fixes #7230 
None
**Checklist**

Fix Event Flow Unit Tests

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/AllowanceValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableNftStoreTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGetNftInfoHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/AllowanceValidatorTest.java
settings.gradle.kts

Use IDs instead of longs in NFT
Fixes #7244 
Related to [PR #289](https://github.com/hashgraph/hedera-protobufs/pull/289) in hedera-protobufs repo 
This PR relies on a temporary branch `change-numbers-to-ids-nft-proto ` in hedera-protobufs repo. The plan is to:
1) Merge this PR
2) Merge [PR #289](https://github.com/hashgraph/hedera-protobufs/pull/289) in hedera-protobufs repo, but DO NOT DELETE THE ASSOCIATED BRANCH YET. Until Step 3 is completed, hedera-services still relies on the branch
3) Create and merge another PR in hedera-services to reset the protobufs branch in use back to add-pbj-types-for-state
4) Delete the hedera-protobufs branch associated with step 2

Change nft owner and spender identifier from long to AccountID

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java

- Closes #6300 
I manually tested the command with these changes, and confirmed that the behavior matches that of `develop`

Move context instantiation out of EventRecoveryWorkflow

---

settings.gradle.kts

Reset protobuf branch in use by services back to `add-pbj-types-for-state`. This is a follow-up to PR #7288, which temporarily changed it to a different branch.
Fixes #7244

Reset protobuf branch back to add-pbj-types-for-state

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt

Closes #7336 
This PR does the following:
- replace several legacy settings with the new fully qualified setting name
- remove settings matching current defaults
- sync.syncAsProtocolEnabled (default true)
- chatter.useChatter (default false)
- make sure settings are in alphabetical order with the new prefixes

Use fully qualified settings names.

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/adapters/VirtualMapLikeAdapter.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/adapters/VirtualMapLike.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporter.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/AccountStorageAdapter.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/AccountStorageAdapterTest.java

Improves performance of `SignedStateBalancesExporter` for token balances when `accounts.storeOnDisk` is enabled by avoiding serialization in `VirtualMapMigration.extractVirtualMapData()`.
Fixes #6659
Relies on #7197
Requires #7264 for testing
**Checklist**

6659: Exporting balances is not parallelized well when accountsOnDisk is enabled

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeMetrics.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/uptime/UptimeTests.java

Fixes an ISS observed in testing. Related to #7369. Must be cherry picked to `develop` if merged after the 0.40 branch is cut.

Disable code that improperly finds judges.

---

platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

The `AddressBookInitializer` will no longer receive a null loaded state from disk, it receives an initial state that must be checked for genesis.  The logic has been updated.  The `AddressBookTestingToolState` and unit tests have been updated to reflect the changed logic. 
Fixes #7393

07393 - AddressBookInitializer Check For Genesis State

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacks.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacksTest.java

- Increases the max stake limit to `1.1 * 50B / (# of nodes)` instead of `50B / (# of nodes)`.

Scale max stake by a 1.1x factor

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/ChannelStubs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiApiClients.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/consensus/HapiGetTopicInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiMessageSubmit.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicDelete.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java

- Instead of sharing the gRPC stubs of a single `ManagedChannel` across all concurrent `HapiSpec`'s for each node URI, instead creates up to `MAX_DESIRED_CHANNELS_PER_NODE` channels per node URI and randomly chooses one for each running `HapiSpec`.

Try pooling channel stubs

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java

Cherry pick from [0.40 fix](https://github.com/hashgraph/hedera-services/pull/7444)
Closes #7443

07443 d uptime bug

---

settings.gradle.kts

Updates _settings.gradle.kts_ with stable proto assets.
**Note to reviewers:** The `itest` [failure](https://scans.gradle.com/s/pdgucgmm2klzg/tests/task/:test-clients:itest/details/AllIntegrationTests/concurrentSpecs()%5B1%5D?top-execution=1) is a clearly flaky test that just happened to surface on this PR. Diagnosed and created [this issue](https://github.com/hashgraph/hedera-services/issues/6486) to fix it.

Use `0.40.0` + `v0.40.0` proto assets

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java

Accommodate sig map size variance in `canAutoCreateWithNftTransfersToAlias()`

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java

Fix summary:
* `hashed` field is removed from `VirtualRootNode`
* Inherited `hash` field isn't used in `VirtualRootNode` to store its hash
* A new `hash` field, of AtomicReference type, is introduced to `VirtualRootNode`. This field is used to store the hash, as well as to check if the root node is hashed or not
Fixes: https://github.com/hashgraph/hedera-services/issues/7416

7416: Virtual map is unhashed after a reconnect

---

.github/workflows/platform-zxcron-release-jrs-regression.yaml

No longer need to run nightly regression for release/0.38 and release/0.39

Change the mini version of running cron jobs of nightly regression

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml

* Fixed the glob on log4j2.xml rollover strategy delete condition
* The glob only looked in subfolders, rather than the current folder. * Modified to look in current folder, and up to 2 folders below that.
* Adjusted the max index proerpty to 10 (from 20).
* The current environments never exceed 3, so 10 is ample.
* Retention duration was not modified.

Infrastructure Issue #4393 excessive log retention

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SummarizeSignedStateFileCommand.java
hedera-node/cli-clients/src/main/java/module-info.java

* Update `SignedStateHolder` to use `ReservedSignedState` correctly (so you use it under try-with-resources)
* Update `SummarizeSignedStateFileCommand` to be a subcommand of a new `SignedStateCommand` in preparation for adding state dump commands
Part of issue #7620
**Reviewers**:
You'll have to provide your own signed state file but the command line you need looks like this:
```
./platform-sdk/swirlds-cli/pcli.sh \
--load hedera-node/cli-clients/build/libs \
--load hedera-node/data/lib/app-spi-0.40.0-SNAPSHOT.jar \
--load hedera-node/data/lib/besu-datatypes-23.1.2.jar \
--load hedera-node/data/lib/evm-23.1.2.jar \
--load hedera-node/data/lib/guava-31.1-jre-module.jar \
--load hedera-node/data/lib/plugin-api-23.1.2.jar \
--load …
```

Update `SignedStateHolder` to use `ReservedSignedState` correctly

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SingleNodeSyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/InboundConnectionHandler.java

Fixes #7659 
Rate limiting just this logged exception.  The `Time` object has to be threaded through constructors that are rate limiting.  It feels out of scope to do that in more than this location.  I am just addressing the particular excessive log message that created this issue.  
I fixed the order of arguments to the exceptions and modified the `otherId` being null in the message to say `unknown`.  The cause of the exception being reported is preventing the determination of the otherId.

07659-Rate-Limit-SocketException

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java

Fixes #6988
Manual Verification Procedures
1. Compile and run locally
2. turn off PCES recording. 
3. run app to generate new states from genesis, then stop app.
4. Turn off state saving. 
5. delete all the saved states for 1 node. 
6. modify the config.txt address book.
7. start the app.  The node with no saved state will start from genesis and use the config.txt address book while the nodes with saved state will use the loaded saved state.  
8. Verify that the reconnecting node fails to connect with all other nodes that started with saved states.

06988 - Reconnect Verify Platform and Learned State AddressBook Match

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/MiscUtils.java

`Token.fromGrpcOpAndMeta()` calls `MiscUtils.asUsableFcKey()` on a variety of keys that may be specified for a token. If a particular key is not specified, an exception is thrown by `JKey.mapKey(key)` and caught by `asUsableFcKey()`, which in that case returns `Optional.empty().` This is very expensive: a token creation benchmark shows 20% time wasted by the transaction handling thread on handling those exceptions.
A simple check if a key is set is appropriate here.

7728: MiscUtils.asUsableFcKey() creates many exceptions

---

hedera-node/cli-clients/build.gradle.kts
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractBytecodesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractStoresSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/README.md
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SummarizeSignedStateFileCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/ByteArrayAsKey.java
hedera-node/cli-clients/src/main/java/module-info.java

Adds PCLI plugin commands to dump contract bytecodes and state from a signed state file.
Can be extended for the rest of the services semantic data stored in the virtual merkle trees (accounts, tokens, topics, etc.)
Manages the signed state file uniformly for those subcommands.
Fixes #7715 
If you would like a "top down" approach to review:
- `SignedStateCommand` is the simple parent of `SummarizeSignedStateFileCommand` and `DumpStateCommand` - that's the PCLI part with command line options pretty straightforward from `picocli`
- `SignedStateHolder` simply changed to return contracts in a known order (moving from `Set` to `TreeSet`)
- Then the two contract state dumpers are contained in `DumpContractBytecodesSubcommand` and …

Restructured signed-state command and added dump (bytecode,store) commands

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractBytecodesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/README.md
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java

Cleanup from PR #7729, leftover reviewer comments.
Biggest single change is removing broken logging overrides.  Another useful change is fixing up the sorting of contract ids so it is really centralized in one place and applied throughout without having to take care of it.
Fixes #7715
**Checklist**

Differential testing analytical engine: Cleanup 7715 fix with additional reviewer comments handled

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelper.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelperTest.java

Fixes https://github.com/hashgraph/hedera-services/issues/7758
- Fixed `curStakePeriod` that was not set during `upgrade` housekeeping
Testing:
Loaded mainnet state from `145234353` and validated fix will not have same error

Fix `curStakePeriod` while doing upgrade house keeping

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelper.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelperTest.java

Cherry-pick https://github.com/hashgraph/hedera-services/pull/7755
Fixed curStakePeriod that was not set during upgrade housekeeping
Testing:
Loaded mainnet state from 145234353 and validated fix will not have same error

Cherry-pick to 0.41: Fix `curStakePeriod` while upgrade

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelper.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelperTest.java

Cherry-pick https://github.com/hashgraph/hedera-services/pull/7755
Fixed curStakePeriod that was not set during upgrade housekeeping
Testing:
Loaded mainnet state from 145234353 and validated fix will not have same error

Cherry-pick to develop: Fix `curStakePeriod` while upgrade

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelper.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakeStartupHelperTest.java

Cherry-pick https://github.com/hashgraph/hedera-services/pull/7755
Fixed curStakePeriod that was not set during upgrade housekeeping
Testing:
Loaded mainnet state from 145234353 and validated fix will not have same error

Cherry-pick to 0.39 : Fix `curStakePeriod` while upgrade

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java

07577 - Fix Uncaught Exception In Platform Core Unit Tests

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacks.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacksTest.java
hedera-node/settings.txt
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue305Spec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java

- Closes #7768 
- _Note to reviewer:_ To validate fix locally, run `congestionMultipliersRefreshOnPropertyUpdate()` with and without [the `resetExpectations()` call](https://github.com/hashgraph/hedera-services/pull/7780/files#diff-5ec9034b5d1b8575aeab53a936027845b22856b5b4a11d27362de77694a9e834R119); observe multipliers do not take effect without it.

Refresh congestion multipliers in config callback

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java

Adding support for running a test package
This feature will be helpful when we start migrating the tests to HapiTestEngine and I imagine we will do that package by package. The ability to run only your package instead of running all tests or test-by-test should save us some time.
Thanks, @netopyr for finding about `discoveryRequest.getFiltersByType(PackageNameFilter.class)` 🏆 
**Checklist**

Add support for test package runs for HapiTestEngine

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpAccountsSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractBytecodesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractStoresSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/ThingsToStrings.java
hedera-node/hedera-mono-service/src/main/java/module-info.java

Add dump (to text) of account store.
Fixes #7738
**Notes for reviewer**: 
(At this exact moment javadoc is mostly missing.  Will be added shortly.)
Somewhat tedious to review, I'm afraid, though it does have its interesting moments to be sure.  Tried to make it as "data driven" as possible to reduce duplication; I'd be interested to know if you thought that it improves or hinders readability.
Lots of fiddly formatting of strings.  And some complexity due to the desire to emit alternatively CSV vs a "compressed field" representation".
_release engineering reviewer_: Changed a `module-info.java` to expose more stuff from the mono-service to the services' `cli-client` module.
**Checklist**
Signed-off-by: David Bakin …

Differential testing analytical engine: Dump accounts, as text, from state file

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java

It fixes the issue that the verification.get(key) can be null when we fetch the key from the hashMap and some of the threshold keys are missing.

small fix to HandleWorkflow verification

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransactionalLedger.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingAccounts.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingNfts.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingStore.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokenRels.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokens.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/pure/PureBackingAccounts.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/SystemAccountsCreator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/TreasuryCloner.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransactionalLedgerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/BackingTokensTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingAccountsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokenRelsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingAccounts.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingNfts.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingTokenRels.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingTokens.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapTestAccounts.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/pure/PureBackingAccountsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreatorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/TreasuryClonerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStoreTest.java

- Closes #7971 
- Closes #7925 
- Adds method `SystemAccountsCreator.ensureSynthRecordsPresentOnFirstEverTransaction()`, called at the beginning of the first-ever handled transaction to ensure we externalize the same synthetic `CryptoCreate` records whether we are starting from genesis or replaying from round 1.
- Removes `idSet()` method.

Fix round 1 replay

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/FeeCalculator.java
hedera-node/hedera-app-spi/src/main/java/module-info.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/fees/FakeFeeCalculator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceImpl.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageTest.java
hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicTest.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/ChunkingSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/SubmitMessageSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicGetInfoSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
hedera-node/test-clients/src/main/resource/log4j2.xml

Closes #7932. Add support for computing fees the "legacy" way with the fee calculator. It is ugly, but it works. Add this to each of the handlers in the consensus service, and enable their associated tests.

Implement consensus fees calcuations

---

settings.gradle.kts

PR https://github.com/hashgraph/hedera-services/pull/7986 temporarily changed the hapi proto branch in use. Now that https://github.com/hashgraph/hedera-protobufs/pull/298 has been merged, it's time to revert the hapi proto branch to what it was before.
Fixes #8037

Revert hapi-proto-branch

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/NettyGrpcServerManager.java

fix the issue sonar fix from PR 7839
that causing e2e tests to fail with that error
```
java.lang.UnsatisfiedLinkError: failed to load the required native library
at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:56)
at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:186)
at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:37)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
at …
```

fix NettyGRPC non linux

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCommon.java

This PR fixes validation that didn't take into account the fact that the index could've changed, and the snapshot of validKeyRange it uses may no longer correspond to the index state. So, if the value it checks is not not the index, the value is simply ignored.
Fixes #8034

08034 Fixed index validation after compaction

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/SystemFilesManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManagerTest.java

Fixes https://github.com/hashgraph/hedera-services/issues/8106
The `stake` field on file 102 is deprecated and need not be updated on restart. 
This update will fix a possible ISS while doing replay of events, if the following steps occur
1. Start a network with an upgrade
2. Platform calls `ServicesState.updateWeight` which updates file 101 stake field, but file 102 is not modified. So file 102 has old stakes.
3. Then on restart in `ServicesState.init()` we update file 102 with new weights from file 101 in state. 
4. But during replay, this will cause ISS because the contents of file 102 are being modified in `ServicesState.init()`

Remove deprecated Stake update field on restart

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/SystemFilesManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManagerTest.java

Fixes #8106 
Cherry-pick https://github.com/hashgraph/hedera-services/pull/8095
The stake field on file 102 is deprecated and need not be updated on restart.

Cherry-pick : Remove deprecated Stake update field on restart

---

hedera-node/docs/design/services/smart-contract-service/contract-accounts-nonces.md

Describe and update on how  contract nonces are stored in state and how contract nonce externalization works.
Fixes https://github.com/hashgraph/hedera-services/issues/7126
**Checklist**

Updated contract nonces design doc

---

.github/workflows/platform-zxc-release-maven-central.yaml
.gitignore

This pull request ensures certain files generated during a CI pipeline execution are never committed. 
- Closes #8114

fix: ensure the ephemeral files created during a release workflow are not committed

---

platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java

I still can't reproduce the exception from the bug description. So this PR is to improve exception reporting in the test, so if it fails next time, a good stack trace is available for further investigation.
Fixes: https://github.com/hashgraph/hedera-services/issues/6475

6475: com.swirlds.merkledb.files.DataFileCollectionTest test flake

---

.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxc-build-release-artifact.yaml

This PR modifies the `Node: Deploy Release Artifact` workflow in order to support the easy creation of Docker images from feature branches, it also enables the automatic building of Docker images on merge to `develop` branch.
* Modify workflow
Fixes #7882 
An example of a successful run is [here](https://github.com/hashgraph/hedera-services/actions/runs/5789731760)
**Checklist**

Adhoc Docker images from branches

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacility.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacilityTest.java

Calling the ExchangeRateManager.update method from SystemFileUpdateFacility
Additional: fixing two comments from https://github.com/hashgraph/hedera-services/pull/8072:
- https://github.com/hashgraph/hedera-services/pull/8072#discussion_r1301615877
- https://github.com/hashgraph/hedera-services/pull/8072#discussion_r1301621458
**Note:** The sonar coverage is so low because of the changes in Hedera.java class. Currently, there are no tests written for that and it will be very time-consuming if I start writing them from the beginning(I'm guessing we have future stories for that). I've marked what needs to be tested in HederaTest
Fixes https://github.com/hashgraph/hedera-services/issues/8120
**Checklist**

Call ExchangeRateManager.update in SystemFileUpdateFacility

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpAccountsSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractBytecodesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractStoresSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpFilesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/ThingsToStrings.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/Writer.java
hedera-node/hedera-mono-service/src/main/java/module-info.java

Dumps all _data_ files from a signed state file.  Includes their content and their full key.  Also has a histogram of file sizes, and a list of all the different key structures.
Given a signed state file from 2023-07-19 it found ~20000 _data_ files and produced a report of ~110MB.
Fixes #8143 
Sample command line (you'll have to provide your own signed state file:
```bash
./platform-sdk/swirlds-cli/pcli.sh \
--memory 40 \
--ignore-jars \
--load hedera-node/data/lib \
--load hedera-node/cli-clients/build/libs \
--cli com.hedera.services.cli.signedstate \
signed-state  -f /Users/davidbakin/StatesStreams/mainnet-2023-07-19/state/2023-07-19.00.00/144535932/SignedState.swh --verbose \
dump \
files --files ./files.lst --deep-keys …
```

Dump files from signed state file

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/MonoThrottleAccumulator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleManager.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/MonoThrottleAccumulatorTest.java

We have the modularization FE throttling implementation in place. Currently, it's deligating to the mono implementation(I'm guessing this will change in the future). The only thing that's left, as far as I can see, is to make it use the throttle definition file configuration implemented here https://github.com/hashgraph/hedera-services/pull/8072.
We do have throttle suite tests but they are failing. As far as I can see they are failing due to not related errors(I'm guessing errors related to the modularization efforts).
Fixes https://github.com/hashgraph/hedera-services/issues/7961
- In `ThrottleManager` we are exposing the proto object
- In `MonoThrottleAccumulator` we are getting the throttle definitions from the …

Implement frontend throttle

---

platform-sdk/settings.gradle.kts
platform-sdk/swirlds-jasperdb/build.gradle.kts
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/build.gradle.kts
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/module-info.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java

This PR changs the way `ClosedByInterruptException` handled in `DataFileCollection`. It's no longer resulted in a message of `ERROR` level.
To capture log entries for further verification I added `MockAppender` to `swirlds-common-test` module. 
Fixes #8103 
**Checklist**

08103 Changed the way ClosedByInterruptException handled in DataFileCollection

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/CreateFailuresSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/DeleteFailuresSpec.java

E2E passing for DeleteFailuresSpec and CreateFailuresSpec
Fixes #8047 #8048

E2E passing for DeleteFailuresSpec and CreateFailuresSpec

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCommon.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileWriterTest.java

This PR fixes possible reconnect failure which may happen due to unfortunate timing of a compaction pause. 
Also, it simplifies `DataFileWriter` by removing lock file because it's not necessary. `Files.createFile(path);` provides guarantees of atomic disk operation. 
Also, this PR reproduces the failure scenario in `DataFileWriterTest`.
Fixes #8105 
**Checklist**

08105 Make DataFileWriter gracefully handle interrupts.

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/codec/FileServiceStateTranslator.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/ReadableFileStore.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/EthereumCallDataHydration.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmTransactionFactoryTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/nfra/EthereumCallDataHydrationTest.java

fix return null instead of optional when call getFileLeaf
Fixes #8198

fix return File instead of optional when call getFileLeaf

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/UpdateFailuresSpec.java

Two recent changes in platform and file service broke some of the tests. 
- Fixed initialization of `SwirldsPlatform`
- Disabled expiry-verification that broke some of the tests
- Disabled tests that are failing

Fix e2e tests

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java
hedera-node/test-clients/src/eet/java/EndToEndTests.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileDeleteSuite.java

implement one key from key list is needed in order to delete file using the threshold key, and  make the delete-suite working properly
Fixes #8054

implement one key from keylist is needed in order to delete file, and delete E2E tests

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpAccountsSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpFilesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java

Added key structure summary reports to account and file signed state dumpers
Displays a histogram showing for each key structure how many {files, accounts} have that structure.
Example output is something like:
```
=== EOA Key Summary ===
811711: Key[EC]
2155557: Key[ED]
2511: Key[KL[#1,ED]]
1: Key[KL[#1,TH[1-of-1,ED]]]
41: Key[KL[#1,TH[1-of-2,ED,ED]]]
1: Key[KL[#1,TH[1-of-3,ED,ED,ED]]]
2: Key[KL[#1,TH[2-of-2,TH[1-of-2,ED,ED],TH[2-of-4,ED,ED,ED,ED]]]]
1499: Key[KL[#1,TH[2-of-2,TH[1-of-7,ED,ED,ED,ED,ED,ED,ED],TH[3-of-7,ED,ED,ED,ED,ED,ED,ED]]]]
1: Key[KL[#1,TH[2-of-3,ED,ED,ED]]]
215: Key[KL[#1,TH[2-of-4,ED,ED,ED,ED]]]
490: Key[KL[#1,TH[3-of-5,ED,ED,ED,ED,ED]]]
```
Fixes #8227 
Use `--keys=STRUCTURE` with both file+account …

Added key structure summary reports to account and file signed state dumpers

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/NodeInfo.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/MigrationContext.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/info/FakeNetworkInfo.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/BootstrapConfigProviderImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderBase.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/NodeInfoImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/SelfNodeInfoImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MigrationContextImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheImplTest.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/LedgerConfig.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/GenesisSchema.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/FreezeServiceImplTest.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/GenesisSchemaTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java

Closes #8267
- Enhance MigrationContext to expose NetworkInfo, so the file service can build files 101 and 102. This involves extending the API on NodeInfo with missing items
- Fix bootstrap configuration in `Hedera`, and create a `NetworkInfo` for migration. Migration needs this, but the dagger app cannot be initialized until after the migration has happened. Also needed to add LedgerConfig to bootstrap
- Add to shutdown the ability to shutdown virtual map databases. Kind of a hack, need a better way to do shutdown from the platform.
- Fix the JUnit HAPI Engine so it starts a single server at the start of all tests and shuts them down at the end

Load the address book info at genesis into files 101 and 102

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/HorizontalAlignment.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/StringFormattingUtils.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/TextTable.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/formatting/HorizontalAlignmentTests.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/CommonUtilsTest.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCommon.java

Closes #8276 
Example tree visualization, copy-pasted verbatim from log:
```
(root) State               /       word-clever-raccoon-pilot
0 HashgraphDemoState    /0      wage-lecture-wisdom-lunar
1 PlatformState         /1      mask-hurry-wolf-novel
0 PlatformData       /1/0    either-trend-enforce-track
1 AddressBook        /1/1    observe-speak-regular-race
2 DualStateImpl         /2      voyage-around-puppy-modify
```

Remove trailing whitespace from merkle tree visualization.

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FetchSystemFiles.java

enable test to work with modularize code FetchSystemFiles
Fixes #8053

enable test to work with modularize code FetchSystemFiles

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpTokensSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpUniqueTokensSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/ThingsToStrings.java

Dumps unique NFTs from a signed state file.
Fixes #8255 
You can use the following command line (except providing your own signed state file):
```bash
./platform-sdk/swirlds-cli/pcli.sh \
--memory 40 \
--ignore-jars \
--load hedera-node/data/lib \
--load hedera-node/cli-clients/build/libs \
--cli com.hedera.services.cli.signedstate \
signed-state  -f /Users/davidbakin/StatesStreams/mainnet-2023-07-19/state/2023-07-19.00.00/144535932/SignedState.swh --verbose \
dump \
uniques --unique ./unique.lst --summary
```
This produced a 262MB file from a mainnet state of 2023-07, >2M unique NFTs.
Start of the file looked like this:
```
=== 2155205 unique tokens (863628 owned by treasury accounts)
0 null owners, 2094718 null or missing …
```

Dump unique NFTs from a signed state file

---

.github/CODEOWNERS

- enable `hedera-base` to approve all of `hedera-node`
- fix approvals for `/hedera-node/configuration/**`

Update code ownership in services repo

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/GenesisSchema.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/schemas/GenesisSchemaTest.java

In `GenesisSchema` of the file service, creates the special files (by default, 150-159) for upgrade, all with empty bytes.
Closes #8316
**Checklist**

Create upgrade special files during genesis with empty file contents

---

hedera-node/hedera-app/src/main/java/module-info.java
hedera-node/test-clients/build.gradle.kts
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
hedera-node/test-clients/src/main/java/module-info.java
platform-sdk/swirlds-platform-core/src/main/java/module-info.java

- Removes the usage of `org.junit.platform.common.util` package from the `HapiTestEngine` class.
- Adds the `org.junit.platform.common.support` package in lieu of the `org.junit.platform.common.util` package.
- Removes changes made during #7875, which effectively rendered the `test-clients` as class path entry.
- Partially resolves #8350 
- Users must manually enable the `Do not use --module-path opton` on all `HapiTestEngine` based tests in the IntelliJ launcher as shown below.

fix: resolve HapiTestEngine issues preventing test execution

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts

Makes sure all `xtest` code is also compiled as part of the PR checks on CI.
Initially we planned this to be included in #7875, but left it out to not rely on this being working.

Compile 'xtest' code as part of 'assemble'

---

.github/workflows/platform-zxc-compile-platform-code.yaml

- Updates the `publish-unit-test-result-action` step to use a valid commit id for the version. 
- Closes #8358
- Related to #8353

fix: correct the version of the publish-unit-test-result-action to be a valid commit

---

.github/workflows/zxc-jrs-regression.yaml

- Updates the `ssh-key-action` step to use a valid commit id for the version. 
- Closes #8358
- Related to #8353

fix: correct the version of the ssh-key-action step to be a valid commit

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts

- Adds `requires("java.logging")` to the `io.grpc:grpc-stub` module specification in order to resolve the issue observed in #8390.
- Closes #8390

fix: ensure the grpc.stub module depends on java.logging

---

hedera-node/test-clients/build.gradle.kts

Fixes the issue that you currently can't start a `main()` method in `test-client` from IntelliJ.
The problem turned up when `test-client/src/main/module-info.java` was added in #7875. Gradle and IntelliJ now assumed things should run with `--module-path` (for which we are not completely ready yet).
Fixes #8350 - in a ways that test execution is done through Gradle and thus the workaround (#8351) is no longer needed.

Executions in 'test-client' (main() / tests) should not use --module-path

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java

Fix summary: MerkleDb now allows snapshots for non-primary tables. It's a valid case during reconnects.
Fixes: https://github.com/hashgraph/hedera-services/issues/8260

8260: CongestionPricing-NDReconnect-1-16m has error IllegalArgumentException

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java

A lambda with references to `initialState` is added to `components`. That prevents the state from ever be garbage collected.
Fixes #8380
Are `components` needed beyond `components.start()`? They could be cleared to avoid leaking temporary components in the future. 
**Checklist**
- [ x] Tested (unit, integration, etc.)

8380: a memory leak in `SwirldsPlatform.components`

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeInfoHelper.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java

Fixed code to pass CryptoUpdateSuite test.
Added stakednode = -1 and stakedaccount = null handling in rewards calculation 
Added unit test for payerAccount=deleted in PreHandleWorkflowImplTest
Fixes #8329 
**Checklist**

fixed code to pass CryptoUpdateSuite test

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/Schema.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/TestService.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/TestSchema.java
hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/NettyGrpcServerManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServicesRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServicesRegistryImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/ValueLeaf.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/ServicesRegistryImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleHederaStateTest.java

Enables "restart" of a node in the modular code. "restart" is when a node has been running, is stopped, and started again. This may happens a result of some administrative action (i.e. bouncing the host,) or due to upgrade, or in response to some error. This PR handles the first and third cases, it does not handle upgrades. The upgrade flow will be handled by 
#8335.
Closes #8245 
Fundamentally, genesis and restart are very similar to each other. In both cases, the `MerkleHederaState` needs to know which services exist and which merkle nodes they map to. The in-memory data structures (throttles, exchange rate, properties, etc) needs to be loaded based on the special files, or information on disk. In both cases the dagger app …

Add the modular restart support

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/pool/StandardWorkGroup.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/pool/StandardWorkGroupTest.java

Fix summary:
* Added a way to specify an exception listener for `StandardWorkGroup`
* The listener will be notified of all exceptions and will be able to tell if it can handle an exception, or default processing (to log it as an error) is needed
* `TeachingSyncronizer` will create an instance of `StandardWorkGroup` with a custom listener that ignores (logs as info) socket errors, but leaves everything else to be reported with EXCEPTION marker
Fixes: https://github.com/hashgraph/hedera-services/issues/8170

8170: MixedOps-Interrupted-2NReconnect-6k-41m failed with MerkleSynchronizationException

---

platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java

This PR fixes a flaky test (`com.swirlds.virtualmap.VirtualMapTests#testFlushCount`)
Fixes #8439

08439 Stabilized VirtualMapTests.testFlushCount

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionCheckerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionScenarioBuilder.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java

We should only check the node account ID, in the transaction, matches **this** node during transaction ingest. We should check during pre-handle that the node account ID matches the node that sent the event.
Fixes #8451
**Checklist**

Check transaction node account matches on ingest not on pre-handle

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/GenesisSchema.java

Restores behavior of to match mono, where file 121 is created but not populated at Genesis.
Fixes #8450 
**Checklist**

Do not preload file 121 with all network properties

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/NoOpFeeAccumulator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/NoOpFeeCalculator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
hedera-node/hedera-app/src/xtest/java/contract/ScaffoldingModule.java

Some child transactions are executed without a known `TransactionID`. Also, we create the `HandleContext` before validating the input. Therefore it has to work with an unknown `payerKey`.
This "solution" is pretty messy, but at least it fixes the failing tests. We should probably revisit the creation of `HandleContext` at some point.
Closes #8493

Enable HandleContextImpl to work with unknown payer

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java

port #8434 to 0.42
Fixes #8380

8380: a memory leak in `SwirldsPlatform.components` 

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java

Fix summary: direct backport of #8260 to release 0.42 Original PR is #8419.
Fixes: https://github.com/hashgraph/hedera-services/issues/8436

8436: Backport the fix for #8260 to release 0.42

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java

For nodes that were shared between the state address book and the config.txt address book, signature validation was using the public keys of the state address book.  Swapped the order to default to the public keys generated from the nodes in current address book (which may be the state address book if the initializer decided that was the AB to use). 
Fixes #8212

08212 - Fix Migrated State Event Validation

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

This PR repairs 8 more tests in the `TokenUpdateSpecs` by applying some fixes in the token update logic:
- Check whether nft owner is not null (it is in some cases) and if it is, then treasury can be counted as owner of this nft.
- When updating a token and no updates regarding expiry are made, there is no need to check and validate the expiry, autorenewAccount and autoRenewPeriod. Most of the time when autoRenewAccountId is not set during creation it results in null, which breaks this check and throws exception.
- When updating to a new treasury, this new treasury needs to have no balance and if it has, we have to return TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES . However it seems that this check has not been implemented.
Fixes #
**Notes for …

Token Update NPE fix

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
platform-sdk/swirlds-platform-core/src/test/resources/com/swirlds/platform/settings4.txt

All services tests are failing because property `state.checkSignedStateFromDisk` has been removed
from platform but still used in settings.txt

Remove no longer existing property 

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/VirtualMerkleLeafHasher.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java

This fix resets MerkleDb static state to prevent usage of incorrect metadata during the validation of the state files. 
Here is the explanation of why it's happening. `VirtualMerkleLeafHasher#main` loads rounds to validate. To do so it creates a virtual map which, in it's turn, creates a _default instance_ of MerkleDB (see `com.swirlds.virtualmap.VirtualMap#loadFromFile`) if it doesn't exist. To check if it exists or not, it checks if the path for a default instance is set or not. If the path is `null`, it creates a new instance. 
Also, `VirtualMap#loadFromFile` loads `virtualMapState` from the disk. This state, among other things, contains `firstLeafPath` and `lastLeafPath`. These parameters are defining a valid range of the keys we can use to get leaf values from the …

08237 Fixed validation of multiple rounds in VirtualMerkleLeafHasher

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/AwareNodeDiligenceScreen.java

- Makes a payer record queryable from node account _only_ in case of `INVALID_PAYER_SIGNATURE` for backward compatibility.

Fix JRS queryable payer record issue

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/ContractCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/DisassembleContractSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/DisassemblyOption.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/CodeRecognizer.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/CodeRecognizerManager.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/MethodAnalysis.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTSelectorLeafNodeEnd.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTSelectorLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTSelectorTableStart.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTSelectorTreeInternalNode.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTableEntryRecognizer.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/analysis/VTableEntryRecognizer.md
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Code.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/CodeLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Columns.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/CommentLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Constants.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/DataPseudoOpLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/DirectiveLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Disassembler.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Editor.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/LabelLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Line.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/MacroLine.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/contracts/assembly/Opcodes.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/HexToBytesConverter.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/Range.java
hedera-node/cli-clients/src/main/java/module-info.java

Takes the contract disassembler and finally a) moves it over to PCLI and b) makes it a proper tool in this repo (instead of being in a separate branch)
Given a contract's bytecode will disassemble it.
* Knows about the presence of Solidity metadata at the end of a contract.
* Can identify the selector table and list the selectors for you.
Fixes #7879
```bash
./hedera-node/cli-clients/services-cli.sh contract disassemble --id NNNN --bytecode <HEXIFIED-BYTECODE> --options OPTIONS
```
where the options are an (optional) comma-separated list of letters:
```
b    with contract bytecode header
d    do not decode before metadata
f    with code offsets in disassembly
m    list macros
p    with opcode (in hex)
q    recognize and …
```

"Productizing" contract disassembler at last

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersInjectionModule.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkAdminServiceInjectionModule.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeUpgradeActionsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CryptoTransferThenFreezeTest.java

- Make an Executor available to freeze handler via Dagger injection
- Use Executor to launch long-running code which unzips the upgrade file
- Other misc cleanup of freeze service
Fixes #6761

Make an Executor available to freeze handler via Dagger injection

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnfreezeAccountHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnfreezeAccountHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java

This PR fixes all, but one tests in the `Hip17UnhappyTokensSuite` by:
- Adding necessary checks for token deletion in `TokenFeeScheduleUpdateHandler`, `TokenFreezeAccountHandler`, `TokenMintHandler` and `TokenUnfreezeAccountHandler`
⚠️ Added 2 new lines in one of the tests, which overrides the configuration for the auto renew duration, as the test create tokens with autoRenewDuration == 100. In most configurations this will fails, as the minimum duration is much higher. This change is mostly to avoid this test failing on most configurations.
Fixes #8557 
**Checklist**

Resolve `Hip17UnhappyTokensSuite` errors

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CryptoTransferThenFreezeTest.java

This PR disables `CryptoTransferThenFreezeTest`, because it causes many other tests to fail. It probably needs to be executed manually for now.

Disable CryptoTransferThenFreezeTest

---

hedera-node/infrastructure/grafana/dashboards/production/hedera-node/arbitrary-stat-prom.json

This PR updates the "any stat" dashboard to also show all stats which have names that match the `merkle.*` pattern.

Update 'any stat' dashboard to also show merkledb stats

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTotalSupplyAfterMintBurnWipeSuite.java

This PR enables all tests in the `TokenTotalSupplyAfterMintBurnWipeSuite` spec as they are passing now.
Also fixes the remaining broken tests in the `Hip17UnhappyTokensSuite` by fixing the total supply for NFT minting.
Fixes #8601 
**Checklist**

Resolve `TokenTotalSupplyAfterMintBurnWipeSuite` errors

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java

The genesis account records were being created in different orders, causing an ISS. Ordering by account ID fixes the issue.

Fix genesis records creation order

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java

This PR adds logic to the fee calculation for TokenWipe and TokenBurn to check for token type, which will be then used for  selection from the feeDataMap
Fixes #8760 
**Checklist**

Fix fee calculation for TokenWipe and TokenBurn

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ServicesStatsManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/ServicesStatsManagerTest.java

Direct backport of #8754 to `release/0.42` branch.
Fixes: https://github.com/hashgraph/hedera-services/issues/8797

8751: No data source metrics for accounts, NFTs, or token rels

---

hedera-node/infrastructure/grafana/dashboards/production/hedera-node/network-details-prom.json

This PR updates the network details dashboard to add all platform statuses as defined in https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatus.java
Previously the dashboard only covered statuses 1-5, and not any of the new statuses added in the last couple months.

Update network details dashboard to map all values for platform status

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualMapStatistics.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapStatisticsTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java

Fix summary:
* A new VirtualMap metric is added, `nodeCacheSizeMb`
* The metric is updated on every virtual pipeline thread iteration (e.g. after flush, merge, etc.)
* A new unit test is provided
* A few related issues are fixed, see my comments in the files
Fixes: https://github.com/hashgraph/hedera-services/issues/8469

8469: New VirtualMap metric: virtual node cache size, in Mb

---

.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxc-build-release-artifact.yaml

- Fixes an issue which caused the Platform SDK alpha artifact to be sent to Maven Central instead of the internal registry. 
- Fixes an issue which caused invalid slack messaging to go out with the maven central details on a pre-release.
- Closes #8827

chore(ci): fix release pipeline issues affecting pre-release builds

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/HapiQueryOp.java

This PR introduces a small change to retry failing queries. This does not fix all possible issues that make the tests unstable, but many of them.

Retry failing queries during HAPI tests

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java

Fixes a  `CreateOperationSuite` test
Fixes #
#8855 
Added a `@HapiTest` annotation to the `childContractStorageWorks` test as it was passing.
I did some debugging for the rest of the tests and opened an issue to address the failing ones #8899 .
**Checklist**

Fix CreateOperationSuite test

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PrngSeedOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/BalanceValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TransactionBodyValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/streaming/RecordStreamValidation.java

We have some suites that do not look like a regular suite that should be run on it’s own, but rather as an additional step after the execution of all suites to check the behaviour after them:
- `BalanceValidation`
- `TokenBalanceValidation`
- `TransactionBodyValidation`
- `RecordStreamValidation`
Also `PrngSeedOperationSuite` is broken and is not being run against mono, removing the annotation from it as well as won't fix for now.
Fixes #
**Checklist**

Remove hapi test suite annotation from suite that not need to be fixed

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java

Add sorting by path to processing the dirty leaves stream in `MerkleDbDataSource.writeLeavesToPathToKeyValue()`.
Fixes #8815 
```
Benchmark                             (keySize)   (maxKey)  (numFiles)  (numRecords)  (numThreads)  (recordSize)  Mode  Cnt      Score   Error  Units
CryptoBenchMerkleDb.transferPrefetch         24  500000000        6000        100000            32          1024  avgt       22085.657           s/op
```
**Checklist**

8815: sort dirty leaves during flush

---

hedera-node/docs/privileged-transactions.md
hedera-node/docs/system-entities.md

Adds a markdown doc for all system entity numbers, to supplement `doc/privileged-transactions.md` which focuses on the admin accounts.
Fixes #8992.
**Reviewers**:
Suggestions for additional "magic numbers" to add to this doc are welcome.
**Checklist**

Add a doc for all system entity numbers

---

platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/WiringBenchmark.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/EventPool.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/Gossip.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/TopologicalEventSorter.java

Run the benchmark at full speed. Incorporate a back-pressure mechanism into `EventPool`.

Measure TPS

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpFilesSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/utils/ThingsToStrings.java

State file file dumper now dumps special files
* And for system files it tells you what file it is. 
* And you can ask for the report _without_ the file contents (much smaller file, suitable for putting into a spreadsheet.
Fixes #8990 
**Checklist**

Differential testing analytic engine: State file file dumper now dumps special files

---

platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/WiringBenchmark.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/Event.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/EventPool.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/Gossip.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/TopologicalEventSorter.java

Validate that all generated events have been processed. `Event` number is now `long` to allow for longer runs at ~1M TPS.
`TopologicalEventSorter.checkSum` is computed without synchronization to ensure that its `accept()` method is invoked in effectively single-threaded mode.
Related to #9005

Validate events; make event numbers longs

---

hedera-node/configuration/dev/application.properties
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoCreateValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AutoAccountCreatorTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/EnsureAliasesStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/ReplaceAliasesWithIDsInOpTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/StepsBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoHandlerTestBase.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java

- Avoids ISS in `smallContractCreate()` by removing special treatment of `node0` in `HapiTestEnv`.
- When un-aliasing an `0.0.<alias>` form `AccountID` in `ReadableAccountStoreImpl`, also considers "indirect" references where an ECDSA key has an implied EVM address that is an in-use alias.
- When answering a `CryptoGetInfo` query, ensures the returned `AccountID` is a numeric `0.0.X` id.
- Also enables a passing `ethereumCallWithCalldataBiggerThanMaxSucceeds()` spec (have not checked others).

Fix `smallContractCreate()` and enable `ethereumCallWithCalldataBiggerThanMaxSucceeds()`

---

hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java

Fix one of `TxnRecordRegression` tests.
Fixes #8943 
Added @HapiTest annotation to `recordNotFoundIfNotInPayerState()` test, had to change the expected return to `INVALID_TRANSACTION_ID` as that is the implemented logic.
**Checklist**

Fix TxnRecordRegression

---

hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java

Fixed some of `TxnReceiptRegression` tests.
Fixes #8917 
Added `@HapiTest` annotation to `returnsInvalidForUnspecifiedTxnId()`, `receiptAvailableWithinCacheTtl()` and `receiptNotFoundOnUnknownTransactionID()`. I had to extend the if condition in `validate` in the `NetworkTransactionGetReceiptHandler` in order to throw the correct exceptions and change the expected return of `receiptNotFoundOnUnknownTransactionID ()` to `INVALID_TRANSACTION_ID` as that is the implemented logic.
**Checklist**

Fix TxnReceiptRegression suite

---

platform-sdk/settings.gradle.kts

Gradle's include mechanism uses different names in the build/project path if the name is not already corrected here. This leads to some functionality in IntelliJ - like test debugging - to not work as expected.
**Checklist**

Fix 'swirlds-platform' vs 'platform-sdk' build identity

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/RecordListBuilderTest.java

This PR changes the calculation of the TransactionID.nonce. The calculation now includes both preceding and trailing transactions.
Closes #9117

Fix setting of nonce in RecordListBuilder

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PaidQueryHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetByKeyHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetRecordsHandler.java

The query handler inferface has a default implementation for fee calculation that reutrns `FREE`.  This is clearly incorrect for paid queries.
The paid query abstract base class does not override this default, however, and six (6) paid queries do not implement fee calculation as a result.
This change adds an abstract declaration of the fee calculation method to the PaidQueryHandler interface so that _paid_ query subclasses must implement fee calculation.
* Made fee calculation for base class PaidQueryHandler an abstract declaration instead of defaulting to FREE (from interface).
* Updated four(4) contract query handlers and two(2) network admin query handlers with a partial (just calculate the fee from workflow) non-free implementation of fee calculation to avoid compile issues.
* All six …

Fix Paid query handler base class to not permit subclasses to be free.

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
hedera-node/hedera-app/src/test/resources/signedState/MHS/settingsUsed.txt
hedera-node/settings.txt
hedera-node/test-clients/src/eet/resources/network/config/settings.txt
hedera-node/test-clients/src/itest/resources/network/config/settings.txt
hedera-node/test-clients/src/main/resource/testfiles/updateFeature/updateSettings/sdk/settings.txt
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/config/ReconnectConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java

Increased `reconnect.asyncStreamTimeout` property to prevent genesis reconnect from failure. Removed usages of `asyncStreamTimeoutMilliseconds`.
Fixes #8138 
This is a copy of https://github.com/hashgraph/hedera-services/pull/9133

08138 Increased `reconnect.asyncStreamTimeout` 

---

hedera-node/configuration/compose/settings.txt
hedera-node/configuration/dev/settings.txt
hedera-node/configuration/mainnet/settings.txt
hedera-node/configuration/preprod/settings.txt
hedera-node/configuration/previewnet/settings.txt
hedera-node/configuration/testnet/settings.txt
hedera-node/hedera-app/src/test/resources/signedState/MHS/settingsUsed.txt
hedera-node/settings.txt
hedera-node/test-clients/src/eet/resources/network/config/settings.txt
hedera-node/test-clients/src/itest/resources/network/config/settings.txt
hedera-node/test-clients/src/main/resource/testfiles/updateFeature/updateSettings/sdk/settings.txt
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/config/ReconnectConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/ConfigMappings.java

Increased reconnect.asyncStreamTimeout property to prevent genesis reconnect from failure
Description:
In case the tree gets too big, hashing may take more that 60s and in this case the learner node doesn't send the lesson confirmation on time, and the teacher node assumes that a connection between nodes should be closed. After that the nodes are not able to finish the reconnect properly.
Fixes https://github.com/hashgraph/hedera-services/issues/8138
This is a copy of https://github.com/hashgraph/hedera-services/pull/9132

08138 Increased `reconnect.asyncStreamTimeout` property to prevent genesis reconnect from failure

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/config/ReconnectConfig.java

This is a follow up for https://github.com/hashgraph/hedera-services/pull/9132
Fixes #8138

08138 Increased `reconnect.asyncStreamTimeout` property to 5 minutes

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoCreateValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

This PR fixes `aliasKeysAreValidated()` test in `CryptoTransferSuite` by enriching the validations of the aliases and keys.
Fixes #
**Checklist**

Fix `aliasKeysAreValidated` test in `CryptoTransferSuite`

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImplTest.java
hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandleParityTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

Part of #8466.
This fixes one test in the crypto transfer suite, testing various attempts at using immutable accounts.

Add checks for immutable keys

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/UtilScalePricingCheck.java

* Syncing the MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED check with mono(UsageLimits.assertMintableNfts)
Fixes https://github.com/hashgraph/hedera-services/issues/9177

Fix UtilScalePricingCheck test

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyFactory.java

* Fixed extremely bad exception design that resulted in massive runaway and time expansion when the hapi node fails.
Basically, we had methods declaring `Throwable` in signature, which makes correct exception handling practically impossible, so I cleaned up a few of those that impacted the runaway code path.  Then I changed the catch blocks to retry when possible, but fail completely when no amount of retry could fix the problem.  Now, instead of burning 6 hours at 100% CPU retrying connection to dead nodes, the HAPI test clients just fail all subsequent tests.
If PR #8733 revives, then a node restart can be added after that to restart the nodes when they fail, instead of just failing all the tests, but for now failing quickly is far preferrable to hours of useless retry.

07672 Run Hapi Tests

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java

Fixes #9201
The implementation of deserializeKeySize() does the wrong thing, as size is written as int in first 4 bytes all is needed is to read that size.

Fix deserializeKeySize method

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleTreeVisualizer.java

Closes #9205 
```
(root) State                               /       brass-bubble-diet-judge
0 HashgraphDemoState    hello_world!    /0      wage-lecture-wisdom-lunar
1 PlatformState         I'm_a_label     /1      share-move-bench-motor
0 PlatformData                       /1/0    corn-unit-immune-awesome
1 AddressBook                        /1/1    observe-speak-regular-race
2 DualStateImpl                         /2      demise-front-damp-travel
```

Add lables to the merkle tree visualziation in the logs.

---

hedera-node/configuration/testnet/application.properties
hedera-node/configuration/testnet/bootstrap.properties

The `0.42.4` tag threw the following error when starting in testnet:
```
java.lang.IllegalStateException: 'bootstrap.properties' contains unrecognized properties: [staking.maxDailyStakeRewardThPerH, staking.rewardRate]!
```
This PR fixes this issue by removing the errant properties from testnet's ` bootstrap.properties` and `application.properties` config files. 
These properties were removed in a 0.41.x release, but they are still in file 121 on testnet, and got accidentally copied to 0.42.
Additional related PRs:
* https://github.com/hashgraph/hedera-services/pull/9209
* https://github.com/hashgraph/hedera-services/pull/9210

[release/0.42] Remove unrecognized properties from testnet bootstrap and application config files

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java

* Minor additional cleanup of exception handling
* re-enable retry in downloadWith of FeesAndRatesProvider to allow some retry attempts without locking up the test run for hours.
* This was requested because some node failures are recoverable

9072 Enable Hapi Tests - General Improvements

---

hedera-node/settings.gradle.kts

Bump the hapi version in use by services to 0.43.0

Bump hapi version to 0.43.0

---

hedera-node/docker/Dockerfile

* Updated the docker file to use a more recent LTS base image, instead of using a PPA.
* Consolidated multiple RUN commands to reduce layers in the final image.
Ideally this will end the frequent failures to build the container image for CI test actions.
Future tasks will modify this further to use a more specifically build base image in the Swirlds Labs internal container repository.

task: Update Dockerfile to reduce failure rates in CI

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandlerTest.java

ScheduleSignHandlerTest `handleExecutesImmediateIfPossible` was not behaving deterministically.  This was traced to a HashSet that was allowing duplicate PBJ values, somehow, for reference-equal objects.  The set implementation was changed to LinkedHashSet, and appears to be behaving correctly now.

Fix unreliable behavior in Unit Test

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualMapStatistics.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapStatisticsTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java

Fixes: https://github.com/hashgraph/hedera-services/issues/9013

9013: Virtual node cache size metric name should be updated to bytes instead of mebibytes

---

hedera-node/hedera-app/src/xtest/java/contract/GrantApprovalXTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/GrantApprovalTranslator.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/GrantApprovalTranslatorTest.java

Implemented `HTSCall` for the classic `GrantApproval` functions and extended the X tests to match the `mono` service behaviour.
Fixes #
#9191  #9192 
**Checklist**

Match mono behaviour for Grant Approval system contract

---

hedera-node/configuration/testnet/upgrade/feeSchedules.json

Testnet feeSchedules.json in the repo was out-of-date from what is on testnet. Updated it to be the same as what is on testnet. Mainnet feeSchedules.json is same as this one in the repo.
NOTE: PRs to release branches will be opened once this is merged to develop.

Update testnet fee schedules

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1648Suite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1742Suite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2051Spec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2098Spec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue305Spec.java

Applies the fixes proposed by @tinker-michaelj  to the following failing tests against the mono repo:
- Issue2098Spec → QueryApiPermissionsChangeImmediately
- Issue2098Spec → AdminsCanQueryNoMatterPermissions
- Issue1648Suite → RecordStorageFeeIncreasesWithNumTransfers
- Issue1742Suite → CryptoTransferListShowsOnlyFeesAfterIAB
- Issue2051Spec → TransferAccountCannotBeDeleted
- Issue2051Spec → TransferAccountCannotBeDeletedForContractTarget
- Issue305Spec → CreateDeleteInSameRoundWorks
Adds the `@HapiTest` annotation to tests that pass without any other changes.
Fixes #9314 
**Checklist**

Fix failing HAPI tests in mono repo

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java

Turning on ContractCreateSuite.cannotCreateTooLargeContract
Fixes https://github.com/hashgraph/hedera-services/issues/8721

Fix cannotCreateTooLargeContract from ContractCreateSuite

---

platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/TransactionCodec.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/algorithms/ECSigningAlgorithm.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/algorithms/SigningAlgorithm.java
platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/algorithms/X25519SigningAlgorithm.java

- Updates StatsSigningTestingTool (SSTT) to hash data using KECCAK-256 when signing with the ECDSA Secp256k1 algorithm.
- Closes #9335 
- [Failing Test (Prior to the Fix)](https://swirldslabs.slack.com/archives/C03E22UB0A2/p1697642802149709)
- [Passing Test (After the Fix)](https://swirldslabs.slack.com/archives/C03E22UB0A2/p1697647732010719)

chore: fix StatsSigningTestingTool to hash the data for ECDSA signatures

---

hedera-node/configuration/testnet/upgrade/feeSchedules.json
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

Fixed allowance transfers tests in `CryptoTransferSuite`
Fixes #9284 
Fixes https://github.com/hashgraph/hedera-services/issues/9321
- Added missing validation that is_approval=true NFT transfer has owner's approval
- Fixed false positive detection of repeated AccountAmount's by including the is_approval value in AccountAmount "identity"

Allowance transfers fixes 

---

settings.gradle.kts

Do not attempt to clone/update `hedera-protobufs.git` if build was started in _offline mode_. 
**Checklist**

Allow build to run without internet connection using --offline

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.hapi.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-module-dependencies.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
hedera-dependency-versions/build.gradle.kts
hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/util/LogCaptor.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/GrpcServiceBuilder.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/verifier/BaseHandleContextVerifier.java
hedera-node/hedera-app/src/main/java/module-info.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/cache/EntityMapWarmer.java
hedera-node/hedera-mono-service/src/main/java/module-info.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
hedera-node/hedera-token-service-impl/src/main/java/module-info.java

Some SLF4J usages sneaked in through transitive dependencies I suppose. In the dependency "cleanup" (e.g. #7875) this was not yet addressed. Instead now you sometimes see:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
This problem was suppressed [before](https://github.com/hashgraph/hedera-services/blob/3893445245b2c290beafe776ea26cb414c8fc53f/platform-sdk/settings.gradle.kts#L143) by adding `slf4j-nop` which swallowed the logging. This is already gone on develop (hence the message above).
This PR does two things:
1. Exchange all usages of "slf4j" in the code with "log4j"
2. Add the `org.apache.logging.log4j.slf4` bridge as a central …

Remove all direct usages of slf4j / forward slf4j to log4j

---

.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/node-zxc-build-release-artifact.yaml
.github/workflows/node-zxc-compile-application-code.yaml
.snyk
build-logic/project-plugins/build.gradle.kts
build-logic/project-plugins/src/main/kotlin/Utils.kt
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.aggregate-reports.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.evm-maven-publish.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
gradle.properties
hedera-dependency-versions/build.gradle.kts

- Fixes the artifact name used during the Maven Central publish for the Hedera EVM.
- Fixes breakages caused by whitespace in the `version.txt` file.
- Fixes breakage in the CI pipeline due to invalid JSON.
- Temporarily disables Sonar analysis.
- Resolves JSON library vulnerability.
- Closes #9366

fix: resolve ci issues and maven central publish issues

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java

This PR fixes tests from the `uniqueTokenManagementSpecs`
Fixes #
One of the tests was change to expect `OK` status on precheck instead, because `OK` is only being used on precheck step.
**Checklist**

Fix `uniqueTokenManagementSpecs` leftover tests

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/TrieSigMapGenerator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java

Fixes https://github.com/hashgraph/hedera-services/issues/9434
Enable `AutoAccountUpdateSuite` updateKeyOnAutoCreatedAccount test. 
Fixes an issue in client side while generating signatureMaps, and add all the public keys that are needed by the transaction which may or may not have signatures for public key prefix matching.

Enable `AutoAccountUpdateSuite` test

---

hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottle.java
hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottleTest.java
hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/mocks/MockTransactionContext.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/BasicTransactionContext.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/NodeInfo.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/TransactionContext.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottling.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/FunctionalityThrottling.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/HapiThrottling.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/ThrottleReqsManager.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/TimedFunctionalityThrottling.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/TxnAwareHandleThrottling.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/BasicTransactionContextTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/NodeInfoTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/LedgerBalanceChangesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransferLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/StoresModuleTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottlingTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/HapiThrottlingTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/ThrottleReqsManagerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/TxnAwareHandleThrottlingTest.java

- Upon a failed auto-creation in `TransferLogic`, makes the node that submitted the failed auto-creation leak the reserved `CryptoCreate` capacity from its frontend throttle.

Invoke `leakCapacityForNOfUnscaled(numImplicitCreations, CryptoCreate)` on failed self-submitted auto-creation

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/IterableStorageManager.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/StorageAccess.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/IterableStorageManagerTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java

Fix broken HAPI tests by using Bytes.EMPTY instead of null
Fixes #9517
**Checklist**

use Bytes.EMPTY instead of null to indicate empty keys/values

---

hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/Scenarios.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/QueryPaymentSuite.java

Enable 3 new tets for query payment that never worked in Mono.
Also fixed the logic in `QueryChecker`
Fixes #9176

enable query payment suite

---

settings.gradle.kts

Use hedera-protobufs version 0.44.0
Partially fixes #9363

Bump hapi version in use to 0.44.0

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbStatisticsTest.java

This is a fix for the test failure described in #9512 and is a follow up for https://github.com/hashgraph/hedera-services/pull/9060
Fixes #9512 
**Checklist**

9512 Prevented MerkleDbStatistics from throwing exceptions if its methods called before `registerMetrics`

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyComparator.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleDeleteHandler.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtilityTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleTestBase.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java

* Enabled most of the HapiTest methods for Schedule Create and Schedule Delete
* Modifications to schedule handlers to increase passing tests
* Added a `KeyComparator` class to compare Key objects and impose a total order on collections of Keys.
* This is necessary to have deterministic order of key collections (particularly sets and maps) across nodes.

9046 Enable ScheduleCreateSpecs HAPI tests

---

.github/workflows/config/node-release.yaml

Tag `0.44.0-alpha.2` and create `release/0.44` branch. This PR schedules these two tasks to be executed on Oct 27 at 17:00 UTC / noon CDT.
Partially fixes #9363

Schedule release branch creation for 0.44

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/RandomOps.java

Enable another test and remove one test that is not needed anymore
Fixes #9531

enaled one more test and remove the other one that not really in use

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java

Fixes two tests in `ContractBurnHTSSuite`. Only `HapiTest` annotation added
Fixes #https://github.com/hashgraph/hedera-services/issues/9435

Fix tests in ContractBurnHTSSuite

---

hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AutoAccountCreatorTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/EnsureAliasesStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/ReplaceAliasesWithIDsInOpTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/StepsBase.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoHandlerTestBase.java

Fixed 38/41 unit tests. 
Left to be fixed:
[cryptoTransferTokenToImmutableReceiverScenario](https://github.com/hashgraph/hedera-services/blob/08044-auto-account-testing/hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java#L141)
[cryptoTransferNftToImmutableReceiverScenario](https://github.com/hashgraph/hedera-services/blob/08044-auto-account-testing/hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java#L175)
[validateNegativeAmounts](https://github.com/hashgraph/hedera-services/blob/08044-auto-account-testing/hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/ …

Fix unit tests for auto account testing

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/InternalDataLesson.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/StandardTeacherTreeView.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/TeacherTreeView.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStore.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenVirtualMapTeacherView.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
platform-sdk/swirlds-virtualmap/build.gradle.kts
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/RecordAccessor.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/RecordAccessorImpl.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTeacherTreeView.java

Fix summary:
* `getChildHashes()` method in `TeacherTreeView` is replaced with another method, `writeChildHashes()`. This new method is expected to write child hashes to the specified output stream in binary format, identical to how list of `Hash` objects was previously written
* In `StandardTeacherTreeView` this method is implemented using the old `getChildHashes()` and serializing them with `SerializableDataOutputStream.writeSerializableList()`
* In `VirtualTeacherTreeView` this new method delegates to the underlying data source
* In `VirtualDataSource` a new method is added for this purpose, `loadAndWriteHash()`
* This new method in `MerkleDbDataSource` loads hash bytes from disk and serializes them to the output stream, bypassing deserialization to `Hash`
Testing:
* Existing virtual …

9514: Reduce Java allocations when sending internal node hashes during reconnect

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/InternalEventValidator.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/InternalEventValidatorTests.java

09449 Create data consistency validator

---

platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbCompactionCoordinatorTest.java

Increased a timeout in `MerkleDbCompactionCoordinatorTest#assertCompactable` and `MerkleDbCompactionCoordinatorTest#testCompactionFailed` to prevent non-deterministic failures
Fixes #9559 
**Checklist**

9559 Increased timeout in the assertions to prevent non-deterministic failures.

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java

remove static from all the test in MiscCryptoSuite

remove static from all the test in MiscCryptoSuite

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java

Cherry-pick #9640 
Fixes https://github.com/hashgraph/hedera-services/issues/9639

Cherry-pick : Fix NPE in `TokenWipe` when using missing alias for an account

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java

The three remaining tests in `TxnRecordRegression` fail in both the modular and the mono code, even with a 3 second TTL. This PR just adds comments to revisit them later. 
Closes #9622

Add comments to failing record regression tests

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java

Fix NPE in FileServiceUtil
Fixes #9685

fix NPE in FileServiceUtil

---

.github/workflows/node-flow-deploy-adhoc-artifact.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxc-build-release-artifact.yaml

- Adds support for publishing the release artifacts to the public CDN
- `release/0.44`
- Closes #9691

chore: publish release artifacts to the public CDN

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts

- Normalizes the unit test output for all Gralde projects.
- Suppresses all output for passing & skipped tests.
- Shows failing tests in the output including their standard output/error streams.
- Closes #9693

chore: normalize test output across all Gradle projects

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/StorageAccess.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java

There were a couple of code review comments from pr #9519 that need to be addressed
Fixes #9517

address comments from pr #9519

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/OrderedServiceMigrator.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/DependencyMigrationTest.java

The logic for inter-service dependencies during startup migrations is currently in the `Hedera` class, which isn't directly tested. This PR captures that logic in its own object, with a test to verify its behavior.

Preserve logic via dependency migration test

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/node-zxc-compile-application-code.yaml
.github/workflows/zxc-jrs-regression.yaml
build-logic/settings-plugins/build.gradle.kts
build-logic/settings-plugins/src/main/kotlin/com.hedera.hashgraph.settings.settings.gradle.kts
gradle/wrapper/gradle-wrapper.properties

- Enables Gradle Build Cache Node support
- Updates CI pipelines to support remote build cache writes.
- Update Gradle configuration to support reading/writing cache from the remote.
- Closes #9758

chore: enable support for the Gradle build cache node

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractRevertibleTokenViewCall.java

Fix `develop` after merging [PR1](https://github.com/hashgraph/hedera-services/pull/9737) and [PR2](https://github.com/hashgraph/hedera-services/pull/9625) because of the related changes in those two PRs
Fixes #
**Checklist**

Fix develop while adding responseCode as the additional required parameter

---

platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/converters/IntegerConverter.java
platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/converters/LongConverter.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/converters/IntegerConverterTest.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/converters/LongConverterTest.java

This PR adds support for numerical literals in the ConfigConvertors for `IntegerConverter` & `LongConvertors`.
**Checklist**

Add support for underscored numerical literals in Configuration Converters

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java

Added new test in the AutoCreationSuite which covers this new case and passes in mono codebase as well.
With this change we cover this happy path from issue https://github.com/hashgraph/hedera-services/issues/9424:
Fixes #
**Checklist**

Add test to confirm preceding child record for HTS transfer

---

.github/workflows/node-flow-build-application.yaml
.github/workflows/node-zxc-compile-application-code.yaml
gradle.properties

- Limits the Gradle parallel worker count to 6 workers.
- Applies I/O niceness to the Gradle processes.
- Applies CPU niceness to the Gradle processes.
- Removes the configurable Gradle version from the CI workflows and instead always uses the Gradle wrapper version.
- Closes #9773

chore: apply limits to the Gradle parallelism to stabilize the Github runner agent

---

hedera-node/cli-clients/services-cli.sh
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpTokenAssociationsSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java

Dumps all token associations in a signed state file as CSV (actually, tab separated), deterministically.
Fixes #9694.
**Example**:
`./services-cli.sh signed-state --file=states/2023-10-29T00:01:59Z/151975134/SignedState.swh  dump associations --associations=associations.txt --summary`
```
account;token;balance;frozen;kycGranted;automaticAssociation;prev;next
200;2035606;1;T;T;;0;0
201;2035606;1;T;T;;0;0
202;2035606;1;T;T;;0;0
203;2035606;1;T;T;;0;0
204;2035606;1;T;T;;0;0
224;2035606;1;T;T;;0;0
938;127877;935000000;;T;;859814;0
938;624505;4000000000;;T;;1985922;859814
938;859814;373082010;;T;;624505;127877
938;1985922;320000;;T;;3716059;624505
938;3716059;75700000000;;T;;0;1985922
950;107597;1000000000;;T;;107598;0 …
```

Dumper for token associations (tokenrels)

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceMetricsTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fixes: https://github.com/hashgraph/hedera-services/issues/9477

9477: Direct memory / data source leak if teacher becomes inaccessible during reconnect

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java

* Added the environment variable `HAPI_DEBUG_NODE`.  When set to "true" this enables an in-process node for debugging HapiTest specs.
* Fixed a bug in the `HapiTestEngine` that caused failures if a method with non-empty parameter list was annotated with `@HapiTest`; now it skips that test and logs a note.
* Minor fix to exception handling in `HapiTestEnv`.

chore: Enable HapiTest debug via environment variable

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/StoppableThreadImpl.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskVirtualKeySet.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectNodeRemover.java

Fixes: https://github.com/hashgraph/hedera-services/issues/9764

9764: ReconnectNodeRemover.getRecordsToDelete() loops forever

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java

Related to #9808 
Needs to be cherry picked to `release/0.44`.

Copy the PCES into saved state directories.

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java

This change prevents possible NPE described in #9839 Instead, the method returns null and other methods pass that null to the point where it's retried on (see `DataFileCollection#retryReadUsingIndex`)
Fixes #9839 
**Checklist**

9839 Prevented possible NPE caused by a race condition

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenUpdateResourceUsage.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

This PR fixes `updateHappyPath` in `TokenUpdateSpec` by enriching the fee calculation by adding the expiration date to it, similar to how it's done in the mono code.
Fixes #
**Checklist**

Fix `updateHappyPath` in `TokenUpdateSpec`

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/istoken/IsTokenCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokentype/TokenTypeCall.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/istoken/IsTokenCallTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenAndTypeCheckSuite.java

Purpose of the PR is fixing the TokenAndTypeCheckSuite. Problems with the checkTokenAndTypeNegativeCases were the following:
In case of a call with invalid token ID to the IsTokenCall class, the status of the result was INVALID_TOKEN_ID, which doesn't match the mono output (success in all cases and false on the isToken field).
In case of a call with invalid token ID to the TokenTypeCall class, the status of the result was REVERTED_SUCCESS, which is a status which overrides the correct one after it is returned, so I had to override the execute function.
Fixes #9427 
**Checklist**

TokenAndTypeCheckFix (#9672)

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java

- It is possible that recent "hanging" runs of `recordStreamValidation()` are due to an intermittent failure in a validator that itself runs `HapiSpec`'s (e.g. the `TokenReconciliationValidator`) throwing an exception instead of returning a failed assertion from `HapiSpecOperation.exec()`.
- This would prevent the finalizer `ExecutorService` from being shut down, and lead to the test hanging forever.

Ensure all non-daemon threads are shutdown even if `exec()` throws 

---

platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/StoppableThreadTests.java

Fix flaky queue thread pause test

---

settings.gradle.kts

Update to use `0.43.0` tag for protobufs

Update to use `0.43.0` tag for protobufs

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/PreconsensusEventFileRenamed.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java

Related to #9883 
Needs to be cherry picked into 0.44

Fix race condition in PCES file copy.

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java

Add @Tag support on class-level
Fixes https://github.com/hashgraph/hedera-services/issues/9926

Support @Tag annotation on a class level

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

This PR aims to fix the last test in the TokenUpdateSpec, by adding additional validation in the ExpiryValidatorImpl, which is responsible to checking whether the current expiry is smaller number than the new expiry and if it's not, it should throw `INVALID_EXPIRATION_TIME`. This is not valid for Topic, hence the check.
Fixes #8939 
**Checklist**

Fix `standardImmutabilitySemanticsHold` in `TokenUpdateSpec`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImplTest.java

Adjust the key gathering context methods to translate exceptions from preHandle; key gathering should not fail for non-pure checks.
* Modified PreHandleContextImpl to translate exceptions from PreHandle in `allKeysForTransaction`
* Modified HandleContextImpl to translate exceptions from PreHandle in `allKeysForTransaction`
* Modified tests to match
Note: These changes assume that services preHandle methods only fail for situations where keys cannot be gathered.  To be fully correct we will need to modify a few service handlers that do not meet that expectation.

Adjust the key gathering context methods to translate exceptions from preHandle

---

.github/CODEOWNERS

Add the platform-base team to the code owners for `/platform-sdk/swirlds-logging/` and `/platform-sdk/**/module-info.java`
**Checklist**

Add base team to module-info and swirlds-logging modules

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/JrsTestReaderReportCommand.java

Allow specifying alternate JRS test directory for JTR report

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandler.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleHandlerTestBase.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java

* Fixed some general signature verification and record building issues previously identified
* Changed the trim to walk the key structure for required keys, rather than attempting a direct match (which will often fail incorrectly) in trim
* Added check in SignHandler to throw exception if a ScheduleSign transaction does not result in a change to signatories, or execution.
* Enabled 17 HapiTest specs in ScheduleSignSpecs.
Fixes #9869

Fix ScheduleSignHandler signature trim and verification building

---

hedera-node/test-clients/src/itest/java/AllIntegrationTests.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java

Since recordStreamValidations step is hanging in CI, disabling that step temporarily until we figure out the issue.

Disable RecordStreamValidations in CI

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java

Remove the check in `FileAppendHandler`  to see contents of the file are empty to fix a failing HAPI test. This check is not being done in `mono-service`

Remove the check in `FileAppendHandler`  to see contents of the file are empty

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyAccountsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUnhappyAccountsSuite.java

This PR moves two tests from `Hip17UnhappyAccountsSuite` to a new suite, because they tests functionality around expiry, which won't be implemented soon. 
Discussion here: https://github.com/hashgraph/hedera-services/issues/8556
Fixes #8556 
**Checklist**

Move `Hip17UnhappyAccountsSuite` tests for expiry to new suite

---

hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/mocks/MockRecordsHistorian.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorian.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/LedgerBalanceChangesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransferLogicTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransferListAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java

- Cherry-pick mono-service changes from #9904

Rationalize treatment of auto-create `MAX_CHILD_RECORDS_EXCEEDED`

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java

* Fixed an arithmetic bug in HandleWorkflow where we added instead of subtracting an offset
* Adjusted RecordCacheImpl to treat scheduled transactions as top-level istead of children of the sign or create.
* Adjusted RecordListBuilter to only create a synthetic transactionID if none is provided.
* Includes modifying AbstractGrantApprovalCall to _not_ send an unnecessary transactionID.
* Modified the DeduplicationCacheImpl to consider the `scheduled` flag when finding duplicate transaction ID values
Note: There remains a bug in consensus timestamp for child transactions.  That will be fixed in a separate PR as it also enables quite a few HapiTest methods, which makes that PR larger and more complex to review.
Fixes #9944

9944 Fix record cache handling to remediate "RECORD_NOT_FOUND" responses.

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.sdk.conventions.gradle.kts
platform-sdk/swirlds-common/src/main/java/module-info.java
platform-sdk/swirlds-logging/src/main/java/module-info.java
platform-sdk/swirlds-platform-core/src/main/java/module-info.java
platform-sdk/swirlds-unit-tests/structures/swirlds-merkle-test/src/main/java/module-info.java

...so that our own `com.swirlds...` modules come first.
By default, the check automatically determines a "prefix" for the module name and based on that decides if a module is our own module or a 3rd party one. In the case of `com.swirlds...` however, the prefix is only `com.`, because `swirlds-` is already part of the gradle project names.

Gradle: set moduleNamePrefix for ModuleDirectivesOrderingCheck (com.swirlds... modules)

---

.github/workflows/node-zxc-build-release-artifact.yaml
build-logic/project-plugins/build.gradle.kts
build-logic/project-plugins/src/main/kotlin/Utils.kt
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.application.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.hapi.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.platform-maven-publish.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.root.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.sdk.conventions.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts
build-logic/settings-plugins/build.gradle.kts
build-logic/settings-plugins/src/main/kotlin/com.hedera.hashgraph.settings.settings.gradle.kts
gradle.properties
gradlew
hedera-dependency-versions/build.gradle.kts
hedera-node/hapi/build.gradle.kts
hedera-node/hedera-app/build.gradle.kts
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/ActionsHelperTest.java
platform-sdk/swirlds/build.gradle.kts
settings.gradle.kts

https://docs.gradle.org/current/userguide/configuration_cache.html
For this to work, all external processes that are part of the Gradle configuration need to run through `providers.exec`. Many plugins do not yet do this, hence this PR removes all plugins that call `git` under the hood. Instead we call `git` directly using `providers.exec` where needed. 
Also, the `com.google.cloud.artifactregistry.gradle-plugin` is not compatible with the _configuration cache_ yet (https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/85). But the functionality is only needed for publishing. Until the plugin is fixed, we apply it conditionally when we run without cache for publishing.

Enable Gradle Configuration Cache

---

.github/workflows/node-zxc-build-release-artifact.yaml

fix: run 'releaseEvmMavenCentral' with --no-configuration-cache

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java

- https://github.com/hashgraph/hedera-services/issues/8716
- Fixes https://github.com/hashgraph/hedera-services/issues/8720
**Checklist**

fix: enable last 2 tests from ContractCreateSuite

---

.github/workflows/node-zxc-build-release-artifact.yaml
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts

This allows running maven central publishing with configuration cache enabled, so we do not need to call Gradle in a special way here on CI.
Revert of / follow up to: #10027 
**Checklist**

chore: simplify Gradle signing setup

---

hedera-node/hapi/build.gradle.kts

Fixes an issue introduced in #9651 
If the branch is already checked out, the build wouldn't update it, because we only used`fetch`.
**Checklist**

Gradle: fix 'hedera-protobufs' git pull

---

.github/workflows/node-zxc-build-release-artifact.yaml

- Addresses the issues preventing EVM and Platform SDK artifacts from being published to Maven Central.
- `develop`
- `release/0.43`
- Related to #9711

chore: disable Gradle configuration cache and parallelism when releasing to Maven Central

---

.github/workflows/node-zxc-compile-application-code.yaml
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts

- Adds support for boxing gradle resource usage via Linux Control Groups.
- Updates the `-XX:ActiveProcessorCount` switch used by the JUnit test runners. 
- Closes #10031

chore: adds linux control group support

---

.github/workflows/node-zxc-deploy-preview.yaml

- Updates the Jenkins job name used by the validator from `build-preview-testnet` to `build-previewnet`.
- Clarifies the name of the github action step. 
```[tasklist]
```
- Closes #10069

Fix previewnet deployment workflow to use correct Jenkins pipeline name for validation

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java

- When running the `_Eth` variants of `HapiSuite`'s, many payer accounts are created using auto-account creation; but in `itest` the default payer is not a superuser and could be throttled. This _might_ explain failures like [these](https://scans.gradle.com/s/polwht4atkecy/tests/task/:test-clients:itest/details/AllIntegrationTests/concurrentSpecs()%5B2%5D?page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1)?

Ensure ETH account creation is not throttled

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/BestEffortPreconsensusEventFileCopy.java

Related to #10082 
Needs to be cherry picked to 0.44

Catch UncheckedIOException during PCES file copy.

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/BestEffortPreconsensusEventFileCopy.java

Catch UncheckedIOException during PCES file copy. (#10083)

---

build-logic/project-plugins/build.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-module-dependencies.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
hedera-dependency-versions/build.gradle.kts
hedera-node/hapi-utils/src/main/java/module-info.java
hedera-node/hedera-evm/src/main/java/module-info.java
hedera-node/hedera-mono-service/src/main/java/module-info.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/EntityManager.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/SkipNullRepresenter.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/validation/PostUpgradeValidation.java
hedera-node/test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
hedera-node/test-clients/src/main/java/module-info.java
platform-sdk/swirlds-common/src/main/java/module-info.java

- Fix module names that are already defined via `Automatic-Module-Name` so we do not change them during patching
- Update SnakeYAML to 2.x (and Jackson using it) to remove the need to patch it 
There are some production code changes in this PR because the API of constructors in SnakeYAML 2.x has changed.

Gradle: Version Upgrades - SnakeYAML and Jackson / Module Name fixes

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java

- Initializes the `ChildFinalizeContextImpl` with a `ReadableStoreFactory` from the dispatched `childStack`.
- This is necessary so we see tokens created **during the dispatched transaction**.

Use readable store from child stack for `ChildRecordFinalizer`

---

hedera-node/hedera-app/src/xtest/java/contract/BurnsXTest.java

* Fixed X test to pass with two return parameters
* Added X test with invalid supplyKey 
Fixes #10040

Provide more X test for burnToken key verification

---

hedera-dependency-versions/build.gradle.kts

Revert PBJ version back `0.7.6` to fix failing HAPI tests

Revert PBJ version back `0.7.6`

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/EventConfig.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java

Use legacy intake pipeline by default

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleGetInfoHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java

* Fixed typo in ScheduleInfo query handler that resulted in setting expiration time instead of execution time.
* Enabled the three tests that exercise that bug.
* Enabled one more schedule create test
* Adjusted comments for execution tests that rely on monoservice key gathering behavior.
Fixes #9975.

9975 Fix ScheduleExecutionSpecs methods that do not execute

---

platform-sdk/swirlds-config-impl/build.gradle.kts
platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationBuilderFactoryImpl.java
platform-sdk/swirlds-config-impl/src/main/java/module-info.java
platform-sdk/swirlds-config-impl/src/main/resources/META-INF/services/com.swirlds.config.api.spi.ConfigurationBuilderFactory

Fixes #10112
Adds Google AutoService annotation processor to config API.

Use Google AutoService for SPI

---

platform-sdk/swirlds-platform-core/build.gradle.kts
platform-sdk/swirlds-platform-core/src/jmh/java/com/swirlds/platform/core/jmh/ConsensusBenchmark.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/build.gradle.kts

Part of [#6640](https://github.com/hashgraph/hedera-services/issues/6640)

JMH benchmarks moved to test module to platform-core

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java

Lambda around the Comparator is redundant. High performance overhead.
Fixes #10153

10153: Comparator wrapped in lambda generates lots of garbage

---

.github/workflows/node-flow-fsts-daily-regression.yaml

Disable failed upgrade tests until NMT get fixed

Disable failed upgrade tests

---

hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/models/OwnershipTrackerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/models/UniqueTokenTest.java

This PR changes the following:
- Remove redundant `setup()` method in `OwnershipTrackerTest` (JUnit 5 auto-instantiation)
- Remove redundant metadata assignment in UniqueTokenTest
**Related issue(s):**
Closes [#2095](https://github.com/hashgraph/hedera-services/issues/2095)

2095 fix redundant unused statements in test code

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/InProcessHapiTestNode.java
hedera-node/test-clients/src/main/java/module-info.java

The in process hapi test node tried to set a null value in shutdown for a method that no longer accepts null.  This caused a crash after each HapiTest.  The fix is to simply not call the method with null.
Fixes #10157

fix(HapiTest): fixing null pointer exception in hapi in process test node shutdown.

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/BasicSoftwareVersion.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/events/BaseEventHashedData.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/PlatformVersion.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/system/BasicSoftwareVersionTest.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/PlatformVersionTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/ConsensusHashManager.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/StartupStateUtils.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/ConsensusHashManagerTests.java

Fix ISS detection.

---

.github/workflows/node-zxc-compile-application-code.yaml

- Disable Gradle cache cleanup features.
- Closes #10202

fix: disable Gradle cache cleanup features

---

.github/workflows/flow-pull-request-formatting.yaml

- Adds a new CI workflow to enforce all pull request titles to follow the conventional commit syntax.
- Closes #10180

chore: add new pull request formatting check workflow

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIterator.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIteratorTest.java

Do not timeout when adding to an internal queue. If the operation blocks for a very long time it should be considered a performance issue and addresses at the root cause (f.e. flushing).
Fixes #9872
**Checklist**

fix: 09872: MerkleSynchronizationException: Timed out waiting to supply a new leaf to the hashing iterator buffer

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java

fix: clear expired EventImpls instead of simply discarding

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java

fix: Handle ArithmeticException in safeFractionMultiply()

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts

We do not have a good reason to publish them and the POM metadata is incomplete/confusing.
This PR also fixes that, if we should publish test fixtures again in the future, versions will be added to _test fixture onnly_ dependencies.
Fixes #10143
**Checklist**

build: do not publish test fixtures

---

.github/workflows/flow-pull-request-formatting.yaml

- Changes the `on: pull_request` trigger to a `on: pull_request_target` trigger in order for the `flow-pull-request-formatting.yaml` workflow to function correctly with forks.
- `release/0.45`
- Closes #10193

chore(ci): change the trigger on the PR Formatting workflow

---

hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractStoresSubcommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
hedera-node/cli-clients/src/main/java/module-info.java
hedera-node/hedera-app/src/main/java/module-info.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/ContractStateMigrator.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/internal/ContractMigrationValidationCounters.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java

New class `ContractStateMigrator` will migrate from a mono service's contract store representation to a modular service's contract store (given by a `WritableKVStore`).
Can optionally perform a validation on the resulting migrated state, ensuring that it is consistent in some ways
* has same number of entries as original state
* all linked lists of slots are still linked
Shown correct by enhancing the contract store dumper to (optionally) migrate the contract store before dumping it. Diff on the two dumps (without migration and with migration) shows only the summary line changes: and that only to include a migration flag (to distinguish them).
Has code that commits the migration-in-progress modular store every 10000 items added (to force flush-to-disk).  Tricky thing …

feat(migration): Migrate contract store (contract's slots) from monservice to modular-service representation

---

.github/workflows/node-flow-pull-request-checks.yaml

- Ensures the JRS job of the PR Checks workflow does not execute when the PR is created from a forked repository or by dependabot.
- `release/0.45`
- Closes #10229

chore: ensure the pull request check workflow properly handles forks

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java

chore: disable sync++-

---

platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java

This pr removes the ip printing for the ui. When executed in a linux environment it was introducing an invalid character in the string interpreted as a format character that ended up in the following exception after:
```
java.util.UnknownFormatConversionException: Conversion = 'w'
at java.base/java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2855) ~[?:?]
at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2891) ~[?:?]
at java.base/java.util.Formatter.parse(Formatter.java:2747) ~[?:?]
at java.base/java.util.Formatter.format(Formatter.java:2671) ~[?:?]
at java.base/java.util.Formatter.format(Formatter.java:2625) ~[?:?]
at java.base/java.lang.String.format(String.java:4145) ~[?:?]
at com.swirlds.demo.hashgraph.HashgraphDemoMain$Picture.print(Ha …
```

fix: remove incompatible ip printing in linux

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/BrokenTransformationException.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/ContractStateMigrator.java

Nodes added to the merkle tree _must be added in deterministic order_.
Especially for the migrators, which add so many nodes they cross _commit_ boundaries.
Remove the concurrent sinking of contract slots; replace with accumulating all `fromState` slots into a concurrent queue, then placing them in an array, and then sorting them.
Fixes #10293
**Checklist**

fix(migration): Migrate contract slots from mono- to modular- in deterministic order

---

.github/workflows/flow-artifact-determinism.yaml
.github/workflows/flow-gradle-determinism.yaml
.github/workflows/support/scripts/generate-gradle-artifact-baseline.sh
.github/workflows/zxc-verify-gradle-build-determinism.yaml

- Adds a new CI workflow which runs on `develop` commits and tags to verify all Gradle artifacts are produced deterministically.
**NOTE: This pipeline is expected to fail until we fix the build determinism issues with follow up pull requests.**
- Closes #10311

chore(ci): add a new CI workflow to ensure release artifact determinism

---

hedera-node/hedera-app/src/xtest/java/contract/AbstractContractXTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QueryHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ProxyWorldUpdater.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ProxyWorldUpdaterTest.java

Implement the `lazyCreationCostInGas` method in the `HandleHederaOperations` class.
Fixes #10336
This was part of a larger pr but is pulled out to potentially unblock some HAPI tests that depend on this functionality.
**Checklist**

feat: Implement lazyCreationCostInGas method

---

hedera-node/hedera-app/build.gradle.kts

Description:
This PR update modrun for running with the dev config.
Fixes https://github.com/hashgraph/hedera-services/issues/10227

fix: 10227 use dev config with modrun

---

.github/workflows/node-flow-pull-request-checks.yaml

- Ensures the Snyk workflow does not run on dependabot or forked pull requests.
- Closes #10354

fix(ci): snyk workflow should not run on dependabot or forked pull requests

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeChildRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUnhappyAccountsSuite.java

This PR move `dissociationFromExpiredTokensAsExpected()` test to `TokenUnhappyAccountsSuite` as it's using expiry logic, which is not implemented.
Fixes dissaciation of deleted tokens and especially nfts, by checking for changes in the token reletions to add them in the transfers list while finalizing the record.
Fixes #
**Checklist**

fix: disassociate deleted nft does not commit a transfer list

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java

Fixes canUseAliasesInPrecompilesAndContractKeys 
Fixes #10251

fix: canUseAliasesInPrecompilesAndContractKeys suite test

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessor.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038Test.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/ValidContractIdsAssertion.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

fix: ensure failed `CREATE2` action is finalized w/ proper frame

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/EvmActionTracer.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomContractCreationProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/ActionStack.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/EvmActionTracerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomContractCreationProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/ActionStackTest.java

- Closes #8533 
- Fix incorrect behavior which, upon a creation failing in a `AbstractMessageProcessor.start()` implementation, would leave the pending action for the originating `CALL`/`CREATE` _still on the tracer's action stack_.
* This removes the need for the `Source` enum's `POPPED_FROM_STACK`/`READ_FROM_LIST_END` distinction.
- Ensure a failed creation is traced even in the case of a failed value transfer to the new contract address.
* This removes the need for the `HaltShouldTraceAccountCreation `'s enum's `YES`/`NO` distinction.

fix: finalize actions from stack for ALL failed creation attempts

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandlerTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java

Modified the key validation to only add primitive keys to remaining keys if a non-validated key is not the original create payer key (i.e. "Default Payer").
* This ensures the original create payer, which had to sign the original create transaction, counts as having signed.
* This also allows us to not *store* the keys for that payer, if those primitive keys are not otherwise required.
Fixes: #10364

fix: Match monoservice "hidden default payer" behavior

---

hedera-node/docker/Dockerfile
hedera-node/docker/start-services.sh

- Updates the E2E/ITest docker definition to use Java 21 during runtime.
- Uses ZGC and ZGenerational
- Adds malloc memory usage fix
- Optimizes docker build 
- Improves docker image build time (down to ~1 minute depending on internet connection speeds)
- Closes #10269

build: update e2e and itests to use Java 21 during runtime

---

.github/CODEOWNERS

Adds the `platform-base` team as code owners to two modules that are going away so they can prevent new code from being added.
Fixes #10323
**Checklist**

chore: Add platform-base as code owners to two platform modules

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java

This PR only adds HapiTest annotation to `TargetNetworkPrep` suite
Fixes #8900 
**Checklist**

fix: only enable `TargetNetworkPrep` suite

---

hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/CustomGasCharging.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/CustomGasChargingTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallV1SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC1155ContractInteractions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC721ContractInteractions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileV1SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/LogsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/IdFuzzingProviderFactory.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java

Cherry-pick https://github.com/hashgraph/hedera-services/pull/10379 to `release/0.45`.
Context:
Take into consideration the input bytes' size from the evm transaction when calculating the intrinsic gas cost.
Fixes #9988
**Checklist**

fix: Consider input bytes when calculating gas cost (#10379)

---

.github/workflows/support/scripts/loki-logs.sh

fix: Fix typo in compare two string variables

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetEventCreator.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetUtils.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/intake/OrphanEventsIntakeTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/linking/OrphanBufferingLinkerTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorTests.java

fix: Make event descriptor building and accessing thread safe

---

.github/workflows/node-flow-fsts-daily-interval-01.yaml
.github/workflows/node-flow-fsts-daily-regression.yaml

Also reenable previously failed upgrade tests after NMT fix

chore: Drop upgrade test support for Ubuntu 18.04

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmTransactionFactoryTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java

Add a check to ensure that contracts with empty initcode cannot be created.  There was a check for checking empty smart contract byte code files but not for inline transactions.
**Checklist**

fix: Add check for empty inline initcode for contract creation

---

.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/support/scripts/generate-gradle-artifact-baseline.sh
.github/workflows/zxc-verify-gradle-build-determinism.yaml

- Fixes an issue with the windows runners generating `sha256sum` output containing a leading asterisk `*` mark. 
- Adds the determinism test as a pull request check.
- Closes #10454

fix: windows runner failure when verifying the artifact determinism

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/MixedSmartContractOpsLoadTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithStakedAccounts.java

Fixes all places `getAccountDetails` is used to pay with GENESIS
Fixes #10253 
Fixes #10255

fix: Fix regression tests failed due to HapiGetAccountInfo

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/FullResult.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractHtsCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/Erc20TransfersCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/Erc721TransferFromCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc20TransfersCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc721TransferFromCallTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/NetworkTypeFilterOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java

- Closes #10424 by returning the `RecordBuilder` from an ERC transfer dispatch to the `MessageCallProcessor` so it can be updated with a status of `INSUFFICIENT_GAS`.
- Closes #10431 by adding `ifHapiTest()` and `ifNotHapiTest()` spec operations to target the different behavior mod-service will exhibit in the edge case that insufficient child records are available to handle a contract operation.
* Instead of throwing an exception to the top-level HAPI transaction, mod-service preserves a "clean shutdown" of the EVM transaction w/ traceability information.
- _Misc_: 
* Extracts an `inProgressBody()` method in `SingleTransactionRecordBuilderImpl` to improve readability and possible reuse.
* Deletes the unused `execute()` overload in `Erc721TransferFromCall`.

fix: use `RecordBuilder` variants of result construction in transfer HtsCalls

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoGetInfoRegression.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/RandomOps.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AddressAliasIdFuzzing.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/PrecompileMintThrottlingCheck.java

Enabled some tests that are passing now and also removed tests that turned out to be obsolete.

chore: Enable some tests and ignore others

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java

As per this comment https://github.com/hashgraph/hedera-services/pull/10287#pullrequestreview-1775613565
The tests requiring top-level signatures are commented
Fixes #9392 
**Checklist**

fix: `LeakyContractTestsSuite` test with top-level signatures

---

hedera-node/test-clients/src/itest/java/AllIntegrationTests.java

- Disables `concurrentEthSpecs()` per https://github.com/hashgraph/hedera-services/issues/10516 but does not close it (RCA pending).

chore: Remove `concurrentEthSpecs()`

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2098Spec.java

This PR changes the tests by instead of erasing the property it sets them to 0-1. Which is essentially the same thing, as far as the testing is concern.
Fixes #8769 
**Checklist**

fix: Override properties for `Issue2098Spec`

---

.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/node-zxc-compile-application-code.yaml

- Changes the default value for the `enable-dependency-check` input to be disabled.
- Adds a discrete `dependency-check` job to make the reason for failure clear.
- Ensures the `Code / Compiles` job is run prior to all other PR check jobs.
- Closes #10192

chore: execute the build workflow before running other workflows to improve cache utilization

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java

Clear "side-effect fields" after switch a child record from `SUCCESS` to `REVERTED_SUCCESS`.
Fixes #10308
At first, I followed this strategy to remove side-effect fields:
- Find specs with system contract call with `REVERTED_SUCCESS`
- Fuzzy match them mod vs mono (individual specs)
- Clear side-effect fields based on results of fuzzy matching
What did I check:
- `ContractMintHTSSuite.rollbackOnFailedMintAfterFungibleTransfer()` — side-effect fields removed in prev PR
- `ContractDeleteSuite.cannotUseMoreThanChildContractLimit()` — checked records and didn’t find any side-effect fields under `REVERTED_SUCCESS`
- `LazyCreateThroughPrecompileSuite.erc20TransferLazyCreate()`  — checked and removed `automatic_token_associations` …

fix: clear "side-effect fields" after switch a child record from SUCCESS to REVERTED_SUCCESS

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1744Suite.java

This PR adds a civilian payer account for the only test in the `Issue1744Spec`. This is needed, because some part of the test depends on the fees payed by the first crypto transfer. However previously it depended on account 0.0.2 to be charged, which can't happen
Fixes #8765 
**Checklist**

fix: Correct payer account on `Issue1744Spec`

---

.github/workflows/flow-node-performance-tests.yaml

12 hours is  too tight for current workflow

ci: change cron job to every 16 hours

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java

feat: Add test setting to force ignore PCES signatures

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/OrderedServiceMigrator.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/DependencyMigrationTest.java

There's an unnecessary round of registration happening for the `EntityIdService` in the `OrderedServiceMigrator`. Since the registration is already invoked in the `Hedera` class (along with all other services), there's no need to do so here. 
Discovered while implementing #10084

fix: Eliminate extra service registration

---

hedera-node/hedera-app/build.gradle.kts

Follow up to: #10249
Fixes that multiple tasks overwrite each other (one task deleting files the other created).
**General Gradle rule:** Never have multiple Gradle tasks write into the same location.
@tinker-michaelj @nathanklick @jamesnguyentech The result from the copying into `build/node` is the same as before, just that is is now consistently working. But I am not sure if it is correct. For me the applications don't seem to start correctly. But I miss a lot of context. Could you please try locally:
`./gradlew clean :app:run`
`./gradlew clean :app:modrun`
See if things work as expected, and if not adjust details in this block that decides which files go where in the working directory:
```
into("lib") {
from(copyLib)
}
into("apps") {
from(copyApp)
}
into("onboard") { …
```

build: merge 'Sync' tasks that wrote into the same destination

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/fixtures/FakeNodeStakeUpdateRecordBuilder.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/NodeStakeUpdateRecordBuilder.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/RecordStreamAccess.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

- Closes #10520 by enabling two passing specs
- Stabilizes CI by:
1. Clearing `RECORD_STREAM_ACCESS`'s map of listeners so it will reconstruct watchers as needed.
2. Setting the end-of-staking period memo on the *record* of the synthetic `NodeStakeUpdateTransaction` so these transactions will be correctly skipped in `getTxnRecord()` child record assertions.

chore: enable passing `ContractCallSuite` specs

---

platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java

fix: downgrade migration testing tool errors to warnings

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/transaction/handler/VirtualMerkleTransactionHandler.java

fix: owngrade PTT error to a warning

---

platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionCompactionTest.java

Fixed nondeterministically failing `DataFileCollectionCompactionTest.testMergeUpdateSnapshotRestore` test
Fixes #10576

fix: `DataFileCollectionCompactionTest.testMergeUpdateSnapshotRestore` flake

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/CannotDeleteSystemEntitiesSuite.java

- Ensure system accounts always have some funds before attempting a prohibited delete in `CannotDeleteSystemEntitiesSuite`.
* This prevents confusing `INSUFFICIENT_PAYER_BALANCE` warnings in CI; even though these are not treated as test failures, they look that way.

chore: avoid confusing `INSUFFICIENT_PAYER_BALANCE` warnings

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/hashing/EventHasher.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventHasherWiring.java

feat: Create hasher classes

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Added asserts to make sure that modifying methods of `VirtualMap` are never used by different threads at the same time. 
Fixes #10583

fix: Added asserts for threads in all modifying methods

---

platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/converters/EnumConverter.java
platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConverterService.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/converters/EnumConverterTest.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/internal/ConfigDataServiceTest.java
platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/internal/ConverterServiceTest.java

Creates a default support for converting enum values
Fixes # https://github.com/hashgraph/hedera-services/issues/10535

fix: 10535 add enum converter

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsNodeDeathReconnectTest.java

Until a new tag is added for reconnect test to be run in a different environment, disable it running under Misc tag in CI. This could probably be causing the hanging for Misc tests

chore: Disable reconnect test in CI 

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextTransactionProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/AbortException.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/CustomGasCharging.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmStaticTransactionFactory.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/records/EthereumTransactionRecordBuilder.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/EvmFrameState.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/HederaEvmAccount.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ProxyEvmAccount.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/TokenEvmAccount.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/ContextTransactionProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionProcessorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/CustomGasChargingTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/hevm/HederaEvmTransactionResultTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java

- Closes #10599 by refactoring as suggested.
- Adds `AbortException` to eliminate duplication of computing the effective `senderId`; now the exception thrown from an aborted `processTransaction()` call includes the `senderId` from `computeInvolvedParties()`.
- Since we no longer need to use the `feesOnlyUpdater` after an abort, this also lets us easily preserve the HAPI fees charged by the workflow by just committing the root updater after an abort.
* Avoids partial gas charges by refactoring `CustomGasCharging` to only charge _any_ fee if _all_ fees are payable.
- Removes unreachable `try`/`catch (ResourceExhaustedException)` around `runToCompletion()`.
- For mono-service fidelity, allows long-zero addresses to be used in top-level HAPI operations even when the …

chore: Misc contract cleanup and fixes

---

hedera-node/configuration/dev/bootstrap.properties
hedera-node/data/config/bootstrap.properties
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/contract/queries/GetContractInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/contract/GetContractInfoAnswer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/crypto/GetAccountBalanceAnswer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/crypto/GetAccountInfoAnswer.java
hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/contract/queries/GetContractInfoResourceUsageTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountInfoResourceUsageTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/contract/GetContractInfoAnswerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/crypto/GetAccountBalanceAnswerTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/crypto/GetAccountInfoAnswerTest.java
hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountInfoHandlerTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/AccountSummariesApi.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java

Reverts this PR https://github.com/hashgraph/hedera-services/pull/10149
Adds a feature flag `tokens.balancesInQueries.enabled` to enable/disable the token balances and token relationships information to be returned in queries

fix: Add a feature flag for token balances and token relationships and enable them

---

.github/workflows/node-flow-pull-request-checks.yaml

- Gates the expensive PR Checks behind the Spotless & Dependency Check (Module Info) tasks. 
- Closes #10656

chore(ci): gate the expensive pull request checks behind the spotless & module info checks

---

.github/workflows/flow-artifact-determinism.yaml
.github/workflows/node-flow-build-application.yaml
.github/workflows/node-flow-pull-request-checks.yaml
.github/workflows/support/scripts/generate-docker-artifact-baseline.sh
.github/workflows/zxc-verify-docker-build-determinism.yaml
README.md

- Updates the `README.md` file to add/fix the status badges. 
- Updates the `README.md` to reflect the correct JVM requirements.
- Adds a new reusable workflow to check the deterministic behaviors of the new docker image definitions.
- Updates the PR Check workflow to add the new docker determinism checks.
- Updates the PR Check workflow to adjust the naming of the Gradle determinism checks.
- Closes #10619

chore(ci): add support for docker image determinism checking

---

.github/workflows/support/scripts/generate-docker-artifact-baseline.sh
.github/workflows/zxc-verify-docker-build-determinism.yaml
.github/workflows/zxc-verify-gradle-build-determinism.yaml

- Updates the Artifact Determinism CI pipelines with the following changes:
- Reduces the number of concurrent macOS runners from 4 to 1 concurrent runner per job.
- Increases the speed of the docker verification pipelines by avoiding Gradle rebuilds. 
- Closes #10675

chore(ci): reduce macOS runner usage footprint

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/copy/MerkleInitialize.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleSerializationTests.java

fix: state leak

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java

- closes #10705
- must be cherry picked into 46

fix: Mark prehandle as complete in legacy intake pipeline

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java

- Fixes unintentional use of `WritableStates` in `RecordCacheImpl#getReadableQueue()`.
- Stabilizes `canAutoCreateWithFungibleTokenTransfersToAlias()` in presence of end-of-day staking records by using `getFirstNonStakingChildRecord()`.
- Creates a utility method `assumingNoStakingChildRecordCausesMaxChildRecordsExceeded()` that allows transactions requiring all preceding child records to be used in CI; uses it to stabilize two specs.

chore: fix mutability exception in pre-handle; stabilize CI

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java

Refactor the logic for conditions to precheck for possible invalid contract call transactions
**Checklist**

chore: clean up contract call sanity precheck logic

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyComparator.java
hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/key/KeyComparatorTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandlerTest.java

* Added KeyComparatorTest
* Added data-driven testing to exercise all probable input combinations.
* Adjusted KeyComparator to correctly order keys where testing showed errors.
* Adjusted one other unit test that depends on key ordering to match correct order.

chore: Create a thorough unit test for KeyComparator

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java

Replaces multiple hard-coded `getChildRecord(0)` with `getFirstNonStakingRecord()`.

chore: account for staking records in various specs

---

hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/NettyGrpcServerManager.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiApiClients.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeCopyOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/NftTransferSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java

- Closes #10637
- As per mod-service, only override Netty server defaults if active profile is not `DEV`.
* This lets us enable `SteadyStateThrottleCheck` and get stable success with a max allowed deviation of 7% from nominal TPS over the 3-minute test period.
- Avoids a possible unhandled exception in `SynchronizedThrottleAccumulator` in which thread scheduling effects could make `Instant.now()` appear to go backward in time.
- Restores an accidentally removed call to `shutdownChannels()` in `HapiApiClients`.
- Makes `NONDETERMINISTIC_NONCE` a default `SnapshotMatchMode` when running in a Linux environment (mostly accurate approximation for "when running in CI").
- Adds `NONDETERMINISTIC_TRANSACTION_FEES` to `ExtCodeCopyOperationSuite.verifiesExistence()`.
- Stabilizes …

chore: only override Netty defaults on non-`DEV` profile; other fixes

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/forensics/RecordStreamEntry.java

Adding getter to `RecordStreamEntry` for `TransactionRecord`.
We are trying to enhance a new feature that the local node has  -> debug command. It takes consensus timestamp and outputs the corresponding record file to the command line.
We are trying to filter all the unnecessary records form the output but we need some more data to be accessible in the `RecordStreamEntry` entity.
https://github.com/hashgraph/hedera-services/issues/10702

feat: adding getter to RecordStreamEntry for TransactionRecord

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml
hedera-node/log4j2.xml
hedera-node/test-clients/src/main/resource/log4j2.xml

- `TransactionStateLogger` is prohibitively expensive at `TRACE` level.

chore: use INFO level for state changes log

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHelperTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java

- Updates to only set the `paid_staking_rewards` field in a record if there are non-zero rewards paid; and only include non-zero rewards in the list (c.f. mono-service behavior [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java#L295)).
- Mark `propagatesNestedCreations()` as `FULLY_NONDETERMINISTIC` because we are (currently, at least) accepting that mod-service externalizes internal `CONTRACT_CREATION`s in the order they are _attempted_; while mono-service externalizes them in the order they _succeed_.

chore: don't externalize zero staking rewards

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java

Please review carefully.  The following changes have been made. 
* the `pcli state genesis` command now sets the current and previous address book to null. 
* code paths which threw exception during testing due to null address book in the state have been modified to check for genesis or tolerate the presence of null. 
* NEEDS Attentive Review
* the signing weight of the genesis state is set to 0
* The startup sequence will adopt the config.txt when given a genesis state. 
* A bug was fixed in the AddressBookUtils class and parsing an address book can now tolerate config.txt. 
* a boolean flag is set to indicate if the address book was changed and the initial state needs to be updated with the new address book. 
* NOTE: after the AddressBookInitializer runs, the …

chore: allow starting from genesis state with null address book.

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/BalanceOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeHashOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PushZeroOperationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC721ContractInteractions.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java

I have three PRs that I'm trying to merge but there is a lot of flakyness. Here is the results I got:
**PR**: https://github.com/hashgraph/hedera-services/pull/10839
```
Attempt #1
ExtCodeHashOperationSuite » verifiesExistenceFAILED(Transaction fees '93545982' and '93562549' varied by more than 1 tinybar)
PushZeroOperationSuite » pushZeroHappyPathWorksFAILED(Transaction fees '93545982' and '93562549' varied by more than 1 tinybar)
ContractCallSuite » depositDeleteSuccessFAILED(Transaction fees '1101898159' and '1102102981' varied by more than 50000 tinybar)
ContractGetInfoSuite » getInfoWorksFAILED(Transaction fees '93545982' and '93562549' varied by more than 1 tinybar)
Attempt #2
SigningReqsSuite » autoRenewAccountCanUseLegacySigActivationIfConfiguredFAILED(Transaction …
```

test: Fix fuzzy match flakiness

---

hedera-node/infrastructure/docker/containers/local-node/network-node-base/Dockerfile

This PR updates the `Dockerfile` for local node in order to support Java 21
* Update Dockerfile
Fixes #10833 
**Checklist**

chore: update local node images to Java 21

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/SingleTransactionRecord.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/RecordTestData.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnpauseHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenPauseHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnpauseHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenAccountWipeRecordBuilder.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenBaseRecordBuilder.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenBurnRecordBuilder.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenCreateRecordBuilder.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenMintRecordBuilder.java

* Added `TokenBaseRecordBuilder`.
* Adjusted token record builders to extend `TokenBaseRecordBuilder`.
* Implemented new method in `SingleTransactionRecordBuilderImpl`.
* Added `TransactionOutputs` to `SingleTransactionRecord`, and filled in `SingleTransactionRecordBuilderImpl.build()`.
* Fixed unit tests where needed.
Resolves: #10820

feat: Add explicit `TokenType` to `SingleTransactionRecord`.

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableKVStateBase.java

Root cause is the [use of a ](http://java/com/hedera/node/app/spi/state/ReadableKVStateBase.java#L41)HashMap readCache[ in ](http://java/com/hedera/node/app/spi/state/ReadableKVStateBase.java#L41)ReadableKVStateBase results a race between (1) thread A that is trying to get an already-read key and (2) thread B that is trying to add a newly-read key and hence resizing the HashMap. This can lead to ISS. 
To solve the issue used `ConcurrentHashMap` or `SynchronizedMap` instead of `HashMap` for readCache. Since we want to store null values in readCache if the entity doesn't exist in state, and `ConcurrentHashMap` doesn't allow null values decided to use `SynchronizedMap`.
This will be changed to use a Marker object instead of null value in the future based on performance testing.

fix: (mod-service)Use concurrent read cache

---

platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/bytecode/SmartContractByteCodeMapKey.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/bytecode/SmartContractByteCodeMapValue.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/bytecode/SmartContractByteCodeMapValueSerializer.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/data/SmartContractMapKey.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/data/SmartContractMapValue.java

Fix summary: implemented `getSerializedSize(T)` method in SmartContractByteCodeMapValueSerializer.
Fixes: https://github.com/hashgraph/hedera-services/issues/10948

fix: 10948: JRS failure SmartContractByteCodeMapValueSerializer.getSerializedSize

---

hedera-node/infrastructure/docker/containers/local-node/network-node-base/Dockerfile

This PR cherry picks an update to `Dockerfile` definitions for `local-node` images of `hedera-services` to facilitate the migration to Java 21 and fix broken local node images for the 0.46 release.
Cherry pick #10834 
Fixes #10833
**Checklist**

chore: Update local-node Docker images to Java 21 (cherry pick #10834)

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java

fix: disable sync filtering

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOperations.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsNodeDeathReconnectTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsRestartTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsStateCreation.java

Fixes #11006 
- Extends the operations done during Restart and Reconnect tests in CI
- Adds a new suite `MixedOpsStateCreation` to create a local state that contains all entity types
The state created has 
```
2024-01-16 23:28:46.436 INFO  392  ServicesState - Platform state includes freeze time=2024-01-17T05:25:53.198681Z and last frozen=2024-01-17T05:25:53.198681Z
2024-01-16 23:28:46.445 INFO  177  ServicesState -   (@ 0) # NFTs               = 38
2024-01-16 23:28:46.446 INFO  181  ServicesState -   (@ 1) # token associations = 40
2024-01-16 23:28:46.446 INFO  185  ServicesState -   (@ 2) # topics             = 21
2024-01-16 23:28:46.446 INFO  186  ServicesState -   (@ 3) # blobs              = 132
2024-01-16 23:28:46.446 INFO  190  ServicesState -   (@ 4) # accounts/contracts = 812 …
```

chore: Extend Mixed operation submitted for Restart and Reconnect tests

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java

Remove a check which performs receiver signature checks during the precheck phase of `ContractCall` transactions.

chore: remove check which performs receiver signature check 

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/GrpcStarter.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/StateModule.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/GrpcStarterTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/StateModuleTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountRecords.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java

- Reduces friction in running mono-service `EVENT_STREAM_RECOVERY` by not trying to create a GUI console or start Netty.

chore: skip unwanted parts of init during mono event stream recovery

---

.github/workflows/node-zxcron-release-fsts-regression.yaml
.github/workflows/platform-zxcron-release-jrs-regression.yaml

Turning off release 0.45 regression tests
Closes #11039

ci: turning off release 0.45 regression

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java

- Fix intermittent failures like [this one](https://scans.gradle.com/s/fwddvtgvwx6cw/tests/task/:test-clients:itest/details/AllIntegrationTests/concurrentSpecs()%5B2%5D?top-execution=1) by using fixed missing contract numbers so that intrinsic gas cost doesn't vary with the number of binary zeros in the EVM payload.

chore: use fixed missing contract numbers in `Evm46ValidationSuite`

---

.github/workflows/support/scripts/generate-docker-artifact-baseline.sh
.github/workflows/zxc-verify-docker-build-determinism.yaml

- Addresses the determinism failure which occurred due to a change in the GitHub hosted runners.
- Temporarily removes usage of the GitHub hosted runners and introduces an additional version of the self-hosted runners.
- Updates the CI pipeline to ensure the same version of `dockerd` and `containerd` is used across all runners.

chore: ensure validation runners use the same docker & containerd versions

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java

Fixes https://github.com/hashgraph/hedera-services/issues/11083
Like mono-service [closes](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListener.java#L65) `multiStreams` when platform status changes to `FREEZE_COMPLETE`. Added similar logic in `Hedera` to close record streams.
Tested with restart test and the `BlockNumberValidator` added in https://github.com/hashgraph/hedera-services/pull/10944

fix: (mod-service)Fix block number closing issue on restart

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredWritableStates.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/MigrationContext.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/MigrationContextImpl.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVers.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java

- Quick-and-dirty change to ensure target `VirtualMap`'s are being regularly flushed to disk throughout the `TokenService` migration.
- Implementation details may need some refinement.

chore: copy and release periodically in `TokenService` migration

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java

This PR fix the ReadableKVStateBase.readCache is not properly synchronized
Fixes #10127

fix: use concurrent hashmap instead of synchroniztion for recordcache

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/LogsSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

This PR removes all direct usage of `snapshotMode()`. It should only be used during development. Once working, we want to use the annotation property `fuzzyMatch` to enable fuzzy matching.
Closes #11127

chore: Remove usage of snapshotMode in HAPI tests

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/InternalEventValidator.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/InternalEventValidatorTests.java

Fixes #11206
I broke the JRS tests with my last PR merged.  This fixes it.  I was missing some exceptional conditions on validation of birthRound being positive.

fix: allow negative birthRound event validation

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC20ContractInteractions.java

Add suggested test from https://github.com/hashgraph/hedera-services/issues/9424 :
An ERC-20 transferFrom() sending fungible value to an absent receiver address (outside long-zero range) generates a preceding child with a synthetic CryptoCreate and TransactionRecord identical that created by mono-service when it resolves to SUCCESS.
Fixes #
**Checklist**

test: add additional test for conditional records

---

settings.gradle.kts

Sets `hapiProtoVersion` to `v0.46.0`.

chore: bump HAPI proto version

---

.github/workflows/node-zxc-compile-application-code.yaml

- Addresses a behavioral change in the latest `snyk` CLI version which causes a blank JSON file to be written if there are no detections.
- Previously, the `snyk` CLI behavior was to not write a file at all if no detections were found.
- Closes #11266

fix: resolve Snyk Report workflow step failure

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateAddressBookStateCommand.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookValidator.java

This PR does the following: 
* adds a new pcli command: `pcli state validateAddressBook`
* adds a check for empty address book to the validation process. 
* fixes a description of a parameter in the `pcli state genesis` command. 
The intended use for  `pcli state validateAddressBook` is to check that a given config.txt will not generate errors during a software upgrade with the given state without needing to spin up a network to find that out.   Great for checking hand-crafted config.txt to make sure there are no problems. 
Fixes #11251 
If there is a better name for this tool, please suggest it. 
Manual testing performed.  
Example Commandline: 
```
pcli state validateAddressBook \
--load …
```

feat: pcli state validateAddressBook command

---

platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoMain.java
platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/TransactionSubmitter.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/ChatterCore.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTab2Stats.java

fix: Ui metrics name

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ParsedBucket.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java

Fix summary: applied `Bucket` changes from https://github.com/hashgraph/hedera-services/pull/11268 to `ParsedBucket` class.
Fixes: https://github.com/hashgraph/hedera-services/issues/11348

fix: 11348: The fix for 11231 doesn't cover ParsedBucket

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/output/OutputWire.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/wires/OutputWireTests.java

Adds an `orderedSolderTo()` method to `OutputWire`.
Fixes #11307
**Checklist**

chore: Add `orderedSolderTo` method to OutputWire

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ParsedBucket.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/11349 to `release/0.47` branch.
Fixes: https://github.com/hashgraph/hedera-services/issues/11363

fix: 11363: Backport the fix for 11348 to release 0.47

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStoreTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

We had a situation occur in mainnet this morning that resulted in a `FAIL_INVALID` instead of `INVALID_TOKEN_ID`. This PR fixes the bug by returning the first error status, instead of continuing to process other potential errors. 
Closes #11335

fix: Return invalid token even if expected decimals are present

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java

Fix summary: added a statement to print reconnect exceptions (if not expected) full stack traces during tests. It doesn't fix the problem, but helps debug it in the future.

fix: 11298: VirtualMapReconnectTest fails intermittently with path not in range log message

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStoreImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableTokenStoreImplTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenStore.java

This PR adds the warming of tokens to `CryptoTransfer` as tokens are also on-disk now.
Closes #11410

perf: Warm tokens as they are also on-disk now

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/charging/NarratedLedgerCharging.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/charging/NarratedLedgerChargingTest.java

fix the issue of Mismatched field counts (found but did not expect [transactionFee]) between expected receipt {
Transaction fee weren't appearing for duplicate transactions as part of the consensus transaction.
Fixes #11402

fix: transaction fee in record for mono code

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java

Change the catch-clause in MethodBase.invoke() so that it logs a message that triggers an alert in production with:
"Possibly CATASTROPHIC failure while handling a call and running the ingest workflow."
Fixes #10904 
**Checklist**

fix: 10904 Log catastrophic failures during ingest 

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncProtocol.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncStatusChecker.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/SyncMetrics.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/protocol/SyncProtocolTests.java

- this PR is the short term solution mentioned in #11418

feat: Check platform status before syncing

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderJdb.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileReaderPbjTest.java

Optimized `DataFileReaderPbj.leaseFileChannel` method  to make sure that it returns an index of the least used file channel at the moment
Fixes #11328 
**Checklist**

fix: 11328 Optimized `DataFileReaderPbj.leaseFileChannel` method 

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV046.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV046Test.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/CustomSelfDestructOperation.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomSelfDestructOperationTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java

Cherry pick #11243 static call with selfdestruct to system account between 0.0.751  and 0.0.999 results in FAIL_INVALID (#11243)
Fixes #
**Checklist**

chore: cherry-pick static call with selfdestruct to system account between 0.0.751  and 0.0.999 results in FAIL_INVALID

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java

Service names are prepended with "proto.". This PR replaces the '.' as it is not accepted in metric names.

fix: Fix service names for metrics

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/EventSignatureValidatorTests.java

Updates the unit test to ensure that the `EventSignatureValidator` is dumping ancient events under both ancient modes. 
Fixes #11079 
Only the unit test needed to be updated.   Instead of altering the setup, I created a new validator where the platform context is updated to generate the different ancient modes. 
**Checklist**

refactor: EventSignatureValidator uses AncientMode

---

platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java

fix: SignedStateFileManagerTests 

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/map/MapTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java

Temporary disabled `VirtualPipelineTests.flushThrottle` stabilize test pipeline
Relates to #11496

fix: 11496 Temporary disabled `VirtualPipelineTests.flushThrottle` 

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts

To chek if this decreases the likelihood of these test environment errors to appear:
https://scans.gradle.com/s/siwhcv3vmntkw/tests/overview?outcome=FAILED
**Checklist**

build: add back '-XX:ActiveProcessorCount=6' to 'eet'

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetTracker.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetTrackerTests.java

This PR makes the final changes to verify that the EventCreator and related classes can handle birthRound for AncientThreshold.   Unit tests are parameterized for both modes. 
Fixes #10020 
**Checklist**

refactor: EventCreator compatible with AncientMode

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapLargeReconnectTest.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTest.java

Temporary disables the following tests
```
VirtualMapReconnectTest#teacherAbortsReconnectOnFirstInternal
multipleAbortedReconnectsCanSucceed
```
Relates to #11507 
There will a follow-up fixing the tests.

fix: 11507 Temporary disabled tests to stabilize pipeline

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java

fix rbs calculation to use hashset with unit token types
Fixes #11486

fix: rbs calculation in modularize code

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTest.java

Temporary disabled a test `VirtualMapReconnectTest.learnerAbortsReconnectHalfWayThrough` to stabilize the test pipeline
Relates to #11507 
These tests will be fixed later
**Checklist**

fix: 11507 Temporary disabled a test 

---

platform-sdk/swirlds-base/src/test/java/com/swirlds/base/test/internal/fixtures/ConcurrentTestSupportTest.java

Reduce the number of threads consumed by the test and check more spaced timeouts.
Fixes #11540

fix: 11540-ConcurrentTestSupportTest

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/ClassicCreatesCall.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/create/ClassicCreatesCallTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
hedera-node/test-clients/src/rcdiff/java/com/hedera/services/rcdiff/RcDiff.java

Fix both issues
Mismatched field counts (expected but not find [amount]) between expected contractID {
Mismatched values, expected '<ByteString@64e92d61 size=48 contents="\301M\020\254\fA\277\354\r\360m\200\375\204\220,tRy\201\363G\r\3764>:\210\373\261\177a\032\357\206\323\032\350%\343Z\002\363\301\344\343\215*">', got '<ByteString@7882c44a size=48 contents="\370*\355e\224j=-c\275&L\362\016\200\324\2761;\313\001\366\312\235\004 Ru>#\311N\270Ng:\2759\353\372u\361d\255\250dYq">' - Matching field 'transactionHash' ==> expected: <<ByteString@64e92d61 size=48 contents="\301M\020\254\fA\277\354\r\360m\200\375\204\220,tRy\201\363G\r\3764>:\210\373\261\177a\032\357\206\323\032\350%\343Z\002\363\301\344\343\215*">> but was: <<ByteString@7882c44a size=48 …

fix: fee charge token create tx and also transaction hashing

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java

closes #11544 
Observed test flake related to not enough signatures being collected, known issue.

fix: reduce sync permit count (#11545)

---

platform-sdk/swirlds-jasperdb/src/hammer/java/com/swirlds/merkledb/files/CloseFlushTest.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/DataSourceValidatorTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/RecordAccessorImplTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
platform-sdk/swirlds-virtualmap/src/testFixtures/java/com/swirlds/virtualmap/test/fixtures/InMemoryDataSource.java

Added `isReconnectContext` flag to handle node removal properly in the reconnect context.
Misc:
- Added `@Tag(TIMING_SENSITIVE)` to `dirtyDeletedLeavesBetweenFlushes` and `snapshotRestoreIndex`.
- Added `isReconnectContext` parameter to InMemoryDataSource.
- Added eventual assert for `MerkleDbTest.shutdownTest`.
- Refactored tests to automatically close the datasource.
Fixes #11561 , relates to #11498 
This PR has the same changes as https://github.com/hashgraph/hedera-services/pull/11500
**Checklist**

fix: 11561 Added `isReconnectContext` flag to handle node removal properly in the reconnect context.

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/CallOutcome.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/CallOutcomeTest.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/benchmark/BenchmarkAccount.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/benchmark/BenchmarkKey.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/dummy/DummyFCQueueElement.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/dummy/FCMapComplexValue.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/dummy/FCQValue.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/dummy/SimpleValue.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/pta/MapKey.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/pta/MerkleMapKey.java
platform-sdk/swirlds-merkle/src/testFixtures/java/com/swirlds/merkle/test/fixtures/map/pta/TransactionRecord.java

- Closes #11277 
- Follow mono-service pattern of externalizing a `contractCallResult` for an aborted transaction only for a top-level `EthereumTransaction`.
- And do not externalize a recipient id (i.e. in `transactionRecord#receipt#contractID`) for an aborted transaction.
- Change some test fixture class ids so we don't have duplicate ids on the default classpath scanned by PCLI.

chore: match mono-service `contractCallResult`/`contractID` externalization

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImpl.java

- Closes #11650 
- It is not safe to modify a mutable `List` member of a PBJ object wrapped in an `InMemoryValue` when that PBJ object is fetched via `.get()`. (The same object might be in-use by a hashing thread.)

chore: don't modify an `InMemoryValue#List` in-place

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/LearnerPushReceiveThread.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherSendingThread.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherSubtree.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/CustomReconnectRoot.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/LearnerPushReceiveMerkleTreeView.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/LearnerTreeView.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/TeacherPushReceiveMerkleTreeView.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/views/TeacherTreeView.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/dummy/DummyCustomReconnectRoot.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/dummy/DummyLearnerPushReceiveMerkleTreeView.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/dummy/DummyTeacherPushReceiveMerkleTreeView.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/LaggingLearningSynchronizer.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/LaggingTeachingSynchronizer.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenVirtualMapTeacherView.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/FakeVirtualRootNode.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTest.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/LearnerPushReceiveVirtualTreeView.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/TeacherPushReceiveVirtualTreeView.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java

The first PR to address https://github.com/hashgraph/hedera-services/issues/11403, more to come. In this PR:
* Added a new method to `LearnerTreeView` to start learner threads in a given work group
* A similar method is added to `TeacherTreeView`
* Both `StandardTeacherTreeView` (renamed to `TeacherPushReceiveMerkleTreeView`) and `VirtualTeacherTreeView` (renamed to `TeacherPushReceiveVirtualTreeView`) create a pair of teacher threads in this method, same as what was done previously. In the future a different thread will be created here
* Similarly, learner views (also renamed) create a single learner thread (renamed to `LearnerPushReceiveThread`), unchanged from the current implementation
* `LearningSynchronizer` and `TeachingSynchronizer` are now pretty straightforward: create a work …

feat: 11436: Provide a way to have different reconnect teacher/learner threads implementations

---

platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/MerkleTestUtils.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/PairedStreams.java

This PR prevents possible failures in attempt of closing `PairedStreams` object which was previously closed. If `close` method throws an expection in this case the test shouldn't fail.
Fixes #11715

fix: 11715 Properly handle closed `PairedStreams` object

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java

- During BBM, add `alias-to-id` mappings for _both_ the in-state alias (which could be a "key alias") and any implied EVM address.
- When checking if an EVM address is the "priority" address for an account, also detect the case the account's key alias maps to the given EVM address.

fix: (mod) fix alias management

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java

This PR fixed synchronization issues stemming from the fact that `saveRecords` method is no longer called from a single thread. 
Fixes #11750 
**Checklist**

fix: 11750 Fixed synchronization in   `BreakableDataSource.saveRecords`

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/SimpleFreezeOnly.java

Sometimes it takes longer for service app to handle freeze transaction and put platform enter sleep mode
Fixes #11788 
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1709097277261679
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1709099820470689

fix: wait longer for freeze transaction to be handled

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/SpanMapManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/span/SpanMapManagerTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleSystemContractOperations.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/Erc20TransfersCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc20TransfersCallTest.java

- Closes #11630 
- Fixes #11778
- Fix two small mono-service issues that we have no reason to reproduce in mod-service:
1. Use the correct resource prices for scheduled `CryptoTransfer`'s that trigger custom fee payments.
2. Set the receiver log topic in an ERC-20 `TRANSFER_EVENT` even when the transferred amount is `0`.
- Fix mod-service to only emit ERC-20 events on `SUCCESS`; and to still distinguish the logical sender and receiver when the amount is `0`.

fix: fix ERC-20 log events and custom fee calculations

---

hedera-dependency-versions/build.gradle.kts
settings.gradle.kts

Upgrading PBJ dependency to 0.7.20 in order to incorporate https://github.com/hashgraph/pbj/issues/208 fixed at https://github.com/hashgraph/pbj/pull/210
The fix introduces a maximum size for repeated/length-encoded fields that PBJ parses successfully. The parsing now errors out if PBJ encounters a field larger than the defined maximum size.
The PBJ 0.7.20 is already published to Maven: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
Fixes #https://github.com/hashgraph/pbj/issues/208
Unit tests in hedera-services pass.
**Checklist**

feat: pbj-208: upgrade PBJ dependency to 0.7.20

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.benchmark-conventions.gradle.kts

1) Allow running a single test from command line using `-PjmhTests`
2) Use the [JMH IntelliJ plugin](https://plugins.jetbrains.com/plugin/7529-jmh-java-microbenchmark-harness) to run from IntelliJ 
Fixes https://github.com/hashgraph/hedera-services/issues/11863
**Checklist**

build: support running selected JMH tests

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/internal/ConcurrentTask.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/tasks/AbstractTask.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java

VirtualHasher performance improvements:
- updated chunk height to 3
- introduced `complete` method to `ChunkHashTask` to handle clean nodes optimally
VirtualHasher performance improvements:
- updated chunk height to 3
- introduced `complete` method to `ChunkHashTask` to handle clean nodes optimally
Fixes #11636

fix: 11636 VirtualHasher performance improvements

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/FutureEventBuffer.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/FutureEventBufferTests.java

Related to #11872 
Needs to be back ported to `release/0.48`

fix: bug in future event buffer

---

platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapLargeReconnectTest.java

This PR temporarily disables  `VirtualMapLargeReconnectTest#multipleAbortedReconnectsCanSucceed`
Relates to #11507

fix: 11507 Temporary disabled test to prevent non-deterministic failures.

---

hedera-dependency-versions/build.gradle.kts
settings.gradle.kts

PBJ has increased the `maxSize` limit when parsing models from 21K to 2M in PBJ v0.7.22.
As discovered at https://github.com/hashgraph/pbj/issues/221 , EVM bytecode can be larger than 21K. And it was suggested in an off-line conversation that the bytecode can be up to 1M in size. So we've increased the currently hard-coded `maxSize` limit in PBJ to 2M to be on the safe size.
Fixes #https://github.com/hashgraph/pbj/issues/221
The PBJ v0.7.22 is released: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
**Checklist**

fix: pbj-221: upgrade PBJ dependency to 0.7.22

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java

This PR removes the explicit setup of fuzzy matching and replaces it with the default implementation. This allows us to control fuzzy matching globally.
Fixes #11938

chore: Remove explicit fuzzy matching

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java

Fix summary:
* Default value for `hashesRamToDiskThreshold` MerkleDb config is set to 0
* On nodes with this threshold set to 0 in MerkleDb metadata, it will result in correct threshold value used. All hashes will be loaded from disk
* On nodes with a different threshold value, the overridden value from loaded MerkleDb metadata will be used, the default will be ignored
Co-authored-by: Oleg Mazurov <oleg.mazurov@swirldslabs.com>
Fixes: https://github.com/hashgraph/hedera-services/issues/11964

fix: 11964: Hashes RAM to disk threshold is incorrect for legacy MerkleDb tables, fileStore and smartContractIterableKvStore

---

platform-sdk/swirlds-platform-core/build.gradle.kts
platform-sdk/swirlds-platform-core/src/jmh/java/com/swirlds/platform/core/jmh/ConsensusBenchmark.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ThreadSafeConsensusInfo.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/GenerateConsensus.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/framework/ConsensusTestNode.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/framework/ConsensusTestOrchestrator.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/framework/OrchestratorBuilder.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/framework/TestInput.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/gui/TestGuiSource.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/cli/EventStreamReportingToolTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/cli/EventStreamSingleFileRepairTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestArgs.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestParams.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestRunner.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/IntakeAndConsensusTests.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/gui/HashgraphGuiTest.java

This PR passes the `PlatformContext` to configure `ConsensusImpl` and related tests.  Isolating this work to this PR will make the PR for consensus supporting birthRound based ancient thresholds less cluttered. 
Fixes #11953 
No functionality should have changed.  
**Checklist**

refactor: PlatformContext to configure Consensus

---

hedera-dependency-versions/build.gradle.kts
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerConcurrent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerSingleThreaded.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/impl/producers/StreamFileProducerTest.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/codec/FileServiceStateTranslatorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/hevm/HederaEvmTransactionResultTest.java
settings.gradle.kts

This fix upgrades the PBJ dependency to v0.7.23 which contains a new implementation for a `null Bytes and Strings` fix where PBJ continues to accept `null` as an argument to model and Builder constructors, but internally ensures that model fields of these types are never `null` and instead get assigned default values (`Bytes.EMPTY` and `""` respectively), so as to prevent any NPEs when serializing such models and be compatible with Google Protobuf specification: https://github.com/hashgraph/pbj/pull/224
Fixes #https://github.com/hashgraph/pbj/issues/220
PBJ v0.7.23 is released: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
**Checklist**

fix: pbj-220: upgrade PBJ dependency to 0.7.23

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKey.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKeySerializer.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/map/MapTest.java

Fix summary: extended the original fix for #11498 to cover generic (object) keys in addition to long keys. A new unit test (actually, a regression test) is provided.
Fixes: https://github.com/hashgraph/hedera-services/issues/11996

fix: 11996: The fix for #11498 doesn't cover generic object keys

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ReadableScheduleStoreImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtilityTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleTestBase.java
hedera-node/hedera-schedule-service/src/main/java/com/hedera/node/app/service/schedule/ReadableScheduleStore.java

Update the map in state for SCHEDULES_BY_EQUALITY_KEY to use Bytes instead of String for modularized code.
Fixes #11971

fix: use Bytes instead of String for SCHEDULES_BY_EQUALITY_KEY

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java

- Closes #12007 
- When building synthetic `CryptoCreate` records, use a `Transaction` with `signedTransactionBytes` created via `transactionWith()` factory, instead of deprecated `body()` field.

fix: use `signedTransactionBytes` in synthetic record builders

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/ExpandedSignaturePair.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureExpanderImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureExpanderImplTest.java

fix: ensure ECDSA `ExpandedSigPair` always has EVM alias

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java

fix: use `signedTxnBytes` in synthetic creation records

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKey.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKeySerializer.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/map/MapTest.java

Fix summary: direct backport of #11998 to `release/0.47` branch.
Fixes: https://github.com/hashgraph/hedera-services/issues/11997

fix: 11997: Backport the fix for 11996 to release 0.47

---

platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/ConcurrentNodeStatusTrackerTests.java

Increased `future` timeout to 1 second to stabilize the test. 
Fixes #12000 
**Checklist**

fix: 12000 Increased timeout for `ConcurrentNodeStatusTrackerTests.setsBoundValue`

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKey.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestObjectKeySerializer.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/map/MapTest.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/11998 to `release/0.48` branch.
Fixes: https://github.com/hashgraph/hedera-services/issues/12004

fix: 12004: Backport the fix for 11996 to release 0.48

---

hedera-dependency-versions/build.gradle.kts
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerConcurrent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerSingleThreaded.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v7/BlockRecordFormatV7.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/TestLongCodec.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/TestStringCodec.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/impl/producers/StreamFileProducerTest.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/codecs/EntityNumCodec.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/codec/FileServiceStateTranslatorTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/CodecFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/MonoMapCodecAdapter.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/codec/MonoSpecialFilesAdapterCodec.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/EntityNumCodec.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/MonoContextAdapterCodec.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/MonoRunningHashesAdapterCodec.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/hevm/HederaEvmTransactionResultTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/serdes/EntityNumCodec.java
settings.gradle.kts

Back-porting PBJ enhancements introduced in versions up to v0.8.1, specifically:
1. `maxSize` where PBJ limits the maximum size of a message that it would parse w/o exceptions
2. `null` where PBJ continues to accept `null` values for `Bytes` and `String` types as input to model and Builder constructors, but internally ensures that all model fields of these types are assigned default values instead of the `null` - `Bytes.EMPTY` and `""` respectively
3. `maxDepth` where PBJ allows clients to limit the maximum depth of nested messages that it would parse.
Essentially, I'm cherry-picking the following two commits/pull-requests from `develop`:
* https://github.com/hashgraph/hedera-services/commit/173f419619af3a289d2be114568e3665d0416827 - …

feat(pbj): upgrade PBJ dependency to 0.8.1

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerConcurrent.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/StreamFileProducerSingleThreaded.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java

As suggested at https://github.com/hashgraph/hedera-services/pull/12003 , I'm removing redundant `null` checks for the `runningHash()` values because with the latest PBJ (v0.7.23+), this field of type `Bytes` can never be `null`.
Fixes #12031
None.
**Checklist**

fix: remove null checks for non-nullable runningHash()

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/GenesisAccountRecordBuilder.java

- Closes #12037 
- Set `SUCCESS` in synth record receipts.

fix: set `SUCCESS` status in genesis records

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ReadableScheduleStoreImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImpl.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtilityTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/ScheduleTestBase.java
hedera-node/hedera-schedule-service/src/main/java/com/hedera/node/app/service/schedule/ReadableScheduleStore.java

Cherry pick to develop of PR #11995
Fixes #11971

fix: use Bytes instead of String for SCHEDULES_BY_EQUALITY_KEY (#11995)

---

hedera-dependency-versions/build.gradle.kts
settings.gradle.kts

This is a direct back-port of https://github.com/hashgraph/hedera-services/pull/12045 to release `0.48`.
I'm upgrading the PBJ dependency to v0.8.3 to introduce a Enum hashCode() implementation that is stable between runs/different VMs.
Per @netopyr suggestion, I'm opening this PR for `0.48` before the above PR for `develop` is reviewed/merged. The reason is the time it takes to pass all the PR checks.
Fixes #https://github.com/hashgraph/pbj/issues/227
PBJ v0.8.3 is released: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
**Checklist**

fix(pbj): stabilize hashCode() for Enums

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java

Fix summary: direct forwardport of https://github.com/hashgraph/hedera-services/pull/11967 to `release/0.48`.
Fixes: https://github.com/hashgraph/hedera-services/issues/12071

fix: 12071: Forwardport the fix for 11964 to release 0.48

---

.github/workflows/node-zxc-build-release-artifact.yaml

- Resolves an issue which results in a improperly formatted file name due to not using the properly escaped branch name.
- Closes #12087

fix(ci): issue with improperly generated artifact file names

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java
settings.gradle.kts

- Closes #12090 
- Populate the `BlockRecordWriterV6#sidecarMetadata` field _before_ writing the corresponding `RecordStreamFile` "footer".
- Bump HAPI proto version for record stream to `0.48.0`.

fix: create sidecar metadata before writing `RecordStreamFile` footer

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java

Fixes https://github.com/hashgraph/hedera-services/issues/11582
When there are no applicable schemas if the version to be migrated is same, we apply the last registered schema. In this scenario, the `ApplicationType` should be considered as `RESTART_ONLY`.
If it is considered as `MIGRATE_THEN_RESTART`, it could lead to ISS if node does a auto-reconnect since the `EntityId` service commits a different EntityId number from state.

fix: (mod-service) Fix a case for identifying `RESTART` scenario

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/SidecarWriterV6.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/impl/producers/formats/v6/BlockRecordWriterV6Test.java

This is the cherry-pick of #12114.
Closes #12113

fix: wire `HashingOutputStream` into sidecar writing (#12114)

---

hedera-node/test-clients/src/eet/java/EndToEndTests.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFractionalFees.java
hedera-node/test-clients/src/test/java/EndToEndPackageRunner.java

Custom fees can be set to a token during token creation. Then when we perform a transfer on the token, fee related business logic is executed for proper payment of the fee collector. With this task we would add additional test coverage to validate all cases behave correctly for FRACTIONAL_FEE plus MIXED_SCENARIO.
Add additional suites for FRACTIONAL_FEE plus MIXED_SCENARIO #11832
Fixes #
#11832

feat: Add additional suites for FRACTIONAL_FEE plus MIXED_SCENARIO

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/ServicesRegistryImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/DependencyMigrationTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java

- Closes #12217 
- Only use a `pre` semver part if it is an `alpha-X` literal.
- Ignore all `build` parts from environment; use **only** if `hedera.config.version` is overridden to non-zero value.

fix: make `HederaSoftwareVersion` match Services upgrade semantics

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/services/ServicesRegistryImplTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/DependencyMigrationTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/AppTestBase.java
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java

Cherry-pick : https://github.com/hashgraph/hedera-services/pull/12228

fix: (cherry-pick) make `HederaSoftwareVersion` match Services upgrade semantics

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/StateDumper.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/accounts/AccountDumpUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/ByteArrayAsKey.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/Contract.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/ContractBytecodesDumpUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/ContractUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/Contracts.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/contracts/Validity.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/files/FileId.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/files/FilesDumpUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/files/HederaFile.java

Cherry pick of #11523 
Fixes #10994

feat: Cherry-pick: Enhance contract bytecode dumper to handle modular representation

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/LearnerThread.java

To assist with debugging https://github.com/hashgraph/hedera-services/issues/12046 , I'm adding more logging to the Learner code to better understand where it could possibly be stuck, if at all, when the test failure described in the issue occurs.
Helps debug #12046 
Just adding a few more non-intrusive (from performance and logs noise perspectives) logs. We'll check them when that test fails again.
**Checklist**

chore(reconnect): add more logs to Learner

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

`TokenUpdate` can throw `NullPointerException`. This PR adds the necessary checks.
Fixes #12205
**Checklist**

fix: Add null check for autorenew account update

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EvmTokenUtil.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java

- Closes #11916 
- Fix a strange construct in `EvmTokenUtil` to answer a `getTokenInfo()` system call to either use the token's default KYC status if it has a KYC key; or `true` if it does not.
- Eliminate a use of `protoc`-generated types in mod `TokenTupleUtils`.
- Print hexed form of `ByteString`s when displaying diffs instead of their octet encoding.

fix: KYC default status is true without KYC key

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AssessmentResult.java

- Closes #12300 
- Replaces `Map.copyOf()` with `LinkedHashMap::new`, as the `ImmutableCollections.MapN` returned by the former has an [intentionally random iterator](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/ImmutableCollections.java#L1266). 🤯 
* This made the order of effective payer numbers for a fractional fee with multiple receivers non-deterministic.

fix: deterministic order of effective payer numbers

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/consensus/TopicCreateTransitionLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/consensus/TopicUpdateTransitionLogic.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/consensus/MerkleTopicUpdateTransitionLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/consensus/TopicCreateTransitionLogicTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AssessmentResult.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java

- Cherry-pick #12317 
- Closes #12251 by allowing [this transaction](https://hashscan.io/mainnet/transaction/1710257012.152064484) to use the expected contract as auto-renew account for a `createToken()` HTS call.
- Avoids adding another pointless special case to auto-renew account validation by also allowing contracts and topics to use contract auto-renew accounts.

fix: apply consistent auto-renew account policy

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmStaticTransactionFactory.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmStaticTransactionFactoryTest.java

Fixes an issue where modularized code was erroring when a CONTRACT_CALL_LOCAL query had less than the minimum amount of gas required for CONTRACT_CALL transactions.
Fixes #12313

fix: ContractCallLocal INSUFFICIENT_GAS ERROR

---

hedera-node/hapi/build.gradle.kts

We created a branch in the protobufs repo – `v0.48.3-release` – so we can depend on a fixed commit instead of using `main`. This PR updates this release branch to use the protobufs release branch. 
(Note: done because the 'tag' part of `branchOrTag` in the build file seems to be broken)

chore: rely on protobuf release 48 branch instead of main

---

hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountInfoHandlerTest.java

This PR disables the listing of token associations in `AccountInfo`, `ContractInfo`, and `AccountBalance` as defined in [HIP-367](https://hips.hedera.com/hip/hip-367)
Fixes #12291

feat: Disable token associations in AccountInfo, ContractInfo, and AccountBalance

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/ReconnectBench.java

Adding `BenchmarkMetrics.register` calls for both the teacher and the learner maps before starting each reconnect invocation. This is similar to what e.g. the VirtualMapBench does when it calls `register` in the `createMap` after the map has been restored.
Fixes #11745
Head from BenchmarkMetrics.csv:
```
time,memTot,memFree,directMem,cpuLoadProc,openFileDesc,ds_compactions_level_0_hashesSavedSpaceMb_learner,ds_compactions_level_0_hashesSavedSpaceMb_teacher,ds_compactions_level_0_hashesTimeMs_learner,ds_compactions_level_0_hashesTimeMs_teacher,ds_compactions_level_0_leafKeysSavedSpaceMb_learner,ds_compactions_level_0_leafKeysSavedSpaceMb_teacher,ds_compactions_level_0_leafKeysTimeMs_learner,ds_compactions_level_0_leafKeysTimeMs_ …
```

feat(ReconnectBench): generate .csv with metrics

---

.github/workflows/node-zxc-compile-application-code.yaml

One or two line summary of what this PR does and why it is needed, followed by a list
of changes in imperative, present tense for use in the commit message or changelog. Example:
This PR modifies .github/workflows/node-zxc-compile-application-code.yaml in order to address limiting Github API calls when publishing results.
- Reverted actionite/publish-unit-test-result-action to EnricoMi/publish-unit-test-result-action
- updated publish-unit-test-result action from v2.3.0 to v2.16.1
Fixes #12403 
- [unit test results](https://github.com/hashgraph/hedera-services/actions/runs/8456218556/job/23165475368)
**Checklist**

ci: Reverted publish-unit-test-result-action from actionite fork to EnricoMi

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenMetadataSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java

Fixes #12387 
- Fixes signing requirements for TokenUpdate to require either adminKey or metadataKey, when updating `metadata` field
- Also fixes signing requirements for expiry only update. Previously it failed with `INVALID_SIGNATURE` if there is no adminKey signature for expiry only update operation

fix: Fix signing requirements for updating metadata on Token

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/CongestionThrottleService.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/InitialModServiceAdminSchema.java

This PR also includes a little cleanup to keep the network context out of the admin schema.
closes #12281

fix: Clean up leaked virtual maps after migration

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbStatisticsTest.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualMapStatistics.java

Fix summary: `.` are replaced with `_` in generated virtual map and data source metric names.
Fixes: https://github.com/hashgraph/hedera-services/issues/12388

fix: 12388: VirtualMap / DataSource metrics should not contain certain chars in the names

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/GrantApprovalTranslator.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCallTest.java

- Closes #12267 
- Treat an `approve(address, amount)` call to the HTS system contract as an invalid operation when `amount` is outside range of a 64-bit `long`.
* This is both backward-compatible, and more in line with the overall convention that if an `HtsCallAttempt` cannot be translated into a plausible `TransactionBody`, it halts as an invalid operation.

fix: treat an out-of-range allowance amount as an invalid op

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java

This PR addresses possible data race that can happen after 0.47 -> 0.48 migration. 
Fixes #12466

fix: 12466 Fixed NPE intermitently occurring after 0.47 -> 0.48 migration

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslator.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslatorTest.java

- Closes #12427 
- Migrates last block number to `(current - 1)` from mono state.

fix: block no migration

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/CodeOrderResultFactory.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManager.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManagerTest.java

- Closes #11881
- Closes #11878
- Reduce diff testing surface area by switching mono-service behavior to mod-service on `release/0.48` in two cases:
1. Use `INVALID_ACCOUNT_ID` instead of `ACCOUNT_ID_DOES_NOT_EXIST` when a `CryptoTransfer` encounters a missing account id.
2. Reclaim an entity id when an `EthereumTransaction` lazy-create fails due to `INSUFFICIENT_GAS`.
➡️ This PR *does not* need to be cherry-picked to `develop`.

chore: reclaim EthTx lazy-create id on INSUFFICIENT_GAS; use INVALID_ACCOUNT_ID

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java

- Closes #12290 
- Mostly for mono-service fidelity, but also for reasons of intuitive priority, check payer solvency before verifying other-party signatures.

fix: verify payer solvency before verifying non-payer sigs

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/SystemContractGasCalculator.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/SystemContractGasCalculatorTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java

- Closes #12266 
- For mono-service fidelity, wait to divide by gas price until _after_ summing the tinybar costs of the synthetic create and update transactions.

chore: divide summed lazy-create cost by gas price

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKvStateMetrics.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/WritableKVStateStack.java

This PR ensure metrics are also setup for `WritableKVStateStack`
Fixes #12485

fix: Setup metrics for WritableKVStateStack

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java

- Remove a `createTopic()` call that did not specify an admin key along with its auto-renew account (for historical reasons, only topics with an admin key can set auto-renew accounts).

fix: remove spurious `createTopic()` call

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/ComponentWiring.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/SchedulerLabel.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/ComponentWiringTests.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulers.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/generate-platform-diagram.sh

closes #12503 
There was a minor change to the wiring diagram (`internalEventValidator` become `InternalEventValidator`), but I did not merge that file to avoid merge conflicts with other branches that are currently open.

feat: construct schedulers automatically

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/checks/VerifyAddLiveHashNotSupported.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/checks/VerifyGetTokenNftInfosNotSupported.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/checks/VerifyUserFreezeNotAuthorized.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java

- Avoid `BUSY` for unsupported and unauthorized txns at ingest.

chore: cherry pick 12547

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/ReturnTypes.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java

- Closes #12538 
- Use `0` instead of `-1` for an unset auto-renew period for backward compatibility.
- Fix `struct Expiry` ABI types to `int64` instead of `uint32` c.f. the published ABI [here](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L69).

fix: use `0` for missing auto-renew period in `getTokenInfo()` result

---

hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java

- Closes #12516 
- Ensure schedules are created with a provided expiration second, if given; this is part of the schedule's "fingerprint" used in detecting identical schedules.

fix: set provided expiry on new schedule

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java

Fixes https://github.com/hashgraph/hedera-services/issues/12565
Add `pureChecks()` to `ContractDeleteHandler` to ensure mandatory `contractID` is provided.

fix: Add pure check to ContractDeleteHandler

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java

This PR fixes `TokenAssociateToAccountHandler`, which had a `pureChecks()` method, but it did not override the standard version.
Fixes #12566

fix: Enable pureChecks in TokenAssociateToAccountHandler

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java

This PR changes the error handling of CryptoCreate slightly. When no alias is provided, we want to return REQUIRED_KEY instead of INVALID_ALIAS_KEY.
Fixes https://github.com/hashgraph/hedera-services/issues/12563

fix: Return REQUIRED_KEY in CryptoCreate if no alias is used

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/ReturnTypes.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java

- Closes #12538 
- Cherry-pick #12576

fix: use 0 for unset auto-renew period

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/scheduledtransactions/ScheduledTransactionsDumpUtils.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/scheduledtransactions/ScheduledTransactionsDumpUtils.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImpl.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImplTest.java

Related to https://github.com/hashgraph/hedera-services/issues/12334
- Fixes duplicated schedules list in SchedulesByEquality Map
- Fixes dumpers to dump schedules

fix: Fix schedules during replay

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

This fix supposed to provide the right response code when the account ID is not available during the crypto update
Fixes #12571

fix: unit test and add the right response code

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java

Fixes typo which resulted in Hapi test failing.
Fixes #12417 
**Checklist**

fix: failing test due to typo for NegativeHtsTransferFrom contract 

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/records/RecordCache.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java

- Closes #12652 
- Fix `DeduplicationCache` comparator to include `nonce`.
- Remove some misleading comments in `RecordCacheImpl`.
- Update receipt and record queries to fetch a specific child by `TransactionID` nonce.

fix: support receipt/record queries with nonce

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/TransactionHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemDeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemUndeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoAddLiveHashHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteLiveHashHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnpauseHandler.java
hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/UtilPrngHandler.java
hedera-node/hedera-util-service-impl/src/main/java/module-info.java
hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/handlers/UtilPrngHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java

TransactionHandler had a default empty implementation of pureChecks, which meant that all inheriting classes could optionally implement pureChecks or accept the empty default. This PR removes the default empty implementation and adds overrides for all implementing classes which previously lacked one.
Fixes #12644

fix: make pureChecks required in all handlers

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/ChildFinalizeContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TriggeredFinalizeContext.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeChildRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/ChildFinalizeContext.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

- Fixes #12667 
- Use `BigInteger` for net-zero adjustment calculations in `CryptoTransfer` pure checks.
- Use exact math for all custom fee summing.
- During record finalization,
1. Use exact math for summing net balance adjustments.
2. Add an extra safety check in record finalization for any balance that exceeds total hbar supply.

fix: use exact math for all summed balances

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/ReconnectBench.java
platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/reconnect/MerkleBenchmarkUtils.java

Fix summary: the existing `ReconnectBench` is enhanced, so it uses a merkle tree with multiple virtual maps rather than one. `mapCount` benchmark param, defaults to 1, can be used to set the number of maps.
Fixes: https://github.com/hashgraph/hedera-services/issues/12693

fix: 12693: Enhance ReconnectBench to reconnect merkle trees with multiple virtual maps

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/checks/VerifyUserFreezeNotAuthorized.java

Cherry-pick of #12647 
Closes #12646

fix: Cherry-pick: Return NOT_SUPPORTED in assertThrottlingPreconditions()

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseCryptoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DissociatePrecompileSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java

Fixes #11306 
Fixes #3629 
Fixes #3630 
- Add tests for validating max-automatic_associations in contracts; 
- Added more pureChecks in `TokenAssociateHandler` and `TokenDissociateHandler` to fail early for invalid accountID and tokenID

fix: Add EETs and pureChecks in few handlers

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/SigControl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenAssociate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java

This PR adds HAPI tests to `TokenAssociationSpec` which check invalid transactions are handled correctly.
Fixes #12675

chore: Implement un-HAPI tests for TokenAssociateToAccountHandler

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java

The failing test contained several errors, and the returned error code depends on the order of checks, which is not guaranteed. This PR ensures the test causes only the one error that is being checked, making it independent of the order.
Fixes #12718

chore: Improve HAPI test to contain only checked error

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/reconnect/MerkleBenchmarkUtils.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/pool/StandardWorkGroup.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/pool/StandardWorkGroupTest.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/merkle/util/MerkleTestUtils.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapLargeReconnectTest.java
platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java

Enabled logging exceptions processed by StandardWorkGroup into System.err. This should help with the tests failure investigations. Before this change the exceptions were just not logged at all in the testing context. 
Misc: Re-enabled tests in VirtualMapLargeReconnectTest
Related to #11507 
This change is not supposed to affect production code in any way. It was added for testing purposes only.

fix: 11507 Enabled logging exceptions processed by StandardWorkGroup into System.err.

---

hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/keys/SigControl.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenAssociate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java

Cherry-pick of #12698 
Closes #12717

chore: Cherry-pick: Implement un-HAPI tests for TokenAssociateToAccountHandler

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/CacheWarmer.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableStateTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java

* eliminated creating a `VirtualThread` for each `VirtualMap.warm()` call
* removed `parallelStream()` from tasks already running with sufficient parallelism
* replaced `ForkJoinPool.commonPool()` with a dedicated `ForkJoinPool`
* added warming up token treasury accounts
Fixes #11915 #12278 
Effect of the fix has been tested with the NFT transfer benchmark and confirmed by profiling.
**Checklist**

perf: reduced warmup overhead #11915;  warm treasury account for token transfer #12278

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc20TransfersCallTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc721TransferFromCallTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/ReplaceAliasesWithIDsInOp.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/TransferContextImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/AllowanceValidator.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustFungibleTokenChangesStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AdjustHbarChangesStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/EnsureAliasesStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/NFTOwnersChangeStepTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/ReplaceAliasesWithIDsInOpTest.java
hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java

Fixes https://github.com/hashgraph/hedera-services/issues/12750
Fixes https://github.com/hashgraph/hedera-services/issues/12776
- Adds a new function in `ReadableAccountStore.getAliasedAccountId()` that looks up accountId's that have aliases set
- The `ReadableAccountStore.getAccountId()` and `ReadableAccountStore.get()` don't look up accountIds that have aliases set
- Used `ReadableAccountStore.getAliasedAccountId()` in `CryptoTransferHandler` and `CryptoGetAccountInfo` and `GetAccountDetails` to permit use of aliases

fix: Allow aliases only in CryptoTransfer

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkPeerIdentifier.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/ConnectionServer.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/InboundConnectionHandler.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/NetworkPeerIdentifierTest.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/network/connectivity/InboundConnectionHandlerTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/ConnectionServerTest.java

closes #12709. 
This PR improves the certificate lookup performance of a newly connected network peer.

feat: improve performance of tlsPeerIdentifier to O(1)

---

hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemDeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemUndeleteHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java

Refactor pureChecks for Smart Contracts and Network Admin services. Move any checks which do not rely on state from preHandle and handle methods to pureChecks method for each transaction handler.
Fixes #12689
Related to #12644

fix: refactor pure checks smart contracts network admin

---

hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/CustomSelfDestructOperation.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v030/V030Module.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v034/V034Module.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v038/V038Module.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v046/V046Module.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v050/V050Module.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomSelfDestructOperationTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java

Post-Cancun SELFDESTRUCT only sweeps if contract was _not_ created in same transaction.
Fixes #11702 .
**Checklist**

feat(cancun): EIP-6780 SELFDESTRUCT semantics

---

hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java

The exception newly added to the unchecked submit's `pureChecks` method is causing some hapi tests to fail. Until we can get the tests updated, or perhaps permanently, this commit returns the handler behavior to its previous state.
For reference, the exception was added in PR #12748

fix: Revert pureChecks exception thrown in unchecked submit

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/MarkerFileWriter.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/PlatformTest.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java

* added file system test for existence of marker file before writing.  
* added atomic boolean flags for when to ignore marker file checks at the end of consensus tests.  
Fixes #12857

fix: unit test marker file writing collision

---

hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java

- Added a condition that was missing in pureChecks. 
- [This PR](https://github.com/hashgraph/hedera-services/pull/12748/files) moved a condition to pureChecks , but missed to add a condition that should be executed only for FREEZE_UPGRADE, TELEMETRY_UPGRADE, PREPARE_UPGRADE

chore: Fix Restart test

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/crypto/internal/MerkleInternalDigestProvider.java

Added null checks to  Hash.serialize and Hash.deserialize
Added null check for `hash.value` to `MerkleInternalDigestProvider.handleItem`. 
Fixes #12862

chore: 12862 Added null checks to  Hash.serialize and Hash.deserialize

---

build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
settings.gradle.kts

Require Gradle to be started using Java 21+. Fail the build if the default JDK (in JAVA_HOME/PATH) points to an older version of Java.
Fixes #12779
For testing purposes, when JAVA_HOME points to Java 17, the build fails as:
```
$ g qualityGate
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/anthony/ws/27-buildJavaVersion/hedera-services/platform-sdk/platform-apps/tests/AddressBookTestingTool/build.gradle.kts' line: 17
* What went wrong:
An exception occurred applying plugin request [id: 'com.hedera.hashgraph.application']
> Failed to apply plugin 'com.hedera.hashgraph.java'.
> ERROR: Gradle is started with Java 17. This project requires running Gradle with Java 21 or above. Please check your JAVA_HOME …
```

feat(build): fail if Gradle is started with Java 20 or older

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java

This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/12665
The failure re-occurred on release/0.49 branch, so I decided to backport the fix. 
Fixes #12247

fix: 12247 Remove incorrect assert from `reopenFileChannel` (#12665)

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/crypto/internal/MerkleInternalDigestProvider.java

Added null checks to  Hash.serialize and Hash.deserialize. Added null check for hash.value to `MerkleInternalDigestProvider.handleItem`
Fixes #12862

chore: 12862 Added null checks to `Hash.serialize` and `Hash.deserialize`

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbTableConfig.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTableConfigTest.java

Fix summary: simplified version of the original fix https://github.com/hashgraph/hedera-services/pull/11973, only changes for `MerkleDbTableConfig` and `MerkleDbConfig` are backported.
Fixes: https://github.com/hashgraph/hedera-services/issues/12901

fix: 12901: Backport the fix for 11966 to release 0.49

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java

This commit includes a fix in the parent finalizer that prevents modular code
from counting staking rewards twice for the parent record, when a scheduled
(child) transaction executes. It also includes a try-catch around parent fina-
lization in the event of a serious problem.
Closes #12875

fix: Don't double-count child staking rewards in parent finalization

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/CustomSpecAssert.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java

Fixing `MAX_CHILD_RECORDS_EXCEEDED` exception when executing tests that are converted to Ethereum.
Fixes https://github.com/hashgraph/hedera-services/issues/12012
The bug was not caused by https://github.com/hashgraph/hedera-services/pull/10944 - it was revealed by it. Till now we were short-circuiting `GenesisRecordsConsensusHook.process` but after https://github.com/hashgraph/hedera-services/pull/10944 was merged we started actually executing the method.
The tests that were converted to Ethereum were throwing `MAX_CHILD_RECORDS_EXCEEDED`. The reason for that is the 
`UtilStateChange.initializeEthereumAccountForSpec`(now `createEthereumAccountForSpec`) method with a combination of `GenesisRecordsConsensusHook.process`.
The …

fix: contractCalls to etheretumContractCalls NPE

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java

This PR moves the checking of judges and writing of marker files before the exception thrown in the issue.   The whole marker file writing endeavor was necessitated by this issue.  This completes the story arc on the platform side.  The next time this exception occurs we will have written a marker file and then it is up to JRS to respond to the presence of the marker file. 
Fixes #11633

fix: consensus writes marker before exception

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EvmTokenUtil.java

fix: use default KYC status `false` for token w/o key

---

hedera-dependency-versions/build.gradle.kts
settings.gradle.kts

Upgrading PBJ to address the following two bugs:
* https://github.com/hashgraph/pbj/issues/236 - `Bytes` ignored the `start`/`length` of a wrapped sub-array.
* https://github.com/hashgraph/pbj/issues/246 - `ReadableSequentialDataInputStream.read()` violated the `InputStream.read()` contract.
Both the bugs are fixed in PBJ v0.8.7.
Fixes https://github.com/hashgraph/pbj/issues/246
PBJ v0.8.7 is released: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
**Checklist**

fix(PBJ): upgrade to PBJ v0.8.7 to address bugs

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2051Spec.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java

- Update expected responses for several specs using `BodyIdClearingStrategy`.
- Add explicit admin key signature to `tokenUpdate()` in `updateIdVariantsTreatedAsExpected()` (it was removed from default signers [here](https://github.com/hashgraph/hedera-services/pull/12396) in anticipation of HIP-540). 
- Increase allowed variation for `CryptoDelete` fee in spec `Issue2051Spec.transferAccountCannotBeDeleted()`.

fix: misc EET expectations

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractLogAsserts.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenAssociate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDissociate.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenFreeze.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycGrant.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycRevoke.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnfreeze.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumV1SecurityModelSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java

Fixes #12953 
- In mono-service we have aliases enabled for only `TokenWipe` transaction apart from `CryptoTransfer` transaction.
- Enable the same in mod service

fix: Enable aliases in TokenWipe as per mono service

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java

This test needed to take into account pre- and post-Cancun changes to SELFDESTRUCT.
Fixes #12895 
**Checklist**

fix(cancun): HAPI test `deletedContractsCannotBeUpdated` fails

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StateChildIndices.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBook.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/roster/RosterDiffGeneratorTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/system/address/AddressBookTests.java

This is a clean up. `AddressBook` objects are no longer used as `MerkleLeaf` objects, because `AddressBook` is now a part of `PlatformState` object which, in it's turn, is a  `MerkleLeaf`. 
So, `AddressBook` should no longer implement this interface. It only needs to be  `Iterable`, `SelfSerializable`, and Hashable.
Fixes #11772

chore: 11772 Refactored `AddressBook` - it's no longer a `MerkleLeaf`

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java

Fix the following failing EETs:
SubmitMessageSuite » idVariantsTreatedAsExpected
TopicDeleteSuite » idVariantsTreatedAsExpected
Fixes #12985

fix: hapi test expectations

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/TokenStateTranslator.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java

- For tokens with a KYC key, mono-service would set their default KCY granted as `true`; but mod-service uses `false` in every case.
- Update migration code to always set KYC granted as `false`.

fix: always migrate token default KYC granted as `false`

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java

* for the NFT receiver account, warm up its `headToken`
* `nftChangesFrom()`: don't read the token unless it's needed
Fixes #12976
**Checklist**

perf: warm up more entities

---

hapi/build.gradle.kts

Bump the hapi version in use by services to that in `hedera-protobufs` branch `v0.50.0-release`
Fixes #13021

feat: Update hapi version in use by services to 0.50

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

This PR removes the check that failed transactions when the estimated gas cost was higher than the maximum transaction fee.
Fixes #13030

fix: remove gas cost check

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java

Cherry-pick of  #13005
Fixes #12976

perf: Cherry-pick: warm up more entities

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/ActionStack.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaWorldUpdater.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ProxyWorldUpdater.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/ActionStackTest.java

fix: cherry pick 12977

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/Fees.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/consensus/queries/GetTopicInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/contract/txns/ContractUpdateResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountDetailsResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountRecordsResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/queries/GetTokenInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/queries/GetTokenNftInfoResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenAssociateResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenDissociateResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenUpdateResourceUsage.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/consensus/queries/GetMerkleTopicInfoResourceUsageTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/contract/txns/ContractUpdateResourceUsageTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java

Fixes https://github.com/hashgraph/hedera-services/issues/13043
- Fixes the handlers that are returning `FeeData.getDefaultInstance` when an entity doesn't exist in state to use a FeeData with a constant value set.

chore: Update default fees to a constant value

---

build-logic/project-plugins/src/main/kotlin/com/hedera/hashgraph/gradlebuild/tasks/GitClone.kt
hapi/build.gradle.kts

This allows not to explicitly define a 'branch' OR a 'tag'. If a 'tag' is defined, we assume that it is stable and the task can be up-to-date.
Fixes #13023
**Checklist**

build: support 'tags' in 'cloneHederaProtobufs'

---

hedera-node/configuration/dev/application.properties
hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ExchangeRateManager.java

- Closes #13069 
- Simply initialize the `ExchangeRateManager`'s midnight rates to what is in state.
* The existing code was probably a vestige of a time when the `FeeService` schema's `migrate()` method did not initialize a genesis state.

fix: midnight rate management on restart

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java

Cherry-pick of #13029 
Closes #13004

fix: Cherry-pick: Avoid catastrophic failure for too large transactions (#13029)

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

Cherry-pick of #13031 
Closes #13030

fix: Cherry pick: remove gas cost check (#13031)

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/stats/ReconnectMapStats.java

Introducing an interface to help gather reconnect-related statistics for maps per a proposal at https://github.com/hashgraph/hedera-services/issues/12412#issuecomment-2076062254
It is out of scope of this particular PR to implement this interface, or start using it.
Contributes to #12412
`gr assemble` passes.
**Checklist**

feat(reconnect): introduce ReconnectMapStats interface

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Account.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/process/Dissociation.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/models/AccountTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/process/DissociationTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java

- Closes #13102 
- Remove behavior of allowing dissociation and doing treasury return when a token is expired.
* This is expected when expiry and rent are enabled, but incorrect without them.
- Rename and enable spec `cannotDissociateFromExpiredTokenWithNonZeroBalance()` as a `@HapiTest` to validate new behavior.

fix: ignore token expiry status in `TokenDissociate`

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Account.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/process/Dissociation.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/models/AccountTest.java
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/process/DissociationTest.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java

fix: ignore token expiry status in `TokenDissociate` 

---

platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatisticsUpdater.java
platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/TestType.java

Fix summary: a reference to `MerkleDbDataSource` is removed from `MerkleDbStatisticsUpdater` class. Instead, a data source instance (to pull stats from) is passed as an arg to all statistics updater methods.
Fixes: https://github.com/hashgraph/hedera-services/issues/12853

fix: 12853: Memory leak from MerkleDbDataSource.copyStatisticsFrom()

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java

- For convenience, ensure migrating from a `v0.48.1` genesis state doesn't throw an exception.

fix: avoid NPE when migrating from genesis (non-prod) state

---

hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleNetworkContext.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/CurrencyAdjustments.java

- Cherry-pick #12826 
- Use `0` for initial gas `UsageSnapshot` to avoid issues migrating a genesis mono-service state.

fix: remove balance adjustment limit from record in state, use `0` for initial gas snapshot

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java

Fixes #13153 
Added missing code coverage. Now the file shows 100% code overage for methods and lines

chore: Add missing code coverage in `EndOfStakingPeriodUpdater`

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java

related to #13198 
cherry pick for 0.50: https://github.com/hashgraph/hedera-services/pull/13200

fix: revert CES name

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSV2SecurityModelSuite.java

Write E2E suites for HSCS operations affected by the security model
Token Burn
-->
https://github.com/hashgraph/hedera-services/issues/12726
Fixes #
https://github.com/hashgraph/hedera-services/issues/12726

feat: Write tests for burn operations #12726

---

.github/workflows/node-flow-deploy-adhoc-artifact.yaml
.github/workflows/node-flow-deploy-release-artifact.yaml
.github/workflows/node-zxc-build-release-artifact.yaml

All modules are now published by one publishing step.
Follow up to: #11731
Fixes #
**Checklist**

build: remove 'publish EVM' step from GH pipeline

---

hedera-node/configuration/testnet/upgrade/throttles.json

Fixes https://github.com/hashgraph/hedera-services/issues/13296
Use mainnet throttles.json for testnet also
PR to release/0.49 - https://github.com/hashgraph/hedera-services/pull/13291

fix: use mainnet `throttles.json` for testnet

---

hedera-node/configuration/testnet/upgrade/throttles.json

Fixes https://github.com/hashgraph/hedera-services/issues/13296
Use mainnet `throttles.json` for testnet also

fix: Use mainnet `throttles.json` for testnet also

---

hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetRecordHandlerTest.java

Adds Unit test coverage > 93% for computeFees and removes all use of junit assertions in NetworkTransactionGetRecordHandler
Fixes #13271

chore: Unit test coverage for NetworkTransactionGetRecordHandler 

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/CacheWarmer.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/AdaptedMonoEventExpansion.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/AdaptedMonoEventExpansionTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/cache/EntityMapWarmer.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/ExpandHandleSpan.java

Switch to `Transaction.getApplicationPayload()` instead of the deprecated method `Transaction.getContents()`
Fixes #12885

chore: Switch to Transaction.getApplicationPayload()

---

hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java

Adds unit tests for FileDeleteHandler. Brings coverage to 94%.
#13189 
**Checklist**

chore: Add Unit tests for FileDeleteHandler

---

hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSignatureWaiversImplTest.java

Adds unit tests for FileSignatureWaiversImpl. Brings coverage to 100%.
#13191 
**Checklist**

chore: Added unit tests for FileSignatureWaiversImpl

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/DummyVirtualRoot.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java

Fix summary: eliminated a thread race in the test, between "main" and virtual pipeline threads. With the race, the pipeline thread can check if a root node copy needs to be flushed before the copy is released. It results in that copy to be merged rather than flushed, which in turn fails the assertion in the end of the test.
Fixes: https://github.com/hashgraph/hedera-services/issues/13336

fix: 13336: :swirlds-virtualmap:timingSensitive sizeBasedFlushes is flaky

---

hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteTest.java

Adds unit tests to FileSystemDeleteHandler. Brings coverage to 92%.
#13192 
**Checklist**

chore: Added Unit tests to FileSystemDeleteHandler

---

hedera-node/hedera-schedule-service-impl/build.gradle.kts
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleHandlersTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchemaTest.java
hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/schemas/PartialLongListFixture.java

This PR improves code coverage for the `InitialModServiceScheduleSchema` and `ScheduleHandlers` classes.
Closes #13311

test: Improve code coverage for initial mod schema, schedule handlers

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/internal/DefaultPlatformContext.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/FileSystemManagerConfig.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/FileSystemManagerFactory.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerFactoryImpl.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerImpl.java
platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/NoOpRecycleBin.java
platform-sdk/swirlds-common/src/test/java/com/swirlds/common/io/filesystem/internal/FileSystemManagerImplTest.java
platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/platform/TestPlatformContextBuilder.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java

This Pr revers the storage location of the recycle bin back to `saved/swirlds-recycle-bin/nodeId`
Fixes #13334 
A recent refactor of the context unified how the PlatformContext is created for commands when no NodeId is needed.
Given the necessity of introducing the nodeId in the factory is limited to cases where we have that information,  I had to create a NoOpRecycleBin that doesn't requiere the nodeId to function.
This introduction brought the opportunity to modify the signature of the factory to support both cases, and thus simplify the factory building patterns

fix: revert recycle-bin store location

---

.github/dependabot.yml
hedera-dependency-versions/build.gradle.kts

Dependabot cannot understand **Module Names**. Thus we have to use the Maven coordinates when we define versions for it to pick them up correctly. Which is something we wanted to avoid initially. As a compromise, we add the **Module Name** of each dependency in the **because** statement. This way, you see both notations to avoid confusion. The updated `java-module-dependencies` plugin **checks if the Module Names are correct** (https://github.com/gradlex-org/java-module-dependencies/issues/105).
Fixes #11570
**Checklist**

build: switch to Dependabot friendly dependency version notation

---

hedera-node/configuration/compose/log4j2.xml
hedera-node/configuration/dev/log4j2.xml
hedera-node/configuration/mainnet/log4j2.xml
hedera-node/configuration/preprod/log4j2.xml
hedera-node/configuration/previewnet/log4j2.xml
hedera-node/configuration/testnet/log4j2.xml
hedera-node/log4j2.xml
hedera-node/test-clients/src/main/resource/log4j2.xml

This PR addresses performance regression introduced by https://github.com/hashgraph/hedera-services/pull/12570
Now `StateLogger` has its own appenders.
Fixes #13300

fix: 13300 Added special handling for `com.swirlds.platform.state.merkle.logging.StateLogger`

---

.github/workflows/node-zxc-build-release-artifact.yaml

- Removes non-existent jobs referenced by the `needs` clause of the `send-notifications` job in the `node-zxc-build-release-artifact.yaml` workflow definition.
- Closes #13420

fix: resolve release pipeline failures due to job dependencies

---

hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/utils/ConversionUtilsTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

- Permits use of `ContractID.DEFAULT` as an implied no-op call to the zero address.

fix: allow default `ContractID`s

---

hedera-node/docs/system-accounts-operations.md
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomMessageCallProcessorTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java

Direct call w/o value to system accounts [0.0.361-0.0.750] result in precompile error
Executing a ContractCall w/o value to system account in the range[0.0.361-0.0.750) result in PRECOMPILE_ERROR
`Expected result:` The call should `succeed` with `no-op`.
1. Create an account
2. Execute ContractCall to 0.0.629 using the account from step1.
3. `Expected` result: The call should succeed with no-op.
4. `Actual` result: The call fails with PRECOMPILE_ERROR
https://github.com/hashgraph/hedera-services/issues/11033
Fixes #
https://github.com/hashgraph/hedera-services/issues/11033
Fixes #
This is achieved by adding a new function called `handleNonExtantSystemAccount`. It will: 
>  //    Create an empty/successful result object
> `PrecompileContractResult result = …

feat: Direct call w/o value to system accounts [0.0.361-0.0.750] change output

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsRestartTest.java

- Use a new `ifNextStakePeriodStartsWithin()` utility verb to sleep for an extra staking period in tests that assume a `cryptoCreate` and `waitUntilStartOfNextStakingPeriod` will occur in the same period.
- Increase the network restart timeout from 2min to 3min in `MixedOpsRestartTest` (one node in a recent run took 2min4s to go `ACTIVE` after restart).

fix: keep staking account creation and initial wait in the same staking period

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java

- freezeToken
- unfreezeToken
Suite | Tests | Signatures
-- | -- | --
FreezeUnfreezeTokenPrecompileV1SecurityModelSuite | freezeUnfreezeFungibleWithNegativeCases()                freezeUnfreezeNftsWithNegativeCases()                isFrozenHappyPathWithLocalCall() | - transaction payer- contract Id- freeze key
https://github.com/hashgraph/hedera-services/issues/12723
Fixes #
https://github.com/hashgraph/hedera-services/issues/12723

feat: Write tests for freeze/unfreeze operations

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java
hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVers.java
platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/BasicSoftwareVersion.java
platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SoftwareVersion.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/RandomSignedStateGenerator.java
platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/system/BasicSoftwareVersionTest.java

feat: apps provide a PBJ software version

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java

fix: invalid package name for HapiUtils

---

hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DissociatePrecompileSuite.java

Signed-off-by: Stefan Stefanov <stefan.stefanooov@gmail.com>
- dissociateTokens
- dissociateToken
Suite | Tests | Signatures
-- | -- | --
DissociatePrecompileV1SecurityModelSuite | dissociatePrecompileHasExpectedSemanticsForDeletedTokens()                nestedDissociateWorksAsExpected()                multiplePrecompileDissociationWithSigsForFungibleWorks() | - transaction payer- contract Id
https://github.com/hashgraph/hedera-services/issues/12724

feat: Write tests for dissociate operations #12724

---

hedera-node/configuration/mainnet/application.properties

- Explicitly set the mainnet ledger id in _application.properties_ to simplify transaction tooling that doesn't expect an empty `0.0.121` file.

fix: explicitly set ledger.id=0x00

---

.gitignore
hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/config/MockGlobalDynamicProps.java

This will always invalidate the "test" task after it ran and it will never be UP-TO-DATE. This is, because you change the inputs, in this case the test sources/resources, of the task while it is running.
Discovered while working on #11565
**Checklist**

build: do not write test data into source folder

---

.github/workflows/node-zxc-compile-application-code.yaml
gradle.properties

Passing `-Dfile.encoding=UTF-8` to the Gradle command effectively has no effect as this only starts a small client process that connects to a (possibly already running) daemon process. These kind of JVM options need to be configured in 'gradle.properties' for the Daemon process.
#11230 
**Checklist**

build: set UTF-8 encoding for Gradle daemon process

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/config/CryptoConfig.java

This change of configuration enables loading signing and agreement keys from PEM files in addition to PFX files. 
Fixes #13488

feat: enable loading keys from PEM files

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractHandlers.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java

There were several checks performed in `IngestChecker` that should be relocated to relevant `pureChecks()` methods in handlers.
Fixes: #13521 
**Checklist**

feat: move checks from `IngestChecker` to `pureChecks` methods

---

platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java

Heartbeat task submission should never block. It should be OK to "skip a heartbeat".
Fixes #13502
**Checklist**

perf: don't block heartbeats

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java

Consider a scenario such as,
```
<<<JVM restarts>>
2024-05-23 14:04:55.913 INFO  430  Hedera - Initializing configuration with trigger RESTART
<<first gRPC server created>>
2024-05-23 14:04:57.140 INFO  809  Hedera - Hederanode#2 is REPLAYING_EVENTS
2024-05-23 14:05:00.017 INFO  809  Hedera - Hederanode#2 is OBSERVING
2024-05-23 14:05:10.031 INFO  809  Hedera - Hederanode#2 is CHECKING
2024-05-23 14:05:10.107 INFO  799  Hedera - Hederanode#2 is ACTIVE
<<first gRPC server started, ports bound>>
2024-05-23 14:05:12.142 INFO  809  Hedera - Hederanode#2 is BEHIND
2024-05-23 14:05:17.035 INFO  430  Hedera - Initializing configuration with trigger RECONNECT
<<second gRPC server created; ⚠️ first should be stopped, ports unbound>>
2024-05-23 14:05:17.324 INFO  809  Hedera - …
```

fix: unbind gRPC server from previous `daggerApp`

---

platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java

disables `ConsensusTests::nodeRemoveTest` which is not implemented correctly.  
This new issue was created to implement the test correctly: https://github.com/hashgraph/hedera-services/issues/13556
Fixes #13201

fix: disable broken consensusTests::nodeRemoveTest

---

hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java

Cherry-pick #13541 
Fixes https://github.com/hashgraph/hedera-services/issues/13515
Fixes NPE in `QueryWorkflowImpl` by use OrElse pattern instead of throw to correctly return a response code instead of NPE

fix: Fix NPE in `QueryWorkflowImpl` (#13541)

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fix summary: see #13584 for details.
Fixes: https://github.com/hashgraph/hedera-services/issues/13584

fix: 13584: Thread race between VirtualPipeline.hashCopy() and VirtualRootNode.computeHash()

---

hapi/src/main/java/com/hedera/hapi/util/HapiUtils.java

Call isBlank() in parsedIntOrZero() to avoid NumberFormatException for empty/blank strings.
Fixes #13587
**Checklist**

perf: HapiUtils.parsedIntOrZero() throws too many exceptions

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java
hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/MigrationContext.java
hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/OrderedServiceMigrator.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServicesRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServicesRegistryImpl.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/SchemaApplicationType.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/SchemaApplications.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/VersionUtils.java
hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/MigrationContextImpl.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SchemaApplicationsTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java
hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/schemas/FileSchemaTest.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/V0500ContractSchema.java
hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/V0500ContractSchemaTest.java
hedera-node/hedera-smart-contract-service/src/main/java/com/hedera/node/app/service/contract/ContractService.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchema.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchemaTest.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java

- Cherry-pick necessary parts of #13535 
* The extra cleanup to make all `Schema`s top-level classes, remove the `version` argument from `Service.registerSchemas()`, and extract mono migration from `Hedera`---while important tech debt to pay down---does not need to be in `release/0.50`.

fix: add migrations to repair storage links

---

hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java

Call isBlank() in parsedIntOrZero() to avoid NumberFormatException for empty/blank strings.
Fixes #13587
**Checklist**

perf: cherry-pick: HapiUtils.parsedIntOrZero() throws too many exceptions

---

platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/13586 to `release/0.50` branch.
Fixes: https://github.com/hashgraph/hedera-services/issues/13610

fix: 13610: Backport the fix for 13584 to 0.50

---

platform-sdk/swirlds-base/src/main/java/module-info.java
platform-sdk/swirlds-base/src/testFixtures/java/module-info.java
platform-sdk/swirlds-cli/src/main/java/module-info.java
platform-sdk/swirlds-common/src/main/java/module-info.java
platform-sdk/swirlds-common/src/testFixtures/java/module-info.java
platform-sdk/swirlds-config-api/src/main/java/module-info.java
platform-sdk/swirlds-config-api/src/testFixtures/java/module-info.java
platform-sdk/swirlds-config-extensions/src/main/java/module-info.java
platform-sdk/swirlds-config-extensions/src/testFixtures/java/module-info.java
platform-sdk/swirlds-config-impl/src/main/java/module-info.java
platform-sdk/swirlds-config-processor/src/main/java/com/swirlds/config/processor/ConfigDataAnnotationProcessor.java
platform-sdk/swirlds-config-processor/src/main/java/module-info.java
platform-sdk/swirlds-fchashmap/src/main/java/module-info.java
platform-sdk/swirlds-fcqueue/src/main/java/module-info.java
platform-sdk/swirlds-jasperdb/src/main/java/module-info.java
platform-sdk/swirlds-logging-log4j-appender/src/main/java/module-info.java
platform-sdk/swirlds-logging/src/main/java/module-info.java
platform-sdk/swirlds-logging/src/testFixtures/java/module-info.java
platform-sdk/swirlds-merkle/src/main/java/module-info.java
platform-sdk/swirlds-metrics-api/src/main/java/module-info.java
platform-sdk/swirlds-metrics-impl/src/main/java/module-info.java
platform-sdk/swirlds-platform-core/src/main/java/module-info.java
platform-sdk/swirlds-platform-core/src/testFixtures/java/module-info.java
platform-sdk/swirlds-state-api/src/main/java/module-info.java
platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/module-info.java
platform-sdk/swirlds-virtualmap/src/main/java/module-info.java

- Annotation library dependencies should be transitive as they are annotations on public interfaces. This is not checked by the dependency analysis, but will be by `javac` itself once #11838 is integrated.
- Correct the Java version in our own `ConfigDataAnnotationProcessor`
#11569
**Checklist**

build: make annotation library dependencies transitive

---

platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggerApiSpecAssertions.java

Required to turn warnings into errors in #11838, as these cannot be ignored.
https://github.com/hashgraph/hedera-services/issues/11569
**Checklist**

chore: Address compiler warnings in LoggerApiSpecAssertions

---

platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncInputStream.java

Using `AtomicLong`, instead of `AtomicInteger`, for the `anticipatedMessages` counter in `AsyncInputStream`.
While investigating https://github.com/hashgraph/hedera-services/issues/13064 , I've noticed that the `LearnerPushVirtualTreeView` maintains the list of expected lessons in a queue that natively supports more than 2G items. In fact, it supports at least the `Long.MAX_VALUE` items (barring physical memory limitations.) This was implemented on purpose because the size of the trees being synchronized may be very large.
However, a counter of anticipated messages in the `AsyncInputStream` was an `AtomicInteger` for some reason, which clearly may produce incorrect results should the number of anticipated messages exceed the 2G or 4G limit.
While I'm unsure if the test …

fix(reconnect): use AtomicLong for anticipatedMessages counter

---

hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottleTest.java

Disables `DeterministicThrottleTest.throttlesWithinPermissibleTolerance()` because it is flaky. The test should be enabled again once it has been redesigned (see #13667).
Fixes #13666

chore: Disable DeterministicThrottleTest.throttlesWithinPermissibleTolerance()

---

platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBaseBench.java
platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java

Fix summary: direct backport of https://github.com/hashgraph/hedera-services/pull/13664 to `release/0.51`
Fixes: https://github.com/hashgraph/hedera-services/issues/13674

fix: 13674: Backport the fix for 13531 to release 0.51

---

hedera-node/configuration/mainnet/application.properties
hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountInfoHandlerTest.java

This PR updates the configuration to enable balances in queries.
It also updates the application.properties file with the changes that were done for the 0.49 release.
Fixes #13715

fix: Cherry-pick: Enable tokens.balancesInQueries.enabled

---

hedera-node/hedera-consensus-service/build.gradle.kts
hedera-node/hedera-consensus-service/src/test/java/com/hedera/node/app/service/consensus/ConsensusServiceDefinitionTest.java
hedera-node/hedera-file-service/build.gradle.kts
hedera-node/hedera-file-service/src/test/java/com/hedera/node/app/service/file/FileServiceDefinitionTest.java
hedera-node/hedera-network-admin-service/build.gradle.kts
hedera-node/hedera-network-admin-service/src/test/java/com/hedera/node/app/service/networkadmin/FreezeServiceDefinitionTest.java
hedera-node/hedera-network-admin-service/src/test/java/com/hedera/node/app/service/networkadmin/NetworkServiceDefinitionTest.java
hedera-node/hedera-schedule-service/build.gradle.kts
hedera-node/hedera-token-service/build.gradle.kts
hedera-node/hedera-token-service/src/test/java/com/hedera/node/app/service/token/CryptoServiceDefinitionTest.java
hedera-node/hedera-token-service/src/test/java/com/hedera/node/app/service/token/TokenServiceDefinitionTest.java
hedera-node/hedera-util-service/build.gradle.kts
hedera-node/hedera-util-service/src/test/java/com/hedera/node/app/service/util/UtilServiceDefinitionTest.java

Add test coverage for the non-impl service modules:
- hedera-consensus-service
- hedera-file-service
- hedera-network-admin-service
- hedera-token-service
- hedera-util-service
hedera-schedule-service already had tests set up.
Fixes #13724 
Fixes #13729 
Fixes #13728 
Fixes #13727 
Fixes #13725 
Fixes #13726 
Fixes #13288

feat: servicedefinition tests

---

hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/flow/dispatch/user/logic/PreHandleResultManagerTest.java

- Near-concurrent merges broke a unit test use of `NodeInfoImpl`.

fix: unit test compile error

---

hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java

This PR fixes hollow account completion when done with nft transfer
This PR modifies ... in order to support ...
`CryptoTransferHandler` now checkSender check if account is hollow and require signature for it
`CryptoTransferSuite` - added hapi test that verifies hollow account completion
-->
Fixes #13831 
**Checklist**

fix: Fix hollow account completion when completing with nft transfer
