hiero-ledger/hiero-consensus-node

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableStakingInfoStoreImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/staking/RewardCalculator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableStakingInfoStoreImplTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/RewardCalculatorTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableStakingInfoStore.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/Units.java
> Implement modularized reward calculator

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
Related to #7611 
I don't think this will fix the issue, but it should cause us to throw an exception sooner, and might point us to the root cause.
> Add extra null checks inside PCES file manager.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ids/EntityIdService.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ids/WritableEntityIdStore.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/Savepoint.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
PR For new Entity ID Service and state. Issue #7256
> New Entity ID Service

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/StaticValidators.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorImplTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/validation/EventValidatorTests.java
> Make tipset algorithm work with single node network.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/MultiQueueThread.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/MultiQueueThreadImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventWriter.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
> Fixed PCES race condition.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowGraphSynchronizer.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncNode.java
> Move hashing to gossip threads.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/GenesisSchema.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileServiceImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableUpgradeStoreImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
Fixes # [7686](https://github.com/hashgraph/hedera-services/issues/7686)
> fix of the singleton state causing an modurun issue

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileUpdate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- Uses `updateLargeFile()` instead of `fileUpdate`() to override properties.
> With 121 large file update

- platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolState.java
> Validate that transactions are prehandled exactly once

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/AdaptedMonoEventExpansion.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/AdaptedMonoEventExpansionTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/EventExpansion.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/EventExpansionTest.java
> Make pre-handle thread-safe

- platform-sdk/sdk/settings.txt
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreationManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
> Remove saveReconnectStateToDisk setting

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Assorted-500-3m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Basic-2.5k-105m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Basic-2.5k-8m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Hotspot-2.5k-8m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-HotspotStress-2.5k-13m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-MultiNIReconnect-1R-500-70m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-MultiNIReconnect-2R-500-70m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-MultiSBReconnect-2R-1k-20m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-NIReconnect-125-26m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Query-2.5k-12m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Query-2.5k-30m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-SBReconnect-2.5k-10m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCMFCQ-Basic-1k-10m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCMFCQ-Hotspot-2.5k-5m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCMFCQ-NIReconnect-1.5k-30m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/NFT-Basic-2.5k-10m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/NFT-Basic-2.5k-40m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/NFT-Basic-2.5k-60m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/NFT-Hotspot-2.5k-30m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/NFT-HotspotTransfers-2.5k-60m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkle-DynamicFreeze-1k-40m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkle-NDReconnect-1k-15m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkle-NIReconnect-1k-15m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkle-SBReconnect-1k-15m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleDual-NDReconnect-400-7m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleSC-Assorted-5k-20m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleSC-Basic-3k-114m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleSC-Basic-5k-20m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleSC-Hotspot-5k-15m.json
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/VMerkleSC-Perform-7k-40m.json
> Restore deleted platform test config files

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
> Use provided round created if either parent is missing.

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/FreezeServiceImplTest.java
Fix an NPE error that occurs during startup when launching via `modrun` gradle command.
Fixes #7754
> Fixed an NPE that occurs when starting via modrun gradle command

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
- Cherry-pick https://github.com/hashgraph/hedera-services/pull/7783
> Avoid unwanted genesis migration records

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacks.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacksTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue305Spec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
- Cherry-pick of https://github.com/hashgraph/hedera-services/pull/7780
> Refresh multipliers in config callback; add EET

- hedera-node/hedera-file-service-impl/build.gradle.kts
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java
> fix fileservice util to support correctly immutible files

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/NftStateTranslator.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/codec/NetworkingStakingTranslator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/codec/NetworkingStakingTranslatorTest.java
bi-directional translator for NetowkringStakingRewards
Fixes #7777
> bi-directional translator for NetworkStakingRewards

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMultiFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMutableFile.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayPipeline.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayPipelineTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
release 41 merge of #7741 (still has to be merged to develop)
> write gossip events to PCES

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
Related to #7799 
Needs to be cherry-picked into develop.
> Delay pruning until after PCES replay.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/metrics/extensions/BusyTimeTest.java
> fix overflow issue

- platform-sdk/swirlds-cli/color-logs.py
> Add colors to status logs

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslator.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslatorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleNetworkContext.java
> BlockInfo translator

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/ChildlessEventTracker.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/ChildlessEventTrackerTests.java
Related to #7750 
Needs to be cherry-picked into develop after merging.
> The tipset algorithm should not log errors when there is branching.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMultiFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMutableFile.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayPipeline.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayPipelineTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
closes #7741
this has already been merged to 41: https://github.com/hashgraph/hedera-services/pull/7793
> write gossip events to PCES (#7793)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/metrics/extensions/BusyTimeTest.java
closes #7817
already merged to 41: https://github.com/hashgraph/hedera-services/pull/7821
> busy time overflowing

- platform-sdk/swirlds-common/src/main/java/module-info.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/CryptographyTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/DetRandomTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/EcdsaSecp256k1VerifierTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/HashTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/MessageDigestTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/RunningHashTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/SerializablePublicKeyTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/SignatureTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/SigningProviderTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/TransactionSignatureTests.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/crypto/EcdsaSignedTxnPool.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/crypto/MessageDigestPool.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/crypto/SerializableHashableDummy.java
- platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/crypto/SliceConsumer.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/crypto/CryptographyBenchmarkTests.java
Part of https://github.com/hashgraph/hedera-services/pull/7763
> crypto tests moved to common module

- platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkMetrics.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/RunningAverageMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/SpeedometerMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/StatEntry.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetricsFactory.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetricsProvider.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultStatEntry.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/RunningAverageMetricConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/SpeedometerMetricConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultStatEntryTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/LegacyCsvWriterTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/prometheus/PrometheusEndpointTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfigurationTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/MeasuredBlockingQueueConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/MeasuredBlockingQueueTest.java
- platform-sdk/swirlds-fcqueue/src/test/java/com/swirlds/fcqueue/FCQueueStatisticsTest.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/jasperdb/JasperDbStatisticsTest.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbStatisticsTest.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTestUtils.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/chatter/SimulatedChatterFactories.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/stats/AccumulatedAverageTimeTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/stats/CycleMetricsTest.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java
> #7266 Remove ConfigurationHolder from Metrics

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetWeightCalculator.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/TipsetEventCreatorImplTests.java
Cherry pick of https://github.com/hashgraph/hedera-services/pull/7834
> 07812 41 fix tipset freeze (#7834)

- hedera-node/configuration/mainnet/upgrade/feeSchedules.json
- hedera-node/configuration/testnet/upgrade/feeSchedules.json
- hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/token/TokenOpsUsage.java
- hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json
- hedera-node/hedera-mono-service/src/test/resources/fees/feeSchedules.json
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AllBaseOpFeesSuite.java
- hedera-node/test-clients/src/main/resource/FeeSchedule.json
> Cherry-pick : Update NFT Mint pricing for extra signatures (#7880)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/ChildlessEventTracker.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/tipset/ChildlessEventTrackerTests.java
Closes #7750 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/7819
> Tipset Branching Bug

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/RunningHashesTranslator.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/codec/RunningHashesTranslatorTest.java
> Running Hashes Translator

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/export/ConfigExport.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/internal/PlatformConfigUtils.java
> #7419 Clean up settingsUsed.txt

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
> Protect against double saving states (#7804)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/EventCreationConfig.java
> Change the default maximum event creation rate to mirror production

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
> Updated maximum event creation rate for production environments.

- platform-sdk/gradle.properties
Updates the platform version to 42.
Fixes #7918
None
**Checklist**
> Update platform version to 42

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
Closes #7799 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/7813
> Delay pruning until after PCES replay. (#7813)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/constructable/internal/GenericConstructorRegistry.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/DefaultPlatformContext.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/TextHistogram.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/TextTable.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/MerkleDataInputStream.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/SerializableDataInputStream.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/impl/destroyable/DestroyableBinaryMerkleInternal.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/impl/destroyable/DestroyableMerkleLeaf.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/impl/destroyable/DestroyableNaryMerkleInternal.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/AbstractDistributionMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetric.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/sequence/set/internal/AbstractSequenceSet.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/transaction/internal/StateSignatureTransaction.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/SyncLock.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/MeasuredBlockingQueue.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/BinarySearch.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/CommonUtils.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/Mnemonics.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/PlatformVersion.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/SemanticVersion.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/UnmodifiableIterator.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetricTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/MeasuredBlockingQueueConfigTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/MeasuredBlockingQueueTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/BinarySearchTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/UnmodifiableIteratorTests.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleSerializationTests.java
Objects.requireNonNull used in common instead of ArgUtil
> Objects.requireNonNull used in common

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
> Avoid unwanted genesis migration records (#7784)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMutableFile.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
Related to #7927 
Needs to be back ported to 0.41
> Handle empty PCES files.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileIterator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMutableFile.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
> Handle empty PCES files. (#7940)

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreatorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
> Fix publishing staking fund account records (#7930)

- platform-sdk/swirlds/build.gradle.kts
Without this fix, the Jar files may not yet be built which can lead to an error like `Not a module and not mapping defined...`.
**Checklist**
> Correctly define the 'runtimeClasspath' as input to :swirlds:jar

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKey.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskValue.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
> Fix deserialization by using views onto buffers

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
> 07972 41 lower event rate

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/EventCreationConfig.java
> Lower event creation rate per node to 20 per second.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransactionalLedger.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingAccounts.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingNfts.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingStore.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokenRels.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokens.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/backing/pure/PureBackingAccounts.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/SystemAccountsCreator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/TreasuryCloner.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransactionalLedgerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/BackingTokensTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingAccountsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingTokenRelsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingAccounts.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingNfts.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingTokenRels.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapBackingTokens.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/HashMapTestAccounts.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/pure/PureBackingAccountsTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/BackedSystemAccountsCreatorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/TreasuryClonerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStoreTest.java
> Cherry-pick : Fix round 1 replay (#7979)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinBrowser.java
> Fix for 7978: exception for null-tabs fixed

- hedera-node/hedera-app/src/xtest/java/contract/ScaffoldingModule.java
This is a quick fix to make ScaffoldingModule compile again.
For the final solution, we should first simplify HandleContextImpl. This will be done in a separate PR.
> Quick fix for ScaffoldingModule

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/Network.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/NetworkTests.java
> #8002 Fix Hashgraph Demo

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
> file create test e2d properly working and fix of file create

- .github/workflows/node-flow-fsts-daily-interval-01.yaml
- .github/workflows/node-flow-fsts-daily-interval-02.yaml
- .github/workflows/node-flow-fsts-daily-interval-03.yaml
- .github/workflows/node-flow-fsts-daily-interval-04.yaml
- .github/workflows/node-flow-fsts-daily-interval-05.yaml
- .github/workflows/node-flow-fsts-daily-interval-06.yaml
- .github/workflows/zxc-jrs-regression.yaml
Updates the Services daily test pipelines to support the changes made in swirlds/swirlds-platform-regression#3703. 
- Closes #8026 
- Related to swirlds/swirlds-platform-regression#3703
> fix: resolve issues with the Services test pipelines to properly support release branches

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/base/FileQueryBase.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/QueryFailuresSpec.java
Fixes #8022 
E2E testing for file query and also fix the behavior for file deletion, file info, and data
>  file query E2E

- .github/workflows/node-zxcron-release-fsts-regression.yaml
This pull request enabled support for running the daily Services Node tests on the release branches. 
- Closes #8088
> chore: add and enable daily Services Node release branch tests

- .github/workflows/platform-flow-deploy-mc-release.yaml
- .github/workflows/platform-zxc-release-maven-central.yaml
This pull request fixes an issue with the Maven Central release pipeline which causes it to require manual intervention in order to commit to the branch. 
- Closes #8110
> fix: resolves issue with the Maven Central pipeline requiring manual intervention

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
Closes #8117
Fixes #
N/A
**Checklist**
N/A
> Remove socket.doUpnp from settings.txt

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCMFCQ-Basic-ECDSA-1.5k-50m.json
Disable invalid signature
Fixes # regression issue 3708
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1692392404507489
> Disable invalid signature ratio for FCMFCQ test

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/FeeCalculator.java
- hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/fees/FakeFeeCalculator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/FileNumbersModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/HederaFileNumbersImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/NumbersModule.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacilityTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/LongPairConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/FilesConfig.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/types/LongPair.java
- hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/LongPairConverterTest.java
- hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileAppendSuite.java
I added Fees calculation to file append in order to E2E to pass.
Fixes #8019
> File Append E2E test pass

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Query-2k-110m.json
Related to #8035 
Must be merged in tandem with https://github.com/swirlds/swirlds-platform-regression/pull/3709
> Reduce TPS for FCM-Query-2.5k-110m.json

- .github/workflows/platform-zxf-jrs-daily-interval-03.yaml
Add a new single node panel to interval 3. This panel contains a new, single node 3 minute test.
Fixes #7850
**Checklist**
> Add a single node test to nightly platform tests in interval 3

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-MultiSBReconnect-3R-1k-20m.json
Closes #8083 
Cherry pick of a change already made to develop: https://github.com/hashgraph/hedera-services/pull/8141
> 08083 d fix sbr test (#8141)

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/ControlAction.java
> Fix regression in PTT.

- hedera-node/hedera-app/src/xtest/java/contract/AssortedOpsXTest.java
- hedera-node/hedera-app/src/xtest/java/contract/MiscViewsXTest.java
- hedera-node/hedera-app/src/xtest/java/contract/ScaffoldingModule.java
This PR fixes compilation errors in xtest. The tests are still failing though.
Closes #8180
> Fix xtest compilation

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/AbstractReservable.java
> Make lambdas in AbstractReservable static.

- .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
> 08200: Run abbreviated panel nightly

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/random/PTTRandom.java
> Fix JSR Tests

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/BootstrapConfigProviderImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
Closes #8234. Simply change to improve the bootstrapping behavior
> Split ConfigProviderImpl into a base class and bootstrap variant

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyReadableStates.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/Utils.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/LedgerConfig.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/domain/security/PermissionedAccountsRange.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/GenesisSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/GenesisSchemaTest.java
> Full implementation of genesis account creations.

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/UpdateFailuresSpec.java
Fix the issue that some of the E2E was failing related to the autorenew validation in file update.
> fix autorenew validation and E2E that failing because of that

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/DeleteFailuresSpec.java
> uncomment one E2E test DeleteFailuresSpec

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/positive/CreateSuccessSpec.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileExpansionLoadProvider.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileUpdateLoadTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/MixedFileOpsLoadTest.java
enable performance test for files in modularize way
Fixes #8162 
#8163 
#8164
#8049
> enable hapitest annotation on performance tests and CreateSuccessTest

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
> Add docs to explain out-of-band state saving

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
Closes #8279. Simply removes the comment. See the associated issue for reasoning.
> Remove TBD for IssListener. The platform is already listening.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
> Remove validation of ledger state at startup

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/InboundConnectionManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkUtils.java
> Downgrade socket exceptions to warnings.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
Minor fixes from previous PR #8197 
- Disable all child verifications per default until handled properly
- Fixed serialization of transactions
Closes #8151
> Minor fixes from previous PR

- .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
Fixes #8331 
Needs to be merged before next JTR and Nightly Run
> AddressBook Add and Remove Test Panel Name Updated

- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
Fixes a flaky unit test.
Fixes #8338
None
**Checklist**
> Fix flaky unit test

- .github/workflows/node-zxc-build-release-artifact.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- .github/workflows/node-zxf-snyk-monitor.yaml
- .github/workflows/platform-zxc-compile-platform-code.yaml
- .github/workflows/platform-zxc-release-internal.yaml
- .github/workflows/platform-zxc-release-maven-central.yaml
- .github/workflows/zxc-jrs-regression.yaml
Updates GH [gradle-build-action](https://github.com/gradle/gradle-build-action) to latest.
> Update GH 'gradle-build-action' to 2.8.0

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/LogsSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/RecordsSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
This change adds several small fixes to the solvency checks.
Unfortunately, I had to disable some tests because of an open issue. Once clarified, the tests can be fixed and enabled again.
> Solvency fixes

- platform-sdk/swirlds-benchmarks/build.gradle.kts
This dependency was mistakenly removed in #7875.
Fixes #8405
**Checklist**
> Re-add runtime only dependency to "com.swirlds.config.impl"

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/EntityId.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/submerkle/EntityIdTest.java
> Throw on conversion outside long-zero subspace

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
Closes #8409 
This is code that I am splitting out of my large emergency recovery PR.
> Make clearing the PCES a static method.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/AsyncTipsetEventCreationManager.java
Related to #8415 
Must be cherry picked to 0.42
> Add metrics to various queues.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/DefaultSignedStateValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectHelper.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformData.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/State.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateValidationData.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/HashLogger.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/DefaultSignedStateValidatorTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/HashLoggerTest.java
Closes #8397 
This code was split from my large emergency recovery branch.
> Improved state logging.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatformBuilder.java
This is a first early implementation. It has been manually tested. I am not sure how to do automated tests for it, since the "buildAndRun" will actually attempt to start up the entire node. This class is heavily used by all the BDD tests after #8349 is resolved. This will cause this code to be heavily tested on a near constant basis.
Follow up PRs should remove the duplication from `Browser` and provide it the hooks it needs for the UI, without brining the UI baggage along with the SwirldsPlatformBuilder.
Fixes #8447 
Blocks #8349 
**Checklist**
> Implementation of SwirldsPlatformBuilder, sufficient for initial use by services

- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
Fix error that occurs during hapi test initialization
Fixes #8476
> Fix hapi initialization error

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
This PR disables all e2e-tests that are currently failing. I am going to reopen the issues for the failing tests.
Closes #8460
> Disable all failing tests

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/pool/StandardWorkGroup.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/pool/StandardWorkGroupTest.java
Fix summary: direct backport of the fix for #8170 to release 0.42 Original PR for develop is here: https://github.com/hashgraph/hedera-services/pull/8443
Fixes: https://github.com/hashgraph/hedera-services/issues/8503
> 8503: Backport the fix for # 8170 to release 0.42

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DualStateUpdateFacility.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/DualStateUpdateFacilityTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
> Use the DualState from handleRound instead of from initialization for the DualStateUpdateFacility

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeService.java
> ExchangeRateSet at genesis matching FileServiceImpl's GenesisSchema

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
Fees are already recorded in the `FeeAccumulator`. No need to record them in the workflow.
> Revert "Store calculated fees in record builder (#8492)"

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ReconnectMetrics.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectThrottle.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/ReconnectThrottleTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
> 07894 Reconnect Teacher - Throttle Logs and New Metric

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/AwareNodeDiligenceScreen.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManagerTest.java
> Accommodate due diligence failure records w/ `records.useConsolidatedFcq=true`

- hedera-node/cli-clients/build.gradle.kts
- hedera-node/cli-clients/services-cli.sh
Create a fat jar for the services cli so it can be run standalone.  Also a script
to run it with (script is a slight modification of `pcli.sh`.
All you need is to copy the fat jar and the script someplace (to the same directory)
and run the script from there.
**Related**:
Fixes #8540 
**Checklist**:
> Create fat jar with services CLI so it can be run standalone

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
- hedera-node/settings.gradle.kts
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/UnsupportedQueriesRegression.java
Fix UnsupportedQueriesRegression e2e test suite (part of Crypto hapi e2e test suite)
Fixes #8155 
Relies on https://github.com/hashgraph/hedera-protobufs/pull/303
Sequence to merge this change across the two repositories:
-Merge this PR which sets hapiProtoBranchOrTag = "7680-Get-Fast-Record" // temporary branch
-Merge https://github.com/hashgraph/hedera-protobufs/pull/303 to merge changes in 7680-Get-Fast-Record into add-pbj-types-for-state
-Merge PR #8538 to reset the hapiProtoBranchOrTag back to add-pbj-types-for-state
> Fix UnsupportedQueriesRegression HapiSuite

- .github/workflows/node-zxc-build-release-artifact.yaml
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.mock-release-tasks.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.root.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com/hedera/hashgraph/gradlebuild/lifecycle/LifecycleSupport.kt
- platform-sdk/platform-apps/demos/CryptocurrencyDemo/build.gradle.kts
- platform-sdk/platform-apps/demos/HashgraphDemo/build.gradle.kts
- platform-sdk/platform-apps/demos/HelloSwirldDemo/build.gradle.kts
- platform-sdk/platform-apps/demos/StatsDemo/build.gradle.kts
- platform-sdk/platform-apps/tests/AddressBookTestingTool/build.gradle.kts
- platform-sdk/platform-apps/tests/ConsistencyTestingTool/build.gradle.kts
- platform-sdk/platform-apps/tests/ISSTestingTool/build.gradle.kts
- platform-sdk/platform-apps/tests/MigrationTestingTool/build.gradle.kts
- platform-sdk/platform-apps/tests/PlatformTestingTool/build.gradle.kts
- platform-sdk/platform-apps/tests/StatsSigningTestingTool/build.gradle.kts
- platform-sdk/swirlds-benchmarks/build.gradle.kts
- platform-sdk/swirlds-config-benchmark/build.gradle.kts
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/build.gradle.kts
- platform-sdk/swirlds-unit-tests/structures/swirlds-merkle-test/build.gradle.kts
- platform-sdk/swirlds/build.gradle.kts
- Addresses the breaking issues in the CI pipeline.
- Makes the enhancement requested by @jjohannes in #8554
- Closes #8565
> fix: resolve issues with the Gradle project identifier breaking the Platform release

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/AwareNodeDiligenceScreen.java
> Fix JRS queryable payer record issue

- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
- platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBinImpl.java
Updated version if Migration Testing Tool to prevent JRS test failures.
Fixed single JVM scenario.
Fixes #8236 
**Checklist**
> Updated version if Migration Testing Tool to prevent JRS test failures.

- hedera-node/settings.gradle.kts
- Re-targets to `add-pbj-types`
> Restore PBJ branch target

- hedera-node/hedera-app/src/xtest/java/contract/PausesXTest.java
- hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HtsTranslatorsModule.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/pauses/PausesDecoder.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/pauses/PausesTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/pauses/PausesDecoderTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/pauses/PausesTranslatorTest.java
Implementation for HTS pause and unpause functions
Fixes #8571
Fixes #8572
> Implement HTS pause/unpause functions

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/HederaAccountCustomizer.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/HederaAccountCustomizerTest.java
> Skip `0.0.0` auto-renew account id in synthetic `ContractCreate`

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/HederaAccountCustomizer.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/HederaAccountCustomizerTest.java
- hedera-platform/build.gradle.kts
- settings.gradle.kts
- Cherry picks #8700 
- Updates to stable protobuf artifact
> Cherry pick 8700

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/AddressBookNetworkUtilsTests.java
> 08741 - Disable Failing Bad Local Address Test on Windows and Macs

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java
> Only be a reconnect teacher if platform status is active

- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/LogProcessor.java
> Fix log file search

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
Added back `deferStatusResolution`
Closes #8417 
Test result
https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1695331927770109
> Fix account balance test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/BrowseCommand.java
> Implement clean option for browse command

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/JrsTestReportGenerator.java
> Add a column to JTR summary for logs

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CallCodeOperationSuite.java
Enabling passing test
Fixes https://github.com/hashgraph/hedera-services/issues/8852
> Fix CallCodeOperationSuite tests 

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1758Suite.java
We have the following test suite Issue1758Suite that has problems when it's running against the modularization codebase.
**Solution**:
Resolve issues with the test suite. When ready add @hapitest annotations to the passing tests.
Fixes #8766
**Checklist**
> Resolve `Issue1758Suite` errors

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1741Suite.java
We have the following test suite Issue1741Suite that has problems when it's running against the modularization codebase.
**Solution**:
Resolve issues with the test suite. When ready add @hapitest annotations to the passing tests.
Fixes #8763
**Checklist**
> Resolve `Issue1741Suite` errors

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
> Enable passing tests for crypto transfer

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SStoreSuite.java
Fix `SStoreSuite` tests.
Fixes #8889 
Just added `@HapiTest` annotation for `childStorage` and `benchmarkSingleSetter` tests because they passed already.
> Fix `SStoreSuite` tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PushZeroOperationSuite.java
Fix `PushZeroOperationSuite` tests.
Fixes #8886
Just added `@HapiTest` annotation for `pushZeroDisabledInV034` test because it passes already.
> Fix `PushZeroOperationSuite` tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
Fix `SelfDestructSuite` tests.
Fixes #8894 
Just added `@HapiTest` annotation for `selfDestructFailsWhenBeneficiaryHasReceiverSigRequiredAndHasNotSignedTheTxn` test because it passes already.
> Fix `SelfDestructSuite` tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/StaticCallOperationSuite.java
Fix `StaticCallOperationSuite` tests.
Fixes #8849 
Just enabled `verifiesExistence` test.
> Fix `StaticCallOperationSuite` tests

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AllBaseOpFeesSuite.java
Change Set to a List in customFeeValidator to avoid ISS in HAPI tests CI
> Change Set to a List in customFeeValidator

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncManagerImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncProtocol.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/protocol/SyncProtocolTests.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/notification/IntegerNotificationTests.java
> Add setting to disable critical quorum.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncInputStream.java
Related to #8984 
Should be backported to 0.43 after merging
> 08984 reconnect deadlock

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/BalanceOperationSuite.java
Fix `BalanceOperationSuite` tests.
Fixes #8804 
Just added `@HapiTest` annotation for `verifiesExistenceOfAccountsAndContracts` test because it passed already.
> Fix `BalanceOperationSuite` tests

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
Add comments for `ContractGetBytecodeHandler`.
Fixes #8945 
Following up on PR #8905 [this comment](https://github.com/hashgraph/hedera-services/pull/8905#discussion_r1341565991)
> Add comments for `ContractGetBytecodeHandler`

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncInputStream.java
Closes #8984 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/8985
> 08984 reconnect deadlock (#8985)

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeCopyOperationSuite.java
Fix `ExtCodeCopyOperationSuite` tests.
Fixes #8867 
Just enabled `verifiesExistence` test.
> Fix `ExtCodeCopyOperationSuite` tests

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/config/HederaNumbers.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
- Cherry-picks the mono-service changes from #8986
> Cherry-pick mono changes

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/internal/SequentialWire.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/internal/Task.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/WiringBenchmark.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/components/TopologicalEventSorter.java
2.3M TPS on Mac when run from `WiringBenchmark.main()` (in IDE or on the command line).
Related to #9005
> POC 9005: lock-free task parallelism

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/Hash.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/SerializableDataOutputStream.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/transaction/internal/StateSignatureTransaction.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/system/transaction/internal/TransactionSerializationTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/ConsensusHashManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/StartupStateUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/ConsensusHashManagerTests.java
backport from develop of https://github.com/hashgraph/hedera-services/pull/8998
> 08816 epoch hash with sig (#8998)

- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
> Stop release 0.41 regression

- hedera-node/configuration/mainnet/bootstrap.properties
Update `ledger.id` and `chain.id` in bootstrap.properties from the changes merged by the PR https://github.com/hashgraph/hedera-services/pull/9055
> Update `ledger.id` and `chain.id` in bootstrap.properties

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/FileQueriesStressTests.java
> Resolve FileQueriesStressTests errors

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/ConsensusQueriesStressTests.java
> Resolve ConsensusQueriesStressTests errors

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/InvalidgRPCValuesTest.java
> Resolve InvalidgRPCValuesTest errors

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/PerpetualTransfers.java
> Resolve PerpetualTransfers errors

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleGetInfoHandler.java
- hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleGetInfoHandlerTest.java
- hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleHandlerTestBase.java
- hedera-node/log4j2.xml
* Added implementaiton of the ScheduleGetInfo query handler
* Added unit test for ScheduleGetInfo query handler
* Fixed a minor oversight in logging config that caused confusing output in gradle run.
Closes #8989
> Issue 8989 - Design ScheduleGetInfo query handler

- hedera-node/configuration/mainnet/application.properties
- hedera-node/configuration/mainnet/bootstrap.properties
- hedera-node/configuration/testnet/application.properties
- hedera-node/configuration/testnet/bootstrap.properties
Cherry-pick https://github.com/hashgraph/hedera-services/pull/9055
> Sync configs from file 121 in the `bootstrap.properties` and `application.properties`

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
* Added WritableScheduleStore to workflow writable store factory.
> 09046 Fix Hapi Schedule Create Spec

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowGraphSynchronizer.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncNode.java
> Fix add vs put bug

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/CryptoQueriesStressTests.java
> Resolve CryptoQueriesStressTests errors

- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleDeleteHandler.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandler.java
- hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleHandlerTestBase.java
* Fixed missing record builder calls to add schedule ID for all three schedule transactions.
* Added mock support in unit tests
> 9046 Schedule Handlers/Fix Record Builder usage.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigRequirements.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
Fixes #9058 
Fixes #9057 
Fixes `duplicateKeysAndSerialsInSameTxnDoesntThrow` and `approveForAllSpenderCanDelegateOnNFT` test
> Fix `duplicateKeysAndSerialsInSameTxnDoesntThrow` test

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CrytoCreateSuiteWithUTF8.java
> Enable tests from CrytoCreateSuiteWithUTF8

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HelloWorldSpec.java
> Enable tests from HelloWorldSpec

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFees.java
Enables all tests from the suite
Fixes #9122 
**Checklist**
> Enable tests from TransferWithCustomFees

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/StateDefinition.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/GenesisSchema.java
Fix #9230 genesis schema vmap size hints too small
> Fix #9230 genesis schema vmap size hints too small

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/GossipEventValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/GossipEventValidators.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/SignatureValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/validation/EventValidatorTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/validation/TestGossipEventValidator.java
closes #9217
https://swirldslabs.slack.com/archives/C03E8UAA2PR/p1697190394612599
> 09217 d add prev ab to state

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/congestion/MonoMultiplierSources.java
Use dummy transaction instead of empty bytes for creating `SignedTxnAccessor` in `MonoMultiplierSources` in order to stop redundant throwing & catching of exceptions [here](https://github.com/hashgraph/hedera-services/blob/0c76929438ec49a46a4c58115ed130afacda68d7/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/MiscUtils.java#L260).
Fixes #
**Checklist**
> Use dummy transaction instead of empty bytes for accessor

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
This PR resolves the last two tests in the TokenManagementSpecs, by adding additional validations. 
Fixes #
**Checklist**
> Fix `TokenManagementSpecs` KYC Tests

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/ReplaceAliasesWithIDsInOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
This PR resolves copy paste issue in the replace alias class for crypto transfers.
Fixes #
**Checklist**
> Resolve Replace Alias error in `CryptoTransferSuite`

- hedera-node/hedera-app/src/xtest/java/contract/GetApprovedXTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/getapproved/GetApprovedCall.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/getapproved/GetApprovedTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/getapproved/GetApprovedCallTest.java
Extended post dispatch checks to return matching responses with the mono service. Added additional X tests.
Fixes #
#9259 
**Checklist**
> Match Get Approved mono behaviour

- platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/SttTransactionPool.java
- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/LogMarker.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/test/LoggingTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/SignatureValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncManagerImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/SocketConnection.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/InboundConnectionHandler.java
> removed useless markers

- hedera-node/hedera-app/src/xtest/java/contract/FreezeUnfreezeXTest.java
Added X test to ensure the same response as in mono
Fixes #
#9254 #9255 
**Checklist**
> Match mono behaviour for Freeze/Unfreeze System Contract

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
> Add new tests to JTR metadata.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/SyntheticSnapshot.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java
> 08461 cli transplant state 2

- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/LogProcessor.java
> Abort html log processing if too many lines exist

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
This PR enables tests that were already fixed by some of the latests changes.
Fixes #
**Checklist**
> Enable fixed AutoAccountCreation tests

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
> Enable tests from LeakyContractTestsSuite

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
Fixes #8430 
Fixes #9343 
**Checklist**
> 8430 auto account update suite

- .github/workflows/node-zxc-build-release-artifact.yaml
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.evm-maven-publish.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.hapi.gradle.kts
- hedera-node/hapi/build.gradle.kts
- hedera-node/hedera-evm/build.gradle.kts
- Resolves issues with the Hedera EVM module publishing
- Closes #9369
> fix: resolves issues with publishing the EVM module to Maven Central

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
Disable flaky test failing with `INSUFFICIENT_TXN_FEE` until its debugged and fixed
> Disable flaky test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
> remove clear pces option

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/AssortedHcsOps.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoGetRecordsRegression.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/AllBaseOpFeesSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/OverlappingKeysSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/ContractRecordsSanityCheckSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/CryptoRecordsSanityCheckSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/HollowAccountCompletionFuzzing.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/PrivilegedOpsSuite.java
Some tests are passing now because the tested functionality was fixed independently. This PR enables them.
Closes #9454
> Enable passing tests

- hedera-node/hedera-app/src/test/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
- hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
- hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
> Disable post-upgrade stake housekeeping

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/SocketConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncInputStream.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncOutputStream.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/InboundConnectionHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/OutboundConnectionCreator.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/DummyConnection.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/OutboundConnectionCreatorTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/communication/ReadWriteFakeConnection.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/LocalConnection.java
> Compress data sent over the network.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
- platform-sdk/swirlds-common/src/test/resources/com/swirlds/common/config/export/test.properties
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
> Remove config option to disable event sig verification

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/config/ReconnectConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherSendingThread.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/LaggingTeachingSynchronizer.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/MerkleTestUtils.java
> Add an optional reconnect rate limit.

- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
> 08389 d fix flaky qt metric test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusSnapshot.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/ConsensusRoundTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/uptime/UptimeTests.java
> remove deprecated method

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/EventConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
> Remove asyncPrehandle config option

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecsStateful.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Three tests in the token service that previously failed are passing now. This PR enables them.
> Enable token service tests that are passing

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/SocketConfig.java
Related to #9553 
Needs to be cherry picked to `release/0.44`.
> Disable compression.

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/SocketConfig.java
> Disable compression. (#9554)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/InternalEventValidator.java
Very small change due to a file somehow missed in #8459
> Fix compile breakage in develop following package move of logging.

- hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
- hedera-node/hedera-token-service-impl/build.gradle.kts
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseCryptoHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/module-info.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/ParityTestBase.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/ApproveAllowanceValidatorTest.java
Fix other failing tests 
NOTE: Need to wait for CI to see if it breaks any HAPI tests
> Fix failing tests

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorian.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorianTest.java
> Make scheduled txn records queryable from `ScheduleCreate` payer account

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleTreeVisualizer.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Fix summary: direct backport of #9481 to release/0.44
Fixes: https://github.com/hashgraph/hedera-services/issues/9582
> 9582: Backport the fix for 9479 to release/0.44

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleTreeVisualizer.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Fix summary: direct backport of #9481 to release 43.
Fixes: https://github.com/hashgraph/hedera-services/issues/9584
> 9584: Backport the fix for 9479 to release/0.43

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/JvmAnchor.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ThreadConfig.java
> Add a non-daemon thread.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessor.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/9640
Fixes https://github.com/hashgraph/hedera-services/issues/9639
> Cherry-pick : Fix NPE in TokenWipe when using missing alias for an account

- hedera-node/configuration/compose/settings.txt
- hedera-node/configuration/dev/settings.txt
- hedera-node/configuration/mainnet/settings.txt
- hedera-node/configuration/preprod/settings.txt
- hedera-node/configuration/previewnet/settings.txt
- hedera-node/configuration/testnet/settings.txt
- platform-sdk/sdk/settings.txt
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/EventConfig.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/config/MetricsConfig.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/config/MetricsConfigTest.java
Cherry pick of https://github.com/hashgraph/hedera-services/pull/9341
Fixes #9340 for release 44
**Checklist**
> Make platform mainnet settings the default (#9341)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/EventSignatureValidator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/EventDeduplicatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/EventSignatureValidatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/InOrderLinkerScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/InternalEventValidatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/LinkedEventIntakeScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/EventSignatureValidatorTests.java
> Create wiring objects for intake components

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
This PR adds meta data entry for tests which exist but do not have meta data.  Most of the new entries were from renamed tests.   These renamed entries are left with the same notion page and occur just below the entry with the previous name.  The older test names can be removed from the file when the all pending release versions no longer have jrs tests with the old test names. 
Fixes #9614
> Adding JRS Test Meta Data

- .github/workflows/node-flow-deploy-adhoc-artifact.yaml
- .github/workflows/node-flow-deploy-release-artifact.yaml
- .github/workflows/node-zxc-build-release-artifact.yaml
> chore: publish release artifacts to the public CDN

- .github/workflows/node-zxc-build-release-artifact.yaml
- Fixes the issue (missing curly brace) discovered in the changeset for #9691
- #9691
> fix: issue with workflow due to missing brace

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/JrsTestReportGenerator.java
> Fixed JTR bug.

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> Fix flaky wiring test.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
> Remove stale data from JTR metadata file.

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
Fixes comment
Fixes #9717
**Checklist**
> Fixed typo in BlockRecordManagerImpl.java comments

- hedera-node/hedera-app/build.gradle.kts
Fixes a hang in the `modrun` startup
> Update modrun mainClass to correct file

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/ByteConstants.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectUtils.java
> reconnect end msg

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Fix transfer tests for fees in LeakyContractTestsSuite
Fixes #9400
**Checklist**
> Fix transfer tests for fees in LeakyContractTestsSuite

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/utils/JtrUtils.java
> Throw if gsutil not installed

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/StartupStateUtilsTests.java
Closes #9808 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/9809
> Copy the PCES into saved state directories. (#9809)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherSendingThread.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/BlockingResourceProvider.java
- platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTest.java
- platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectController.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTeacher.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/LaggingTeachingSynchronizer.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/MerkleTestUtils.java
Backport of the changes from https://github.com/hashgraph/hedera-services/pull/9741
> Remove reconnect abort

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
Enable 2 more tests in Create2OperationSutie
Fixes #9394
**Checklist**
> Create2OperationSuite - enable 2 more tests #9394

- .github/workflows/node-flow-fsts-daily-interval-01.yaml
One more place where gradle cache credential was missing
> Add missing gradle cache credential

- hedera-node/infrastructure/grafana/dashboards/production/platform/data-on-disk.json
This PR adds a data on disk dashboard, which was created by @jasperpotts, @artemananiev and myself.
> Add data on disk dashboard

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/PhaseTimer.java
> Mirror fractional time usage in phase timer

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/TaskScheduler.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/input/BindableInputWire.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/input/InputWire.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/output/OutputWire.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/benchmark/WiringBenchmark.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/model/ModelTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/ConcurrentTaskSchedulerTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/DirectTaskSchedulerTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/transformers/TaskSchedulerTransformersTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/EventDeduplicatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/EventSignatureValidatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/InOrderLinkerScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/InternalEventValidatorScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/LinkedEventIntakeScheduler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/OrphanBufferScheduler.java
> Cleaner generics for input wires.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/PreconsensusEventFileRenamed.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
Closes #9883 
Cherry pick of https://github.com/hashgraph/hedera-services/pull/9890
> Fix race condition in PCES file copy. (#9890)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/DirectSchedulerChecks.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/ModelVertex.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringFlowchart.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/model/ModelTests.java
> Add logic for detection of illegal direct scheduler use.

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/FCMTransactionPool.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedMapUtils.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PttTransactionPool.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/Triple.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/transaction/handler/VirtualMerkleTransactionHandler.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/transaction/pool/VirtualMerkleTransactionPool.java
- platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/merkle/map/FCMTransactionUtilsTest.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/crypto/CryptographyTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileReader.java
Fixes [#9901](https://github.com/hashgraph/hedera-services/issues/9901)
> Triple removed from base

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/BestEffortPreconsensusEventFileCopy.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
Related to #10054 and #10053 
Needs to be cherry picked into `release/0.44`.
> Fix PCES copy bugs.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/BestEffortPreconsensusEventFileCopy.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
> Fix PCES copy bugs. (#10057)

- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/PlatformCli.java
- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/utility/PlatformCliPreParser.java
> Add PCLI bootstrap argument.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
> Refactor extract receiver logic

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateMap.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateReference.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/ReservedSignedStateTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/signed/SignedStateNexusTest.java
closes #9954
original PR #9959
comment from original PR: https://github.com/hashgraph/hedera-services/pull/9959#issuecomment-1818485177
@cody-littley I hacked the signed state reservation a bit, we should discuss this
> cherry picked nexus

- hedera-dependency-versions/build.gradle.kts
Upgrade PBJ to 0.7.7. This is a follow up for https://github.com/hashgraph/pbj/pull/109
Fixes #10090
> 10090 Upgrade PBJ to 0.7.7

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
- Cherry picks the changes from https://github.com/hashgraph/hedera-services/commit/e69d0a917c1c0a9417a3f335129a74ac3004b7c9 to the `develop` branch.
- Closes #10124
> Cherry-pick NFT allowance check on auto-creation

- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
add additional 2 tests to ScheduleCreateSpecs
Fixes #9932
> add additional 2 tests to ScheduleCreateSpecs

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/orphan/OrphanBufferTests.java
> Add pause unit test

- .github/workflows/config/node-release.yaml
> chore: Schedule release branch creation for 0.45

- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/zxc-jrs-regression.yaml
- Uses the pull request base branch as the fallback if there is not matching feature branch in the JRS repository.
- Closes #10191
> chore: use the pull request base branch as a fallback

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
Change `HashMap` to `LinkedHashMap` in custom fees assessment to fix ISS in CI.
> chore: Change `HashMap` to `LinkedHashMap` in custom fees assessment

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/PcesCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/PcesCompactCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventUtilities.java
Related to #10256 
Needs to be cherry picked to 0.45
> fix: Compact last PCES file at boot time

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
Enable the sync++- gossip algorithm. Closes #10259
> feat: sync++-

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
> fix: fix failing PCES unit test.

- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts
> build: do not publish test fixtures (release/0.44)

- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts
> build: do not publish test fixtures (release/0.45)

- .github/workflows/node-flow-fsts-daily-interval-01.yaml
- .github/workflows/node-flow-fsts-daily-regression.yaml
DevOps team suggested no longer support Ubuntu1804
> chore(ci): drop upgrade test support for Ubuntu 18.04

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/JrsTestReportGenerator.java
> feat: make branch more visually distinct in JTR report.

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
Cherry pick #10348 into release/0.45
Fixes #10346
> chore: Cherry pick #10348

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC20ContractInteractions.java
Fixes suite test flow in `Erc20ContractInteractions`
Fixes #10250 #10374 
**Checklist**
> fix: `Erc20ContractInteractions` suite test

- .github/workflows/flow-node-performance-tests.yaml
Previously parameter order is incorrect
> chore(ci): change order of cluster parameter 

- build-logic/project-plugins/build.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
See: https://github.com/gradlex-org/extra-java-module-info/pull/89
Fixes one of the issues discovered through #10347
> build: update 'extra-java-module-info' for reproducible Jar patching

- .github/workflows/platform-zxf-jrs-daily-interval-05.yaml
> chore: add new legacy intake tests to nightly regression

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
> fix: Flush intake prior to finishing replay

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/BootstrapConfigProviderImpl.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/FilesConfig.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeFileStoreImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/FileGenesisSchema.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
- hedera-node/hedera-file-service-impl/src/main/java/module-info.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileServiceImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableUpgradeFileStoreImplTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeFileStoreTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/schemas/GenesisSchemaTest.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/ReadableUpgradeFileStore.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
Fix to support all 10 upgrade files from 150-159
Fixes #10335
> fix: support all 10 upgrade files from 150-159

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/EntityTypeConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/HederaFunctionalityConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/MapAccessTypeConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/ProfileConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/RecomputeTypeConverter.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/SidecarTypeConverter.java
- platform-sdk/swirlds-config-extensions/build.gradle.kts
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/converters/AbstractEnumConfigConverter.java
- platform-sdk/swirlds-config-extensions/src/main/java/module-info.java
- platform-sdk/swirlds-config-extensions/src/test/java/com/swirlds/config/extensions/test/converters/AbstractEnumConfigConverterTest.java
Fixes https://github.com/hashgraph/hedera-services/issues/10320
> chore: AbstractEnumConfigConverter moved

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
Enable someErc20NegativeTransferFromScenariosPass hapi test
Fixes #10465 
**Checklist**
> fix: enable someErc20NegativeTransferFromScenariosPass hapi test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetEventCreator.java
> fix: make event creator ignore ancient events

- hedera-node/infrastructure/grafana/dashboards/production/hedera-node/arbitrary-stat-prom.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/gossip.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/hashgraph.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/merkleDb.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/networkHealth.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/reconnect.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/signedStates.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/threadsAndQueues.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/virtualMap.json
Backport of https://github.com/hashgraph/hedera-services/pull/10302
Fixes #9882 for release 45
**Checklist**
> chore: Dashboard Updates

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
closes #10484
[reconnect test run](https://swirldslabs.slack.com/archives/C03E8UAA2PR/p1702550028176069)
> fix: NPE on reconnect teacher

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
> fix: Enable HAPI test in `ERCPrecompileSuite`

- .github/workflows/node-flow-fsts-daily-interval-04.yaml
- .github/workflows/node-flow-fsts-daily-regression.yaml
> chore: Disable some reconnect and upgrade tests for coming hedera modularization

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/SavedStateController.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/TestSavedStateController.java
> chore: move saved state controller invocation

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/NoOpPreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamSequencer.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventStreamSequencerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
- closes #10508 
In support of #10024
> chore: Move sequence number to GossipEvent

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> fix: race condition in wiring unit test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
- Cherry pick of https://github.com/hashgraph/hedera-services/pull/10538
> feat: Add test setting to force ignore PCES signatures (#10538)

- settings.gradle.kts
> chore: update hapi version to 0.45.0

- hedera-node/infrastructure/docker/containers/production/jrs-ar-network-node/Dockerfile
- hedera-node/infrastructure/docker/containers/production/jrs-ar-network-node/entrypoint.sh
- hedera-node/infrastructure/docker/containers/production/jrs-network-node/Dockerfile
- hedera-node/infrastructure/docker/containers/production/jrs-network-node/entrypoint.sh
- hedera-node/infrastructure/docker/containers/production/main-network-node/Dockerfile
- hedera-node/infrastructure/docker/containers/production/main-network-node/entrypoint.sh
- Adds support for overriding the java main class to support testing of the modular Services code.
- Adds support for overriding the java classpath. (Added bonus)
- Closes #10459
> feat(docker): add support for overriding the java main class

- gradle.properties
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
- Cherry pick of https://github.com/hashgraph/hedera-services/pull/10538
> feat: Add test setting to force ignore PCES signatures to release/0.44

- platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java
> fix: removed PTT log that was failing tests.

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/PrngSystemContract.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/HtsSystemContractTest.java
Addressing comments from https://github.com/hashgraph/hedera-services/pull/10074 
Fixes https://github.com/hashgraph/hedera-services/issues/10564
> chore: Follow up - Unconditional, enriched, traced records of UtilPrng system contract calls

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/ModelManualLink.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/ModelEdge.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/StandardWiringModel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/WiringFlowchart.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/model/ModelTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
closes #10606 
[new wiring diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnYwKCgiKiIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M3t7ImdldE1pbmltdW1HZW5lcmF0aW9uTm9uQW5jaWVudCJ9fQp2NFsibGlua2VkRXZlbnRJbnRha2UiXQp2NXt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY2WyJpbk9yZGVyTGlua2VyPGJyIC8+KiJdCmVuZApzdWJncmFwaCB2N1siSW50YWtlIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjhbIkV2ZW50IFZhbGlkYXRpb24iXQp2OVsiZXZlbnREZWR1cGxpY2F0b3I8YnIgLz4qIl0KdjEwWyJldmVudFNpZ25hdHVyZVZhbGlkYXRvcjxiciAvPioiXQp2MTFbImludGVybmFsRXZlbnRWYWxpZGF0b3I8YnIgLz7igKAiXQplbmQKc3ViZ3JhcGggdjEyWyJPcnBoYW4gQnVmZmVyIl0KdjEzWyJvcnBoYW5CdWZmZXI8YnIgLz4qIl0KdjE0e3sib3JwaGFuQnVmZmVyU3BsaXR0ZXIifX0KZW5kCmVuZApzdWJncmFwaCB2MTVbIlN0YXRlIEZpbGUgTWFuYWdlbWVudCJdCnYxNnt7ImV4dHJhY3RPbGRlc3RNaW5p …
> feat: add manual link support to wiring diagram

- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/HtmlGenerator.java
- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/HtmlTagFactory.java
- closes #8303 
- closes #8296 
(rename to .html, since github won't allow me to upload that file type)
[swirlds-logs.log](https://github.com/hashgraph/hedera-services/files/13744144/swirlds-logs.log)
> feat: html improvements

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/EventCreationManagerFactory.java
> fix: add event creation throttle for new intake pipeline

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/NetworkTypeFilterOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Cherry pick additional of sanity pre-checks for `ContractCall` transactions
**Checklist**
> chore: cherry pick 10585

- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/10584
Fixes #10583
> fix: Added asserts for threads in all modifying methods (#10584)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/LatestEventTipsetTracker.java
> fix: bug when node is removed

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/StateSignatureCollectorWiring.java
> fix: bind prehandle signature transactions to correct handle

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/EventStreamManager.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/stream/EventStreamManagerTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/RecoveryTestUtils.java
> fix: rate limit spammy log

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/JrsTestReportGenerator.java
> fix: JTR tool compatible with Java 21

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/testMetadata.csv
> chore: update JTR test metadata file

- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/DefaultPlatformContext.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/context/internal/DefaultPlatformContextTest.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/CompareStatesCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditor.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/appcomm/AppCommComponentTests.java
- platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/context/TestPlatformContextBuilder.java
- platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/module-info.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
> feat: add time to the platform context

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/copy/MerkleInitialize.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
- platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleSerializationTests.java
> fix: state leak (#10690)

- .github/workflows/node-zxcron-release-fsts-regression.yaml
- .github/workflows/platform-zxcron-release-jrs-regression.yaml
No longer need to run regression on release 0.44
> ci: turn off regression for release 0.44

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleDeleteSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecStateful.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermExecutionSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermSignSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java
* Removed leftover todo comments
* Consolidated repeated/redundant string constants to ScheduleUtils class
* Consolidated shared utility functions to ScheduleUtils class
> chore: Clean up schedule HapiSpec suites

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/Tipset.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/SyncUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBook.java
> fix: node removal bug

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
> fix: Mark prehandle as complete in legacy intake pipeline

- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/NanoClock.java
- platform-sdk/swirlds-base/src/test/java/com/swirlds/base/time/NanoClockTest.java
Move NanoClock to swirlds-base project
Fixes #10593
> chore: 10593 move nanoclock to base

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
> fix: diagram commands

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/InOrderLinker.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesMetrics.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusHandlingMetrics.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookMetrics.java
- closes #10776 
Must be cherry picked into `0.46`
> fix: Solve bad metric units

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/InOrderLinker.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusHandlingMetrics.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookMetrics.java
- cherry pick of https://github.com/hashgraph/hedera-services/pull/10777
> fix: Solve bad metric units (#10777)

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleRecordSpecs.java
Improves the logic around prechecks for ContractCall transactions
> chore: cherry pick #10750

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/logging/TransactionStateLogger.java
Move all logs to DEBUG instead of INFO
> Move all logs to DEBUG instead of INFO

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/deduplication/EventDeduplicator.java
> chore: Document why the deduplicator considers signature

- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpContractStoresSubcommand.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/CongestionThrottleService.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/congestion/EntityUtilizationMultiplierTest.java
- hedera-node/hedera-app/src/xtest/java/common/AbstractXTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceImpl.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/schemas/InitialModServiceConsensusSchema.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/InitialModFileGenesisSchema.java
- hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/schemas/FileSchemaTest.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkServiceImpl.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/InitialModServiceAdminSchema.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/InitialModServiceNetworkSchema.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceImpl.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/InitialModServiceContractSchema.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ReadableContractStateStore.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableContractStateStore.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ReadableContractStateStoreTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/WritableContractStateStoreTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/SyntheticRecordsGeneratorTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/MixedOpsRestartTest.java
refactor the code to use explicit Schema and not anonymous Schema, it will allow providing an explicit sequence of specific release
It also fixes one flaky test related to record cache
Fixes #10749
> fix: refactor the code to use explicit Schema and not anonymous Schema and one flaky test

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/PerfTestLoadSettings.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithStakedAccounts.java
Test result
https://swirldslabs.slack.com/archives/C03G7CBJJ06/p1704648924328729
> fix: cherry pick fix permissions for upgrade test (#10779)

- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/HandlerLoggingLevelConfigStressTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileManagerTests.java
Temporally disabling platform flaky test
Fixes #10881
> chore: disable flaky test

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileManagerTests.java
> fix: Repair and reenable PCES File Manager test

- hedera-node/hapi/build.gradle.kts
- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiPartitionCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
**Description**
To create TokenCreatePartitionDefinition for the particular TokenId.
**The PR has the following files changes**
**Existing Files**
1. test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
2. test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
3. test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
4. hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
**New File**
1. test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiPartitionCreate.java
**Compile**
1. BUILD is SUCCESS
2. ./gradlew spotlessApply is SUCCESS
> feat(HIP796): Implement HIP-796 HapiSpecOperation primitives #9886 (createTokenPartitionDefinition only)

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/WiringFlowchart.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
Closes #10616 
[Example diagram generated with this code](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnYwKCgiQCIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M3t7ImdldE1pbmltdW1HZW5lcmF0aW9uTm9uQW5jaWVudCJ9fQp2NHt7ImdldE5vbkFuY2llbnRFdmVudFdpbmRvdyJ9fQp2NVsibGlua2VkRXZlbnRJbnRha2U8YnIgLz7imIUiXQp2Nnt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY3WyJpbk9yZGVyTGlua2VyPGJyIC8+ypgiXQplbmQKc3ViZ3JhcGggdjhbIkludGFrZSBQaXBlbGluZSJdCnN1YmdyYXBoIHY5WyJFdmVudCBWYWxpZGF0aW9uIl0KdjEwWyJldmVudERlZHVwbGljYXRvcjxiciAvPsqYIl0KdjExWyJldmVudFNpZ25hdHVyZVZhbGlkYXRvcjxiciAvPsqYIl0KdjEyWyJpbnRlcm5hbEV2ZW50VmFsaWRhdG9yPGJyIC8+4oCgIl0KZW5kCnN1YmdyYXBoIHYxM1siT3JwaGFuIEJ1ZmZlciJdCnYxNFsib3JwaGFuQnVmZmVyPGJyIC8+ypgiXQp2MTV7eyJvcnBoYW5CdWZmZXJTcGxpdHRlciJ9fQplbmQKdj …
> fix: bug with wiring diagram substitution

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/SignedStateFileManagerWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/StateSignatureCollectorWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
Improve the wiring diagram by adding more descriptive labels and grouping things together.
[Full diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnN1YmdyYXBoIHYwWyJDb25zZW5zdXMgUGlwZWxpbmUiXQpzdWJncmFwaCB2MVsiTGlua2VkIEV2ZW50IEludGFrZSJdCnYye3siZ2V0TWluaW11bUdlbmVyYXRpb25Ob25BbmNpZW50In19CnYze3siZ2V0Tm9uQW5jaWVudEV2ZW50V2luZG93In19CnY0WyJsaW5rZWRFdmVudEludGFrZTxiciAvPuKYhSJdCnY1e3sibGlua2VkRXZlbnRJbnRha2VTcGxpdHRlciJ9fQplbmQKdjZbImluT3JkZXJMaW5rZXI8YnIgLz7KmCJdCmVuZApzdWJncmFwaCB2N1siSW50YWtlIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjhbIkV2ZW50IFZhbGlkYXRpb24iXQp2OVsiZXZlbnREZWR1cGxpY2F0b3I8YnIgLz7KmCJdCnYxMFsiZXZlbnRTaWduYXR1cmVWYWxpZGF0b3I8YnIgLz7KmCJdCnYxMVsiaW50ZXJuYWxFdmVudFZhbGlkYXRvcjxiciAvPuKAoCJdCmVuZApzdWJncmFwaCB2MTJbIk9ycGhhbiBCdWZmZXIiXQp2MTNbIm9ycGhhbkJ1ZmZlcjxiciAvPsqYIl0KdjE0e3sib3JwaG …
> Cleaned up wiring diagram.

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/LinkedEventIntake.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/EventDurabilityNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/LinkedEventIntakeWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PcesWriterWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/generator/AbstractGraphGenerator.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/generator/StandardGraphGenerator.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesSequencerTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesWriterTests.java
- closes #10930 
- closes #10887 
- [diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnYwKCgiQCIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M3t7ImdldE5vbkFuY2llbnRFdmVudFdpbmRvdyJ9fQp2NFsibGlua2VkRXZlbnRJbnRha2U8YnIgLz7imIUiXQp2NXt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY2WyJpbk9yZGVyTGlua2VyPGJyIC8+ypgiXQplbmQKc3ViZ3JhcGggdjdbIkludGFrZSBQaXBlbGluZSJdCnN1YmdyYXBoIHY4WyJFdmVudCBWYWxpZGF0aW9uIl0KdjlbImV2ZW50RGVkdXBsaWNhdG9yPGJyIC8+ypgiXQp2MTBbImV2ZW50U2lnbmF0dXJlVmFsaWRhdG9yPGJyIC8+ypgiXQp2MTFbImludGVybmFsRXZlbnRWYWxpZGF0b3I8YnIgLz7igKAiXQplbmQKc3ViZ3JhcGggdjEyWyJPcnBoYW4gQnVmZmVyIl0KdjEzWyJvcnBoYW5CdWZmZXI8YnIgLz7KmCJdCnYxNHt7Im9ycGhhbkJ1ZmZlclNwbGl0dGVyIn19CmVuZAp2MTVbLyJldmVudEhhc2hlciIvXQplbmQKc3ViZ3JhcGggdjE2WyJQcmVjb25zZW5zdX …
> fix: Implement new PCES writer flush

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
closes #10922 
[resulting legend](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnN1YmdyYXBoIHYwWyJBcmJpdHJhcnkgR3JvdXBpbmciXQp2MVtbIkNvbmN1cnJlbnRTY2hlZHVsZXIiXV0KdjJbLyJEaXJlY3RTY2hlZHVsZXIiL10KdjN7eyJEaXJlY3RTdGF0ZWxlc3NTY2hlZHVsZXIifX0KdjRbIlNlcXVlbnRpYWxTY2hlZHVsZXIiXQp2NVsiU2VxdWVudGlhbFRocmVhZFNjaGVkdWxlcjxiciAvPuKcqSJdCmVuZAp2NigoIuKcqSIpKQp2MSAtLiAibWFudWFsIGRpYWdyYW0gbGluayAobm90IGFjdHVhbGx5IGEgd2lyZSkiIC4tbyB2NAp2MiAtLSAid2lyZSB3aXRoIGJhY2twcmVzc3VyZSIgLS0+IHYzCnY0IC0tICJ3aXJlIHN1YnN0aXR1dGlvbiAoZm9yIHJlYWRhYmlsaXR5KSIgLS0+IHY2CnY1IC0uICJ3aXJlIHdpdGhvdXQgYmFja3ByZXNzdXJlIiAuLT4gdjIKY2xhc3NEZWYgczAgZmlsbDojOUNGLHN0cm9rZTojMDAwLHN0cm9rZS13aWR0aDoycHgKY2xhc3MgdjAgczAKY2xhc3NEZWYgczEgZmlsbDojZmY5LHN0cm9rZTojMDAwLHN0cm9rZS13aWR0aDoycHgKY2xhc3MgdjEsdjQsdjUgczEKY2xhc3NEZWYgczIgZmlsbDojY2NjLH …
> feat: Create command to generate a legend for framework diagrams

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/AdvancedTransformation.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/internal/AdvancedWireTransformer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/output/OutputWire.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/wires/output/internal/TransformingOutputWire.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/transformers/TaskSchedulerTransformersTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/SignedStateReserver.java
> feat: wiring offer cleanup

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
> feat: transform evm v46 checks to prechecks

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogic.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogicTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
> chore:  cherry pick #11013

- platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/logging/HtmlGenerator.java
- closes #11027 
Example file: (replace .txt with .html)
[swirlds-logs.txt](https://github.com/hashgraph/hedera-services/files/13969356/swirlds-logs.txt)
> fix: Improve ugly html

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
Closes #11052 
[Full diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnYwKCgiQCIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M3t7ImdldE5vbkFuY2llbnRFdmVudFdpbmRvdyJ9fQp2NFsibGlua2VkRXZlbnRJbnRha2U8YnIgLz7imIUiXQp2NXt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY2WyJpbk9yZGVyTGlua2VyPGJyIC8+ypgiXQplbmQKc3ViZ3JhcGggdjdbIkludGFrZSBQaXBlbGluZSJdCnN1YmdyYXBoIHY4WyJFdmVudCBWYWxpZGF0aW9uIl0KdjlbImV2ZW50RGVkdXBsaWNhdG9yPGJyIC8+ypgiXQp2MTBbImV2ZW50U2lnbmF0dXJlVmFsaWRhdG9yPGJyIC8+ypgiXQp2MTFbImludGVybmFsRXZlbnRWYWxpZGF0b3I8YnIgLz7igKAiXQplbmQKc3ViZ3JhcGggdjEyWyJPcnBoYW4gQnVmZmVyIl0KdjEzWyJvcnBoYW5CdWZmZXI8YnIgLz7KmCJdCnYxNHt7Im9ycGhhbkJ1ZmZlclNwbGl0dGVyIn19CmVuZAp2MTVbLyJldmVudEhhc2hlciIvXQplbmQKc3ViZ3JhcGggdjE2WyJQQ0VTIl0KdjE3Wy8iZXZlbnREdXJhYm …
> fix: pcli diagram

- hedera-dependency-versions/build.gradle.kts
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/AccountStateTranslator.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/DataBufferTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/ActionsHelper.java
- settings.gradle.kts
This PR upgrades PBJ version to 0.7.12
Fixes #11042 
Relates to https://github.com/hashgraph/pbj/issues/174
> fix: 11042 Upgraded PBJ version to 0.7.12

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/ConsensusConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/MinGenInfo.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/MinGenInfoTests.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/PlatformDataTests.java
> chore: MinGenInfo serialization cleanup

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/LinkedEventIntake.java
> fix: let shadowgraph be responsible for all unlinking

- .github/CODEOWNERS
- .remarkrc
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.java.gradle.kts
- config/checkstyle/checkstyle-suppressions.xml
- config/checkstyle/checkstyle.xml
- config/detekt/detekt.yml
- config/pmd/ruleset.xml
- Adds configuration files for the tools below in preparation for a transition to Codacy.
- Remark Lint
- PMD
- Detekt
- CheckStyle
- Updates the `CODEOWNER` definitions to include the added files.
- Adds CheckStyle support to Gradle.
- Closes #11117
> chore: add tool configuration files to support Codacy reporting

- .github/workflows/node-flow-build-application.yaml
- .github/workflows/node-flow-pull-request-checks.yaml
- .github/workflows/node-zxc-compile-application-code.yaml
- Updates the CI pipelines to invoke the Codacy code coverage uploader.
- Closes #11118
> ci(codacy): enable Codacy coverage reporting

- hedera-node/docs/design/services/smart-contract-service/evm-versioning.md
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_46Module.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v046/V046Module.java
In v46 of the EVM use the Journaled Updater.
Also, update tests to better reflect that EvmConfiguration is injected.
Fixes #8340 in v0.46 EVM
The v0.46 EVM was done concurrently and didn't pick up the new config changes in the dagger injector. This addresses that workflow issue.
**Checklist**
> feat: Use Journaled EVM Updater

- hedera-node/docs/design/services/smart-contract-service/evm-versioning.md
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_46Module.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/v046/V046Module.java
Uses Journaled EVM updater in v046 EVMs.
Cherry pick of #11171 
Fixes #8340 in release 46 branch
**Checklist**
> feat: Use Journaled EVM Updater (0.46)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ParseExceptionWorkaround.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableStateTest.java
This PR moves the warming of the cache to a virtual thread.
Closes #11215
> perf: Execute each cache warming on individual virtual thread

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/WiringFlowchart.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/diagram-commands.txt
closes #11226 
[resulting diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IFRECnYwKCgiQCIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M1sibGlua2VkRXZlbnRJbnRha2U8YnIgLz7imIUiXQp2NHt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY1KCgiZyIpKQp2NlsiaW5PcmRlckxpbmtlcjxiciAvPsqYIl0KZW5kCnN1YmdyYXBoIHY3WyJHb3NzaXAiXQp2OHt7Imdvc3NpcCJ9fQp2OVsic2hhZG93Z3JhcGg8YnIgLz5nypgiXQplbmQKc3ViZ3JhcGggdjEwWyJJbnRha2UgUGlwZWxpbmUiXQpzdWJncmFwaCB2MTFbIkV2ZW50IEhhc2hpbmciXQp2MTJbWyJldmVudEhhc2hlciJdXQp2MTNbInBvc3RIYXNoQ29sbGVjdG9yIl0KZW5kCnN1YmdyYXBoIHYxNFsiRXZlbnQgVmFsaWRhdGlvbiJdCnYxNVsiZXZlbnREZWR1cGxpY2F0b3I8YnIgLz7KmCJdCnYxNlsiZXZlbnRTaWduYXR1cmVWYWxpZGF0b3I8YnIgLz7KmCJdCnYxN1siaW50ZXJuYWxFdmVudFZhbGlkYXRvcjxiciAvPuKAoCJdCmVuZAp2MThbIk9ycGhhbiBCdWZmZXI8YnIgL …
> feat: clean up wiring diagram

- .gitignore
- build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.hapi.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com/hedera/hashgraph/gradlebuild/tasks/GitClone.kt
- hedera-node/hapi/build.gradle.kts
After #9651, we now fully control the `git` commands that clone and update `hedera-protobufs` and can now:
- do the clone in a task instead of (always) during Gradle configuration
- clone into a subfolder of `build`, so `gradle clean` will clean it up as well
**Checklist**
> build: perform git clone/update of 'hedera-protobufs' in a task

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
This PR turns `HandleWorkflow` and `QueryWorkflowImpl` into Singletons as originally intended.
> perf: Turn workflows into Singletons

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
See https://github.com/hashgraph/hedera-services/issues/10698
With https://github.com/hashgraph/hedera-services/pull/10701, the following use case was fixed:
1. Create a hollow account through a transfer to EVM address not linked to any existing account
2. Delete the account with a CryptoDeleteTransaction
3. Create a new account with the same alias through a new transfer to the EVM address ✅ 
but this use case is not working as expected:
1. Create account with CryptoCreateTransaction and assign an alias to the newly created account
5. Delete the account with a CryptoDeleteTransaction
6. Create a new account with the same alias - results in `ALIAS_ALREADY_ASSIGNED`, should be `SUCCESS` ❌ 
Fixes #11221
**Checklist**
> test: unlinking of alias is not working as expected

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/StandardWiringModel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/benchmark/WiringBenchmark.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/model/ModelTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/HeartbeatSchedulerTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulersConfig.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/SignedStateReserverTest.java
- platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/TestWiringModelBuilder.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
> fix: platform should not use common fork join pool

- platform-sdk/swirlds-base/src/testFixtures/java/com/swirlds/base/test/fixtures/concurrent/internal/ConcurrentTestSupport.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggingSystemStressTest.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
> fix:  Fix flaky parallel tests

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
Move schema definition of tokens on disk
Closes #11271
> perf: Move token on disk

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
Replace usage of Executors.newVirtualThreadPerTaskExecutor() with simple static Runnable.
Closes #11299
> perf: Avoid excessive creation of Executors

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/MiscSpeedometers.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ServicesStatsConfig.java
> fix: 11305: failing application metrics

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/counters/BackpressureObjectCounterTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> fix: rejected execution in wiring framework

- hedera-node/hapi/build.gradle.kts
- settings.gradle.kts
Update protobuf version for release 0.47 branch
> chore: Update protobuf version

- hedera-node/configuration/testnet/upgrade/throttles.json
This change will relax testnet throttles for a few days so people can reconfigure testnet following their upgrade.
> chore: Update throttles.json

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/locks/IndexLockTests.java
> fix: broken unit test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventHasherWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PostHashCollectorWiring.java
- closes #11367 
**MUST BE CHERRY PICKED INTO RELEASE `0.47`**
> fix: Modify where components look to indicate overloaded intake

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventHasherWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/PostHashCollectorWiring.java
- cherry pick of https://github.com/hashgraph/hedera-services/pull/11369
> fix: 11367 Use correct measure for intake backpressure

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStoreTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
> fix: Return invalid token even if expected decimals are present (#11342)

- hedera-node/hapi/build.gradle.kts
- settings.gradle.kts
Update protobuf version on develop
> chore: Update protobuf version on develop

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/QueryMethod.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/impl/QueryMethodTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/impl/TransactionMethodTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/WritableTopicStore.java
This PR fixes metric names that are generated.
Closes #11417
> fix: Fix generated metric names

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/DurationGauge.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultDurationGaugeTest.java
> fix: 11391adapting DurationGauge naming to conventions

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/CustomCallOperation.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameBuilder.java
Cherry pick #11244
Fixes #
**Checklist**
> chore: Cherry pick fix: contracts.evm.allowCallsToNonContractAccounts flag misbehaviour

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> fix: Increase wait for squelch test assertion

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
> chore: add debug info

- hedera-node/infrastructure/grafana/dashboards/production/platform/consensusRoundHandling.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/eventCreation.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/gossip.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/hashgraph.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/intakePipeline.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/multiAnyStatAndStatus.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/networkHealth.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/reconnect.json
- hedera-node/infrastructure/grafana/dashboards/production/platform/threadsAndQueues.json
- closes #11531 
For reviewers: the dashboard changes can be examined in preprod grafana
> feat: Create new status panel, and add to existing dashboards

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
> fix: reduce sync permit count

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/engine/CryptoEngine.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/crypto/engine/IntakeDispatcher.java
> fix: make verifyAsync() a passthrough method to the executor service

- platform-sdk/swirlds-jasperdb/src/hammer/java/com/swirlds/merkledb/files/CloseFlushTest.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/DataSourceValidatorTest.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
- platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/map/MapTest.java
- platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/RecordAccessorImplTest.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java
- platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
- platform-sdk/swirlds-virtualmap/src/testFixtures/java/com/swirlds/virtualmap/test/fixtures/InMemoryDataSource.java
> fix: 11498 Fix MapTest.

- config/checkstyle/checkstyle-suppressions.xml
- config/checkstyle/checkstyle-xpath-suppressions.xml
- config/checkstyle/checkstyle.xml
- Updates the CheckStyle configuration to more closely align to the SL/Hedera standards.
- Partial of #11590
> chore: tune checkstyle config

- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/context/Context.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/function/BooleanFunction.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/function/CheckedConsumer.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/function/CheckedFunction.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/state/LifecycleException.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/state/Mutable.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/NanoClock.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/Time.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/units/UnitConstants.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Pair.java
- platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/ToStringBuilder.java
- Addresses Codacy SAST detections in the `swirlds-base` module. 
- Partial of #11590
> chore: resolve check style detections in the swirlds-base module

- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/Configuration.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/ConfigurationBuilder.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/converter/ConfigConverter.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/intern/ConfigurationProvider.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/source/ConfigSource.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigPropertyConstraint.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigValidator.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigViolation.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigViolationException.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/PropertyMetadata.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/annotation/ConstraintMethod.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/annotation/Max.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/annotation/Min.java
- Addresses Codacy SAST detections in the `swirlds-config-api` module. 
- Partial of #11590
> chore: resolve check style detections in the swirlds-config-api module

- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/export/ConfigExport.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/package-info.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/reflection/ConfigReflectionUtils.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/AbstractConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/ConfigMapping.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/LegacyFileConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/MappedConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/SimpleConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/SystemEnvironmentConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/SystemPropertiesConfigSource.java
- platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/validators/DefaultConfigViolation.java
- Addresses Codacy SAST detections in the `swirlds-config-extensions` module. 
- Partial of #11590
> chore: resolve check style detections in the swirlds-config-extensions module

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/DirectSchedulerChecks.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/StandardVertex.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/WiringFlowchart.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerType.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/internal/DirectTaskScheduler.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/WireFilter.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/WireListSplitter.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/WireTransformer.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/internal/AdvancedWireTransformer.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/model/ModelTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/DirectTaskSchedulerTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulers.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventWindowManagerWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/GossipWiring.java
> chore: rename DIRECT_STATELESS to DIRECT_THREADSAFE

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/WiringFlowchart.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/generate-platform-diagram.sh
- closes #11692 
Unfortunately, the elk renderer is still experimental, and subgraph colors don't work correctly. Still, the better organized graph is worth the worse colors. Hopefully the color problem will be fixed at some point
Using elk allowed me to use fewer substitutions for the chart. I also subbed in emojis instead of symbols for the necessary substitutions, to be easier to follow.
[diagram using elk](https://mermaid.ink/svg/JSV7aW5pdDogeydmbG93Y2hhcnQnOiB7J2RlZmF1bHRSZW5kZXJlcic6ICdlbGsnfX19JSUKZmxvd2NoYXJ0IFRECnYwWy8iQ29uc2Vuc3VzIEV2ZW50IFN0cmVhbSIvXQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0KdjJbIkNvbnNlbnN1cyBFbmdpbmUiXQp2M1siaW5PcmRlckxpbmtlcjxiciAvPvCfjIAiXQp2NCgoIvCfjIAiKSkKdjUoKCLwn5OsIikpCnY2KCgi8J+avSIpKQplbmQKc3ViZ3JhcGggdjdbIkV2ZW50IENyZWF0aW9uIl0KdjhbImV2ZW50Q3JlYX …
> feat: use elk renderer for mermaid diagrams

- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/AbstractLogPayload.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkUtils.java
> fix: print illegal payload messages

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/CacheWarmer.java
This PR implements two small performance improvements:
- Cache index lookup
- Warm payer account
> perf: Minor performance improvements

- hedera-node/hedera-app/src/xtest/java/README.md
Add a README file to the xTests directory to help motivate its purpose and provide a general description of how and when they should be added.
Fixes #11680
> chore: Add README file to explain xTests

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/InternalEventValidator.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/validation/InternalEventValidatorTests.java
> fix: stop checking for minimum birth round

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/RoundCalculationUtils.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/ChatterCore.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/State.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadataField.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/consensus/RoundCalculationUtilsTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterCoreTests.java
> feat: make the state compatible with birth rounds

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformSchedulers.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/LatestCompleteStateNotifierWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/generate-platform-diagram.sh
[new wiring diagram](https://mermaid.ink/svg/JSV7aW5pdDogeydmbG93Y2hhcnQnOiB7J2RlZmF1bHRSZW5kZXJlcic6ICdlbGsnfX19JSUKZmxvd2NoYXJ0IFRECnYwWy8iQ29uc2Vuc3VzIEV2ZW50IFN0cmVhbSIvXQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0KdjJbIkNvbnNlbnN1cyBFbmdpbmUiXQp2M1siaW5PcmRlckxpbmtlcjxiciAvPvCfjIAiXQp2NCgoIvCfjIAiKSkKdjUoKCLwn5OsIikpCnY2KCgi8J+avSIpKQplbmQKc3ViZ3JhcGggdjdbIkV2ZW50IENyZWF0aW9uIl0KdjhbImV2ZW50Q3JlYXRpb25NYW5hZ2VyPGJyIC8+4p2k77iP8J+MgCJdCnY5WyJmdXR1cmVFdmVudEJ1ZmZlcjxiciAvPvCfjIAiXQp2MTB7eyJmdXR1cmVFdmVudEJ1ZmZlclNwbGl0dGVyIn19CnYxMVsvInRyYW5zYWN0aW9uUG9vbCIvXQp2MTIoKCLwn42OIikpCmVuZApzdWJncmFwaCB2MTNbIkV2ZW50IEhhc2hpbmciXQp2MTRbWyJldmVudEhhc2hlciJdXQp2MTVbInBvc3RIYXNoQ29sbGVjdG9yIl0KZW5kCnN1YmdyYXBoIHYxNlsiRXZlbnQgVmFsaWRhdGlvbiJdCnYxN1siZXZlbnREZWR1cGxpY2F0b3I8YnIgLz7wn4yAIl0KdjE4WyJ …
> feat: diagram tweaks

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
> fix: consensus test flake

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/SpanMapManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/span/SpanMapManagerTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleSystemContractOperations.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersCall.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/Erc20TransfersCall.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc20TransfersCallTest.java
> fix: fix ERC-20 log events and custom fee calculations (#11789)

- hedera-node/docs/design/services/smart-contract-service/atomic-crypto-transfer.md
The design doc for atomic crypto transfer included a positive test which is not possible.  Remove this test case.
> chore: update design doc for atomic crypto transfer

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/internal/ConcurrentTask.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/tasks/AbstractTask.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
> fix: 11636 VirtualHasher performance improvements (#11787)

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/FutureEventBuffer.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/FutureEventBufferTests.java
cherry pick of https://github.com/hashgraph/hedera-services/pull/11875
closes #11872
> fix: bug in future event buffer

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/StaticSoftwareVersion.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/events/BaseEventHashedData.java
> fix: properly handle services software version migration

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/counters/BackpressureObjectCounterTests.java
> fix: flaky backpressure unit test

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
> fix: fixed diff test issue 11952

- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTest.java
added unit tests to validateTopLevelAllowances()
Fixes #
**Checklist**
> chore: cherry pick pr 11944, added unit tests to validateTopLevelAllowances()

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
cherry-pick fixed diff test issue 11952 (#11965)
Fixes #
**Checklist**
> fix: cherry-pick fixed diff test issue 11952 (#11965)

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/schemas/InitialModServiceConsensusSchema.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java
Cherry-pick that moves topics and schedules on disk
> perf: Move remaining in-memory maps on disk (#11974)

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/counters/BackpressureObjectCounterTests.java
> fix: bug in backpressure test

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/nexus/DefaultLatestCompleteStateNexus.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/nexus/LatestCompleteStateNexus.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSignatureCollectorTester.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/nexus/SignedStateNexusTest.java
> feat: Extract interface from `LatestCompleteStateNexus`

- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggerImplTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggingSystemTest.java
Temporally disabling console writing tests
Fixes #12032
> fix: 12032 temporally disable log tests

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/ComponentWiring.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/InputWireLabel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/SchedulerLabel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/internal/InputWireToBind.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/internal/TransformerToBind.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/internal/WiringComponentProxy.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/WireTransformer.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/WiringComponentPerformanceTests.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/WiringComponentTests.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
> feat: automatic transformers

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/tipset/TipsetEventCreator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/FutureEventBufferWiring.java
closes #12063 
Fix in 48: https://github.com/hashgraph/hedera-services/pull/12065
> fix: future event buffer bug

- .github/workflows/node-zxc-build-release-artifact.yaml
- Cherry Pick from #12088 
- Closes #12087
> fix(ci): issue with improperly generated artifact file names

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/ComponentWiring.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/ComponentWiringTests.java
> feat: wiring proxy splitters

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/metric/HandleWorkflowMetrics.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowMetricsTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
This PR add the `gasPerConsSec` metric to modular code.
> feat: Add gasPerConsSec metric

- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/api/internal/LoggingSystem.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/HandlerLoggingLevelConfigTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LevelTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LogLevelTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggersTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/api/internal/LoggingSystemTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/api/internal/format/EpochFormatUtilsTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/legacy/LoggingTests.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/util/HandlerLoggingLevelConfigTestOrchestrator.java
- platform-sdk/swirlds-logging/src/testFixtures/java/com/swirlds/logging/test/fixtures/internal/LoggerMirrorExtension.java
- platform-sdk/swirlds-logging/src/testFixtures/java/com/swirlds/logging/test/fixtures/internal/LoggingMirrorImpl.java
> fix: 12032 Handle Log framework System.err output in tests

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java
- settings.gradle.kts
This is the cherry-pick of #12091
Closes #12090
> fix: create sidecar metadata before writing RecordStreamFile footer #12091

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/ComponentWiring.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/internal/FilterToBind.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/transformers/WireFilter.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/ComponentWiringTests.java
> feat: proxy filter

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/allowance/GetAllowanceCall.java
- Closes #12127 
- Whenever returning a `COMPLETED_SUCCESS` precompile result from the `AllowanceCall`, encode a length-2 tuple.
- Previously mirror node acceptance test would revert when calling [this method](https://github.com/hashgraph/hedera-mirror-node/blob/e4a28be9d61a3d40280dfe628bb992614adab2af/hedera-mirror-test/src/test/resources/solidity/contracts/EstimatePrecompileContract.sol#L370) with a non-fungible token type using a non-static call.
> fix: encode zero allowance in success response for non-fungible token

- platform-sdk/swirlds-cli/install.sh
- platform-sdk/swirlds-cli/pcli.sh
> feat: install script for pcli

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
Related to https://github.com/hashgraph/hedera-services/issues/11582
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12109
> fix: (mod-service) Fix a case for identifying `RESTART` scenario

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/component/ComponentWiring.java
- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/component/ComponentWiringTests.java
> feat: transform/filter on split proxy output

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/allowance/GetAllowanceCall.java
> fix: always encode length-2 output for `AllowanceCall` success

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/allowance/GetAllowanceCall.java
> fix: re-cherry-pick allowance fix

- hedera-node/hapi/build.gradle.kts
Update to use main protobufs branch
> chore: Update to use main protobufs branch

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/StateDumper.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/accounts/AccountDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/accounts/HederaAccount.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/utils/ThingsToStrings.java
Cherry-pick of #11489 
Fixes #10990
> feat: Cherry-pick: Enhance account store dumper to handle modular representation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/tokentypes/Token.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/tokentypes/TokenTypesDumpUtils.java
- hedera-node/hedera-mono-service/src/main/java/module-info.java
Cherry-pick of #11543 
Fixes #10992
> feat: Cherry-pick: Enhance token (type) dumper to handle modular representation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/scheduledtransactions/ScheduledTransaction.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/scheduledtransactions/ScheduledTransactionId.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/scheduledtransactions/ScheduledTransactionsDumpUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
Cherry-pick of #11524 
Fixes: #11197
> feat: Cherry-pick: scheduled txs modularization signed state dumper

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> fix: back pressure test flake

- hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureVerificationFutureImplTest.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
> fix: (cherry-pick) `numPositiveBalances` mgmt 

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/topics/Topic.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/topics/TopicDumpUtils.java
Cherry pick of #11601 
Fixes #10919
> feat: Cherry Pick: Enhance topics store dumper to handle modular representation

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTestDefinitions.java
Cherry-pick of #11817 
Fixes #11791
> fix: cherry-pick: consensus test flake

- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpBlockInfoSubcommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpCongestionSubcommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpPayerRecordsSubcommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStakingInfoSubcommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStakingRewardsSubcommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpStateCommand.java
- hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/BlockInfoAndRunningHashes.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/BlockInfoDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/Congestion.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/CongestionDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/PayerRecord.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/PayerRecordsDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/StakingInfo.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/StakingInfoDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/StakingRewards.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/singleton/StakingRewardsDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/utils/ThingsToStrings.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheService.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleNetworkContext.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
Cherry-pick of #11275 
Fixes #10999
> fix: Cherry-pick: add singleton stores mono and modular representation

- platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/api/internal/format/ShrinkableSizeCache.java
> feat: ShrinkeableSizeCache Should use BaseExecutor

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/StateDumper.java
> feat: State dumper final changes (#12092)

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesBirthRoundMigrationTests.java
Fixes #12250
Develop currently fails to compile without this fix.
> refactor: fix compilation of unit test.

- platform-sdk/swirlds-logging/build.gradle.kts
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LogLevelTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggerImplTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggersTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/LoggingSystemStressTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/api/internal/LoggingSystemTest.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/legacy/LoggingTests.java
- platform-sdk/swirlds-logging/src/test/java/com/swirlds/logging/util/LoggingTestUtils.java
- platform-sdk/swirlds-logging/src/testFixtures/java/com/swirlds/logging/test/fixtures/InMemoryHandler.java
- platform-sdk/swirlds-logging/src/testFixtures/java/module-info.java
> chore: Refactoring logging tests

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
Cherry-pick of https://github.com/hashgraph/hedera-services/pull/12261
> fix: Implement modular freeze time (develop)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
Related to #8530 
This fixes a hashchain issue we encountered in mono code awhile back.
> fix: Implement modular freeze time

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/stream/EventStreamManager.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventStreamManagerWiring.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/stream/EventStreamManagerTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/RecoveryTestUtils.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java
> refactor: move EventStreamManager to Platform Core

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/CongestibleThrottle.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/NetworkUtilizationManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleMetrics.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleServiceManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleServiceModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleMetricsTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleServiceManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
This PR adds throttle metrics similar to what we had in mono code.
Fixes #11558
> feat: throttle metrics

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/GenesisAccountRecordBuilder.java
> fix: set `SUCCESS` status in genesis records (#12038)

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/Validations.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
Fixed expected 'INVALID_ALLOWANCE_SPENDER_ID', got 'INVALID_ACCOUNT_ID' error on diff test 11885
Fixes #11885
**Checklist**
> fix: fixed diff test 11885

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Cherry-pick of  #12207 
Fixes #12205
> fix: Cherry-pick: Add null check for autorenew account update

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/CongestibleThrottle.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/NetworkUtilizationManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleMetrics.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleServiceManager.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleServiceModule.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleAccumulatorTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleMetricsTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleServiceManagerTest.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
Cherry pick of #12254 
Closes #11558
> feat: Cherry-pick: throttle metrics

- hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/forensics/OrderedComparison.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoApproveAllowanceTransitionLogic.java
> fix: avoid precheck `FAIL_INVALID` for `CryptoApproveAllowance` with missing token

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/testreader/JrsTestReportGenerator.java
> fix: JTR sorting issue

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
- platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/ConfigurationBuilder.java
- platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationBuilderImpl.java
> fix: services config registration fix

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManager.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactory.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/SpanMapManager.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/LedgerBalanceChangesTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransferLogicTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManagerTest.java
- Cherry-pick mono changes from #12314
> chore: cherry-pick unified `CryptoCreate` throttle reclamation

- platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/CleanCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/CompareStatesCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramLegendCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/GenesisPlatformStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/StateEditorCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateAddressBookStateCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateManifestFileCommand.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/DefaultConfiguration.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditor.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
> fix: address book testing tool config

- hedera-node/hedera-app/src/xtest/java/common/AbstractXTest.java
- hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
This PR adds default values to the `RunninHashes` fields and init `PlatformState` in `BaseScaffoldingModule`
Fixes #12325 
**Checklist**
> fix: Xtests by passing default values to runningHashes and init platformState

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
> fix: fixed diff test issue 12355.

- hedera-node/configuration/README.md
* Tried to capture some useful info in the config readme that @rbair23 shared with me about how throttle overrides work. Probably isn't 100% right so please provide feedback to make it more accurate
> docs: update throttles section of config readme

- .github/CODEOWNERS
> chore: update code ownership of platform documentation

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StaticPlatformBuilder.java
> feat: build context first

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/schemas/InitialModServiceConsensusSchema.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12401
> fix: (cherry-pick) Fix to deterministic iteration order (#12401)

- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java
- platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbStatisticsTest.java
- platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualMapStatistics.java
Fix summary: slightly simplified version of the original fix #12390 adapted to `release/0.48`
Fixes: https://github.com/hashgraph/hedera-services/issues/12424
> fix: 12424: Backport the fix for 12388 to release 0.48

- hedera-node/configuration/dev/application.properties
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/SubmissionManagerTest.java
This PR adds extra checks to secure unchecked submits even more.
Fixes #12363
> chore: Added extra-checks to prevent unchecked submits on mainnet and testnet

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java
Fixed ConfigVersion serialization
> fix: Fix `ConfigVersion` serialization

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
related to #12441 
needs to be cherry-picked to 0.49
> fix: unsoldered wire instantiation bug

- .github/workflows/node-flow-fsts-daily-interval-01.yaml
Adding a new test panel to test removing a node from config.txt before upgrade
N/A
> ci: add new uprade test panel

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslator.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/StateDumper.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/associations/TokenAssociationsDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/contracts/ContractBytecodesDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/files/FilesDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/singleton/BlockInfoDumpUtils.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/tokentypes/TokenTypesDumpUtils.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslatorTest.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/AccountStateTranslator.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/accounts/AccountDumpUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/accounts/BBMHederaAccount.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/contracts/BBMContract.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/contracts/ContractBytecodesDumpUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/contracts/ContractUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/utils/ThingsToStrings.java
Cherry-pick #12392 
Fixes #12333
> chore: (cherry-pick) Migration fixes from state dumpers (#12392)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigMetrics.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
Cherry pick of #12200
Closes #11556
> feat: Add maximum entity count metrics (#12200)

- .snyk
> chore: Fix synk expiry

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenUpdateValidator.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenMetadataSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Fixes #12387 
Cherry-pick #12409
> fix: (cherry-pick) Fix signing requirements for updating metadata on Token (#12409)

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/AbortException.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/EthereumCallDataHydration.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java
-  Cherry-pick relevant part of #12172
> fix: don't use explicit `0.0.0` auto-renew account id in synth `ContractCreateTransactionBody`

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/version/HederaSoftwareVersionTest.java
> fix: (cherry-pick) Fix `ConfigVersion` serialization (#12439)

- .snyk
> chore: (cherry-pick) Fix synk expiry (#12477)

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/AncestorSearchTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/graph/SimpleGraphs.java
> fix: Manually set event time created in SimpleGraphs

- .github/CODEOWNERS
This PR changes the owner of the DEV configuration to the development team.
> chore: Change owner of DEV configuration

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TokenContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TriggeredFinalizeContext.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/FinalizeParentRecordHandlerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHandlerImplTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/FinalizeContext.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/ParentRecordFinalizer.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoDelete.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java
> fix: finalize stake metadata only once per transaction

- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/JvmAnchor.java
- platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/internal/StandardWiringModel.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ThreadConfig.java
> feat: move the JVM anchor into the wiring model

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractGetBytecodeHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetBytecodeSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
> fix: cherry pick 12512

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Call pureChecks() in ingest workflow
Added some catch-all handling
> fix: add pureChecks to ingest workflow

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextQueryProcessor.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmStaticTransactionFactory.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmStaticTransactionFactoryTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
Cherry pick of #12484 from release/0.48 to develop
Fixes #12313
> fix: ContractCallLocal INSUFFICIENT_GAS ERROR #12484

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
Fix possible NPE when there is no head token number to begin with
Fixes #12524
**Checklist**
> fix: tokenDissociate can fail with NullPointerException

- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
- hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageTest.java
> fix: fixed topicMessageSubmit without topicID throws unexpected NPE

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
> chore: cherry pick pause fix

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AdjustHbarChangesStep.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Fixes #12564 
- Fixes the response code returned in HbarChangesStep if the balance is insufficient for customFee
> fix: Fixes response code when failing in HbarChangesStep with custom fees

- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java
- Cherry-pick #12583 
- Closes #12516
> fix: set provided expiry on new schedule

- .github/workflows/flow-node-performance-tests.yaml
Updated performance nightly test workflow to wait less time on state loading
> chore: updated nightly test workflow state loading wait time

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
> fix: Set minimum staking to 0

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
Fixed cryptoUpdateFees.
Fixes #12509 
**Checklist**
> fix: fixed diff test issue 12509

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
Cherry-pick #12601 
Fixes #
**Checklist**
> fix: Cherry-pick: Set minimum staking to 0 (#12601)

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
Cherry-pick #12597 
Fixes #
**Checklist**
> fix: Cherry-pick: fixed diff test issue 12509 (#12597)

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
- Closes #12587 
- Catch and translate any unchecked exception thrown from `EthTxSigs.extractSignatures()`.
> fix: catch and translate `EthTxSigs` IAE

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Cherry-pick of #12535 
Closes #12532
> fix: Cherry-pick: add pureChecks to ingest workflow

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java
Cherry-pick of #12590 
Closes #12566
> fix: Cherry-pick: Enable pureChecks in TokenAssociateToAccountHandler (#12590)

- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
Cherry-pick of #12574 
Closes #12565
> fix: Cherry-pick: Add pure check to ContractDeleteHandler

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
Cherry pick of https://github.com/hashgraph/hedera-services/pull/12581
Closes https://github.com/hashgraph/hedera-services/issues/12571
> chore: Cherry-pick: unit test and add the right response code (#12581)

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileReaderTests.java
> fix: flaky PCES test

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
Fixes https://github.com/hashgraph/hedera-services/issues/12592
Implement fees for ContractCallLocalHandler
Testing:
Validated by running a test with `ContractCallLocal`
> fix: Add fees for ContractCallLocalHandler

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/records/RecordCache.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
- hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
- hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
> fix: support receipt/record queries with nonce 

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallLocalHandlerTest.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12645
> fix: (cherry-pick) Add fees for ContractCallLocalHandler

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AdjustHbarChangesStep.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFixedFees.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
Fixes #12564 
Cherry-pick #12586
> fix: (cherry-pick) Fixes response code when failing in HbarChangesStep with customFees

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/orphan/OrphanBufferTests.java
> refactor: use new test utility for Orphan Buffer tests

- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java
This PR addresses rare non-deterministic failure of `DataFileCollectionTest#merge` test. It may happen due to race of reading and compacting threads. It turned out that in some cases there _may be_ null in `DataFileReaderPbj.fileChannels` collection, and it's a valid case, we should not assume that it's never null in `DataFileReaderPbj#reopenFileChannel` method. 
Fixes #12247 
**Checklist**
> fix: 12247 Remove incorrect assert from `reopenFileChannel`

- .github/workflows/flow-node-performance-tests.yaml
reduce the time needed to load the 0.48 known state.
> chore: tuned the time to wait for state to be loaded

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuilder.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformBuildingBlocks.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/EventCreationManagerFactory.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/RandomGraph.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/topology/StaticTopology.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/RandomBuilder.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/RandomBuilderTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/StaticConnectionManagersTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/TopologyTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/reconnect/FallenBehindManagerTest.java
> feat: random builder

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncProtocol.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncStatusChecker.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/SyncMetrics.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/protocol/SyncProtocolTests.java
- cherry pick of https://github.com/hashgraph/hedera-services/pull/11429
> feat: Check platform status before syncing (#11429)

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/comparator/TokenComparators.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/comparator/TokenComparatorsTest.java
> fix: fixed diff test issue 12615

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/ChildFinalizeContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TriggeredFinalizeContext.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeChildRecordHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/ChildFinalizeContext.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
- Cherry-pick #12668 
- Closes #12667
> fix: use exact math for all summed balances

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/linking/InOrderLinkerTests.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/TestingEventBuilder.java
> refactor: Use `TestingEventBuilder` in `InOrderLinkerTests`

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Cherry-pick of #12719 
Fixes #12718
> chore: Cherry-pick: Improve HAPI test to contain only checked error

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/comparator/TokenComparators.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/comparator/TokenComparatorsTest.java
> fix: fixed diff test issue #12699

- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PcesFileReaderTests.java
> fix: PCES test flake

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseCryptoHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
Fixes https://github.com/hashgraph/hedera-services/issues/11306
Fixes https://github.com/hashgraph/hedera-services/issues/3629
Fixes https://github.com/hashgraph/hedera-services/issues/3630
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12696
> fix: (cherry-pick)Add EETs and pureChecks in few handlers (#12696)

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/statedumpers/scheduledtransactions/ScheduledTransactionsDumpUtils.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/statedumpers/scheduledtransactions/ScheduledTransactionsDumpUtils.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java
- hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImpl.java
- hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/WritableScheduleStoreImplTest.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12585
> fix: (cherry-pick) Fix schedules during replay (#12585)

- platform-sdk/docs/core/dynamic-address-book/testing/DynamicRoster-Test-Plan.md
- platform-sdk/docs/core/dynamic-address-book/testing/GreenWire-Test-Plan.md
> docs: document test plan for green wire.

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/comparator/TokenComparators.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/comparator/TokenComparatorsTest.java
Cherry-pick PR #12737 
Fixes #
**Checklist**
> fix: cherry-pick: fixed diff test issue #12699 (#12737)

- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java
> chore: fix compile issue

- hedera-node/hapi/build.gradle.kts
> chore: Update protobuf version 0.49

- hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/ContextQueryProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/ContextTransactionProcessorTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
Turn on Cancun semantics.  Also fix some unit tests that were hardcoded to v0.46.
Depends on #11698.
Fixes #12761.
**Checklist**
> feat(cancun): Enable Cancun EVM (module v0.50)

- hedera-dependency-versions/build.gradle.kts
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenAssociate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDissociate.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenFreeze.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycGrant.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenKycRevoke.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnfreeze.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/12812
> chore: Add test for validating aliases in token operations (#12812)

- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
- platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ParsedBucket.java
Fix summary: added some debug log statements to help with #12311 investigation.
> fix: 12311: HalfDiskHashMap: Unknown bucket field 2

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaLifecyclesImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/HederaLifecyclesImplTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java
Cherry-pick #12841
Fixes #12840
> fix: Update weights of newly added nodes in `updateWeight` (#12841)

- .github/CODEOWNERS
This PR enables the smart contracts team to approve e2e-tests
> chore: Enable smart contract team to approve tests

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureVerifierImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureVerifierImplTest.java
Cherry-pick of  #12881
Fixes #12237
> perf: Cherry-pick: synchronous signature verification

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/metric/HandleWorkflowMetrics.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/FinalizeParentRecordHandler.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/ParentRecordFinalizer.java
Cherry-pick of #12867 
Fixes #12594
> fix: Cherry-pick: Better handling of fatal errors in handle workflow

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
- hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
Cherry-pick main fixes from #12811
> fix: cherry-pick main fixes from #12811

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaLifecyclesImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TokenContextImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/HederaLifecyclesImplTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenContext.java
- settings.gradle.kts
> fix: manage `StakingInfos` in restart

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssDetector.java
- platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EarlySignaturesTest.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssDetectorTests.java
> refactor: Remove epochHash field access

- hedera-node/configuration/preprod/application.properties
- hedera-node/configuration/previewnet/application.properties
Update configuration to turn on atomic crypto transfer for previewnet and preprod environments.
Fixes #12822 
**Checklist**
> feat: turn on atomic crypto transfer in preprod and previewnet

- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoCreateUtils.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFixedFees.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFractionalFees.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
The purpose of this PR is to cover with tests the cases when a hollow account is fee collector for all fee types(fixed, fractional, royalty).
**Related issue(s)**: https://github.com/hashgraph/hedera-services/issues/12483
Fixes #12483 
**Checklist**
> test: add additional tests for custom fees with hollow account collector

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java
> fix: wiring test flake

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaLifecyclesImpl.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/TokenContextImpl.java
- hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/HederaLifecyclesImplTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java
- hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/TokenContext.java
- settings.gradle.kts
- Cherry-pick #12911 
- Closes #12910
> fix: implement `updateWeight()` without States API

- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/ApproveAllowanceValidator.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
- Cherry-pick additional fixes from #12811
> fix: `ApproveAllowanceValidator` NPEs

- hapi/build.gradle.kts
> refactor: Point back to protobuf main branch

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/consensus/ConsensusTests.java
> fix: write marker file on consensus exception

- hedera-dependency-versions/build.gradle.kts
- hedera-node/docs/design/services/smart-contract-service/cancun-fork-support.md
- hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperation.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/AccountTemperature.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationTest.java
- hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationV038Test.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationV038Test.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034Test.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV038Test.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationV038Test.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/CustomGasCalculator.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomCallCodeOperationTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomCallOperationTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomDelegateCallOperationTest.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/operations/CustomStaticCallOperationTest.java
1. Upgrade `CustomGasCalculator` to Cancun (from London! ages ago)
2. Upgrade BESU again to 24.3.3, just released
Fixes #12294
**Checklist**
> feat(cancun): Upgrade `GasCalculator` to Cancun and also take latest Besu EVM client

- platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/counters/BackpressureObjectCounterTests.java
> fix: disable flaky back pressure test

- hedera-node/docs/design/services/token-service/airdrops/max-auto-associations-changes.md
> docs: add design document for HIP-904 maxAutoAssociations changes

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/SyncGossip.java
> fix: Fix config bug

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountRecordsResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/file/queries/GetFileInfoResourceUsage.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountRecordsHandler.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetInfoHandler.java
Cherry-pick of the main fixes from #13020
> fix: Cherry-pick: Main fixes from #13020

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/AccountStateTranslator.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/IterableStorageManager.java
- hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/IterableStorageManagerTest.java
- hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/InitialModServiceTokenSchemaTest.java
> fix: storage link migration and management

- hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/Fees.java
- hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/consensus/queries/GetTopicInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/contract/txns/ContractUpdateResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountDetailsResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/crypto/queries/GetAccountRecordsResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/schedule/queries/GetScheduleInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/queries/GetTokenInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/queries/GetTokenNftInfoResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenAssociateResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenDissociateResourceUsage.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenUpdateResourceUsage.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/consensus/queries/GetMerkleTopicInfoResourceUsageTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/contract/txns/ContractUpdateResourceUsageTest.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
- hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/13044
> chore: Update default fees to a constant value (#13044)

- .github/workflows/config/node-release.yaml
Schedule creation of release/0.50 branch from develop
Fixes #13094
Execution time is in UTC
> chore: update release branch creation schedule for 0.50

- hedera-node/docs/design/services/token-service/airdrops/token-reject.md
> docs: add design document for HIP-904 token reject operation

- platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
> feat: add the ability to disable the running event hasher

- hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ExchangeRateManager.java
> fix: cherry-pick midnight rate management on restart (#13071)

- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Account.java
- hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/process/Dissociation.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/models/AccountTest.java
- hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/process/DissociationTest.java
- hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
- hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Cherry-pick https://github.com/hashgraph/hedera-services/pull/13104
> fix: (cherry-pick) Ignore token expiry status in TokenDissociate

- hedera-node/docs/design/services/token-service/airdrops/token-claim-airdrop.md
> docs: add design document for HIP-904 token claim airdrop transaction

- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/codec/FileServiceStateTranslator.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileHandlers.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSignatureWaiversImpl.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
- hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/InitialModFileGenesisSchema.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/FileService.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/FileServiceDefinition.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/ReadableFileStore.java
- hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/ReadableUpgradeFileStore.java
add javadoc to file service
#13120
> chore: add javadoc to file service
